// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch56 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1101,
            rows: [
                [nil, nil, 1, 2, 2, nil, nil, nil],
                [nil, 2, 2, 1, 2, nil, nil],
                [nil, 3, 1, 5, 5, 1, nil, nil],
                [1, 1, 1, 2, 1, 4, nil],
                [nil, 4, 4, 2, 4, 2, nil, nil],
                [1, 3, 1, 1, 3, 2, nil],
                [nil, nil, 1, nil, 2, nil, nil, nil],
                [nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, 2, nil, nil, 1, nil, nil],
                [nil, 5, 2, 2, nil, 2, 1, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1102,
            rows: [
                [3, nil, nil, nil, 3, 2, nil, nil],
                [6, nil, nil, 3, 3, 2, nil],
                [4, nil, nil, 2, 3, 2, 1, nil],
                [2, nil, 3, 3, 3, 2, 2],
                [2, nil, nil, 2, 3, 3, 4, nil],
                [1, nil, 2, 2, 2, 2, 2],
                [3, nil, nil, 4, 3, 1, 1, nil],
                [1, nil, nil, 4, 1, 1, nil],
                [2, nil, nil, 1, 4, 1, 4, nil],
                [4, nil, nil, 1, 3, 2, nil],
                [1, nil, nil, nil, 1, 6, nil, nil],
                [nil, nil, nil, 1, 1, 5, nil],
                [1, nil, nil, nil, 3, 1, nil, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1103,
            rows: [
                [nil, 1, 2, 2, nil, nil, 5, 5],
                [nil, 1, 2, 1, nil, nil, 2],
                [nil, 2, 1, 2, nil, nil, 1, 2],
                [nil, 2, 1, 2, nil, 4, 1],
                [nil, 1, 2, 1, nil, nil, 3, 1],
                [nil, 2, 2, 1, nil, 2, 2],
                [nil, 2, 1, 2, nil, 1, 3, 2],
                [nil, 2, 2, 1, nil, 2, 1],
                [nil, 2, 2, 1, nil, 1, 4, 4],
                [nil, 1, 2, 1, nil, 2, 1],
                [nil, 4, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1104,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 2, 2, 4, 5, nil],
                [nil, 5, 1, 3, 3, 1, 2, nil],
                [5, 5, 3, 2, 5, 5, 1],
                [nil, 2, 4, 2, 2, 1, 2, nil],
                [3, 3, 3, 1, 1, 2, 1],
                [nil, 2, 1, 2, 2, 2, 1, nil],
                [nil, 1, 4, 1, 1, 4, nil],
                [nil, 1, 1, 3, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1105,
            rows: [
                [4, nil, nil, 1, nil, 1, nil, 4],
                [4, 4, 1, nil, nil, 2, 2],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 3, 1, 1, 3, 4],
                [nil, nil, 3, nil, nil, 3, nil, nil],
                [nil, 1, 5, 2, 1, 3, 1],
                [nil, nil, 3, 2, 2, 1, 4, 1],
                [nil, nil, 3, 3, 2, 3, 2],
                [nil, nil, 2, 3, 1, 1, 1, 1],
                [nil, nil, 2, 1, 1, 2, 1],
                [nil, nil, nil, 1, 2, nil, 4, 1],
                [nil, nil, nil, 2, nil, 7, 1],
                [nil, nil, nil, 2, 1, nil, 2, 1],
                [nil, nil, nil, 1, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1106,
            rows: [
                [4, 3, 2, 3, 5, 5, 5, 5],
                [1, 2, 3, 1, 3, 3, 2],
                [2, 1, 1, 1, 1, 1, 2, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 4, 2, 3, 2, 1, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1107,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 5, nil, nil, nil, nil],
                [nil, 4, 4, 2, 3, nil, nil, 2],
                [2, 1, 1, 2, 3, nil, 1],
                [nil, 1, 3, 6, 2, nil, nil, 2],
                [1, 3, 1, 1, 2, nil, 1],
                [1, 1, 3, 1, 1, 2, 3, nil],
                [2, 2, 2, 2, 2, nil, 1],
                [2, 2, 1, 2, 3, 1, 2, nil],
                [1, 1, 1, 2, 1, nil, 1],
                [nil, 2, 2, 2, 3, nil, nil, 1],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, 1, 1, 2, 2, nil, nil, 6],
                [nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, nil, 6, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1108,
            rows: [
                [nil, nil, nil, nil, nil, 3, 2, 3],
                [nil, nil, nil, nil, 3, 1, 1],
                [nil, 3, 1, 1, 3, nil, 3, 2],
                [1, 1, 1, 2, nil, nil, nil],
                [nil, 2, 2, 1, 2, nil, 2, 3],
                [2, 2, 2, 2, nil, nil, nil],
                [4, nil, nil, nil, 1, 3, 3, 1],
                [3, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 2, 1, 3, 6],
                [6, nil, nil, nil, nil, nil, nil],
                [3, 3, 1, 1, 1, nil, 1, nil],
                [3, 3, 1, 4, 1, 4, 2],
                [2, 1, 2, 1, 5, nil, 1, nil],
                [3, 4, 3, 1, 1, 1, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1109,
            rows: [
                [nil, nil, nil, 1, 4, 1, 3, nil],
                [1, 4, 4, nil, nil, nil, 1],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [2, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, nil, 4],
                [1, nil, nil, nil, nil, nil, 4],
                [1, nil, nil, nil, 3, 3, 3, 3],
                [2, nil, nil, 1, 1, 1, 2],
                [2, nil, nil, nil, 1, 1, 2, 1],
                [1, nil, nil, 5, 1, 3, 3],
                [1, nil, nil, nil, 5, 1, 3, 1],
                [1, 3, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 1, 1, 1, 1],
                [5, 1, nil, nil, nil, nil, nil],
                [3, 1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1110,
            rows: [
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [3, nil, nil, 2, nil, nil, 5],
                [7, 2, 3, 3, 3, 3, 3, 3],
                [4, nil, nil, 5, nil, nil, 5],
                [3, 3, 1, 2, 2, 2, 2, 1],
                [1, nil, nil, 2, nil, nil, 2],
                [nil, 2, nil, 1, nil, nil, 2, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, 2, nil, 1, nil, nil, 4, nil],
                [nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1111,
            rows: [
                [1, 1, 1, 3, 4, 4, 4, 1],
                [3, 2, 1, 1, 1, 2, 3],
                [1, 4, 4, 1, 1, 5, 3, 3],
                [3, 2, 3, 2, 2, 2, 2],
                [1, 2, 5, 1, 4, 1, 2, 1],
                [1, 2, 1, 1, 2, 2, 1],
                [3, 2, 1, 1, 2, 2, 1, 2],
                [1, 2, 2, 1, 2, 5, 1],
                [4, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1112,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [1, 5, 1, 4, 1, 2, 1, 2],
                [3, nil, 1, nil, 5, nil, 5],
                [5, 2, 1, 3, 3, 1, 1, 2],
                [6, nil, 4, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1113,
            rows: [
                [nil, 2, nil, 2, nil, 5, nil, nil],
                [nil, 3, nil, 1, nil, 2, nil],
                [nil, 2, nil, 5, nil, 1, nil, nil],
                [nil, 2, nil, 2, nil, 4, nil],
                [nil, 4, nil, 1, nil, 3, nil, nil],
                [nil, 3, nil, 1, nil, 1, nil],
                [nil, 3, nil, 3, nil, 3, nil, nil],
                [nil, 4, nil, 1, nil, 7, nil],
                [nil, 1, nil, 1, nil, 3, nil, nil],
                [nil, 1, nil, 4, nil, 1, nil],
                [nil, 1, nil, 5, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1114,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [3, 3, 4, 4, nil, nil, nil],
                [2, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 3, 1, 1, 3],
                [2, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, 2, 1, 4],
                [1, nil, nil, nil, 3, nil, nil, 4],
                [1, 3, 1, 2, nil, nil, nil],
                [7, nil, nil, nil, 2, nil, nil, 1],
                [1, 2, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, 2],
                [nil, nil, nil, 1, 4, 2, 2],
                [nil, nil, nil, 3, nil, nil, nil, 1],
                [nil, nil, nil, 2, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1115,
            rows: [
                [nil, nil, 4, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 1, 1, 3, 3, nil],
                [nil, 2, 4, 1, nil, 2, 1],
                [nil, nil, nil, 3, 3, nil, 1, nil],
                [nil, 2, 4, nil, 4, 1, 2],
                [1, 1, 2, nil, nil, nil, nil, nil],
                [1, nil, 2, nil, 1, nil, 1],
                [nil, 4, 1, 2, 6, 1, 2, 2],
                [1, 4, 4, 1, 5, 1, 1],
                [nil, 1, 1, 1, 3, 1, 1, 1],
                [nil, 2, 1, 2, 1, 1, 2],
                [nil, 2, 1, 1, 2, 2, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1116,
            rows: [
                [nil, 2, 2, nil, nil, 1, 4, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, 1, 5, nil, 5, 1],
                [4, 4, 1, 1, 1, 3, 3],
                [6, 3, nil, 1, 3, nil, 3, 1],
                [1, 6, 1, 1, 2, 1, 2],
                [1, 1, 2, 1, 6, 1, 1, 2],
                [1, nil, 1, 2, 1, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1117,
            rows: [
                [3, nil, nil, nil, nil, nil, nil, 1],
                [2, 2, nil, nil, nil, 2, 2],
                [nil, 2, 2, nil, nil, 1, 2, nil],
                [nil, 1, 1, nil, 4, 3, nil],
                [nil, 1, 1, 2, 2, 1, 2, nil],
                [nil, 3, 1, 1, 2, 1, nil],
                [nil, 3, 1, 5, 1, 2, 2, nil],
                [nil, 2, 6, 2, 4, 4, nil],
                [nil, 1, 1, 1, 3, 1, 3, nil],
                [nil, 1, 1, 4, 1, 1, nil],
                [nil, 3, 1, 3, 1, 3, 1, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1118,
            rows: [
                [nil, nil, 1, 2, nil, 1, nil, nil],
                [nil, 3, nil, 2, nil, nil, nil],
                [nil, 2, 1, 1, 1, nil, 2, nil],
                [2, 1, 3, nil, 4, 1, nil],
                [nil, 1, nil, 1, 4, 2, 1, nil],
                [1, nil, 1, 1, nil, nil, 1],
                [4, 3, nil, 4, 2, nil, 1, nil],
                [2, 2, 1, 3, 4, nil, 1],
                [nil, nil, nil, 3, 3, 3, nil, 3],
                [1, 5, nil, nil, 5, 5, nil],
                [nil, 2, 1, nil, 4, nil, 4, 1],
                [nil, nil, nil, nil, nil, 2, 2],
                [nil, 2, 2, 2, 4, 1, nil, 3],
                [nil, 1, 3, 1, nil, 2, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1119,
            rows: [
                [1, 2, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, 2],
                [nil, 1, nil, 4, 4, 1, 4, 1],
                [nil, 3, 1, nil, nil, nil, nil],
                [nil, 2, 1, 3, 3, 3, 2, 3],
                [2, 1, 2, 1, 3, 1, 2],
                [1, 3, 3, 1, 3, 1, 1, 1],
                [2, 2, 2, 5, 2, 2, 1],
                [2, 1, 1, 2, 3, 2, 1, 1],
                [4, 4, 1, 2, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1120,
            rows: [
                [nil, 2, 3, nil, nil, nil, nil, nil],
                [2, 2, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil, nil],
                [nil, nil, 3, 1, nil, nil, nil],
                [nil, 2, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 6, 5, 2, nil, nil, nil],
                [nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, 4, 3, 4, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 3, 1, nil, nil],
                [nil, nil, nil, 2, 1, 1, nil],
                [nil, nil, nil, nil, 5, 1, nil, nil],
                [nil, nil, nil, 3, 3, 2, nil],
                [nil, nil, nil, nil, 3, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
    ]
}
