// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch60 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1181,
            rows: [
                [nil, 1, 3, nil, 1, 2, nil, nil],
                [nil, 2, 3, nil, 1, 2, nil],
                [nil, 1, nil, nil, nil, 4, nil, nil],
                [nil, 2, nil, nil, nil, 6, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 4, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 4, 3, 2, nil, nil],
                [nil, nil, 2, 1, 4, nil, nil, nil],
                [nil, 1, 4, 1, nil, nil, nil],
                [nil, 2, 1, 1, nil, nil, nil, nil],
                [nil, 4, 1, 1, nil, nil, nil],
                [nil, 6, 1, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1182,
            rows: [
                [nil, 3, 1, nil, 2, 3, 3, nil],
                [1, nil, nil, nil, nil, nil, 3],
                [nil, 1, 1, 2, nil, 1, 1, nil],
                [4, nil, nil, nil, nil, nil, 1],
                [nil, 4, 5, 5, nil, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 2, 2, nil, 1, 3, 5, nil],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 2, 3, nil, 3, 1, 3, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 4, 3, 3, nil, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 1, 4, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1183,
            rows: [
                [2, 1, nil, 1, nil, nil, 2, 1],
                [1, nil, nil, nil, 1, 2, nil],
                [1, 1, 1, 3, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [2, nil, 1, nil, 4, 1, nil, nil],
                [4, 4, nil, nil, 2, 1, 1],
                [4, nil, nil, nil, nil, 4, 4, 1],
                [nil, nil, nil, nil, 3, nil, 2],
                [1, 2, nil, nil, 1, 2, nil, nil],
                [3, nil, 3, 3, nil, nil, 1],
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [2, nil, nil, 1, nil, 2, 1],
                [2, 1, 1, 2, 2, 1, 2, 1],
                [2, 2, 1, 3, 1, 5, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1184,
            rows: [
                [nil, 2, 2, nil, nil, 2, nil, 3],
                [3, 3, 3, nil, nil, 1, nil],
                [nil, 2, 1, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, nil, nil],
                [nil, 2, nil, 3, 5, 1, nil, 2],
                [nil, 4, 4, nil, 1, nil, nil],
                [nil, nil, 2, 2, 2, 1, nil, 3],
                [1, nil, 3, 1, nil, 2, nil],
                [1, nil, nil, 5, 1, 3, nil, nil],
                [1, nil, 2, 1, 3, nil, 1],
                [4, nil, 1, nil, 1, nil, 2, nil],
                [1, 3, nil, nil, 3, nil, 4],
                [1, 1, nil, 1, 5, 1, 3, 1],
                [5, 1, 2, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1185,
            rows: [
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, 2, 2, 3, 1, 2, 2, nil],
                [2, 2, 1, 1, 3, 1, 2],
                [nil, 4, 2, 2, 2, 3, 1, nil],
                [1, 2, 6, 2, 1, 1, 1],
                [nil, 3, 3, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 5, 1, 1, 2, 2, 4, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, 3, 1, 4, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1186,
            rows: [
                [2, nil, nil, 2, 2, nil, nil, 2],
                [3, nil, 2, nil, 2, nil, 2],
                [nil, 1, 4, nil, nil, 4, 1, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [2, 3, nil, nil, nil, 3, 1],
                [3, nil, 3, 2, 2, 1, nil, 3],
                [1, 2, nil, nil, nil, 3, 2],
                [3, nil, 2, 2, 2, 3, nil, 5],
                [1, 1, nil, nil, nil, 2, 2],
                [nil, 3, 3, nil, nil, 1, 2, nil],
                [1, nil, 1, nil, 3, nil, 3],
                [nil, 1, 1, nil, nil, 1, 6, nil],
                [4, nil, 2, nil, 1, nil, 6],
                [6, nil, nil, 1, 2, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1187,
            rows: [
                [nil, nil, nil, 2, nil, 2, 2, nil],
                [nil, nil, 1, 3, 4, nil, nil],
                [nil, 3, 5, 2, nil, 1, 2, nil],
                [nil, 2, 1, 1, 2, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, 4, nil, 1, nil],
                [nil, 1, nil, 1, 2, 1, nil, nil],
                [nil, 3, nil, 1, 1, 1, nil],
                [nil, nil, 4, 3, nil, nil, 1, nil],
                [nil, 4, 4, 1, 2, 1, nil],
                [nil, nil, 2, 2, 2, 2, 1, nil],
                [nil, 1, 3, 1, 2, 1, nil],
                [nil, 3, 6, 1, 1, 2, 2, nil],
                [nil, 4, 5, 1, 3, 1, nil],
                [nil, 1, 1, 2, 2, 1, 1, nil],
                [nil, 3, 1, 1, 1, 2, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1188,
            rows: [
                [nil, nil, nil, 1, nil, nil, 3, nil],
                [nil, 3, 3, 1, nil, nil, 4],
                [nil, 1, nil, 1, nil, nil, 2, 1],
                [nil, 1, 3, 2, nil, 2, 4],
                [nil, 3, 1, 2, nil, nil, 2, 1],
                [nil, 3, 3, 4, nil, 2, 5],
                [nil, 3, 2, 1, nil, 1, 1, 2],
                [nil, 2, 1, 1, nil, 5, 1],
                [nil, 1, 1, 1, nil, 1, 4, 1],
                [nil, 2, 1, 1, nil, 3, 1],
                [nil, 2, 2, 1, nil, 3, 1, 1],
                [nil, 3, 1, 1, nil, 2, 1],
                [nil, 2, 1, 1, nil, 2, 2, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1189,
            rows: [
                [nil, 1, nil, nil, nil, nil, 4, nil],
                [nil, 5, 1, 2, 3, 1, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 5, 3, 3, 1, 1, 2],
                [nil, 1, nil, nil, nil, nil, 1],
                [nil, 4, 2, 4, 4, 2, 1, 3],
                [nil, 1, nil, nil, nil, nil, 2],
                [nil, nil, nil, 1, 3, 1, 7, nil],
                [nil, 1, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, 2, 2, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1190,
            rows: [
                [nil, 1, nil, 4, 4, 5, 1, 2],
                [2, nil, nil, nil, nil, 2, 1],
                [5, 5, nil, 1, nil, 2, 1, nil],
                [nil, 4, 1, 2, 2, 2, nil],
                [2, 1, 2, 1, 1, 2, 2, 1],
                [2, 1, 4, 1, 2, 1, 2],
                [3, 3, 1, 2, 2, 1, 1, 4],
                [2, 1, 2, 1, 2, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 2, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1191,
            rows: [
                [3, 3, nil, 3, 3, 1, 6, 2],
                [1, 2, 1, 1, 5, 1, 2],
                [2, 1, 2, 2, 1, 4, 4, 4],
                [4, 1, 1, 1, 2, 5, 1],
                [4, 1, 3, 1, 3, 3, 3, 3],
                [5, 1, 1, 6, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1192,
            rows: [
                [1, nil, nil, 2, 1, 2, 1, 2],
                [2, 2, 2, 1, 1, 3, 3],
                [1, 4, 1, 2, 2, 2, 2, 5],
                [1, 3, 3, 3, 1, 4, 1],
                [nil, 1, 1, 5, 5, 1, nil, nil],
                [nil, 4, 1, 1, 4, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil, nil],
                [nil, 4, 4, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1193,
            rows: [
                [nil, 1, nil, nil, 1, 1, nil, nil],
                [nil, nil, 3, 1, 3, 5, nil],
                [nil, 5, 3, 1, 3, 1, 4, nil],
                [nil, 1, 3, 1, 3, 1, nil],
                [nil, 1, 2, 2, 1, 3, 1, nil],
                [nil, 1, 1, 1, 3, 1, nil],
                [nil, 1, 1, 1, 2, 2, 1, nil],
                [nil, 1, 2, 1, 4, 1, nil],
                [nil, nil, 1, 4, 1, 6, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 2, 1, 2, 2, 4],
                [1, nil, nil, nil, nil, nil, 2],
                [1, nil, 1, 1, 1, 1, nil, 1],
                [1, nil, 1, nil, nil, 1, 1],
                [1, nil, 1, nil, 1, 1, nil, 1],
                [1, nil, 1, nil, nil, 1, 1],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1194,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, nil],
                [1, 2, nil, 2, nil, 1, 1],
                [6, 3, 1, 3, 1, 3, 1, 2],
                [nil, nil, 1, 1, nil, 5, 2],
                [1, 2, 1, 1, 2, 1, 1, 2],
                [nil, nil, 1, 2, nil, 1, 6],
                [nil, 2, 2, 2, 2, nil, 2, 2],
                [1, 2, 2, 4, nil, 1, 4],
                [nil, 4, 1, 1, 1, nil, 3, 1],
                [1, 3, 1, 1, nil, 3, 1],
                [nil, nil, nil, 3, nil, 1, 1, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1195,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 3, 1, nil, nil, nil, nil],
                [nil, nil, 1, 4, nil, nil, nil, nil],
                [nil, 1, 1, 4, nil, nil, nil],
                [nil, nil, 5, 1, nil, nil, nil, nil],
                [nil, 3, 1, 2, nil, nil, nil],
                [3, 4, 4, 3, 1, 3, 2, nil],
                [2, 1, 3, 2, 2, 1, nil],
                [3, 1, 1, 4, 5, 5, 1, nil],
                [3, 2, 2, 3, 1, 1, nil],
                [3, 3, 1, 4, 3, 1, 1, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 4, 4, 1, 3, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1196,
            rows: [
                [nil, nil, 1, nil, 2, 2, nil, nil],
                [2, nil, nil, 1, 4, 1, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, nil, 2, nil, nil, nil, 1],
                [nil, nil, 4, nil, nil, 1, 3, 2],
                [2, nil, nil, nil, 1, 2, 2],
                [nil, 1, 1, nil, 2, 1, 5, nil],
                [nil, nil, 5, 1, 5, 3, 1],
                [1, 2, 2, nil, 1, 1, 1, 2],
                [2, 1, 1, 1, 6, 2, 1],
                [3, 1, 2, 1, nil, 3, 3, 1],
                [2, 1, 2, 1, 1, 1, 1],
                [1, 1, 1, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1197,
            rows: [
                [nil, 1, 6, 4, nil, nil, 2, nil],
                [nil, nil, 1, nil, 5, 2, nil],
                [nil, 1, nil, 3, 1, nil, 2, nil],
                [nil, nil, 1, 1, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 2, 1, nil, nil, 2, nil],
                [nil, 2, 1, 1, 2, 1, 1, nil],
                [nil, 3, 1, 1, 2, 1, nil],
                [nil, 2, 2, 1, 3, 1, 3, nil],
                [nil, 3, 1, 1, 1, 3, nil],
                [nil, 1, 3, 3, 1, 4, 1, nil],
                [nil, 2, 1, 2, 1, 1, nil],
                [nil, 4, 1, 1, 1, 1, 3, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1198,
            rows: [
                [1, 3, 1, 1, 1, 2, 6, 3],
                [1, 1, 2, 3, 2, 2, 4],
                [4, 2, 4, 4, 1, 2, 1, 1],
                [1, 1, 1, 2, 2, 1, 2],
                [nil, 2, 1, 1, 1, 2, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 2, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 3, 1, 1, 1, 1, 1, 1],
                [2, 1, 1, 2, 1, 2, 2],
                [1, 2, 1, 2, 1, 2, 1, 2],
                [1, 2, 2, 1, 1, 1, 1],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1199,
            rows: [
                [nil, 1, 1, 1, 3, 1, nil, nil],
                [nil, 2, 1, 2, nil, 1, nil],
                [nil, 1, 2, 1, 1, 4, 4, nil],
                [nil, 4, 1, 2, 3, 1, nil],
                [nil, 3, 1, 3, 3, 1, 1, nil],
                [nil, 2, 1, 3, 5, 5, nil],
                [nil, 1, 1, 2, 2, 2, 1, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, nil, 1, 1, 1, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 4, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 1, 1, 1, nil, 1],
                [1, nil, 1, nil, nil, 1, 1],
                [1, nil, 1, nil, 1, 1, nil, 1],
                [1, nil, 1, nil, nil, 1, 1],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1200,
            rows: [
                [nil, 2, 3, 1, nil, 2, nil, nil],
                [nil, 2, nil, 4, 1, nil, nil],
                [nil, nil, 2, 1, 4, nil, 1, nil],
                [nil, 4, 4, 4, 3, 3, nil],
                [nil, 3, 1, 1, 3, 1, 1, nil],
                [nil, 2, 1, nil, 2, nil, nil],
                [nil, 1, nil, 1, nil, 2, 1, nil],
                [nil, 2, 1, 2, 1, 1, nil],
                [nil, 2, 1, 2, 4, 1, 1, nil],
                [nil, 2, 2, 1, 2, 1, nil],
                [nil, 2, 1, 3, 1, 1, 1, nil],
                [nil, 1, 3, 1, 3, 3, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
    ]
}
