// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch52 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1021,
            rows: [
                [nil, 4, nil, nil, nil, 4, nil, 4],
                [nil, nil, nil, 1, nil, 3, 3],
                [3, 1, 1, nil, 1, 1, nil, 2],
                [2, 2, 2, nil, 2, 2, nil],
                [nil, nil, nil, 2, nil, 2, nil, 2],
                [nil, nil, 2, 2, 2, nil, nil],
                [2, 2, 2, 3, nil, nil, nil, nil],
                [3, 3, 1, 1, nil, 1, 5],
                [nil, 5, 5, 5, nil, 1, 1, 5],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, 1, nil, 1, 1, nil],
                [6, nil, 6, nil, nil, 1, 1, nil],
                [nil, 1, nil, nil, nil, 6, 6],
                [nil, nil, 1, nil, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1022,
            rows: [
                [nil, nil, nil, nil, 2, 2, 4, nil],
                [nil, 4, nil, nil, 4, nil, nil],
                [nil, 4, 4, 1, 3, nil, 3, nil],
                [nil, 3, nil, 6, 6, 6, nil],
                [nil, 2, nil, 2, nil, nil, nil, nil],
                [nil, 2, nil, 2, 2, 2, nil],
                [nil, 2, nil, nil, nil, 2, 2, nil],
                [nil, 2, 2, 2, 1, nil, nil],
                [nil, nil, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 3, 3, 5, 1, 1, nil],
                [nil, 1, 5, 5, 2, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1023,
            rows: [
                [1, nil, nil, 1, 1, 1, nil, nil],
                [1, nil, 1, nil, nil, nil, 1],
                [4, nil, 4, nil, 4, nil, nil, 6],
                [6, 4, 4, nil, 4, 4, nil],
                [nil, 4, 4, 5, nil, 5, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [2, 2, 2, nil, 2, 2, nil, nil],
                [nil, nil, nil, 2, nil, 2, 2],
                [2, nil, 2, 1, 1, 1, 1, nil],
                [3, 3, 3, nil, nil, 3, nil],
                [nil, 3, nil, 3, nil, 3, nil, 3],
                [nil, nil, nil, 1, 1, 1, 3],
                [3, nil, 1, 1, nil, nil, nil, nil],
                [1, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, 1, nil],
                [nil, nil, 1, nil, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1024,
            rows: [
                [2, 2, 2, 2, nil, 2, 2, nil],
                [nil, 2, 2, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil, nil],
                [1, 1, 1, 1, nil, 1, 1],
                [1, nil, nil, 1, 1, nil, 3, nil],
                [3, 3, 3, 3, nil, 3, 3],
                [nil, 6, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 6, nil, 6, nil, 1, nil, 1],
                [nil, nil, nil, 1, 1, 1, 5],
                [nil, nil, 5, nil, nil, 5, 5, nil],
                [5, 1, nil, 1, 1, 1, 4],
                [4, nil, nil, 2, 2, nil, nil, 2],
                [nil, nil, 1, nil, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1025,
            rows: [
                [nil, nil, nil, 2, 2, 2, 4, nil],
                [nil, 4, 4, nil, 4, nil, nil],
                [nil, 3, nil, 3, 3, 3, 1, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, 2, 4, nil, 4, 3, nil, nil],
                [nil, 3, 3, 2, 2, 2, nil],
                [nil, nil, 2, 2, nil, nil, nil, nil],
                [nil, 2, 4, 3, 3, 3, nil],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 6, 1, 1, nil, nil, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, 1, nil, 1, 1, 1, 2, nil],
                [nil, 2, 1, 1, 1, 1, nil],
                [nil, 1, 1, 5, 5, 1, 1, nil],
                [nil, 6, 1, 1, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1026,
            rows: [
                [nil, nil, nil, 2, 2, nil, 6, nil],
                [nil, 6, 3, 3, nil, 3, nil],
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, 1, 1, nil, 1, 1, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, 1, nil, 5, nil, nil],
                [nil, 5, nil, 5, 1, 1, 2, nil],
                [nil, 2, 1, 1, 1, 1, nil],
                [nil, 4, 4, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 4, nil],
                [nil, 4, 4, 4, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, nil, 1, nil, 1, nil, 1],
                [3, nil, 1, nil, 1, nil, 4],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1027,
            rows: [
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, 1, 1, 1, nil],
                [nil, nil, 1, nil, 1, 1, nil],
                [nil, 2, nil, 2, 2, 2, 2, nil],
                [nil, nil, 2, nil, 2, 2, nil],
                [nil, nil, 2, nil, 2, 3, 3, nil],
                [nil, 3, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, 5, 2, nil],
                [nil, 2, 2, 6, 6, 6, 5, nil],
                [nil, 1, 1, 1, 5, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 2, 2, 4, 4, nil],
                [nil, 4, 4, 1, 1, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1028,
            rows: [
                [nil, nil, 6, nil, 6, 6, nil, nil],
                [nil, 1, nil, 1, nil, nil, 4],
                [4, nil, 4, nil, nil, 3, nil, 2],
                [2, 2, nil, nil, 2, nil, 2],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [nil, 2, nil, nil, nil, nil, 2],
                [2, 1, 1, nil, nil, 1, 1, 1],
                [1, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, nil, 5, 5, 5, 5],
                [5, 1, 1, 1, nil, 1, nil],
                [1, nil, 1, 1, nil, nil, 1, 1],
                [1, nil, nil, 1, 1, 1, nil],
                [nil, 3, 3, 3, nil, 3, nil, 3],
                [3, 3, 3, 3, 3, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1029,
            rows: [
                [nil, 2, nil, 1, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1],
                [nil, 3, 3, 3, nil, 3, nil, 1],
                [1, nil, nil, nil, 1, nil, 1],
                [1, 1, nil, 2, 2, nil, 2, 2],
                [2, nil, 2, 2, 2, 2, 2],
                [2, 2, nil, 2, 2, 2, 2, 2],
                [nil, nil, 1, nil, 1, nil, 6],
                [6, 6, 6, 1, 1, 2, 2, nil],
                [1, 1, 1, 1, nil, 1, nil],
                [1, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, 2, 2, nil, nil, nil],
                [2, nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, 2, 1, nil, 1, 1],
                [1, nil, nil, 4, 4, 4, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1030,
            rows: [
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, 3, 2, nil, 2, nil],
                [nil, 2, 2, 2, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, 2, 3, 3, nil, nil, 1, nil],
                [nil, 1, 1, nil, nil, 1, nil],
                [nil, 1, 1, 1, 1, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 4, 3, nil, nil, nil, nil],
                [nil, 3, 3, 3, nil, nil, nil],
                [nil, nil, nil, 6, 2, 2, nil, nil],
                [nil, nil, 2, 2, nil, 1, nil],
                [nil, 1, 1, 4, 6, 6, 1, nil],
                [nil, 1, 4, 4, 4, 4, nil],
                [nil, 4, 4, 2, 2, 1, 5, nil],
                [nil, 5, 5, 1, 1, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1031,
            rows: [
                [2, nil, nil, nil, nil, 1, 1, nil],
                [1, nil, 1, 1, nil, nil, nil],
                [1, 1, nil, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, 1, 1, nil],
                [1, 1, nil, 1, 1, 1, 1, 1],
                [1, 1, nil, 1, 1, 1, nil],
                [nil, 3, 3, 3, nil, nil, nil, 3],
                [nil, nil, 3, 2, 2, 2, 2],
                [nil, 5, 5, 5, nil, nil, 5, 2],
                [4, 4, 4, 4, 4, 6, nil],
                [6, nil, 3, nil, 3, nil, 2, nil],
                [2, 2, nil, 2, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, 3, 3, 3, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1032,
            rows: [
                [nil, 4, 4, nil, 4, 4, 4, nil],
                [4, 4, 1, nil, nil, nil, 1],
                [1, nil, 1, 1, 1, 5, nil, 5],
                [nil, 5, nil, 1, 1, nil, 1],
                [nil, nil, 1, 1, nil, nil, 1, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, 1, 1, nil, nil, 6],
                [nil, nil, 6, nil, 3, nil, 3, 3],
                [nil, nil, nil, 3, nil, 3, 3],
                [nil, 3, 3, nil, 2, 2, 3, nil],
                [nil, 3, nil, nil, 3, nil, nil],
                [nil, nil, nil, 3, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1033,
            rows: [
                [nil, nil, nil, 2, 6, 1, 2, nil],
                [nil, nil, 2, nil, nil, nil, 2],
                [2, nil, 2, nil, nil, 2, 2, 2],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, nil, 3, nil, 3],
                [nil, 3, nil, 3, nil, 3, 3],
                [1, nil, 1, 1, nil, nil, 1, 1],
                [nil, 3, nil, 3, 1, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil, 1],
                [nil, 1, nil, 1, 1, 1, nil],
                [nil, 1, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, 5, 5, nil, 5],
                [5, nil, 5, nil, 2, 2, 2],
                [4, 4, nil, nil, 4, nil, 4, 4],
                [4, 3, 3, 1, 1, 1, 1],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1034,
            rows: [
                [nil, 1, 1, 1, nil, 1, 1, nil],
                [1, 1, 1, nil, nil, 1, nil],
                [1, 1, 1, 4, nil, 4, 4, 4],
                [2, 2, nil, nil, nil, 2, 2],
                [2, 1, 1, nil, 1, 1, nil, nil],
                [1, 1, nil, nil, 2, nil, 3],
                [nil, 3, 3, 3, 3, 2, nil, nil],
                [1, nil, 1, nil, 1, 1, 1],
                [1, 1, 1, 2, 2, nil, nil, nil],
                [nil, nil, 2, nil, 2, 2, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 6, 6, 5, 5, 5, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1035,
            rows: [
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, 5, nil, nil, nil, 1, nil],
                [nil, 1, nil, 1, 1, nil, nil, nil],
                [nil, 1, 1, nil, nil, 6, nil],
                [nil, 6, 6, 1, nil, 1, 1, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 2, nil, 2, 2, nil, nil],
                [nil, 2, 2, nil, nil, 2, nil],
                [nil, nil, nil, 3, nil, 3, 3, nil],
                [nil, nil, 3, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 2, 2, nil],
                [nil, 2, 2, 2, 2, 3, nil],
                [nil, 3, 4, 5, 4, 3, 4, nil],
                [nil, 4, 4, 4, 4, 4, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1036,
            rows: [
                [nil, 2, nil, 2, 2, 2, nil, 2],
                [nil, 2, 2, 2, 2, nil, 2],
                [nil, nil, 2, 2, nil, 4, 4, 4],
                [4, nil, 4, 4, nil, 4, 4],
                [5, nil, 5, 5, nil, nil, nil, nil],
                [nil, nil, 5, nil, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, 1],
                [3, 3, 3, 3, 3, 3, nil],
                [nil, 3, 3, 3, 3, 1, 1, 1],
                [1, nil, nil, nil, 2, 2, nil],
                [6, 6, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1037,
            rows: [
                [3, 3, 3, 3, nil, 1, nil, nil],
                [nil, 6, 6, 6, 6, 3, nil],
                [1, 1, nil, 1, 1, nil, 1, nil],
                [nil, nil, nil, nil, 2, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [2, 2, nil, 2, nil, nil, 2],
                [nil, 2, nil, 2, 1, 1, 1, 1],
                [2, nil, nil, nil, 2, 2, nil],
                [2, nil, 2, 2, 2, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, nil],
                [1, nil, 1, 1, nil, 1, nil],
                [3, 3, nil, 3, nil, 3, 3, 3],
                [4, nil, 4, nil, nil, nil, 4],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [nil, 1, nil, 1, 1, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1038,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, 4, 4, nil],
                [nil, nil, nil, 4, 4, 4, nil, nil],
                [nil, 4, nil, nil, nil, 2, 2],
                [nil, 2, nil, 2, nil, 2, nil, nil],
                [nil, 2, 2, 2, 2, nil, nil],
                [2, 2, nil, 2, nil, 1, 1, 1],
                [1, 1, nil, nil, 1, nil, 1],
                [1, nil, 1, 1, 1, 1, 1, 1],
                [nil, 1, nil, 1, 1, nil, 1],
                [nil, 1, 1, nil, nil, 1, 1, 6],
                [nil, 6, 6, 5, 1, nil, 1],
                [nil, 1, 1, 1, 3, 3, 3, 3],
                [nil, 4, 4, 4, 1, 1, 3],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1039,
            rows: [
                [nil, nil, 4, nil, 4, 4, 4, nil],
                [nil, nil, nil, nil, nil, 4, nil],
                [nil, nil, 4, 4, 4, 3, 3, nil],
                [nil, 3, 3, nil, nil, 3, nil],
                [nil, nil, 3, 3, 3, nil, 1, nil],
                [nil, 1, 1, 2, 2, nil, nil],
                [nil, nil, 2, nil, 2, 2, 2, nil],
                [nil, 2, 2, nil, 2, nil, nil],
                [nil, 5, nil, 5, nil, 1, 1, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, 6, nil],
                [nil, nil, nil, 6, 6, 1, nil],
                [nil, 2, 2, nil, 2, 1, 1, nil],
                [nil, nil, nil, 1, 2, 1, nil],
                [nil, 1, 2, 1, 1, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1040,
            rows: [
                [nil, 3, 3, 3, nil, 3, nil, nil],
                [nil, 3, 3, 1, nil, 1, nil],
                [nil, nil, 1, nil, 1, nil, 1, nil],
                [nil, 4, 4, 4, 4, nil, nil],
                [nil, nil, 4, 4, 4, nil, 3, nil],
                [nil, 3, nil, 3, 2, 2, nil],
                [nil, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, nil, 2, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, nil, nil, 1, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, nil, 1, nil, 5, 5, nil],
                [nil, 4, 4, 2, 2, 2, nil],
                [nil, 2, nil, 2, 2, 2, 2, nil],
                [nil, 1, 1, 1, 6, 6, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
    ]
}
