// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch104 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2061,
            rows: [
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, 3, 4, 1, nil, nil],
                [nil, nil, 5, 1, 4, 2, nil, nil],
                [nil, 5, 5, 5, 2, 1, nil],
                [nil, nil, 3, 1, 1, 7, nil, nil],
                [nil, 2, 2, 4, 1, 2, nil],
                [nil, nil, 1, 1, 2, 2, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 3, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2062,
            rows: [
                [nil, 1, nil, 3, nil, 1, nil, 6],
                [1, 1, nil, 5, 1, nil, 3],
                [3, nil, 3, nil, 1, nil, 2, nil],
                [1, 2, nil, 1, 1, nil, 5],
                [5, nil, 1, nil, 2, nil, 1, nil],
                [3, 1, nil, 2, 2, nil, 2],
                [nil, 2, nil, 1, nil, 1, nil, 1],
                [4, 4, nil, 4, 1, nil, 2],
                [nil, 2, nil, 2, nil, 1, nil, 1],
                [1, 1, nil, 1, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [1, 1, nil, 1, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [1, 1, nil, 1, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2063,
            rows: [
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [nil, 2, 3, 3, 1, 4, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 5, 6, 4, 1, 3, 3],
                [nil, 2, nil, nil, nil, nil, 1],
                [nil, 3, 3, 2, 1, 1, 1, 1],
                [nil, 2, nil, nil, nil, nil, 1],
                [nil, nil, nil, 1, 2, 1, 2, nil],
                [nil, 2, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, 4, 2, nil],
                [nil, 4, 4, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2064,
            rows: [
                [1, 3, 3, 1, 2, 2, 1, 1],
                [6, nil, nil, 1, nil, nil, 2],
                [1, 3, 3, 3, 3, 3, 3, 1],
                [1, nil, nil, 3, nil, nil, 2],
                [2, 2, 2, 2, 1, 4, 2, 2],
                [2, nil, nil, 1, nil, nil, 2],
                [nil, 2, nil, nil, 2, nil, nil, 2],
                [5, 5, 3, 3, 1, 3, 3],
                [nil, 1, nil, nil, 6, nil, nil, 2],
                [1, 1, 1, 2, 1, 3, 4],
                [nil, 1, nil, nil, 3, nil, nil, 3],
                [1, nil, nil, 2, nil, nil, 1],
                [nil, 2, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2065,
            rows: [
                [1, 1, 4, 1, 1, 1, 4, 1],
                [1, 2, 3, 2, 1, 6, 4],
                [2, 3, 3, 3, 5, 5, 4, 1],
                [1, 2, 1, 1, 2, 1, 1],
                [1, 1, 4, 4, 1, 2, 1, 1],
                [2, 2, 1, 2, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2066,
            rows: [
                [2, nil, nil, 1, nil, 1, 1, 3],
                [3, nil, 7, nil, 6, nil, 2],
                [2, nil, nil, 1, nil, nil, nil, 3],
                [3, 4, 2, nil, nil, nil, 2],
                [3, nil, nil, 4, nil, nil, nil, 2],
                [2, 2, 1, nil, nil, nil, 1],
                [nil, nil, nil, 3, nil, 5, 5, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, 4, nil, 1, 1, nil],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, nil, 3, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, 1, 4, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2067,
            rows: [
                [2, nil, 2, nil, nil, 3, nil, 2],
                [3, nil, 1, nil, 1, nil, 1],
                [3, nil, nil, 2, 1, nil, nil, 3],
                [3, nil, 3, 3, 1, nil, 2],
                [4, nil, nil, 2, 2, nil, nil, 1],
                [2, nil, 6, 3, 2, nil, 1],
                [3, nil, nil, 1, 1, nil, nil, 6],
                [1, nil, 4, nil, 1, nil, 2],
                [1, nil, nil, 3, 2, nil, nil, 1],
                [1, nil, 2, nil, 2, nil, 1],
                [4, nil, 2, nil, nil, 2, nil, 1],
                [6, nil, nil, nil, nil, nil, 1],
                [2, nil, 1, nil, nil, 2, nil, 2],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2068,
            rows: [
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, 1, 3, nil, nil, nil, nil],
                [3, 1, nil, 2, 5, nil, nil, nil],
                [nil, nil, nil, nil, 5, 2, nil],
                [1, 3, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, nil, 1, 4, nil],
                [nil, nil, nil, 2, 3, nil, 2, 1],
                [nil, 3, 3, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, 1, 2],
                [nil, 1, 2, nil, nil, nil, nil],
                [1, 2, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, 2, nil],
                [1, 2, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2, 6],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2069,
            rows: [
                [1, 3, 2, 2, 1, 2, 2, 4],
                [2, nil, nil, 4, nil, nil, 4],
                [4, nil, nil, 1, 6, nil, nil, 1],
                [nil, nil, nil, 3, nil, nil, nil],
                [3, nil, nil, 1, 2, nil, nil, 2],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2070,
            rows: [
                [nil, 6, 1, 4, 4, 4, 2, nil],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [3, 3, 2, 1, 6, 1, 2],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [2, 1, 1, 6, 6, 2, 5],
                [nil, 2, 1, 2, 2, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 1, 1, 2, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2071,
            rows: [
                [6, 1, nil, nil, nil, nil, 2, 3],
                [1, 3, 3, 2, 1, 5, 3],
                [1, 1, nil, nil, nil, nil, 2, 1],
                [2, 1, 3, 3, 1, 1, 3],
                [3, 3, nil, nil, nil, nil, 1, 2],
                [5, 2, 1, 2, 2, 1, 2],
                [1, 2, nil, nil, nil, nil, 1, 2],
                [4, 1, 5, 3, 2, 1, 2],
                [1, 2, nil, nil, nil, nil, 2, 1],
                [1, 5, 2, 2, 1, 1, 1],
                [5, 4, nil, nil, nil, nil, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 2, nil, nil, nil, nil, 2, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2072,
            rows: [
                [2, nil, nil, nil, nil, nil, nil, 2],
                [2, 2, 1, 2, 2, 1, 2],
                [2, nil, nil, nil, nil, nil, nil, 7],
                [4, 4, 1, 3, 1, 3, 2],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [1, 2, 2, 1, 1, 3, 3],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [3, 1, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2073,
            rows: [
                [3, 3, nil, 4, 2, nil, 2, 4],
                [4, 4, nil, 3, nil, 1, 5],
                [nil, 3, nil, 3, 1, nil, 1, nil],
                [3, 1, 1, 1, 1, 2, 3],
                [nil, 2, nil, 3, 3, nil, 1, nil],
                [2, 3, 3, 1, 1, 2, 2],
                [nil, 2, nil, 2, 1, nil, 2, nil],
                [2, 1, nil, nil, nil, 3, 1],
                [nil, 2, nil, 1, 3, nil, 3, nil],
                [2, 1, nil, nil, nil, 1, 4],
                [1, 3, 3, nil, nil, 1, 2, 2],
                [1, 1, nil, nil, nil, 2, 1],
                [1, 2, 1, nil, nil, 3, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2074,
            rows: [
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 2, nil, nil, 1, nil, 4, nil],
                [1, nil, nil, 1, nil, nil, 5],
                [nil, 4, nil, nil, 1, nil, 2, nil],
                [2, nil, nil, 2, nil, nil, 2],
                [nil, 1, nil, nil, 3, nil, 3, nil],
                [nil, 2, nil, 1, nil, 3, nil],
                [nil, 3, nil, nil, 7, nil, 1, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [nil, nil, 1, 2, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 2, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2075,
            rows: [
                [nil, 2, 2, nil, 2, 2, nil, nil],
                [5, nil, 2, 2, nil, 2, nil],
                [1, nil, nil, nil, nil, nil, 3, nil],
                [1, 1, 3, nil, nil, 1, 5],
                [1, nil, nil, nil, nil, nil, 1, nil],
                [2, 2, 2, nil, nil, 3, 3],
                [nil, 3, 3, 3, 1, 1, 1, 1],
                [nil, 1, 1, nil, nil, 2, 4],
                [nil, 1, 2, 3, 6, 2, 1, 4],
                [nil, 2, 6, nil, nil, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2076,
            rows: [
                [nil, 3, 3, nil, nil, 3, 1, nil],
                [1, 1, nil, nil, 1, 4, nil],
                [nil, 4, 1, nil, nil, 5, 5, nil],
                [1, 2, nil, nil, 1, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, nil, 1, nil, 2, nil, 2, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [1, nil, 1, nil, 2, nil, 6, nil],
                [nil, 1, nil, 1, nil, 4, nil],
                [1, nil, 1, nil, 5, nil, 1, nil],
                [nil, 2, nil, 1, nil, 2, nil],
                [1, nil, 2, nil, 2, nil, 1, nil],
                [nil, 1, nil, 5, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2077,
            rows: [
                [nil, nil, 1, 3, 1, nil, nil, nil],
                [nil, nil, 3, 2, 3, nil, nil],
                [nil, nil, nil, 3, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 5, nil, 5, nil, 4, nil],
                [nil, 3, nil, 3, nil, 4, nil],
                [2, nil, 3, nil, 4, nil, 1, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [3, nil, 1, nil, 4, nil, 3, nil],
                [nil, 3, nil, 2, nil, 1, nil],
                [2, nil, 1, nil, 2, nil, 2, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [2, nil, 3, nil, 2, nil, 1, nil],
                [nil, 5, nil, 1, nil, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2078,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, 2, 2, nil, nil],
                [1, 4, nil, 2, 4, nil, nil],
                [nil, 3, 2, nil, 3, 3, nil, nil],
                [1, 3, nil, 1, 2, nil, nil],
                [nil, 1, 1, nil, 1, 5, nil, nil],
                [5, 2, nil, 1, 3, nil, nil],
                [nil, 2, 1, nil, 1, 2, nil, nil],
                [4, 6, nil, 2, 2, nil, nil],
                [nil, 5, 2, nil, 2, 1, nil, nil],
                [1, 3, nil, 3, 2, nil, nil],
                [nil, 4, 4, nil, 4, 1, nil, nil],
                [1, 1, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2079,
            rows: [
                [nil, nil, nil, 5, 2, 4, 1, nil],
                [2, 1, 2, nil, nil, nil, 6],
                [3, nil, nil, nil, nil, nil, nil, 3],
                [3, nil, nil, nil, nil, nil, 2],
                [1, nil, nil, nil, nil, nil, nil, 5],
                [5, nil, nil, nil, nil, nil, 2],
                [1, nil, nil, nil, 1, 1, 1, 1],
                [1, nil, nil, 2, 4, 4, 3],
                [3, nil, nil, nil, 3, 2, 2, 2],
                [2, nil, nil, 4, 4, 3, 1],
                [2, nil, nil, nil, 1, 3, 3, 2],
                [4, 2, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 3, 1, 1, 2],
                [2, 1, nil, nil, nil, nil, nil],
                [2, 1, 2, nil, nil, nil, nil, nil],
                [1, 2, 2, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2080,
            rows: [
                [nil, 1, 2, nil, 1, 2, 1, nil],
                [1, nil, nil, nil, nil, nil, 4],
                [nil, 1, 3, 1, nil, 2, 2, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, 3, 3, 1, nil, 2, 1, nil],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 1, 5, nil, 1, 5, 5, nil],
                [2, nil, nil, nil, nil, nil, 4],
                [nil, 5, 1, nil, 2, 1, 2, nil],
                [2, nil, nil, nil, nil, nil, 1],
                [nil, 1, 4, 1, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 5, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
    ]
}
