// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch35 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 681,
            rows: [
                [nil, 5, 5, 5, 1, 1, nil, nil],
                [nil, nil, 1, nil, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, 1, 1, nil, nil],
                [nil, nil, 2, nil, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, 2, 1, nil],
                [nil, nil, 3, 3, nil, 3, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, 4, 4, nil, 4, nil, 4, nil],
                [nil, nil, 4, 4, nil, 4, nil],
                [nil, 4, 1, 1, 6, 6, 1, nil],
                [nil, 1, 2, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 682,
            rows: [
                [nil, 3, 5, nil, nil, nil, 5, nil],
                [nil, nil, 5, 4, nil, 4, nil],
                [nil, 4, 3, 3, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, 1, 1, nil, nil, 1, nil],
                [nil, 1, 1, nil, nil, 4, nil],
                [nil, 2, 1, 1, 1, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 2, nil, nil, nil, nil],
                [nil, 2, 2, 2, nil, nil, nil],
                [nil, nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, nil, 2, nil],
                [nil, 2, 2, 3, 3, 3, 3, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 4, 4, 4, 4, 6, 1, nil],
                [nil, 1, 1, 6, 6, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 683,
            rows: [
                [nil, 3, nil, nil, 3, 3, nil, nil],
                [nil, 3, nil, nil, 3, nil, nil],
                [nil, 2, nil, nil, 2, 2, 2, nil],
                [nil, nil, 2, nil, 3, 1, nil],
                [nil, 1, 1, nil, 4, nil, 4, nil],
                [nil, nil, 4, nil, 1, nil, nil],
                [nil, 1, 5, nil, 5, 1, 1, nil],
                [nil, 1, 1, 1, 5, nil, nil],
                [nil, 5, 5, 5, nil, 1, 2, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, 3, 3, 3, 1, nil, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [nil, nil, 1, 2, 2, 2, nil],
                [nil, 2, 2, 2, 1, 1, 1, nil],
                [nil, 2, 2, 6, 6, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 684,
            rows: [
                [1, 1, nil, 2, 2, nil, 1, 1],
                [1, 3, 3, 3, nil, nil, nil],
                [nil, nil, 3, nil, nil, 3, 3, 3],
                [nil, 3, 1, nil, nil, 1, nil],
                [1, 1, 1, 1, nil, nil, nil, 1],
                [1, nil, nil, 5, 5, nil, nil],
                [nil, 5, 5, 5, 5, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 4, nil, nil, 4, nil, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, 2, nil, 1, 1, nil, nil],
                [nil, 1, 1, 2, 2, 2, nil],
                [nil, 2, 1, 2, 2, 1, nil, nil],
                [nil, 1, 1, 1, 6, 6, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 685,
            rows: [
                [nil, 3, nil, 3, 3, 3, 3, nil],
                [nil, nil, 3, 4, nil, nil, nil],
                [nil, nil, 4, 4, nil, 4, nil, nil],
                [nil, 4, 4, 2, 2, nil, nil],
                [nil, 2, 2, 1, 1, nil, 1, nil],
                [nil, 1, nil, 1, 1, nil, nil],
                [nil, 1, 5, nil, 5, 5, 5, nil],
                [nil, nil, 5, 1, 1, 1, nil],
                [nil, 1, 1, nil, 6, 6, nil, nil],
                [nil, nil, 1, nil, 3, 3, nil],
                [nil, 3, 3, nil, nil, nil, nil, nil],
                [nil, 3, 1, 2, nil, nil, nil],
                [nil, 1, 1, nil, 1, nil, 1, nil],
                [nil, nil, 1, nil, 1, 3, nil],
                [nil, nil, 2, nil, 3, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 686,
            rows: [
                [nil, nil, nil, nil, 2, 2, 2, nil],
                [nil, 2, nil, nil, 3, nil, nil],
                [nil, 3, 3, 3, 3, nil, 1, nil],
                [nil, 1, nil, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, nil, nil, nil],
                [nil, 1, nil, 1, 2, 2, nil],
                [nil, 2, nil, nil, nil, 2, 2, nil],
                [nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, nil, 2, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 4, 4, 4, 4, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 6, nil, 6, nil, 6],
                [5, nil, 4, nil, 5, nil, 5],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 687,
            rows: [
                [nil, 1, 1, 1, nil, nil, nil, 1],
                [nil, 1, nil, 2, 2, 2, nil],
                [nil, 1, 1, nil, nil, 1, 4, 4],
                [nil, nil, 4, 4, nil, nil, 4],
                [nil, 4, 2, nil, 2, 1, 1, 1],
                [2, 1, 1, nil, 1, 1, 1],
                [1, 2, 2, nil, 2, 2, nil, 2],
                [2, 2, 2, nil, 2, 2, nil],
                [1, 1, 3, nil, nil, 3, 3, 1],
                [1, nil, nil, nil, 1, nil, 1],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [5, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [1, nil, 1, nil, nil, nil, 1],
                [nil, nil, 1, 1, 6, 6, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 688,
            rows: [
                [1, 1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, 1, nil, nil],
                [4, nil, nil, nil, 4, 4, nil, 4],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, 2, nil, nil, 5, 5, 5, 6],
                [3, 3, 3, 6, 6, 1, 1],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 2, 1],
                [1, 4, 4, 2, 2, 2, 3],
                [3, 3, 1, 2, 2, 2, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 689,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, nil, 1, nil],
                [1, 1, 1, nil, 1, 1, 2],
                [nil, 2, nil, 2, nil, 2, 2, nil],
                [2, 2, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, 2, 1, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [1, 5, 5, nil, nil, 1, 3, 3],
                [3, 3, 3, nil, 1, 1, 1],
                [1, 1, 1, 4, 4, 4, 1, 1],
                [1, 1, 1, 1, 6, 6, 6],
                [3, 3, 3, 1, 2, 2, 1, 1],
                [1, 1, 1, 1, 3, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 690,
            rows: [
                [nil, 1, 1, 1, nil, nil, 1, nil],
                [1, 1, 1, 1, nil, 1, nil],
                [1, nil, 1, nil, 4, nil, nil, nil],
                [4, nil, nil, 4, nil, nil, nil],
                [nil, 1, nil, nil, 1, 1, 4, nil],
                [nil, 4, 4, 4, 3, nil, nil],
                [3, 3, 3, 3, 3, 3, nil, 3],
                [3, 1, 1, 1, nil, 1, nil],
                [2, 2, 2, 1, nil, nil, 1, 1],
                [nil, nil, nil, 1, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, 2, nil],
                [1, 2, 2, 1, nil, 1, nil],
                [nil, 1, 1, nil, nil, nil, nil, nil],
                [1, nil, 1, nil, nil, nil, 6],
                [nil, 6, nil, nil, nil, 6, 1, nil],
                [nil, 1, 1, 2, 2, 5, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 691,
            rows: [
                [4, nil, nil, nil, nil, 4, 4, nil],
                [4, nil, 4, 1, nil, nil, nil],
                [1, 1, nil, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, 1, 1],
                [nil, 2, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, 1, 1, nil],
                [1, 3, nil, 3, 3, 3, 3, 3],
                [3, 3, nil, 3, 3, 2, nil],
                [nil, 2, 2, 2, nil, nil, nil, 2],
                [nil, nil, 2, 2, 2, 2, 2],
                [nil, 2, 2, 1, nil, nil, 1, 5],
                [1, 1, 1, 1, 1, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [5, 5, nil, 5, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 6, 6, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 692,
            rows: [
                [nil, 1, 5, 5, nil, 1, nil, nil],
                [nil, 1, 1, 2, nil, 2, nil],
                [nil, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 6, 6, nil, 2, nil],
                [nil, 2, nil, 3, 3, 3, nil],
                [nil, nil, 3, nil, 3, nil, 3, nil],
                [nil, 3, nil, nil, 3, nil, nil],
                [nil, 3, nil, 4, nil, 4, nil, nil],
                [nil, 4, 4, 4, 4, 4, nil],
                [nil, 4, 4, 1, nil, nil, 1, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, 1, 1, 1, 2, 2, nil],
                [nil, 2, nil, 2, 2, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 693,
            rows: [
                [nil, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [1, 1, 5, 5, 4, 4, 4],
                [nil, nil, 1, 2, 2, 2, 2, nil],
                [2, nil, 3, 3, 3, 3, 3],
                [3, 3, 2, nil, 2, 4, 4, 2],
                [nil, nil, 2, nil, 2, 2, nil],
                [2, nil, 2, nil, nil, 2, nil, nil],
                [nil, 1, 1, 1, nil, nil, 1],
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [nil, nil, 5, nil, 6, 6, nil],
                [nil, nil, 2, 2, 2, nil, 2, 2],
                [nil, 2, nil, nil, nil, nil, 1],
                [nil, nil, 1, 4, nil, nil, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 694,
            rows: [
                [nil, 3, nil, 5, 5, 5, 2, nil],
                [2, 2, 2, 2, 2, 2, nil],
                [2, nil, 2, nil, 2, 1, 1, 1],
                [nil, nil, nil, 1, 6, 4, nil],
                [nil, nil, 4, 4, 4, nil, 3, nil],
                [3, 3, nil, nil, 3, nil, 3],
                [3, 3, 3, 3, 3, nil, nil, 3],
                [nil, nil, nil, 1, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [nil, 4, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 4, 5, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 695,
            rows: [
                [3, 3, 1, nil, 1, 1, 1, nil],
                [1, 1, nil, 2, 2, nil, nil],
                [nil, 6, nil, 6, 6, nil, nil, nil],
                [6, nil, 6, nil, 1, nil, nil],
                [1, nil, nil, 1, nil, 1, nil, nil],
                [1, nil, nil, 3, nil, 3, 1],
                [1, nil, 1, 1, nil, nil, 1, nil],
                [1, nil, 1, 1, 1, 1, 3],
                [3, nil, 3, nil, nil, nil, 3, nil],
                [2, nil, nil, 2, nil, 3, nil],
                [4, 4, 4, 4, 2, 2, nil, 2],
                [nil, 2, 2, 2, nil, nil, nil],
                [2, nil, nil, 2, 2, nil, 2, 2],
                [3, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, 5, 3, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 696,
            rows: [
                [nil, 2, 2, nil, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, 2],
                [1, 1, nil, nil, 1, nil, 1, 4],
                [4, 4, 4, nil, nil, nil, 1],
                [6, 6, 6, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, nil, 5],
                [nil, 1, 1, nil, 1, 1, 1, 1],
                [3, 3, nil, nil, 3, 3, 5],
                [5, nil, nil, 2, 2, nil, nil, 2],
                [2, 2, nil, 1, 3, 3, 3],
                [3, nil, 3, 1, 1, 1, 1, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 4, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 697,
            rows: [
                [nil, nil, nil, 1, 1, nil, 1, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, 4, 4, nil, nil],
                [nil, nil, 4, 4, nil, 4, 4, nil],
                [nil, 4, nil, nil, nil, nil, nil],
                [nil, nil, 6, 6, 3, nil, 3, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, 2, nil, 3, 3, 3, 3, nil],
                [nil, 3, 3, 2, 2, 2, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 5, 5, 5, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 698,
            rows: [
                [nil, nil, nil, nil, 6, nil, nil, nil],
                [nil, 6, 1, 1, nil, nil, nil],
                [1, nil, 1, 1, nil, nil, nil, 1],
                [1, nil, nil, nil, 1, nil, 1],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, 2, nil, 2, 2, 2, 2],
                [2, 2, nil, nil, nil, nil, nil, nil],
                [2, 2, 1, 1, 1, 1, nil],
                [1, nil, 1, nil, nil, nil, 1, 1],
                [nil, nil, 1, nil, 1, 1, 1],
                [4, 4, 4, 4, nil, 4, 4, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [3, 3, 3, 3, nil, 3, 4, 3],
                [3, 3, 6, 6, 5, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 699,
            rows: [
                [1, nil, nil, nil, 1, 1, 1, nil],
                [1, 3, nil, 3, nil, nil, 3],
                [nil, 3, 3, 4, nil, 4, nil, nil],
                [4, 4, 4, 4, 1, 1, 1],
                [1, 1, nil, nil, nil, 6, 6, 6],
                [5, 5, nil, nil, nil, 5, 5],
                [nil, 2, 1, nil, 1, nil, 2, nil],
                [2, 2, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 700,
            rows: [
                [nil, 3, 6, 6, nil, 2, nil, 1],
                [1, nil, nil, 1, 1, 2, 2],
                [nil, 3, 3, nil, 3, nil, nil, nil],
                [3, nil, nil, nil, 3, 1, nil],
                [1, 1, 2, 2, 4, nil, 4, nil],
                [4, nil, 4, nil, nil, 4, nil],
                [nil, 4, nil, nil, nil, nil, 2, nil],
                [2, 2, 2, 2, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, 2, 2, nil, 1, 1, nil, 1],
                [1, nil, nil, 1, 1, 1, 1],
                [nil, nil, 1, 1, nil, 3, nil, nil],
                [3, 3, nil, nil, 4, 4, nil],
                [nil, nil, 1, 1, nil, nil, 3, nil],
                [nil, 3, 3, nil, 5, 5, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
    ]
}
