// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch134 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2661,
            rows: [
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [3, 1, nil, nil, nil, 2, 1],
                [nil, 4, nil, nil, nil, nil, 1, nil],
                [4, 1, nil, nil, nil, 2, 4],
                [nil, 1, nil, nil, nil, nil, 5, nil],
                [2, 2, nil, nil, nil, 1, 4],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [2, 3, nil, nil, nil, 3, 1],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [3, 4, nil, nil, nil, 2, 1],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 7, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2662,
            rows: [
                [1, nil, nil, 4, nil, 1, 5, 3],
                [1, nil, 5, nil, 3, nil, 4],
                [2, nil, nil, 1, nil, nil, nil, 3],
                [1, 6, 1, nil, nil, nil, 2],
                [1, nil, nil, 2, nil, nil, nil, 1],
                [2, 1, 1, nil, nil, nil, 2],
                [nil, nil, nil, 1, nil, 2, 1, nil],
                [nil, nil, 7, nil, 3, nil, nil],
                [nil, nil, nil, 1, nil, 2, 1, nil],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2663,
            rows: [
                [1, 2, 2, 3, 4, 1, 1, 2],
                [2, nil, nil, 1, nil, nil, 1],
                [3, 1, 4, 2, 1, 2, 1, 6],
                [2, nil, nil, 2, nil, nil, 5],
                [2, 4, 2, 1, 1, 4, 1, 2],
                [1, nil, nil, 3, nil, nil, 3],
                [nil, 2, nil, nil, 1, nil, nil, 1],
                [2, 3, 2, 1, 2, 4, 1],
                [nil, 4, nil, nil, 1, nil, nil, 4],
                [1, 3, 4, 1, 4, 1, 2],
                [nil, 1, nil, nil, 4, nil, nil, 2],
                [1, nil, nil, 4, nil, nil, 1],
                [nil, 1, nil, nil, 1, nil, nil, 4],
                [2, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2664,
            rows: [
                [nil, 4, 3, nil, nil, 1, 3, nil],
                [3, 1, nil, nil, 2, 3, nil],
                [nil, 4, 1, nil, nil, 2, 1, nil],
                [2, 1, nil, nil, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, nil, 2, nil, 1, nil, 2, nil],
                [nil, 1, nil, 2, nil, 4, nil],
                [1, nil, 2, nil, 2, nil, 1, nil],
                [nil, 6, nil, 2, nil, 3, nil],
                [2, nil, 1, nil, 2, nil, 1, nil],
                [nil, 3, nil, 3, nil, 1, nil],
                [3, nil, 1, nil, 5, nil, 1, nil],
                [nil, 1, nil, 4, nil, 1, nil],
                [3, nil, 2, nil, 1, nil, 2, nil],
                [nil, 4, nil, 2, nil, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2665,
            rows: [
                [1, nil, 7, nil, 1, nil, 2, nil],
                [nil, 1, nil, 3, nil, 2, nil],
                [3, nil, 1, nil, 2, nil, 2, nil],
                [nil, 1, nil, 6, nil, 1, nil],
                [2, nil, 3, nil, 4, nil, 1, nil],
                [nil, 5, nil, 2, nil, 1, nil],
                [3, nil, 1, nil, 1, nil, 1, nil],
                [nil, 2, nil, 1, nil, 2, nil],
                [1, nil, 2, nil, 3, nil, 3, nil],
                [nil, 1, nil, 2, nil, 4, nil],
                [2, nil, 1, nil, 2, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 1, 3, 1, 2, 1, 3, 1],
                [2, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2666,
            rows: [
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, 5, nil, nil],
                [1, 2, 4, 4, 1, 5, 7, 2],
                [nil, nil, nil, nil, 3, nil, nil],
                [1, 3, 1, 2, 3, 1, 3, 4],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 5, nil, 2, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2667,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [4, 1, 4, 1, nil, nil, nil],
                [2, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, 5, 2, 2],
                [1, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, 3, 2],
                [3, nil, nil, nil, 2, nil, nil, 4],
                [1, 3, 4, 3, nil, nil, nil],
                [6, nil, nil, nil, 2, nil, nil, 1],
                [5, 3, 1, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, 2],
                [nil, nil, nil, 1, 2, 1, 1],
                [nil, nil, nil, 5, nil, nil, nil, 4],
                [nil, nil, nil, 3, 1, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2668,
            rows: [
                [2, nil, 2, nil, 3, nil, 1, nil],
                [nil, 4, nil, 1, nil, 2, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, 1, nil, nil],
                [nil, 5, nil, nil, nil, 3, nil],
                [5, nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 7, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2669,
            rows: [
                [2, 1, nil, nil, nil, nil, 5, 4],
                [3, 1, nil, nil, nil, 3, 2],
                [1, 3, nil, nil, nil, nil, 1, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [5, 1, nil, nil, nil, nil, 3, 1],
                [4, nil, nil, nil, nil, nil, 2],
                [1, 4, nil, nil, nil, nil, 3, 1],
                [3, nil, nil, nil, nil, nil, 1],
                [2, 1, nil, nil, nil, nil, 5, 1],
                [2, nil, nil, nil, nil, nil, 1],
                [5, 1, nil, nil, nil, nil, 3, 2],
                [2, 1, nil, nil, nil, 2, 1],
                [3, 1, nil, nil, nil, nil, 3, 1],
                [6, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2670,
            rows: [
                [nil, nil, 7, nil, nil, 6, nil, nil],
                [nil, 3, 3, nil, 2, 2, nil],
                [nil, 2, 4, 1, 2, 5, 3, nil],
                [nil, 1, 1, nil, 3, 1, nil],
                [nil, 2, 5, 1, 5, 1, 4, nil],
                [nil, 4, 6, nil, 2, 1, nil],
                [nil, nil, 3, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2671,
            rows: [
                [nil, 1, nil, nil, nil, nil, 4, nil],
                [1, nil, nil, 4, nil, nil, 1],
                [3, nil, nil, 5, 1, nil, nil, 2],
                [4, nil, nil, 3, nil, nil, 2],
                [1, nil, nil, 2, 4, nil, nil, 1],
                [2, nil, nil, 3, nil, nil, 1],
                [nil, 2, 1, 2, 3, 7, 1, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 1, 2, 1, 3, 2, 1, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2672,
            rows: [
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, 4, nil, nil, 4, nil, nil],
                [nil, 1, nil, nil, 5, 1, 2, nil],
                [1, nil, nil, nil, nil, 2, nil],
                [nil, 7, nil, nil, 1, 2, 6, nil],
                [3, nil, nil, nil, nil, 1, nil],
                [3, 2, 5, 5, nil, 1, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [3, 1, 2, 1, nil, 2, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2673,
            rows: [
                [1, nil, 2, nil, nil, 2, nil, 1],
                [2, nil, 1, nil, 4, nil, 2],
                [2, nil, nil, 4, 2, nil, nil, 1],
                [4, nil, 1, 2, 6, nil, 5],
                [1, nil, nil, 2, 1, nil, nil, 2],
                [4, nil, 1, 2, 1, nil, 6],
                [1, nil, nil, 1, 1, nil, nil, 2],
                [4, nil, 4, nil, 1, nil, 5],
                [1, nil, nil, 3, 1, nil, nil, 2],
                [4, nil, 2, nil, 3, nil, 1],
                [3, nil, 1, nil, nil, 4, nil, 1],
                [3, nil, nil, nil, nil, nil, 1],
                [3, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2674,
            rows: [
                [4, nil, nil, nil, 4, nil, nil, nil],
                [1, nil, nil, nil, 1, nil, nil],
                [nil, 5, nil, nil, 1, 4, nil, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [nil, 4, nil, nil, 3, 1, nil, nil],
                [nil, 3, nil, 1, nil, 2, nil],
                [nil, 1, nil, nil, 3, 3, nil, nil],
                [1, nil, nil, 1, 5, 6, nil],
                [nil, 1, nil, nil, 3, 1, nil, nil],
                [6, nil, nil, 1, 1, 1, nil],
                [1, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2675,
            rows: [
                [nil, 1, nil, 1, nil, 3, nil, 1],
                [3, nil, 1, nil, 4, nil, 3],
                [nil, 5, nil, 1, nil, 3, nil, 2],
                [3, nil, 1, nil, 5, nil, 3],
                [nil, 1, nil, 3, nil, 1, nil, 2],
                [1, nil, 1, nil, 2, nil, 3],
                [nil, 5, nil, 1, nil, 2, nil, 1],
                [2, nil, 1, nil, 6, nil, 5],
                [nil, 1, nil, 4, nil, 3, nil, 1],
                [4, nil, 1, nil, 3, nil, 1],
                [nil, 4, nil, 1, nil, 3, nil, 1],
                [3, nil, 4, nil, 1, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2676,
            rows: [
                [nil, nil, 1, 3, 5, nil, nil, nil],
                [nil, nil, 3, 1, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, nil, 1, nil, 1, nil, 2, nil],
                [nil, 3, nil, 1, nil, 2, nil],
                [2, nil, 3, nil, 6, nil, 1, nil],
                [nil, 3, nil, 2, nil, 1, nil],
                [5, nil, 2, nil, 1, nil, 5, nil],
                [nil, 1, nil, 5, nil, 1, nil],
                [2, nil, 3, nil, 2, nil, 1, nil],
                [nil, 2, nil, 1, nil, 2, nil],
                [2, nil, 3, nil, 2, nil, 5, nil],
                [nil, 2, nil, 4, nil, 2, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2677,
            rows: [
                [3, 1, 3, 4, 1, 2, 1, 3],
                [1, nil, nil, 2, nil, nil, 5],
                [3, nil, nil, 1, 7, nil, nil, 1],
                [nil, nil, nil, 2, nil, nil, nil],
                [1, nil, nil, 5, 1, nil, nil, 5],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2678,
            rows: [
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 1, 2, nil, nil],
                [nil, 2, 2, 1, 2, nil, nil],
                [nil, 1, 7, 3, 1, 2, 1, nil],
                [nil, 6, 1, 2, 1, 1, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2679,
            rows: [
                [4, 2, 1, 1, 1, 2, 1, 4],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, 5, nil, nil, nil, nil],
                [5, 4, 2, 1, 1, 3, 1, 4],
                [nil, nil, nil, nil, 2, nil, nil],
                [3, 2, 1, 2, 4, 6, 1, 2],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 7, 4, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [2, 4, 1, 1, 1, 4, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2680,
            rows: [
                [nil, nil, 1, 3, 4, nil, nil, nil],
                [nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, 2, 1, 3, 2, 1, nil],
                [nil, 2, 5, 4, nil, nil, 1],
                [nil, nil, 3, 1, 2, 7, 3, nil],
                [nil, 2, 2, 1, nil, nil, 1],
                [nil, 4, nil, nil, 1, 3, 1, nil],
                [nil, 2, 5, 3, 1, 2, nil],
                [nil, 2, nil, nil, 6, 3, 1, nil],
                [nil, 2, 1, 2, 1, 3, nil],
                [nil, nil, 1, 4, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
    ]
}
