// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch47 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 921,
            rows: [
                [nil, nil, nil, nil, 2, 2, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, nil, 1, nil],
                [nil, 1, nil, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, nil, nil, nil],
                [nil, 4, nil, 4, 4, 4, nil],
                [nil, 4, nil, nil, nil, 1, 1, nil],
                [nil, 1, 1, 1, 2, nil, nil],
                [nil, nil, 2, nil, 3, 3, nil, nil],
                [nil, 3, 3, 3, 1, 1, nil],
                [nil, 1, 1, 2, 2, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 2, 2, 2, 2, 6, 6, nil],
                [nil, 6, 2, 2, 2, 5, nil],
                [nil, 5, nil, 5, nil, 1, nil, 1],
                [1, nil, 1, nil, 2, nil, 2],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 922,
            rows: [
                [3, nil, nil, 1, 3, 3, nil, nil],
                [3, nil, 3, nil, nil, nil, 3],
                [3, nil, 3, nil, 1, nil, nil, 1],
                [1, 1, 1, nil, 1, 1, nil],
                [nil, 1, 1, 4, nil, 4, nil, nil],
                [nil, 4, 1, nil, 1, 1, nil],
                [6, 6, 1, nil, 2, 4, nil, nil],
                [nil, nil, nil, 4, nil, 4, 4],
                [4, nil, 4, 2, 2, 2, 2, nil],
                [2, 2, 2, nil, nil, 2, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, 1, 1, 5, 5],
                [1, nil, 3, 3, nil, nil, nil, nil],
                [1, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, 2, nil],
                [nil, nil, 1, nil, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 923,
            rows: [
                [2, 2, 2, 2, nil, 2, 2, nil],
                [nil, 5, 5, nil, 5, nil, nil],
                [nil, nil, 5, 5, 1, nil, nil, nil],
                [1, 1, 1, 1, nil, 1, 1],
                [1, nil, nil, 1, 1, nil, 1, nil],
                [1, 3, 3, 3, nil, 1, 1],
                [nil, 1, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 6, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, 1, 1, 3, 1],
                [nil, nil, 1, nil, nil, 3, 3, nil],
                [3, 6, nil, 2, 2, 2, 2],
                [2, nil, nil, 1, 1, nil, nil, 1],
                [nil, nil, 1, nil, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, nil, nil],
                [nil, 4, 4, 6, 1, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 924,
            rows: [
                [nil, nil, nil, 2, 2, 2, 2, nil],
                [nil, 2, 2, nil, 2, nil, nil],
                [nil, 2, nil, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, 3, 3, nil, 3, 5, nil, nil],
                [nil, 5, 6, 6, 1, 1, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 4, 4, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, nil, 1, 2, 2, 2, nil],
                [nil, 2, 3, 3, 3, 3, nil],
                [nil, 3, 3, 3, 4, 4, 4, nil],
                [nil, 4, 4, 4, 4, 4, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 925,
            rows: [
                [nil, nil, nil, 1, 1, nil, 1, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, 1, 2, nil, nil],
                [nil, nil, 2, 2, nil, 2, 2, nil],
                [nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, 2, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, 1, nil, 5, 5, 5, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 4, 4, 4, nil],
                [nil, 4, 6, 6, 4, 4, nil],
                [nil, 4, 1, 3, 3, 3, 3, nil],
                [nil, 3, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 3, nil, 3],
                [3, nil, 2, nil, 2, nil, 2],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 926,
            rows: [
                [nil, nil, 1, nil, 3, 3, nil, nil],
                [nil, 3, nil, 3, nil, nil, 3],
                [3, nil, 3, nil, nil, 1, nil, 1],
                [2, 2, nil, nil, 1, nil, 1],
                [nil, 6, 6, nil, nil, 6, 1, nil],
                [nil, 1, nil, nil, nil, nil, 1],
                [1, 1, 3, nil, nil, 3, 3, 3],
                [3, nil, 3, nil, 1, nil, nil],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [1, 1, 1, 1, nil, 1, nil],
                [1, nil, 2, 2, nil, nil, 1, 2],
                [2, nil, nil, 2, 2, 5, nil],
                [nil, 5, 5, 2, nil, 2, nil, 2],
                [4, 4, 4, 1, 5, 5, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 927,
            rows: [
                [nil, 1, nil, 1, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1],
                [nil, 1, 1, 1, nil, 1, nil, 1],
                [1, nil, nil, nil, 1, nil, 1],
                [1, 1, nil, 1, 1, nil, 1, 1],
                [1, nil, 1, 1, 1, 1, 1],
                [1, 3, nil, 3, 4, 4, 4, 4],
                [nil, nil, 4, nil, 2, nil, 2],
                [2, 2, 2, 2, 3, 2, 2, nil],
                [2, 2, 2, 6, nil, 6, nil],
                [6, nil, 6, nil, nil, nil, nil, nil],
                [nil, 2, 2, 2, nil, nil, nil],
                [2, nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, 2, 2, nil, 2, 2],
                [2, nil, nil, 2, 2, 2, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 928,
            rows: [
                [nil, 3, 2, nil, nil, nil, 2, nil],
                [nil, nil, 3, 3, nil, 1, nil],
                [nil, 1, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, 1, 1, nil, nil, 1, nil],
                [nil, 1, 1, nil, nil, 2, nil],
                [nil, 2, 2, 2, 2, nil, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, nil, 4, nil],
                [nil, 6, 6, 6, 1, 1, 1, nil],
                [nil, 1, 1, 4, 4, 4, nil],
                [nil, 4, 4, 4, 3, 3, 3, nil],
                [nil, 3, 5, 4, 5, 5, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 929,
            rows: [
                [nil, 1, 1, nil, 5, 5, 5, nil],
                [1, 1, 1, nil, nil, nil, 1],
                [1, nil, 1, 1, 1, 1, nil, 1],
                [nil, 3, nil, 3, 3, nil, 3],
                [nil, nil, 3, 3, nil, nil, 3, nil],
                [nil, 3, 3, nil, 3, 3, nil],
                [3, nil, nil, nil, nil, nil, 2, 2],
                [nil, 2, 2, nil, nil, nil, nil],
                [2, 2, nil, nil, nil, nil, 1, 1],
                [1, nil, 2, 2, nil, nil, 2],
                [nil, nil, 1, nil, 1, nil, 1, 1],
                [nil, nil, nil, 1, nil, 1, 1],
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [nil, 6, nil, nil, 6, nil, nil],
                [nil, nil, nil, 4, 2, 4, 4, nil],
                [nil, 4, 4, 4, 4, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 930,
            rows: [
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, nil, 1, nil, nil, nil, 1],
                [1, nil, 1, nil, nil, 3, 3, 3],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, nil, 3, nil, 2],
                [nil, 2, nil, 2, nil, 2, 2],
                [2, nil, 2, 2, nil, nil, 2, 2],
                [nil, 1, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, 1, 6, nil, 2],
                [nil, 2, nil, 2, 2, 1, nil],
                [nil, 5, nil, nil, 5, 5, nil, nil],
                [nil, nil, nil, 5, nil, 5, nil],
                [nil, nil, nil, nil, 4, 4, nil, 4],
                [4, nil, 4, nil, 4, 1, 1],
                [1, 1, nil, nil, 1, nil, 1, 1],
                [1, 1, 1, 2, 2, 2, 3],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 931,
            rows: [
                [nil, 4, 4, 4, nil, 4, 1, nil],
                [2, 1, 2, nil, nil, 2, nil],
                [2, 2, 2, 2, nil, 2, 2, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [1, 1, 1, nil, 5, 5, nil, nil],
                [5, 1, nil, nil, 1, nil, 1],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [1, nil, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, nil, nil, nil],
                [nil, nil, 1, nil, 1, 1, 1],
                [3, 3, 3, 3, 3, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 2, 2, 6, 6, 6, 2, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 932,
            rows: [
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, 1, 1, nil, nil, nil],
                [nil, 1, 3, nil, nil, 3, nil],
                [nil, 3, 3, 3, nil, 2, 2, nil],
                [nil, 2, 2, nil, nil, nil, nil],
                [nil, nil, 2, nil, 2, 2, nil, nil],
                [nil, 2, 2, nil, nil, 2, nil],
                [nil, nil, nil, 5, nil, 5, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 4, 4, nil],
                [nil, 4, 4, 4, 4, 4, nil],
                [nil, 4, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 6, nil],
                [nil, 6, 6, 2, 2, 3, 3, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 933,
            rows: [
                [2, 2, 2, 3, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [1, 1, nil, 1, 2, nil, 2, nil],
                [nil, nil, nil, nil, 2, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [2, 2, nil, 2, nil, nil, 2],
                [nil, 1, nil, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, 1, 1, nil],
                [1, nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 3, 3, 2, 2, 3, 3, nil],
                [3, nil, 3, 3, nil, 3, nil],
                [3, 3, nil, 6, nil, 6, 6, 6],
                [2, nil, 2, nil, nil, nil, 4],
                [nil, 4, 4, nil, 1, 1, nil, nil],
                [nil, 1, nil, 1, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 934,
            rows: [
                [nil, nil, 2, nil, 2, 2, 2, nil],
                [nil, nil, nil, nil, nil, 4, nil],
                [nil, nil, 4, 4, 4, 4, 4, nil],
                [nil, 4, 4, nil, nil, 5, nil],
                [nil, nil, 5, 1, 1, nil, 1, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, nil, 1, 1, 1, nil],
                [nil, 1, 1, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, 1, nil],
                [nil, 1, 1, 1, 3, nil, nil],
                [nil, nil, 6, 6, 6, nil, 1, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, 1, 2, nil, 2, 2, 2, nil],
                [nil, nil, nil, 2, 2, 2, nil],
                [nil, 2, 2, 2, 3, nil, 3, nil],
                [nil, 3, 3, 3, 3, 3, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 935,
            rows: [
                [nil, 3, 3, 3, nil, 3, nil, nil],
                [nil, 3, 3, 3, nil, 3, nil],
                [nil, nil, 3, nil, 4, nil, 4, nil],
                [nil, 4, 4, 4, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, 2, nil],
                [nil, 2, nil, 2, 2, 2, nil],
                [nil, nil, 6, nil, 1, nil, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 2, 2, 2, nil, nil, 2, nil],
                [nil, 2, 2, 4, nil, 4, nil],
                [nil, nil, nil, 4, nil, 4, 6, nil],
                [nil, 5, 5, 1, 1, 1, nil],
                [nil, 1, nil, 1, 1, 1, 1, nil],
                [nil, 2, 1, 1, 1, 2, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 936,
            rows: [
                [nil, 1, 1, 1, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, nil, 2, nil, nil, 3, nil],
                [nil, nil, nil, 3, nil, 1, nil],
                [nil, 1, nil, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, nil, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, 2, 2, 2, nil],
                [nil, 2, nil, nil, nil, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 3, nil, 3, 3, 3, 3, nil],
                [nil, 3, 3, 4, 4, 4, nil],
                [nil, 4, 4, 5, 5, 3, 3, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 6, 6, 6, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 937,
            rows: [
                [1, 1, 1, nil, 1, 1, 1, nil],
                [1, 3, nil, 3, 2, nil, nil],
                [nil, 2, nil, 1, 1, nil, nil, nil],
                [1, nil, 1, nil, 1, nil, nil],
                [1, nil, nil, 1, nil, 1, nil, nil],
                [1, nil, nil, 1, nil, 3, 3],
                [3, nil, 3, 4, nil, nil, 4, nil],
                [2, nil, 2, 2, 2, 2, 2],
                [6, nil, 5, nil, nil, nil, 3, nil],
                [3, nil, nil, 3, nil, 3, nil],
                [3, 3, 3, 4, 4, 2, nil, 2],
                [nil, 2, 2, 1, nil, nil, nil],
                [1, nil, nil, 1, 1, nil, 2, 6],
                [6, nil, nil, nil, nil, nil, nil],
                [6, nil, nil, 6, 2, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 938,
            rows: [
                [nil, 2, 2, nil, nil, nil, 2, nil],
                [3, 3, 3, 3, 3, nil, 3],
                [nil, 3, 3, 3, nil, 1, nil, 1],
                [1, nil, nil, nil, nil, 1, 2],
                [nil, 3, nil, 3, nil, 3, 3, nil],
                [1, nil, 1, nil, nil, nil, 1],
                [1, nil, nil, nil, 1, 1, nil, 1],
                [nil, 1, 1, 1, 5, 5, nil],
                [5, nil, 2, nil, 2, 2, nil, nil],
                [2, 2, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, 2, 2, 2, 1, 1],
                [4, 1, 4, 4, nil, 4, 4, 4],
                [1, 1, 1, 1, 1, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 939,
            rows: [
                [1, 5, nil, nil, 5, nil, nil, 5],
                [5, nil, 1, nil, 1, 1, nil],
                [1, 3, nil, 3, nil, 3, 3, 2],
                [2, 1, 1, 1, 1, 2, nil],
                [2, nil, nil, 2, 1, 1, nil, nil],
                [1, 1, 1, 1, nil, 1, 1],
                [1, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [1, nil, 1, 1, 1, 1, nil, 1],
                [nil, nil, nil, 1, 1, nil, 1],
                [1, nil, 1, 1, nil, nil, 5, nil],
                [nil, nil, nil, nil, nil, 5, 2],
                [nil, 2, 2, nil, 4, 4, nil, 6],
                [nil, nil, 6, 6, 2, nil, 2],
                [nil, nil, nil, nil, 2, 4, 2, 4],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 940,
            rows: [
                [2, 2, nil, 2, 2, nil, 4, 4],
                [nil, nil, 4, 4, nil, 1, nil],
                [nil, nil, nil, nil, nil, 1, 3, nil],
                [3, 3, nil, nil, 3, nil, 3],
                [nil, 3, 3, nil, 3, nil, 2, 2],
                [nil, nil, 2, nil, nil, nil, 2],
                [nil, 2, nil, nil, 1, nil, nil, nil],
                [1, 1, 2, 2, nil, 1, 1],
                [1, nil, 1, 1, nil, 1, 2, nil],
                [2, nil, 2, nil, nil, nil, 2],
                [nil, nil, 2, nil, nil, 1, nil, 2],
                [2, 2, nil, 1, 1, 1, nil],
                [6, nil, 6, 1, 1, nil, nil, 1],
                [1, nil, nil, nil, 1, nil, nil],
                [nil, 1, 6, 2, 2, 2, 2, nil],
                [nil, 1, 1, 5, 5, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
    ]
}
