// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch62 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1221,
            rows: [
                [nil, 3, nil, 1, nil, 4, 1, nil],
                [nil, nil, nil, nil, 3, 3, nil],
                [nil, 3, nil, nil, 1, nil, 3, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, 1, 2, 2, nil, 1, nil, nil],
                [nil, nil, 1, 3, 1, 1, nil],
                [nil, 1, 3, 1, 1, 2, 1, nil],
                [nil, 2, 2, 4, 1, 2, nil],
                [nil, 2, 1, 2, 1, 1, 2, nil],
                [nil, 4, 4, 1, 3, 2, nil],
                [nil, 3, 3, 3, 1, 1, 2, nil],
                [nil, 1, 2, 1, 2, 1, nil],
                [nil, 2, 1, 1, 2, 5, 1, nil],
                [nil, 2, 2, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1222,
            rows: [
                [2, 1, nil, nil, nil, nil, 3, 3],
                [1, 4, nil, nil, nil, 3, 4],
                [2, 1, nil, nil, nil, nil, 1, 1],
                [3, nil, nil, nil, nil, nil, 4],
                [4, 3, nil, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [3, 1, nil, nil, nil, nil, 1, 3],
                [1, 1, 2, 1, 3, 2, 2],
                [3, 1, nil, nil, nil, nil, 1, 1],
                [5, 1, 5, 5, 3, 3, 3],
                [nil, 1, 1, 2, 2, 1, 1, nil],
                [nil, 1, nil, 2, nil, 5, nil],
                [nil, 5, 3, 3, 1, 1, 1, nil],
                [nil, 4, nil, 1, nil, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1223,
            rows: [
                [nil, 1, 2, 4, 4, 1, 1, nil],
                [4, nil, nil, nil, nil, nil, 2],
                [nil, 2, nil, nil, nil, nil, 4, nil],
                [4, 1, 1, 2, 2, 3, 1],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [2, 2, 1, 1, 1, 1, 2],
                [nil, 2, 1, 3, 1, 3, 1, nil],
                [nil, 3, 1, 5, 3, 3, nil],
                [nil, 1, 4, 4, 1, 1, 2, nil],
                [nil, 1, 3, 1, 3, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1224,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 1, 3, 2, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, 1, 3, nil, 3, 1, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, 4, 5, nil, 4, 2, nil],
                [nil, 3, 4, 1, 4, 1, 1, nil],
                [nil, 4, 4, nil, 4, 1, nil],
                [nil, 1, 2, 3, 5, 4, 1, nil],
                [nil, 2, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1225,
            rows: [
                [nil, 1, 2, nil, 3, 1, nil, nil],
                [nil, 2, 2, 1, 3, nil, nil],
                [nil, 5, 5, 1, nil, nil, 2, nil],
                [nil, nil, 4, 2, 2, 3, nil],
                [nil, 1, 3, 3, 1, 3, 1, nil],
                [nil, 4, 1, 3, 5, 2, nil],
                [nil, 1, 4, 1, 1, 1, 2, nil],
                [nil, 1, 1, 4, 1, 3, nil],
                [nil, nil, 2, 1, 1, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 3, 3, 1, 1, 1, 4, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 1, 1, 1, nil, 1],
                [1, nil, 1, nil, nil, 1, 1],
                [1, nil, 1, nil, 1, 1, nil, 1],
                [1, nil, 1, nil, nil, 1, 1],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1226,
            rows: [
                [3, 1, 2, 1, nil, 2, nil, 2],
                [3, 1, nil, 3, nil, 1, 1],
                [1, 5, 1, 2, nil, 3, 3, nil],
                [nil, nil, nil, 3, nil, nil, 1],
                [2, nil, 1, nil, 2, 1, 4, 4],
                [2, 1, 2, 1, 1, 2, 2],
                [1, 2, 1, 5, 1, 3, 1, 6],
                [6, 1, 1, 1, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 4, nil, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1227,
            rows: [
                [nil, nil, 1, 1, 2, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 2, nil, 2, 3, nil, 1],
                [1, 5, nil, 1, 1, nil, 5],
                [nil, 1, 1, 1, 5, 5, 5, nil],
                [2, 1, 4, 4, 4, 1, nil],
                [nil, nil, 2, 1, nil, 2, 1, nil],
                [nil, 2, 2, nil, 3, 1, nil],
                [nil, nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 5, 2, 1, nil, nil],
                [nil, nil, 2, 3, 1, 1, nil, nil],
                [nil, 1, 1, 1, 5, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1228,
            rows: [
                [nil, 2, 2, 2, 2, nil, 5, nil],
                [nil, 1, nil, 2, nil, nil, nil],
                [nil, 2, 1, 3, nil, 1, 1, nil],
                [nil, 3, 3, nil, 3, nil, nil],
                [nil, 3, 3, nil, 1, nil, nil, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, 4, 4, nil, 1, 5, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, 3, 1, 5, 5, 1, 1, nil],
                [nil, 2, 1, 2, 1, 2, nil],
                [nil, 3, 2, 2, 2, 2, 1, nil],
                [nil, 2, 1, 2, 2, 2, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1229,
            rows: [
                [nil, 2, 2, nil, 1, 4, nil, nil],
                [1, 3, nil, 3, nil, 4, 4],
                [nil, 4, nil, 1, nil, 2, 1, 1],
                [nil, 2, 2, 1, 2, 5, nil],
                [nil, 2, 1, nil, nil, 2, 1, nil],
                [2, 2, nil, nil, 1, 2, 2],
                [nil, nil, nil, nil, 3, 3, 6, 6],
                [2, 1, 4, 4, 1, 2, 5],
                [nil, 1, nil, nil, 1, 3, 1, 2],
                [nil, nil, 1, 2, nil, nil, 2],
                [1, nil, 2, 2, nil, nil, 1, 1],
                [5, nil, 1, nil, 1, 3, nil],
                [1, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1230,
            rows: [
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 5, 3, 3, nil, nil],
                [nil, nil, 2, 4, 1, 5, nil, nil],
                [nil, 2, 2, 4, 4, 1, nil],
                [nil, nil, 1, 3, 3, 1, nil, nil],
                [nil, 2, 3, 3, 1, 2, nil],
                [nil, 1, 4, 2, 1, 1, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 1, 2, 2, 5, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1231,
            rows: [
                [nil, 4, nil, nil, 4, 1, 4, nil],
                [4, 3, 2, nil, 6, 1, 2],
                [2, 1, nil, 2, nil, 2, nil, nil],
                [1, 2, 2, 2, nil, 2, nil],
                [nil, 4, nil, 1, nil, 3, 3, 2],
                [2, 2, nil, 4, 4, nil, 4],
                [nil, 1, 2, nil, 3, nil, nil, 3],
                [nil, 2, 1, nil, 2, nil, nil],
                [nil, 1, nil, nil, 3, 5, 1, 3],
                [nil, nil, nil, 1, 2, 2, nil],
                [1, 2, nil, nil, nil, 1, 3, 1],
                [nil, 3, 1, 1, 1, nil, nil],
                [nil, nil, 2, 1, nil, 5, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1232,
            rows: [
                [nil, nil, 1, 5, 2, 1, nil, nil],
                [nil, 2, nil, 1, 2, 1, nil],
                [nil, nil, 1, 2, nil, 2, nil, nil],
                [nil, 1, 3, nil, 1, nil, nil],
                [nil, 6, 6, nil, nil, nil, nil, nil],
                [nil, 1, 2, nil, 1, nil, nil],
                [nil, 1, 5, 5, 1, 1, 2, nil],
                [nil, 2, 1, 1, 4, 1, nil],
                [nil, 2, 2, 2, 2, 1, 2, nil],
                [nil, 2, 1, 3, 1, 3, nil],
                [nil, 1, 1, 4, 1, 1, 2, nil],
                [nil, 1, 4, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1233,
            rows: [
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 2, 1, 2, nil],
                [nil, nil, 1, 4, 1, 5, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, 1, nil, 1, 1, 1, 2, nil],
                [nil, 1, 4, 1, 1, 2, nil],
                [nil, 1, 4, 4, 1, 1, 3, nil],
                [nil, 1, 1, 2, 1, 3, nil],
                [nil, 3, 3, 1, 2, 2, 1, nil],
                [nil, 1, 3, 1, 5, 1, nil],
                [nil, 2, 2, 1, 4, 1, 2, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1234,
            rows: [
                [nil, 1, 1, 2, 1, 1, nil, nil],
                [nil, 2, 1, nil, 4, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil, nil],
                [nil, 1, 1, 2, nil, nil, nil],
                [nil, nil, 1, 2, 1, 1, 1, nil],
                [nil, 1, 1, 2, 2, 2, nil],
                [nil, 1, 5, 5, 1, 1, 1, nil],
                [nil, 1, 2, 2, 2, 1, nil],
                [nil, 4, 4, 1, 2, 1, 1, nil],
                [nil, 3, 3, 3, 1, 1, nil],
                [nil, 1, 2, 1, 1, 4, 1, nil],
                [nil, 3, 1, 1, 2, 4, nil],
                [nil, 1, 1, 2, 1, 4, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1235,
            rows: [
                [nil, 1, nil, 1, 3, nil, 3, nil],
                [nil, nil, 3, 3, nil, 3, nil],
                [nil, 1, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, 2, 1, nil],
                [nil, 1, 1, 2, 2, 2, 1, nil],
                [nil, 1, 1, 2, 2, 2, nil],
                [nil, 2, 1, 4, 4, 1, 5, nil],
                [nil, 1, 4, 4, 1, 1, nil],
                [nil, 2, 1, 6, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1236,
            rows: [
                [nil, 2, nil, nil, nil, 2, 3, nil],
                [1, nil, 3, nil, 2, nil, 1],
                [4, 3, nil, 3, 3, nil, 3, 1],
                [1, 2, 2, 1, 4, 1, 1],
                [4, 1, nil, 6, 1, nil, 2, 1],
                [1, 4, 1, 1, 1, 4, 4],
                [1, 1, 5, 1, 5, 1, 1, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1237,
            rows: [
                [nil, 2, 1, 6, 1, 1, 4, nil],
                [nil, 1, 1, 2, 1, 4, nil],
                [nil, nil, nil, 4, nil, 2, nil, nil],
                [nil, nil, nil, nil, 1, 2, nil],
                [nil, 1, 2, 2, 4, nil, 4, nil],
                [nil, 2, 3, 3, 3, nil, nil],
                [nil, nil, 1, 2, nil, 2, nil, nil],
                [nil, 2, nil, nil, 4, 2, nil],
                [nil, 1, 1, nil, 1, 2, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil],
                [nil, 3, 3, 1, 1, 1, 1, nil],
                [nil, 4, 4, 6, nil, 1, nil],
                [nil, 1, 2, 1, 2, 1, 1, nil],
                [nil, 2, 1, 2, 1, 1, nil],
                [nil, 5, nil, 5, nil, 1, nil, 1],
                [2, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1238,
            rows: [
                [nil, nil, 1, nil, nil, 1, 3, nil],
                [3, nil, 3, nil, 1, nil, 3],
                [2, 2, nil, 1, 3, nil, 1, 4],
                [1, 4, 1, 1, 5, 1, 4],
                [2, 1, nil, 2, 1, nil, 1, 4],
                [4, 1, 2, 1, 2, 1, 2],
                [1, 1, 1, 3, 3, 3, 2, 4],
                [1, nil, 1, 3, 1, nil, 1],
                [2, 1, 4, 1, 2, 1, 1, 2],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1239,
            rows: [
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, nil, 2, 3, 2, nil, nil],
                [nil, 1, 1, 1, 2, 2, nil],
                [nil, nil, 1, 1, 3, 3, nil, nil],
                [nil, 3, 1, 5, 1, 4, nil],
                [nil, 4, 4, 1, 4, 1, 2, nil],
                [1, 1, 2, 1, 3, 1, 6],
                [nil, 1, 2, 1, 1, 2, 2, nil],
                [1, 5, 1, 1, 4, 6, 1],
                [nil, 1, 2, 2, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1240,
            rows: [
                [1, nil, nil, nil, 2, 2, nil, 1],
                [nil, nil, 4, nil, 1, 1, nil],
                [3, 3, 3, 3, 1, nil, 1, 2],
                [2, nil, 1, nil, 2, 1, 2],
                [1, 1, 1, 2, 1, 3, 1, 5],
                [5, 1, 2, nil, 1, 2, 2],
                [1, 2, 2, 1, 1, 4, 1, 2],
                [1, 3, 3, nil, 3, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
    ]
}
