// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch118 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2341,
            rows: [
                [nil, 3, nil, 1, nil, 3, 1, nil],
                [nil, 1, nil, 1, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, 4, 4, nil, nil],
                [nil, nil, nil, nil, nil, 2, 2, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, 5, 4, 4, 1, 2, nil],
                [nil, 2, 1, 2, nil, nil, nil],
                [nil, 2, nil, nil, 2, 1, nil, nil],
                [nil, 3, 1, 1, 4, 4, nil],
                [nil, 1, 1, 2, 1, 2, 1, nil],
                [nil, 5, 1, 5, 5, 1, nil],
                [nil, 2, 1, 6, 1, 5, 1, nil],
                [nil, 1, 2, 2, 2, 1, nil],
                [nil, 3, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2342,
            rows: [
                [nil, nil, 4, 1, nil, 2, 5, nil],
                [nil, nil, 2, 2, nil, nil, nil],
                [nil, 2, nil, nil, 1, 3, 1, nil],
                [nil, 2, 2, 1, nil, nil, nil],
                [nil, 4, 1, nil, 2, 2, 6, nil],
                [nil, 2, 5, 1, 4, 1, nil],
                [nil, nil, nil, nil, 2, 4, 1, nil],
                [nil, 1, 1, nil, nil, 1, nil],
                [nil, 3, nil, 1, nil, 2, 2, nil],
                [nil, nil, 2, nil, 3, 3, nil],
                [nil, nil, 2, 2, 4, 1, 2, nil],
                [nil, 2, 1, 1, 1, 1, nil],
                [nil, 3, 1, 1, 2, 1, 3, nil],
                [nil, 1, 3, 2, 1, 1, nil],
                [nil, 1, 2, 1, 1, 4, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2343,
            rows: [
                [3, 1, 2, 1, 4, 1, 4, 1],
                [nil, nil, nil, nil, nil, nil, 1],
                [1, 4, 2, 2, 4, 1, 1, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [1, 4, 1, 4, 1, 4, 2, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [1, 2, 1, 3, 1, 1, 3, 1],
                [nil, nil, nil, nil, nil, nil, 5],
                [1, 2, 1, 2, 1, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, 1],
                [1, 2, 2, 7, 3, 4, 4, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [4, 1, 2, 1, 1, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2344,
            rows: [
                [1, 4, 4, 1, 2, 5, 2, 2],
                [4, nil, nil, 1, nil, nil, 4],
                [1, 2, 1, 2, 1, 6, 1, 1],
                [4, nil, nil, 1, nil, nil, 1],
                [2, 2, 2, 1, 4, 1, 6, 1],
                [3, nil, nil, 1, nil, nil, 1],
                [nil, 1, nil, nil, 3, nil, nil, 1],
                [4, 2, 1, 3, 3, 2, 2],
                [nil, 1, nil, nil, 3, nil, nil, 3],
                [1, 1, 4, 1, 1, 3, 1],
                [nil, 2, nil, nil, 1, nil, nil, 3],
                [4, nil, nil, 1, nil, nil, 3],
                [nil, 1, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2345,
            rows: [
                [7, 3, 4, 2, 2, 1, 1, 1],
                [5, 5, 2, 1, 3, 3, 1],
                [4, 2, 2, 1, 4, 3, 1, 4],
                [4, 4, 3, 1, 1, 3, 3],
                [2, 1, 2, 2, 1, 2, 1, 1],
                [2, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2346,
            rows: [
                [4, nil, nil, 1, nil, 3, 4, 4],
                [4, nil, 1, nil, 2, nil, 1],
                [3, nil, nil, 2, nil, nil, nil, 1],
                [3, 1, 2, nil, nil, nil, 2],
                [2, nil, nil, 1, nil, nil, nil, 3],
                [2, 1, 3, nil, nil, nil, 2],
                [nil, nil, nil, 1, nil, 7, 2, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, 2, nil, 5, 3, nil],
                [nil, nil, 3, nil, 2, nil, nil],
                [nil, nil, nil, 1, nil, 1, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, 4, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2347,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, 4, nil, 3, nil, 1, nil],
                [nil, nil, nil, 5, 4, nil, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [2, 4, 4, 1, 4, 1, 1, 1],
                [1, nil, 5, nil, 1, nil, 1],
                [1, 1, 3, 3, 2, 4, 2, 2],
                [2, nil, 2, nil, 2, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2348,
            rows: [
                [2, nil, 2, nil, nil, 3, nil, 1],
                [1, nil, 4, nil, 4, nil, 1],
                [2, nil, nil, 2, 1, nil, nil, 1],
                [4, nil, 2, 4, 1, nil, 2],
                [4, nil, nil, 1, 3, nil, nil, 1],
                [4, nil, 4, 1, 3, nil, 2],
                [2, nil, nil, 2, 2, nil, nil, 1],
                [3, nil, 3, nil, 7, nil, 1],
                [3, nil, nil, 1, 5, nil, nil, 2],
                [3, nil, 3, nil, 1, nil, 1],
                [3, nil, 3, nil, nil, 3, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2349,
            rows: [
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, 2, 1, nil, nil, nil, nil],
                [4, 4, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, nil, 2, 1, nil],
                [5, 1, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, 3, 2, nil],
                [nil, nil, nil, 1, 1, nil, 2, 2],
                [nil, 1, 5, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, 1, 1],
                [nil, 1, 4, nil, nil, nil, nil],
                [1, 1, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [2, 2, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, nil, 3, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2350,
            rows: [
                [nil, 3, nil, nil, nil, nil, 1, nil],
                [2, nil, nil, 1, nil, nil, 3],
                [1, nil, nil, 2, 1, nil, nil, 2],
                [2, nil, nil, 4, nil, nil, 2],
                [2, nil, nil, 2, 2, nil, nil, 2],
                [4, nil, nil, 2, nil, nil, 2],
                [nil, 1, 1, 6, 2, 3, 5, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 3, 3, 3, 1, 2, 7, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2351,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 3, 3, nil, nil],
                [nil, nil, 3, 2, 4, 1, nil, nil],
                [nil, 2, 4, 1, 1, 1, nil],
                [nil, nil, 4, 2, 1, 1, nil, nil],
                [nil, 2, 4, 4, 2, 5, nil],
                [nil, 5, nil, 1, 5, nil, 1, nil],
                [2, 2, 1, 2, 2, 1, 2],
                [nil, 2, nil, 1, 3, nil, 3, nil],
                [3, 1, 1, 3, 1, 6, 1],
                [nil, 1, nil, 5, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2352,
            rows: [
                [nil, nil, 3, 1, 2, nil, nil, nil],
                [nil, 6, nil, nil, 6, nil, nil],
                [nil, nil, 6, 3, 3, 1, 4, nil],
                [nil, 4, 1, 1, nil, nil, 2],
                [nil, nil, 2, 4, 1, 2, 5, nil],
                [nil, 3, 2, 2, nil, nil, 2],
                [nil, 3, nil, nil, 3, 1, 5, nil],
                [nil, 1, 2, 2, 5, 3, nil],
                [nil, 1, nil, nil, 5, 1, 2, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2353,
            rows: [
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, 5, 2, 3, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, 2, 3, 7, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 2, 4, nil, nil],
                [nil, nil, nil, 2, 5, nil, nil, nil],
                [nil, nil, 1, 2, 4, nil, nil],
                [nil, nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2354,
            rows: [
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 3, 5, 1, nil, nil],
                [nil, nil, 2, 3, 3, 1, nil, nil],
                [nil, 2, nil, 4, nil, 3, nil],
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, 3, nil, 4, nil, 4, nil],
                [1, nil, nil, 2, 2, nil, nil, 1],
                [1, 5, nil, 1, nil, 2, 2],
                [1, nil, nil, 2, 3, nil, nil, 1],
                [1, 3, nil, 3, nil, 1, 7],
                [nil, 3, 1, 1, 6, 1, 3, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 2, 2, 1, 4, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2355,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 1, 1, 6, 2, nil, nil],
                [nil, 2, 1, 1, 2, 1, nil],
                [nil, nil, 4, 2, 1, 1, nil, nil],
                [nil, 1, 1, 3, 1, 2, nil],
                [nil, 1, 5, 2, 2, 1, 2, nil],
                [2, 1, 5, 2, 4, 2, 3],
                [nil, 3, 3, 1, 1, 4, 1, nil],
                [2, 1, 1, 1, 2, 2, 1],
                [nil, 1, 2, 2, 3, 1, 2, nil],
                [nil, 2, 1, 2, 1, 1, nil],
                [nil, 2, 1, 1, 2, 2, 1, nil],
                [nil, 2, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2356,
            rows: [
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [nil, 2, nil, nil, nil, 5, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 3, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 5, nil],
                [nil, 1, nil, nil, nil, 3, nil, nil],
                [nil, 3, nil, nil, nil, 2, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 7, nil, nil, nil, 1, nil],
                [nil, 4, nil, nil, nil, 4, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 5, nil, nil, nil, 4, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2357,
            rows: [
                [5, nil, 3, nil, nil, 3, nil, 3],
                [2, nil, 3, nil, 5, 1, 2],
                [nil, 1, nil, 2, 1, nil, 4, nil],
                [1, 1, nil, nil, nil, 1, nil],
                [nil, 3, nil, 3, 3, nil, 3, nil],
                [1, 2, nil, nil, nil, 2, nil],
                [1, nil, 2, 2, 1, 2, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [5, nil, 2, 6, 6, 1, nil, 4],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 2, 1, 2, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2358,
            rows: [
                [nil, 2, 1, nil, nil, nil, nil, nil],
                [2, 1, 1, nil, nil, nil, nil],
                [nil, 2, 2, nil, nil, nil, nil, nil],
                [nil, nil, 3, 5, nil, nil, nil],
                [nil, 4, 4, nil, nil, nil, nil, nil],
                [nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, 3, 6, 2, nil, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 5, 5, 4, nil, nil, nil],
                [nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, 4, 1, 3, nil],
                [nil, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, 1, 6, 2, nil],
                [nil, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2359,
            rows: [
                [2, 2, 2, 1, 4, 3, 1, 1],
                [5, nil, nil, 4, nil, nil, 4],
                [4, nil, nil, 3, 1, nil, nil, 2],
                [nil, nil, nil, 3, nil, nil, nil],
                [1, nil, nil, 2, 1, nil, nil, 3],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2360,
            rows: [
                [nil, 3, 1, 2, 1, 1, 3, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 3, nil, nil, nil, nil, 4, nil],
                [3, 2, 1, 1, 3, 3, 4],
                [nil, 4, nil, nil, nil, nil, 2, nil],
                [1, 2, 2, 5, 4, 3, 1],
                [nil, 6, 1, 3, 3, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
    ]
}
