// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch123 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2441,
            rows: [
                [2, nil, nil, nil, 4, nil, nil, nil],
                [2, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, 4, 2, nil, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [nil, 1, nil, nil, 2, 1, nil, nil],
                [nil, 2, nil, 5, nil, 7, nil],
                [nil, 1, nil, nil, 4, 1, nil, nil],
                [3, nil, nil, 7, 1, 2, nil],
                [nil, 1, nil, nil, 2, 3, nil, nil],
                [2, nil, nil, 1, 3, 2, nil],
                [1, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2442,
            rows: [
                [3, 2, 1, 3, 4, 4, 1, 2],
                [1, 2, 1, 2, 6, 1, 5],
                [7, 3, 3, 3, 1, 4, 4, 2],
                [1, 2, 3, 1, 2, 3, 2],
                [1, 2, 1, 2, 2, 1, 5, 1],
                [2, 1, 2, 1, 2, 3, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2443,
            rows: [
                [3, 1, 3, 1, 3, 5, 1, 5],
                [1, nil, nil, 5, nil, nil, 1],
                [3, 3, 2, 1, 2, 1, 2, 6],
                [3, nil, nil, 1, nil, nil, 1],
                [2, 1, 4, 2, 3, 2, 1, 3],
                [1, nil, nil, 2, nil, nil, 1],
                [nil, 1, nil, nil, 3, nil, nil, 2],
                [3, 2, 4, 2, 1, 2, 1],
                [nil, 2, nil, nil, 1, nil, nil, 4],
                [1, 2, 3, 1, 3, 1, 3],
                [nil, 1, nil, nil, 2, nil, nil, 1],
                [2, nil, nil, 5, nil, nil, 1],
                [nil, 2, nil, nil, 1, nil, nil, 2],
                [1, nil, nil, 2, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2444,
            rows: [
                [nil, 4, nil, 1, nil, 2, nil, 1],
                [2, nil, 4, nil, 1, nil, 3],
                [nil, 1, nil, 2, nil, 3, nil, 2],
                [1, nil, 3, nil, 2, nil, 2],
                [nil, 1, nil, 2, nil, 1, nil, 1],
                [5, nil, 2, nil, 1, nil, 2],
                [nil, 2, nil, 1, nil, 1, nil, 2],
                [6, nil, 1, nil, 1, nil, 1],
                [nil, 3, nil, 7, nil, 1, nil, 1],
                [3, nil, 1, nil, 3, nil, 1],
                [nil, 1, nil, 2, nil, 1, nil, 4],
                [5, nil, 2, nil, 1, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2445,
            rows: [
                [nil, 2, 1, nil, nil, 2, 1, nil],
                [6, nil, nil, nil, nil, nil, 3],
                [5, 1, nil, nil, nil, nil, 3, 3],
                [2, nil, nil, nil, nil, nil, 1],
                [3, 3, nil, nil, nil, nil, 3, 2],
                [1, nil, nil, nil, nil, nil, 3],
                [2, 1, nil, nil, nil, nil, 5, 1],
                [2, nil, nil, nil, nil, nil, 1],
                [5, 1, nil, nil, nil, nil, 1, 2],
                [5, nil, nil, nil, nil, nil, 2],
                [1, 1, nil, nil, nil, nil, 5, 1],
                [2, 1, nil, nil, nil, 2, 4],
                [5, 1, nil, nil, nil, nil, 5, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2446,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 4, 5, 5, 5, nil, nil],
                [nil, nil, 2, 1, 3, nil, nil],
                [nil, nil, 4, 3, 3, 5, nil, nil],
                [nil, nil, 3, 2, 2, nil, nil],
                [nil, nil, 1, 2, 1, 2, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil],
                [nil, nil, 6, 4, 2, 1, nil, nil],
                [nil, nil, 6, 4, 3, nil, nil],
                [nil, nil, 2, 1, 1, 2, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2447,
            rows: [
                [nil, nil, 2, nil, nil, 7, nil, nil],
                [nil, 1, 3, nil, 5, 2, nil],
                [nil, 1, 3, 1, 1, 2, 3, nil],
                [nil, 2, 1, nil, 2, 1, nil],
                [nil, 5, 2, 1, 5, 1, 3, nil],
                [nil, 1, 4, nil, 1, 1, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2448,
            rows: [
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, nil, 1, 4, 2, 1, nil, nil],
                [nil, nil, 5, nil, 1, nil, nil],
                [nil, nil, 3, 1, 6, 1, nil, nil],
                [nil, nil, 4, nil, 2, nil, nil],
                [6, 4, 1, nil, nil, 4, 2, 1],
                [nil, nil, 3, nil, 2, nil, nil],
                [1, 4, 1, nil, nil, 2, 4, 6],
                [nil, nil, 2, nil, 3, nil, nil],
                [nil, nil, 1, 3, 1, 2, nil, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2449,
            rows: [
                [nil, nil, 2, 5, 3, nil, nil, nil],
                [nil, nil, 2, 3, 2, nil, nil],
                [nil, nil, nil, 1, 6, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, nil, 1, nil, 1, nil, 5, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [3, nil, 1, nil, 2, nil, 2, nil],
                [nil, 4, nil, 1, nil, 3, nil],
                [1, nil, 2, nil, 3, nil, 3, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [2, nil, 1, nil, 5, nil, 4, nil],
                [nil, 1, nil, 4, nil, 1, nil],
                [2, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2450,
            rows: [
                [nil, 2, 4, 7, 1, 1, 2, nil],
                [3, nil, nil, nil, nil, nil, 1],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [3, 4, 1, 2, 1, 4, 2],
                [nil, 4, nil, nil, nil, nil, 3, nil],
                [2, 3, 5, 2, 1, 3, 2],
                [nil, 6, 2, 4, 2, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 2, 3, 1, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2451,
            rows: [
                [nil, nil, 3, 2, 1, nil, nil, nil],
                [nil, 2, nil, nil, 3, nil, nil],
                [nil, nil, 1, 5, 5, 5, 1, nil],
                [nil, 2, 3, 1, nil, nil, 5],
                [nil, nil, 6, 3, 3, 1, 4, nil],
                [nil, 2, 2, 1, nil, nil, 4],
                [nil, 4, nil, nil, 3, 3, 1, nil],
                [nil, 1, 2, 3, 2, 1, nil],
                [nil, 2, nil, nil, 1, 7, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2452,
            rows: [
                [1, nil, nil, nil, 5, nil, nil, nil],
                [2, nil, nil, nil, 4, nil, nil],
                [nil, 2, nil, nil, 3, 2, nil, nil],
                [nil, 3, nil, 1, nil, 3, nil],
                [nil, 1, nil, nil, 4, 1, nil, nil],
                [nil, 3, nil, 6, nil, 2, nil],
                [nil, 1, nil, nil, 2, 1, nil, nil],
                [3, nil, nil, 1, 3, 3, nil],
                [nil, 1, nil, nil, 4, 3, nil, nil],
                [1, nil, nil, 1, 5, 2, nil],
                [1, nil, nil, nil, 4, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2453,
            rows: [
                [1, 2, 5, 4, 1, 3, 3, 7],
                [1, 2, 1, 2, 1, 2, 1],
                [6, 2, 1, 2, 5, 1, 2, 1],
                [2, 4, 1, 2, 3, 1, 3],
                [1, 3, 1, 5, 1, 3, 1, 3],
                [1, 5, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2454,
            rows: [
                [2, nil, nil, 1, nil, 2, 4, 2],
                [3, nil, 3, nil, 1, nil, 3],
                [1, nil, nil, 6, nil, nil, nil, 3],
                [3, 2, 2, nil, nil, nil, 6],
                [2, nil, nil, 1, nil, nil, nil, 2],
                [1, 5, 1, nil, nil, nil, 2],
                [nil, nil, nil, 3, nil, 2, 1, nil],
                [nil, nil, 4, nil, 1, nil, nil],
                [nil, nil, nil, 2, nil, 1, 5, nil],
                [nil, nil, 1, nil, 4, nil, nil],
                [nil, nil, nil, 1, nil, 3, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2455,
            rows: [
                [3, 1, 2, 3, 1, 1, 2, 1],
                [3, nil, nil, 2, nil, nil, 4],
                [2, 1, 4, 1, 2, 1, 4, 1],
                [2, nil, nil, 3, nil, nil, 1],
                [4, 1, 6, 1, 5, 5, 1, 2],
                [3, nil, nil, 3, nil, nil, 1],
                [nil, 1, nil, nil, 2, nil, nil, 2],
                [1, 1, 2, 1, 2, 1, 4],
                [nil, 1, nil, nil, 2, nil, nil, 3],
                [1, 3, 2, 1, 2, 4, 1],
                [nil, 3, nil, nil, 5, nil, nil, 4],
                [1, nil, nil, 3, nil, nil, 1],
                [nil, 3, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2456,
            rows: [
                [nil, 2, nil, 1, nil, 3, nil, 2],
                [1, nil, 2, nil, 1, nil, 4],
                [nil, 1, nil, 2, nil, 1, nil, 3],
                [1, nil, 1, nil, 3, nil, 1],
                [nil, 3, nil, 4, nil, 1, nil, 4],
                [2, nil, 1, nil, 5, nil, 1],
                [nil, 2, nil, 1, nil, 7, nil, 2],
                [3, nil, 2, nil, 1, nil, 3],
                [nil, 1, nil, 2, nil, 1, nil, 5],
                [1, nil, 4, nil, 1, nil, 2],
                [nil, 1, nil, 2, nil, 1, nil, 2],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2457,
            rows: [
                [nil, 1, 1, nil, nil, 3, 4, nil],
                [3, nil, nil, nil, nil, nil, 1],
                [5, 1, nil, nil, nil, nil, 3, 1],
                [2, nil, nil, nil, nil, nil, 5],
                [2, 1, nil, nil, nil, nil, 3, 4],
                [1, nil, nil, nil, nil, nil, 2],
                [1, 2, nil, nil, nil, nil, 4, 5],
                [1, nil, nil, nil, nil, nil, 5],
                [1, 2, nil, nil, nil, nil, 3, 3],
                [1, nil, nil, nil, nil, nil, 5],
                [1, 2, nil, nil, nil, nil, 1, 5],
                [6, 1, nil, nil, nil, 5, 1],
                [2, 5, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2458,
            rows: [
                [nil, 4, nil, 4, nil, 2, nil, 5],
                [6, nil, 1, nil, 2, nil, 1],
                [nil, 1, nil, 2, nil, 4, nil, 1],
                [3, nil, 1, nil, 5, nil, 1],
                [nil, 2, nil, 1, nil, 2, nil, 1],
                [2, nil, 2, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, 7, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, 1, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2459,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 1, 2, 2, 6, 1, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [1, nil, 1, 2, 1, 7, nil, 5],
                [2, nil, nil, nil, nil, nil, 1],
                [nil, 2, 1, 2, 3, 1, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 4, 1, 3, nil, nil],
                [nil, nil, 1, 4, 2, nil, nil],
                [nil, nil, 1, 2, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2460,
            rows: [
                [2, nil, 2, nil, 5, nil, 1, nil],
                [nil, 4, nil, 2, nil, 6, nil],
                [nil, nil, nil, 6, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, nil, 2, nil],
                [1, nil, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [nil, 3, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
    ]
}
