// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch145 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2881,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [1, 3, 1, 5, nil, nil, nil],
                [1, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 2, 2, 1, 1],
                [3, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 4, 1, 2, 1],
                [4, nil, nil, nil, 3, nil, nil, 1],
                [2, 1, 2, 1, nil, nil, nil],
                [4, nil, nil, nil, 3, nil, nil, 3],
                [1, 5, 2, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, 2],
                [nil, nil, nil, 1, 2, 1, 1],
                [nil, nil, nil, 1, nil, nil, nil, 1],
                [nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2882,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 5, 1, 3, 1, 2, nil],
                [1, nil, nil, nil, nil, nil, 2],
                [1, nil, 2, 5, 5, 4, nil, 2],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, 1, 2, 1, 3, 3, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 3, 2, nil, nil],
                [nil, nil, 1, 2, 3, nil, nil],
                [nil, nil, 1, 1, 2, 1, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2883,
            rows: [
                [nil, nil, 1, 2, 1, nil, nil, nil],
                [nil, nil, 2, 3, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, nil, 1, nil, 3, nil, 1, nil],
                [nil, 2, nil, 1, nil, 4, nil],
                [2, nil, 1, nil, 1, nil, 3, nil],
                [nil, 1, nil, 4, nil, 1, nil],
                [2, nil, 3, nil, 1, nil, 2, nil],
                [nil, 1, nil, 3, nil, 1, nil],
                [2, nil, 1, nil, 2, nil, 1, nil],
                [nil, 2, nil, 4, nil, 1, nil],
                [3, nil, 1, nil, 2, nil, 1, nil],
                [nil, 2, nil, 1, nil, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2884,
            rows: [
                [nil, nil, 1, nil, nil, 4, nil, nil],
                [nil, 2, nil, nil, 3, nil, nil],
                [nil, nil, nil, 4, nil, nil, 1, nil],
                [nil, nil, 2, nil, nil, 1, nil],
                [nil, nil, nil, nil, 2, nil, nil, 1],
                [nil, nil, nil, 3, nil, nil, 1],
                [nil, nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, nil, 5, nil, nil],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, 2, 1, 2, 3, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2885,
            rows: [
                [nil, 1, nil, nil, nil, nil, 4, nil],
                [1, nil, nil, 2, nil, nil, 1],
                [2, nil, nil, 3, 1, nil, nil, 4],
                [2, nil, nil, 5, nil, nil, 1],
                [5, nil, nil, 1, 2, nil, nil, 1],
                [3, nil, nil, 1, nil, nil, 2],
                [nil, 3, 1, 2, 1, 3, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 1, 4, 1, 3, 1, 2, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2886,
            rows: [
                [nil, 2, 1, nil, 3, 2, nil, nil],
                [4, nil, 3, 1, nil, 2, nil],
                [2, nil, nil, nil, nil, nil, 3, nil],
                [2, 1, 3, nil, nil, 1, 1],
                [2, nil, nil, nil, nil, nil, 3, nil],
                [2, 3, 1, nil, nil, 3, 3],
                [nil, 1, 2, 3, 1, 3, 2, 2],
                [nil, 3, 2, nil, nil, 2, 1],
                [nil, 2, 3, 3, 2, 1, 2, 1],
                [nil, 3, 1, nil, nil, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2887,
            rows: [
                [nil, nil, 3, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, 1, 1, 2, nil],
                [1, nil, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, 1, 4, 1, nil],
                [2, nil, nil, nil, nil, 3, nil],
                [1, 2, 5, 3, nil, 4, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [3, 1, 2, 1, nil, 2, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2888,
            rows: [
                [3, 2, nil, 1, 2, nil, 1, 2],
                [2, nil, nil, 1, nil, nil, 2],
                [1, nil, nil, 2, nil, nil, 3, nil],
                [1, nil, nil, 3, nil, nil, 1],
                [3, nil, nil, 1, nil, nil, 1, nil],
                [2, nil, nil, 3, nil, nil, 5],
                [1, nil, nil, 3, nil, nil, 1, nil],
                [1, nil, nil, 4, nil, nil, 2],
                [1, nil, nil, 2, nil, nil, 1, nil],
                [3, nil, nil, 2, nil, nil, 3],
                [3, nil, nil, 1, nil, nil, 4, nil],
                [3, nil, nil, 4, nil, nil, 1],
                [2, nil, nil, 1, nil, nil, 1, nil],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2889,
            rows: [
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [3, 2, nil, nil, nil, 3, 2],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [4, 3, nil, nil, nil, 1, 2],
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [1, 3, nil, nil, nil, 1, 3],
                [nil, 1, nil, nil, nil, nil, 4, nil],
                [3, 2, nil, nil, nil, 1, 3],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [2, 1, nil, nil, nil, 1, 3],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2890,
            rows: [
                [nil, 3, nil, nil, 3, 1, 3, nil],
                [1, nil, nil, 3, 5, 1, nil],
                [2, nil, nil, 1, 4, 1, nil, nil],
                [2, nil, 1, 2, 1, nil, nil],
                [3, nil, nil, 2, 1, 2, nil, nil],
                [4, nil, 4, 1, 2, nil, nil],
                [1, nil, nil, 2, 1, 2, nil, nil],
                [1, nil, 2, 1, 2, 2, nil],
                [1, nil, nil, 2, 1, 2, nil, nil],
                [1, nil, 2, 1, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2891,
            rows: [
                [nil, 1, 2, 1, 1, 1, 2, nil],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [2, 4, 1, 4, 2, 1, 4],
                [nil, 4, nil, nil, nil, nil, 1, nil],
                [2, 2, 1, 3, 1, 1, 1],
                [nil, 2, 1, 2, 1, 5, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 2, 1, 2, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2892,
            rows: [
                [nil, 2, nil, 1, nil, 3, nil, 3],
                [1, nil, 3, nil, 1, nil, 2],
                [nil, 1, nil, 3, nil, 1, nil, 2],
                [1, nil, 3, nil, 3, nil, 1],
                [nil, 4, nil, 1, nil, 5, nil, 1],
                [4, nil, 1, nil, 1, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2893,
            rows: [
                [3, nil, nil, 2, nil, 3, 1, 1],
                [2, nil, 3, nil, 2, nil, 1],
                [2, nil, nil, 3, nil, nil, nil, 1],
                [2, 2, 3, nil, nil, nil, 1],
                [2, nil, nil, 3, nil, nil, nil, 2],
                [1, 5, 5, nil, nil, nil, 3],
                [nil, nil, nil, 1, nil, 3, 2, nil],
                [nil, nil, 1, nil, 4, nil, nil],
                [nil, nil, nil, 2, nil, 3, 1, nil],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, nil, 2, nil, 1, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, 1, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2894,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 4],
                [1, nil, 5, 2, 1, nil, 4],
                [nil, 1, 3, nil, nil, 2, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 3, 1, nil, nil, 1, 4, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 4, 3, nil, nil, 3, 1, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 3, 1, nil, nil, 2, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, nil, 3, nil, nil, 2, nil, nil],
                [nil, nil, 3, 1, 4, nil, nil],
                [nil, nil, 1, nil, nil, 4, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2895,
            rows: [
                [nil, nil, 2, 1, 2, nil, nil, nil],
                [nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, 1, 2, 3, 1, 2, nil],
                [nil, 2, 1, 2, nil, nil, 1],
                [nil, nil, 2, 2, 1, 3, 2, nil],
                [nil, 1, 1, 4, nil, nil, 2],
                [nil, 3, nil, nil, 1, 4, 1, nil],
                [nil, 3, 3, 1, 4, 1, nil],
                [nil, 4, nil, nil, 4, 1, 5, nil],
                [nil, 2, 1, 2, 1, 2, nil],
                [nil, nil, 1, 2, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2896,
            rows: [
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, 2, 1, 2, 3, 1, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, 2, 1, 5, 2, 1, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, 4, 1, 2, 5, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2897,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, 4, 2, 3, 1, nil, nil],
                [nil, 2, 1, 5, 1, 2, nil],
                [nil, nil, 3, 1, 2, 1, nil, nil],
                [nil, 1, 2, 1, 2, 1, nil],
                [nil, 2, 1, 4, 1, 3, 1, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 2, 1, 1, 3, 1, 2, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2898,
            rows: [
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil],
                [nil, nil, nil, nil, 3, 2, nil, nil],
                [nil, nil, nil, nil, 3, 1, nil],
                [nil, nil, nil, nil, nil, 2, 4, nil],
                [nil, nil, nil, nil, nil, 1, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, 2, 1, nil],
                [1, 3, nil, nil, 2, 1, nil],
                [nil, 3, 1, nil, nil, 2, 3, nil],
                [3, 1, nil, nil, 5, 1, nil],
                [nil, 3, 1, nil, nil, 2, 1, nil],
                [2, 2, nil, nil, 1, 1, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, 1, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2899,
            rows: [
                [nil, 2, 2, nil, nil, 1, 2, nil],
                [4, nil, 1, nil, 3, nil, 3],
                [1, nil, nil, 2, 1, nil, nil, 3],
                [1, nil, nil, nil, nil, nil, 2],
                [1, nil, nil, 2, 1, nil, nil, 3],
                [3, nil, nil, nil, nil, nil, 5],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 5, nil, nil, 1, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2900,
            rows: [
                [5, 4, nil, nil, nil, nil, 1, 2],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, nil, 2, 6, 1, 2, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 3, 2, 1, 2, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 2, nil, nil, nil],
                [3, 2, nil, nil, nil, nil, 1, 3],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, 3, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
    ]
}
