// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch30 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 581,
            rows: [
                [nil, 5, 5, nil, 5, 5, 5, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 1, 1, 1, nil, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 1, 3, 3, nil, 3, 3, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 2, 2, nil, 2, 4, 4, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, 6, 1, nil, 7, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 1, 1, 5, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, 3, nil, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 582,
            rows: [
                [3, 3, nil, nil, nil, nil, 1, 2],
                [2, 2, nil, nil, nil, 2, 1],
                [1, 1, nil, nil, nil, nil, 3, 3],
                [3, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 5],
                [5, 5, nil, nil, nil, nil, 5, 3],
                [4, nil, nil, nil, nil, nil, 7],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, 2, nil, nil, nil, 1, 1],
                [4, 4, nil, nil, nil, nil, 4, 1],
                [1, 6, nil, nil, nil, 6, 7],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 583,
            rows: [
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
                [nil, 2, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 3, nil, 3],
                [7, nil, 7, nil, 2, nil, 2],
                [nil, 2, nil, 4, nil, 4, nil, 1],
                [1, nil, 1, nil, 5, nil, 5],
                [nil, 5, nil, 5, nil, 1, nil, 1],
                [1, nil, 1, nil, 3, nil, 3],
                [nil, 3, nil, 3, nil, 3, nil, 3],
                [7, nil, 2, nil, 2, nil, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 584,
            rows: [
                [4, 2, nil, nil, nil, nil, 2, 2],
                [1, 1, nil, nil, nil, 1, 1],
                [3, 3, nil, nil, nil, nil, 3, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [3, 3, nil, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, 5],
                [5, 5, nil, nil, nil, nil, 4, 6],
                [6, 4, nil, nil, nil, 2, 7],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 585,
            rows: [
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, nil, 2, 2, 2, nil, 2],
                [2, nil, nil, 2, 2, nil, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
                [2, nil, nil, 6, 6, nil, nil, 4],
                [4, nil, 3, nil, 3, nil, 3],
                [3, nil, 3, nil, nil, 4, nil, 4],
                [5, nil, nil, nil, nil, nil, 5],
                [7, nil, 7, nil, nil, 3, nil, 3],
                [4, nil, nil, nil, nil, nil, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 586,
            rows: [
                [nil, nil, 1, 5, 5, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, nil, 3, nil, 3, nil, 3, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [2, nil, 2, nil, 2, nil, 1, nil],
                [nil, 1, nil, 4, nil, 4, nil],
                [4, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 7, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 6, nil, 7, nil],
                [nil, 2, nil, 2, nil, 2, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 587,
            rows: [
                [nil, 3, 3, nil, nil, 3, 1, nil],
                [1, 1, nil, nil, 1, 1, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 4, nil, 3, nil, 2, nil],
                [2, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 5, nil],
                [5, nil, 3, nil, 3, nil, 3, nil],
                [nil, 3, nil, 3, nil, 4, nil],
                [4, nil, 4, nil, 4, nil, 4, nil],
                [nil, 1, nil, 6, nil, 6, nil],
                [4, nil, 4, nil, 4, nil, 1, nil],
                [nil, 1, nil, 1, nil, 7, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 588,
            rows: [
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 2, nil, nil, nil, nil, 6, 4],
                [4, nil, nil, nil, nil, nil, 4],
                [4, 4, nil, nil, nil, nil, 4, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 5, nil, nil, nil, nil, 5, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [3, 3, nil, nil, nil, nil, 3, 2],
                [2, 2, nil, nil, nil, 2, 2],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [5, 4, nil, nil, nil, 6, 7],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 589,
            rows: [
                [nil, 6, nil, 6, nil, 1, nil, 2],
                [1, nil, 2, nil, 5, nil, 5],
                [nil, 5, nil, 5, nil, 5, nil, 5],
                [4, nil, 4, nil, 4, nil, 4],
                [nil, 4, nil, 4, nil, 4, nil, 2],
                [7, nil, 3, nil, 3, nil, 3],
                [nil, 3, nil, 3, nil, 3, nil, 2],
                [2, nil, 1, nil, 1, nil, 1],
                [nil, 2, nil, 7, nil, 2, nil, 1],
                [2, nil, 2, nil, 2, nil, 2],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 4
        ),
        LevelTemplate(
            levelNumber: 590,
            rows: [
                [nil, 5, nil, 5, nil, 5, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, nil, 7, nil, 7],
                [nil, 2, nil, 2, nil, 4, nil, 4],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, 6, nil],
                [nil, nil, nil, nil, nil, nil, 6, nil],
                [nil, nil, nil, nil, 4, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 591,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 5, 4, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [2, 2, 2, 1, 1, 6, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 2, 7, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 592,
            rows: [
                [1, nil, 1, nil, 1, nil, 3, nil],
                [nil, 3, nil, 3, nil, 1, nil],
                [nil, nil, nil, 6, 6, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 4, nil],
                [4, nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, 7, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 7, nil, nil, nil],
                [7, nil, nil, nil, nil, nil, nil, 2],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 593,
            rows: [
                [nil, 4, 4, nil, nil, 4, 4, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [3, nil, nil, nil, nil, nil, 3],
                [3, 3, nil, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 3, 3],
                [3, 3, nil, nil, nil, 3, 3],
                [3, 6, nil, nil, nil, nil, 5, 5],
                [6, 3, nil, nil, nil, 5, 7],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 594,
            rows: [
                [3, 3, nil, nil, nil, nil, 3, 3],
                [3, 3, nil, nil, nil, 1, 1],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 3],
                [3, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 6],
                [6, 6, nil, nil, nil, 4, 1],
                [1, 1, nil, nil, nil, nil, 1, 4],
                [4, 5, nil, nil, nil, 5, 7],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 595,
            rows: [
                [nil, 5, nil, nil, nil, nil, 5, nil],
                [5, 3, nil, nil, nil, 3, 3],
                [nil, 7, nil, nil, nil, nil, 7, nil],
                [3, 3, nil, nil, nil, 3, 3],
                [nil, 3, nil, nil, nil, nil, 1, nil],
                [1, 2, nil, nil, nil, 2, 1],
                [nil, 1, nil, nil, nil, nil, 4, nil],
                [4, 1, nil, nil, nil, 1, 1],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [1, 4, nil, nil, nil, 4, 2],
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 596,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 1, nil, 1, 1, nil, nil],
                [nil, 3, nil, nil, nil, 3, 1, nil],
                [1, 1, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, 1, 1, 1, 1],
                [nil, nil, 1, 1, nil, nil, nil, 1],
                [1, 2, nil, 2, 2, 1, 1],
                [nil, 1, nil, 1, nil, 1, 3, nil],
                [3, nil, nil, nil, 3, 3, 1],
                [nil, 1, 1, 1, 1, 1, 1, 1],
                [nil, 1, 2, 2, 2, 5, 5],
                [nil, 1, 1, 1, 2, 4, 4, 4],
                [nil, 4, 3, 3, 3, 2, 2],
                [nil, nil, 2, 6, 3, 6, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 597,
            rows: [
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, nil, 1, nil, nil, nil, 1],
                [1, nil, 1, nil, nil, 1, 2, 2],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 4, 3, nil, 3, nil, 3],
                [nil, 3, nil, 3, nil, 2, 2],
                [2, nil, 2, 2, nil, nil, 2, 2],
                [nil, 2, nil, 2, 2, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil, 2],
                [nil, 3, nil, 3, 3, 6, nil],
                [nil, 1, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, 1, 1, nil, 1],
                [1, nil, 1, nil, 1, 1, 1],
                [1, 5, nil, nil, 5, nil, 2, 2],
                [3, 3, 5, 5, 5, 4, 4],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 598,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 1, nil, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, 1, nil],
                [3, 3, 3, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, 3, nil, nil],
                [nil, 3, nil, 3, 3, 3, 3],
                [nil, nil, 1, 1, nil, nil, nil, 1],
                [1, 1, nil, 1, 1, 1, 5],
                [nil, 5, nil, 2, nil, 2, 1, nil],
                [1, nil, nil, nil, 1, 6, 6],
                [nil, 6, 1, 1, 1, 1, 1, 1],
                [nil, 4, 2, 4, 4, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, 1],
                [nil, 1, 1, 1, 4, 2, 2],
                [nil, nil, 2, 2, 2, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 599,
            rows: [
                [2, 2, 2, nil, 3, 3, 3, nil],
                [3, 1, nil, 1, 2, nil, nil],
                [nil, 2, nil, 2, 2, nil, nil, nil],
                [2, nil, 2, nil, 2, nil, nil],
                [2, nil, nil, 2, nil, 2, nil, nil],
                [2, nil, nil, 2, nil, 1, 1],
                [1, nil, 6, 6, nil, nil, 6, nil],
                [6, nil, 6, 1, 3, 3, 3],
                [3, nil, 3, nil, nil, nil, 3, nil],
                [3, nil, nil, 3, nil, 3, nil],
                [1, 1, 1, 1, 1, 1, nil, 1],
                [nil, 1, 1, 1, nil, nil, nil],
                [4, nil, nil, 4, 4, nil, 4, 1],
                [1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, 1, 1, nil, nil, 5],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 600,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, 2, nil, 2, 2, nil, nil],
                [nil, 2, nil, nil, nil, 2, 2, nil],
                [2, 2, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, 1, 4, 4, 1],
                [nil, nil, 5, 5, nil, nil, nil, 1],
                [1, 1, nil, 1, 1, 1, 1],
                [nil, 1, nil, 1, nil, 1, 1, nil],
                [1, nil, nil, nil, 6, 3, 3],
                [nil, 3, 3, 3, 3, 3, 3, 3],
                [nil, 3, 1, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, 1],
                [nil, 1, 1, 1, 4, 6, 6],
                [nil, nil, 1, 4, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
    ]
}
