// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch31 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 601,
            rows: [
                [nil, nil, 1, nil, 3, nil, nil, nil],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, 3, nil, 3, 3, nil, nil, nil],
                [nil, 3, 1, nil, nil, 1, nil],
                [nil, 1, 1, 2, nil, 2, 2, nil],
                [nil, 2, 2, nil, nil, nil, nil],
                [nil, nil, 2, nil, 2, 2, nil, nil],
                [nil, 2, 2, nil, nil, 2, nil],
                [nil, nil, nil, 2, nil, 6, 6, nil],
                [nil, nil, 6, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 4, 4, 5, 5, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 4, 4, 4, 4, 4, nil],
                [nil, 1, 4, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 602,
            rows: [
                [nil, 4, nil, nil, nil, 4, nil, 4],
                [nil, nil, nil, 3, nil, 3, 3],
                [6, 6, 6, nil, 6, 1, nil, 1],
                [1, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, 1, nil, 1, nil, 1],
                [nil, nil, 1, 5, 5, nil, nil],
                [3, 3, 3, 2, nil, nil, nil, nil],
                [2, 2, 2, 2, nil, 2, 2],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [1, 1, nil, nil, nil, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, 2, nil, 2, 2, nil],
                [2, nil, 2, nil, nil, 2, 2, nil],
                [nil, 5, nil, nil, nil, 5, 5],
                [nil, nil, 1, nil, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 603,
            rows: [
                [1, 1, 1, 1, 1, 1, nil, 1],
                [1, 1, nil, 1, nil, 1, 2],
                [2, nil, 2, 1, 1, 1, 1, 1],
                [1, 2, nil, 6, nil, 6, 6],
                [nil, 6, 1, nil, 1, 1, 1, 1],
                [2, nil, nil, nil, 2, 2, 2],
                [nil, nil, 2, nil, nil, 1, 1, nil],
                [3, nil, nil, nil, nil, 3, nil],
                [3, 3, 2, 2, 2, 2, 2, nil],
                [2, nil, 2, nil, nil, nil, 1],
                [1, 3, 1, 1, 4, 4, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 3, nil, 3, 3, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 604,
            rows: [
                [nil, nil, nil, 1, 1, 2, 2, nil],
                [nil, nil, 2, nil, nil, nil, 2],
                [2, nil, 2, nil, nil, 2, 2, 2],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, nil, 2, nil, 2],
                [nil, 2, nil, 5, nil, 5, 5],
                [5, nil, 5, 4, nil, nil, 4, 4],
                [nil, 4, nil, 4, 4, nil, nil],
                [nil, nil, nil, nil, 3, 3, nil, 3],
                [nil, 3, nil, 3, 1, 1, nil],
                [nil, 3, nil, nil, 3, 1, nil, nil],
                [nil, nil, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, 1, 1, nil, 1],
                [3, nil, 3, nil, 3, 1, 1],
                [1, 1, nil, nil, 1, nil, 1, 1],
                [1, 1, 1, 1, 1, 1, 6],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 605,
            rows: [
                [nil, nil, nil, 6, 6, nil, nil, nil],
                [nil, 6, nil, 1, 1, nil, nil],
                [nil, 3, nil, nil, nil, 3, 1, nil],
                [5, 1, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, 2, 2, 2, 2],
                [nil, nil, 2, 2, nil, nil, nil, 2],
                [2, 2, nil, 1, 1, 1, 3],
                [nil, 3, nil, 3, nil, 3, 3, nil],
                [3, nil, nil, nil, 3, 3, 1],
                [nil, 1, 1, 1, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 4, 4],
                [nil, 4, 4, 1, 5, 1, 1, 1],
                [nil, 1, 1, 1, 2, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 606,
            rows: [
                [nil, nil, 6, 6, 6, nil, 6, 1],
                [1, 1, 1, 1, nil, nil, nil],
                [1, 1, nil, nil, nil, 1, nil, 1],
                [1, nil, 1, 1, 1, 1, 1],
                [1, nil, 1, 1, nil, nil, 1, nil],
                [nil, 1, nil, nil, 1, nil, 1],
                [2, 2, nil, nil, 2, 2, 2, 2],
                [nil, nil, nil, 2, nil, nil, 2],
                [2, 1, 1, nil, nil, 1, nil, 1],
                [1, nil, nil, 1, 1, nil, nil],
                [nil, nil, 1, nil, 4, nil, 2, 2],
                [2, nil, 2, 2, nil, 2, nil],
                [3, nil, nil, nil, nil, 1, 1, 1],
                [6, nil, 3, nil, 3, nil, 3],
                [3, 3, nil, 4, 3, 3, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 607,
            rows: [
                [nil, 2, 2, nil, nil, nil, 2, nil],
                [nil, nil, 1, 1, nil, 1, nil],
                [nil, 1, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, 1, 1, nil, nil, 1, nil],
                [nil, 1, 1, nil, nil, 1, nil],
                [nil, 1, 2, 2, 1, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, 1, 4, nil, nil, nil],
                [nil, nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 3, 3, nil, 3, nil],
                [nil, 3, 3, 3, 3, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 4, 4, 4, 6, 4, nil],
                [nil, 6, 6, 5, 5, 5, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 608,
            rows: [
                [2, 2, 2, nil, 2, 2, 2, nil],
                [2, 2, nil, 2, 3, nil, nil],
                [nil, 3, nil, 3, 3, nil, nil, nil],
                [1, nil, 1, nil, 1, nil, nil],
                [1, nil, nil, 1, nil, 1, nil, nil],
                [1, nil, nil, 1, nil, 1, 1],
                [1, nil, 1, 3, nil, nil, 3, nil],
                [3, nil, 3, 3, 3, 3, 3],
                [3, nil, 2, nil, nil, nil, 1, nil],
                [1, nil, nil, 1, nil, 1, nil],
                [5, 4, 4, 4, 6, 6, nil, 6],
                [nil, 6, 6, 4, nil, nil, nil],
                [2, nil, nil, 1, 2, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 609,
            rows: [
                [nil, nil, 2, nil, 3, nil, nil, nil],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, 3, nil, 4, 4, nil, nil, nil],
                [nil, 4, 4, nil, nil, 4, nil],
                [nil, 4, 4, 4, nil, 2, 2, nil],
                [nil, 2, 2, nil, nil, nil, nil],
                [nil, nil, 2, nil, 1, 1, nil, nil],
                [nil, 1, 1, nil, nil, 6, nil],
                [nil, nil, nil, 6, nil, 6, 1, nil],
                [nil, nil, 1, 1, 2, 2, nil],
                [nil, 2, 2, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 5, 5, nil],
                [nil, 1, 3, 3, 3, 1, 2, nil],
                [nil, 2, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 610,
            rows: [
                [nil, nil, 1, nil, 3, 3, nil, nil],
                [nil, 3, nil, 3, nil, nil, 3],
                [3, nil, 4, nil, nil, 4, nil, 4],
                [5, 5, nil, nil, 5, nil, 5],
                [nil, 5, 1, nil, nil, 1, 1, nil],
                [nil, 1, nil, nil, nil, nil, 1],
                [1, 1, 1, nil, nil, 1, 1, 1],
                [1, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [1, 1, 1, 1, nil, 3, nil],
                [3, nil, 3, 2, nil, nil, 2, 2],
                [2, nil, nil, 2, 2, 2, nil],
                [nil, 2, 2, 2, nil, 6, nil, 3],
                [2, 2, 3, 3, 3, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 611,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, 1, 1, nil],
                [nil, nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, 1],
                [nil, 1, nil, 2, nil, 2, nil, nil],
                [nil, 2, 2, 2, 2, nil, nil],
                [2, 1, nil, 1, nil, 1, 1, 1],
                [1, 1, nil, nil, 1, nil, 1],
                [1, nil, 1, 1, 2, 2, 2, 2],
                [nil, 2, nil, 4, 4, nil, 4],
                [nil, 4, 4, nil, nil, 4, 4, 4],
                [nil, 4, 1, 1, 5, nil, 1],
                [nil, 6, 6, 6, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, 3, 3, 3, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 612,
            rows: [
                [nil, 3, 3, 1, 1, nil, 2, nil],
                [2, nil, 3, 3, 3, 3, 3],
                [6, nil, 6, nil, 6, nil, nil, 1],
                [nil, 4, 4, 4, nil, nil, 4],
                [1, nil, 1, nil, 1, 2, 2, nil],
                [nil, 2, nil, 2, nil, 2, 2],
                [2, 1, nil, 1, 1, nil, 1, 1],
                [nil, nil, nil, nil, 1, 1, nil],
                [1, nil, 1, 1, 1, nil, 1, 1],
                [nil, nil, 1, nil, 1, nil, nil],
                [1, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [1, nil, 1, nil, nil, 1, nil, 2],
                [2, nil, nil, 2, nil, nil, 4],
                [4, 2, 5, nil, nil, nil, nil, nil],
                [5, nil, nil, 3, 2, 2, 2],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 613,
            rows: [
                [nil, 2, 4, 4, 4, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, nil, 1, nil],
                [nil, nil, 1, nil, nil, nil, 1, nil],
                [nil, 2, nil, 2, 3, nil, nil],
                [nil, 3, 3, 3, nil, 3, nil, nil],
                [nil, 3, 3, nil, 3, 2, nil],
                [nil, nil, nil, 1, nil, 2, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, nil, 2, 2, 2, nil],
                [nil, 2, nil, 2, 6, 1, 1, nil],
                [nil, 1, 1, 4, 4, 5, nil],
                [nil, 1, 1, 1, 1, 1, 4, nil],
                [nil, 4, 5, 3, 6, 6, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 614,
            rows: [
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, nil, 1, nil, nil, nil, 1],
                [1, nil, 1, nil, nil, 1, 1, 1],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, 1],
                [4, nil, 4, 4, nil, nil, 4, 4],
                [nil, 4, nil, 2, 2, nil, nil],
                [nil, nil, nil, nil, 3, 3, nil, 3],
                [nil, 3, nil, 2, 2, 2, nil],
                [nil, 2, nil, nil, 2, 2, nil, nil],
                [nil, nil, nil, 5, nil, 5, nil],
                [nil, nil, nil, nil, 5, 5, nil, 5],
                [2, nil, 3, nil, 3, 3, 3],
                [3, 2, nil, nil, 2, nil, 2, 2],
                [2, 2, 3, 2, 2, 1, 6],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 615,
            rows: [
                [nil, 3, 3, nil, 1, 3, 3, nil],
                [3, 3, 3, nil, nil, nil, 3],
                [2, nil, 2, 2, 2, 2, nil, 2],
                [nil, 2, nil, 2, 2, nil, 2],
                [nil, nil, 1, 1, nil, nil, 1, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, 1, 1],
                [nil, 4, 4, nil, nil, nil, nil],
                [4, 4, nil, nil, nil, nil, 4, 4],
                [4, nil, 1, 1, nil, nil, 5],
                [nil, nil, 5, nil, 5, nil, 1, 1],
                [nil, nil, nil, 1, nil, 1, 1],
                [nil, 1, 1, nil, 3, 3, 3, nil],
                [nil, 3, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 6, 6, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 616,
            rows: [
                [nil, nil, nil, 2, 1, 2, 2, nil],
                [nil, nil, 2, nil, nil, nil, 2],
                [2, nil, 2, nil, nil, 2, 2, 2],
                [nil, nil, 2, 5, 5, nil, nil],
                [nil, nil, 5, 5, nil, 5, nil, 1],
                [nil, 1, nil, 1, nil, 1, 1],
                [1, nil, 3, 2, nil, nil, 2, 2],
                [nil, 3, nil, 3, 3, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil, 1],
                [nil, 1, nil, 1, 2, 2, nil],
                [nil, 2, nil, nil, 3, 3, nil, nil],
                [nil, nil, nil, 3, nil, 3, nil],
                [nil, nil, nil, nil, 3, 3, nil, 1],
                [1, nil, 1, nil, 4, 4, 4],
                [4, 4, nil, nil, 1, nil, 1, 1],
                [1, 4, 1, 1, 1, 1, 6],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 617,
            rows: [
                [nil, 2, 2, nil, 2, 1, 1, 1],
                [2, 2, 2, 2, 2, 2, 2],
                [nil, 2, nil, nil, 2, nil, 2, 2],
                [nil, 2, nil, nil, nil, nil, nil],
                [2, 1, nil, nil, 1, 1, 1, nil],
                [1, nil, 1, nil, 1, nil, 1],
                [3, nil, 3, 4, nil, 4, 1, nil],
                [nil, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, 1, 1, 1, nil, 1, 1],
                [1, 1, 1, 1, 6, 6, 1, 1],
                [1, nil, 1, 4, nil, nil, nil],
                [nil, 4, nil, nil, 4, nil, nil, nil],
                [3, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, 3, 3, nil],
                [nil, 3, 5, 5, 5, 5, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 618,
            rows: [
                [nil, nil, nil, 2, 2, 2, 2, nil],
                [nil, nil, 2, nil, nil, nil, 2],
                [3, nil, 3, nil, nil, 4, 4, 4],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 1, 1, nil, 2, nil, 2],
                [nil, 2, nil, 2, nil, 2, 2],
                [2, nil, 2, 2, nil, nil, 2, 2],
                [nil, 3, nil, 3, 3, nil, nil],
                [nil, nil, nil, nil, 3, 3, nil, 3],
                [nil, 1, nil, 1, 1, 5, nil],
                [nil, 5, nil, nil, 5, 5, nil, nil],
                [nil, nil, nil, 5, nil, 1, nil],
                [nil, nil, nil, nil, 1, 6, nil, 1],
                [1, nil, 1, nil, 1, 1, 1],
                [1, 1, nil, nil, 1, nil, 1, 1],
                [1, 1, 1, 1, 1, 3, 3],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 619,
            rows: [
                [nil, 2, 2, nil, 2, 2, 1, nil],
                [1, 1, 1, nil, nil, nil, 1],
                [1, nil, 1, 1, 1, 1, nil, 1],
                [nil, 1, nil, 1, 1, nil, 1],
                [nil, nil, 2, 2, nil, nil, 2, nil],
                [nil, 2, 2, nil, 2, 1, nil],
                [1, nil, nil, nil, nil, nil, 1, 1],
                [nil, 4, 4, nil, nil, nil, nil],
                [4, 4, nil, nil, nil, nil, 3, 5],
                [5, nil, 5, 6, nil, nil, 6],
                [nil, nil, 3, nil, 3, nil, 3, 3],
                [nil, nil, nil, 4, nil, 4, 4],
                [nil, 3, 3, nil, 3, 3, 3, nil],
                [nil, 3, nil, nil, 3, nil, nil],
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 620,
            rows: [
                [nil, 1, 1, nil, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 1, nil, nil, 2, nil, 2, 2],
                [nil, 2, nil, nil, nil, nil, nil],
                [2, 2, nil, nil, 1, 1, 1, nil],
                [1, nil, 1, nil, 1, nil, 3],
                [3, nil, 3, 3, nil, 3, 3, nil],
                [nil, nil, nil, 3, nil, nil, 5],
                [nil, nil, nil, 5, nil, 5, 5, nil],
                [nil, 2, 2, 2, nil, 2, 2],
                [2, 2, 1, 1, 1, 1, 4, 4],
                [4, nil, 4, 4, nil, nil, nil],
                [nil, 2, nil, nil, 2, nil, nil, nil],
                [6, nil, nil, nil, nil, 6, nil],
                [nil, nil, nil, nil, nil, 1, 1, nil],
                [nil, 1, 1, 1, 2, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
    ]
}
