// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch141 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2801,
            rows: [
                [nil, nil, 1, nil, nil, 3, nil, nil],
                [nil, nil, 5, 3, 1, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 1, 3, 4, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 3, 1, 2, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 1, 4, 4, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, 2, 1, 3, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2802,
            rows: [
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [1, 3, 1, 1, 3, 3, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 2, 1, 1, 4, 1, 5, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2803,
            rows: [
                [nil, 1, 5, nil, 1, 3, nil, nil],
                [nil, 1, 2, nil, 3, 1, nil],
                [nil, 2, nil, nil, nil, 3, nil, nil],
                [nil, 2, nil, nil, nil, 3, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 4, 1, 4, nil, nil],
                [nil, nil, 1, 3, 2, nil, nil, nil],
                [nil, 1, 4, 1, nil, nil, nil],
                [nil, 3, 1, 1, nil, nil, nil, nil],
                [nil, 4, 1, 5, nil, nil, nil],
                [nil, 1, 3, 2, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2804,
            rows: [
                [1, 6, 3, 1, 2, 1, 2, 1],
                [2, 3, 4, 2, 3, 2, 2],
                [1, 3, 1, 5, 5, 2, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 1, 2, 1, 2, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2805,
            rows: [
                [nil, nil, 1, nil, nil, 3, nil, nil],
                [nil, 1, nil, nil, 2, nil, nil],
                [nil, 4, nil, nil, 1, 2, 4, nil],
                [3, nil, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, 2, 1, 3, nil],
                [2, nil, nil, nil, nil, 1, nil],
                [3, 2, 1, 2, nil, 3, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [2, 1, 3, 3, nil, 2, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2806,
            rows: [
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 2, 3, 1, nil, nil],
                [nil, nil, 3, 4, 1, 4, nil, nil],
                [nil, 1, 1, 2, 1, 1, nil],
                [nil, nil, 3, 2, 3, 4, nil, nil],
                [nil, 1, 2, 1, 4, 3, nil],
                [nil, nil, 3, 1, 2, 1, nil, nil],
                [nil, nil, 2, 1, 4, nil, nil],
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2807,
            rows: [
                [1, 4, nil, nil, nil, nil, 1, 2],
                [1, nil, nil, nil, nil, nil, 4],
                [nil, nil, 1, 2, 2, 4, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, nil, 2, 1, 3, 1, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 1, 4, nil, nil, nil],
                [3, 1, nil, nil, nil, nil, 4, 1],
                [2, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2808,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 2],
                [3, 3, 1, 1, 2, 1, 5],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [1, 4, 1, 3, 2, 1, 4],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [5, 2, 4, 1, 2, 3, 2],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2809,
            rows: [
                [nil, 1, 2, nil, nil, 1, 1, nil],
                [nil, 6, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 3, nil, nil],
                [nil, 1, nil, nil, nil, 5, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 3, nil, nil],
                [nil, 3, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 3, nil, nil],
                [nil, 3, nil, nil, nil, 5, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2810,
            rows: [
                [nil, nil, nil, nil, nil, nil, 1, 2],
                [nil, nil, 1, 2, 3, 1, 3],
                [nil, nil, nil, nil, nil, nil, 1, 3],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 2, 1],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 2, 3, nil, nil, 2, nil, nil],
                [1, 2, 1, nil, 2, nil, nil],
                [nil, 5, 1, nil, nil, 2, nil, nil],
                [1, 3, 5, nil, 1, nil, nil],
                [2, nil, 4, 1, 2, 3, nil, 1],
                [nil, 3, nil, 2, nil, 1, 2],
                [1, nil, 2, 1, 3, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, 1],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2811,
            rows: [
                [nil, nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 3, nil, nil, 5, nil, 2, nil],
                [4, nil, nil, 1, nil, nil, 2],
                [nil, 2, nil, nil, 3, nil, 2, nil],
                [3, nil, nil, 1, nil, nil, 5],
                [nil, 1, nil, nil, 2, nil, 3, nil],
                [nil, 2, nil, 1, nil, 2, nil],
                [nil, 2, nil, nil, 2, nil, 5, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [nil, nil, 2, 1, 3, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 1, 1, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2812,
            rows: [
                [nil, 5, 2, nil, nil, 1, 2, nil],
                [2, nil, 1, nil, 1, nil, 4],
                [1, nil, nil, 4, 5, nil, nil, 1],
                [3, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, 2, 1, nil, nil, 3],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [nil, 4, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, nil, 3, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, nil, 2, nil, nil, 4, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2813,
            rows: [
                [nil, nil, 2, nil, nil, 3, nil, nil],
                [nil, 2, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, nil, nil, 1, nil],
                [nil, nil, 3, nil, nil, 1, nil],
                [nil, nil, nil, nil, 2, nil, nil, 4],
                [nil, nil, nil, 1, nil, nil, 4],
                [nil, nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, 3, 2, 3, nil, nil],
                [nil, nil, 2, 3, 1, 2, nil, nil],
                [nil, 1, 3, 2, 2, 2, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2814,
            rows: [
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [3, 1, 2, 3, 2, 3, 1],
                [nil, nil, 2, 2, 1, 2, nil, nil],
                [nil, 1, 3, 1, 5, 1, nil],
                [nil, nil, 2, 1, 1, 2, nil, nil],
                [nil, 1, 2, 1, 2, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2815,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, 1, 3, 1, 2, 2, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 1, 4, 2, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 4, 3, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, 1, 3, 1, 4, 1, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, 2, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2816,
            rows: [
                [nil, nil, 2, 1, 4, 2, nil, nil],
                [nil, 3, 2, 1, 2, 1, nil],
                [nil, 1, 2, 1, 2, 1, 2, nil],
                [nil, 1, 2, 1, 2, 3, nil],
                [nil, 1, 2, 1, 4, 4, 1, nil],
                [nil, 1, 2, 1, 2, 1, nil],
                [nil, nil, 1, 6, 1, 2, nil, nil],
                [nil, nil, 1, nil, 3, nil, nil],
                [nil, nil, 1, 1, 3, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2817,
            rows: [
                [nil, nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, 3, 1, 3, nil, nil],
                [nil, nil, 1, 2, 3, 1, nil, nil],
                [nil, 3, 1, 4, 1, 2, nil],
                [nil, nil, 5, 1, 2, 4, nil, nil],
                [nil, 2, 1, 2, 1, 2, nil],
                [nil, 1, 1, 3, 1, 2, 3, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, 2, 3, 1, 1, 2, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2818,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 2, 3, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, nil, 4, 4, 1, nil, nil],
                [nil, nil, 3, 5, 1, 1, nil, nil],
                [nil, nil, 2, 3, 1, nil, nil],
                [nil, nil, 3, 3, 2, 1, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2819,
            rows: [
                [nil, nil, 1, nil, nil, 3, nil, nil],
                [nil, nil, 2, 1, 3, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, 4, 3, 2, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 5, 1, 4, nil, nil],
                [nil, nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2820,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 4, 2, 1, nil, nil],
                [nil, nil, 3, 2, 5, nil, nil],
                [nil, nil, 2, 4, 2, 1, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil],
                [nil, nil, 2, 1, 4, 1, nil, nil],
                [nil, nil, 2, 1, 5, nil, nil],
                [nil, nil, 3, 2, 2, 1, nil, nil],
                [nil, nil, 2, 1, 3, nil, nil],
                [nil, nil, 3, 2, 1, 2, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
    ]
}
