// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch53 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1041,
            rows: [
                [nil, 2, 2, 2, nil, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, 4, nil, 4, nil, nil, 4, nil],
                [nil, nil, nil, 4, nil, 4, nil],
                [nil, 3, nil, 3, 3, 3, 3, nil],
                [nil, 3, 3, 1, nil, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, 1, 1, 1, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, 3, 3, nil],
                [nil, 2, nil, 2, 2, 2, 2, nil],
                [nil, 2, 3, 3, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 6, 6, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 5, 6, 5, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1042,
            rows: [
                [2, 2, 2, nil, 2, 2, 2, nil],
                [2, 2, nil, 2, 2, nil, nil],
                [nil, 2, nil, 3, 3, nil, nil, nil],
                [3, nil, 3, nil, 3, nil, nil],
                [1, nil, nil, 1, nil, 6, nil, nil],
                [6, nil, nil, 6, nil, 6, 6],
                [3, nil, 3, 3, nil, nil, 3, nil],
                [3, nil, 3, 3, 3, 1, 1],
                [1, nil, 5, nil, nil, nil, 1, nil],
                [1, nil, nil, 1, nil, 1, nil],
                [1, 1, 1, 1, 1, 1, nil, 1],
                [nil, 1, 1, 4, nil, nil, nil],
                [4, nil, nil, 4, 4, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, 1, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1043,
            rows: [
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [1, 1, 1, 1, 2, nil, 2],
                [nil, 2, 6, 6, nil, 2, nil, 2],
                [2, nil, nil, nil, nil, 3, 3],
                [nil, 3, nil, 3, nil, 3, 3, nil],
                [3, nil, 3, nil, nil, nil, 3],
                [3, nil, nil, nil, 3, 3, nil, 3],
                [nil, 1, 5, 5, 5, 1, nil],
                [1, nil, 1, nil, 1, 2, nil, nil],
                [2, 2, nil, nil, nil, nil, nil],
                [nil, nil, 4, nil, nil, 4, nil, nil],
                [nil, 4, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, nil, 1, 2, 2],
                [2, 2, 2, 2, 4, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1044,
            rows: [
                [nil, 2, 2, 2, 1, 2, nil, nil],
                [nil, 2, 2, nil, nil, nil, nil],
                [nil, 2, 2, 3, 3, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil],
                [nil, nil, 2, 2, nil, 2, nil, nil],
                [nil, 2, 2, 1, 1, 1, nil],
                [nil, nil, 1, 1, nil, 1, 1, nil],
                [nil, 1, 1, nil, 2, 2, nil],
                [nil, 2, 2, nil, 2, 3, 3, nil],
                [nil, 3, 3, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, 3, 3, nil],
                [nil, nil, nil, 3, 3, nil, nil],
                [nil, 6, 5, 5, nil, 2, 2, nil],
                [nil, 1, 1, 6, 1, 1, nil],
                [nil, nil, 4, 4, nil, 4, 1, nil],
                [nil, 1, nil, 6, 6, 6, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1045,
            rows: [
                [5, 5, nil, nil, 5, nil, nil, 5],
                [5, nil, 5, nil, 2, 2, nil],
                [4, 4, nil, 1, nil, 1, 3, 3],
                [3, 3, 1, 1, 1, 1, nil],
                [1, nil, nil, 1, 1, 1, nil, nil],
                [1, 1, 2, 2, nil, 2, 1],
                [1, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [1, nil, 1, 1, 1, 1, nil, 2],
                [nil, nil, nil, 2, 2, nil, 1],
                [1, nil, 1, 2, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, 2, 2],
                [nil, 1, 1, nil, 6, 6, nil, 6],
                [nil, nil, 4, 4, 1, nil, 1],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1046,
            rows: [
                [nil, 2, 2, 3, 3, 3, 1, 1],
                [nil, 1, nil, 1, nil, 1, 3],
                [3, 3, nil, nil, nil, 5, nil, 5],
                [5, 5, 6, 6, 4, nil, nil],
                [5, 5, nil, 1, nil, nil, 1, 1],
                [1, 1, nil, nil, 1, 1, 1],
                [1, 1, 1, nil, nil, nil, 1, 1],
                [nil, 1, 2, 2, 2, 2, 2],
                [nil, 2, 2, 2, nil, 3, 3, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [2, nil, nil, 2, nil, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, 3, 4, nil, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1047,
            rows: [
                [nil, 2, nil, nil, 1, 1, nil, 1],
                [1, nil, 1, nil, nil, 1, nil],
                [1, nil, 1, nil, nil, 1, 4, nil],
                [nil, 4, 1, 1, nil, 1, nil],
                [nil, 1, nil, 4, 4, 4, 4, 4],
                [4, 4, 3, nil, nil, nil, 3],
                [nil, 3, 5, nil, nil, 5, nil, nil],
                [5, 5, 1, 3, 1, nil, nil],
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [2, 2, 2, 2, 2, 2, 2],
                [2, 1, 1, 1, 3, 3, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1048,
            rows: [
                [1, 1, nil, 1, 1, nil, 1, 1],
                [nil, nil, 1, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, 1, nil, 1],
                [nil, 1, 1, nil, 1, nil, 1, 2],
                [nil, nil, 2, nil, nil, nil, 2],
                [nil, 6, nil, nil, 6, nil, nil, nil],
                [6, 1, 1, 1, nil, 1, 1],
                [3, nil, 3, 3, nil, 3, 3, nil],
                [3, nil, 3, nil, nil, nil, 2],
                [nil, nil, 2, nil, nil, 2, nil, 2],
                [2, 2, nil, 4, 4, 4, nil],
                [2, nil, 2, 2, 2, nil, nil, 2],
                [2, nil, nil, nil, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [nil, 2, 4, 5, 5, 3, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1049,
            rows: [
                [1, 1, nil, nil, nil, 1, nil, 4],
                [2, 2, nil, 2, 2, 2, nil],
                [nil, nil, 6, 6, nil, nil, nil, 6],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, 1, 1, 1, nil, nil, 2, 1],
                [1, nil, nil, 1, 1, 1, nil],
                [nil, 1, nil, nil, nil, nil, 1, 1],
                [nil, nil, 1, nil, 1, 1, 1],
                [nil, 3, nil, nil, 3, 3, nil, 3],
                [3, 2, 2, 2, nil, 2, nil],
                [2, 2, 2, 2, 3, nil, 3, nil],
                [3, nil, nil, 3, 1, nil, 1],
                [1, 1, 2, nil, nil, 2, 1, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [4, 4, nil, 4, 2, 5, 5],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1050,
            rows: [
                [nil, 1, nil, nil, 1, nil, 2, nil],
                [nil, 2, 2, nil, 2, nil, nil],
                [nil, 2, nil, 2, 2, 2, nil, nil],
                [nil, 2, 2, nil, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil, nil],
                [nil, 1, 6, 6, nil, nil, nil],
                [nil, 1, 1, 1, 1, 3, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, 4, nil, nil],
                [nil, nil, nil, 4, 4, 4, nil],
                [nil, 1, 1, 1, 3, nil, 3, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [nil, 3, 3, 3, 3, 6, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 2, 2, 1, 1, 1, nil],
                [nil, 1, 2, 2, 5, 6, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1051,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 3, 3, 1, 2, nil],
                [nil, nil, nil, 3, 6, 1, nil, nil],
                [nil, 2, 1, 3, 1, nil, nil],
                [nil, nil, nil, 1, 4, 4, nil, nil],
                [nil, 1, 3, 1, 5, nil, nil],
                [nil, 1, 3, 2, 6, 1, nil, nil],
                [3, 1, 3, 1, 4, 1, nil],
                [nil, 2, 2, 2, 1, 5, nil, nil],
                [5, 2, 1, 2, 1, 3, nil],
                [nil, 3, 2, 1, 2, 3, nil, nil],
                [nil, 2, 2, 1, 4, 4, nil],
                [nil, 2, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1052,
            rows: [
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [2, 1, 4, 2, 3, 2, 5, 1],
                [nil, nil, nil, nil, nil, nil, 1],
                [2, 1, 3, 1, 4, 4, 3, 3],
                [nil, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, 1, 5, 5, 5, 1, nil],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, 1, 1, 4, 5, 1, nil],
                [nil, 5, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [4, 1, 1, 2, 2, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1053,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [3, 1, 3, 2, 3, 2, 1],
                [3, 1, 4, 1, 2, 3, 2, 1],
                [2, 1, 2, 1, 2, 2, 2],
                [2, 2, 4, 3, 1, 1, 4, 4],
                [3, 1, 1, 1, 1, 6, 4],
                [1, 3, 3, 2, 2, 1, 1, 1],
                [1, 5, 5, 1, 1, 3, 2],
                [4, 1, 1, 2, 3, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1054,
            rows: [
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 5, 3, 2, 2, nil, nil],
                [nil, 2, 1, 4, 5, 2, nil],
                [nil, nil, 2, 3, 3, 2, nil, nil],
                [nil, 2, 2, 1, 2, 2, nil],
                [nil, 2, 3, 1, 3, 3, 1, nil],
                [3, 5, 5, 1, 1, 1, 1],
                [nil, 1, 1, 3, 4, 3, 3, nil],
                [3, 3, 1, 1, 1, 5, 5],
                [1, 1, 2, 3, 1, 3, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1055,
            rows: [
                [nil, nil, 1, 4, 1, 3, nil, nil],
                [nil, 2, 3, 1, 3, 2, nil],
                [nil, 1, 2, 2, 3, 1, 2, nil],
                [nil, 1, 3, 2, 6, 6, nil],
                [nil, 3, 3, 2, 1, 1, 1, nil],
                [nil, 5, 3, 1, 1, 4, nil],
                [nil, nil, 1, 1, 2, 1, nil, nil],
                [nil, nil, 3, nil, 3, nil, nil],
                [nil, nil, 1, 4, 1, 2, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1056,
            rows: [
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, 6, 1, 2, 1, 3, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, 2, 2, 3, 1, 5, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, 7, 1, 5, 1, 2, nil],
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1057,
            rows: [
                [nil, 2, 1, nil, nil, 1, 1, nil],
                [3, nil, 1, nil, 1, nil, 3],
                [2, nil, 3, 2, 1, 4, nil, 1],
                [1, 2, nil, 1, nil, 4, 1],
                [2, nil, 5, 1, 3, 2, nil, 1],
                [2, 1, nil, 2, nil, 2, 1],
                [nil, 4, nil, 5, 1, nil, 2, nil],
                [3, 2, 1, nil, 2, 2, 1],
                [nil, 2, nil, 3, 2, nil, 5, nil],
                [2, 1, 3, nil, 2, 3, 3],
                [3, nil, 2, nil, nil, 1, nil, 2],
                [1, 2, nil, nil, nil, 2, 3],
                [4, nil, 2, nil, nil, 1, nil, 2],
                [1, 2, nil, nil, nil, 1, 2],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1058,
            rows: [
                [nil, 5, 5, nil, 5, 5, nil, nil],
                [1, nil, 1, 1, nil, 2, nil],
                [2, nil, nil, nil, nil, nil, 4, nil],
                [3, 3, 3, nil, nil, 3, 3],
                [2, nil, nil, nil, nil, nil, 2, nil],
                [1, 1, 1, nil, nil, 4, 1],
                [nil, 4, 2, 2, 1, 3, 1, 1],
                [nil, 4, 2, nil, nil, 2, 1],
                [nil, 1, 1, 4, 1, 3, 1, 1],
                [nil, 1, 1, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1059,
            rows: [
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 5, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 5, 1, 2, 2, nil, nil],
                [nil, 1, 2, 4, 4, nil, nil],
                [nil, 4, 1, 1, 2, 2, 2, nil],
                [nil, 2, 1, 5, 1, 4, nil],
                [nil, 4, 3, 3, 1, 3, 4, nil],
                [nil, 3, 1, 4, 1, 4, nil],
                [nil, 2, 2, 1, 2, 1, 1, nil],
                [nil, 1, 1, 2, 1, 2, nil],
                [nil, 2, 1, 2, 1, 2, 2, nil],
                [nil, 1, 1, 3, 1, 2, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1060,
            rows: [
                [3, 3, 3, 3, 3, 4, 4, 6],
                [1, 2, 1, 3, 1, 1, 1],
                [4, 4, 3, 1, 2, 2, 1, 1],
                [1, 1, 1, 2, 4, 1, 1],
                [1, 2, 2, 1, 2, 1, 2, 2],
                [2, 2, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
    ]
}
