// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch34 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 661,
            rows: [
                [2, 4, nil, nil, nil, nil, nil, 4],
                [5, 5, nil, nil, 5, nil, nil],
                [2, nil, nil, nil, 2, 2, nil, 2],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [3, 3, 3, 3, 1, 1, 1],
                [1, 4, 4, 4, 4, 1, 2, 2],
                [2, 2, 2, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 2, 2, 2, 2, 6, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 662,
            rows: [
                [5, nil, nil, nil, nil, 5, 5, nil],
                [5, nil, 2, 2, nil, nil, nil],
                [2, 2, nil, nil, 2, nil, 3, nil],
                [nil, nil, nil, nil, nil, 3, 3],
                [nil, 3, 2, nil, nil, nil, 2, nil],
                [nil, 2, nil, nil, 2, 2, nil],
                [2, 4, nil, 4, 6, 6, 3, 3],
                [3, 1, nil, 1, 1, 1, nil],
                [nil, 1, 1, 1, nil, nil, nil, 1],
                [nil, nil, 1, 1, 1, 1, 1],
                [nil, 1, 1, 1, nil, nil, 1, 3],
                [3, 3, 2, 2, 1, 1, nil],
                [1, nil, 1, nil, 4, nil, 4, nil],
                [4, 1, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 663,
            rows: [
                [nil, 4, 4, 4, nil, 4, nil, nil],
                [nil, 4, 4, 2, nil, 2, nil],
                [nil, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, 2, nil],
                [nil, 2, nil, 2, 2, 1, nil],
                [nil, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 6, nil, nil],
                [nil, 6, 1, 1, 4, 4, nil],
                [nil, 4, 1, 1, nil, nil, 1, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, nil, 3, nil, 3, 3, nil],
                [nil, 3, 3, 1, 1, 1, nil],
                [nil, 1, nil, 1, 1, 3, 3, nil],
                [nil, 3, 3, 5, 5, 2, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 664,
            rows: [
                [1, 3, 3, nil, 2, 1, 1, nil],
                [6, 6, nil, 6, 6, nil, nil],
                [nil, 6, nil, 5, 1, nil, nil, nil],
                [1, nil, 1, nil, 1, nil, nil],
                [1, nil, nil, 1, nil, 1, nil, nil],
                [1, nil, nil, 1, nil, 1, 1],
                [1, nil, 1, 2, nil, nil, 2, nil],
                [2, nil, 2, 2, 2, 2, 2],
                [2, nil, 4, nil, nil, nil, 4, nil],
                [4, nil, nil, 4, nil, 1, nil],
                [1, 1, 1, 1, 3, 3, nil, 2],
                [nil, 2, 2, 2, nil, nil, nil],
                [2, nil, nil, 3, 3, nil, 3, 3],
                [3, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, 3, 3, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 665,
            rows: [
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [nil, nil, 4, 4, 4, nil, 4],
                [3, 1, nil, nil, 1, nil, 1, 1],
                [2, 2, 2, nil, nil, nil, 2],
                [2, 2, 2, nil, nil, 2, nil, nil],
                [nil, 2, 2, 2, 2, nil, 2],
                [nil, 1, 1, nil, 1, 1, 1, 1],
                [1, 1, nil, nil, 3, 4, 4],
                [6, nil, nil, 3, 3, nil, nil, 3],
                [3, 3, nil, 1, 1, 1, 1],
                [1, nil, 1, 1, 1, 1, 1, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 3, 5, 5, 5, 6, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 666,
            rows: [
                [nil, nil, nil, 4, 4, nil, 4, nil],
                [nil, 4, 2, 2, nil, 1, nil],
                [nil, 1, 1, nil, nil, 2, 2, nil],
                [nil, nil, nil, 2, 4, nil, nil],
                [nil, nil, 4, 4, nil, 1, 1, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 2, nil, 2, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, 1, nil, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 2, nil],
                [nil, 2, 2, 5, 5, 5, 3, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, 3, 3, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 6, nil, 6],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 667,
            rows: [
                [nil, 4, 4, nil, 4, 4, 4, nil],
                [4, 1, 1, nil, nil, nil, 1],
                [1, nil, 1, 1, 1, 1, nil, 4],
                [nil, 1, nil, 1, 1, nil, 1],
                [nil, nil, 2, 2, nil, nil, 2, nil],
                [nil, 2, 2, nil, 2, 6, nil],
                [6, nil, nil, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, 1, 3],
                [3, nil, 2, 2, nil, nil, 2],
                [nil, nil, 2, nil, 5, nil, 5, 5],
                [nil, nil, nil, 1, nil, 1, 1],
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [nil, 1, nil, nil, 3, nil, nil],
                [nil, nil, nil, 3, 3, 3, 3, nil],
                [nil, 3, 3, 3, 3, 3, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 668,
            rows: [
                [nil, 1, 6, nil, nil, nil, 6, nil],
                [2, 2, 2, 2, 2, nil, 2],
                [nil, 2, 2, 2, nil, 2, nil, 2],
                [2, nil, nil, nil, nil, 2, 2],
                [nil, 2, nil, 1, nil, 1, 1, nil],
                [1, nil, 1, nil, nil, nil, 1],
                [1, nil, nil, nil, 4, 4, nil, 4],
                [nil, 4, 4, 4, 5, 5, nil],
                [5, nil, 1, nil, 1, 1, nil, nil],
                [1, 1, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, 3, nil, nil],
                [nil, 1, 3, 3, 3, 3, 3],
                [3, 3, 1, 1, nil, 1, 1, 1],
                [1, 1, 1, 3, 3, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 669,
            rows: [
                [3, 3, 3, 3, nil, 3, nil, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [3, 2, nil, 2, 2, nil, 2, nil],
                [nil, nil, nil, nil, 2, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [2, 2, nil, 2, nil, nil, 2],
                [nil, 2, nil, 2, 2, 2, 1, 1],
                [1, nil, nil, nil, 1, 4, nil],
                [1, nil, 6, 6, 6, nil, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 4, 4, 1, 1, 1, nil],
                [1, nil, 1, 1, nil, 1, nil],
                [1, 1, nil, 2, nil, 1, 1, 1],
                [1, nil, 1, nil, nil, nil, 1],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [nil, 1, nil, 1, 1, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 670,
            rows: [
                [nil, 6, nil, nil, 1, 1, 1, nil],
                [nil, 1, 1, 4, 4, nil, nil],
                [nil, nil, nil, 4, 1, nil, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, nil, nil, 1, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, nil, 1, 1, nil, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, nil, 1, nil, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, 1, 1, 1, 6, 6, 6, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 5, nil],
                [nil, 5, nil, 5, nil, 5, nil, 3],
                [3, nil, 4, nil, 3, nil, 3],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 671,
            rows: [
                [1, nil, nil, 3, 3, 1, nil, nil],
                [1, nil, 1, nil, nil, nil, 1],
                [1, nil, 1, nil, 1, nil, nil, 1],
                [1, 1, 1, nil, 1, 1, nil],
                [nil, 1, 3, 3, nil, 3, nil, nil],
                [nil, 3, 4, nil, 4, 4, nil],
                [4, 6, 6, nil, 1, 1, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1],
                [1, nil, 1, 1, 1, 1, 1, nil],
                [1, 1, 1, nil, nil, 1, nil],
                [nil, 5, nil, 5, nil, 4, nil, 3],
                [nil, nil, nil, 3, 3, 3, 4],
                [2, nil, 2, 2, nil, nil, nil, nil],
                [2, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 2, 2, nil, 2, nil],
                [nil, nil, 4, nil, 4, 4, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 672,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 6, nil, 1, 2, nil],
                [nil, nil, nil, 2, 2, 2, nil, nil],
                [nil, 2, nil, nil, nil, 2, 2],
                [nil, 2, nil, 4, nil, 4, nil, nil],
                [nil, 4, 4, 4, 4, nil, nil],
                [4, 4, nil, 4, nil, 3, 3, 3],
                [3, 3, nil, nil, 5, nil, 6],
                [6, nil, 1, 1, 1, 1, 1, 1],
                [nil, 1, nil, 1, 1, nil, 2],
                [nil, 2, 1, nil, nil, 2, 1, 1],
                [nil, 1, 1, 2, 1, nil, 1],
                [nil, 1, 1, 1, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 673,
            rows: [
                [nil, 3, nil, nil, nil, 2, nil, 2],
                [nil, nil, nil, 5, nil, 5, 4],
                [2, 2, 2, nil, 2, 1, nil, 1],
                [1, 2, 2, nil, 2, 2, nil],
                [nil, nil, nil, 2, nil, 2, nil, 2],
                [nil, nil, 2, 2, 1, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [6, 6, 6, 6, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [4, 4, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, 1, nil, 1, 1, nil],
                [1, nil, 1, nil, nil, 1, 1, nil],
                [nil, 3, nil, nil, nil, 3, 3],
                [nil, nil, 3, nil, 3, 5, nil, nil],
                [nil, nil, nil, 5, 5, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 674,
            rows: [
                [2, 2, nil, nil, nil, 2, nil, 2],
                [2, 2, nil, 2, 2, 2, nil],
                [nil, nil, 1, 1, nil, nil, nil, 1],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, 4, 4, 4, nil, nil, 4, 1],
                [1, nil, nil, 2, 2, 2, nil],
                [nil, 2, nil, nil, nil, nil, 6, 6],
                [nil, nil, 6, nil, 3, 3, 3],
                [nil, 2, nil, nil, 2, 2, nil, 2],
                [3, 3, 3, 3, nil, 3, nil],
                [3, 1, 1, 1, 5, nil, 5, nil],
                [1, nil, nil, 1, 1, nil, 1],
                [1, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [1, 1, nil, 1, 1, 1, 1],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 675,
            rows: [
                [nil, 2, 2, nil, 2, 2, 2, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 1, nil, nil, 1, nil, 1, 1],
                [nil, 1, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, 1, 1, 2, nil],
                [2, nil, 2, nil, 2, nil, 1],
                [1, nil, 5, 5, nil, 5, 5, nil],
                [nil, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, 1, 1, 1, nil, 1, 1],
                [1, 2, 2, 2, 2, 3, 6, 6],
                [3, nil, 3, 3, nil, nil, nil],
                [nil, 3, nil, nil, 3, nil, nil, nil],
                [3, nil, nil, nil, nil, 4, nil],
                [nil, nil, nil, nil, nil, 2, 2, nil],
                [nil, 2, 4, 4, 4, 4, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 676,
            rows: [
                [nil, 6, 6, 6, nil, 6, 1, nil],
                [1, 4, 4, nil, nil, 4, nil],
                [4, 2, 2, 2, nil, 1, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [1, 1, 1, nil, 2, 2, nil, nil],
                [2, 1, nil, nil, 1, nil, 1],
                [nil, 1, 1, 3, 3, 3, nil, nil],
                [1, nil, 1, nil, 1, 1, 1],
                [2, 2, 2, 2, 2, nil, nil, nil],
                [nil, nil, 1, nil, 5, 5, 5],
                [3, 3, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 2, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 677,
            rows: [
                [1, nil, 1, 1, 1, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, nil],
                [2, nil, 1, nil, 1, 1, nil, 1],
                [2, 2, 2, nil, 2, 2, 1],
                [nil, 5, 5, nil, 5, 5, 1, nil],
                [1, nil, nil, nil, 1, 1, nil],
                [nil, 4, nil, nil, 4, nil, nil, 5],
                [5, nil, 2, nil, 2, nil, 4],
                [nil, nil, 4, 4, 3, 3, 3, 3],
                [3, 3, 3, nil, 3, 6, 1],
                [1, 1, 1, 2, 2, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 3, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 678,
            rows: [
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, nil, 5, nil, nil, nil, 5],
                [2, nil, 2, nil, nil, 2, 2, 4],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 4, 5, nil, 5, nil, 5],
                [nil, 1, nil, 1, nil, 2, 2],
                [2, nil, 2, 2, nil, nil, 2, 2],
                [nil, 2, nil, 2, 2, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil, 2],
                [nil, 3, nil, 3, 3, 4, nil],
                [nil, 1, nil, nil, 3, 3, nil, nil],
                [nil, nil, nil, 3, nil, 3, nil],
                [nil, nil, nil, nil, 6, 1, nil, 1],
                [3, nil, 3, nil, 3, 1, 1],
                [1, 1, nil, nil, 1, nil, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 679,
            rows: [
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, 5, nil, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, 1, nil],
                [1, 1, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, 1, 1, 1, 1],
                [nil, nil, 1, 1, nil, nil, nil, 3],
                [3, 3, nil, 3, 1, 1, 1],
                [nil, 1, nil, 1, nil, 1, 1, nil],
                [2, nil, nil, nil, 2, 2, 2],
                [nil, 2, 2, 2, 2, 2, 1, 1],
                [nil, 1, 4, 4, 4, 4, 1],
                [nil, 3, 3, 3, 3, 6, 6, 1],
                [nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, 1, 1, 6, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 680,
            rows: [
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, 2, 2, 1, 1, nil, 1, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, nil, 1, nil],
                [nil, 1, 4, nil, 4, 4, nil],
                [nil, nil, 4, 4, 4, nil, 5, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, nil, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, 1, 1, nil, 1, nil],
                [nil, 1, 1, 1, 1, 3, 3, nil],
                [nil, 3, 6, 6, 6, 6, nil],
                [nil, 2, 2, 1, 1, 1, 1, nil],
                [nil, 1, 2, 2, 2, 2, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
    ]
}
