// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch59 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1161,
            rows: [
                [nil, 1, nil, nil, nil, nil, 2, 3],
                [nil, 2, 1, 3, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, 2, 1, 3, nil, nil, nil],
                [nil, 5, 4, 4, nil, nil, 4, 4],
                [nil, 1, 2, 1, nil, 4, 3],
                [nil, 3, 3, 1, nil, 2, 2, 2],
                [nil, 1, 3, 2, nil, 1, 2],
                [nil, 1, 2, 2, nil, 1, 3, 1],
                [nil, 5, 5, 5, nil, 1, 1],
                [nil, 1, 2, 1, nil, 3, 1, 1],
                [nil, 2, 1, 1, nil, 2, 1],
                [nil, 2, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1162,
            rows: [
                [nil, nil, nil, nil, 1, 5, 5, nil],
                [nil, nil, 4, 4, 4, 2, 4],
                [nil, nil, 3, 3, 2, 1, 5, nil],
                [nil, 5, 2, 4, 4, 2, nil],
                [nil, nil, 4, 1, 1, 2, 1, nil],
                [nil, 4, 1, 4, 1, 1, nil],
                [nil, 4, 4, 4, 2, 2, nil, nil],
                [2, 3, 1, 3, 1, nil, nil],
                [nil, 1, 3, 1, 1, 2, nil, nil],
                [2, 2, 3, 1, 1, nil, nil],
                [5, 3, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 1, 1, 3, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1163,
            rows: [
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, nil, 2, 4, 6, nil, nil],
                [nil, 1, 1, 2, 2, 1, nil],
                [nil, nil, 1, 1, 5, 2, nil, nil],
                [nil, 1, 4, 4, 4, 3, nil],
                [nil, 1, 1, 3, 1, 2, 1, nil],
                [4, 4, 1, 2, 2, 1, 1],
                [nil, 1, 1, 3, 1, 2, 1, nil],
                [1, 3, 1, 1, 1, 3, 1],
                [3, 3, 2, 1, 6, 1, 1, 2],
                [1, 2, nil, nil, nil, nil, 2],
                [1, 1, 2, 1, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1164,
            rows: [
                [3, nil, 1, 3, 1, 2, nil, 1],
                [1, 1, 3, nil, nil, nil, 2],
                [1, 3, 1, 4, nil, nil, 1, nil],
                [3, 1, 1, nil, nil, nil, 1],
                [nil, 2, 1, nil, 1, nil, 2, 1],
                [5, nil, 5, nil, 1, nil, 2],
                [2, 1, 1, nil, 2, nil, 1, 2],
                [1, 3, nil, nil, 1, 6, 6],
                [1, 2, 1, 4, 1, 3, 3, 1],
                [2, 2, 1, nil, 5, 1, 2],
                [1, 3, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1165,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 5, 1, 1, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 1, 4, 1, 3, 1, nil],
                [nil, nil, 1, 1, 3, 1, nil, nil],
                [nil, 5, 5, 3, 3, 1, nil],
                [nil, 1, nil, 3, 1, nil, 3, nil],
                [1, 2, 1, 1, 6, 5, 1],
                [nil, 2, nil, 4, 1, nil, 1, nil],
                [3, 1, 2, 4, 1, 1, 4],
                [nil, 1, nil, 4, 4, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1166,
            rows: [
                [nil, nil, 2, nil, nil, 3, nil, nil],
                [3, 1, 2, 1, 2, 6, 2],
                [4, 2, 2, 1, 4, 4, 1, 1],
                [1, 1, nil, 3, nil, 3, 2],
                [2, 1, 2, 2, 6, 1, 2, 1],
                [1, 2, nil, 1, nil, 1, 3],
                [1, 2, nil, 2, 2, nil, 2, 1],
                [4, nil, nil, 1, nil, nil, 1],
                [1, 4, nil, 6, 1, nil, 2, 2],
                [2, nil, nil, 2, nil, nil, 2],
                [1, 2, 1, nil, nil, 4, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1167,
            rows: [
                [nil, nil, nil, nil, nil, 1, 3, nil],
                [1, nil, 1, nil, 1, nil, 1],
                [4, 1, nil, 3, 1, nil, 2, 1],
                [4, 1, 2, 1, 3, 4, 1],
                [2, 1, nil, 4, 4, nil, 1, 2],
                [1, 3, 3, 1, 2, 2, 2],
                [1, 6, 1, 1, 4, 1, 1, 1],
                [4, nil, 4, 1, 1, nil, 1],
                [5, 1, 3, 1, 1, 1, 1, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1168,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 3, 1, 3, 4, 4, nil],
                [4, nil, nil, nil, nil, nil, 5],
                [2, nil, 5, 2, 1, 2, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 2, 7, 2, 1, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 3, 1, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 1, 2, 3, 1, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1169,
            rows: [
                [nil, 4, 5, nil, 1, nil, 5, nil],
                [3, 3, nil, nil, 3, nil, nil],
                [2, 2, nil, 3, nil, nil, nil, nil],
                [nil, nil, 3, nil, 5, nil, nil],
                [nil, 1, 4, 4, 3, 3, nil, 1],
                [nil, 4, nil, 4, nil, 1, 2],
                [1, 1, 2, 2, 1, 2, 1, 1],
                [4, 1, 6, 1, 2, 2, 2],
                [1, 4, 1, 2, 2, 1, 2, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1170,
            rows: [
                [nil, nil, 1, nil, 3, nil, 2, nil],
                [nil, 1, 4, 4, nil, 1, 1],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [1, 1, 3, 2, nil, nil, nil],
                [1, nil, 2, 1, nil, nil, 4, 4],
                [1, nil, 1, 2, nil, 1, 3],
                [1, 2, 1, nil, 2, nil, 2, 6],
                [1, nil, nil, nil, nil, 1, nil],
                [2, 1, 3, nil, 3, 1, 2, 2],
                [1, 2, 1, 3, 2, 1, 3],
                [3, 1, 3, 1, nil, 3, 1, 2],
                [1, 1, 2, 1, 1, 1, 1],
                [1, 1, 1, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1171,
            rows: [
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 2, 2, 4, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, 1, 1, 6, 1, 3, 2, nil],
                [nil, nil, nil, nil, nil, nil, 4],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, 6, 6, 4, 3, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, 2, 3, 3, 1, 3, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 1, 3, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1172,
            rows: [
                [nil, 1, 2, 3, 1, 2, 2, nil],
                [nil, 2, 1, 7, 1, 1, nil],
                [nil, nil, 4, 5, 1, 5, nil, nil],
                [nil, nil, 1, 2, 4, nil, nil],
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, 3, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 2, nil, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, nil],
                [nil, 1, 2, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 4, 1, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1173,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 1],
                [4, nil, 1, 1, 1, nil, 2],
                [nil, 1, 3, nil, nil, 1, 4, nil],
                [nil, 5, nil, nil, nil, 1, nil],
                [nil, 2, 1, nil, nil, 3, 2, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 5, 2, nil, nil, 3, 3, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 2, 1, nil, nil, 3, 2, nil],
                [nil, 2, nil, nil, nil, 4, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, 5, 5, 1, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 3, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1174,
            rows: [
                [1, 1, nil, nil, nil, nil, 6, 1],
                [3, 3, 4, 4, 2, 1, 5],
                [1, 3, nil, nil, nil, nil, 3, 1],
                [2, 1, 1, 2, 3, 2, 1],
                [2, 1, nil, nil, nil, nil, 2, 1],
                [2, 6, 2, 2, 1, 2, 1],
                [3, 1, nil, nil, nil, nil, 1, 1],
                [2, 1, 1, 1, 1, 1, 3],
                [4, 2, nil, nil, nil, nil, 2, 2],
                [3, 3, 1, 4, 1, 4, 2],
                [2, 3, nil, nil, nil, nil, 4, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 3, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1175,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [5, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 4, 1, 1, nil, nil],
                [nil, 1, 1, 3, 4, nil, nil],
                [nil, 2, 4, 4, 3, 5, 3, nil],
                [nil, 3, 5, 3, 4, 5, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1176,
            rows: [
                [nil, nil, 2, 3, 3, nil, nil, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, 2, 3, 2, 2, 3, nil],
                [nil, 4, 4, 3, nil, nil, 5],
                [nil, nil, 3, 2, 1, 1, 1, nil],
                [nil, 3, 1, 3, nil, nil, 4],
                [nil, 4, nil, nil, 2, 2, 1, nil],
                [nil, 3, 1, 1, 1, 4, nil],
                [nil, 1, nil, nil, 1, 4, 1, nil],
                [nil, 5, 1, 3, 1, 1, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1177,
            rows: [
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil],
                [nil, nil, nil, nil, 1, 2, nil, nil],
                [nil, nil, nil, nil, 2, 5, nil],
                [nil, nil, nil, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, 2, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 3, nil, nil, 4, 2, nil],
                [2, 2, nil, nil, 4, 4, nil],
                [nil, 1, 3, nil, nil, 1, 1, nil],
                [3, 3, nil, nil, 1, 2, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [5, 3, nil, nil, 1, 1, nil],
                [nil, 2, 3, nil, nil, 3, 3, nil],
                [1, 4, nil, nil, 5, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1178,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 2, nil, 1, 1, nil, nil],
                [4, 1, nil, 1, 2, nil, nil],
                [nil, 3, 3, nil, 1, 2, nil, nil],
                [3, 3, nil, 1, 1, nil, nil],
                [nil, 1, 6, nil, 6, 1, nil, nil],
                [1, 2, nil, 4, 3, nil, nil],
                [nil, 3, 1, nil, 2, 1, nil, nil],
                [1, 3, nil, 3, 3, nil, nil],
                [nil, 2, 1, nil, 1, 1, nil, nil],
                [1, 4, nil, 1, 2, nil, nil],
                [nil, 1, 2, nil, 1, 2, nil, nil],
                [1, 2, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1179,
            rows: [
                [nil, 1, nil, 1, nil, 1, nil, 2],
                [1, nil, 1, nil, 1, nil, 1],
                [1, nil, 3, nil, 3, nil, 1, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [3, nil, 1, nil, 2, nil, 1, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [nil, 6, nil, 2, nil, 2, nil, nil],
                [2, nil, 1, nil, 4, nil, nil],
                [nil, 1, nil, 1, nil, 4, nil, nil],
                [4, nil, 1, nil, 2, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, 6, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1180,
            rows: [
                [1, 2, nil, nil, nil, 2, 1, 1],
                [4, nil, nil, 2, 2, 1, 3],
                [nil, nil, nil, nil, 2, 3, nil, 1],
                [3, nil, 3, 2, nil, 1, 2],
                [1, 4, 1, nil, nil, 4, 1, 3],
                [1, 3, nil, nil, 1, 1, nil],
                [nil, 1, 1, 1, 6, 1, 3, nil],
                [1, 2, 4, 1, 1, 2, 1],
                [1, 1, 1, 1, 3, 1, 2, 1],
                [6, 1, 1, 2, 2, 2, 1],
                [1, 3, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
    ]
}
