// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch11 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 201,
            rows: [
                [nil, nil, nil, nil, 5, 1, 1, nil],
                [nil, nil, 1, 1, 1, 1, 1],
                [nil, nil, 1, 1, 1, 1, 2, nil],
                [nil, 2, 2, 2, 4, 4, nil],
                [nil, nil, 4, 4, 4, 4, 4, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 2, 2, 2, nil, nil],
                [2, 2, 2, 2, 3, nil, nil],
                [3, 3, 3, 3, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 3, 6, 6, 7, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 202,
            rows: [
                [nil, nil, nil, 1, nil, 3, nil, nil],
                [nil, nil, 3, nil, 3, nil, nil],
                [nil, 3, 3, 3, nil, nil, 2, nil],
                [4, 4, 4, nil, 4, 4, nil],
                [nil, 1, 1, 2, nil, nil, 2, nil],
                [nil, nil, 2, 2, 2, 2, 2],
                [2, 2, nil, 1, 1, 5, 5, nil],
                [5, 1, 1, nil, 1, nil, nil],
                [1, nil, nil, 1, nil, 1, 1, nil],
                [1, nil, 1, nil, 1, 1, 1],
                [nil, 1, 1, nil, nil, 1, 1, 4],
                [nil, nil, 4, 2, 6, nil, nil],
                [nil, 2, 2, nil, 4, 4, nil, 4],
                [nil, nil, nil, 5, nil, 5, nil],
                [nil, nil, 2, nil, 1, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 203,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, nil, 2, 2, nil, nil],
                [2, 2, nil, 2, 2, nil, nil],
                [nil, 4, 4, nil, 7, 7, nil, nil],
                [5, 5, nil, 5, 5, nil, nil],
                [nil, 3, 2, nil, 1, 1, nil, nil],
                [3, 3, nil, 3, 1, nil, nil],
                [nil, 1, 1, nil, 3, 3, nil, nil],
                [3, 3, nil, 3, 3, nil, nil],
                [nil, 3, 1, nil, 1, 1, nil, nil],
                [1, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, 2, nil, nil],
                [2, 2, nil, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 204,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, 1, 1, 3, 3, 3, 3, nil],
                [nil, 3, nil, nil, 3, nil, nil],
                [nil, 3, 3, nil, 3, 3, nil, nil],
                [nil, 3, nil, nil, nil, 4, 4],
                [nil, 4, 4, nil, nil, 1, nil, 1],
                [1, 1, nil, nil, 2, nil, 2],
                [2, 2, nil, nil, nil, 2, 2, 2],
                [2, nil, 2, nil, 1, nil, 1],
                [1, 1, 5, 5, 5, 5, 1, 1],
                [1, 6, 6, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 205,
            rows: [
                [nil, 2, 2, 2, nil, nil, nil, 2],
                [nil, 2, nil, 4, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, 4, nil],
                [nil, nil, 3, nil, nil, 3, 1],
                [nil, 3, 3, 1, nil, nil, 1, 1],
                [nil, 3, 3, 1, nil, 1, 1],
                [nil, 1, 2, 2, nil, 2, 2, 6],
                [nil, 6, 6, 6, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 2, 2],
                [nil, 2, 1, 2, nil, 1, 1],
                [nil, 1, 1, 5, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 206,
            rows: [
                [nil, nil, 6, 6, nil, nil, 6, nil],
                [nil, nil, 1, nil, nil, 1, nil],
                [nil, nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, 1, nil, nil, 1, 1, 2, nil],
                [nil, 2, 2, 2, 2, 1, nil],
                [nil, 1, 1, 1, 1, 1, 4, nil],
                [nil, 4, 3, 3, 3, 3, nil],
                [nil, 3, 3, 2, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, nil, 2, nil, 5, nil, 5],
                [5, nil, 4, nil, 4, nil, 4],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 207,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [1, 1, 1, 1, 1, 1, 3],
                [3, 2, 2, 2, 2, 2, 2, 2],
                [2, 2, nil, 2, nil, 2, 2],
                [2, 2, 1, 1, 1, 1, 1, 1],
                [1, 1, nil, 1, nil, 1, 1],
                [1, 1, nil, 1, 1, nil, 1, 1],
                [1, nil, nil, 1, nil, nil, 3],
                [3, 3, nil, 3, 3, nil, 3, 3],
                [3, nil, nil, 2, nil, nil, 4],
                [2, 4, 4, nil, nil, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 3, nil, nil, 6, 6, 7],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 208,
            rows: [
                [nil, nil, nil, nil, nil, 5, 5, 3],
                [nil, nil, nil, nil, 3, 3, 3],
                [nil, 3, 3, 3, 3, nil, 1, 2],
                [2, 2, 2, 2, nil, nil, nil],
                [nil, 4, 4, 4, 4, nil, 4, 2],
                [2, 2, 2, 2, nil, nil, nil],
                [2, nil, nil, nil, 2, 2, 2, 2],
                [1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 1, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, nil],
                [6, 1, 7, 1, 4, nil, 1, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, nil, 1, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 209,
            rows: [
                [4, nil, nil, nil, 4, nil, nil, 4],
                [4, 4, nil, nil, 4, nil, 4],
                [nil, nil, 4, nil, 1, nil, 1, nil],
                [1, nil, 1, 1, nil, 1, nil],
                [nil, nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, 1, nil, 1, nil],
                [1, 1, 1, 1, 1, 1, nil, 1],
                [nil, nil, 1, 2, 2, 2, 2],
                [2, 2, 2, 2, 1, 1, nil, 1],
                [nil, nil, 1, 1, 1, 3, 3],
                [nil, 3, 3, nil, nil, 2, nil, nil],
                [7, 2, nil, nil, nil, 2, 2],
                [nil, 5, 5, nil, nil, 2, nil, nil],
                [1, 2, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 210,
            rows: [
                [nil, 2, nil, 2, nil, 2, nil, nil],
                [nil, 2, nil, 2, nil, 6, nil],
                [nil, 6, nil, 6, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil, nil],
                [nil, 2, nil, 5, nil, 5, nil],
                [nil, 5, nil, 4, nil, 4, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 3, nil, 3, nil, 3, nil, nil],
                [nil, 3, nil, 3, nil, 1, nil],
                [nil, 1, nil, 4, nil, 4, nil, nil],
                [nil, 4, nil, 3, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, nil],
                [nil, 1, nil, 7, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 211,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, 1, 1, 1, 4, 4, nil],
                [nil, nil, 4, 4, 5, 5, nil, nil],
                [nil, 5, 5, 1, 1, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, nil, nil, 7, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 212,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, 1, 5, 2, nil, 2],
                [nil, 2, 2, 4, 1, 1, 1, nil],
                [1, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [1, nil, 1, nil, 1, 1, 1],
                [2, 2, 2, nil, nil, 2, 2, 2],
                [nil, 1, 1, nil, 1, nil, nil],
                [1, nil, nil, nil, nil, 1, 1, 1],
                [1, nil, 1, nil, 1, 1, 1],
                [nil, 3, 3, nil, 3, 3, 2, nil],
                [nil, 2, 2, 2, 2, 4, 4],
                [5, 3, 1, 5, 5, 5, 1, 1],
                [1, 1, 1, 6, 3, 3, 6],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 213,
            rows: [
                [nil, nil, 2, nil, nil, 2, 2, nil],
                [nil, 2, 2, nil, nil, 2, 2],
                [2, nil, nil, 2, 2, 2, nil, nil],
                [2, 2, nil, 1, nil, nil, nil],
                [1, nil, nil, 1, 1, 1, nil, nil],
                [1, 1, nil, 1, nil, nil, nil],
                [1, nil, 1, 1, 1, 1, 1, nil],
                [nil, 5, nil, nil, 3, nil, 3],
                [3, nil, 3, 3, 4, 4, 5, nil],
                [nil, 5, nil, nil, 5, nil, 5],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 7, nil, nil, nil, 6, nil],
                [nil, nil, 7, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 214,
            rows: [
                [1, nil, nil, 1, 3, nil, nil, 3],
                [4, nil, 4, 4, 4, nil, 4],
                [nil, 4, nil, 4, 5, nil, 5, nil],
                [nil, 5, 5, 2, 1, 1, nil],
                [nil, 1, nil, 1, 1, nil, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [3, 3, 3, 3, 3, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 2, 5],
                [6, nil, nil, nil, nil, nil, 6],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 215,
            rows: [
                [nil, 2, 2, nil, 2, 2, 2, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 2, 2, 2, nil, 2, 1, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 1, 1, 1, nil, 1, 1, nil],
                [3, nil, nil, nil, nil, nil, 4],
                [nil, 4, 1, nil, 1, 4, 1, nil],
                [1, nil, nil, nil, nil, nil, 7],
                [nil, 3, 3, nil, 5, 5, 5, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, 3, 3, 3, nil, 6, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 216,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 1],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 2, 2, 2, 2, 5, nil],
                [nil, 5, 5, 5, 5, 6, 6, nil],
                [nil, 6, 2, 2, 2, 2, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 5, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 217,
            rows: [
                [2, 2, 2, 2, nil, 2, 2, 2],
                [nil, nil, 2, nil, nil, 1, 4],
                [nil, 4, 4, 4, nil, 4, 1, nil],
                [1, 1, 1, nil, 1, 1, 1],
                [nil, 1, nil, 1, 1, nil, 1, 2],
                [2, nil, 2, 2, nil, nil, 4],
                [nil, nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, 4, 4, 4, 4, 4],
                [4, 1, nil, 1, 1, 1, 1, nil],
                [1, nil, nil, 1, 1, nil, nil],
                [1, 1, 1, 3, 3, 3, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 3, nil, 6, 6, 5, 5, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 218,
            rows: [
                [2, 2, 2, 2, 2, 2, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, 2, 2, 2, 3, 3],
                [3, nil, nil, nil, 3, 3, 3],
                [3, nil, nil, 3, 3, 3, 3, 3],
                [1, nil, nil, nil, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, 1, 4],
                [4, 1, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, 4, nil, nil, nil, nil],
                [4, 4, 5, 5, nil, nil, nil],
                [5, 5, 5, 5, nil, nil, nil, nil],
                [5, 5, 5, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 219,
            rows: [
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 2, 2, 3, nil],
                [nil, 2, 2, 2, 2, 5, nil],
                [nil, 5, 5, 4, 4, 4, 4, nil],
                [nil, 4, 4, 4, 4, 4, nil],
                [nil, 3, 6, 6, 1, 1, 1, nil],
                [nil, 1, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [nil, 3, 3, 3, 3, 3, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 220,
            rows: [
                [4, 4, nil, nil, nil, nil, 4, 4],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [2, nil, 2, 2, 2, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [1, nil, 1, 1, 1, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 3, nil, 3, 3, 4],
                [4, 4, 4, 1, 1, 1, 1, 1],
                [1, 1, 1, nil, 1, 1, 1],
                [nil, 3, 2, nil, nil, 2, 3, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, 3, 5, nil, nil, 6, 6, nil],
                [nil, nil, 6, 3, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
    ]
}
