// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch146 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2901,
            rows: [
                [nil, 1, 2, nil, nil, 1, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 3, nil, nil],
                [nil, 1, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, nil, 3, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 5, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 4, nil, nil, nil, 2, nil],
                [nil, 3, nil, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2902,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 4, 4, 1, 4, nil, nil],
                [nil, 1, 2, 2, 1, nil, nil],
                [nil, 4, 4, 3, 1, 5, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2903,
            rows: [
                [nil, 4, 2, nil, nil, 2, 2, nil],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, 3, nil, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 3, nil, nil, nil, 1, nil, nil],
                [nil, 4, nil, nil, nil, 1, nil],
                [nil, 5, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 4, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 3, nil, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 3, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2904,
            rows: [
                [nil, 1, 2, 1, 3, 1, 2, nil],
                [4, nil, nil, nil, nil, nil, 2],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [1, 2, 1, 3, 2, 1, 2],
                [nil, 3, nil, nil, nil, nil, 4, nil],
                [2, 1, 2, 3, 4, 3, 4],
                [nil, 1, 3, 1, 5, 3, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 1, 1, 4, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2905,
            rows: [
                [nil, nil, 5, nil, nil, 3, nil, nil],
                [nil, 2, 3, nil, 4, 4, nil],
                [nil, 1, 3, 1, 2, 1, 5, nil],
                [nil, 1, 2, nil, 5, 2, nil],
                [nil, 1, 3, 2, 1, 2, 1, nil],
                [nil, 2, 1, nil, 2, 4, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2906,
            rows: [
                [nil, nil, nil, 5, 6, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2907,
            rows: [
                [nil, 1, 1, nil, nil, 2, 1, nil],
                [nil, 2, nil, nil, nil, 4, nil],
                [nil, 2, nil, nil, nil, 3, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 4, nil, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 5, nil, nil, nil, 6, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 3, nil, nil],
                [nil, 2, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2908,
            rows: [
                [2, nil, nil, nil, nil, nil, nil, 1],
                [3, 2, 1, 1, 3, 1, 5],
                [4, nil, nil, nil, nil, nil, nil, 2],
                [1, 5, 5, 1, 4, 1, 2],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [1, 2, 1, 5, 1, 1, 4],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2909,
            rows: [
                [nil, nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 2, nil, nil, 1, nil, 2, nil],
                [3, nil, nil, 2, nil, nil, 1],
                [nil, 3, nil, nil, 2, nil, 1, nil],
                [2, nil, nil, 4, nil, nil, 2],
                [nil, 1, nil, nil, 1, nil, 1, nil],
                [nil, 3, nil, 1, nil, 2, nil],
                [nil, 1, nil, nil, 2, nil, 1, nil],
                [nil, 2, nil, 1, nil, 2, nil],
                [nil, nil, 3, 2, 4, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2910,
            rows: [
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 3, 1, 4, nil, nil],
                [nil, 1, 3, 1, 3, nil, nil],
                [nil, 2, 1, 5, 3, 1, 3, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2911,
            rows: [
                [nil, 2, 4, 1, 3, 2, 1, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [1, 3, 2, 1, 3, 1, 2],
                [nil, 1, nil, nil, nil, nil, 5, nil],
                [1, 4, 3, 1, 3, 2, 1],
                [nil, 2, 1, 2, 1, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2912,
            rows: [
                [nil, nil, 2, nil, nil, 5, nil, nil],
                [nil, 4, 1, nil, 3, 1, nil],
                [nil, 5, 1, 4, 1, 3, 2, nil],
                [nil, 4, 4, nil, 1, 2, nil],
                [nil, 1, 2, 1, 2, 1, 2, nil],
                [nil, 3, 1, nil, 2, 1, nil],
                [nil, nil, 2, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2913,
            rows: [
                [nil, nil, 1, nil, nil, 3, nil, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, 1, 3, 1, nil],
                [1, nil, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, 2, 3, 5, nil],
                [1, nil, nil, nil, nil, 2, nil],
                [1, 4, 1, 2, nil, 4, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [2, 3, 1, 3, nil, 1, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2914,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2915,
            rows: [
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [2, 1, nil, nil, nil, 2, 1],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [1, 4, nil, nil, nil, 1, 2],
                [nil, 5, nil, nil, nil, nil, 5, nil],
                [1, 3, nil, nil, nil, 2, 3],
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [1, 2, nil, nil, nil, 1, 4],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2916,
            rows: [
                [nil, 1, nil, nil, nil, nil, 5, nil],
                [3, nil, nil, 1, nil, nil, 2],
                [1, nil, nil, 2, 1, nil, nil, 2],
                [2, nil, nil, 3, nil, nil, 2],
                [1, nil, nil, 2, 1, nil, nil, 2],
                [5, nil, nil, 1, nil, nil, 2],
                [nil, 3, 3, 1, 3, 2, 1, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 1, 5, 2, 1, 2, 1, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2917,
            rows: [
                [nil, nil, nil, 2, 5, nil, nil, nil],
                [nil, nil, 1, 5, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, 2, 4, nil, 4, 1, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, 2, 1, nil, 2, 1, nil],
                [nil, 2, 2, 3, 3, 1, 3, nil],
                [nil, 2, 1, nil, 2, 1, nil],
                [nil, 1, 1, 3, 1, 3, 1, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2918,
            rows: [
                [3, nil, nil, 2, nil, 1, 4, 4],
                [1, nil, 2, nil, 1, nil, 1],
                [2, nil, nil, 1, nil, nil, nil, 3],
                [1, 3, 1, nil, nil, nil, 5],
                [5, nil, nil, 1, nil, nil, nil, 2],
                [1, 5, 1, nil, nil, nil, 2],
                [nil, nil, nil, 1, nil, 3, 1, nil],
                [nil, nil, 2, nil, 3, nil, nil],
                [nil, nil, nil, 1, nil, 4, 1, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2919,
            rows: [
                [nil, 1, 4, nil, nil, 1, 4, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 4, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 3, nil],
                [nil, 2, nil, nil, nil, 3, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 5, nil, nil, nil, 1, nil],
                [nil, 3, nil, nil, nil, 3, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2920,
            rows: [
                [3, nil, nil, nil, nil, nil, nil, 1],
                [2, 1, 2, 1, 2, 3, 2],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [1, 3, 4, 3, 1, 4, 1],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [5, 1, 2, 1, 2, 4, 1],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
    ]
}
