// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch98 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1941,
            rows: [
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [4, nil, nil, nil, 1, nil, 3],
                [1, nil, nil, 3, 3, nil, 3, 3],
                [3, 1, 6, 1, 4, 4, 1],
                [1, 1, nil, 2, 1, nil, 1, 1],
                [1, 1, 3, 1, 2, 2, 1],
                [3, 5, 1, 4, 1, 1, 1, 1],
                [1, nil, 1, 1, 3, nil, 2],
                [2, 2, 1, 5, 1, 3, 1, 1],
                [4, nil, 1, 1, 1, nil, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1942,
            rows: [
                [nil, nil, nil, 1, nil, 2, 1, nil],
                [nil, 4, 2, 1, 5, 1, nil],
                [nil, nil, 6, 1, nil, nil, nil, 2],
                [1, nil, 2, 4, 1, nil, nil],
                [1, nil, 1, 1, nil, 2, nil, nil],
                [3, nil, 1, nil, 3, 1, 1],
                [nil, 2, nil, nil, nil, 2, 1, nil],
                [2, nil, 1, nil, nil, 4, 2],
                [2, nil, nil, 1, 4, 4, 4, 3],
                [nil, nil, 3, 1, nil, nil, nil],
                [nil, 2, 3, nil, 2, 2, 1, 1],
                [1, 1, 1, 2, nil, 2, nil],
                [2, 1, 3, nil, 1, nil, 1, 1],
                [3, 1, 1, 2, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1943,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, 1],
                [2, 1, 3, 1, nil, 1, 2],
                [1, 3, 1, 1, 2, 2, 1, 1],
                [nil, nil, 1, 4, nil, 4, 3],
                [1, 3, 1, 2, 2, 1, 1, 4],
                [nil, nil, 4, 2, nil, 2, 2],
                [nil, 1, 2, 1, 3, nil, 3, 1],
                [3, 1, 1, 5, nil, 1, 2],
                [nil, 2, 1, 6, 1, nil, 3, 1],
                [3, 1, 1, 1, nil, 1, 1],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1944,
            rows: [
                [1, 1, 3, 1, 5, 3, 1, 2],
                [nil, 2, nil, 1, nil, 1, 1],
                [nil, nil, 1, 3, 4, 2, 1, 4],
                [4, 4, 4, 1, 3, 3, 3],
                [nil, 1, 2, 2, 1, 5, nil, nil],
                [nil, 3, 1, 1, 2, nil, nil],
                [nil, 1, 1, 2, nil, nil, nil, nil],
                [nil, 2, 2, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 6, 1, 3, 1, 2, 1, 3],
                [1, 3, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1945,
            rows: [
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, 3, 1, nil, nil, nil],
                [nil, 1, nil, 4, nil, 2, nil, nil],
                [nil, 1, nil, 1, 2, 4, nil],
                [nil, 3, nil, 1, nil, 4, 2, nil],
                [nil, 2, 2, 1, 1, 2, nil],
                [nil, 2, 1, 3, 1, 2, 1, nil],
                [nil, 3, 3, 1, 1, 1, nil],
                [nil, 6, 2, 2, 1, 1, 1, nil],
                [nil, 3, 2, 2, 1, 2, nil],
                [nil, 4, 1, 2, 1, 4, 1, nil],
                [nil, 3, 1, 3, 2, 1, nil],
                [nil, 1, 2, 1, 2, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1946,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 2, 2, nil, nil, nil],
                [nil, nil, nil, 3, 2, 1, 2, nil],
                [nil, 2, nil, nil, 1, 1, nil],
                [nil, nil, 5, nil, nil, 5, 5, nil],
                [nil, 1, 3, 1, 1, 3, nil],
                [1, 1, 1, 3, 1, 3, 1, 1],
                [nil, nil, nil, nil, 1, 6, 3],
                [3, nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, nil, 2, 3, nil, nil],
                [nil, 1, 4, 4, 4, 1, 2, 2],
                [nil, 1, 1, 3, 1, 1, 3],
                [nil, 1, 1, 6, 2, 1, 3, 1],
                [nil, 3, 1, 3, 1, 1, 1],
                [nil, nil, 1, 2, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1947,
            rows: [
                [nil, nil, 1, nil, 2, nil, 1, 2],
                [1, 3, nil, 2, 1, nil, 1],
                [6, nil, 3, 1, 4, 2, 1, 1],
                [nil, nil, 2, 1, nil, nil, nil],
                [1, 3, 3, nil, 3, 1, nil, 2],
                [nil, nil, 1, nil, nil, 2, nil],
                [3, 3, 1, 3, 1, 1, 1, 1],
                [1, 5, 5, 2, 1, 2, 1],
                [1, 1, 4, 4, 1, 2, 1, 2],
                [2, 1, 3, 1, 1, 3, 1],
                [1, 1, 2, 1, 2, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1948,
            rows: [
                [1, 3, 1, 1, 6, nil, 1, nil],
                [nil, nil, 1, 2, nil, nil, nil],
                [2, 1, nil, nil, 2, 1, 3, 1],
                [2, 4, 1, 2, 3, nil, 2],
                [2, 2, nil, 2, nil, nil, 1, 2],
                [nil, 2, nil, 1, 3, nil, nil],
                [3, 6, nil, 1, 3, 2, nil, 4],
                [nil, 1, 1, 2, 3, 1, nil],
                [1, 2, 1, nil, nil, nil, 4, 1],
                [4, 4, 1, 3, 3, 1, 1],
                [2, 2, 5, 2, 1, 3, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1949,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 2],
                [1, 3, nil, 3, nil, 3, 3],
                [nil, nil, 3, 3, 1, 1, nil, 2],
                [nil, nil, nil, 1, nil, nil, 2],
                [2, 2, 1, 1, 1, nil, 4, 4],
                [nil, nil, 1, 1, nil, 1, 3],
                [nil, 1, 5, 5, 5, nil, 2, 3],
                [3, 1, 2, 2, nil, 2, 1],
                [nil, 3, 1, 1, 2, nil, 1, 1],
                [1, 2, 2, 1, nil, 4, 1],
                [nil, nil, nil, 1, nil, 1, 6, nil],
                [1, 1, 6, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1950,
            rows: [
                [nil, nil, 1, 1, 3, nil, nil, nil],
                [nil, nil, 1, 3, 3, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 1, nil, 5, nil, 2, nil],
                [nil, 2, nil, 5, nil, 3, nil],
                [3, nil, 5, nil, 2, nil, 1, nil],
                [nil, 3, nil, 3, nil, 2, nil],
                [1, nil, 2, nil, 1, nil, 2, nil],
                [nil, 1, nil, 1, nil, 5, nil],
                [1, nil, 1, nil, 3, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 2, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1951,
            rows: [
                [nil, nil, nil, nil, 5, nil, nil, nil],
                [nil, 1, nil, 4, nil, 4, nil],
                [nil, nil, 3, 2, nil, 2, 1, nil],
                [nil, 1, 1, 4, nil, 1, 3],
                [nil, nil, nil, 2, 2, nil, 2, nil],
                [nil, 2, 1, nil, 3, 1, 1],
                [1, nil, 2, 1, 2, 1, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [1, 1, 1, 4, nil, 2, nil, 2],
                [3, 3, 4, 1, nil, nil, 4],
                [nil, 3, nil, 4, 4, 1, 2, 1],
                [nil, nil, nil, 3, 3, 1, 3],
                [nil, 2, 2, 5, 1, 2, 6, 1],
                [nil, 1, 2, 1, 2, 2, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1952,
            rows: [
                [nil, 2, 6, 1, nil, 2, 3, 3],
                [nil, nil, nil, nil, nil, nil, 3],
                [3, 2, 1, 4, 4, 2, 3, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [1, 5, 5, 5, 1, 2, 4, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [2, 5, 1, 2, 2, 1, 2, 2],
                [nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 5, 5, 1, 4, 1, 3],
                [nil, nil, nil, nil, nil, nil, 2],
                [1, 2, 1, 2, 2, 1, 4, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1953,
            rows: [
                [nil, 5, 1, 1, 3, 4, 2, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [2, 2, 4, 1, 5, 5, 1],
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [1, 4, 1, 1, 2, 2, 1],
                [nil, 3, 2, 1, 1, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 2, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1954,
            rows: [
                [nil, 1, 2, 2, nil, nil, 1, 4],
                [nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, 1],
                [nil, 1, 2, 2, nil, 2, 1],
                [nil, 4, 2, 1, nil, nil, 2, 1],
                [nil, 2, 1, 4, nil, 4, 3],
                [nil, 6, 5, 5, nil, 2, 1, 5],
                [nil, 2, 2, 2, nil, 2, 1],
                [nil, 3, 1, 3, nil, 1, 1, 1],
                [nil, 5, 1, 1, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1955,
            rows: [
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, 5, 2, 1, nil, nil],
                [nil, nil, 2, 1, 3, 2, nil, nil],
                [nil, 1, 1, 1, 1, 2, nil],
                [nil, nil, 2, 3, 3, 6, nil, nil],
                [nil, 2, 1, 1, 2, 1, nil],
                [nil, 1, 1, 2, 1, 2, 1, nil],
                [2, 2, 2, 2, 1, 2, 1],
                [nil, 4, 2, 1, 1, 5, 1, nil],
                [2, 3, 3, 3, 1, 1, 1],
                [2, 1, 1, 1, 2, 1, 1, 1],
                [2, 1, nil, nil, nil, nil, 2],
                [2, 1, 4, 1, 2, 1, 2, 2],
                [1, 1, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1956,
            rows: [
                [3, 3, nil, 1, 2, 4, nil, 4],
                [nil, nil, nil, 5, 5, 2, nil],
                [1, 1, 1, 1, 2, 3, nil, nil],
                [nil, 1, nil, nil, nil, nil, 2],
                [1, nil, nil, nil, nil, 6, 1, nil],
                [3, nil, 2, 1, 1, nil, 2],
                [nil, nil, nil, 2, 1, 1, 1, nil],
                [nil, nil, 1, nil, 2, 1, 1],
                [2, nil, 2, nil, 1, nil, nil, 2],
                [nil, 2, nil, nil, 1, 3, 4],
                [nil, nil, 4, 2, 2, nil, 2, nil],
                [nil, nil, 2, nil, nil, nil, 2],
                [nil, nil, 3, 1, nil, 5, nil, 1],
                [nil, nil, 3, 3, 4, 4, 2],
                [1, 3, 1, 4, 2, 1, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1957,
            rows: [
                [4, nil, nil, 2, 2, 2, 1, 2],
                [2, nil, 2, nil, 2, 2, 2],
                [nil, nil, 2, 1, 3, 1, 3, 1],
                [4, 1, 2, 3, 1, 2, 1],
                [nil, 3, 1, 2, 4, 4, nil, nil],
                [nil, 1, 2, 1, 1, nil, nil],
                [nil, 3, 1, 3, nil, nil, nil, nil],
                [nil, 1, 3, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 2, 1, 3],
                [1, 1, 1, 1, 1, 1, 1],
                [3, 3, 6, 1, 4, 1, 1, 1],
                [1, 1, 6, 1, 1, 1, 1],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1958,
            rows: [
                [nil, nil, 1, 5, 5, nil, 1, 1],
                [3, nil, 2, 1, 3, 1, nil],
                [nil, nil, nil, nil, 1, 4, nil, 1],
                [nil, nil, nil, 3, nil, 1, nil],
                [4, nil, 1, nil, 2, 2, 1, nil],
                [1, 1, nil, 2, nil, nil, nil],
                [1, 1, nil, 2, nil, 1, 1, 2],
                [2, nil, 1, nil, 4, nil, 4],
                [1, 3, 3, 4, 1, 5, 1, 1],
                [1, 5, 2, 1, 3, 1, 6],
                [5, 1, 1, 1, 5, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 3, 1, 1, 2, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1959,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, 1, 5, 5, 5, nil, nil],
                [nil, 1, 3, 1, 1, 1, nil],
                [nil, nil, 3, 3, 3, 1, nil, nil],
                [nil, 2, 1, 1, 2, 1, nil],
                [nil, 1, 2, 1, 2, 1, 4, nil],
                [4, 1, 1, 1, 2, 1, 1],
                [nil, 6, 1, 2, 4, 4, 1, nil],
                [6, 1, 2, 2, 1, 3, 1],
                [4, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1960,
            rows: [
                [nil, 1, 2, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, 1, nil, 4, nil, nil, nil],
                [nil, 1, nil, 1, 1, 1, nil],
                [nil, 2, 1, 2, 2, 1, 1, nil],
                [nil, 1, 3, 1, 3, 3, nil],
                [nil, 3, 1, 1, 1, 4, 1, nil],
                [nil, 4, 1, 1, 1, 2, nil],
                [nil, 3, 5, 1, 4, 4, 2, nil],
                [nil, 2, 2, 2, 2, 1, nil],
                [nil, 2, 1, 1, 2, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
    ]
}
