// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch22 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 421,
            rows: [
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
                [nil, 2, nil, 2, nil, 1, nil, 1],
                [1, nil, 1, nil, 3, nil, 3],
                [nil, 3, nil, 3, nil, 3, nil, 3],
                [3, nil, 3, nil, 3, nil, 3],
                [nil, 1, nil, 6, nil, 6, nil, 6],
                [1, nil, 1, nil, 4, nil, 4],
                [nil, 4, nil, 4, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 5, nil, 5, nil, 5],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 422,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [3, 3, nil, nil, 3, 3, nil],
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [7, 7, nil, nil, 7, 4, nil],
                [nil, 4, 4, nil, nil, 4, 4, nil],
                [4, 2, nil, nil, 2, 6, nil],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [2, 2, nil, nil, 2, 5, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 423,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 1, 1, 1, 1],
                [1, 1, 1, 1, 4, 4, 4, 4],
                [4, 4, 2, 2, 2, 7, 1],
                [1, 1, 1, 3, 3, 3, 3, 3],
                [3, 3, 2, 2, 2, 4, 4],
                [4, 4, 3, 3, 3, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [2, 2, 2, 2, 2, 2, 6, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 424,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, nil, 4, 4, nil],
                [nil, 4, 4, 4, 2, 2, 2, nil],
                [nil, 2, 2, nil, 2, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [7, nil, nil, 7, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 3],
                [3, nil, nil, 3, 3, nil, nil, 3],
                [3, nil, nil, 3, nil, nil, 3],
                [nil, 5, 2, 2, 1, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 425,
            rows: [
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, 1, 2, 2, 2, 2, 2],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, 4, nil, nil, 4, 4, nil],
                [4, nil, 4, 4, 1, nil, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, 2, 2, nil, nil, 2, 7, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, 5, 5, 3, 3, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 6, 1, 1, 5, 5, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 426,
            rows: [
                [5, nil, nil, nil, nil, nil, nil, 5],
                [5, 5, 5, 5, 5, 2, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [2, 2, 2, 1, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 4, 4, 4],
                [4, nil, nil, nil, nil, nil, nil, 4],
                [4, 4, 4, 3, 3, 3, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [4, 4, 6, 5, 1, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 427,
            rows: [
                [2, nil, 2, nil, nil, 2, nil, 2],
                [2, nil, 2, nil, 2, 4, 4],
                [nil, 4, nil, 4, 3, nil, 3, nil],
                [3, 2, nil, nil, nil, 2, nil],
                [nil, 2, nil, 1, 1, nil, 1, nil],
                [1, 1, nil, nil, nil, 3, nil],
                [1, nil, 1, 1, 1, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 5],
                [3, nil, 3, 1, 1, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 6],
                [nil, 1, 1, 1, 3, 3, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, 5, 1, 1, 1, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 428,
            rows: [
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [2, nil, nil, 2, 2, nil, nil, 2],
                [nil, nil, nil, 2, nil, nil, nil],
                [2, nil, nil, 2, 3, nil, nil, 3],
                [nil, nil, nil, 7, nil, nil, nil],
                [nil, nil, nil, 7, 4, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 429,
            rows: [
                [nil, nil, nil, 6, 6, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, 2, 1, nil],
                [nil, nil, 1, 1, 3, 1, nil, nil],
                [nil, 5, 5, 1, 1, 1, nil],
                [nil, nil, 1, 1, 3, 3, nil, nil],
                [nil, nil, 7, 7, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 430,
            rows: [
                [nil, 6, 6, nil, nil, 6, nil, nil],
                [6, 5, 3, 3, 3, 3, nil],
                [3, nil, 3, nil, nil, 3, 3, nil],
                [nil, 3, 4, 4, nil, 4, 1],
                [1, 1, 1, nil, nil, 1, 1, nil],
                [nil, 2, 2, nil, nil, nil, nil],
                [nil, 2, 2, nil, 3, 3, 3, nil],
                [nil, 3, 2, 2, 2, nil, 2],
                [1, 1, 1, nil, 1, 1, 1, nil],
                [nil, nil, 1, 1, nil, 2, nil],
                [2, 2, 1, 1, nil, 1, nil, 1],
                [2, nil, 2, nil, 2, 2, 1],
                [nil, 1, nil, nil, nil, 1, 1, 1],
                [1, nil, 1, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 431,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, 1, nil],
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [nil, 1, 1, nil, 1, nil, nil],
                [nil, 1, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 1, 1, 1, 1, nil],
                [nil, 1, 1, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 5, 5, 3, 3, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 3, 1, 1, 1, 1, 6, 6],
                [4, 4, 6, 4, 4, 4, 4],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 432,
            rows: [
                [1, nil, 1, 1, 2, 2, nil, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 3, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 4, 4, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 3, nil, 3, nil, 3, nil, 3],
                [3, nil, 3, nil, 4, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 4, nil, 4, nil, 4, nil, 4],
                [5, nil, 5, nil, 5, nil, 7],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 433,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 4, nil, 4, 4, nil, nil],
                [2, 2, nil, 2, 2, nil, nil],
                [nil, 2, 5, nil, 5, 5, nil, nil],
                [3, 3, nil, 3, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [3, 3, nil, 3, 3, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [1, 1, nil, 1, 1, nil, nil],
                [nil, 2, 2, nil, 2, 2, nil, nil],
                [2, 2, nil, 6, 6, nil, nil],
                [nil, 7, 7, nil, 1, 1, nil, nil],
                [1, 1, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 434,
            rows: [
                [5, nil, 5, 5, 2, 2, nil, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [5, 5, 5, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
                [nil, 2, nil, 3, nil, 3, nil, 3],
                [3, nil, 3, nil, 3, nil, 3],
                [nil, 3, nil, 3, nil, 4, nil, 4],
                [4, nil, 4, nil, 1, nil, 2],
                [nil, 4, nil, 4, nil, 4, nil, 4],
                [1, nil, 6, nil, 1, nil, 1],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 435,
            rows: [
                [nil, nil, nil, 2, 2, 2, 2, nil],
                [2, 2, 2, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [5, nil, nil, nil, nil, nil, 5],
                [6, nil, nil, nil, 1, 1, 1, 1],
                [1, nil, nil, 3, 3, 3, 4],
                [4, nil, nil, nil, 4, 4, 1, 5],
                [5, nil, nil, 6, 6, 3, 3],
                [3, nil, nil, nil, 3, 1, 1, 1],
                [1, 4, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, 1, 1, 1, 1],
                [6, 5, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 436,
            rows: [
                [1, nil, 1, 1, 1, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 3],
                [5, 5, 5, 5, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, 3, nil, 3, nil, 3],
                [3, nil, 3, nil, 3, nil, 3],
                [nil, 3, nil, 3, nil, 3, nil, 3],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 4, nil, 2],
                [6, nil, 6, nil, 4, nil, 4],
                [nil, 4, nil, 4, nil, 4, nil, 2],
                [4, nil, 2, nil, 2, nil, 2],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 437,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [1, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [1, 3, nil, 4, 4, nil, nil],
                [nil, 2, 2, nil, 2, 2, nil, nil],
                [3, 3, nil, 3, 3, nil, nil],
                [nil, 3, 3, nil, 3, 1, nil, nil],
                [2, 5, nil, 5, 5, nil, nil],
                [nil, 7, 7, nil, 6, 6, nil, nil],
                [6, 4, nil, 4, 4, nil, nil],
                [nil, 2, 2, nil, 2, 2, nil, nil],
                [2, 2, nil, 2, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 4
        ),
        LevelTemplate(
            levelNumber: 438,
            rows: [
                [2, 2, 2, 3, 2, 2, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, 2, 1, 1, 1, 1],
                [1, nil, nil, nil, 1, 1, 1],
                [1, nil, nil, 1, 1, 1, 1, 4],
                [4, nil, nil, nil, 3, 3, 3],
                [3, nil, nil, nil, nil, nil, 3, 3],
                [3, 3, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, 2, 2],
                [2, 5, nil, nil, nil, nil, nil],
                [5, 2, 2, 2, nil, nil, nil, nil],
                [4, 1, 1, 2, nil, nil, nil],
                [2, 2, 4, 4, nil, nil, nil, nil],
                [6, 6, 7, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 439,
            rows: [
                [3, nil, 3, nil, 3, nil, 3, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 5, nil],
                [5, nil, 5, nil, 3, nil, 3, nil],
                [nil, 3, nil, 5, nil, 5, nil],
                [5, nil, 5, nil, 2, nil, 2, nil],
                [nil, 4, nil, 4, nil, 4, nil],
                [4, nil, 4, nil, 2, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 2, 2, 2, 2],
                [4, 4, 4, 4, 4, 6, 6],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 440,
            rows: [
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [1, nil, nil, 7, 2, nil, nil, 2],
                [2, nil, 2, 2, 2, nil, 2],
                [2, nil, nil, 2, 2, nil, nil, 4],
                [4, nil, 4, 4, 4, nil, 5],
                [5, nil, nil, 5, 1, nil, nil, 2],
                [2, nil, 2, nil, 1, nil, 1],
                [3, nil, nil, 3, 3, nil, nil, 3],
                [3, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [3, nil, 3, nil, nil, 6, nil, 6],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
    ]
}
