// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch48 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 941,
            rows: [
                [nil, 1, nil, nil, 1, nil, 1, nil],
                [nil, 1, 1, nil, 1, nil, nil],
                [nil, 1, nil, 1, 1, 1, nil, nil],
                [nil, 1, 1, nil, 4, nil, nil],
                [nil, nil, 4, 1, 1, nil, nil, nil],
                [nil, 6, 6, 6, nil, nil, nil],
                [nil, 6, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, 2, nil],
                [nil, 2, 2, 2, 2, nil, 2, nil],
                [nil, 3, nil, 2, nil, 3, nil],
                [nil, 3, 3, 3, 3, 2, 2, nil],
                [nil, 2, 2, 2, 2, 3, nil],
                [nil, 4, 4, 2, 2, 2, 2, nil],
                [nil, 2, 3, 3, 3, 5, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 942,
            rows: [
                [nil, 1, nil, nil, 1, 1, 1, nil],
                [nil, 1, 1, 2, 2, nil, nil],
                [nil, nil, nil, 2, 2, nil, 1, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, 2, 2, nil, nil, 2, nil],
                [nil, 2, 2, 2, nil, 2, nil],
                [nil, nil, nil, 2, 1, nil, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, nil, 1, nil, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, 6, 1, 1, 6, 6, 6, nil],
                [nil, 1, 1, 1, 3, 3, nil],
                [nil, 3, 3, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 4, nil, 4, nil, 4, nil, 4],
                [5, nil, 5, nil, 5, nil, 5],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 943,
            rows: [
                [nil, 1, 1, 1, 1, 1, nil, 1],
                [1, nil, 1, 1, 1, 4, 4],
                [4, 4, 4, nil, nil, 4, nil, 4],
                [4, 4, 4, 4, nil, nil, 4],
                [1, nil, nil, 3, 3, 3, nil, 3],
                [3, 3, nil, nil, 3, 1, 1],
                [1, nil, nil, 1, 1, 1, nil, 1],
                [1, 1, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 5, 2, nil, 6, 6, nil, nil],
                [nil, 2, nil, 1, 1, 1, nil],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 944,
            rows: [
                [nil, 1, 4, nil, 4, 6, 6, 2],
                [2, 2, 2, 2, 5, 5, 5],
                [nil, 5, nil, nil, 1, nil, 1, 1],
                [nil, 4, nil, nil, nil, nil, nil],
                [4, 4, nil, nil, 1, 1, 1, nil],
                [1, nil, 1, nil, 1, nil, 1],
                [2, nil, 2, 2, nil, 2, 2, nil],
                [nil, nil, nil, 3, nil, nil, 3],
                [nil, nil, nil, 3, nil, 3, 2, nil],
                [nil, 2, 2, 2, nil, 2, 1],
                [1, 1, 2, 1, 1, 1, 1, 1],
                [1, nil, 3, 3, nil, nil, nil],
                [nil, 3, nil, nil, 1, nil, nil, nil],
                [1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 945,
            rows: [
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, nil, 1, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, nil, 1, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, 1, 2, 2, nil, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, nil, nil, 2, nil, nil],
                [nil, 2, nil, 2, nil, nil, nil],
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [nil, nil, 3, 3, nil, 3, nil],
                [nil, 3, 4, 4, 1, 1, 1, nil],
                [nil, 1, 4, 4, 4, 4, nil],
                [nil, 1, 1, 6, 1, 1, 1, nil],
                [nil, 1, 6, 6, 6, 5, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 946,
            rows: [
                [3, nil, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, 2, 2, nil, 2],
                [nil, 2, 2, 2, 2, 1, 1, nil],
                [3, nil, 3, nil, 3, 3, 6],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, 1, 1, nil, 1, 1, 1],
                [nil, nil, 1, nil, nil, 1, 1, nil],
                [nil, 1, 1, nil, nil, 1, nil],
                [1, 2, 2, nil, nil, 2, 3, 3],
                [nil, 3, nil, nil, 5, 5, nil],
                [2, nil, 2, 2, nil, nil, nil, nil],
                [nil, 2, 1, 1, 4, nil, 4],
                [4, 4, 4, 1, 1, 1, 5, 1],
                [1, 1, 1, 1, 1, 5, 6],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 947,
            rows: [
                [nil, 2, nil, nil, nil, 2, 2, nil],
                [2, 2, nil, 2, 2, nil, 2],
                [nil, nil, nil, 1, nil, 1, 1, 1],
                [nil, nil, 1, 1, nil, 1, 1],
                [1, nil, 1, 1, nil, 2, nil, nil],
                [2, 3, nil, nil, 3, 3, 2],
                [nil, 2, 2, nil, 2, 2, 3, nil],
                [3, nil, 3, 6, 1, 1, 1],
                [1, nil, nil, nil, nil, 4, 4, 4],
                [nil, nil, nil, 4, nil, nil, 4],
                [4, 4, 4, 1, nil, 1, nil, nil],
                [1, 1, nil, 1, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [1, 5, nil, 5, 5, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 948,
            rows: [
                [1, nil, 1, 1, 1, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, nil],
                [1, nil, 2, nil, 2, 2, nil, 2],
                [2, 2, 2, nil, 3, 1, 1],
                [nil, 4, 4, nil, 4, 4, 4, nil],
                [3, nil, nil, nil, 3, 3, nil],
                [nil, 3, nil, nil, 3, nil, nil, 3],
                [3, nil, 3, nil, 1, nil, 1],
                [nil, nil, 1, 1, 1, 1, 1, 2],
                [2, 2, 2, nil, 2, 5, 5],
                [5, 5, 5, 5, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 6, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 949,
            rows: [
                [nil, nil, nil, nil, 2, 2, 2, 2],
                [nil, 2, nil, nil, nil, 2, 2],
                [2, nil, 2, 2, nil, nil, nil, nil],
                [2, 2, 2, nil, 2, nil, 2],
                [2, nil, nil, 2, nil, 3, 3, 3],
                [3, 3, 3, nil, nil, nil, 3],
                [nil, nil, 3, 5, 5, 5, nil, 5],
                [nil, 5, nil, nil, 5, nil, nil],
                [4, 1, nil, nil, 1, 6, 6, 1],
                [nil, 1, nil, nil, 3, nil, nil],
                [1, nil, 1, nil, nil, 1, 1, nil],
                [1, nil, nil, nil, nil, 1, 1],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, nil, 1, nil, 1, 1],
                [nil, 1, 1, nil, nil, 1, 1, 1],
                [nil, 1, nil, nil, 1, nil, 1],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 950,
            rows: [
                [nil, nil, 4, 4, 4, 2, nil, nil],
                [nil, nil, 2, nil, nil, 1, nil],
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, 2, 2, nil, nil, 2, nil],
                [nil, nil, nil, 2, 3, nil, 3, nil],
                [nil, nil, nil, nil, 3, 3, nil],
                [nil, 6, nil, 6, nil, 6, 1, nil],
                [nil, nil, 1, 3, nil, 1, nil],
                [nil, 1, 1, 5, 5, 1, 1, nil],
                [nil, 4, 4, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 2, 2, nil],
                [nil, 6, nil, 6, nil, 3, nil, 3],
                [3, nil, 1, nil, 1, nil, 3],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 951,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 1, 1, nil, nil],
                [nil, 1, 2, 3, nil, 3, nil, nil],
                [6, 6, 1, nil, nil, 1, 1],
                [nil, 4, 4, 4, nil, nil, 4, nil],
                [4, nil, nil, nil, 4, nil, nil],
                [4, 4, 4, nil, nil, 2, 2, 2],
                [1, 1, nil, nil, 1, nil, 1],
                [1, nil, 1, nil, nil, nil, nil, 1],
                [2, nil, 2, nil, 2, 2, nil],
                [2, nil, 2, nil, nil, 2, nil, 2],
                [2, 2, 2, nil, 2, 5, 1],
                [1, 1, 1, 1, 3, 5, 5, 1],
                [1, 1, 3, 1, 1, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 952,
            rows: [
                [1, nil, nil, 1, 2, 2, nil, 3],
                [3, 3, nil, 2, nil, nil, nil],
                [1, 1, nil, nil, 1, nil, 1, 1],
                [nil, 1, 1, nil, 1, 1, nil],
                [1, 4, nil, 4, nil, 4, nil, 4],
                [4, 4, nil, nil, 2, 2, 2],
                [1, 1, 1, 1, 1, nil, nil, 1],
                [1, 1, 1, 1, nil, 1, 1],
                [nil, nil, nil, 3, nil, nil, 3, 3],
                [nil, 3, 3, nil, 2, 2, 2],
                [2, nil, 2, nil, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 4, 4, 4, 5, 6, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 953,
            rows: [
                [nil, 1, nil, nil, nil, 2, 2, 2],
                [2, nil, 2, nil, nil, nil, nil],
                [2, nil, 2, 2, nil, 2, nil, 1],
                [1, nil, nil, nil, 1, 1, 1],
                [1, nil, 3, nil, 1, nil, nil, 1],
                [nil, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 4, 4, 4, nil, 4],
                [nil, nil, 4, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 5, 5],
                [5, 5, 3, nil, 3, 3, 3],
                [3, 3, 3, 6, 6, 3, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 3, 3, 3, 3, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 954,
            rows: [
                [nil, 4, 4, nil, 4, 4, nil, nil],
                [nil, nil, 4, 4, 3, nil, 3],
                [3, 3, nil, nil, 3, nil, 3, 3],
                [3, 3, 1, nil, nil, nil, 1],
                [1, 1, 2, nil, nil, 2, nil, nil],
                [nil, 2, 2, 2, 1, nil, 1],
                [nil, 1, 1, nil, 1, 1, 1, 6],
                [6, 2, nil, nil, 1, 1, 1],
                [1, nil, nil, 1, 1, nil, nil, 5],
                [5, 5, nil, 1, 1, 1, 1],
                [1, nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 2, 2, 2, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 955,
            rows: [
                [nil, 1, nil, nil, 1, 1, nil, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, 3, nil, 1, nil, 1, nil, nil],
                [nil, 2, 2, nil, nil, 2, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 1, 1, 6, 6, nil],
                [nil, 6, nil, nil, 2, 2, nil, nil],
                [nil, nil, 1, nil, 1, 1, nil],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 4, nil],
                [nil, 4, 4, 4, 4, 4, nil],
                [nil, 4, 1, 1, 1, 1, 1, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [5, nil, 1, nil, 1, nil, 4],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 956,
            rows: [
                [3, nil, nil, 3, nil, 3, nil, nil],
                [nil, nil, 3, nil, 3, 3, 3],
                [nil, 3, 3, nil, nil, 3, 6, nil],
                [6, nil, 1, nil, 1, nil, 2],
                [2, 2, 2, 1, 1, nil, 1, nil],
                [nil, 1, 1, 5, nil, nil, 5],
                [5, nil, nil, nil, nil, 4, nil, nil],
                [nil, nil, 4, nil, nil, 4, 4],
                [4, 4, nil, nil, 4, 5, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, 1, nil, 1, nil, 1, 1, nil],
                [4, 4, nil, nil, 1, nil, 2],
                [nil, nil, 2, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [1, 1, 1, 1, 2, 1, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 957,
            rows: [
                [nil, 1, nil, nil, 5, 5, nil, nil],
                [nil, 5, nil, nil, 5, nil, nil],
                [nil, 5, nil, nil, 5, 4, 4, nil],
                [nil, nil, 4, nil, 3, 3, nil],
                [nil, 3, 3, nil, 3, nil, 3, nil],
                [nil, nil, 3, nil, 3, nil, nil],
                [nil, 3, 1, nil, 1, 1, 2, nil],
                [nil, 2, 2, 2, 2, nil, nil],
                [nil, 1, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 6, nil, 6, nil],
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil],
                [nil, 1, 1, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 958,
            rows: [
                [1, 2, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, 2, nil, nil],
                [3, nil, nil, nil, 3, 3, nil, 2],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [1, 1, 1, 1, 1, 6, 2],
                [5, 5, 5, 4, 4, 4, 4, 4],
                [4, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 3, 3, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 6, 6, 2, 2, 2, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 959,
            rows: [
                [nil, 2, 2, 2, 1, 1, nil, nil],
                [nil, nil, 1, nil, 1, 1, nil],
                [nil, 6, nil, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, 1, 1, nil, nil],
                [nil, nil, 2, nil, 2, 2, nil],
                [nil, 2, 3, 3, 3, 3, nil, nil],
                [nil, 3, 3, 1, 1, 1, nil],
                [nil, nil, 1, 1, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, nil, 1, nil],
                [nil, nil, 4, 4, nil, 4, nil],
                [nil, 4, 4, 4, 4, 6, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 2, 2, 2, 2, 2, nil],
                [nil, 2, 5, 5, 5, 4, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 960,
            rows: [
                [1, 1, 6, nil, nil, nil, 6, nil],
                [6, 4, 3, nil, 3, nil, 3],
                [3, 3, 3, 3, nil, nil, 3, nil],
                [nil, 3, nil, nil, nil, 3, 1],
                [1, 2, 2, 2, 1, 1, nil, 1],
                [2, 2, 2, nil, 2, 2, nil],
                [1, 1, 1, 1, nil, nil, 1, 5],
                [nil, nil, 5, nil, nil, 1, nil],
                [1, 1, 1, nil, 1, 1, 1, nil],
                [1, 4, 4, nil, nil, nil, 4],
                [4, 4, 4, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
    ]
}
