// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch05 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 81,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, nil, 1, nil, 2, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, nil, 2, nil, 5, nil],
                [5, nil, nil, 5, 5, nil, nil, 5],
                [2, 2, nil, 2, nil, 2, 2],
                [2, nil, nil, 7, 4, nil, nil, 1],
                [1, 1, nil, 1, nil, 4, 4],
                [nil, 4, 4, 4, 4, 4, 3, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 3, 3, 7, 1, 6, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 82,
            rows: [
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, nil, 3, 2, nil, 2, nil],
                [nil, 2, 2, 1, 1, 1, nil],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [nil, 1, 1, 3, 5, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 4, 4, nil, nil],
                [3, 3, 3, 3, 3, 3, 4, 4],
                [4, nil, nil, nil, nil, nil, 4],
                [4, 5, 5, 5, 4, 5, 5, 5],
                [5, nil, nil, nil, nil, nil, 5],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 83,
            rows: [
                [2, nil, nil, 2, 1, nil, nil, 6],
                [4, nil, 4, nil, 4, nil, 4],
                [nil, 4, 4, nil, nil, 4, 1, nil],
                [6, 6, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, nil, 2, 2],
                [2, nil, 2, 1, 1, 1, nil, 1],
                [2, 2, nil, nil, nil, 1, 1],
                [2, nil, 2, 2, 2, 2, nil, 5],
                [5, 5, nil, nil, nil, 1, 3],
                [nil, 3, 3, nil, nil, 3, 1, nil],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, nil, 1, nil, 1, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 84,
            rows: [
                [1, nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, 1, nil, nil, 1, 1],
                [nil, 1, 4, 4, 1, nil, nil, 1],
                [nil, nil, nil, nil, 1, nil, 1],
                [nil, 4, nil, 2, nil, 2, 2, 2],
                [nil, nil, 2, nil, nil, 2, 2],
                [2, 6, 6, 6, 6, 2, 2, 2],
                [2, 2, 2, nil, 2, 1, 1],
                [1, 3, 3, 3, 3, 3, 3, 3],
                [1, 1, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 5, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 85,
            rows: [
                [6, 6, nil, nil, nil, nil, 6, 6],
                [1, 3, nil, nil, nil, 3, 3],
                [3, 3, nil, nil, nil, nil, 3, 3],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 4],
                [4, 4, nil, nil, nil, nil, 1, 1],
                [1, 1, 1, 1, 2, 2, 2],
                [2, 2, nil, nil, nil, nil, 2, 3],
                [3, 3, 3, 3, 2, 2, 2],
                [nil, 2, 2, 2, 2, 2, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, 1, 1, 3, 3, 3, nil],
                [nil, 3, nil, 3, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 86,
            rows: [
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [3, nil, 3, nil, 3, nil, 3],
                [3, nil, 3, 3, 1, 1, nil, 6],
                [6, 6, nil, 1, nil, 1, 1],
                [1, nil, 1, 1, 2, 2, nil, 2],
                [2, 2, nil, 2, nil, 2, 1],
                [nil, 1, nil, 1, 2, nil, 2, nil],
                [2, 1, 1, nil, 1, 1, 1],
                [nil, 5, nil, 5, 5, nil, 5, nil],
                [1, 1, 1, nil, 1, 1, 1],
                [4, nil, 4, nil, nil, 1, nil, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 87,
            rows: [
                [4, 4, nil, nil, nil, nil, nil, nil],
                [4, 4, nil, nil, nil, nil, nil],
                [4, 4, 4, nil, nil, nil, nil, nil],
                [4, 4, 2, nil, nil, nil, nil],
                [1, 2, 2, nil, nil, nil, nil, nil],
                [2, 2, 2, nil, nil, nil, nil],
                [3, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 2, nil, nil, nil],
                [2, 2, 2, 2, nil, nil, nil, nil],
                [2, 2, 1, 3, nil, nil, nil],
                [3, 3, 1, 1, 1, nil, nil, nil],
                [1, 1, 3, 3, 1, nil, nil],
                [1, 1, 1, 1, 1, nil, nil, nil],
                [5, 1, 1, 1, 1, nil, nil],
                [1, 1, 7, 7, 3, 5, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 88,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, 2, 2, 1, 1, nil, nil, 1],
                [2, 2, 2, 2, 2, nil, 2],
                [nil, 2, 2, 2, 4, nil, nil, 4],
                [4, 4, 4, 4, 1, nil, 1],
                [1, 1, 6, 6, 6, 6, 3, nil],
                [1, 1, 1, 1, 1, nil, 1],
                [3, 3, 3, 3, 1, 5, 1, nil],
                [1, 1, 1, 1, 1, nil, 1],
                [nil, 1, 1, 1, 1, nil, nil, 1],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil, 1],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 89,
            rows: [
                [nil, nil, 2, 2, nil, nil, nil, nil],
                [nil, 2, 1, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 4, nil, nil],
                [4, 4, 4, 1, 5, 5, 5],
                [nil, 5, 5, 1, 1, 1, nil, nil],
                [1, 1, 1, 3, 3, 3, 3],
                [3, 1, 6, 6, 2, 2, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [2, 2, 2, 2, 2, 1, 2, 1],
                [1, 1, 1, 1, 5, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 90,
            rows: [
                [nil, 3, nil, nil, nil, nil, 4, nil],
                [4, nil, nil, 4, nil, nil, 4],
                [4, 3, 3, 3, 3, 3, 3, 3],
                [3, nil, nil, 5, nil, nil, 2],
                [2, 1, 1, 1, 2, 2, 2, 2],
                [1, nil, nil, 7, nil, nil, 7],
                [nil, 1, nil, 1, nil, nil, 1, nil],
                [nil, nil, 1, 2, nil, nil, nil],
                [nil, 2, nil, 2, nil, nil, 2, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 91,
            rows: [
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 4, 1, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, 1, 3, nil, nil, 3, 3, nil],
                [3, 5, nil, nil, nil, 5, 5],
                [nil, 5, 3, nil, nil, 3, 6, nil],
                [6, 5, nil, nil, nil, 5, 2],
                [2, 2, nil, nil, nil, nil, 2, 3],
                [3, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 92,
            rows: [
                [1, nil, nil, 2, nil, 2, nil, 2],
                [2, 4, 4, nil, nil, 1, 1],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 3, 1, 1, 1, 5],
                [nil, nil, 5, 3, 3, 3, 3, 3],
                [nil, nil, 3, 3, 2, 2, 2],
                [nil, nil, 2, 2, 2, 2, 2, 2],
                [nil, nil, 2, 2, 1, 1, 1],
                [nil, nil, nil, 1, 1, nil, 1, 1],
                [nil, nil, nil, 5, nil, 1, 1],
                [nil, nil, nil, 4, 4, nil, 4, 1],
                [nil, nil, nil, 1, nil, 1, 6],
                [nil, nil, nil, nil, nil, nil, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 93,
            rows: [
                [2, nil, 2, nil, 3, nil, 3, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [3, nil, 1, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [nil, nil, 4, 4, 4, 1, 2, nil],
                [nil, 1, 1, 1, 2, 2, nil],
                [nil, 2, 2, 2, 2, 3, 3, nil],
                [3, 3, 3, 3, 1, 1, 1],
                [nil, 2, 2, 2, 2, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, 6, 1, 1, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 5, nil, nil, nil],
                [nil, nil, 5, 1, 1, nil, nil],
                [nil, nil, nil, 6, 6, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 94,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 1, 5, 5, nil, nil],
                [nil, nil, 5, 6, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 1, 3, 3, 3, nil, nil],
                [nil, nil, 3, 4, 7, nil, nil],
                [nil, nil, nil, 7, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 95,
            rows: [
                [nil, 3, 3, nil, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, 1, nil, nil, nil, 5, nil, nil],
                [nil, 5, nil, nil, nil, 5, nil],
                [nil, 5, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 3, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil, nil],
                [nil, 7, 7, 1, nil, nil, nil],
                [nil, 1, 3, 5, nil, nil, nil, nil],
                [nil, 5, 1, 4, nil, nil, nil],
                [nil, 4, 4, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 96,
            rows: [
                [nil, nil, nil, 6, nil, nil, nil, nil],
                [nil, nil, 6, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 2, 2, 2, nil],
                [nil, 2, 2, 2, 1, 1, nil],
                [nil, 1, 3, 3, 5, 5, 5, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 3, 3, 3, 3, 3, 2, nil],
                [nil, 2, 2, 2, 4, 4, nil],
                [nil, 4, 4, 4, 4, 4, 4, nil],
                [nil, 3, 1, 3, 3, 3, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 97,
            rows: [
                [nil, 5, nil, nil, 4, 4, 4, nil],
                [4, nil, nil, 3, 3, 3, nil],
                [3, nil, nil, 3, 3, 3, nil, nil],
                [3, nil, 2, 2, 2, nil, nil],
                [2, nil, nil, 2, 2, 1, nil, nil],
                [1, nil, 1, 1, 1, nil, nil],
                [1, nil, nil, 1, 5, 1, nil, nil],
                [5, nil, 5, 5, 1, 1, nil],
                [1, nil, nil, 1, 1, 1, nil, nil],
                [1, nil, 1, 6, 6, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 98,
            rows: [
                [nil, 2, nil, nil, 2, 2, 2, nil],
                [nil, 2, 2, 2, nil, 2, nil],
                [nil, nil, 2, nil, 2, nil, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil],
                [nil, 1, 1, 1, nil, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 4, 4, 4, 4, 4, 3, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, nil, 3, 3, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 6, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 1, 1, 1, nil, 1],
                [1, nil, 1, nil, nil, 6, 6],
                [1, nil, 1, nil, 4, 4, nil, 1],
                [1, nil, 1, nil, nil, 1, 5],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 99,
            rows: [
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, 1, 1, 3, 3, nil, nil],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, 2, nil, nil, nil, 4, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [7, 7, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, 5, nil, nil, 5],
                [5, nil, nil, 5, nil, nil, 1],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 100,
            rows: [
                [2, 2, nil, nil, 2, 1, 2, nil],
                [3, 2, 4, nil, 4, nil, 4],
                [nil, 4, 4, nil, 4, 4, 4, nil],
                [nil, 4, 2, nil, 2, 3, nil],
                [3, nil, 2, 2, nil, 2, nil, 2],
                [2, nil, nil, nil, 2, 2, 2],
                [1, 1, 3, 3, nil, nil, nil, 3],
                [3, nil, 3, nil, 3, nil, nil],
                [nil, 3, nil, 3, nil, 5, nil, 5],
                [5, nil, 1, nil, 1, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [6, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
    ]
}
