// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch61 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1201,
            rows: [
                [nil, 1, 1, nil, nil, nil, 1, 1],
                [nil, 2, 1, 3, nil, nil, 3],
                [nil, 4, 4, 4, nil, nil, 3, 1],
                [nil, 1, 2, 1, nil, 2, 2],
                [nil, 1, 2, 1, nil, nil, 5, 2],
                [nil, 1, 2, 1, nil, 3, 3],
                [nil, 1, 2, 1, nil, 4, 1, 4],
                [nil, 1, 1, 2, nil, 2, 1],
                [nil, 2, 1, 1, nil, 2, 1, 2],
                [nil, 1, 1, 1, nil, 2, 1],
                [nil, 2, 2, 1, nil, 1, 1, 1],
                [nil, 3, 1, 3, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1202,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 6, 1, 2, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 2, 3, 6, 2, nil, nil],
                [nil, nil, 5, 4, 1, nil, nil],
                [nil, nil, 4, 3, 2, 2, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, 2, 3, 1, 4, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 3, 5, 1, 4, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1203,
            rows: [
                [nil, nil, 5, nil, nil, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, 2, 2],
                [nil, nil, 6, 1, 2, 2, 1, 1],
                [1, 1, 1, 3, 1, 2, 3],
                [2, 1, 1, 1, 2, 2, 1, 4],
                [6, 1, 5, 1, 3, 1, 2],
                [nil, 1, 2, 2, 1, 4, 1, 1],
                [nil, 4, 4, 1, 1, 4, 4],
                [nil, 1, 3, 1, 3, 3, 1, 3],
                [nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1204,
            rows: [
                [1, 2, 2, nil, nil, nil, 2, nil],
                [nil, nil, 3, nil, 2, 1, nil],
                [nil, nil, 5, nil, 5, 2, 1, 1],
                [nil, nil, nil, 3, 3, nil, 3],
                [nil, 2, 2, 2, 1, 1, 1, 5],
                [nil, 1, nil, nil, nil, nil, 2],
                [nil, 1, nil, 4, nil, nil, nil, nil],
                [4, nil, 1, nil, 4, 2, nil],
                [1, nil, 3, 2, 1, 3, 2, 1],
                [1, 1, nil, 2, 1, 3, 3],
                [3, nil, 3, nil, 1, nil, 2, nil],
                [nil, 1, 2, 2, 1, nil, 2],
                [nil, 2, 1, 1, nil, 2, 1, nil],
                [1, 2, 1, 2, nil, 1, nil],
                [nil, nil, 1, 1, nil, nil, 2, nil],
                [nil, 1, 1, 2, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1205,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 2, 2, 1, 1, 1, nil],
                [1, 2, 2, nil, 2, 2, 2],
                [nil, 2, 2, 1, 4, 1, 1, nil],
                [3, 1, 3, nil, 1, 3, 1],
                [3, 1, 3, nil, nil, 1, 6, 1],
                [1, 4, 1, nil, 1, 4, 1],
                [3, 1, 3, nil, nil, 1, 1, 3],
                [1, 1, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1206,
            rows: [
                [nil, 1, 2, nil, nil, nil, nil, 1],
                [2, 1, nil, nil, 1, 2, 1],
                [4, 4, 3, 3, nil, 1, 1, 3],
                [3, 2, nil, nil, nil, nil, 1],
                [nil, nil, 1, nil, 1, 2, 2, 1],
                [1, 2, 1, nil, 4, 1, 1],
                [4, 4, 2, 2, 1, 2, 5, 3],
                [1, 2, 2, nil, 2, 1, 2],
                [1, 3, 1, 2, 2, 1, 2, 1],
                [1, 1, 3, nil, 1, 1, 1],
                [4, 1, 3, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1207,
            rows: [
                [nil, nil, 5, 3, nil, 3, nil, nil],
                [nil, 1, 1, 2, 3, nil, nil],
                [nil, 1, 2, 1, 2, nil, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 3, nil],
                [nil, 3, nil, 4, 1, 2, 3, nil],
                [nil, 3, 1, nil, nil, 3, nil],
                [nil, nil, nil, 3, 1, 6, 1, nil],
                [nil, 4, 4, 4, 4, 2, nil],
                [nil, 2, 1, 2, 3, 1, 1, nil],
                [nil, 5, 1, 2, 1, 2, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1208,
            rows: [
                [nil, 1, 3, 3, 1, 3, 3, 3],
                [2, 1, 1, 3, 3, 1, 1],
                [2, 1, 4, 1, 4, 1, 4, 1],
                [2, 1, 4, 1, 2, 2, 1],
                [nil, 1, 5, 1, 1, 1, nil, nil],
                [nil, 1, 4, 1, 4, nil, nil],
                [nil, 4, 2, 2, nil, nil, nil, nil],
                [nil, 2, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 3, 1, 3, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1209,
            rows: [
                [3, nil, 2, 2, 1, nil, 2, 4],
                [4, 3, 2, 1, 1, 2, 2],
                [4, nil, nil, 2, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, 3],
                [3, 2, 1, 1, nil, nil, 2, nil],
                [3, nil, nil, nil, 2, nil, 1],
                [nil, 1, 1, nil, nil, nil, nil, 3],
                [nil, 2, 2, 2, nil, 1, nil],
                [4, nil, nil, 1, nil, nil, nil, 1],
                [2, nil, nil, 1, 5, nil, nil],
                [1, nil, nil, 4, nil, nil, 1, nil],
                [4, 4, nil, 2, 4, nil, 3],
                [3, 2, 2, 1, 2, 1, 1, 1],
                [2, 2, 2, 2, 1, 1, 1],
                [1, 1, 1, 2, 1, 1, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1210,
            rows: [
                [3, 3, nil, 2, nil, 2, nil, 2],
                [nil, nil, 2, nil, 1, 3, 2],
                [1, nil, 4, nil, 2, 2, nil, 1],
                [2, 3, 1, nil, 2, 1, 2],
                [1, 1, 2, 1, 2, 1, 2, 2],
                [3, 3, 1, 1, 1, 3, 3],
                [3, 3, 3, 1, 1, 1, 1, 2],
                [2, 1, 1, 2, 2, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, 6, nil, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [nil, 2, 1, nil, 1, 2, nil, nil],
                [nil, 2, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1211,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, 2],
                [3, nil, nil, 1, 3, nil, 3],
                [nil, 1, 3, 3, nil, nil, nil, nil],
                [1, nil, nil, nil, 3, 1, 2],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [1, 1, 1, nil, nil, 4, 5],
                [1, nil, nil, nil, nil, 2, 2, 2],
                [1, 3, 1, nil, 1, 1, 5],
                [3, nil, nil, nil, nil, nil, 3, 5],
                [4, 2, nil, nil, 2, 1, 4],
                [1, 1, 2, 1, 1, 4, 1, 4],
                [1, 2, 1, 2, 1, 2, 1],
                [2, 2, 1, 1, 2, 1, 1, 4],
                [4, 4, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1212,
            rows: [
                [nil, nil, 4, 3, 1, nil, nil, nil],
                [nil, nil, 4, 4, 1, 1, nil],
                [nil, 2, nil, nil, 1, nil, 1, nil],
                [nil, 2, nil, nil, 2, 1, nil],
                [nil, 4, 2, nil, 1, 2, 1, nil],
                [nil, 1, nil, 2, 1, 3, nil],
                [nil, 3, 2, 1, 3, nil, 3, nil],
                [nil, 1, nil, 1, 2, 2, nil],
                [nil, 1, 1, 1, 1, 4, 4, nil],
                [nil, 1, 3, 1, 1, 3, nil],
                [nil, 3, 3, 3, 3, 1, 1, nil],
                [nil, 2, 1, 2, 1, 1, nil],
                [nil, 2, 1, 2, 1, 4, 1, nil],
                [nil, 4, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1213,
            rows: [
                [2, nil, 1, nil, 1, 1, nil, nil],
                [2, 3, 2, nil, 2, 3, 1],
                [5, 5, 1, 2, nil, 1, nil, 1],
                [1, nil, 1, nil, 3, nil, nil],
                [3, 2, nil, 2, 1, 2, 1, 2],
                [1, 3, 3, nil, 3, 2, 2],
                [1, 2, 1, 2, 2, 1, 2, 1],
                [1, 4, 1, nil, 2, 2, 1],
                [4, 1, 1, 1, 1, 3, 1, 2],
                [1, 1, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1214,
            rows: [
                [nil, nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, 3, nil, nil, 2, nil, 3, nil],
                [3, nil, nil, 5, nil, nil, 1],
                [nil, 5, nil, nil, 1, nil, 2, nil],
                [1, nil, nil, 5, nil, nil, 1],
                [nil, 5, nil, nil, 1, nil, 2, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [nil, 2, nil, nil, 1, nil, 5, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1215,
            rows: [
                [1, nil, 3, nil, nil, 3, 3, nil],
                [1, 2, 2, 1, nil, nil, 2],
                [nil, 1, 2, nil, nil, 2, 1, 1],
                [1, 3, 3, 3, nil, 2, 5],
                [nil, nil, nil, nil, nil, 4, nil, nil],
                [4, nil, 2, nil, nil, 2, 2],
                [nil, 2, 2, 2, 3, 2, 2, 1],
                [2, 2, 2, 1, nil, nil, 1],
                [2, 2, nil, 1, nil, nil, 3, nil],
                [1, 3, nil, nil, 1, nil, 1],
                [nil, nil, 5, 1, nil, 2, nil, nil],
                [nil, 1, nil, 3, 1, nil, 2],
                [1, nil, 1, nil, nil, 1, 1, nil],
                [1, nil, 4, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1216,
            rows: [
                [nil, 2, 2, nil, nil, 3, 6, nil],
                [1, nil, 2, nil, 5, nil, 2],
                [1, nil, nil, 4, 1, nil, nil, 1],
                [2, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 2],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, 2, nil, nil, nil, nil, 4, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, 5, nil, 2, nil, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, 3, nil, 3, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1217,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, 4, 2, 1, nil, 2, nil, nil],
                [2, nil, 1, 1, 2, nil, nil],
                [nil, 3, 1, nil, nil, 1, 3, nil],
                [3, 3, nil, 3, nil, 4, 2],
                [nil, nil, 2, 4, 4, nil, 4, nil],
                [nil, nil, 1, nil, nil, 5, nil],
                [1, 2, 2, 2, 2, 1, 2, 3],
                [3, 3, 2, 1, 1, 2, 2],
                [nil, 1, 2, 1, 2, 1, 1, 3],
                [nil, 3, 3, 1, 2, 1, 1],
                [nil, 5, 1, 1, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1218,
            rows: [
                [2, 5, 1, 3, nil, nil, 3, 1],
                [3, 4, nil, nil, nil, nil, 1],
                [1, nil, 2, nil, nil, 3, 1, 2],
                [nil, nil, 3, nil, 3, nil, 1],
                [1, 2, nil, 1, nil, nil, nil, 2],
                [nil, 2, 3, nil, 1, nil, nil],
                [nil, 4, nil, 4, 4, 1, 3, 1],
                [1, 2, 2, nil, 1, 5, 1],
                [1, 2, 2, 1, 1, 3, 2, 2],
                [2, 2, 5, nil, 1, 3, 2],
                [1, 1, 5, 1, 3, 1, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1219,
            rows: [
                [nil, nil, 4, 1, nil, nil, nil, nil],
                [nil, 4, 2, 2, nil, nil, nil],
                [nil, 2, 1, 2, 2, 1, nil, nil],
                [2, 1, 3, 2, 2, 3, 1],
                [nil, 1, 2, 1, 2, 2, nil, nil],
                [4, 2, 1, 4, 1, 3, 4],
                [6, 1, 6, 1, 1, 2, 2, 3],
                [1, 3, 2, 1, 6, 1, 1],
                [2, 1, 2, 2, 1, 3, 3, 1],
                [2, 1, 1, 2, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1220,
            rows: [
                [1, 2, 2, nil, 2, 2, 2, 1],
                [4, 2, nil, 2, nil, nil, nil],
                [nil, 1, nil, 3, 3, 4, 2, 4],
                [nil, 1, nil, 1, 1, 4, nil],
                [nil, nil, nil, 3, 3, 2, 1, 1],
                [3, 1, 2, 2, 2, 2, 1],
                [2, 1, 1, 3, 3, 1, 3, 1],
                [5, 1, 6, 1, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 5, nil, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
    ]
}
