// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch06 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 101,
            rows: [
                [nil, nil, 1, nil, nil, 4, 4, nil],
                [nil, 4, 4, nil, nil, 5, 5],
                [1, nil, nil, 1, 1, 1, nil, nil],
                [5, 2, nil, 2, nil, nil, nil],
                [2, nil, nil, 5, 5, 5, nil, nil],
                [2, 1, nil, 1, nil, nil, nil],
                [1, nil, 1, 2, 2, 2, 2, nil],
                [nil, 2, nil, nil, 2, nil, 3],
                [3, nil, 3, 3, 3, 3, 1, nil],
                [nil, 1, nil, nil, 1, nil, 1],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 6, nil, nil, nil, 6, nil],
                [nil, nil, 6, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 102,
            rows: [
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [2, 2, 2, 1, 1, 1, 1],
                [4, 4, 4, 5, 5, 5, 1, 1],
                [1, 1, 1, 1, 1, 2, 2],
                [2, 2, 2, 2, 3, 3, 3, 3],
                [3, 3, 3, 3, 3, 1, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, 2, nil, nil, 7, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 103,
            rows: [
                [2, 2, 2, 2, 2, 2, 2, 1],
                [nil, nil, nil, nil, nil, nil, 3],
                [3, 3, 3, 1, 1, 1, 4, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [4, 1, 1, 5, 5, 5, 2, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 2, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, 1],
                [5, 1, 1, 1, 1, 6, 6, nil],
                [6, nil, nil, nil, nil, nil, nil],
                [1, 1, 3, 1, 1, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 104,
            rows: [
                [2, 2, 2, 2, 2, 2, 2, 6],
                [6, 4, 4, 4, 4, 4, 4],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 3, 1, 1, 1],
                [5, 5, 1, 1, 1, 1, 3, 3],
                [1, 1, 3, 3, 3, 7, 7],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 105,
            rows: [
                [nil, nil, 1, 1, nil, 1, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, 1, nil],
                [nil, 1, 1, nil, nil, 1, 1],
                [nil, 1, 1, 1, 1, 3, 3, nil],
                [nil, nil, nil, 3, nil, 3, 3],
                [3, 3, nil, nil, 3, nil, 2, nil],
                [2, 2, 2, nil, 2, nil, 2],
                [2, nil, nil, 6, 6, 6, nil, 4],
                [4, 2, nil, 2, 2, 2, 2],
                [nil, 2, nil, 2, 2, 2, 2, 4],
                [nil, 4, 4, 4, 4, 1, 1],
                [nil, 1, 1, nil, nil, 1, 1, 5],
                [nil, 1, 1, nil, 1, nil, 1],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 106,
            rows: [
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, 4, 2, 2, 2, 2, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, 5, 5, 5, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 1, 1, 4, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, 1, 7, 7, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 107,
            rows: [
                [nil, nil, nil, nil, 4, nil, nil, nil],
                [nil, 4, nil, nil, 4, 4, nil],
                [nil, 4, 5, nil, 5, nil, 5, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, nil, nil, nil, nil, nil],
                [2, 3, nil, 3, nil, 3, 1],
                [nil, 1, nil, nil, 1, nil, 1, 1],
                [1, 1, 1, 1, nil, nil, nil],
                [1, nil, nil, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, nil],
                [nil, 1, nil, 3, 3, nil, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1],
                [nil, 1, 2, 2, 2, 1, 1, 1],
                [nil, 1, 2, 2, 2, 2, 2],
                [nil, nil, 2, 6, 6, 6, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 108,
            rows: [
                [nil, nil, nil, 4, 5, nil, nil, nil],
                [nil, nil, 5, 5, 5, nil, nil],
                [nil, 5, 5, 5, 1, 6, 4, nil],
                [4, 4, 2, 2, 2, 2, 2],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [2, 2, 1, 1, 4, 4, 4],
                [nil, 4, 4, 3, 3, 3, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 3, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 6, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 109,
            rows: [
                [2, 2, nil, nil, nil, nil, nil, nil],
                [2, 2, nil, nil, nil, nil, nil],
                [2, 2, 2, nil, nil, nil, nil, nil],
                [2, 3, 3, nil, nil, nil, nil],
                [3, 3, 3, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [1, 4, 2, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [1, 6, 6, 6, 1, nil, nil, nil],
                [1, 1, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, 3, nil, nil, nil],
                [3, 3, 5, 5, 5, nil, nil],
                [5, 4, 4, 4, 4, 7, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 110,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, 1, 2, 2, 2, 2, 2, nil],
                [2, 2, 1, 1, 1, 1, 5],
                [nil, 5, 5, 5, 1, 3, 3, nil],
                [3, 7, 4, 4, 1, 1, 1],
                [nil, 1, 3, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 3, 3, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 7, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, 1, 1, 3, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 111,
            rows: [
                [nil, nil, nil, nil, 2, 2, 2, nil],
                [nil, nil, 2, 2, 2, 4, 4],
                [nil, nil, 4, 4, 2, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 2, 2, 2, 1, 7, nil],
                [nil, 7, 3, 3, 3, 3, nil],
                [nil, 3, 3, 3, 2, 2, nil, nil],
                [2, 2, 2, 2, 5, nil, nil],
                [nil, 5, 1, 1, 1, 3, nil, nil],
                [3, 3, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 5, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 112,
            rows: [
                [3, nil, nil, 3, 3, nil, nil, 3],
                [4, nil, 4, 4, 4, nil, 4],
                [nil, 4, nil, 1, 1, nil, 1, nil],
                [nil, 1, 3, 3, 3, 6, nil],
                [nil, 6, nil, 2, 2, nil, 2, nil],
                [nil, 2, 1, 1, 1, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [1, 1, 5, 5, 5, 5, 1, 3],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 113,
            rows: [
                [2, nil, nil, 2, 2, nil, nil, 1],
                [1, 1, 1, 1, 2, 2, 2],
                [nil, 6, 6, nil, nil, 6, 2, nil],
                [2, nil, 2, 2, 4, nil, 3],
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [3, nil, 3, 1, 1, nil, 1],
                [nil, 2, 2, nil, nil, 1, 5, nil],
                [nil, nil, 5, 5, 5, nil, nil],
                [nil, 5, 1, nil, nil, 4, 4, nil],
                [nil, nil, 2, 3, 3, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 7, 2, 2, 2, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 114,
            rows: [
                [3, 5, nil, nil, nil, nil, nil, nil],
                [5, 5, nil, nil, nil, nil, nil],
                [5, 3, 3, nil, nil, nil, nil, nil],
                [3, 3, 3, nil, nil, nil, nil],
                [3, 3, 3, nil, nil, nil, nil, nil],
                [3, 3, 3, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [1, 4, 1, 1, 1, nil, nil, nil],
                [1, 1, 2, 6, 6, nil, nil],
                [1, 1, 1, 1, 2, nil, nil, nil],
                [2, 2, 2, 2, 2, nil, nil],
                [1, 1, 2, 2, 2, 7, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 115,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, 2, 1, 5, 5, 5, 5, nil],
                [5, 5, 5, 6, 3, 3, 3],
                [nil, 3, 3, 3, 3, 3, 3, nil],
                [3, 3, 2, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 3, 3, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 3, 4, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 116,
            rows: [
                [nil, nil, nil, nil, 1, 1, 2, nil],
                [nil, nil, 2, 2, 2, 2, 3],
                [nil, nil, 2, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 4, nil],
                [nil, nil, 4, 3, 3, 3, 3, nil],
                [nil, 4, 4, 4, 4, 4, nil],
                [nil, 5, 5, 5, 5, 5, nil, nil],
                [5, 4, 4, 4, 1, nil, nil],
                [nil, 2, 2, 2, 2, 3, nil, nil],
                [3, 1, 2, 2, 2, nil, nil],
                [1, 1, 1, 6, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 117,
            rows: [
                [5, nil, nil, nil, 5, nil, nil, 5],
                [1, 1, nil, nil, 1, nil, 1],
                [nil, nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, 6, nil, 6, nil],
                [nil, nil, 6, nil, 2, nil, 2, nil],
                [4, nil, 4, 4, nil, 4, nil],
                [4, 2, 2, 2, 1, 1, nil, 3],
                [nil, nil, 2, 2, 2, 2, 1],
                [1, 1, 1, 3, 2, 2, nil, 2],
                [nil, nil, 2, 2, 2, 2, 2],
                [nil, 2, 3, nil, nil, 1, nil, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, nil, 3, nil, nil],
                [3, 3, nil, nil, nil, 3, 1],
                [1, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 118,
            rows: [
                [2, nil, nil, 2, 2, nil, nil, 2],
                [5, nil, 5, 5, 5, nil, 5],
                [nil, 1, nil, 2, 2, nil, 2, nil],
                [nil, 2, 2, 2, 1, 1, nil],
                [nil, 1, nil, 2, 2, nil, 2, nil],
                [nil, 2, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 4, 7, 7, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 1, 1, 3, nil, nil],
                [3, 3, 3, 1, 1, 3, 3, 3],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 3, 3, 3, 3, 3],
                [4, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 119,
            rows: [
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 4, nil],
                [nil, 4, 4, 4, 4, 3, 6, nil],
                [nil, 5, 5, 5, 2, 2, nil],
                [nil, 2, 7, 3, 3, 3, 3, nil],
                [nil, 3, 3, 6, 5, 5, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 120,
            rows: [
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 1, 1, nil, nil, 7, 7, nil],
                [2, nil, 2, 2, 2, nil, 1],
                [nil, 4, 4, nil, nil, 4, 4, nil],
                [2, nil, 1, 1, 1, nil, 1],
                [nil, 1, 3, nil, nil, 3, 1, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, 5, 5, nil, nil, 5, 2, nil],
                [nil, nil, 2, 2, 6, nil, nil],
                [nil, 2, 2, 2, 2, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 3, 6, 2, 1, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
    ]
}
