// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch86 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1701,
            rows: [
                [nil, nil, nil, nil, nil, nil, 4, 1],
                [nil, nil, 5, 5, 5, 5, 2],
                [nil, nil, nil, nil, nil, nil, 2, 3],
                [nil, 4, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, 3, 4],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 1, 1, nil, nil, 5, nil, nil],
                [4, 1, 2, nil, 2, nil, nil],
                [nil, 1, 1, nil, nil, 2, nil, nil],
                [1, 4, 1, nil, 4, nil, nil],
                [1, nil, 4, 1, 1, 2, nil, 1],
                [nil, 4, nil, 1, nil, 5, 1],
                [3, nil, 3, 1, 1, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, 1],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1702,
            rows: [
                [1, 2, 1, 1, 5, 2, 2, 4],
                [nil, nil, nil, nil, nil, nil, 1],
                [3, 1, 5, 1, 2, 3, 2, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [2, 2, 1, 3, 3, 3, 5, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [2, 4, 1, 3, 1, 1, 2, 2],
                [nil, nil, nil, nil, nil, nil, 4],
                [4, 3, 1, 1, 2, 1, 2, 2],
                [nil, nil, nil, nil, nil, nil, 3],
                [3, 1, 2, 1, 2, 5, 1, nil],
                [5, nil, nil, nil, nil, nil, nil],
                [1, 4, 1, 2, 1, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1703,
            rows: [
                [nil, 3, nil, nil, nil, nil, 1, nil],
                [1, nil, nil, 2, nil, nil, 1],
                [1, nil, nil, 5, 1, nil, nil, 1],
                [1, nil, nil, 2, nil, nil, 2],
                [2, nil, nil, 2, 5, nil, nil, 2],
                [1, nil, nil, 2, nil, nil, 1],
                [nil, 3, 2, 3, 3, 5, 4, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, 4, 1, 2, 1, 2, 1, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1704,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 1, 3, 2, 1, 1, nil],
                [3, nil, nil, nil, nil, nil, 7],
                [7, nil, 3, 4, 4, 2, nil, 1],
                [1, nil, nil, nil, nil, nil, 3],
                [nil, 3, 3, 1, 1, 3, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 5, 1, 2, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, 5, 2, 1, 2, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1705,
            rows: [
                [2, 1, nil, nil, nil, nil, 1, 3],
                [2, 1, nil, nil, nil, 2, 3],
                [3, 1, nil, nil, nil, nil, 3, 3],
                [3, nil, nil, nil, nil, nil, 1],
                [4, 1, nil, nil, nil, nil, 3, 3],
                [1, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 1, 4],
                [2, 1, 1, 2, 4, 4, 2],
                [1, 1, nil, nil, nil, nil, 7, 2],
                [3, 2, 5, 3, 1, 2, 1],
                [nil, 2, 1, 1, 3, 5, 1, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [nil, 5, 1, 3, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1706,
            rows: [
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 2, 3, 3, nil, nil],
                [nil, 1, 2, 5, 2, 1, 3, nil],
                [1, 1, 5, 1, 3, 3, 3],
                [nil, 3, 2, 1, 2, 3, 1, nil],
                [4, 1, 1, 1, 2, 3, 1],
                [nil, 2, 1, 2, 1, 2, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 7, 2, 1, 2, 6, 1, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, 1, 4, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1707,
            rows: [
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 4, nil, 4, nil, 1, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [1, 4, 6, 1, 1, 2, 1, 2],
                [2, nil, 6, nil, 1, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1708,
            rows: [
                [nil, nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 3, 1, 1, nil, nil],
                [nil, 1, 2, 3, 2, nil, nil],
                [nil, 1, 1, 1, 3, 2, 1, nil],
                [nil, 2, 2, 6, 1, 1, nil],
                [nil, 2, 5, 5, 2, 2, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 4, 1, 1, 4, 4, 1, nil],
                [nil, 1, 1, 2, 1, 3, nil],
                [nil, 3, 2, 2, 1, 2, 2, nil],
                [nil, 2, 1, 2, 2, 2, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1709,
            rows: [
                [1, nil, nil, 2, 3, nil, nil, 2],
                [2, nil, 1, 2, 1, nil, 3],
                [nil, 3, nil, 3, 1, nil, 1, nil],
                [nil, 1, 1, 4, 3, 3, nil],
                [nil, 3, nil, 3, 3, nil, 2, nil],
                [nil, 2, 2, 1, 2, 2, nil],
                [nil, nil, nil, 2, 5, nil, nil, nil],
                [nil, nil, 4, 1, 1, nil, nil],
                [nil, nil, nil, 2, 5, nil, nil, nil],
                [nil, nil, 5, 2, 4, nil, nil],
                [1, 1, 5, 1, 1, 1, 3, 1],
                [4, nil, nil, nil, nil, nil, 1],
                [1, 1, 3, 1, 2, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1710,
            rows: [
                [nil, 3, 3, nil, 3, 1, nil, nil],
                [4, nil, 4, 4, nil, 4, nil],
                [2, nil, nil, nil, nil, nil, 2, nil],
                [1, 1, 2, nil, nil, 1, 1],
                [5, nil, nil, nil, nil, nil, 1, nil],
                [2, 2, 1, nil, nil, 4, 2],
                [nil, 1, 1, 3, 1, 2, 3, 1],
                [nil, 1, 4, nil, nil, 1, 4],
                [nil, 1, 2, 1, 2, 1, 3, 1],
                [nil, 5, 1, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1711,
            rows: [
                [nil, 1, nil, 2, nil, 5, nil, 5],
                [1, nil, 3, nil, 5, nil, 1],
                [nil, 1, nil, 2, nil, 1, nil, 1],
                [2, nil, 1, nil, 2, nil, 4],
                [nil, 7, nil, 1, nil, 3, nil, 3],
                [4, nil, 1, nil, 4, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, 2, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1712,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 1],
                [3, 2, nil, nil, nil, 1, 1],
                [nil, 1, 3, nil, nil, 3, 3, nil],
                [nil, 2, 2, nil, 1, 2, nil],
                [nil, 1, 1, 2, 2, 1, 1, nil],
                [nil, 2, 2, 6, 2, 1, nil],
                [nil, 1, 2, 2, 2, 2, 2, nil],
                [nil, 1, 1, 2, 1, 2, nil],
                [nil, 1, 3, 5, 2, 3, 3, nil],
                [nil, 1, 1, 2, 2, 2, nil],
                [nil, 2, 1, 1, 3, 2, 1, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 4, 1, 1, 1, 2, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1713,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 1, 4, 2, nil, nil],
                [nil, nil, 1, 4, 3, 3, nil, nil],
                [nil, 1, 2, 1, 1, 2, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 3, 2, 1, 1, 1, nil],
                [nil, nil, 5, 2, 2, 4, nil, nil],
                [nil, nil, 2, 1, 4, nil, nil],
                [nil, nil, 4, 4, 6, 1, nil, nil],
                [nil, nil, 1, 3, 2, nil, nil],
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1714,
            rows: [
                [nil, 1, nil, 3, nil, 2, nil, 2],
                [2, nil, 1, nil, 1, nil, 6],
                [4, nil, 1, nil, 3, nil, 4, nil],
                [nil, 5, nil, 2, nil, 1, nil],
                [1, nil, 4, nil, 1, nil, 1, nil],
                [nil, 4, nil, 1, nil, 3, nil],
                [nil, 3, nil, 1, nil, 1, nil, nil],
                [1, nil, 4, nil, 4, nil, nil],
                [nil, 4, nil, 5, nil, 5, nil, nil],
                [2, nil, 4, nil, 2, nil, nil],
                [nil, nil, 2, nil, 4, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1715,
            rows: [
                [nil, nil, 4, nil, nil, 3, nil, nil],
                [nil, 3, nil, nil, 3, nil, nil],
                [nil, nil, nil, 2, nil, nil, 1, nil],
                [nil, nil, 2, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, 2, nil, nil, 1],
                [nil, nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, 6, 1, 2, nil, nil],
                [nil, nil, 2, 2, 6, 1, nil, nil],
                [nil, 2, 1, 1, 2, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1716,
            rows: [
                [nil, 1, 2, nil, nil, 3, 3, nil],
                [1, 3, nil, nil, 3, 3, nil],
                [nil, 3, 1, nil, nil, 1, 2, nil],
                [1, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, nil, 4, nil, 2, nil, 2, nil],
                [nil, 6, nil, 2, nil, 2, nil],
                [2, nil, 1, nil, 2, nil, 1, nil],
                [nil, 1, nil, 5, nil, 1, nil],
                [2, nil, 3, nil, 2, nil, 1, nil],
                [nil, 5, nil, 1, nil, 2, nil],
                [2, nil, 1, nil, 3, nil, 1, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [2, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1717,
            rows: [
                [nil, 1, nil, nil, nil, 2, 1, nil],
                [1, nil, 4, nil, 4, nil, 4],
                [4, 3, nil, 2, 1, nil, 1, 2],
                [2, 3, 3, 1, 2, 3, 1],
                [5, 1, nil, 4, 4, nil, 4, 1],
                [3, 1, 1, 1, 1, 2, 1],
                [3, 1, 2, 2, 2, 1, 4, 1],
                [3, nil, 3, 1, 1, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1718,
            rows: [
                [1, 2, nil, nil, nil, nil, 4, 1],
                [2, 2, 3, 1, 4, 4, 1],
                [1, 1, nil, nil, nil, nil, 4, 4],
                [4, 5, 1, 2, 2, 3, 1],
                [2, 5, nil, nil, nil, nil, 5, 5],
                [1, 3, 6, 1, 2, 1, 1],
                [1, 2, nil, nil, nil, nil, 2, 1],
                [5, 1, 3, 2, 1, 1, 1],
                [2, 1, nil, nil, nil, nil, 4, 1],
                [1, 3, 3, 3, 1, 2, 1],
                [2, 1, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1719,
            rows: [
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [1, 7, 3, 2, 1, 2, 1, 3],
                [nil, nil, nil, nil, nil, nil, 3],
                [2, 3, 1, 1, 5, 5, 4, 4],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, 1, 1, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, 2, 3, 4, 3, 4, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [1, 3, 3, 2, 1, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1720,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 2, 2, 4, nil, nil],
                [nil, nil, 4, 1, 6, 1, nil, nil],
                [nil, 1, 3, 2, 3, 3, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, 1, 1, 3, 1, nil],
                [nil, 1, 2, 5, 5, 2, 1, nil],
                [6, 3, 1, 2, 1, 1, 2],
                [nil, 3, 1, 3, 1, 1, 1, nil],
                [1, 3, 3, 1, 3, 2, 2],
                [1, 1, 2, 1, 4, 1, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 1, 1, 2, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
    ]
}
