// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch87 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1721,
            rows: [
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [nil, 4, nil, nil, nil, 1, nil],
                [nil, nil, 4, 1, 3, 3, nil, nil],
                [nil, nil, 1, nil, 5, nil, nil],
                [nil, nil, 1, 3, 1, 3, nil, nil],
                [nil, nil, 5, nil, 6, nil, nil],
                [6, 1, 1, nil, nil, 2, 1, 5],
                [nil, nil, 5, nil, 1, nil, nil],
                [3, 1, 4, nil, nil, 4, 1, 2],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, nil, 1, 3, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1722,
            rows: [
                [6, nil, nil, 6, nil, 1, 1, 1],
                [2, nil, 4, nil, 2, nil, 2],
                [2, nil, nil, 1, nil, nil, nil, 3],
                [3, 1, 3, nil, nil, nil, 1],
                [3, nil, nil, 1, nil, nil, nil, 4],
                [4, 4, 2, nil, nil, nil, 3],
                [nil, nil, nil, 1, nil, 3, 2, nil],
                [nil, nil, 1, nil, 5, nil, nil],
                [nil, nil, nil, 5, nil, 3, 4, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, nil, 1, nil, 2, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1723,
            rows: [
                [3, 3, nil, nil, nil, nil, 3, 5],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, nil, 5, 2, 2, 2, nil, nil],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, nil, 3, 1, 1, 4, nil, nil],
                [nil, 1, nil, nil, nil, 5, nil],
                [nil, nil, nil, 6, 1, nil, nil, nil],
                [nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, 2, 2, nil, nil, nil],
                [1, 3, nil, nil, nil, nil, 1, 5],
                [1, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1724,
            rows: [
                [nil, 4, 3, nil, nil, nil, nil, nil],
                [7, 2, 1, nil, nil, nil, nil],
                [nil, 4, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, 1, 3, nil, nil, nil, nil, nil],
                [nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil, nil],
                [nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 5, 1, nil, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1725,
            rows: [
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, 5, nil, 5, 2, nil, 6],
                [4, 3, nil, 1, 1, nil, 2],
                [nil, 2, 2, 2, 2, 2, 1, nil],
                [1, 1, 2, 1, 1, 3, nil],
                [nil, nil, 1, 1, nil, 3, 1, nil],
                [nil, 1, 2, nil, 3, 1, nil],
                [nil, nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, 4, 1, 2, nil, nil],
                [nil, nil, 6, 1, 1, 4, nil, nil],
                [nil, 1, 1, 2, 3, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1726,
            rows: [
                [nil, nil, 1, 5, 2, 2, nil, nil],
                [nil, 4, 2, 1, 1, 3, nil],
                [nil, 3, 5, 5, 1, 1, 2, nil],
                [nil, 4, 2, 2, 2, 2, nil],
                [nil, 3, 1, 1, 3, 2, 1, nil],
                [nil, 1, 3, 3, 1, 1, nil],
                [nil, nil, 1, 1, 2, 6, nil, nil],
                [nil, nil, 1, nil, 3, nil, nil],
                [nil, nil, 4, 4, 4, 1, nil, nil],
                [nil, nil, 5, nil, 1, nil, nil],
                [nil, nil, 2, 1, 1, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1727,
            rows: [
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, 1, 3, 1, 2, nil, nil],
                [nil, 2, nil, 2, nil, 7, nil],
                [nil, nil, 2, 4, 1, 4, nil, nil],
                [nil, 2, nil, 2, nil, 3, nil],
                [1, nil, nil, 4, 2, nil, nil, 2],
                [4, 1, nil, 4, nil, 4, 3],
                [3, nil, nil, 1, 4, nil, nil, 1],
                [1, 2, nil, 1, nil, 2, 1],
                [nil, 2, 4, 1, 1, 2, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 2, 2, 2, 3, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1728,
            rows: [
                [nil, nil, 1, 3, nil, nil, nil, nil],
                [nil, 3, 1, 2, nil, nil, nil],
                [nil, 3, 1, 1, 7, 5, nil, nil],
                [1, 3, 1, 4, 4, 1, 3],
                [nil, 2, 2, 1, 3, 1, nil, nil],
                [1, 4, 4, 1, 1, 1, 2],
                [1, 5, 5, 1, 3, 1, 3, 3],
                [1, 1, 3, 3, 3, 1, 1],
                [3, 1, 2, 1, 1, 1, 1, 4],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1729,
            rows: [
                [nil, nil, nil, 5, 3, 3, 3, nil],
                [1, 3, 1, nil, nil, nil, 5],
                [3, nil, nil, nil, nil, nil, nil, 4],
                [3, nil, nil, nil, nil, nil, 2],
                [4, nil, nil, nil, nil, nil, nil, 1],
                [3, nil, nil, nil, nil, nil, 2],
                [1, nil, nil, nil, 2, 2, 3, 5],
                [1, nil, nil, 2, 1, 2, 4],
                [1, nil, nil, nil, 2, 1, 1, 5],
                [2, nil, nil, 3, 2, 4, 1],
                [1, nil, nil, nil, 1, 1, 2, 1],
                [1, 1, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, 6, 2, 2, 1],
                [2, 1, nil, nil, nil, nil, nil],
                [1, 3, 2, nil, nil, nil, nil, nil],
                [1, 2, 2, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1730,
            rows: [
                [1, 2, 1, 5, 5, 5, 5, 2],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [1, 3, 3, 2, 2, 1, 3, 2],
                [nil, nil, nil, nil, 2, nil, nil],
                [2, 1, 4, 1, 1, 1, 3, 1],
                [nil, nil, nil, nil, 4, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [1, 3, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1731,
            rows: [
                [4, nil, nil, nil, 1, nil, nil, nil],
                [4, nil, nil, nil, 3, nil, nil],
                [nil, 2, nil, nil, 3, 3, nil, nil],
                [nil, 3, nil, 2, nil, 5, nil],
                [nil, 1, nil, nil, 1, 4, nil, nil],
                [nil, 5, nil, 1, nil, 1, nil],
                [nil, 4, nil, nil, 5, 2, nil, nil],
                [2, nil, nil, 1, 1, 2, nil],
                [nil, 2, nil, nil, 4, 4, nil, nil],
                [4, nil, nil, 1, 2, 1, nil],
                [1, nil, nil, nil, 1, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1732,
            rows: [
                [nil, 1, nil, nil, nil, nil, 4, nil],
                [4, nil, nil, 4, nil, nil, 4],
                [4, 4, 1, 2, 2, 2, 2, 1],
                [2, nil, nil, 4, nil, nil, 1],
                [4, 4, 4, 5, 5, 2, 1, 6],
                [1, nil, nil, 3, nil, nil, 1],
                [nil, 2, nil, 2, nil, nil, 1, nil],
                [nil, nil, 3, 3, nil, nil, nil],
                [nil, 3, nil, 1, nil, nil, 1, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1733,
            rows: [
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, 5, nil],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 3, 2, 2, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, 4, 1, 1, 5, 5, 4, nil],
                [nil, 1, 1, 7, 1, 5, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1734,
            rows: [
                [nil, nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [1, 3, 3, 1, 4, 4, 2, 2],
                [nil, nil, nil, nil, 3, nil, nil],
                [3, 1, 2, 4, 5, 1, 1, 1],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, nil, 4, nil, nil],
                [nil, nil, nil, 3, 4, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1735,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 2, nil, 1, 1, nil, nil],
                [2, 1, nil, 3, 1, nil, nil],
                [nil, 1, 5, nil, 5, 1, nil, nil],
                [2, 2, nil, 1, 1, nil, nil],
                [nil, 4, 4, nil, 3, 1, nil, nil],
                [3, 3, nil, 1, 4, nil, nil],
                [nil, 3, 2, nil, 1, 1, nil, nil],
                [2, 1, nil, 2, 5, nil, nil],
                [nil, 1, 2, nil, 4, 2, nil, nil],
                [1, 3, nil, 1, 3, nil, nil],
                [nil, 1, 2, nil, 3, 1, nil, nil],
                [1, 1, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1736,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 5],
                [5, 5, 5, 7, 2, 1, 3],
                [3, nil, nil, nil, nil, nil, nil, 2],
                [2, 1, 2, 1, 1, 3, 3],
                [1, nil, nil, nil, nil, nil, nil, 3],
                [1, 1, 1, 1, 6, 1, 2],
                [nil, nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1737,
            rows: [
                [2, 1, 2, 2, 3, 4, 1, 3],
                [6, nil, nil, 1, nil, nil, 2],
                [2, 3, 2, 1, 2, 3, 2, 1],
                [3, nil, nil, 2, nil, nil, 2],
                [2, 1, 2, 2, 1, 2, 2, 2],
                [1, nil, nil, 2, nil, nil, 1],
                [nil, 1, nil, nil, 1, nil, nil, 3],
                [3, 3, 3, 4, 3, 1, 3],
                [nil, 2, nil, nil, 4, nil, nil, 3],
                [2, 1, 1, 1, 2, 6, 3],
                [nil, 1, nil, nil, 3, nil, nil, 3],
                [2, nil, nil, 2, nil, nil, 3],
                [nil, 1, nil, nil, 3, nil, nil, 1],
                [1, nil, nil, 3, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1738,
            rows: [
                [nil, nil, 2, 1, 2, nil, nil, nil],
                [nil, nil, 1, 1, 4, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, nil, 1, nil, 2, nil, 3, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [4, nil, 4, nil, 4, nil, 2, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [3, nil, 3, nil, 1, nil, 2, nil],
                [nil, 2, nil, 1, nil, 2, nil],
                [4, nil, 4, nil, 4, nil, 4, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [2, nil, 2, nil, 4, nil, 1, nil],
                [nil, 2, nil, 1, nil, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1739,
            rows: [
                [nil, 1, 4, 1, 1, 5, 1, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 5, nil, nil, nil, nil, 1, nil],
                [5, 2, 1, 2, 1, 3, 1],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [2, 1, 2, 3, 3, 3, 4],
                [nil, 4, 1, 1, 4, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 1, 2, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1740,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 1],
                [2, 2, 2, 1, 3, 3, 5],
                [1, nil, nil, nil, nil, nil, nil, 3],
                [3, 1, 2, 3, 1, 4, 1],
                [5, nil, nil, nil, nil, nil, nil, 5],
                [5, 3, 1, 1, 1, 3, 3],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [2, 1, 2, 4, 1, 2, 1],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
    ]
}
