// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch14 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 261,
            rows: [
                [2, nil, nil, 2, nil, 2, nil, 2],
                [2, 2, 2, nil, nil, 2, 2],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, 3, 3, 3, 3, 4],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 1, 2, 2, 2, 1],
                [nil, nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, 1, 1, 3, 1, 1],
                [nil, nil, 5, 5, 5, 5, 5, 5],
                [nil, nil, 3, 3, 3, 3, 3],
                [nil, nil, nil, 1, 1, nil, 1, 1],
                [nil, nil, nil, 1, nil, 1, 1],
                [nil, nil, nil, 4, 4, nil, 4, 6],
                [nil, nil, nil, 1, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 262,
            rows: [
                [1, nil, nil, nil, 1, 1, 1, nil],
                [1, nil, 1, nil, nil, 1, nil],
                [1, nil, 1, 4, nil, nil, nil, 4],
                [4, nil, 4, nil, nil, 4, 1],
                [1, 1, nil, 1, 1, nil, nil, 1],
                [1, 1, 1, nil, nil, 6, nil],
                [6, 6, nil, 2, nil, 2, 2, nil],
                [nil, 2, 2, nil, nil, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil, 2],
                [nil, nil, 2, 2, 2, nil, nil],
                [2, 2, nil, nil, 2, 3, 3, nil],
                [nil, nil, 3, 3, nil, 3, nil],
                [3, 3, nil, 3, 3, nil, 3, nil],
                [nil, nil, nil, nil, 1, nil, 1],
                [1, 1, nil, 5, 5, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 263,
            rows: [
                [1, nil, nil, 1, 1, 1, 1, 1],
                [1, nil, 1, 1, nil, 1, nil],
                [1, 1, nil, 1, nil, 1, 1, 2],
                [nil, nil, 2, 2, nil, 2, 2],
                [4, nil, nil, nil, nil, 4, nil, nil],
                [4, nil, nil, nil, 4, 3, 2],
                [2, nil, 2, nil, 2, nil, nil, nil],
                [2, 1, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, nil, nil, 1],
                [nil, nil, 1, 1, 5, nil, nil, 2],
                [2, nil, nil, 2, 2, 3, nil],
                [3, 3, 3, 3, nil, 3, nil, nil],
                [nil, 3, nil, nil, nil, nil, 6],
                [6, 6, 6, 5, 4, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 264,
            rows: [
                [nil, 5, nil, nil, nil, nil, 5, nil],
                [nil, 5, nil, nil, nil, 1, nil],
                [nil, nil, 1, 1, 3, 3, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [2, 2, 1, nil, nil, 1, 1, 1],
                [nil, nil, 1, nil, 1, nil, nil],
                [1, 1, 1, nil, nil, 1, 1, 2],
                [nil, nil, 7, nil, 7, nil, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, nil, 2, 2, 4, 4, nil, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 265,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 3, 3, nil, 3, nil],
                [nil, nil, nil, nil, 4, nil, nil, 4],
                [4, 4, 4, nil, nil, 4, 1],
                [1, 1, 1, 1, 1, nil, 5, 5],
                [nil, nil, nil, 5, 5, 2, 2],
                [nil, nil, 2, nil, 2, nil, 1, 1],
                [nil, 1, nil, nil, 1, 1, 1],
                [1, 1, 1, nil, 1, nil, nil, 1],
                [nil, 1, nil, nil, 1, 1, 2],
                [2, 2, 2, nil, nil, 2, nil, 2],
                [nil, 2, 2, nil, 2, 2, nil],
                [3, 3, nil, nil, nil, nil, nil, nil],
                [3, nil, 3, 2, nil, 5, nil],
                [5, 6, 2, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 266,
            rows: [
                [nil, nil, nil, nil, nil, nil, 4, 1],
                [nil, nil, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, 1, nil, nil, nil, 5, nil],
                [nil, nil, nil, nil, nil, nil, 2, 2],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [1, 1, 2, nil, 2, nil, nil],
                [nil, 2, 2, nil, nil, 2, nil, nil],
                [4, 4, 4, nil, 4, nil, nil],
                [4, nil, 4, 4, 4, 4, nil, 5],
                [nil, 5, nil, 5, nil, 5, 5],
                [3, nil, 3, 3, 3, 2, nil, 2],
                [nil, 6, nil, 2, nil, 2, 2],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 267,
            rows: [
                [nil, nil, 1, 6, nil, 6, nil, nil],
                [nil, nil, 6, 2, 2, nil, nil],
                [nil, 3, 3, nil, nil, nil, 3, nil],
                [nil, nil, 3, 3, nil, 3, 3],
                [nil, nil, nil, 3, nil, nil, 2, nil],
                [2, 2, nil, nil, 2, 2, nil],
                [1, nil, nil, 1, 1, 1, 1, nil],
                [2, 2, 2, nil, 2, 2, 2],
                [nil, 2, 2, nil, 2, nil, 1, nil],
                [nil, 1, 1, 1, 1, 5, nil],
                [nil, 5, 5, 5, nil, nil, nil, 3],
                [nil, nil, 1, 1, 1, nil, 1],
                [nil, nil, nil, 1, 4, 4, nil, nil],
                [nil, nil, 4, 4, 4, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 268,
            rows: [
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 4, 4, 4, nil, nil],
                [nil, nil, 4, 1, 6, nil, nil],
                [nil, nil, 6, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 1, 6, 6, 6, nil, nil],
                [nil, nil, 6, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 5, 7, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 269,
            rows: [
                [nil, nil, 4, 3, nil, nil, nil, nil],
                [nil, 3, 3, 3, nil, nil, nil],
                [nil, 3, 3, 1, 7, 2, nil, nil],
                [2, 2, 2, 2, 5, 5, 5],
                [nil, 5, 5, 2, 2, 2, nil, nil],
                [2, 4, 4, 4, 6, 2, 2],
                [2, 2, 1, 1, 1, 6, 1, 1],
                [1, 1, 1, 2, 3, 3, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 270,
            rows: [
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 3, 3, 3],
                [3, 3, 3, 3, 7, 7, 4, 4],
                [2, 2, 2, 2, 2, 2, 2],
                [2, 1, 1, 1, 4, 4, 4, 4],
                [4, 1, 1, 1, 6, 6, 5],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 271,
            rows: [
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 5, 5, 5, 5, nil, nil],
                [nil, nil, 5, 5, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 7, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 4, 1, 1, 6, nil, nil],
                [nil, nil, 6, 3, 3, nil, nil],
                [nil, nil, 3, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 272,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, 2, 2, 2, 2, 2, 1, nil],
                [1, 3, 3, 3, 3, 3, 3],
                [nil, 3, 2, 2, 2, 2, 2, nil],
                [2, 2, 2, 2, 2, 2, 1],
                [nil, 1, 1, 1, 1, 5, 5, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, 5, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, 7, 4, 4, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 273,
            rows: [
                [2, 2, 2, 2, 2, 2, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, 4, 4, 1, 1, 1],
                [1, nil, nil, nil, 1, 1, 1],
                [1, nil, nil, 1, 1, 1, 5, 5],
                [3, nil, nil, nil, 3, 3, 3],
                [3, nil, nil, nil, nil, nil, 4, 4],
                [4, 4, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, 4, 4],
                [4, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, 6, nil, nil, nil, nil],
                [5, 5, 5, 5, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 5, 2, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 274,
            rows: [
                [nil, nil, 2, 2, nil, nil, nil, nil],
                [nil, 2, 3, 3, nil, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [2, 5, 5, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [3, 3, 3, 3, 3, 3, 3, 3],
                [4, 4, 4, 4, 7, 2, 2],
                [2, 2, 2, 2, 2, 1, 1, 1],
                [2, 2, 1, 1, 6, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 275,
            rows: [
                [4, 4, nil, nil, nil, nil, nil, nil],
                [4, 4, nil, nil, nil, nil, nil],
                [1, 1, 3, nil, nil, nil, nil, nil],
                [3, 3, 3, nil, nil, nil, nil],
                [3, 3, 3, nil, nil, nil, nil, nil],
                [3, 3, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 2, 1, 1, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [1, 1, 2, 2, 2, nil, nil, nil],
                [2, 2, 2, 2, 2, nil, nil],
                [2, 2, 6, 6, 5, nil, nil, nil],
                [5, 5, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, 5, 7, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 276,
            rows: [
                [1, 1, 4, 1, 1, 1, 3, 3],
                [3, 1, 1, 1, 1, 1, 1],
                [2, 2, 6, 6, 2, 1, 1, 1],
                [2, 2, 2, 2, 2, 2, 2],
                [2, 5, 5, 2, 2, 2, 2, 3],
                [3, 3, 1, 4, 4, 4, 7],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 277,
            rows: [
                [4, 4, 4, nil, nil, 1, 3, 3],
                [nil, nil, 3, nil, 3, nil, nil],
                [nil, nil, 1, 2, 2, 2, nil, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, nil, 5, 5, 7, 1, nil, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [nil, nil, 3, 3, 3, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 4, 4, nil, nil],
                [nil, 2, 2, nil, nil, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, 6, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 278,
            rows: [
                [nil, nil, 1, 1, 3, 7, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 7, 7, nil, 1, 3, nil, 3],
                [3, 1, nil, 1, 1, nil, 1],
                [nil, 1, 3, 3, 3, 4, 1, nil],
                [1, 3, 3, 3, 1, 2, nil],
                [nil, nil, 2, 2, nil, 2, 2, nil],
                [nil, 2, 2, nil, 2, 2, nil],
                [nil, nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 1, 5, 1, nil, nil],
                [nil, nil, 4, 4, 4, 5, nil, nil],
                [nil, 5, 1, 1, 1, nil, nil],
                [nil, nil, nil, 6, 1, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 4
        ),
        LevelTemplate(
            levelNumber: 279,
            rows: [
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, 4, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 4, 4, 5, 5, nil, nil],
                [nil, nil, 5, 1, 2, nil, nil],
                [nil, nil, 7, 1, 1, 1, nil, nil],
                [nil, nil, 1, 6, 1, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 280,
            rows: [
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 4, 4, 4, nil, nil],
                [nil, 4, 4, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 5, 5, 5, 1, 1, nil],
                [nil, 1, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 3, 3, nil],
                [nil, 2, 2, 1, 3, 3, 1, nil],
                [nil, 1, 4, 4, 4, 4, nil],
                [nil, 4, 4, 6, 6, 3, 1, nil],
                [nil, 1, 1, 1, 1, 4, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
    ]
}
