// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch24 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 461,
            rows: [
                [nil, 1, 2, nil, nil, 2, 2, nil],
                [2, 2, nil, nil, 2, 2, nil],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [2, 2, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, nil, 2, nil, 2, nil, 4, nil],
                [nil, 5, nil, 5, nil, 5, nil],
                [5, nil, 3, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [4, nil, 4, nil, 4, nil, 4, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [7, nil, 7, nil, 4, nil, 1, nil],
                [nil, 1, nil, 1, nil, 3, nil],
                [3, nil, 3, nil, 1, nil, 1, nil],
                [nil, 3, nil, 3, nil, 6, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 462,
            rows: [
                [1, 1, 1, nil, nil, 1, 1, 1],
                [nil, nil, 1, nil, 3, nil, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 6, 4, 4, nil, nil],
                [nil, nil, 4, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, 5, nil, nil, 5, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 7, 5, nil, nil, 5, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 463,
            rows: [
                [nil, nil, 1, 1, 4, nil, nil, nil],
                [nil, 4, 4, 4, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, 1, 2, nil],
                [nil, 2, 2, 2, 7, 5, nil, nil],
                [2, 2, 2, 2, 2, 2, nil],
                [nil, nil, 2, nil, 3, nil, nil, nil],
                [nil, 3, nil, nil, 3, nil, nil],
                [nil, nil, 3, nil, 3, nil, nil, nil],
                [nil, 3, nil, nil, 6, nil, nil],
                [nil, 6, 5, 1, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, 5, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 464,
            rows: [
                [2, nil, 2, nil, nil, 2, nil, 2],
                [5, nil, 5, nil, 5, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [4, nil, 3, 3, 3, nil, 3],
                [3, nil, nil, 3, 3, nil, nil, 3],
                [2, nil, 2, 2, 2, nil, 2],
                [2, nil, nil, 4, 4, nil, nil, 4],
                [4, nil, 4, nil, 4, nil, 7],
                [7, nil, nil, 2, 2, nil, nil, 2],
                [2, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, 2, nil, nil, 2, nil, 2],
                [2, nil, nil, nil, nil, nil, 6],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 465,
            rows: [
                [nil, nil, nil, 5, 5, 1, 2, nil],
                [2, 2, 2, nil, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, 2, 1, 1, 1],
                [1, nil, nil, 1, 1, 1, 1],
                [1, nil, nil, nil, 1, 1, 1, 1],
                [1, nil, nil, 1, 1, 1, 1],
                [1, nil, nil, nil, 1, 3, 4, 2],
                [2, 2, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, 2, 3, 3, 3],
                [3, 3, nil, nil, nil, nil, nil],
                [3, 3, 3, nil, nil, nil, nil, nil],
                [7, 7, 1, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 466,
            rows: [
                [4, nil, nil, nil, nil, nil, nil, 4],
                [4, 4, 4, 1, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 2, 2, 5],
                [5, nil, nil, nil, nil, nil, nil, 5],
                [5, 5, 2, 2, 3, 3, 3],
                [3, nil, nil, nil, nil, nil, nil, 2],
                [2, 2, 2, 5, 7, 6, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 467,
            rows: [
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, nil, 3, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [3, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [3, 3, 3, 3, 3, 3, 3],
                [3, 3, nil, nil, nil, nil, 4, 4],
                [4, 4, 4, 4, 4, 2, 1],
                [nil, 1, 1, 1, 2, 5, 5, nil],
                [nil, 7, nil, 2, nil, 2, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 468,
            rows: [
                [nil, 2, 2, nil, 2, 2, 2, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 2, 2, 2, nil, 2, 2, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 1, 1, 6, nil, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 7, 7, nil, 1, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 1, 4, nil, 3, 3, 3, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, 1, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, 5, 4, nil, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 469,
            rows: [
                [1, 1, 1, 1, 1, 3, 3, 3],
                [3, 3, 2, 2, 2, 2, 2],
                [2, 2, 2, 3, 3, 3, 3, 3],
                [3, 3, 3, 6, 1, 1, 6],
                [6, 6, 7, 1, 1, 1, 1, 1],
                [1, 1, 1, 5, 1, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 470,
            rows: [
                [nil, nil, nil, nil, nil, nil, 4, 3],
                [nil, nil, 3, 3, 3, 3, 2],
                [nil, nil, nil, nil, nil, nil, 2, 2],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2, 2],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 5, 5, nil, nil, 4, nil, nil],
                [4, 5, 1, nil, 1, nil, nil],
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [1, 1, 3, nil, 1, nil, nil],
                [1, nil, 1, 1, 1, 1, nil, 1],
                [nil, 6, nil, 6, nil, 6, 4],
                [4, nil, 4, 4, 1, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, 1],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 471,
            rows: [
                [nil, 2, 2, nil, nil, 2, 1, nil],
                [1, 1, 2, 2, 2, 2, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 3, 3, 3],
                [3, 3, 2, 2, 2, 2, 2, 2],
                [2, 4, 4, 4, 5, 2, 1],
                [nil, 1, 1, nil, nil, 7, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 3, nil, nil, 7, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 472,
            rows: [
                [2, nil, 3, 3, 2, 2, nil, 2],
                [4, nil, nil, nil, nil, nil, 4],
                [4, 4, 4, 4, 2, 2, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, 2, 2, 5, nil, nil],
                [nil, nil, 5, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 7, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, nil, 6, nil, 6],
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 473,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, nil, 2, 2, nil, nil],
                [2, 2, nil, 2, 2, nil, nil],
                [nil, 1, 1, nil, 5, 5, nil, nil],
                [1, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [1, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [4, 4, nil, 4, 4, nil, nil],
                [nil, 4, 4, nil, 1, 3, nil, nil],
                [3, 5, nil, 5, 4, nil, nil],
                [nil, 4, 6, nil, 6, 3, nil, nil],
                [3, 7, nil, 7, 7, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 4
        ),
        LevelTemplate(
            levelNumber: 474,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, 4, nil, nil, nil, nil],
                [nil, nil, 4, 4, nil, nil, nil, nil],
                [nil, 4, 3, 3, nil, nil, nil],
                [nil, nil, 3, 3, nil, nil, nil, nil],
                [nil, 3, 3, 3, nil, nil, nil],
                [3, 3, 2, 2, 2, 2, 2, nil],
                [2, 2, 2, 2, 2, 2, nil],
                [2, 1, 1, 1, 1, 4, 4, nil],
                [4, 1, 1, 1, 1, 1, nil],
                [7, 2, 2, 2, 2, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 5, 1, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 475,
            rows: [
                [nil, 7, nil, nil, nil, nil, 7, nil],
                [1, nil, nil, 1, nil, nil, 1],
                [1, 1, 1, 4, 4, 4, 4, 4],
                [4, nil, nil, 2, nil, nil, 2],
                [2, 2, 2, 2, 2, 1, 2, 2],
                [2, nil, nil, 2, nil, nil, 3],
                [nil, 3, nil, 3, nil, nil, 3, nil],
                [nil, nil, 3, 6, nil, nil, nil],
                [nil, 6, nil, 1, nil, nil, 1, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, 3, 5, nil, nil, nil, nil],
                [nil, 5, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 476,
            rows: [
                [4, 6, 1, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [3, nil, nil, 3, 3, 3, 3, 3],
                [3, nil, nil, nil, 1, 1, 1],
                [1, nil, nil, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, 1, 1],
                [4, 5, nil, nil, nil, nil, nil],
                [5, nil, nil, nil, nil, nil, 7, 7],
                [4, 4, nil, nil, nil, nil, nil],
                [4, 4, 2, 2, nil, nil, nil, nil],
                [2, 2, 2, 2, nil, nil, nil],
                [2, 2, 2, 2, nil, nil, nil, nil],
                [2, 2, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 477,
            rows: [
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, 1, 3, nil, nil, nil],
                [nil, 3, 1, 1, 1, 1, nil, nil],
                [2, 2, 2, 2, 2, 2, 2],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [2, 2, 1, 1, 1, 3, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 4, 1, 1, 1, 5],
                [5, 4, 4, 4, 4, 3, 3, 3],
                [3, 7, 6, 4, 4, 4, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 478,
            rows: [
                [1, nil, 1, nil, 4, nil, 4, nil],
                [nil, 4, nil, 4, nil, 4, nil],
                [4, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 3, nil, 3, nil],
                [3, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 5, nil],
                [nil, 5, nil, 5, nil, 5, nil],
                [5, nil, 3, nil, 3, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 6, 6, 6, 6, 2, 2, 2],
                [2, 2, 2, 1, 1, 1, 5],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 479,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [3, 1, nil, nil, 1, 1, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, 1, 1, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, 6, 6, nil],
                [nil, 4, 5, nil, nil, 5, 5, nil],
                [5, 5, nil, nil, 6, 7, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 480,
            rows: [
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [2, 2, nil, nil, 2, 2, nil],
                [nil, 2, 1, nil, nil, 1, 4, nil],
                [4, 4, nil, nil, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 6, nil, 6, nil],
                [3, nil, 3, nil, 3, nil, 3, nil],
                [nil, 5, nil, 5, nil, 5, nil],
                [5, nil, 3, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 3, nil, 1, nil, 1, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [3, nil, 3, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 7, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
    ]
}
