// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch96 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1901,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, 4],
                [1, nil, nil, 1, nil, nil, nil],
                [nil, 1, 2, 1, 1, nil, 5, nil],
                [nil, nil, nil, nil, 1, 2, 2],
                [nil, nil, 2, 1, 2, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, 3],
                [1, 2, 1, nil, nil, 1, 2, 1],
                [3, 1, 1, nil, 1, 2, 1],
                [3, 4, 2, nil, nil, 1, 1, 1],
                [3, 1, 1, nil, 4, 1, 5],
                [1, 1, 1, 2, 1, 1, 6, 1],
                [1, 3, 2, 2, 2, 1, 1],
                [6, 1, 2, 1, 3, 2, 1, 1],
                [1, 1, 1, 2, 1, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1902,
            rows: [
                [2, nil, 1, 3, 2, 2, 2, nil],
                [2, 1, nil, 5, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, 1, 4, 2, 1],
                [3, 1, nil, 1, 2, nil, 1, 2],
                [1, 1, 5, nil, 3, nil, nil],
                [1, 3, nil, nil, nil, 1, 3, nil],
                [3, 3, 1, nil, 2, nil, nil],
                [nil, nil, 2, nil, nil, nil, 4, 2],
                [nil, 4, nil, nil, 4, 2, nil],
                [nil, nil, 2, 1, 1, nil, 2, 6],
                [nil, 2, 1, 3, 3, nil, nil],
                [1, 2, nil, 2, 1, nil, nil, nil],
                [2, 1, nil, 2, 1, 1, 1],
                [nil, 2, 5, nil, nil, nil, 1, nil],
                [4, nil, 1, nil, 2, 1, 1],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1903,
            rows: [
                [nil, 3, 1, nil, 2, 2, 3, nil],
                [2, nil, 2, nil, 2, 1, 1],
                [2, nil, 2, 1, nil, 3, nil, 1],
                [1, 2, 1, 2, 1, 3, nil],
                [1, 1, 4, 4, nil, nil, nil, 1],
                [nil, nil, 3, nil, nil, 1, nil],
                [2, 2, 1, nil, nil, 3, nil, 1],
                [nil, 1, 4, nil, 3, nil, 2],
                [nil, nil, 2, nil, 2, nil, 2, 2],
                [nil, nil, 2, 1, 1, 3, 1],
                [3, nil, 1, 5, nil, 1, nil, nil],
                [1, 3, 1, 3, 1, 1, 1],
                [3, 1, 6, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1904,
            rows: [
                [2, 1, nil, nil, nil, nil, nil, 1],
                [2, 1, nil, 2, 2, nil, nil],
                [nil, nil, nil, 2, 1, nil, 1, 4],
                [4, nil, 1, nil, 1, nil, 4],
                [4, 4, 1, 2, 4, 2, 1, 4],
                [1, 2, 1, 1, 2, 1, 3],
                [1, 3, 3, 1, 1, 2, 2, 6],
                [1, 4, 4, 4, 1, 2, 5],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 2, 1, nil, 2, 1, nil, nil],
                [nil, 2, 1, 3, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1905,
            rows: [
                [nil, 1, 1, nil, 1, nil, nil, nil],
                [4, 2, 3, nil, 1, nil, 2],
                [6, 2, 2, nil, nil, nil, nil, 2],
                [1, 1, nil, 1, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, 1, 3],
                [1, nil, nil, nil, nil, 4, 1, nil],
                [5, 1, 2, 3, 1, 2, 2],
                [1, 3, 1, nil, 1, 3, 1, 1],
                [2, 2, 2, 1, 1, 4, 3],
                [3, 1, 5, 1, nil, 4, 1, 2],
                [2, 1, 3, 1, 1, 1, 1],
                [1, 1, 1, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1906,
            rows: [
                [nil, 1, 4, 1, nil, 1, 2, nil],
                [nil, nil, nil, 2, 2, 1, nil],
                [nil, 1, 1, 2, 2, nil, 1, nil],
                [nil, 2, 1, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, 1, nil],
                [nil, 5, 1, 3, nil, 3, nil],
                [nil, 3, nil, 1, nil, 1, 1, nil],
                [nil, nil, 2, 1, nil, 2, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 5, 5, 1, 4, 6, nil],
                [nil, 4, 1, 4, 1, 3, 1, nil],
                [nil, 2, 4, 1, 4, 4, nil],
                [nil, 1, 2, 1, 2, 2, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1907,
            rows: [
                [nil, nil, nil, 6, 1, 1, 1, nil],
                [6, 3, 1, nil, nil, nil, 3],
                [2, nil, nil, nil, nil, nil, nil, 5],
                [3, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [2, nil, nil, nil, nil, nil, 2],
                [1, nil, nil, nil, 5, 5, 2, 1],
                [1, nil, nil, 1, 2, 2, 3],
                [3, nil, nil, nil, 1, 4, 2, 1],
                [3, nil, nil, 1, 1, 1, 3],
                [4, nil, nil, nil, 4, 1, 3, 4],
                [1, 4, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 3, 3, 2, 1],
                [3, 3, nil, nil, nil, nil, nil],
                [1, 1, 2, nil, nil, nil, nil, nil],
                [2, 3, 1, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1908,
            rows: [
                [1, 4, 4, 1, nil, nil, 3, 1],
                [3, 3, 1, nil, 3, nil, nil],
                [2, 4, 1, nil, 1, nil, 2, 2],
                [nil, nil, nil, nil, 1, 4, nil],
                [4, nil, 1, nil, 3, nil, 2, 2],
                [1, 1, nil, nil, 2, nil, nil],
                [1, 2, 1, nil, 1, 2, nil, nil],
                [1, 2, 6, nil, 2, 1, 3],
                [1, 1, 2, nil, 1, 1, 2, 1],
                [3, 3, 3, nil, 3, 6, 2],
                [4, 1, 2, 1, 1, 1, 3, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 1, 4, 2, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1909,
            rows: [
                [2, 3, 2, 1, 3, 1, 2, 1],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 6, nil, nil, nil, nil],
                [nil, nil, nil, 6, 1, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [3, 2, 1, 2, 3, 2, 2, 2],
                [nil, nil, nil, nil, 1, nil, nil],
                [2, 4, 4, 3, 1, 2, 1, 4],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [1, 1, 2, 1, 5, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1910,
            rows: [
                [4, nil, nil, nil, 4, nil, nil, nil],
                [3, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, 2, 2, nil, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [nil, 5, nil, nil, 1, 3, nil, nil],
                [nil, 3, nil, 7, nil, 1, nil],
                [nil, 7, nil, nil, 1, 2, nil, nil],
                [2, nil, nil, 1, 1, 4, nil],
                [nil, 1, nil, nil, 3, 3, nil, nil],
                [1, nil, nil, 4, 1, 5, nil],
                [1, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1911,
            rows: [
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [6, nil, nil, 6, nil, nil, 1],
                [1, 4, 4, 1, 4, 1, 2, 2],
                [2, nil, nil, 4, nil, nil, 4],
                [1, 2, 2, 1, 3, 3, 3, 3],
                [1, nil, nil, 5, nil, nil, 1],
                [nil, 5, nil, 5, nil, nil, 1, nil],
                [nil, nil, 1, 3, nil, nil, nil],
                [nil, 1, nil, 5, nil, nil, 1, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1912,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 4, 4, nil, nil],
                [nil, nil, 4, 4, 1, 1, nil, nil],
                [nil, 3, 2, 1, 4, 1, nil],
                [nil, nil, 3, 3, 3, 4, nil, nil],
                [nil, 4, 1, 2, 1, 1, nil],
                [nil, 5, 2, 2, 2, 1, 1, nil],
                [3, 1, 2, 1, 2, 5, 1],
                [nil, 1, 2, 2, 3, 2, 1, nil],
                [1, 1, 1, 6, 1, 2, 1],
                [3, 1, 1, 1, 3, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1913,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, 5, nil, nil, nil, nil],
                [nil, 5, nil, nil, nil, nil, nil, nil],
                [5, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, 1, 4, 1, 1, nil, nil],
                [nil, 3, 3, 1, 4, 1, 1, nil],
                [nil, 4, 1, 7, 1, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1914,
            rows: [
                [nil, 1, nil, nil, nil, nil, 3, 3],
                [1, nil, nil, 1, 2, 1, 1],
                [2, 3, nil, 2, nil, 2, nil, nil],
                [nil, 1, 1, 2, 3, nil, 1],
                [2, 1, 2, nil, nil, nil, nil, 1],
                [2, nil, 4, 6, nil, 3, 1],
                [nil, 1, 1, 2, 1, 1, 4, nil],
                [1, 3, nil, nil, nil, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, 4],
                [3, 2, 1, nil, 2, 1, nil],
                [3, 3, nil, nil, 4, 1, nil, 1],
                [nil, nil, 3, 1, 1, nil, 3],
                [nil, 4, 1, nil, 2, nil, 2, 1],
                [nil, 3, 1, 1, 1, 4, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1915,
            rows: [
                [nil, nil, 3, nil, nil, 4, 1, nil],
                [nil, 3, nil, nil, nil, nil, nil],
                [nil, nil, 4, nil, 4, 4, nil, nil],
                [3, 3, 3, 2, nil, 2, nil],
                [1, nil, nil, 4, 4, nil, 1, nil],
                [nil, 2, 2, 2, nil, 2, nil],
                [nil, nil, 2, 1, 2, nil, nil, 1],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 4, 3, 1, 3, 3, 1],
                [1, 2, nil, 5, 6, 1, 3],
                [2, 1, nil, 2, 2, 2, 2, 5],
                [1, 3, nil, 1, nil, 1, nil],
                [nil, 5, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, 1, 1, 1],
                [nil, nil, 2, nil, nil, 4, nil, nil],
                [nil, 1, 4, 1, 1, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1916,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, 3],
                [nil, nil, 1, nil, nil, nil, 2],
                [nil, 2, nil, 1, 2, 2, nil, nil],
                [nil, 3, nil, nil, 3, 3, nil],
                [nil, 4, nil, nil, nil, 1, 1, nil],
                [3, 1, nil, nil, nil, 3, 2],
                [1, nil, nil, nil, nil, nil, 4, nil],
                [1, 1, 1, nil, nil, 2, 1],
                [1, 2, nil, nil, nil, 1, 1, 1],
                [1, 1, 4, nil, 4, 4, 4],
                [3, 1, 2, 2, 2, 1, 1, 1],
                [3, 2, 1, 6, 4, 4, 2],
                [2, 1, 3, 1, 1, 1, 1, 1],
                [1, 3, 3, 3, 3, 6, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1917,
            rows: [
                [2, nil, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 4, 2, 4, 4, nil],
                [3, nil, 2, nil, 1, 1, 1],
                [nil, nil, nil, 3, nil, 1, 2, nil],
                [nil, nil, nil, nil, 1, 3, 1],
                [nil, nil, 5, nil, nil, 3, 3, 1],
                [nil, nil, 2, nil, 1, 2, 2],
                [nil, 2, 2, nil, nil, 1, 1, 5],
                [5, 5, 1, nil, 2, 1, 1],
                [2, 2, 3, 1, 2, 2, 2, 2],
                [1, 3, 3, 3, 3, 1, 1],
                [1, 2, 1, 2, 4, 1, 4, 1],
                [2, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1918,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 4, 4, 2, nil, nil],
                [nil, nil, nil, 2, 1, 4, nil, nil],
                [nil, 2, 1, nil, 4, 3, nil],
                [nil, nil, 1, 3, 3, 2, nil, nil],
                [nil, 1, 1, 1, 5, 4, nil],
                [nil, 4, 1, 1, 1, 6, 6, nil],
                [1, 2, 2, 1, 5, 1, 2],
                [nil, 1, 4, 1, 2, 2, 1, nil],
                [1, 3, 1, 2, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1919,
            rows: [
                [nil, 6, 6, 1, 1, nil, 1, nil],
                [nil, 1, nil, nil, 1, 1, nil],
                [nil, nil, 1, 2, nil, 2, 1, nil],
                [nil, 2, nil, 2, 3, 3, nil],
                [nil, nil, 1, nil, nil, 1, 2, nil],
                [nil, 1, 3, nil, nil, 1, nil],
                [nil, 1, 5, 1, 1, 2, 1, nil],
                [nil, 1, 3, 3, 1, 1, nil],
                [nil, 4, 4, 1, 3, 3, 3, nil],
                [nil, 1, 1, 2, 2, 2, nil],
                [nil, 2, 2, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1920,
            rows: [
                [nil, nil, nil, nil, nil, 4, 1, 2],
                [nil, nil, nil, 1, 1, 2, 1],
                [3, 2, nil, 3, 3, nil, nil, 3],
                [nil, nil, 1, 4, 4, nil, 5],
                [5, nil, 2, 2, 1, 2, 2, 2],
                [2, 2, 1, 1, 3, 1, 1],
                [4, 1, 1, 1, 6, 1, 3, 1],
                [3, 1, 1, 2, 1, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, 1, nil, nil],
                [nil, 3, nil, 3, nil, 1, nil],
                [nil, 3, 1, nil, 3, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
    ]
}
