// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch28 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 541,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, 2, 2, 2, 2, nil, 3],
                [3, nil, nil, nil, nil, nil, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 6, 6, 6, nil, nil],
                [nil, nil, 4, 4, 1, nil, nil],
                [nil, nil, 1, 1, 1, 5, nil, nil],
                [nil, nil, 5, 4, 4, nil, nil],
                [nil, nil, nil, 4, 7, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 542,
            rows: [
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 5, 5, 5, 4],
                [nil, nil, nil, nil, nil, nil, 4],
                [4, 4, 4, 4, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, 6, nil],
                [nil, 1, 1, 1, 1, 3, nil],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 4, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 543,
            rows: [
                [6, nil, nil, nil, 6, nil, nil, nil],
                [6, nil, nil, nil, 5, nil, nil],
                [nil, 5, nil, nil, 3, 3, nil, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [nil, 3, nil, nil, 3, 3, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, nil, 1, 1, nil, nil],
                [1, nil, nil, 1, 1, 1, nil],
                [nil, 1, nil, nil, 1, 2, nil, nil],
                [2, nil, nil, 2, 2, 2, nil],
                [2, nil, nil, nil, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [7, nil, nil, nil, 2, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 544,
            rows: [
                [nil, 1, 1, 1, 1, 1, 2, nil],
                [nil, 2, 2, 1, 1, 1, nil],
                [nil, nil, 1, 1, 1, 3, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 5, nil, nil, nil, nil, nil, nil],
                [4, 2, nil, nil, nil, nil, nil],
                [nil, 2, 2, nil, nil, nil, nil, nil],
                [nil, 4, 4, nil, nil, nil, nil],
                [nil, nil, 7, 7, nil, nil, nil, nil],
                [nil, nil, 5, 6, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 545,
            rows: [
                [1, 3, nil, nil, nil, nil, 3, 3],
                [3, 3, nil, nil, nil, 3, 2],
                [2, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 7],
                [7, nil, nil, nil, nil, nil, 7],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, 5, nil, nil, nil, 5, 4],
                [4, 3, nil, nil, nil, nil, 3, 2],
                [2, 2, nil, nil, nil, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 546,
            rows: [
                [nil, 4, 4, 4, 4, 4, 1, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [2, 1, 1, 1, 1, 1, 3],
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [3, 3, 3, 3, 3, 3, 5],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 1, 1, nil],
                [nil, 1, 6, 6, 1, 1, 1, nil],
                [nil, 1, 1, 1, 7, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 547,
            rows: [
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [3, 3, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 5],
                [1, nil, nil, nil, nil, nil, 1],
                [2, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 6],
                [5, 2, nil, nil, nil, nil, 2, 2],
                [1, 1, nil, nil, nil, 1, 1],
                [1, 4, nil, nil, nil, nil, 4, 3],
                [5, 2, nil, nil, nil, 7, 7],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 548,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, 4, 4, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 1, 1, 2, 2, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 4, 4, 5, nil, nil],
                [nil, nil, 5, 3, 7, 6, nil, nil],
                [nil, nil, 6, 5, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 549,
            rows: [
                [nil, 3, nil, 3, nil, 3, nil, 2],
                [2, nil, 4, nil, 4, nil, 4],
                [nil, 4, nil, 4, nil, 6, nil, 6],
                [2, nil, 2, nil, 2, nil, 2],
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
                [nil, 2, nil, 2, nil, 2, nil, 7],
                [7, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 5, nil, 5, nil, 5],
                [5, nil, 5, nil, 1, nil, 1],
                [nil, 1, nil, 3, nil, 3, nil, 3],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 550,
            rows: [
                [nil, 4, 4, nil, nil, 4, 4, nil],
                [4, 4, nil, nil, 4, 1, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 3, nil, 3, nil, 3, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [3, nil, 7, nil, 7, nil, 7, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 6, nil],
                [2, nil, 2, nil, 5, nil, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 551,
            rows: [
                [nil, 1, nil, 2, nil, 2, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 2, nil, 1],
                [1, nil, 1, nil, 4, nil, 4],
                [nil, 1, nil, 3, nil, 3, nil, 3],
                [3, nil, 3, nil, 5, nil, 2],
                [nil, 2, nil, 2, nil, 1, nil, 5],
                [5, nil, 5, nil, 7, nil, 7],
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
                [nil, 1, nil, 1, nil, 1, nil, 6],
                [1, nil, 2, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 552,
            rows: [
                [3, nil, nil, nil, nil, nil, nil, 3],
                [3, nil, 3, 2, 2, nil, 2],
                [nil, 2, 2, nil, nil, 5, 5, nil],
                [nil, 5, nil, nil, nil, 5, nil],
                [nil, 1, 4, nil, nil, 4, 4, nil],
                [nil, 4, nil, nil, nil, 1, nil],
                [nil, 1, 4, nil, nil, 3, 3, nil],
                [nil, 4, nil, nil, nil, 4, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, 6, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 1, 7, 1, nil, nil],
                [nil, nil, 5, nil, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 553,
            rows: [
                [nil, 6, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [3, nil, 3, nil, 3, nil, 3],
                [nil, 3, nil, 3, nil, 2, nil, 2],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 2, nil, 2],
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [7, nil, 7, nil, 4, nil, 4],
                [nil, 4, nil, 4, nil, 6, nil, 6],
                [6, nil, 5, nil, 5, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 4
        ),
        LevelTemplate(
            levelNumber: 554,
            rows: [
                [1, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [2, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, 4, nil, 4, nil],
                [4, nil, 4, nil, 4, nil, 3, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [3, nil, 3, nil, 3, nil, 2, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 5, nil, 1, nil],
                [nil, 1, nil, 7, nil, 7, nil],
                [3, nil, 3, nil, 3, nil, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 2, 2, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 555,
            rows: [
                [nil, 2, 2, nil, nil, 2, 1, nil],
                [1, 1, nil, nil, 1, 1, nil],
                [nil, 1, 1, nil, nil, 1, 4, nil],
                [4, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 7, nil],
                [7, nil, 2, nil, 2, nil, 2, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [4, nil, 4, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 3, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [3, nil, 5, nil, 3, nil, 2, nil],
                [nil, 2, nil, 2, nil, 6, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 556,
            rows: [
                [nil, 1, nil, 3, nil, 3, nil, 3],
                [3, nil, 3, nil, 3, nil, 3],
                [nil, 1, nil, 7, nil, 7, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
                [nil, 2, nil, 1, nil, 1, nil, 4],
                [4, nil, 4, nil, 4, nil, 4],
                [nil, 1, nil, 1, nil, 3, nil, 3],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 3, nil, 3, nil, 3, nil, 5],
                [6, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 557,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, 1, nil, nil, 5, 5, nil],
                [nil, 5, nil, nil, nil, 5, nil],
                [nil, 5, 3, nil, nil, 3, 3, nil],
                [nil, 7, nil, nil, nil, 7, nil],
                [nil, 4, 4, nil, nil, 4, 4, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, 3, 6, 3, nil, nil],
                [nil, nil, 3, nil, nil, 3, nil, nil],
                [nil, nil, 3, 4, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 558,
            rows: [
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 5, nil],
                [5, nil, 5, nil, 1, nil, 3, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [3, nil, 3, nil, 3, nil, 1, nil],
                [nil, 7, nil, 3, nil, 3, nil],
                [3, nil, 3, nil, 3, nil, 3, nil],
                [nil, 4, nil, 4, nil, 4, nil],
                [4, nil, 4, nil, 4, nil, 4, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [2, nil, 2, nil, 2, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 1, 1, 6, 6, 1, 1],
                [1, 1, 1, 1, 1, 2, 2],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 559,
            rows: [
                [nil, 1, 1, nil, nil, 1, 2, nil],
                [2, 2, nil, nil, 2, 1, nil],
                [nil, 1, 1, nil, nil, 1, 3, nil],
                [3, 3, nil, nil, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, nil, 4, nil, 4, nil, 4, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [6, nil, 6, nil, 5, nil, 5, nil],
                [nil, 1, nil, 2, nil, 2, nil],
                [2, nil, 3, nil, 3, nil, 3, nil],
                [nil, 3, nil, 2, nil, 2, nil],
                [2, nil, 2, nil, 2, nil, 1, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 7, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 560,
            rows: [
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [2, nil, nil, 2, nil, nil, 2],
                [2, nil, nil, 2, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, 2, nil, nil, 6],
                [5, nil, nil, 5, nil, nil, 3],
                [nil, 3, 1, 1, 2, 2, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, 7, nil, nil, nil],
                [nil, nil, nil, 7, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
    ]
}
