// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch139 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2761,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 2, 2, 1, nil, nil],
                [nil, nil, 5, 3, 1, nil, nil],
                [nil, nil, 4, 1, 3, 1, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 3, 1, 5, 3, nil, nil],
                [nil, nil, 1, 3, 5, nil, nil],
                [nil, nil, 2, 1, 2, 3, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, 3, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2762,
            rows: [
                [nil, 1, 3, nil, 1, 5, nil, nil],
                [nil, 2, 1, nil, 2, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 3, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, 1, 4, 1, nil, nil],
                [nil, nil, 2, 2, 4, nil, nil, nil],
                [nil, 2, 1, 3, nil, nil, nil],
                [nil, 1, 3, 2, nil, nil, nil, nil],
                [nil, 3, 1, 4, nil, nil, nil],
                [nil, 2, 1, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2763,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 4, 1, nil, nil],
                [nil, 3, 1, 2, 1, nil, nil],
                [nil, 5, 2, 4, 2, 4, 2, nil],
                [nil, 1, 5, 2, 1, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2764,
            rows: [
                [nil, nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [1, 2, 1, 3, 1, 3, 1, 3],
                [nil, nil, nil, nil, 1, nil, nil],
                [3, 1, 2, 2, 1, 2, 3, 1],
                [nil, nil, nil, nil, 4, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, nil, 4, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2765,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 5, 2, nil, nil],
                [nil, nil, 3, 1, 3, nil, nil],
                [nil, nil, 2, 3, 1, 3, nil, nil],
                [nil, nil, 5, 1, 1, nil, nil],
                [nil, nil, 4, 2, 1, 2, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 2, 2, 1, 2, nil, nil],
                [nil, nil, 1, 4, 1, nil, nil],
                [nil, nil, 3, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2766,
            rows: [
                [nil, 4, nil, 3, nil, 2, nil, 1],
                [4, nil, 3, nil, 1, nil, 2],
                [nil, 1, nil, 3, nil, 1, nil, 2],
                [4, nil, 3, nil, 1, nil, 2],
                [nil, 1, nil, 1, nil, 4, nil, 1],
                [2, nil, 1, nil, 2, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2767,
            rows: [
                [nil, 2, 1, nil, nil, nil, nil, nil],
                [2, 1, 2, nil, nil, nil, nil],
                [nil, 3, 1, nil, nil, nil, nil, nil],
                [nil, nil, 4, 1, nil, nil, nil],
                [nil, 3, 1, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 3, 4, 1, nil, nil, nil],
                [nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil, nil],
                [nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 2, 1, nil, nil],
                [nil, nil, nil, 6, 1, 1, nil],
                [nil, nil, nil, nil, 2, 1, nil, nil],
                [nil, nil, nil, 2, 1, 1, nil],
                [nil, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2768,
            rows: [
                [nil, 1, 3, nil, 2, 1, nil, nil],
                [nil, 2, 1, nil, 2, 1, nil],
                [nil, 2, nil, nil, nil, 3, nil, nil],
                [nil, 5, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil],
                [nil, nil, 3, 1, 1, nil, nil, nil],
                [nil, 2, 1, 2, nil, nil, nil],
                [nil, 3, 2, 1, nil, nil, nil, nil],
                [nil, 2, 1, 3, nil, nil, nil],
                [nil, 1, 3, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2769,
            rows: [
                [nil, 1, 3, 1, 2, 3, 1, nil],
                [nil, 2, 1, 2, 1, 4, nil],
                [nil, nil, 2, 1, 1, 2, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, nil, 6, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 3, nil, nil, nil, nil, nil, nil],
                [2, 1, nil, nil, nil, nil, nil],
                [nil, 4, 1, nil, nil, nil, nil, nil],
                [nil, 3, 1, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2770,
            rows: [
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, 3, 1, nil, 4, 3, nil],
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, 1, 1, nil, 1, 2, nil],
                [nil, 1, 2, 1, 2, 3, 1, nil],
                [nil, 2, 1, nil, 3, 1, nil],
                [nil, 4, 1, 2, 1, 1, 1, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2771,
            rows: [
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 1, 2, 1, 3, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, 3],
                [nil, 1, 1, 2, 1, 4, 1, nil],
                [nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, 4, nil],
                [nil, 3, 2, 1, 3, 1, nil],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, 1, 5, 2, 2, 3, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 1, 4, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2772,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, 4, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 1, 3, 1, nil, nil],
                [nil, 3, 1, 4, 1, nil, nil],
                [nil, 1, 1, 1, 2, 4, 2, nil],
                [nil, 3, 2, 2, 2, 4, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2773,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [2, 4, 1, 1, 3, 1, 2, 1],
                [nil, nil, nil, nil, 3, nil, nil],
                [2, 1, 2, 3, 2, 1, 4, 4],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 3, nil, 2, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2774,
            rows: [
                [nil, 3, nil, 3, nil, 1, nil, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [nil, 5, nil, 1, nil, 3, nil, nil],
                [nil, 2, nil, 1, nil, 2, nil],
                [nil, 2, nil, 1, nil, 3, nil, nil],
                [nil, 1, nil, 3, nil, 1, nil],
                [nil, 2, nil, 1, nil, 4, nil, nil],
                [nil, 1, nil, 3, nil, 1, nil],
                [nil, 2, nil, 2, nil, 1, nil, nil],
                [nil, 2, nil, 1, nil, 2, nil],
                [nil, 1, nil, 2, nil, 1, nil, nil],
                [nil, 3, nil, 3, nil, 1, nil],
                [nil, 2, nil, 1, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2775,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 3, 3, 1, nil, nil],
                [nil, nil, 3, 2, 4, nil, nil],
                [nil, nil, 4, 3, 2, 1, nil, nil],
                [nil, nil, 2, 1, 3, nil, nil],
                [nil, nil, 1, 2, 1, 3, nil, nil],
                [nil, nil, 5, 1, 5, nil, nil],
                [nil, nil, 1, 3, 4, 1, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 2, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2776,
            rows: [
                [nil, 2, nil, 1, nil, 3, nil, 1],
                [2, nil, 1, nil, 3, nil, 1],
                [nil, 2, nil, 2, nil, 1, nil, 1],
                [4, nil, 3, nil, 3, nil, 1],
                [nil, 3, nil, 1, nil, 2, nil, 1],
                [2, nil, 1, nil, 2, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, 1, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2777,
            rows: [
                [nil, 1, 1, nil, nil, nil, nil, nil],
                [1, 5, 4, nil, nil, nil, nil],
                [nil, 3, 2, nil, nil, nil, nil, nil],
                [nil, nil, 3, 1, nil, nil, nil],
                [nil, 5, 1, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil, nil],
                [nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 1, 2, 3, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 2, 3, nil, nil],
                [nil, nil, nil, 1, 3, 2, nil],
                [nil, nil, nil, nil, 3, 1, nil, nil],
                [nil, nil, nil, 3, 1, 3, nil],
                [nil, nil, nil, nil, 1, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2778,
            rows: [
                [nil, nil, 2, nil, nil, 1, nil, nil],
                [nil, nil, 1, 1, 3, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2779,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [4, 1, 2, 1, 1, 5, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 1, 2, 4, 2, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2780,
            rows: [
                [nil, 1, 3, nil, 3, 1, nil, nil],
                [nil, 3, 6, nil, 4, 2, nil],
                [nil, 3, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 3, nil, nil, nil, 1, nil, nil],
                [nil, 4, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil, nil],
                [nil, 4, 1, 2, nil, nil, nil],
                [nil, 1, 2, 1, nil, nil, nil, nil],
                [nil, 2, 1, 3, nil, nil, nil],
                [nil, 1, 2, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
    ]
}
