// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch147 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2921,
            rows: [
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 2, nil, nil, 1, nil, 3, nil],
                [1, nil, nil, 2, nil, nil, 2],
                [nil, 4, nil, nil, 2, nil, 1, nil],
                [1, nil, nil, 3, nil, nil, 5],
                [nil, 2, nil, nil, 1, nil, 5, nil],
                [nil, 1, nil, 3, nil, 2, nil],
                [nil, 2, nil, nil, 1, nil, 3, nil],
                [nil, 2, nil, 4, nil, 3, nil],
                [nil, nil, 1, 5, 1, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2922,
            rows: [
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, 4, nil],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, 2, 4, 4, 1, nil, nil],
                [nil, 6, 5, 1, 2, 1, 2, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2923,
            rows: [
                [nil, 1, 2, 3, 4, 2, 1, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, 1, nil, nil, nil, nil, 4, nil],
                [3, 2, 1, 3, 2, 1, 1],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [1, 3, 1, 3, 2, 1, 1],
                [nil, 4, 2, 6, 3, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 2, 1, 2, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2924,
            rows: [
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, 1, 3, nil, 1, 4, nil],
                [nil, 1, 2, 3, 1, 1, 1, nil],
                [nil, 1, 3, nil, 2, 1, nil],
                [nil, 4, 2, 1, 2, 1, 1, nil],
                [nil, 4, 1, nil, 2, 1, nil],
                [nil, nil, 1, nil, nil, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2925,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, 1, 4, 1, nil],
                [2, nil, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, 3, 1, 4, nil],
                [2, nil, nil, nil, nil, 1, nil],
                [2, 1, 3, 1, nil, 5, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [2, 1, 2, 1, nil, 2, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2926,
            rows: [
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, 1, 2, nil, nil, nil, nil],
                [1, 4, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, 4, nil],
                [1, 4, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 3, 3, nil],
                [nil, nil, nil, 4, 2, nil, 1, 2],
                [nil, 1, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, 4, nil, 2, 1],
                [nil, 2, 2, nil, nil, nil, nil],
                [1, 3, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [1, 1, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2927,
            rows: [
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 5, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [2, 1, 3, 1, 4, 2, 1, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 3, 1, 1, 1, 2, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2928,
            rows: [
                [nil, nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2929,
            rows: [
                [nil, 3, nil, nil, nil, nil, 2, nil],
                [1, 3, nil, nil, nil, 2, 1],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [2, 1, nil, nil, nil, 2, 1],
                [nil, 3, nil, nil, nil, nil, 1, nil],
                [2, 3, nil, nil, nil, 2, 1],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [5, 1, nil, nil, nil, 2, 1],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2930,
            rows: [
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [1, nil, nil, 3, nil, nil, 1],
                [1, nil, nil, 2, 4, nil, nil, 1],
                [2, nil, nil, 1, nil, nil, 2],
                [1, nil, nil, 2, 3, nil, nil, 1],
                [1, nil, nil, 2, nil, nil, 1],
                [nil, 2, 4, 1, 1, 2, 2, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 2, 1, 2, 1, 5, 1, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2931,
            rows: [
                [nil, 1, nil, 2, nil, 5, nil, 1],
                [2, nil, 3, nil, 5, nil, 3],
                [nil, 5, nil, 1, nil, 1, nil, 2],
                [2, nil, 1, nil, 1, nil, 3],
                [nil, 1, nil, 3, nil, 1, nil, 3],
                [2, nil, 3, nil, 3, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, 4, nil],
                [nil, nil, nil, nil, 3, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2932,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 2, 1, 4, 3, 2, nil],
                [nil, nil, nil, 5, 3, nil, nil, nil],
                [nil, nil, 1, 2, 4, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, 6, 1, nil, nil, nil],
                [nil, 4, 1, 2, 1, 2, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, 1, 2, 1, 1, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2933,
            rows: [
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [5, nil, nil, nil, nil, nil, nil],
                [1, 4, 1, 2, 1, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, 5],
                [3, 2, 1, 3, 2, 4, 3, 1],
                [nil, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 2, 2, 3, 1, 3, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 3, 1, 3, 1, 2, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2934,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 3, 1, 1, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, 3, 5, nil, 1, 2, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, 2, 3, nil, 1, 3, nil],
                [nil, 1, 2, 1, 4, 1, 2, nil],
                [nil, 1, 3, nil, 1, 1, nil],
                [nil, 2, 1, 1, 2, 1, 4, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2935,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 2, 5, 6, 2, 1, nil],
                [3, nil, nil, nil, nil, nil, 1],
                [1, nil, 2, 1, 2, 3, nil, 3],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 3, 1, 2, 1, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, 1, 2, nil, nil],
                [nil, nil, 1, 1, 4, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2936,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, nil, 2, 3, 3, nil, nil],
                [nil, nil, 1, 1, 2, 3, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 1, 4, 1, 3, nil, nil],
                [nil, nil, 1, 2, 4, nil, nil],
                [nil, nil, 1, 1, 5, 1, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 2, 1, 1, 5, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2937,
            rows: [
                [2, nil, nil, 1, nil, 2, 1, 3],
                [1, nil, 3, nil, 4, nil, 3],
                [1, nil, nil, 3, nil, nil, nil, 2],
                [1, 4, 1, nil, nil, nil, 2],
                [1, nil, nil, 3, nil, nil, nil, 1],
                [3, 1, 4, nil, nil, nil, 1],
                [nil, nil, nil, 2, nil, 1, 2, nil],
                [nil, nil, 1, nil, 3, nil, nil],
                [nil, nil, nil, 3, nil, 1, 1, nil],
                [nil, nil, 4, nil, 1, nil, nil],
                [nil, nil, nil, 4, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2938,
            rows: [
                [nil, 3, nil, nil, nil, nil, 1, nil],
                [nil, 3, 1, 3, 4, 2, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 4, 1, 3, 1, 5, 3],
                [nil, 4, nil, nil, nil, nil, 2],
                [nil, 1, 2, 1, 3, 3, 1, 4],
                [nil, 1, nil, nil, nil, nil, 2],
                [nil, nil, nil, 3, 1, 3, 3, nil],
                [nil, 2, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, 3, 1, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2939,
            rows: [
                [nil, 4, 1, nil, 3, 1, nil, nil],
                [nil, 2, 1, nil, 3, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 5, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 5, 4, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 4, 1, 1, nil, nil, nil],
                [nil, 3, 3, 1, nil, nil, nil],
                [nil, 4, 1, 2, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2940,
            rows: [
                [nil, 2, 3, nil, nil, 4, 5, nil],
                [nil, 1, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, nil, 4, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 4, nil, nil, nil, 1, nil, nil],
                [nil, 4, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
    ]
}
