// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch112 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2221,
            rows: [
                [nil, 1, 2, 2, 1, 2, 2, nil],
                [1, nil, nil, nil, nil, nil, 3],
                [nil, 3, nil, nil, nil, nil, 1, nil],
                [2, 1, 2, 1, 1, 1, 4],
                [nil, 4, nil, nil, nil, nil, 4, nil],
                [2, 2, 3, 3, 4, 1, 3],
                [nil, 2, 1, 3, 3, 3, 2, nil],
                [nil, 6, 1, 1, 1, 2, nil],
                [nil, 4, 1, 5, 1, 1, 2, nil],
                [nil, 2, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2222,
            rows: [
                [1, nil, nil, 4, 2, nil, nil, 1],
                [2, nil, 1, 2, 1, nil, 2],
                [nil, 7, nil, 1, 3, nil, 3, nil],
                [nil, 3, 2, 3, 2, 3, nil],
                [nil, 3, nil, 4, 2, nil, 1, nil],
                [nil, 1, 2, 1, 4, 3, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 3, 3, 2, nil, nil],
                [nil, nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [2, 1, 1, 1, 1, 2, 2, 4],
                [1, nil, nil, nil, nil, nil, 2],
                [1, 1, 1, 2, 1, 1, 1, 2],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2223,
            rows: [
                [2, nil, 1, 2, 1, 3, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [3, 3, 1, 2, 1, 1, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 4, 2, 1, 1, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 5, 1, 5, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 2, nil, 2, nil, 2],
                [3, nil, 1, nil, 5, nil, 5],
                [nil, 2, nil, 1, nil, 1, nil, 1],
                [2, nil, 2, nil, 4, nil, 4],
                [nil, 2, nil, 5, nil, 1, nil, 6],
                [1, nil, 1, nil, 2, nil, 1],
                [nil, 2, nil, 1, nil, 4, nil, 1],
                [3, nil, 2, nil, 2, nil, 1],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2224,
            rows: [
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [5, nil, nil, nil, nil, nil, nil],
                [5, 1, 4, 2, 4, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, 3],
                [3, 2, 6, 4, 4, 1, 2, 3],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, 5, 5, 2, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, 6, nil],
                [nil, 2, 1, 2, 2, 2, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [1, 3, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2225,
            rows: [
                [1, 2, 1, 4, 2, 2, 4, 1],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 3, 5, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [3, 3, 3, 2, 1, 4, 4, 3],
                [nil, nil, nil, nil, 1, nil, nil],
                [2, 3, 2, 2, 2, 1, 3, 3],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [1, 2, 1, 5, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2226,
            rows: [
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [4, 1, 3, 2, 1, 2, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 1, 2, 6, 2, 2, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2227,
            rows: [
                [nil, 3, 1, 2, 2, 1, 1, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, nil, 4, 4, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 1, 4, 4, 4, 4, 1, 1],
                [2, nil, nil, nil, nil, nil, 3],
                [2, nil, 5, 5, 5, 1, nil, 1],
                [1, nil, 2, 3, 1, nil, 6],
                [1, nil, 1, 2, 1, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [4, 1, 2, 2, 2, 2, 1, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 1, 1, nil, nil],
                [nil, nil, 3, 1, 3, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2228,
            rows: [
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 2, 1, 4, 4, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, 3],
                [nil, 2, 6, 1, 3, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, 1, 1, 1, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 5, 1, 2, 2, 1, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 7, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2229,
            rows: [
                [nil, nil, 2, nil, nil, 5, 2, nil],
                [nil, 3, 2, nil, nil, 2, 1],
                [2, nil, nil, 2, 1, 2, nil, nil],
                [1, 6, nil, 2, nil, nil, nil],
                [2, nil, nil, 1, 4, 1, nil, nil],
                [3, 4, nil, 1, nil, nil, nil],
                [1, nil, 2, 1, 4, 1, 2, nil],
                [nil, 3, nil, nil, 3, nil, 2],
                [2, nil, 2, 1, 1, 7, 1, nil],
                [nil, 1, nil, nil, 5, nil, 1],
                [nil, 4, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2230,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 3, 1, 1, nil, nil],
                [nil, nil, 2, 2, 6, nil, nil],
                [nil, nil, 6, 1, 2, 1, nil, nil],
                [nil, nil, 1, 3, 3, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 6, nil, nil],
                [nil, nil, 1, 5, 5, 4, nil, nil],
                [nil, nil, 5, 3, 3, nil, nil],
                [nil, nil, 5, 1, 1, 4, nil, nil],
                [nil, nil, 1, 1, 5, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2231,
            rows: [
                [nil, 1, nil, 2, nil, 1, nil, 5],
                [1, nil, 2, nil, 1, nil, 1],
                [5, nil, 2, nil, 1, nil, 1, nil],
                [nil, 3, nil, 3, nil, 1, nil],
                [5, nil, 5, nil, 1, nil, 1, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, 1, nil, 1, nil, 1, nil, nil],
                [2, nil, 1, nil, 1, nil, nil],
                [nil, 2, nil, 1, nil, 6, nil, nil],
                [1, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, 2, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2232,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 4, 2, 1, nil, nil],
                [nil, nil, 2, 5, 5, 1, nil, nil],
                [nil, 1, 3, 3, 2, 2, nil],
                [nil, nil, 4, 4, 4, 3, nil, nil],
                [nil, 3, 4, 2, 1, 2, nil],
                [nil, 1, 1, 2, 3, 2, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 4, 4, 1, 2, 3, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2233,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, 3, nil, nil],
                [nil, nil, nil, 4, nil, nil, 2, nil],
                [nil, nil, 3, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, 1, nil, nil, 4],
                [nil, nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, 4],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 1, 2, 2, 2, nil, nil],
                [nil, 2, 5, 1, 4, 7, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2234,
            rows: [
                [nil, nil, 2, 4, 4, 1, nil, nil],
                [nil, nil, 1, 3, 4, nil, nil],
                [nil, nil, 2, 1, 1, 2, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 1, 1, 2, 2, nil, nil],
                [nil, nil, 3, 1, 2, nil, nil],
                [nil, nil, 1, 3, 1, 5, nil, nil],
                [nil, nil, 2, 1, 6, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 6, 1, 3, nil, nil],
                [nil, nil, 6, 1, 2, 2, nil, nil],
                [nil, nil, 1, 5, 1, nil, nil],
                [nil, nil, 2, 3, 3, 1, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, 1, 2, 2, 5, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2235,
            rows: [
                [5, 3, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, 6, 2, 2, 2, nil, nil],
                [nil, 4, nil, nil, nil, 4, nil],
                [nil, nil, 4, 1, 1, 3, nil, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 4, nil, nil, nil],
                [1, 3, nil, nil, nil, nil, 3, 1],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, 5, nil, nil, 1],
                [2, nil, nil, 1, nil, nil, 1],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2236,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, 2, nil, nil, nil, nil],
                [nil, nil, 1, 2, nil, nil, nil, nil],
                [nil, 1, 3, 2, nil, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil, nil],
                [nil, 1, 1, 6, nil, nil, nil],
                [4, 1, 1, 1, 2, 1, 2, nil],
                [2, 3, 2, 3, 1, 1, nil],
                [3, 4, 2, 1, 1, 2, 3, nil],
                [3, 3, 2, 3, 2, 1, nil],
                [1, 2, 4, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 5, 3, 3, 1, 2, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2237,
            rows: [
                [nil, 6, 4, nil, nil, 1, 3, nil],
                [1, nil, 2, nil, 2, nil, 1],
                [2, nil, nil, 1, 2, nil, nil, 4],
                [1, nil, nil, nil, nil, nil, 2],
                [1, nil, nil, 2, 1, nil, nil, 2],
                [1, nil, nil, nil, nil, nil, 3],
                [nil, 1, nil, nil, nil, nil, 5, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 2, nil, nil, nil, nil, 3, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, nil, 2, nil, nil, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, nil, 3, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2238,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [2, 2, 1, 2, 2, 2, 3, 1],
                [nil, nil, nil, nil, 3, nil, nil],
                [1, 6, 1, 4, 4, 1, 4, 3],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, 1, nil, 4, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, nil, 2, 6, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, nil, 5, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2239,
            rows: [
                [nil, nil, nil, nil, nil, nil, 1, 2],
                [nil, nil, 2, 2, 1, 3, 3],
                [nil, nil, nil, nil, nil, nil, 4, 4],
                [nil, 1, nil, nil, nil, 6, nil],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 1, 2, nil, nil, 2, nil, nil],
                [1, 1, 3, nil, 7, nil, nil],
                [nil, 1, 3, nil, nil, 2, nil, nil],
                [1, 1, 2, nil, 1, nil, nil],
                [5, nil, 2, 1, 2, 5, nil, 1],
                [nil, 3, nil, 1, nil, 1, 1],
                [1, nil, 2, 5, 2, 1, nil, 2],
                [nil, 3, nil, 2, nil, 4, 2],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2240,
            rows: [
                [nil, 2, nil, nil, 5, 1, 1, nil],
                [4, nil, nil, 3, 3, 3, nil],
                [1, nil, nil, 2, 2, 4, nil, nil],
                [4, nil, 1, 5, 2, nil, nil],
                [1, nil, nil, 5, 3, 1, nil, nil],
                [1, nil, 3, 1, 2, nil, nil],
                [2, nil, nil, 5, 1, 3, nil, nil],
                [6, nil, 2, 3, 1, 3, nil],
                [5, nil, nil, 3, 1, 1, nil, nil],
                [1, nil, 3, 1, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
    ]
}
