// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch107 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2121,
            rows: [
                [nil, 3, 3, nil, nil, 1, 3, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 3, nil, nil],
                [nil, 4, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 3, nil, nil, nil, 3, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 5, nil],
                [nil, 2, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, 7, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2122,
            rows: [
                [3, 1, 5, 3, 1, 3, 6, 2],
                [2, nil, nil, 2, nil, nil, 1],
                [2, nil, nil, 3, 1, nil, nil, 1],
                [nil, nil, nil, 2, nil, nil, nil],
                [1, nil, nil, 2, 2, nil, nil, 1],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 5, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 6, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2123,
            rows: [
                [nil, 2, 2, 3, 2, 2, 3, nil],
                [3, nil, nil, nil, nil, nil, 1],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [1, 1, 1, 5, 3, 1, 5],
                [nil, 5, nil, nil, nil, nil, 3, nil],
                [3, 3, 4, 1, 1, 3, 1],
                [nil, 1, 1, 4, 6, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 3, 1, 1, 2, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2124,
            rows: [
                [1, 1, nil, nil, nil, nil, 1, 2],
                [2, 1, 2, 2, 3, 3, 3],
                [1, 3, nil, nil, nil, nil, 1, 1],
                [1, 3, 3, 1, 2, 3, 3],
                [4, 3, nil, nil, nil, nil, 2, 2],
                [2, 4, 4, 4, 2, 5, 3],
                [2, 2, nil, nil, nil, nil, 2, 3],
                [3, 1, 1, 1, 3, 2, 3],
                [4, 1, nil, nil, nil, nil, 1, 4],
                [4, 3, 3, 1, 4, 4, 4],
                [1, 3, nil, nil, nil, nil, 1, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2125,
            rows: [
                [2, nil, nil, nil, nil, nil, nil, 1],
                [2, 1, 2, 2, 2, 1, 1],
                [1, nil, nil, nil, nil, nil, nil, 5],
                [1, 1, 2, 2, 1, 2, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [1, 4, 5, 4, 2, 1, 4],
                [4, nil, nil, nil, nil, nil, nil, 4],
                [1, 2, 2, 2, 4, 1, 1],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [1, 3, 1, 1, 3, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2126,
            rows: [
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, nil, nil, 7, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, 5, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, 1, 2, 1, 6, nil, nil],
                [nil, 1, 1, 4, 1, 1, 4, nil],
                [nil, 1, 4, 3, 4, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2127,
            rows: [
                [1, 2, nil, 4, 1, nil, 2, 2],
                [3, 2, nil, 1, nil, 2, 1],
                [nil, 1, nil, 2, 1, nil, 1, nil],
                [2, 2, 4, 4, 4, 4, 1],
                [nil, 2, nil, 3, 1, nil, 1, nil],
                [1, 1, 2, 1, 2, 1, 2],
                [nil, 1, nil, 2, 1, nil, 2, nil],
                [1, 2, nil, nil, nil, 3, 2],
                [nil, 3, nil, 1, 2, nil, 1, nil],
                [2, 1, nil, nil, nil, 4, 2],
                [3, 2, 1, nil, nil, 2, 2, 1],
                [5, 1, nil, nil, nil, 1, 1],
                [3, 1, 6, nil, nil, 1, 3, 2],
                [1, 1, nil, nil, nil, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2128,
            rows: [
                [nil, 1, 3, nil, nil, 1, 4, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [5, 2, nil, nil, nil, nil, 1, 4],
                [2, nil, nil, nil, nil, nil, 2],
                [1, 1, nil, nil, nil, nil, 3, 3],
                [3, nil, nil, nil, nil, nil, 1],
                [1, 3, nil, nil, nil, nil, 2, 4],
                [1, nil, nil, nil, nil, nil, 1],
                [2, 1, nil, nil, nil, nil, 4, 6],
                [3, nil, nil, nil, nil, nil, 3],
                [4, 4, nil, nil, nil, nil, 4, 1],
                [1, 2, nil, nil, nil, 2, 4],
                [1, 1, nil, nil, nil, nil, 1, 3],
                [2, 1, nil, nil, nil, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2129,
            rows: [
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, nil, nil, 3, nil, 6, nil],
                [1, nil, nil, 3, nil, nil, 1],
                [nil, 2, nil, nil, 3, nil, 2, nil],
                [3, nil, nil, 3, nil, nil, 5],
                [nil, 5, nil, nil, 2, nil, 3, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, nil, 3, nil, 2, nil],
                [nil, 6, nil, 2, nil, 1, nil],
                [nil, nil, 3, 3, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2130,
            rows: [
                [nil, 4, 3, nil, 1, 1, nil, nil],
                [2, nil, 2, 3, nil, 1, nil],
                [4, nil, nil, nil, nil, nil, 4, nil],
                [5, 1, 2, nil, nil, 3, 3],
                [1, nil, nil, nil, nil, nil, 1, nil],
                [2, 1, 2, nil, nil, 1, 2],
                [nil, 1, 2, 3, 1, 5, 1, 6],
                [nil, 4, 1, nil, nil, 1, 2],
                [nil, 2, 1, 1, 4, 1, 5, 1],
                [nil, 2, 1, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2131,
            rows: [
                [nil, 3, 1, nil, nil, 1, 1, nil],
                [2, 4, nil, nil, 4, 2, nil],
                [nil, 2, 2, nil, nil, 1, 1, nil],
                [3, 1, nil, nil, 3, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, nil, 1, nil, 4, nil, 5, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 3, nil, 3, nil],
                [nil, 2, nil, 5, nil, 2, nil],
                [2, nil, 2, nil, 1, nil, 3, nil],
                [nil, 1, nil, 3, nil, 1, nil],
                [2, nil, 4, nil, 7, nil, 3, nil],
                [nil, 5, nil, 4, nil, 3, nil],
                [1, nil, 1, nil, 3, nil, 5, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2132,
            rows: [
                [nil, nil, 3, 4, 4, nil, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 5, nil, 2, nil, 1, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [3, nil, 1, nil, 1, nil, 5, nil],
                [nil, 1, nil, 2, nil, 5, nil],
                [5, nil, 1, nil, 2, nil, 1, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [1, nil, 2, nil, 1, nil, 2, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2133,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, 6, nil, 1, 2, nil, nil],
                [3, 3, nil, 2, 2, nil, nil],
                [nil, 1, 4, nil, 1, 4, nil, nil],
                [2, 3, nil, 1, 4, nil, nil],
                [nil, 4, 3, nil, 4, 2, nil, nil],
                [2, 1, nil, 1, 1, nil, nil],
                [nil, 2, 1, nil, 3, 1, nil, nil],
                [2, 2, nil, 3, 2, nil, nil],
                [nil, 6, 1, nil, 2, 1, nil, nil],
                [2, 1, nil, 4, 1, nil, nil],
                [nil, 2, 1, nil, 5, 1, nil, nil],
                [1, 6, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2134,
            rows: [
                [nil, nil, nil, 5, 5, 4, 4, nil],
                [1, 1, 2, nil, nil, nil, 4],
                [1, nil, nil, nil, nil, nil, nil, 3],
                [3, nil, nil, nil, nil, nil, 1],
                [4, nil, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [6, nil, nil, nil, 1, 3, 1, 4],
                [4, nil, nil, 2, 1, 2, 1],
                [3, nil, nil, nil, 1, 3, 2, 2],
                [3, nil, nil, 3, 1, 2, 1],
                [2, nil, nil, nil, 1, 1, 2, 2],
                [1, 2, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, 4, 1, 2, 1],
                [1, 1, nil, nil, nil, nil, nil],
                [2, 1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2135,
            rows: [
                [nil, 6, 6, nil, 1, 2, 1, nil],
                [4, nil, nil, nil, nil, nil, 3],
                [nil, 1, 1, 1, nil, 5, 1, nil],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 2, 1, 2, nil, 1, 4, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 1, 4, nil, 3, 3, 1, nil],
                [4, nil, nil, nil, nil, nil, 4],
                [nil, 5, 5, nil, 1, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 2, 5, 2, nil, 6, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 1, 2, nil, 1, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2136,
            rows: [
                [nil, nil, 2, 1, 3, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 4, nil, 4, 3, nil, 2],
                [1, 1, nil, 2, 1, nil, 3],
                [nil, 1, 1, 6, 1, 1, 1, nil],
                [2, 3, 3, 3, 3, 1, nil],
                [nil, nil, 5, 4, nil, 1, 2, nil],
                [nil, 1, 4, nil, 1, 2, nil],
                [nil, nil, nil, 2, 4, 4, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, 1, 2, 2, 2, nil, nil],
                [nil, 3, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2137,
            rows: [
                [3, nil, nil, nil, nil, nil, nil, 2],
                [1, nil, 6, 6, 3, nil, 3],
                [nil, 3, 1, nil, nil, 1, 1, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 2, 1, nil, nil, 2, 1, nil],
                [nil, 3, nil, nil, nil, 2, nil],
                [nil, 2, 1, nil, nil, 1, 4, nil],
                [nil, 2, nil, nil, nil, 5, nil],
                [nil, 3, 1, nil, nil, 1, 1, nil],
                [nil, 2, nil, nil, nil, 3, nil],
                [nil, nil, 2, nil, nil, 1, nil, nil],
                [nil, nil, 1, 7, 1, nil, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, 3, 3, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2138,
            rows: [
                [nil, 2, 3, 2, 2, 3, 2, nil],
                [nil, 5, 2, 2, 2, 4, nil],
                [nil, nil, 2, 1, 1, 4, nil, nil],
                [nil, nil, 2, 3, 3, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 1, 4, 2, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 1, nil, nil, nil, nil, nil, nil],
                [2, 1, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil, nil],
                [nil, 2, 7, nil, nil, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2139,
            rows: [
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, 3, 1, 1, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, 4, 4, nil, 3, 1, nil],
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, 1, 2, nil, 1, 1, nil],
                [nil, 1, 1, 4, 4, 1, 1, nil],
                [nil, 3, 2, nil, 2, 1, nil],
                [nil, 1, 2, 3, 2, 2, 3, nil],
                [nil, 4, 2, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2140,
            rows: [
                [2, 2, 3, 3, 2, 2, 1, 1],
                [6, nil, nil, nil, nil, nil, 1],
                [3, nil, nil, 1, 3, 2, 5, 1],
                [2, nil, nil, nil, 2, 3, 3],
                [2, nil, nil, 2, 1, 5, 1, 4],
                [1, nil, nil, nil, 1, 1, 4],
                [3, nil, nil, nil, nil, nil, 1, 4],
                [1, 2, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, 2, 1],
                [2, 2, nil, nil, nil, nil, nil],
                [1, 1, 2, 1, nil, nil, nil, nil],
                [1, 2, 1, 1, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [4, 4, 4, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
    ]
}
