// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch64 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1261,
            rows: [
                [1, 4, nil, nil, 2, nil, nil, 1],
                [3, nil, nil, 3, 3, 3, 5],
                [2, 4, 4, nil, 4, nil, nil, nil],
                [1, 1, 2, nil, 1, 1, 2],
                [3, nil, 1, 1, nil, nil, 3, 3],
                [2, nil, nil, 1, nil, 2, nil],
                [nil, 4, 4, 1, nil, nil, 2, nil],
                [1, 2, 1, 1, 2, 2, 1],
                [2, 1, nil, 2, 1, 3, 3, 2],
                [2, 2, 1, 2, 1, 2, 2],
                [1, 1, 1, 3, 4, 1, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1262,
            rows: [
                [nil, nil, nil, nil, 1, 3, nil, nil],
                [1, 1, 3, nil, nil, 1, 1],
                [1, 4, nil, 1, 2, 2, 1, 1],
                [1, 2, 1, 2, 2, 1, 2],
                [2, 1, 2, 2, 2, 1, 1, 1],
                [1, 4, 1, 1, 2, 2, 2],
                [1, 1, 4, 2, 1, 1, 1, 2],
                [2, 1, 2, 1, 1, 1, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 3, nil, nil],
                [nil, 3, nil, 1, nil, 4, nil],
                [nil, 1, 3, nil, 3, 1, nil, nil],
                [nil, 1, 6, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1263,
            rows: [
                [nil, nil, 2, nil, 5, nil, 5, nil],
                [nil, 1, 4, 4, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, 3, 1, nil, nil, 2, 1, nil],
                [nil, nil, 1, 2, 1, 1, nil],
                [nil, 1, 1, 1, 4, 1, 2, nil],
                [nil, 1, 1, 2, 1, 4, nil],
                [nil, 1, 1, 3, 1, 1, 2, nil],
                [nil, 4, 4, 4, 1, 3, nil],
                [nil, 1, 2, 1, 2, 3, 2, nil],
                [nil, 2, 1, 1, 1, 1, nil],
                [nil, 3, 1, 3, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1264,
            rows: [
                [nil, 1, 4, nil, 2, 1, 3, nil],
                [nil, nil, 1, nil, 1, 1, nil],
                [nil, 4, 4, 2, 2, 1, 2, nil],
                [nil, 1, 1, 2, 2, 1, nil],
                [nil, 4, 4, 1, 1, 5, 5, nil],
                [nil, 3, 3, 1, 2, 1, nil],
                [nil, 1, 1, 3, 3, 3, 2, nil],
                [nil, 1, 1, 2, 1, 2, nil],
                [nil, nil, 2, 2, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 2, 1, 1, 2, 1],
                [2, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 1, 1, 1, nil, 1],
                [1, nil, 1, nil, nil, 1, 1],
                [1, nil, 1, nil, 1, 1, nil, 1],
                [1, nil, 1, nil, nil, 1, 1],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1265,
            rows: [
                [nil, 1, 2, nil, 1, 2, 1, nil],
                [nil, nil, 1, nil, 1, 1, nil],
                [nil, 2, 2, 1, nil, 4, 2, nil],
                [nil, nil, 3, 1, nil, 1, nil],
                [nil, nil, 3, 3, 3, nil, 2, nil],
                [nil, 4, 4, nil, nil, 1, nil],
                [nil, 2, nil, nil, 1, nil, 4, nil],
                [nil, nil, 4, 1, 4, 1, nil],
                [nil, 2, 1, 1, 5, 1, 1, nil],
                [nil, 1, 3, 2, 1, 2, nil],
                [nil, 3, 1, 3, 3, 3, 1, nil],
                [nil, 1, 2, 2, 2, 1, nil],
                [nil, 2, 1, 2, 1, 2, 2, nil],
                [nil, 1, 1, 2, 5, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1266,
            rows: [
                [2, nil, nil, nil, 1, nil, nil, 1],
                [2, nil, 2, 1, nil, 1, 3],
                [1, 2, 1, 2, 1, 1, 3, 1],
                [nil, nil, 1, 2, nil, 1, 5],
                [4, 1, 1, 1, 2, 1, 4, 1],
                [nil, nil, 2, 1, nil, 5, 5],
                [nil, 2, 1, 1, 1, nil, 1, 3],
                [2, 2, 3, 1, nil, 3, 1],
                [nil, 2, 2, 2, 1, nil, 3, 1],
                [3, 1, 1, 4, nil, 1, 1],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1267,
            rows: [
                [nil, 2, nil, 1, nil, nil, 2, 1],
                [nil, 2, nil, nil, 1, 2, 1],
                [nil, nil, nil, 3, nil, 1, nil, nil],
                [nil, 3, 2, nil, 3, nil, nil],
                [1, nil, 1, 2, nil, nil, 2, 2],
                [2, 1, 1, nil, 1, 2, 2],
                [1, nil, nil, nil, 1, nil, nil, 2],
                [3, nil, nil, nil, nil, 2, 2],
                [1, 1, 3, nil, 3, nil, 5, nil],
                [nil, nil, nil, 1, 1, nil, nil],
                [2, nil, 1, 1, 1, nil, 2, 1],
                [nil, 1, 3, 1, nil, 1, 1],
                [1, 1, 4, 1, 1, 1, 5, 2],
                [1, 3, 1, 1, 2, 2, 2],
                [nil, 1, 3, 1, 2, 1, 1, nil],
                [nil, 5, 1, 1, 1, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1268,
            rows: [
                [1, nil, 3, 1, nil, nil, 1, nil],
                [nil, 2, 2, 1, 4, 4, 4],
                [nil, 4, 1, 2, nil, 1, nil, 2],
                [2, 4, 1, 2, 1, nil, 4],
                [1, nil, nil, 5, nil, nil, nil, 1],
                [nil, 1, 5, 1, 3, 2, 1],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [2, 2, nil, 1, 4, 1, 1],
                [2, 1, 2, 1, 3, 1, 2, 2],
                [1, 5, 1, 1, 2, 1, 2],
                [1, 3, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1269,
            rows: [
                [nil, nil, 1, nil, nil, 3, 3, 3],
                [2, nil, 2, 1, 4, 2, 1],
                [6, 1, 5, 1, 1, 1, 2, 2],
                [2, 2, 1, 1, 5, 5, 1],
                [nil, 2, 1, 4, 4, 2, nil, nil],
                [nil, 1, 1, 3, 1, nil, nil],
                [nil, 3, 1, 2, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 3, 1, 3, 1, 3],
                [1, 3, 3, 1, 2, 1, 2],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1270,
            rows: [
                [nil, nil, 2, nil, 1, 2, 4, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, 1, 1, 2, 1, nil, nil, nil],
                [nil, 2, nil, 1, nil, 3, nil],
                [nil, 3, 2, nil, 2, 1, 3, nil],
                [nil, 3, nil, 3, nil, nil, nil],
                [nil, 1, nil, 1, 1, 2, 1, nil],
                [nil, 5, 1, 3, 1, 2, nil],
                [nil, 2, 1, 2, 1, 3, 1, nil],
                [nil, 3, 3, 1, 3, 1, nil],
                [nil, 2, 2, 2, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1271,
            rows: [
                [nil, 1, 5, nil, 1, 1, 1, nil],
                [1, nil, nil, nil, 1, nil, 4],
                [4, nil, nil, 1, nil, nil, 1, nil],
                [nil, nil, 1, 5, nil, 1, nil],
                [4, nil, nil, 1, nil, 4, nil, 1],
                [nil, 2, 1, 2, 1, 1, 1],
                [4, nil, nil, nil, 1, 1, nil, nil],
                [nil, 5, 1, 4, nil, nil, 4],
                [2, 1, nil, nil, nil, 2, 2, nil],
                [nil, nil, 3, 2, 2, 2, 2],
                [2, 3, 1, 3, nil, 3, 2, 2],
                [2, 1, 1, 1, 1, 3, 1],
                [5, 1, 3, 3, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1272,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, 1, 3, nil, nil, nil, nil],
                [1, 1, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, 2, 1, nil],
                [1, 3, nil, 5, 2, nil, nil, nil],
                [nil, nil, nil, nil, 2, 3, nil],
                [nil, nil, nil, 3, 3, nil, 1, 3],
                [nil, 2, 1, nil, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, 4, 1],
                [nil, 5, 4, nil, nil, nil, nil],
                [1, 3, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, 3, nil],
                [1, 3, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, nil, 1, 3, nil],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1273,
            rows: [
                [1, 2, nil, nil, nil, nil, 1, nil],
                [nil, nil, 1, 4, 1, 4, 4],
                [4, nil, nil, 1, nil, 2, nil, nil],
                [2, 4, 1, 2, 2, 1, 3],
                [3, 2, nil, 4, 4, 4, 2, 2],
                [2, nil, 1, 1, nil, nil, 1],
                [1, 2, nil, nil, 3, 1, 3, 3],
                [1, 1, 1, nil, nil, 2, 1],
                [nil, nil, 3, 3, nil, nil, 3, nil],
                [3, nil, 2, 1, 1, 1, 5],
                [nil, nil, nil, nil, 1, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, 2, 1],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, 1, 5, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1274,
            rows: [
                [4, 1, nil, nil, nil, nil, 1, 2],
                [1, nil, nil, nil, nil, nil, 3],
                [nil, nil, 2, 3, 4, 2, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, nil, 5, 1, 2, 2, nil, nil],
                [nil, 2, nil, nil, nil, 4, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, 1, 3, nil, nil, nil],
                [2, 2, nil, nil, nil, nil, 1, 3],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1275,
            rows: [
                [nil, 1, 1, nil, nil, 3, 2, nil],
                [nil, 2, 2, nil, 3, nil, nil],
                [nil, nil, nil, nil, nil, 1, 1, 4],
                [4, 1, 3, 2, nil, 1, 3],
                [2, 3, 3, 1, nil, 3, 3, 1],
                [2, 3, nil, 3, 1, nil, nil],
                [2, 1, 1, nil, nil, 5, nil, nil],
                [nil, 2, nil, nil, 3, 1, 2],
                [1, nil, 1, nil, nil, 1, nil, 4],
                [4, 3, nil, 3, nil, nil, 1],
                [nil, nil, 5, 5, nil, nil, 6, 1],
                [2, 2, nil, 1, nil, 1, 2],
                [1, 2, 1, 2, nil, 1, 2, 1],
                [1, 2, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1276,
            rows: [
                [3, nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 3, 1, 1, nil, nil],
                [nil, 1, 1, 4, nil, 2, nil, 2],
                [nil, nil, nil, 1, 2, 3, nil],
                [1, 1, 1, 1, nil, 2, 2, 5],
                [3, 1, 3, 2, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, 2],
                [nil, 1, 3, 1, nil, 1, nil],
                [2, nil, nil, 3, 2, nil, 4, nil],
                [2, nil, nil, 1, nil, 2, 1],
                [3, 3, nil, 1, nil, nil, nil, nil],
                [2, 2, 5, 1, nil, 2, 2],
                [6, nil, 2, nil, nil, nil, nil, nil],
                [3, nil, nil, 2, 1, 2, 2],
                [nil, 1, 1, 2, 2, 1, 2, nil],
                [nil, 1, 4, 2, 4, 2, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1277,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, 1, 5, 1, 2, nil, nil],
                [nil, 2, 4, 1, 1, 3, nil],
                [nil, nil, 1, 4, 1, 1, nil, nil],
                [nil, 4, 4, 3, 3, 1, nil],
                [nil, 1, 4, 1, 4, 4, 1, nil],
                [1, 2, 1, 4, 1, 1, 2],
                [nil, 2, 2, 2, 1, 5, 2, nil],
                [5, 1, 4, 1, 2, 1, 2],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1278,
            rows: [
                [nil, 5, nil, nil, nil, nil, nil, nil],
                [nil, 1, 3, nil, 3, nil, nil],
                [nil, 2, nil, nil, nil, 1, 4, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 2, 1, nil, nil, nil, nil],
                [nil, nil, nil, 3, 2, 4, 1, nil],
                [nil, nil, 4, 1, 2, 2, nil],
                [nil, 3, 1, 1, 3, 1, 3, nil],
                [nil, 3, 3, 1, 4, 6, nil],
                [nil, 6, 1, 2, 5, 2, 2, nil],
                [nil, 2, 1, 5, 4, 3, nil],
                [nil, 2, 2, 1, 2, 2, 1, nil],
                [nil, 2, 2, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1279,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 4, 5, 1, nil, nil],
                [nil, nil, 4, 3, 5, nil, nil],
                [nil, nil, 4, 1, 1, 1, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 2, 2, 1, 4, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 4, 3, 1, nil, nil],
                [nil, nil, 1, 3, 3, nil, nil],
                [nil, nil, 5, 1, 3, 1, nil, nil],
                [nil, nil, 5, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1280,
            rows: [
                [1, 1, 1, 2, 2, 1, 1, 1],
                [2, 4, 2, 2, 1, 2, 2],
                [5, 3, 5, 5, 3, 3, 4, 3],
                [2, 3, 2, 3, 2, 2, 2],
                [3, 4, 1, 2, 2, 1, 2, 6],
                [1, 1, 3, 4, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
    ]
}
