// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch15 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 281,
            rows: [
                [2, 2, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 3],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [5, 5, nil, nil, nil, nil, 5, 2],
                [2, 2, 2, 2, 2, 4, 4],
                [nil, 4, 4, 4, 4, 4, 4, nil],
                [nil, 4, nil, 4, nil, 4, nil],
                [nil, 3, 3, 3, 3, 3, 3, nil],
                [nil, 3, nil, 4, nil, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 282,
            rows: [
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, 3, 1, 5, 5, 5, 2, nil],
                [1, 1, 1, 2, 2, 2, 4],
                [nil, 4, 4, 1, 1, 1, 1, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 2, 3, 3, 1, 1, 1, nil],
                [nil, nil, nil, 7, nil, nil, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, 1, 1, 6, 6, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 283,
            rows: [
                [nil, 1, 3, nil, 3, 3, nil, nil],
                [1, nil, 1, 1, nil, 2, nil],
                [2, nil, nil, nil, nil, nil, 2, nil],
                [2, 2, 2, nil, nil, 4, 4],
                [4, nil, nil, nil, nil, nil, 4, nil],
                [4, 1, 3, nil, nil, 3, 3],
                [nil, 3, 6, 6, 1, 5, 5, 1],
                [nil, 1, 1, nil, nil, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, 1],
                [nil, 1, 7, nil, nil, 1, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 284,
            rows: [
                [2, 1, 1, 1, 2, 2, 2, 2],
                [2, nil, nil, nil, nil, nil, 3],
                [3, nil, nil, 3, 3, 1, 1, 1],
                [1, nil, nil, nil, 1, 1, 1],
                [1, nil, nil, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, 1, 2, 2],
                [2, nil, nil, nil, nil, nil, 4, 6],
                [6, 6, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, 5, 5],
                [5, 2, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, nil, nil, nil, nil],
                [2, 1, 1, 1, nil, nil, nil],
                [1, 4, 4, 4, nil, nil, nil, nil],
                [4, 4, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 285,
            rows: [
                [nil, nil, 4, 4, nil, nil, nil, nil],
                [nil, 4, 4, 4, nil, nil, nil],
                [nil, 3, 3, 4, 4, 1, nil, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 1, 5, 3, 3, 3, nil, nil],
                [3, 3, 3, 5, 5, 1, 1],
                [1, 1, 2, 2, 2, 6, 2, 2],
                [2, 2, 2, 2, 2, 2, 3],
                [1, 2, 2, 2, 2, 2, 3, 3],
                [3, 1, 1, 1, 1, 1, 7],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 286,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 4, 4, nil, nil],
                [nil, 4, nil, 4, nil, 4, nil],
                [nil, nil, 4, 4, 3, 3, nil, nil],
                [nil, 3, nil, 3, nil, 5, nil],
                [5, nil, nil, 2, 2, nil, nil, 1],
                [1, 1, nil, 1, nil, 1, 1],
                [1, nil, nil, 3, 3, nil, nil, 3],
                [3, 3, nil, 3, nil, 2, 2],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 2, 2, 2, 2, 7, 7, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 287,
            rows: [
                [3, 3, nil, nil, nil, nil, nil, nil],
                [3, 3, nil, nil, nil, nil, nil],
                [3, 3, 3, nil, nil, nil, nil, nil],
                [4, 4, 4, nil, nil, nil, nil],
                [4, 5, 5, nil, nil, nil, nil, nil],
                [5, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [2, 2, 2, 2, nil, nil, nil],
                [2, 2, 2, 2, nil, nil, nil, nil],
                [2, 2, 2, 2, nil, nil, nil],
                [1, 1, 1, 1, 1, nil, nil, nil],
                [2, 2, 2, 2, 2, nil, nil],
                [1, 1, 1, 1, 1, nil, nil, nil],
                [5, 5, 5, 5, 4, nil, nil],
                [4, 6, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 288,
            rows: [
                [nil, nil, nil, 3, 3, 3, 3, nil],
                [3, 3, 1, nil, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [3, nil, nil, nil, 3, 3, 3, 3],
                [3, nil, nil, 3, 3, 3, 3],
                [1, nil, nil, nil, 1, 1, 1, 1],
                [1, nil, nil, 1, 1, 1, 4],
                [4, nil, nil, nil, 4, 4, 5, 5],
                [5, 5, nil, nil, nil, nil, nil],
                [5, nil, nil, nil, 2, 2, 2, 2],
                [2, 2, nil, nil, nil, nil, nil],
                [2, 4, 4, nil, nil, nil, nil, nil],
                [6, 4, 4, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 289,
            rows: [
                [2, 1, 2, 2, 2, 2, 2, 2],
                [2, 2, 2, 1, 1, 1, 1],
                [1, 1, 3, 3, 3, 4, 1, 1],
                [4, 4, 4, 1, 1, 1, 1],
                [1, 1, 1, 3, 3, 6, 3, 6],
                [6, 5, 5, 5, 7, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 290,
            rows: [
                [1, 1, 1, nil, nil, 3, 3, 3],
                [nil, nil, 3, nil, 3, nil, nil],
                [nil, nil, 3, 3, 3, 6, nil, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, 1, 5, 5, 5, nil, nil],
                [nil, nil, 5, 5, 1, nil, nil],
                [nil, nil, 1, 1, 1, 4, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, 4, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, 1, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 291,
            rows: [
                [nil, nil, 1, 1, 4, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 4, nil, 3, 3, nil, 3],
                [3, 3, nil, 3, 3, nil, 3],
                [nil, 3, 3, 1, 1, 1, 1, nil],
                [1, 1, 1, 2, 1, 7, nil],
                [nil, nil, 2, 2, nil, 5, 3, nil],
                [nil, 6, 5, nil, 5, 5, nil],
                [nil, nil, nil, 5, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, 2, 3, 2, 2, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 292,
            rows: [
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, 1, 1, 1, 5, 5, 3, nil],
                [nil, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, 3, 3, 3, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, 2, 4, 4, 4, 4, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [5, nil, nil, nil, nil, nil, nil],
                [nil, 5, 2, 6, 7, 7, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 293,
            rows: [
                [nil, nil, 4, nil, nil, nil, nil, nil],
                [nil, 4, 1, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, 1, 3, nil, nil, nil],
                [7, 2, 2, 2, 2, 2, 3, nil],
                [3, 3, 3, 3, 3, 3, nil],
                [3, 3, 6, 2, 2, 2, 2, nil],
                [2, 1, 1, 1, 1, 1, nil],
                [2, 2, 2, 5, 2, 2, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 4, 4, 4, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 294,
            rows: [
                [4, nil, 1, 1, 1, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 1, 1, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, 4, nil, 1, nil, 1],
                [1, nil, 5, nil, 5, nil, 5],
                [nil, 4, nil, 4, nil, 4, nil, 4],
                [4, nil, 4, nil, 4, nil, 1],
                [nil, 1, nil, 2, nil, 2, nil, 3],
                [3, nil, 3, nil, 3, nil, 6],
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [3, nil, 2, nil, 6, nil, 2],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 295,
            rows: [
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 3, nil, nil],
                [nil, nil, 3, 3, 3, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 4, 4, nil, nil],
                [nil, nil, 4, 6, 6, 5, nil, nil],
                [nil, nil, 5, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, 5, 3, 7, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 296,
            rows: [
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, 6, nil, nil],
                [nil, 6, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 3, 3, nil],
                [nil, 3, 3, 3, 3, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 4, 4, 3, 2, 2, nil],
                [nil, 2, 2, 2, 4, 4, 4, nil],
                [nil, 4, 7, 7, 5, 6, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 297,
            rows: [
                [nil, nil, nil, nil, 1, 1, 1, nil],
                [nil, nil, 1, 1, 4, 4, 4],
                [nil, nil, 4, 4, 4, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, 1, 3, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [2, 2, 2, 5, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [1, 1, 3, 3, 5, nil, nil],
                [5, 5, 3, 3, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 3, 3, 6, 6, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 298,
            rows: [
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [1, 2, nil, nil, nil, nil, 2, 1],
                [4, nil, nil, nil, nil, nil, 4],
                [4, 4, nil, nil, nil, nil, 4, 4],
                [4, nil, nil, nil, nil, nil, 4],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 2],
                [2, 2, 2, 2, 2, 2, 2],
                [nil, 2, 2, 2, 3, 3, 3, nil],
                [nil, 3, nil, 3, nil, 4, nil],
                [nil, 4, 5, 6, 5, 4, 5, nil],
                [nil, 5, nil, 5, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 299,
            rows: [
                [nil, 5, nil, nil, nil, nil, 5, nil],
                [6, nil, nil, 6, nil, nil, 2],
                [2, 2, 2, 2, 2, 2, 2, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 3],
                [3, nil, nil, 3, nil, nil, 3],
                [nil, 3, nil, 4, nil, nil, 4, nil],
                [nil, nil, 4, 4, nil, nil, nil],
                [nil, 1, nil, 7, nil, nil, 1, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 5, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 6, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 300,
            rows: [
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, 4, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [1, 1, 1, 1, 1, 1, 3],
                [nil, 5, 5, 5, 5, 3, 2, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 2, 3, 3, 3, 3, 3, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 7, 6, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, 2, 2, 4, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
    ]
}
