// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch04 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 61,
            rows: [
                [3, nil, nil, 3, nil, 3, nil, 3],
                [3, 3, 1, nil, nil, 1, 5],
                [nil, nil, 5, nil, nil, 1, nil, nil],
                [nil, 2, 2, 2, 2, 2, 2],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, 1],
                [nil, nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1],
                [nil, nil, 1, 1, 1, 6, 6, 1],
                [nil, nil, 1, 5, 5, 5, 5],
                [nil, nil, nil, 4, 1, nil, 1, 1],
                [nil, nil, nil, 1, nil, 2, 4],
                [nil, nil, nil, 4, 1, nil, 1, 1],
                [nil, nil, nil, 1, nil, 4, 1],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 62,
            rows: [
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 3, nil, 3, nil, 2, nil],
                [2, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, nil, 2, 2, 2, 2, 2, nil],
                [nil, 1, 1, 4, 4, 4, nil],
                [nil, 3, 3, 1, 1, 1, 1, nil],
                [1, 1, 1, 1, 1, 2, 2],
                [nil, 1, 1, 1, 2, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, 1, 1, 3, nil],
                [nil, nil, 3, 3, 6, nil, nil],
                [nil, nil, 6, 5, 5, nil, nil, nil],
                [nil, nil, 5, 2, 4, nil, nil],
                [nil, nil, nil, 5, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 63,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 6, 6, 4, nil],
                [nil, 4, nil, 4, 1, nil, 1, nil],
                [2, 2, 2, 2, 5, 5, 5],
                [nil, 4, nil, 2, 2, nil, 4, nil],
                [4, 4, 4, 4, 4, 4, 2],
                [nil, 7, nil, 2, 2, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, 2, 2, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 64,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [2, 2, 5, 4, 4, 4, 4],
                [nil, 4, 4, 1, 1, 1, 1, nil],
                [1, 1, 1, 1, 3, 3, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 6, 6, 6, 6, 6, nil],
                [nil, 1, 3, 1, 1, 5, 5, nil],
                [nil, 1, 1, 1, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 65,
            rows: [
                [2, 2, 1, 1, 3, 3, 3, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [3, nil, nil, 1, 1, 1, 1, 4],
                [4, nil, nil, nil, 2, 7, 1],
                [1, nil, nil, 1, 2, 2, 2, 2],
                [2, nil, nil, nil, 2, 2, 2],
                [2, nil, nil, nil, nil, nil, 2, 5],
                [5, 1, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [5, 5, 6, 6, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 66,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [5, 5, 5, 5, 5, 2, 2],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 6, 6, 2, 3],
                [2, 4, 4, 2, 2, 2, 2, 2],
                [2, 4, 4, 3, 3, 3, 3],
                [2, 2, 1, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 67,
            rows: [
                [nil, 5, 5, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 2, 2, 4, 4],
                [4, nil, nil, nil, nil, nil, 3],
                [3, nil, 3, 3, 3, 2, nil, 2],
                [2, nil, 2, 3, 3, nil, 3],
                [3, nil, 2, 2, 2, 2, nil, 2],
                [6, nil, nil, nil, nil, nil, 6],
                [6, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 68,
            rows: [
                [1, nil, nil, nil, 2, 2, nil, nil],
                [2, nil, nil, 2, 1, 1, nil],
                [1, nil, nil, 1, 1, 1, 1, nil],
                [1, nil, 1, 1, 1, 1, 1],
                [1, nil, nil, 1, 1, 1, 1, nil],
                [1, nil, 1, 1, 1, 1, 1],
                [1, nil, nil, 2, 1, 1, 1, nil],
                [1, nil, nil, 1, 1, 3, nil],
                [3, nil, nil, 2, 2, 2, 2, nil],
                [2, nil, nil, 2, 2, 3, nil],
                [3, nil, nil, nil, 3, 1, nil, nil],
                [nil, nil, nil, 1, 5, 5, nil],
                [5, nil, nil, nil, 5, 3, nil, nil],
                [nil, nil, nil, 3, 4, 4, nil],
                [nil, nil, nil, 4, 2, 6, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 69,
            rows: [
                [3, nil, nil, nil, 3, nil, nil, 3],
                [3, 3, nil, nil, 3, nil, 3],
                [nil, nil, 3, nil, 4, nil, 4, nil],
                [2, nil, 2, 2, nil, 2, nil],
                [nil, nil, 2, nil, 2, nil, 1, nil],
                [1, nil, 2, 2, nil, 2, nil],
                [2, 1, 1, 1, 1, 1, nil, 1],
                [nil, nil, 1, 3, 3, 3, 1],
                [1, 1, 1, 1, 1, 4, nil, 4],
                [nil, nil, 4, 4, 4, 1, 2],
                [nil, 2, 1, nil, nil, 1, nil, nil],
                [1, 5, nil, nil, nil, 5, 5],
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [2, 2, nil, nil, nil, 2, 6],
                [5, nil, nil, nil, nil, nil, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 70,
            rows: [
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, 2, nil, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, nil, 2, 1, nil],
                [nil, 3, 3, 3, 3, 3, 3, nil],
                [nil, 1, 4, nil, 4, 4, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 7, nil, nil, nil],
                [nil, nil, nil, 7, nil, nil, nil],
                [1, nil, nil, 1, 1, nil, nil, 5],
                [1, nil, nil, 1, nil, nil, 5],
                [5, nil, nil, 1, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 71,
            rows: [
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 4, 4, 4, 4, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 5, 5, nil, nil],
                [nil, nil, 5, 5, 5, 5, nil, nil],
                [nil, nil, 5, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, 6, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 2, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 3, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 72,
            rows: [
                [4, nil, nil, 4, 4, nil, nil, 4],
                [4, 1, 2, 2, 3, 3, 3],
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [4, nil, 4, 4, 4, nil, 4],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, 1, 3, 3, nil, nil],
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [nil, nil, 3, 3, 5, nil, nil],
                [nil, 5, 2, 2, 5, 5, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 6, 2, 2, 2, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 73,
            rows: [
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, 1, 2, nil, nil, nil],
                [nil, nil, 2, 2, nil, nil, nil, nil],
                [nil, 1, 1, 2, nil, nil, nil],
                [5, 1, 1, 1, 2, 2, 2, nil],
                [2, 2, 2, 2, 2, 2, nil],
                [2, 2, 2, 2, 2, 2, 3, nil],
                [3, 3, 3, 1, 1, 1, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, 3, 3, 3, 3, 3, 7, 7],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 74,
            rows: [
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [2, 2, 2, 2, 2, 2, 2],
                [2, 2, 2, 6, 6, 3, 3, 3],
                [3, 1, 1, 5, 5, 5, 5],
                [1, 1, 1, 1, 1, 1, 1, 4],
                [1, 1, 1, 1, 6, 1, 4],
                [nil, nil, nil, nil, 1, 1, 1, 4],
                [nil, nil, nil, nil, 4, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 75,
            rows: [
                [nil, 3, 3, nil, 6, 6, 6, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 1, 3, 3, nil, 3, 5, nil],
                [5, nil, nil, nil, nil, nil, 5],
                [nil, 5, 1, 1, nil, 1, 1, nil],
                [7, nil, nil, nil, nil, nil, 7],
                [nil, 2, 2, nil, 2, 2, 2, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 2, 2, nil, 2, 2, 4, nil],
                [4, nil, nil, nil, nil, nil, 4],
                [nil, 4, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 76,
            rows: [
                [nil, nil, 2, 2, 3, 3, nil, nil],
                [nil, 2, 7, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 2, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, 3, 3, 3, 3, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, nil, 2, 2, 1, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 7, 4, 2, 2, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, 2, 4, 4, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 4, 4, 4, 6, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 77,
            rows: [
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, 1, 1],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [1, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, 3, 3, nil, 3, nil],
                [5, 5, nil, nil, nil, 5, nil],
                [2, nil, 1, 1, 4, 4, nil, 4],
                [7, nil, nil, nil, nil, nil, 2],
                [2, nil, 2, 2, 2, 1, nil, 1],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 2, 2, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 3, 2, 2, 7, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 78,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil],
                [nil, nil, nil, 2, 2, 2, nil, nil],
                [nil, 1, 4, 4, 4, nil, nil],
                [nil, nil, nil, 4, 4, 1, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [1, 1, 1, 3, 3, 3, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 6, 6, 7, 1, 1, nil, nil],
                [nil, 1, 1, 5, 5, 5, nil],
                [nil, nil, 3, 3, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 79,
            rows: [
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [1, nil, 1, 5, 5, nil, 5],
                [5, nil, nil, nil, nil, nil, nil, 3],
                [3, nil, 3, 3, 3, nil, 3],
                [3, 1, 1, 1, 1, 1, 1, 1],
                [3, 3, 1, nil, 1, 1, 1],
                [1, 4, 4, 1, 1, 1, 1, 1],
                [1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, 1, 1, 4, nil, nil],
                [nil, 4, 4, nil, nil, 4, 4, nil],
                [nil, nil, 4, 6, 6, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 80,
            rows: [
                [nil, nil, nil, nil, 1, 1, 1, nil],
                [nil, nil, 1, 1, 2, 2, 2],
                [nil, nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 3, 3, nil],
                [nil, nil, 3, 3, 3, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 5, nil, nil],
                [5, 5, 5, 5, 5, nil, nil],
                [nil, 4, 4, 4, 3, 3, nil, nil],
                [3, 3, 3, 3, 3, nil, nil],
                [3, 3, 3, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [6, 6, 2, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
    ]
}
