// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch78 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1541,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, 3, 3, nil, nil],
                [nil, nil, 1, 3, 3, 3, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, 2, nil, 1, nil, 4, nil],
                [4, nil, nil, 2, 4, nil, nil, 6],
                [2, 2, nil, 2, nil, 1, 1],
                [2, nil, nil, 1, 3, nil, nil, 3],
                [5, 2, nil, 4, nil, 1, 1],
                [nil, 2, 4, 2, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 2, 2, 1, 4, 1, 1, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1542,
            rows: [
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [1, nil, nil, 2, nil, nil, 3],
                [2, 2, 4, 2, 3, 2, 1, 1],
                [2, nil, nil, 5, nil, nil, 5],
                [1, 3, 5, 1, 4, 1, 3, 4],
                [2, nil, nil, 2, nil, nil, 3],
                [nil, 3, nil, 3, nil, nil, 4, nil],
                [nil, nil, 1, 2, nil, nil, nil],
                [nil, 1, nil, 2, nil, nil, 1, nil],
                [nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 3, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1543,
            rows: [
                [nil, nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [1, 1, 3, 4, 6, 2, 5, 5],
                [nil, nil, nil, nil, 1, nil, nil],
                [3, 1, 2, 5, 5, 3, 3, 3],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1544,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 1],
                [6, 1, 2, 2, 1, 5, 5],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, 4, 4, 3, 1, 2, 2],
                [2, nil, nil, nil, nil, nil, nil, 3],
                [3, 1, 3, 1, 3, 3, 1],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1545,
            rows: [
                [2, nil, nil, nil, nil, nil, nil, 2],
                [1, 5, 2, 5, 5, 1, 2],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [2, 2, 1, 3, 3, 1, 2],
                [2, nil, nil, nil, nil, nil, nil, 4],
                [4, 4, 1, 2, 1, 1, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [1, 3, 1, 3, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1546,
            rows: [
                [1, 2, 1, 2, 6, 2, 1, 1],
                [2, 3, 3, 1, 2, 2, 3],
                [3, 3, 1, 3, 3, 3, 4, 4],
                [4, 2, 2, 1, 1, 2, 2],
                [1, 2, 1, 4, 1, 2, 1, 2],
                [1, 3, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1547,
            rows: [
                [nil, 2, 2, 2, 1, 3, 2, nil],
                [nil, 5, 1, 5, 1, 3, nil],
                [nil, nil, 3, 3, 2, 2, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 4, 2, 2, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 1, nil, nil, nil, nil, nil, nil],
                [4, 4, nil, nil, nil, nil, nil],
                [nil, 4, 2, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 2, 6, nil, nil, nil, nil],
                [nil, nil, 1, 2, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1548,
            rows: [
                [4, 1, 1, 1, 2, 2, 1, 1],
                [2, nil, 1, nil, 2, nil, 2],
                [nil, 2, 1, 3, 3, 1, 2, nil],
                [nil, 1, nil, 4, nil, 2, nil],
                [nil, 5, 2, 2, 2, 1, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, 5, 2, 1, 6, 5, nil],
                [3, nil, 1, nil, 4, nil, 2],
                [nil, 5, 1, 2, 5, 1, 1, nil],
                [2, nil, 1, nil, 2, nil, 2],
                [1, 5, 1, 3, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1549,
            rows: [
                [1, 4, nil, 4, 1, nil, 1, 2],
                [1, 1, nil, 3, nil, 3, 3],
                [nil, 3, nil, 6, 1, nil, 2, nil],
                [1, 1, 1, 6, 1, 1, 2],
                [nil, 1, nil, 5, 1, nil, 2, nil],
                [1, 5, 2, 2, 5, 2, 1],
                [nil, 5, nil, 1, 1, nil, 2, nil],
                [1, 2, nil, nil, nil, 2, 1],
                [nil, 2, nil, 2, 5, nil, 1, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [1, 1, 1, nil, nil, 1, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [1, 1, 1, nil, nil, 1, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1550,
            rows: [
                [nil, nil, 2, 1, 2, 2, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 1, 3, 5, 2, nil, nil],
                [nil, nil, 2, 1, 5, nil, nil],
                [nil, nil, 1, 2, 4, 4, nil, nil],
                [nil, nil, 6, 2, 1, nil, nil],
                [nil, nil, 3, 3, 1, 3, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 1, 2, 2, 2, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 1, 3, 1, 3, nil, nil],
                [nil, nil, 1, 1, 4, nil, nil],
                [nil, nil, 3, 1, 3, 4, nil, nil],
                [nil, nil, 3, 4, 2, nil, nil],
                [nil, nil, 1, 3, 4, 1, nil, nil],
                [nil, nil, 1, 2, 5, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1551,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, 3, 3, 3, 1, nil, nil, 3],
                [3, 4, 4, 6, 1, nil, 2],
                [nil, 2, 1, 5, 1, nil, nil, 1],
                [1, 1, 5, 5, 2, nil, 1],
                [3, 2, 1, 2, 1, 2, 1, nil],
                [1, 2, 1, 3, 3, nil, 3],
                [3, 2, 1, 2, 2, 1, 1, nil],
                [2, 2, 2, 1, 1, nil, 2],
                [nil, 2, 2, 2, 4, nil, nil, 2],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, 2, 1, nil, nil, 4],
                [nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1552,
            rows: [
                [nil, nil, 1, nil, nil, 4, nil, nil],
                [1, 2, 1, 2, 2, 2, 1],
                [1, 4, 4, 1, 3, 2, 3, 2],
                [3, 6, nil, 6, nil, 6, 3],
                [1, 1, 1, 3, 3, 3, 1, 2],
                [2, 2, nil, 1, nil, 1, 3],
                [2, 2, nil, 1, 4, nil, 2, 2],
                [2, nil, nil, 1, nil, nil, 1],
                [2, 2, nil, 1, 3, nil, 2, 2],
                [1, nil, nil, 2, nil, nil, 2],
                [2, 1, 3, nil, nil, 3, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 2, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1553,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 5, nil, 2, 1, nil],
                [nil, 4, 1, 3, 3, 1, 1, nil],
                [nil, 4, 4, nil, 4, 3, nil],
                [nil, 1, 2, 6, 3, 1, 5, nil],
                [nil, 5, 1, nil, 4, 4, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [1, nil, nil, 2, 1, nil, nil, 1],
                [2, nil, nil, 1, nil, nil, 1],
                [2, nil, nil, 2, 1, nil, nil, 1],
                [1, nil, nil, 3, nil, nil, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1554,
            rows: [
                [2, nil, nil, nil, 1, 2, nil, nil],
                [4, nil, nil, 1, 3, 3, nil],
                [3, nil, nil, 3, 3, 3, 3, nil],
                [1, nil, 2, 2, 1, 4, 4],
                [1, nil, nil, 2, 4, 1, 1, nil],
                [1, nil, 1, 2, 1, 4, 4],
                [1, nil, nil, 3, 1, 1, 3, nil],
                [3, nil, nil, 1, 3, 3, nil],
                [3, nil, nil, 2, 6, 4, 2, nil],
                [1, nil, nil, 2, 1, 4, nil],
                [2, nil, nil, nil, 2, 1, nil, nil],
                [nil, nil, nil, 2, 1, 1, nil],
                [4, nil, nil, nil, 2, 1, nil, nil],
                [nil, nil, nil, 5, 2, 3, nil],
                [nil, nil, nil, 2, 2, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1555,
            rows: [
                [nil, 3, 2, nil, nil, 1, 1, nil],
                [5, nil, 5, nil, 1, nil, 2],
                [2, nil, nil, 4, 4, nil, nil, 1],
                [2, nil, nil, nil, nil, nil, 2],
                [1, nil, nil, 3, 3, nil, nil, 4],
                [4, nil, nil, nil, nil, nil, 2],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 6, nil],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 4, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, 5, nil, 1, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 3, nil, 2, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1556,
            rows: [
                [3, 3, 3, 2, 3, 1, 1, 2],
                [1, 1, 1, 3, 2, 1, 2],
                [3, 4, 4, 4, 1, 1, 3, 3],
                [2, 1, 2, 1, 1, 3, 4],
                [1, 2, 1, 3, 1, 5, 2, 1],
                [2, 1, 1, 4, 6, 1, 3],
                [2, 1, 2, 1, 2, 2, 1, 1],
                [1, 2, 1, 2, 2, 4, 1],
                [1, 1, 1, 1, 4, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1557,
            rows: [
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil],
                [nil, nil, nil, nil, 3, 3, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, 1, 4, nil],
                [nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, nil, nil, 2, 3, nil],
                [2, 3, nil, nil, 3, 3, nil],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [4, 1, nil, nil, 5, 2, nil],
                [nil, 1, 2, nil, nil, 2, 5, nil],
                [1, 1, nil, nil, 4, 2, nil],
                [nil, 3, 5, nil, nil, 4, 2, nil],
                [2, 4, nil, nil, 4, 4, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1558,
            rows: [
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [1, 1, 1, 2, nil, nil, nil],
                [2, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 4, 4, 1, 1],
                [5, nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, nil, 2, 4, 3, 2],
                [1, nil, nil, nil, 1, nil, nil, 2],
                [1, 4, 2, 1, nil, nil, nil],
                [3, nil, nil, nil, 3, nil, nil, 3],
                [1, 1, 2, 3, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil, 1],
                [nil, nil, nil, 3, 2, 2, 1],
                [nil, nil, nil, 2, nil, nil, nil, 3],
                [nil, nil, nil, 2, 1, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1559,
            rows: [
                [nil, 1, nil, 3, nil, 2, nil, 2],
                [2, 1, nil, 5, 1, nil, 1],
                [1, nil, 2, nil, 2, nil, 2, nil],
                [4, 4, nil, 1, 1, nil, 1],
                [4, nil, 2, nil, 1, nil, 1, nil],
                [1, 2, nil, 2, 1, nil, 2],
                [nil, 3, nil, 1, nil, 2, nil, 2],
                [4, 5, nil, 5, 4, nil, 1],
                [nil, 1, nil, 3, nil, 3, nil, 2],
                [3, 2, nil, 1, 4, nil, 2],
                [1, nil, 3, nil, 2, nil, 2, nil],
                [1, 1, nil, 3, 1, nil, 3],
                [1, nil, 3, nil, 1, nil, 2, nil],
                [1, 1, nil, 2, 2, nil, 3],
                [nil, 1, nil, 3, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1560,
            rows: [
                [nil, 1, nil, nil, 1, 2, 2, nil],
                [1, nil, nil, 1, 3, 3, nil],
                [1, nil, nil, 2, 1, 5, nil, nil],
                [2, nil, 1, 2, 2, nil, nil],
                [3, nil, nil, 1, 2, 3, nil, nil],
                [3, nil, 4, 3, 6, nil, nil],
                [4, nil, nil, 4, 1, 2, nil, nil],
                [2, nil, 1, 1, 1, 6, nil],
                [2, nil, nil, 3, 2, 1, nil, nil],
                [1, nil, 3, 4, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
    ]
}
