// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch101 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2001,
            rows: [
                [nil, 2, nil, 2, nil, 1, nil, 1],
                [3, 3, nil, 4, 6, nil, 2],
                [2, nil, 1, nil, 3, nil, 3, nil],
                [3, 2, nil, 3, 4, nil, 1],
                [1, nil, 2, nil, 1, nil, 3, nil],
                [5, 2, nil, 1, 3, nil, 2],
                [nil, 1, nil, 2, nil, 1, nil, 2],
                [1, 1, nil, 1, 2, nil, 2],
                [nil, 2, nil, 3, nil, 3, nil, 1],
                [5, 2, nil, 1, 3, nil, 1],
                [1, nil, 1, nil, 3, nil, 1, nil],
                [3, 1, nil, 3, 1, nil, 2],
                [1, nil, 3, nil, 1, nil, 3, nil],
                [2, 2, nil, 1, 3, nil, 1],
                [nil, 1, nil, 3, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2002,
            rows: [
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [nil, 1, 4, 1, 1, 4, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 6, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 5, 1, 4, 4, 4, 1, 2],
                [nil, 5, nil, nil, nil, nil, 3],
                [nil, 2, 1, 2, 1, 1, 2, 2],
                [nil, 1, nil, nil, nil, nil, 1],
                [nil, nil, nil, 1, 2, 1, 1, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, 2, 3, 2, nil],
                [nil, 3, 4, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2003,
            rows: [
                [1, 3, 1, 2, 4, 1, 1, 2],
                [1, 2, 3, 3, 1, 3, 6],
                [1, 2, 2, 2, 1, 4, 1, 2],
                [1, 5, 1, 3, 3, 3, 3],
                [3, 1, 1, 2, 1, 2, 1, 7],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2004,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 4, 2, nil, nil, nil, nil],
                [2, 5, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 2, 3, nil],
                [1, 2, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, 4, 5, nil],
                [nil, nil, nil, 3, 2, nil, 1, 2],
                [nil, 1, 2, nil, nil, nil, nil],
                [nil, nil, nil, 5, 2, nil, 1, 1],
                [nil, 2, 1, nil, nil, nil, nil],
                [2, 5, nil, 1, 7, nil, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil],
                [1, 2, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2005,
            rows: [
                [nil, 3, 1, nil, 2, 1, nil, nil],
                [1, nil, 1, 1, nil, 2, nil],
                [1, nil, nil, nil, nil, nil, 2, nil],
                [2, 4, 3, nil, nil, 5, 3],
                [3, nil, nil, nil, nil, nil, 3, nil],
                [5, 3, 3, nil, nil, 3, 3],
                [nil, 3, 1, 5, 1, 6, 1, 1],
                [nil, 2, 1, nil, nil, 2, 2],
                [nil, 4, 1, 6, 1, 1, 1, 2],
                [nil, 1, 1, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2006,
            rows: [
                [nil, nil, 5, 4, 2, nil, nil, nil],
                [nil, nil, 6, 5, 5, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 1, nil, 2, nil, 4, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [2, nil, 1, nil, 4, nil, 1, nil],
                [nil, 4, nil, 1, nil, 3, nil],
                [1, nil, 3, nil, 3, nil, 2, nil],
                [nil, 1, nil, 3, nil, 3, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2007,
            rows: [
                [nil, nil, nil, 1, 1, 1, 2, nil],
                [2, 2, 2, nil, nil, nil, 6],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [3, nil, nil, nil, nil, nil, 1],
                [4, nil, nil, nil, 2, 5, 1, 2],
                [4, nil, nil, 4, 3, 1, 1],
                [1, nil, nil, nil, 1, 2, 2, 3],
                [2, nil, nil, 2, 3, 2, 2],
                [3, nil, nil, nil, 1, 1, 1, 1],
                [3, 2, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, 1, 1, 4, 5],
                [5, 3, nil, nil, nil, nil, nil],
                [2, 1, 3, nil, nil, nil, nil, nil],
                [3, 1, 3, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2008,
            rows: [
                [1, 5, 3, 1, 2, 2, 5, 5],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, 2, 2, 1, 3, 1],
                [3, nil, nil, nil, 3, 1, 1],
                [1, nil, nil, 6, 6, 1, 2, 1],
                [1, nil, nil, nil, 2, 1, 2],
                [1, nil, nil, nil, nil, nil, 4, 1],
                [4, 1, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, 1, 3],
                [1, 1, nil, nil, nil, nil, nil],
                [2, 2, 1, 4, nil, nil, nil, nil],
                [1, 1, 1, 4, nil, nil, nil],
                [3, 1, 4, 1, nil, nil, nil, nil],
                [2, 1, 1, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2009,
            rows: [
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, nil, 1, 2, 2, 6, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, 3, 2, 2, 1, nil, nil],
                [nil, nil, 3, nil, 2, nil, nil],
                [2, 3, 1, nil, nil, 5, 3, 1],
                [nil, nil, 2, nil, 3, nil, nil],
                [3, 1, 2, nil, nil, 1, 1, 3],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2010,
            rows: [
                [nil, nil, 3, nil, nil, 3, nil, nil],
                [nil, 4, nil, nil, 4, nil, nil],
                [nil, 1, nil, nil, 1, 1, 3, nil],
                [2, nil, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, 2, 2, 1, nil],
                [1, nil, nil, nil, nil, 1, nil],
                [6, 1, 5, 1, nil, 3, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [1, 6, 3, 1, nil, 2, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2011,
            rows: [
                [2, nil, nil, nil, nil, nil, nil, 2],
                [nil, 6, nil, nil, nil, 6, nil],
                [nil, nil, 1, nil, nil, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 2, 1, 4, 4, nil, nil],
                [nil, 5, 1, 2, 5, 3, nil],
                [nil, 1, 2, 5, 1, 2, 2, nil],
                [nil, 2, 1, 4, 4, 1, nil],
                [nil, nil, 1, 4, 2, 3, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 1, 3, 2, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2012,
            rows: [
                [nil, 1, 2, 2, 1, 3, 1, nil],
                [2, nil, nil, nil, nil, nil, 1],
                [nil, 3, nil, nil, nil, nil, 2, nil],
                [1, 3, 1, 3, 6, 2, 3],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [4, 3, 1, 1, 2, 1, 1],
                [nil, 3, 1, 4, 2, 2, 1, nil],
                [nil, 2, 6, 5, 7, 1, nil],
                [nil, 1, 4, 2, 1, 2, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2013,
            rows: [
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [3, 1, 2, 3, 3, 1, 2, 4],
                [nil, nil, nil, nil, nil, nil, 3],
                [1, 4, 4, 3, 3, 1, 5, 5],
                [nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, 1, 1, 6, 2, nil],
                [nil, nil, nil, nil, nil, nil, 4, nil],
                [nil, 2, 2, 2, 3, 3, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [2, 2, 1, 1, 1, 6, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2014,
            rows: [
                [1, 2, 1, 2, 5, 1, 4, 4],
                [nil, nil, nil, nil, 4, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 6, 2, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [3, 3, 1, 1, 1, 4, 4, 1],
                [nil, nil, nil, nil, 1, nil, nil],
                [2, 2, 2, 2, 1, 1, 1, 3],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 6, 1, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [1, 1, 1, 3, 2, 1, 5, 5],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2015,
            rows: [
                [nil, 4, 4, 3, 1, 5, 5, nil],
                [nil, 5, 1, 3, 2, 2, nil],
                [nil, nil, 1, 1, 1, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 2, 1, 1, 2, 2],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 4, 4, 4, nil, 4],
                [1, nil, 1, 3, 2, nil, 2],
                [1, nil, 4, 4, 3, 3, nil, 1],
                [2, nil, nil, nil, nil, nil, 4],
                [4, 3, 1, 2, 1, 1, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 3, 1, 6, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 1, 2, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2016,
            rows: [
                [nil, nil, 1, nil, nil, 1, 1, nil],
                [nil, 4, 4, nil, nil, 2, 1],
                [2, nil, nil, 2, 2, 3, nil, nil],
                [1, 3, nil, 2, nil, nil, nil],
                [2, nil, nil, 1, 1, 2, nil, nil],
                [4, 4, nil, 1, nil, nil, nil],
                [1, nil, 4, 4, 4, 1, 3, nil],
                [nil, 1, nil, nil, 1, nil, 2],
                [2, nil, 2, 1, 3, 1, 5, nil],
                [nil, 3, nil, nil, 7, nil, 1],
                [nil, 3, 1, nil, nil, nil, 3, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 4, nil, nil, nil, 6, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2017,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 5, 2, 1, nil, nil],
                [nil, nil, 3, 2, 2, nil, nil],
                [nil, nil, 2, 1, 1, 3, nil, nil],
                [nil, nil, 3, 4, 5, nil, nil],
                [nil, nil, 5, 3, 2, 2, nil, nil],
                [nil, nil, 5, 1, 3, nil, nil],
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, nil, 1, 3, 3, nil, nil],
                [nil, nil, 1, 1, 2, 1, nil, nil],
                [nil, nil, 6, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2018,
            rows: [
                [nil, 3, nil, 2, nil, 3, nil, 1],
                [3, nil, 1, nil, 2, nil, 2],
                [1, nil, 3, nil, 3, nil, 3, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [2, nil, 1, nil, 4, nil, 4, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, nil],
                [2, nil, 1, nil, 1, nil, nil],
                [nil, 1, nil, 2, nil, 1, nil, nil],
                [3, nil, 5, nil, 3, nil, nil],
                [nil, nil, 1, nil, 6, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, 2, nil, 3, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2019,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 6, 1, 2, nil, nil],
                [nil, nil, 3, 3, 1, 4, nil, nil],
                [nil, 2, 2, 2, 1, 2, nil],
                [nil, nil, 2, 1, 1, 1, nil, nil],
                [nil, 1, 4, 2, 3, 5, nil],
                [nil, 2, 1, 4, 4, 1, 2, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 3, 1, 2, 1, 2, 2, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2020,
            rows: [
                [nil, nil, 1, nil, nil, 3, nil, nil],
                [nil, 2, nil, nil, 3, nil, nil],
                [nil, nil, nil, 1, nil, nil, 4, nil],
                [nil, nil, 4, nil, nil, 4, nil],
                [nil, nil, nil, nil, 2, nil, nil, 2],
                [nil, nil, nil, 2, nil, nil, 3],
                [nil, nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 7, 5, nil, nil],
                [nil, nil, 4, 2, 1, 1, nil, nil],
                [nil, 1, 4, 2, 1, 2, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
    ]
}
