// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch44 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 861,
            rows: [
                [nil, 2, nil, nil, 2, 2, nil, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, nil, nil, 4, 1, 2, nil],
                [nil, nil, 2, nil, 2, 2, nil],
                [nil, 1, 1, nil, 1, nil, 1, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, 1, 3, nil, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 3, nil, 3, 3, nil],
                [nil, nil, nil, nil, nil, 3, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, 5, 5, nil, 3, 3, 3, nil],
                [nil, nil, 3, 5, 5, 5, nil],
                [nil, 5, 2, 2, 2, 2, 1, nil],
                [nil, 1, 6, 6, 4, 4, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 862,
            rows: [
                [1, 1, nil, nil, nil, nil, nil, 3],
                [2, 2, nil, nil, 2, nil, nil],
                [1, nil, nil, nil, 1, 1, nil, 1],
                [nil, nil, nil, nil, nil, 5, nil],
                [nil, 5, nil, nil, 5, 1, 1, 3],
                [3, 3, 3, 3, 1, 1, 1],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [2, 2, 2, 2, 2, 2, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 4, 4, 6, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 4, 4, 4, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 863,
            rows: [
                [nil, 1, nil, nil, nil, 1, nil, 1],
                [nil, nil, nil, 1, nil, 6, 6],
                [6, 6, 1, nil, 1, 1, nil, 1],
                [1, 1, 1, nil, 3, 3, nil],
                [nil, nil, nil, 4, nil, 4, nil, 4],
                [nil, nil, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, 1, 5],
                [nil, 5, 3, 3, nil, 3, 3, 2],
                [2, 2, nil, nil, nil, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, 2, nil, 2, 2, nil],
                [2, nil, 2, nil, nil, 2, 2, nil],
                [nil, 2, nil, nil, nil, 5, 5],
                [nil, nil, 5, nil, 1, 1, nil, nil],
                [nil, nil, nil, 2, 1, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 864,
            rows: [
                [nil, nil, nil, nil, 2, 1, 1, nil],
                [nil, 1, nil, nil, 2, nil, nil],
                [nil, 2, 2, 2, 2, nil, 2, nil],
                [nil, 2, nil, 5, 5, 5, nil],
                [nil, 1, nil, 1, nil, nil, nil, nil],
                [nil, 4, nil, 4, 4, 4, nil],
                [nil, 4, nil, nil, nil, 1, 1, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 3, nil, 3, 3, nil, nil],
                [nil, 6, 6, 6, 1, 1, nil],
                [nil, 1, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 3, 3, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 865,
            rows: [
                [2, nil, nil, 4, 4, 4, nil, nil],
                [4, nil, 4, nil, nil, nil, 4],
                [4, nil, 4, nil, 4, nil, nil, 1],
                [1, 1, 1, nil, 1, 1, nil],
                [nil, 1, 1, 1, nil, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [1, 1, 5, nil, 5, 2, nil, nil],
                [nil, nil, nil, 2, nil, 2, 2],
                [2, nil, 1, 1, 1, 1, 1, nil],
                [2, 2, 2, nil, nil, 2, nil],
                [nil, 3, nil, 3, nil, 1, nil, 1],
                [nil, nil, nil, 1, 1, 1, 1],
                [1, nil, 1, 6, nil, nil, nil, nil],
                [6, nil, 3, 3, 3, nil, nil],
                [nil, nil, nil, 3, 3, nil, 3, nil],
                [nil, nil, 3, nil, 3, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 866,
            rows: [
                [3, 3, 3, 3, nil, 3, 5, nil],
                [nil, 5, 1, nil, 1, nil, nil],
                [nil, nil, 6, 6, 6, nil, nil, nil],
                [2, 2, 2, 2, nil, 1, 1],
                [1, nil, nil, 1, 1, nil, 1, nil],
                [1, 1, 1, 1, nil, 1, 1],
                [nil, 1, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 1, nil, 2, nil, 2],
                [nil, nil, nil, 2, 3, 3, 1],
                [nil, nil, 1, nil, nil, 1, 1, nil],
                [1, 5, nil, 5, 1, 2, 2],
                [2, nil, nil, 1, 1, nil, nil, 2],
                [nil, nil, 1, nil, nil, 1, 4],
                [nil, 4, 5, 1, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 867,
            rows: [
                [nil, nil, 5, nil, 5, 5, nil, nil],
                [nil, 5, nil, 5, nil, nil, 1],
                [2, nil, 2, nil, nil, 2, nil, 2],
                [2, 2, nil, nil, 2, nil, 2],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [nil, 6, nil, nil, nil, nil, 6],
                [6, 1, 1, nil, nil, 1, 1, 1],
                [1, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [3, 3, 3, 3, nil, 3, nil],
                [3, nil, 1, 1, nil, nil, 1, 1],
                [1, nil, nil, 3, 3, 3, nil],
                [nil, 3, 3, 3, nil, 4, nil, 4],
                [1, 1, 1, 1, 1, 4, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 868,
            rows: [
                [nil, 1, nil, 1, nil, nil, nil, 1],
                [6, 6, nil, nil, nil, nil, 2],
                [nil, 2, 2, 2, nil, 2, nil, 2],
                [2, nil, nil, nil, 2, nil, 2],
                [3, 1, nil, 1, 1, nil, 1, 6],
                [2, nil, 2, 2, 2, 2, 2],
                [2, 2, nil, 2, 2, 2, 1, 1],
                [nil, nil, 1, nil, 2, nil, 2],
                [2, 2, 2, 6, 1, 1, 1, nil],
                [4, 4, 1, 1, nil, 1, nil],
                [1, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
                [1, nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, 1, 4, nil, 4, 1],
                [1, nil, nil, 1, 4, 3, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 869,
            rows: [
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, 5, nil, 5, nil],
                [nil, 5, 2, 2, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, 2, 2, 2, nil, nil, 2, nil],
                [nil, 2, 1, nil, nil, 1, nil],
                [nil, 3, 6, 6, 6, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, 2, 2, 2, nil, nil, nil],
                [nil, nil, nil, 2, 2, 3, nil, nil],
                [nil, nil, 1, 1, nil, 1, nil],
                [nil, 3, 3, 1, 1, 3, 1, nil],
                [nil, 1, 1, 4, 4, 1, nil],
                [nil, 1, 1, 1, 4, 4, 4, nil],
                [nil, 3, 3, 4, 4, 4, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 870,
            rows: [
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [1, 3, 3, nil, nil, nil, 3],
                [3, nil, 3, 3, 3, 3, nil, 3],
                [nil, 3, nil, 3, 3, nil, 1],
                [nil, nil, 1, 1, nil, nil, 4, nil],
                [nil, 4, 4, nil, 4, 4, nil],
                [1, nil, nil, nil, nil, nil, 2, 2],
                [nil, 2, 2, nil, nil, nil, nil],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, nil, 2, 1, nil, nil, 1],
                [nil, nil, 6, nil, 6, nil, 5, 5],
                [nil, nil, nil, 4, nil, 4, 5],
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 871,
            rows: [
                [nil, nil, nil, 1, 2, 2, 2, nil],
                [nil, nil, 2, nil, nil, nil, 2],
                [2, nil, 2, nil, nil, 2, 2, 3],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, nil, 3, nil, 3],
                [nil, 3, nil, 1, nil, 6, 1],
                [5, nil, 5, 5, nil, nil, 4, 4],
                [nil, 4, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil, 1],
                [nil, 1, nil, 1, 1, 2, nil],
                [nil, 2, nil, nil, 2, 2, nil, nil],
                [nil, nil, nil, 2, nil, 2, nil],
                [nil, nil, nil, nil, 2, 1, nil, 1],
                [1, nil, 1, nil, 1, 1, 1],
                [1, 1, nil, nil, 1, nil, 1, 1],
                [3, 5, 5, 4, 4, 4, 2],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 872,
            rows: [
                [nil, nil, 1, nil, 6, nil, nil, nil],
                [nil, 6, nil, nil, nil, 6, nil],
                [nil, 1, nil, 1, 1, nil, nil, nil],
                [nil, 1, 1, nil, nil, 1, nil],
                [nil, 1, 1, 1, nil, 1, 1, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 2, nil, 2, 2, nil, nil],
                [nil, 1, 1, nil, nil, 1, nil],
                [nil, nil, nil, 1, nil, 2, 2, nil],
                [nil, nil, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 5, 5, 4, nil],
                [nil, 4, 4, 4, 4, 4, nil],
                [nil, 4, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 3, 3, 3, 3, 3, nil],
                [nil, 4, 1, 3, 3, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 873,
            rows: [
                [3, 3, 3, 3, nil, 3, nil, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [3, 2, nil, 2, 2, nil, 2, nil],
                [nil, nil, nil, nil, 2, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [2, 6, nil, 1, nil, nil, 4],
                [nil, 4, nil, 4, 1, 2, 2, 2],
                [2, nil, nil, nil, 2, 2, nil],
                [1, nil, 6, 6, 6, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, nil],
                [1, nil, 1, 1, nil, 1, nil],
                [2, 2, nil, 1, nil, 1, 1, 1],
                [1, nil, 1, nil, nil, nil, 1],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [nil, 1, nil, 1, 1, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 874,
            rows: [
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [2, 6, 6, 2, 2, nil, 2],
                [nil, 2, 3, 1, nil, 1, nil, 1],
                [3, nil, nil, nil, nil, 3, 3],
                [nil, 3, nil, 3, nil, 3, 3, nil],
                [3, nil, 3, nil, nil, nil, 3],
                [3, nil, nil, nil, 3, 2, nil, 2],
                [nil, 2, 2, 2, 1, 1, nil],
                [1, nil, 1, nil, 1, 1, nil, nil],
                [1, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 1, 2, 2, 2, 2],
                [2, 4, 4, 4, nil, 4, 4, 4],
                [5, 5, 1, 5, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 875,
            rows: [
                [2, 2, nil, 2, 2, nil, 2, 5],
                [nil, nil, 5, 3, nil, 3, nil],
                [nil, nil, nil, nil, nil, 3, 3, nil],
                [3, 2, nil, nil, 1, nil, 6],
                [nil, 6, 6, nil, 1, nil, 1, 1],
                [nil, nil, 1, nil, nil, nil, 1],
                [nil, 1, nil, nil, 1, nil, nil, nil],
                [1, 1, 1, 1, nil, 1, 1],
                [1, nil, 1, 1, nil, 1, 1, nil],
                [1, nil, 1, nil, nil, nil, 1],
                [nil, nil, 1, nil, nil, 1, nil, 2],
                [2, 2, nil, 2, 2, 2, nil],
                [2, nil, 2, 3, 3, nil, nil, 3],
                [2, nil, nil, nil, 2, nil, nil],
                [nil, 4, 4, 4, 4, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 876,
            rows: [
                [nil, 1, nil, nil, 1, nil, 1, nil],
                [nil, 1, 1, nil, 1, nil, nil],
                [nil, 1, nil, 1, 1, 1, nil, nil],
                [nil, 2, 2, nil, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil, nil],
                [nil, 2, 2, 5, nil, nil, nil],
                [nil, 6, 6, 6, 6, 2, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, 1, 3, 3, 3, nil, 3, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 4, 4, 4, 4, 2, nil],
                [nil, 2, 2, 2, 2, 2, 3, nil],
                [nil, 3, 3, 3, 3, 3, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 877,
            rows: [
                [nil, 5, nil, nil, 5, 5, 5, nil],
                [nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, nil, 2, 2, nil, 2, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, 2, 2, nil, nil, 2, nil],
                [nil, 2, 2, 6, nil, 6, nil],
                [nil, nil, nil, 6, 6, nil, 1, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 3, 3, nil, 3, nil, nil, nil],
                [nil, 1, 4, nil, 4, 1, nil],
                [nil, 1, 1, 1, 4, 4, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 878,
            rows: [
                [nil, 1, 1, nil, 1, 1, 1, 1],
                [1, 1, 1, 1, 4, 4, 4],
                [nil, 4, nil, nil, 4, nil, 3, 3],
                [nil, 3, nil, nil, nil, nil, nil],
                [3, 3, nil, nil, 3, 3, 2, nil],
                [2, nil, 2, nil, 2, nil, 2],
                [2, nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, 2, 2, 2, nil, 2, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, nil, 1, 5, nil, nil, nil],
                [nil, 5, nil, nil, 5, nil, nil, nil],
                [5, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, 2, 2, nil],
                [nil, 2, 2, 6, 6, 2, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 879,
            rows: [
                [nil, nil, 2, 2, 1, 1, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, 1, 3, 3, 3, nil, 3, nil],
                [nil, 3, nil, nil, nil, nil, nil],
                [nil, 3, 3, 3, 4, nil, 4, nil],
                [nil, 2, 2, nil, 2, 2, nil],
                [nil, nil, 2, 2, 1, nil, 1, nil],
                [nil, 1, 1, 1, 1, 2, nil],
                [nil, 2, 2, nil, nil, 2, nil, nil],
                [nil, 2, nil, 1, nil, nil, nil],
                [nil, 5, 6, nil, nil, 6, 1, nil],
                [nil, nil, 1, 1, nil, 1, nil],
                [nil, 6, 6, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 4, 4, nil],
                [nil, 4, 4, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 880,
            rows: [
                [5, nil, 5, 5, 5, nil, 5, 5],
                [1, 4, nil, nil, nil, 4, nil],
                [4, nil, 4, nil, 4, 2, nil, 2],
                [2, 2, 2, nil, 1, 3, 3],
                [nil, 3, 3, nil, 3, 3, 3, nil],
                [3, nil, nil, nil, 3, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, nil, 1, 2, 2, 2, 2, 1],
                [6, 1, 1, nil, 2, 2, 2],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
    ]
}
