// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch39 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 761,
            rows: [
                [nil, 3, 3, nil, 3, 3, nil, nil],
                [3, nil, 3, 3, 3, 3, 3],
                [3, 3, nil, 3, nil, 6, 6, 5],
                [nil, nil, 5, nil, nil, 5, nil],
                [5, nil, 1, nil, nil, 1, nil, nil],
                [1, 1, nil, nil, 1, 1, 1],
                [nil, nil, 1, nil, nil, nil, nil, 1],
                [nil, nil, nil, 2, 2, 2, nil],
                [2, nil, nil, nil, 2, nil, 2, nil],
                [nil, 2, 2, nil, 2, nil, 2],
                [2, nil, 2, 2, nil, 2, 2, 1],
                [1, 1, nil, 1, 1, 1, 1],
                [1, 4, 4, 4, nil, nil, 2, nil],
                [2, 2, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 762,
            rows: [
                [1, 1, 1, 1, nil, 1, 2, 2],
                [2, 2, nil, 1, 1, 1, 1],
                [1, 1, nil, 1, 1, 1, nil, 1],
                [1, 1, 1, 1, nil, nil, 1],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [1, nil, nil, nil, nil, 1, nil],
                [2, 2, nil, 2, nil, 2, 2, 2],
                [nil, 2, nil, 4, nil, 4, nil],
                [nil, nil, 4, 4, 4, 3, 3, nil],
                [3, nil, nil, 3, 3, 3, 3],
                [3, 3, 3, 3, nil, 2, 6, 6],
                [nil, 6, nil, 6, nil, 4, 4],
                [4, 4, 4, nil, 3, 3, 3, 3],
                [3, nil, 2, 2, 2, nil, 2],
                [nil, 2, 2, 4, nil, 5, 5, 1],
                [1, nil, 1, 1, 3, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 4
        ),
        LevelTemplate(
            levelNumber: 763,
            rows: [
                [4, nil, 4, 4, nil, 4, 6, nil],
                [nil, 6, 6, 1, 3, 3, nil],
                [nil, nil, 3, 3, nil, 3, nil, nil],
                [nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, nil, 2, 2, 2, nil],
                [nil, 2, 5, nil, nil, 5, nil],
                [nil, 5, nil, 4, nil, 4, 4, nil],
                [1, 1, 1, nil, 1, nil, 1],
                [2, nil, nil, nil, nil, 2, 2, 2],
                [nil, 2, 1, nil, 2, 2, nil],
                [2, 1, nil, 1, nil, nil, 1, 1],
                [1, nil, nil, nil, 1, nil, 5],
                [nil, 1, 1, nil, nil, 1, nil, 1],
                [1, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, 1],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 764,
            rows: [
                [1, 1, 1, nil, 2, 2, nil, 2],
                [2, 2, nil, 2, 2, 2, nil],
                [1, 1, 4, nil, nil, 4, nil, nil],
                [2, 2, 2, nil, nil, 2, nil],
                [nil, nil, 1, nil, 1, nil, 1, 1],
                [3, nil, 1, 1, 1, 1, nil],
                [1, 4, 4, 6, nil, 6, nil, 5],
                [5, 4, nil, 4, 4, nil, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, 1, 1, nil, nil],
                [nil, 1, nil, 1, 2, 2, nil],
                [nil, 3, 3, 2, 2, 3, nil, nil],
                [nil, 5, 5, 5, 3, 3, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 765,
            rows: [
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, 1, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [nil, 2, nil, 2, 1, nil, nil],
                [nil, 2, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, 1, 6, 6, nil],
                [nil, 6, 5, 5, nil, 5, nil],
                [nil, nil, 5, nil, 4, 4, nil, nil],
                [nil, nil, nil, 4, 4, 4, nil],
                [nil, 1, nil, 3, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [3, nil, 3, nil, 3, nil, 6],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 766,
            rows: [
                [4, 4, 4, nil, nil, nil, 4, 2],
                [2, 2, nil, 2, 2, 2, nil],
                [2, nil, 2, 1, nil, 1, 1, nil],
                [1, nil, 1, 1, 1, 1, 1],
                [1, nil, 1, 1, 1, 2, 2, 2],
                [nil, 2, 2, nil, 2, 3, 3],
                [nil, nil, nil, nil, 3, 3, 3, nil],
                [5, nil, 5, nil, nil, 5, 5],
                [nil, 1, 1, nil, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, nil],
                [6, 6, nil, nil, nil, nil, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 4, 4, 1, 1, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 767,
            rows: [
                [nil, nil, 2, 2, 2, 2, 2, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, nil, nil, 2, 2, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 1, nil, 1, 1, 1, 1, nil],
                [nil, 1, nil, 2, 2, 2, nil],
                [nil, nil, 2, 4, 4, 4, 4, nil],
                [nil, nil, nil, 4, nil, 4, nil],
                [nil, nil, 4, nil, 1, nil, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil],
                [nil, nil, 3, 3, 4, 4, 3, nil],
                [nil, 3, 3, 3, nil, 3, nil],
                [nil, nil, nil, 3, 3, 3, 3, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, 3, nil, 5, 5, 1, 1, nil],
                [nil, 3, 3, 6, nil, 5, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 768,
            rows: [
                [nil, 2, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, nil, 1, nil, nil],
                [nil, 1, nil, nil, 1, 1, 1, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, 1, nil, nil, 1, nil],
                [nil, 1, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, 1, 1, 5, nil, 5, nil],
                [nil, nil, 4, 2, nil, 2, 2, nil],
                [nil, 2, 2, 5, 5, 5, nil],
                [nil, 6, 3, 4, 2, 2, 2, nil],
                [nil, 2, 2, 2, 4, 4, nil],
                [nil, 4, 4, 4, 4, 3, 3, nil],
                [nil, 3, 3, 3, 1, 5, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 769,
            rows: [
                [nil, 2, 2, 3, 3, 1, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, 2, 2, 2, 2, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil],
                [nil, nil, 2, 2, nil, 4, nil, nil],
                [nil, 4, 2, 2, 2, 2, nil],
                [nil, nil, 2, 2, nil, 2, 2, nil],
                [nil, 2, 2, nil, 2, 2, nil],
                [nil, 3, 3, nil, 6, 6, 1, nil],
                [nil, 4, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, 5, 5, nil],
                [nil, nil, nil, 1, 1, nil, nil],
                [nil, 1, 1, 6, nil, 6, 6, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, nil, 3, 3, nil],
                [nil, 3, nil, 3, 3, 3, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 770,
            rows: [
                [6, nil, nil, nil, 6, 6, nil, 1],
                [1, 1, 3, nil, 3, 2, nil],
                [nil, nil, 2, 2, 2, nil, nil, 2],
                [2, 2, 2, 4, nil, nil, 4],
                [4, nil, nil, 4, nil, nil, nil, nil],
                [nil, 1, nil, nil, 2, nil, 2],
                [nil, 1, nil, nil, 1, nil, 3, nil],
                [3, nil, 5, nil, nil, nil, 5],
                [nil, nil, nil, nil, nil, nil, 5, 5],
                [1, 1, nil, 1, 1, 1, nil],
                [3, nil, 2, nil, 2, nil, nil, 2],
                [nil, nil, 1, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, nil, 3],
                [nil, nil, 1, 3, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 771,
            rows: [
                [nil, 5, 5, 5, 5, nil, nil, nil],
                [nil, 5, 5, 5, nil, 5, 1],
                [2, 2, nil, 2, nil, nil, 2, nil],
                [nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, 2, 2, 2, 6],
                [1, nil, nil, nil, 1, 1, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, nil, 1],
                [nil, 1, 1, 4, 4, nil, 4, 1],
                [1, 1, nil, 1, nil, nil, nil],
                [3, 1, nil, nil, nil, 1, 1, 1],
                [nil, 1, 1, nil, nil, 3, nil],
                [nil, 3, nil, 2, nil, 2, 1, nil],
                [nil, 1, 1, nil, 3, 3, 1],
                [1, 1, 1, 1, 1, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 772,
            rows: [
                [6, 1, nil, nil, 1, 1, nil, 1],
                [1, 1, nil, 1, nil, nil, nil],
                [nil, 5, 6, nil, nil, nil, 1, 1],
                [5, 5, 4, nil, nil, nil, nil],
                [nil, nil, nil, nil, 4, 1, 1, nil],
                [nil, nil, 2, nil, 2, 4, nil],
                [4, 4, nil, 2, nil, 2, nil, 2],
                [nil, nil, 2, 2, nil, nil, nil],
                [nil, 3, nil, 3, 3, 3, nil, nil],
                [nil, 2, 2, 2, 2, 3, 3],
                [3, 3, 2, 2, 2, 2, nil, 2],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, 1, 1, nil, 1, nil, 1, 1],
                [nil, nil, nil, 2, 4, nil, nil],
                [nil, nil, nil, nil, 2, 2, 2, nil],
                [nil, nil, 2, nil, 2, 2, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 773,
            rows: [
                [nil, nil, 1, 6, nil, 4, 4, nil],
                [nil, nil, nil, nil, 4, nil, nil],
                [nil, 4, 2, 2, nil, nil, nil, nil],
                [2, 2, nil, nil, 2, 2, 1],
                [nil, 1, 1, 1, nil, 4, nil, nil],
                [nil, 4, nil, 4, 5, nil, 5],
                [nil, 1, nil, nil, nil, nil, nil, 1],
                [nil, 1, 2, nil, nil, nil, nil],
                [2, 3, nil, nil, nil, nil, 1, nil],
                [1, 1, 1, 1, nil, 1, nil],
                [nil, nil, 1, 1, 1, 1, 1, 1],
                [1, nil, 1, 1, 1, 1, 1],
                [nil, 3, nil, nil, nil, 3, nil, nil],
                [nil, 2, 2, 2, 2, 2, 3],
                [nil, nil, 3, nil, 3, 3, 3, nil],
                [nil, 3, 5, 5, 5, 2, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 774,
            rows: [
                [nil, nil, 3, nil, nil, nil, nil, 3],
                [nil, 3, 3, nil, nil, nil, 3],
                [nil, 2, 2, 2, nil, nil, 1, 1],
                [nil, 1, nil, 1, 1, nil, nil],
                [nil, nil, 1, 2, 2, 2, 2, nil],
                [nil, nil, 2, nil, 2, 1, 1],
                [1, 1, nil, 1, 1, 1, 1, 1],
                [nil, 1, 6, 1, nil, 1, 1],
                [nil, 1, 1, 4, 4, 4, 4, 4],
                [2, 2, 2, 2, 2, 1, 5],
                [5, 5, 1, 4, 4, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 1, 1, 3, 1, 1, 1, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 775,
            rows: [
                [nil, 3, nil, 3, nil, 3, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 3, 3, 3, 1, 1, 1, nil],
                [nil, nil, 4, nil, nil, 1, nil],
                [nil, 1, 1, 1, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, 1, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, 4, nil, 4, nil, 1, nil],
                [nil, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [nil, 1, 6, 4, 4, 4, nil],
                [nil, 5, 5, 5, 2, 2, 2, nil],
                [nil, 2, 1, 1, 2, 2, nil],
                [nil, 2, 2, 1, 1, 2, 2, nil],
                [nil, 2, 6, 6, 4, 4, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 776,
            rows: [
                [3, 3, 3, 3, 3, 3, 3, 3],
                [nil, 1, 2, nil, nil, 2, 2],
                [6, 5, nil, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, 2],
                [nil, 2, 2, nil, 2, 4, 5, 5],
                [nil, 5, 1, 1, 6, nil, nil],
                [1, 2, nil, 2, nil, 2, 2, 1],
                [nil, nil, nil, nil, 1, nil, 1],
                [nil, nil, 1, nil, nil, nil, 1, nil],
                [1, 1, 1, 1, nil, 6, 1],
                [nil, 1, nil, nil, 1, 4, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 777,
            rows: [
                [nil, 2, nil, nil, 2, 2, nil, 2],
                [2, nil, 2, nil, nil, 2, nil],
                [2, nil, 2, nil, nil, 2, 2, nil],
                [nil, 2, 2, 4, nil, 4, nil],
                [nil, 1, nil, 1, 1, 1, 1, 3],
                [3, 3, 3, nil, nil, nil, 4],
                [nil, 4, 4, nil, nil, 4, nil, nil],
                [4, 4, 4, 1, 5, nil, nil],
                [nil, 5, nil, 5, nil, 5, nil, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [3, 3, 3, 1, 6, 6, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 778,
            rows: [
                [nil, nil, 4, nil, 4, nil, nil, nil],
                [nil, 4, nil, nil, nil, 4, nil],
                [nil, 1, nil, 3, 3, nil, nil, nil],
                [nil, 3, 3, nil, nil, 3, nil],
                [nil, 3, 1, 1, nil, 1, 1, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 1, nil, 1, 1, nil, nil],
                [nil, 6, 6, nil, nil, 6, nil],
                [nil, nil, nil, 4, nil, 1, 1, nil],
                [nil, nil, 4, 4, 4, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 2, 2, 2, 1, 2, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 5, 5, 1, nil],
                [nil, 3, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 779,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, 2, nil, 2, nil, 2],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [2, nil, 2, nil, nil, 2, 2],
                [nil, nil, 2, 2, nil, nil, 3, nil],
                [nil, 3, nil, nil, 4, nil, nil],
                [nil, 4, 1, nil, nil, 1, nil, 1],
                [nil, nil, nil, nil, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, nil, 3],
                [3, 3, 3, nil, 3, nil, 3],
                [3, 3, nil, 5, nil, 5, 1, 1],
                [nil, 1, nil, 1, 1, 5, 5],
                [5, 6, 6, 1, 1, 1, 1, 1],
                [1, 1, 1, 4, 4, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 780,
            rows: [
                [nil, 1, nil, nil, nil, 1, 1, nil],
                [2, 2, nil, 1, 1, nil, 1],
                [nil, 1, 4, nil, nil, nil, 4, 4],
                [4, 4, 4, 4, nil, 4, nil],
                [nil, 4, nil, nil, nil, nil, 4, nil],
                [1, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [1, nil, 6, nil, 2, 2, 2],
                [nil, 2, 2, nil, nil, 2, 2, 2],
                [2, nil, 2, nil, 3, nil, 3],
                [3, 3, nil, 3, nil, 3, nil, 3],
                [nil, 3, nil, 1, 1, 1, 1],
                [1, 1, 1, 1, nil, 5, 5, 1],
                [6, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
    ]
}
