// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch70 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1381,
            rows: [
                [1, 1, 3, 1, 3, 3, 1, 1],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 4, 1, 2, 2, 6, 3, 1],
                [nil, 4, nil, nil, nil, nil, nil],
                [nil, 2, 1, 1, 4, 2, 1, 2],
                [nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 3, 3, 2, 4],
                [nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, 4, 1, 2, 1, 2, 1],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, 4, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 5, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1382,
            rows: [
                [2, 7, 1, nil, nil, 5, 4, 4],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, 1, 4, 4, 2, nil, nil],
                [nil, 1, nil, 1, nil, 4, nil],
                [nil, nil, 4, 5, 2, 1, nil, nil],
                [nil, 1, nil, 3, nil, 3, nil],
                [nil, nil, 2, 2, 1, 1, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, 4, 1, 2, 4, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, 1, 2, nil, nil, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1383,
            rows: [
                [1, 2, nil, nil, nil, nil, 2, 2],
                [1, nil, nil, nil, nil, nil, 4],
                [1, nil, nil, nil, nil, nil, nil, 3],
                [1, nil, 1, 4, 6, nil, 1],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [4, nil, 1, 3, 4, nil, 2],
                [2, 1, 1, 3, 1, 1, 4, 5],
                [4, 3, 3, nil, 4, 1, 4],
                [1, 4, 4, 1, 2, 2, 1, 2],
                [1, 2, 1, nil, 4, 1, 3],
                [nil, 3, 1, nil, nil, 5, 5, nil],
                [nil, nil, 1, 3, 2, nil, nil],
                [nil, 1, 1, nil, nil, 2, 2, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1384,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, 4, 4, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 5, 3, 3, 5, nil, nil],
                [nil, nil, 6, 2, 1, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, nil, 2, 1, 4, nil, nil],
                [nil, nil, 5, 1, 2, 2, nil, nil],
                [nil, nil, 2, 2, 3, nil, nil],
                [nil, nil, 1, 5, 3, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1385,
            rows: [
                [nil, 1, 1, nil, 1, 5, 2, nil],
                [2, nil, nil, nil, nil, nil, 4],
                [nil, 1, 5, 1, nil, 3, 1, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, 1, 6, 5, nil, 2, 2, nil],
                [2, nil, nil, nil, nil, nil, 1],
                [nil, 6, 3, nil, 1, 1, 3, nil],
                [4, nil, nil, nil, nil, nil, 1],
                [nil, 1, 2, nil, 3, 1, 5, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, 3, 2, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, 1, 3, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1386,
            rows: [
                [nil, nil, 4, 4, 2, nil, nil, nil],
                [nil, 1, 2, 1, 3, nil, nil],
                [nil, 4, 1, 1, 1, 1, nil, nil],
                [1, 2, 3, 3, 3, 3, nil],
                [nil, 2, 1, 2, 2, 4, nil, nil],
                [1, 1, 2, 1, 3, 3, nil],
                [nil, nil, 5, nil, 1, nil, nil, nil],
                [nil, 2, nil, nil, 6, nil, nil],
                [nil, nil, 6, nil, 1, nil, nil, nil],
                [nil, 2, nil, nil, 1, nil, nil],
                [nil, 2, 1, 1, nil, 2, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 1, 2, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1387,
            rows: [
                [4, nil, nil, 4, nil, 4, nil, 1],
                [2, 2, 2, nil, nil, 2, 1],
                [nil, nil, 3, nil, nil, 1, nil, nil],
                [nil, 1, 3, 1, 2, 1, 2],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, 5, 1, 1, 3, 1, 1],
                [nil, nil, 3, 3, 2, 2, 1, 2],
                [nil, nil, 2, 1, 1, 6, 2],
                [nil, nil, 2, 5, 1, 1, 4, 3],
                [nil, nil, 3, 1, 1, 1, 1],
                [nil, nil, nil, 2, 1, nil, 3, 1],
                [nil, nil, nil, 1, nil, 4, 1],
                [nil, nil, nil, 3, 3, nil, 5, 1],
                [nil, nil, nil, 4, nil, 1, 5],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1388,
            rows: [
                [nil, nil, nil, 5, 3, nil, nil, nil],
                [nil, nil, 2, 2, 4, nil, nil],
                [nil, nil, 1, 3, 3, 3, nil, nil],
                [nil, 1, 1, 3, 2, 2, nil],
                [nil, nil, 2, 1, 1, 4, nil, nil],
                [nil, 4, 2, 1, 1, 4, nil],
                [nil, 4, nil, 1, 1, nil, 1, nil],
                [2, 3, 1, 1, 3, 1, 2],
                [nil, 1, nil, 1, 3, nil, 1, nil],
                [3, 3, 3, 2, 1, 5, 1],
                [nil, 2, nil, 1, 6, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1389,
            rows: [
                [nil, 3, nil, nil, nil, nil, 2, nil],
                [nil, 2, 4, 4, 5, 5, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, 3, 1, 1, 1, 1],
                [nil, 1, nil, nil, nil, nil, 1],
                [nil, 4, 4, 3, 1, 1, 1, 2],
                [nil, 5, nil, nil, nil, nil, 1],
                [nil, nil, nil, 3, 3, 4, 1, nil],
                [nil, 6, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, 2, 4, 4, nil],
                [nil, 2, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1390,
            rows: [
                [1, 2, nil, 1, 2, nil, 1, 2],
                [1, nil, nil, 3, nil, nil, 2],
                [1, nil, nil, 5, nil, nil, 5, nil],
                [1, nil, nil, 3, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1, nil],
                [2, nil, nil, 2, nil, nil, 2],
                [1, nil, nil, 2, nil, nil, 6, nil],
                [1, nil, nil, 2, nil, nil, 2],
                [2, nil, nil, 1, nil, nil, 4, nil],
                [1, nil, nil, 3, nil, nil, 3],
                [1, nil, nil, 1, nil, nil, 1, nil],
                [1, nil, nil, 3, nil, nil, 3],
                [3, nil, nil, 1, nil, nil, 3, nil],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1391,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 2, nil, nil, 1, nil, 1, nil],
                [1, nil, nil, 2, nil, nil, 4],
                [nil, 2, nil, nil, 1, nil, 3, nil],
                [2, nil, nil, 1, nil, nil, 7],
                [nil, 4, nil, nil, 2, nil, 2, nil],
                [nil, 5, nil, 3, nil, 3, nil],
                [nil, 3, nil, nil, 1, nil, 2, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [nil, nil, 2, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1392,
            rows: [
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, 4, 3, 2, 2, 1, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 4, 2, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, 6, 5, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 2, 2, 2, 2, 1, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, 5, 3, 1, 1, 1, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1393,
            rows: [
                [nil, 2, nil, 3, nil, 1, nil, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, 3, nil, 3, nil, nil],
                [nil, 1, nil, 2, nil, 2, nil],
                [nil, 2, nil, 1, nil, 3, nil, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [nil, 3, nil, 1, nil, 5, nil, nil],
                [nil, 1, nil, 1, nil, 4, nil],
                [nil, 5, nil, 2, nil, 1, nil, nil],
                [nil, 3, nil, 2, nil, 3, nil],
                [nil, 3, nil, 1, nil, 1, nil, nil],
                [nil, 7, nil, 1, nil, 3, nil],
                [nil, 1, nil, 1, nil, 4, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1394,
            rows: [
                [nil, 1, 1, 5, 3, 3, 1, nil],
                [2, nil, nil, nil, nil, nil, 3],
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [2, 2, 5, 5, 1, 2, 2],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [2, 2, 3, 1, 1, 3, 3],
                [nil, 1, 2, 4, 1, 2, 2, nil],
                [nil, 1, 6, 6, 2, 2, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1395,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 3, 2, 4, nil, nil],
                [nil, nil, 5, 1, 3, 1, nil, nil],
                [nil, 3, 1, 3, 3, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 2, 1, 4, 1, nil],
                [nil, 6, 5, 2, 1, 1, 4, nil],
                [4, 4, 1, 2, 2, 1, 2],
                [nil, 1, 2, 1, 2, 1, 1, nil],
                [2, 2, 1, 1, 3, 3, 3],
                [nil, 1, 3, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1396,
            rows: [
                [6, nil, nil, nil, nil, nil, nil, 5],
                [nil, 4, nil, nil, nil, 4, nil],
                [nil, nil, 4, nil, nil, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, 4, nil, nil],
                [nil, 4, 2, 1, 2, 4, nil],
                [nil, 2, 3, 1, 1, 3, 2, nil],
                [nil, 1, 3, 2, 1, 1, nil],
                [nil, nil, 1, 2, 2, 3, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 2, 3, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1397,
            rows: [
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [nil, 1, 3, 3, 1, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, 4],
                [nil, 1, 2, 7, 2, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, 1, 2, 3, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, 4, 3, 3, 1, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, 5, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 2, 3, 1, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1398,
            rows: [
                [4, nil, nil, 4, 4, nil, nil, 1],
                [1, nil, 1, nil, 1, nil, 3],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, 3, nil, nil, nil, 3, 2],
                [nil, 2, 1, nil, nil, 1, 3, nil],
                [3, 3, nil, nil, nil, 1, 1],
                [1, nil, 2, 3, 2, 1, nil, 1],
                [3, 1, nil, nil, nil, 2, 2],
                [1, nil, 3, 4, 4, 4, nil, 2],
                [1, 2, nil, nil, nil, 6, 2],
                [nil, 2, 1, nil, nil, 1, 1, nil],
                [4, nil, 4, nil, 1, nil, 2],
                [nil, 5, 2, nil, nil, 3, 4, nil],
                [2, nil, 3, nil, 2, nil, 4],
                [1, nil, nil, 2, 2, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1399,
            rows: [
                [nil, nil, nil, nil, 1, 1, 2, 1],
                [1, 3, 2, 2, 1, 1, 2],
                [1, 3, 3, 3, 3, 2, 2, 1],
                [5, 2, 4, 1, 2, 2, 1],
                [3, 1, 4, 4, 1, 2, 1, 3],
                [3, 1, 5, 2, 1, 1, 2],
                [nil, nil, nil, nil, 2, 1, 2, 2],
                [nil, nil, nil, nil, 2, 1, 6],
                [nil, nil, nil, nil, 6, 1, 2, 1],
                [nil, nil, nil, nil, 3, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1400,
            rows: [
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [2, 2, 3, 1, 2, 2, 2],
                [nil, nil, 1, 3, 1, 1, nil, nil],
                [nil, 1, 3, 1, 3, 3, nil],
                [nil, nil, 4, 1, 1, 5, nil, nil],
                [nil, 1, 3, 1, 6, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 5, 1, 1, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, 4, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
    ]
}
