// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch13 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 241,
            rows: [
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, nil, 2, nil, 2, nil],
                [nil, nil, 2, 2, 2, 3, nil, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [3, nil, nil, 3, 3, nil, nil, 2],
                [2, 2, nil, 1, nil, 1, 1],
                [1, nil, nil, 7, 1, nil, nil, 1],
                [1, 1, nil, 1, nil, 4, 4],
                [nil, 4, 4, 4, 4, 4, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 2, 2, 2, 5, 5, 5, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 242,
            rows: [
                [nil, nil, 1, 1, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 3, 3, nil, nil],
                [3, 3, 3, 4, 4, 4, nil],
                [nil, 4, 4, 4, 3, 3, nil, nil],
                [3, 3, 3, 7, 7, 1, nil],
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, 5, 5, 5, nil, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, 2, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 243,
            rows: [
                [nil, 1, 1, 1, 1, nil, 1, 1],
                [1, nil, nil, nil, 1, 1, nil],
                [1, 1, 2, 2, 3, 3, 3, 3],
                [1, 4, 2, nil, nil, 2, 2],
                [2, 2, 6, 6, 6, 3, 3, nil],
                [3, nil, 3, nil, nil, nil, nil],
                [2, nil, nil, 2, nil, nil, 2, 2],
                [2, 2, 2, nil, nil, 2, 2],
                [2, nil, nil, 1, nil, nil, nil, 1],
                [1, 1, 1, nil, nil, nil, 1],
                [1, 5, 5, 5, 5, 1, 5, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 244,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 5, 5, 5, 5, 5, 1, 4],
                [4, 4, 4, 4, 1, 2, 2],
                [2, 2, 2, 2, 2, 2, 2, 2],
                [2, 2, 2, 3, 3, 1, 3],
                [3, 3, 3, 3, 1, 7, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 245,
            rows: [
                [nil, 1, 1, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
                [nil, 1, 2, 2, 1, 1, 1, nil],
                [nil, nil, 2, 2, 6, 6, nil],
                [nil, nil, nil, 6, nil, 1, 1, nil],
                [nil, 1, 1, 1, nil, nil, nil],
                [nil, 1, nil, 1, 2, nil, 2, nil],
                [nil, 2, 2, nil, nil, 2, nil],
                [nil, nil, 2, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, 3, 3, 1, nil, 1, nil, nil],
                [nil, 1, nil, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 4, nil],
                [nil, 4, 4, 4, 4, 4, nil],
                [nil, 4, 4, 4, 3, 3, 3, nil],
                [nil, 3, 6, 3, 3, 3, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 246,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, nil, 3, 3],
                [3, nil, nil, 6, 6, nil, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [6, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, 1, 1, nil, 1, 1],
                [nil, 1, 1, 1, 1, nil, 1, 1],
                [1, 1, 1, 1, nil, 1, 1],
                [nil, 1, 1, 2, 1, nil, 1, 1],
                [2, 2, 2, 4, nil, 4, 4],
                [nil, nil, nil, 4, nil, 3, 5, nil],
                [3, 1, 1, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, 2, 3, nil],
                [2, 2, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 247,
            rows: [
                [5, nil, nil, nil, nil, nil, nil, nil],
                [5, nil, 1, 1, 1, nil, 1],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, nil, nil, nil, 1],
                [nil, 1, nil, nil, 3, 3, 1, nil],
                [2, nil, 2, nil, 2, 3, nil],
                [nil, nil, nil, nil, nil, 3, 4, nil],
                [4, 1, 3, nil, nil, 3, 3],
                [3, 3, 2, nil, nil, nil, nil, 2],
                [2, 3, 3, nil, 3, 3, 2],
                [2, nil, 2, 2, nil, nil, nil, 1],
                [6, nil, nil, 6, 4, 4, 4],
                [4, 4, 4, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 248,
            rows: [
                [1, nil, nil, nil, 1, 1, nil, nil],
                [1, nil, nil, 2, 3, 3, nil],
                [3, nil, nil, 3, 3, 3, 6, nil],
                [6, nil, 1, 1, 1, 1, 1],
                [1, nil, nil, 1, 1, 3, 3, nil],
                [3, nil, 3, 3, 3, 5, 5],
                [5, nil, nil, 5, 5, 1, 1, nil],
                [2, nil, nil, 2, 2, 2, nil],
                [2, nil, nil, 2, 2, 2, 2, nil],
                [2, nil, nil, 1, 1, 2, nil],
                [1, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, 1, 4, 4, nil],
                [2, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, nil, nil, 1, 2, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 249,
            rows: [
                [nil, nil, nil, 2, nil, 2, nil, nil],
                [nil, 2, nil, 2, 2, nil, nil],
                [nil, 2, nil, 2, 2, nil, 2, nil],
                [2, 3, nil, nil, nil, nil, nil],
                [nil, nil, 3, 3, 3, 3, 4, nil],
                [4, 4, 4, 1, nil, nil, nil],
                [1, 1, 3, nil, nil, nil, 3, 3],
                [3, 3, 3, 3, 3, nil, nil],
                [nil, 1, nil, nil, nil, 1, 1, 1],
                [nil, 5, nil, 1, 1, 5, 5],
                [nil, 5, nil, nil, nil, nil, 5, 1],
                [nil, 1, 1, 1, 1, 1, 1],
                [nil, 2, nil, 2, 2, 2, 1, 1],
                [nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, 6, 6, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 250,
            rows: [
                [1, 1, 1, 1, 1, 5, 5, 5],
                [nil, nil, nil, nil, nil, nil, 5],
                [5, 1, 1, 1, 1, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [1, 1, 2, 2, 2, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 6, 1],
                [nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 3, 3],
                [nil, nil, nil, nil, nil, nil, 3],
                [3, 1, 1, 1, 1, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [1, 1, 4, 4, 4, 4, 1, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 6, 6, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 251,
            rows: [
                [nil, nil, nil, 2, 2, 2, 2, nil],
                [2, 2, 5, nil, nil, nil, 5],
                [5, nil, nil, nil, nil, nil, nil, 5],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, nil, 1, 1, 3, 3],
                [3, nil, nil, 3, 3, 3, 3],
                [6, nil, nil, nil, 6, 6, 4, 4],
                [1, nil, nil, 1, 1, 1, 1],
                [1, nil, nil, nil, 1, 1, 1, 4],
                [4, 1, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 3, 3, 3, 2],
                [2, 3, nil, nil, nil, nil, nil],
                [3, 1, 1, nil, nil, nil, nil, nil],
                [1, 2, 1, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 252,
            rows: [
                [3, 3, 3, 3, 3, 3, 3, 3],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, 1],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 4, 4],
                [nil, 4, nil, nil, nil, nil, nil],
                [nil, nil, 4, 2, 4, 2, 2, 2],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, 3, 3, 2, 2, 2, 2],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, 4, 4, 4, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 5, 5, 5, 5, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 253,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, 1, nil, nil, 2, 1, nil],
                [nil, 1, 1, 2, 2, nil, nil, nil],
                [2, nil, 2, nil, nil, 2, nil],
                [nil, 2, 2, 2, nil, nil, nil, nil],
                [5, 5, nil, 5, 5, 2, nil],
                [2, 2, nil, 2, 2, 2, nil, 2],
                [2, 2, 1, 1, 1, 1, nil],
                [2, 2, 1, nil, nil, nil, 1, 1],
                [1, 1, 1, 1, nil, nil, 1],
                [nil, 1, 1, nil, nil, 3, 3, nil],
                [nil, 3, 1, nil, nil, nil, 1],
                [nil, nil, 6, nil, 6, 6, nil, 4],
                [nil, nil, 4, 4, 4, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 254,
            rows: [
                [nil, 6, nil, nil, 6, 6, 6, nil],
                [5, nil, nil, 5, 2, 2, nil],
                [2, nil, nil, 2, 2, 2, nil, nil],
                [2, nil, 2, 2, 4, nil, nil],
                [1, nil, nil, 4, 1, 1, nil, nil],
                [3, nil, 3, 3, 3, nil, nil],
                [1, nil, nil, 1, 1, 1, nil, nil],
                [1, nil, 1, 1, 1, 1, nil],
                [1, nil, nil, 1, 1, 1, nil, nil],
                [4, nil, 4, 4, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 255,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 3, nil, nil],
                [nil, nil, 3, 3, 3, 4, nil, nil],
                [nil, 4, 4, nil, 4, 1, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, 3, 3, nil, 3, 2, nil],
                [nil, 2, 2, nil, nil, 2, 1, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, nil, 1, 5, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [6, 2, nil, nil, nil, nil, 2, 2],
                [7, nil, nil, nil, nil, nil, 7],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 256,
            rows: [
                [nil, 2, 2, nil, nil, nil, nil, nil],
                [2, 2, 2, nil, nil, nil, nil],
                [nil, 4, 4, nil, nil, nil, nil, nil],
                [nil, nil, 1, 3, nil, nil, nil],
                [nil, 3, 3, nil, nil, nil, nil, nil],
                [nil, nil, 2, 6, nil, nil, nil],
                [nil, nil, 6, 6, 6, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 4, 1, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, nil, nil, nil, 1, 7, nil, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, nil, nil, nil, 2, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 257,
            rows: [
                [1, 1, 1, 1, 1, 2, 2, 2],
                [2, 2, 2, 2, 3, 3, 3],
                [3, 3, 3, 3, 3, 3, 3, 3],
                [3, 3, 1, 1, 7, 2, 2],
                [2, 4, 4, 4, 4, 4, 1, 1],
                [1, 1, 1, 1, 6, 6, 5],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 258,
            rows: [
                [nil, 5, 5, nil, 5, 5, nil, nil],
                [nil, 4, 1, nil, 1, 1, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 7, nil, nil, nil, 7, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil, nil],
                [nil, 2, 2, 4, nil, nil, nil],
                [nil, 4, 4, 4, nil, nil, nil, nil],
                [nil, 1, 1, 3, nil, nil, nil],
                [nil, 3, 3, 3, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 259,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 1],
                [nil, 1, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, 1, 6, nil],
                [nil, 6, 6, 1, nil, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 3, 3, 2, nil],
                [nil, 3, 3, 3, 2, 2, 2, nil],
                [nil, 2, 5, 5, 5, 1, nil],
                [nil, 2, 2, 2, 2, 2, 1, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 3, 4, 3, 3],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 260,
            rows: [
                [2, nil, 2, 3, 2, nil, 2, 2],
                [nil, nil, nil, nil, nil, nil, 2],
                [nil, 2, nil, 2, nil, 2, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, 1, 2, 4, 4, nil],
                [4, nil, 4, 1, 1, nil, 1],
                [1, 1, nil, 1, 1, 1, nil, 1],
                [1, nil, nil, nil, 1, 1, 1],
                [2, nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, 5, 5, nil, 5],
                [6, 3, nil, nil, 3, 3, 3, 3],
                [nil, 3, 2, 2, nil, 2, nil],
                [2, 2, 2, 4, 4, 4, nil, 6],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
    ]
}
