// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch94 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1861,
            rows: [
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [1, 6, nil, 2, 2, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, 1],
                [3, 1, 2, 2, 3, 1, nil],
                [nil, nil, nil, 2, nil, 1, 2, 1],
                [2, 2, nil, nil, 1, nil, 2],
                [3, 3, 1, nil, 1, 1, nil, nil],
                [nil, 1, 3, nil, 3, 1, 1],
                [nil, 4, 1, nil, nil, 1, nil, nil],
                [3, nil, 4, 1, 1, nil, nil],
                [5, 4, 1, 1, nil, 3, 1, 1],
                [1, 1, 3, 3, 3, 1, 2],
                [1, 4, 1, 1, nil, 1, 4, 1],
                [6, 1, 4, 1, 4, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1862,
            rows: [
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, 2, 1, 3, nil, nil],
                [nil, nil, 3, 1, 2, 1, nil, nil],
                [nil, 5, 1, 1, 2, 1, nil],
                [nil, nil, 4, 1, 1, 3, nil, nil],
                [nil, 2, 2, 1, 2, 2, nil],
                [nil, 4, 4, 1, 3, 1, 2, nil],
                [2, 2, 2, 1, 1, 1, 3],
                [nil, 3, 1, 2, 1, 3, 3, nil],
                [3, 3, 1, 2, 1, 1, 3],
                [1, 2, 2, 1, 6, 3, 1, 1],
                [2, 2, nil, nil, nil, nil, 1],
                [1, 3, 1, 1, 3, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1863,
            rows: [
                [nil, 1, 2, 4, 1, 5, 1, nil],
                [nil, 2, 1, nil, nil, 1, nil],
                [nil, 1, 1, 3, nil, 1, 1, nil],
                [nil, 2, 1, 2, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, 1, nil],
                [nil, 6, 1, 1, nil, 4, nil],
                [nil, 4, nil, nil, nil, 4, 2, nil],
                [nil, 1, nil, 2, 2, 2, nil],
                [nil, 1, 1, 1, 4, 1, 3, nil],
                [nil, 3, 3, 2, 1, 1, nil],
                [nil, 2, 1, 3, 3, 1, 4, nil],
                [nil, 4, 2, 1, 2, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1864,
            rows: [
                [2, nil, 2, nil, 5, nil, 5, nil],
                [nil, 5, nil, 1, nil, 1, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [2, nil, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil, 4],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1865,
            rows: [
                [nil, 1, nil, nil, nil, 3, 1, nil],
                [2, nil, 2, nil, 1, nil, 5],
                [5, 1, nil, 2, 2, nil, 6, 1],
                [4, 4, 1, 3, 2, 1, 1],
                [3, 3, nil, 3, 3, nil, 1, 1],
                [3, 1, 2, 2, 1, 2, 4],
                [1, 4, 4, 1, 1, 1, 1, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1866,
            rows: [
                [1, 4, 3, nil, nil, 2, nil, 1],
                [nil, nil, nil, nil, 1, 2, 1],
                [nil, nil, 2, nil, 2, 2, 1, nil],
                [nil, 3, nil, 3, 1, 2, 1],
                [nil, 5, 1, 1, 2, 1, nil, nil],
                [nil, 4, 2, nil, nil, 2, 2],
                [2, 2, 1, 4, 3, 3, nil, 2],
                [nil, nil, nil, 1, 3, 4, 2],
                [nil, 1, 4, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, 2, 1, 6, nil, nil, 1],
                [nil, 4, 1, 1, 1, 6, 2],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1867,
            rows: [
                [nil, 1, nil, 3, nil, nil, 2, 2],
                [nil, 3, nil, nil, nil, 3, 3],
                [nil, nil, nil, 4, 3, 6, nil, 6],
                [1, 1, 2, 4, 2, nil, 1],
                [nil, 1, 2, nil, 1, 1, nil, 1],
                [2, 2, 2, nil, nil, nil, nil],
                [1, 1, 2, 2, 3, nil, nil, 3],
                [3, nil, nil, nil, 3, 3, 2],
                [2, nil, nil, 2, nil, nil, nil, 1],
                [1, nil, 1, 2, nil, 2, 2],
                [1, 2, 2, nil, nil, 1, nil, nil],
                [4, nil, 4, 1, 4, 4, 1],
                [nil, 1, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1868,
            rows: [
                [1, nil, 1, 3, 1, nil, nil, 2],
                [2, 1, nil, 3, nil, nil, 2],
                [5, nil, nil, 1, 1, nil, nil, nil],
                [6, nil, nil, nil, nil, 3, 1],
                [1, nil, 2, 2, nil, 2, 2, nil],
                [1, 1, nil, 2, 1, nil, 2],
                [nil, nil, 2, nil, 1, nil, nil, 2],
                [nil, 1, 5, nil, 2, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil, 1],
                [nil, nil, 1, 2, nil, nil, nil],
                [1, nil, 5, nil, nil, 1, nil, nil],
                [nil, 2, nil, 1, 2, nil, 4],
                [4, 1, 3, 1, 2, 1, 1, 3],
                [1, 4, 1, nil, 1, 5, nil],
                [1, nil, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1869,
            rows: [
                [1, 3, nil, nil, nil, nil, 1, 4],
                [4, 4, 2, 2, 2, 3, 4],
                [1, 2, nil, nil, nil, nil, 2, 1],
                [1, 2, 2, 1, 4, 4, 4],
                [3, 3, nil, nil, nil, nil, 1, 4],
                [3, 4, 3, 1, 1, 2, 2],
                [1, 1, nil, nil, nil, nil, 2, 4],
                [2, 3, 3, 3, 2, 2, 1],
                [2, 2, nil, nil, nil, nil, 2, 6],
                [1, 2, 3, 1, 3, 3, 1],
                [4, 1, nil, nil, nil, nil, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1870,
            rows: [
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [1, 6, 6, 1, 5, 2, 2, 1],
                [nil, nil, nil, nil, nil, nil, 3],
                [2, 1, 3, 3, 5, 4, 4, 2],
                [nil, nil, nil, nil, nil, nil, 5],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, 1, 4, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, 2, 2, 1, 3, 6, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [3, 5, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1871,
            rows: [
                [1, 4, 5, 5, 5, 5, nil, nil],
                [3, 1, nil, nil, 1, nil, nil],
                [nil, 1, 3, nil, 3, nil, nil, 1],
                [1, 1, 1, 1, 4, 2, 2],
                [2, nil, 2, 2, 2, nil, 4, 2],
                [1, 2, nil, nil, nil, nil, nil],
                [2, 3, 1, nil, 2, nil, 1, 2],
                [2, 2, 2, 6, nil, nil, 2],
                [nil, 3, nil, 4, 1, nil, nil, 1],
                [nil, nil, nil, 2, 1, nil, nil],
                [nil, 2, nil, nil, 3, 2, 3, nil],
                [nil, nil, 3, 3, nil, 2, 1],
                [nil, nil, 2, nil, 1, nil, 4, nil],
                [nil, nil, 1, 1, 2, 1, 2],
                [nil, nil, 1, nil, 1, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1872,
            rows: [
                [nil, nil, 5, nil, nil, 2, nil, 1],
                [nil, 2, nil, 1, 1, 1, 1],
                [1, 1, nil, 2, nil, nil, 2, 1],
                [1, 1, 2, 1, 2, 2, 1],
                [1, 1, 2, 3, 2, 6, 2, 3],
                [nil, 3, nil, nil, 2, nil, 3],
                [nil, 3, nil, nil, 2, nil, 1, nil],
                [2, 1, nil, 4, nil, nil, 1],
                [2, 1, 4, 2, 1, 5, 5, 1],
                [2, 2, 2, 1, 5, 1, 3],
                [1, 1, 2, 1, 1, 2, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1873,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 1, 1, 3, nil, nil],
                [nil, nil, 1, 3, 1, 2, nil, nil],
                [nil, 2, 2, 1, 1, 2, nil],
                [nil, nil, 3, 1, 1, 4, nil, nil],
                [nil, 1, 4, 1, 1, 2, nil],
                [nil, 2, 1, 2, 2, 2, 2, nil],
                [2, 3, 1, 5, 1, 1, 2],
                [nil, 3, 1, 1, 2, 1, 1, nil],
                [3, 1, 3, 2, 1, 4, 3],
                [4, 5, 3, 3, 3, 3, 2, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 2, 1, 5, 1, 2, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1874,
            rows: [
                [nil, 1, nil, nil, nil, nil, 5, nil],
                [nil, 5, nil, nil, nil, 5, nil],
                [nil, nil, 3, 1, 4, 2, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, 1, 1, 1, 4, nil, nil],
                [nil, nil, 4, nil, 1, nil, nil],
                [2, 3, 3, nil, nil, 3, 1, 3],
                [nil, nil, 2, nil, 1, nil, nil],
                [2, 3, 1, nil, nil, 4, 1, 4],
                [nil, nil, 4, nil, 1, nil, nil],
                [nil, nil, 1, 3, 1, 3, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1875,
            rows: [
                [1, nil, nil, 2, nil, 2, 1, 2],
                [1, nil, 4, nil, 1, nil, 2],
                [1, nil, nil, 1, nil, nil, nil, 5],
                [5, 1, 1, nil, nil, nil, 1],
                [2, nil, nil, 1, nil, nil, nil, 3],
                [3, 1, 3, nil, nil, nil, 3],
                [nil, nil, nil, 3, nil, 3, 1, nil],
                [nil, nil, 3, nil, 2, nil, nil],
                [nil, nil, nil, 1, nil, 2, 1, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, nil, 2, nil, 5, 5, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1876,
            rows: [
                [1, nil, 5, 1, 4, nil, 1, 2],
                [1, 1, 2, 1, 2, 1, 2],
                [1, 1, 6, 1, 2, 4, 1, 2],
                [2, 1, 4, 4, 4, 1, 1],
                [nil, 3, 3, 1, 6, 2, nil, nil],
                [nil, 3, 1, 1, 2, nil, nil],
                [nil, 2, 1, 3, nil, nil, nil, nil],
                [nil, 1, 2, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1877,
            rows: [
                [5, 5, nil, nil, nil, nil, 5, 3],
                [3, nil, nil, nil, nil, nil, 1],
                [nil, nil, 2, 1, 2, 4, nil, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, nil, 3, 1, 6, 1, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 2, 3, nil, nil, nil],
                [3, 1, nil, nil, nil, nil, 1, 1],
                [6, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1878,
            rows: [
                [nil, nil, 1, 4, 1, nil, 3, nil],
                [nil, nil, 4, 1, 4, 2, nil],
                [nil, 1, nil, 6, nil, nil, 1, nil],
                [nil, 5, 5, nil, 1, 2, nil],
                [nil, 4, 1, 2, 1, 1, 3, nil],
                [nil, 1, 1, 3, 1, 4, nil],
                [nil, 2, 1, 1, 2, 1, 3, nil],
                [nil, 1, 3, 1, 1, 1, nil],
                [nil, nil, 4, 4, 1, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 1, 1, 3, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 1, 1, 1, nil, 1],
                [1, nil, 1, nil, nil, 1, 1],
                [1, nil, 1, nil, 1, 1, nil, 1],
                [1, nil, 1, nil, nil, 1, 1],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1879,
            rows: [
                [nil, 1, nil, 4, nil, 1, 3, nil],
                [nil, nil, nil, 3, 4, 1, nil],
                [nil, nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 2, 2, 1, 3, nil],
                [nil, nil, nil, nil, nil, 1, nil, nil],
                [nil, 2, 1, nil, nil, 3, nil],
                [nil, nil, 1, nil, nil, 3, 3, nil],
                [nil, 1, 1, 4, 1, 1, nil],
                [nil, nil, nil, 1, 4, 1, 4, nil],
                [nil, 2, 1, 2, 1, 1, nil],
                [nil, 3, 3, 1, 2, 2, 2, nil],
                [nil, 1, 4, 1, 2, 2, nil],
                [nil, 1, 2, 2, 1, 1, 2, nil],
                [nil, 1, 6, 2, 2, 1, nil],
                [nil, 2, 1, 1, 4, 4, 1, nil],
                [nil, 5, 1, 1, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1880,
            rows: [
                [1, 1, 1, 2, nil, 2, nil, 3],
                [1, 4, nil, nil, nil, nil, nil],
                [nil, 3, 1, 3, nil, nil, 1, 2],
                [1, 2, 1, nil, nil, 3, nil],
                [1, nil, nil, 1, nil, 1, 2, 1],
                [1, 2, 1, nil, 4, 2, 1],
                [1, 3, 1, 3, 3, 1, 5, 1],
                [2, 4, 2, nil, 1, 2, 2],
                [2, 1, 1, 2, 1, 1, 3, 1],
                [1, 1, 3, nil, 3, 2, 2],
                [1, 6, 2, 1, 4, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
    ]
}
