// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch23 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 441,
            rows: [
                [nil, nil, nil, 1, 3, 3, 3, nil],
                [3, 3, 3, nil, nil, nil, 3],
                [3, nil, nil, nil, nil, nil, nil, 3],
                [3, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, 4, 1, 1, 1],
                [1, nil, nil, 1, 5, 4, 4],
                [4, nil, nil, nil, 4, 4, 2, 2],
                [1, nil, nil, 1, 1, 1, 1],
                [1, nil, nil, nil, 1, 1, 7, 2],
                [2, 2, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, 4, 4, 1, 1],
                [1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil, nil],
                [5, 5, 6, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 442,
            rows: [
                [1, nil, 2, 2, 2, 3, nil, 3],
                [3, nil, nil, nil, nil, nil, 1],
                [1, 7, 2, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, 1, 1, nil, nil],
                [nil, nil, 1, 1, 5, nil, nil],
                [nil, nil, 5, 5, 5, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 3, nil, 3, nil, 3],
                [3, nil, 3, nil, 3, nil, 3],
                [nil, 3, nil, 3, nil, 3, nil, 3],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 4, nil, 4, nil, 4],
                [4, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 6, nil, 2, nil, 5],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 443,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 2, nil, 2, 2, nil, nil],
                [1, 2, nil, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [1, 5, nil, 5, 5, nil, nil],
                [nil, 2, 1, nil, 1, 1, nil, nil],
                [1, 2, nil, 6, 2, nil, nil],
                [nil, 2, 2, nil, 3, 3, nil, nil],
                [3, 3, nil, 6, 6, nil, nil],
                [nil, 4, 4, nil, 4, 2, nil, nil],
                [2, 2, nil, 2, 2, nil, nil],
                [nil, 2, 3, nil, 3, 3, nil, nil],
                [3, 3, nil, 3, 7, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 444,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, 2, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, nil, nil, nil, nil],
                [nil, 2, 2, 2, nil, nil, nil],
                [2, 1, 1, 1, 1, 1, 1, nil],
                [1, 1, 2, 2, 4, 4, nil],
                [4, 6, 6, 5, 5, 5, 5, nil],
                [2, 2, 7, 3, 3, 3, nil],
                [3, 3, 3, 3, 2, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 2, 2, 2, 2, 4, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 445,
            rows: [
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [3, nil, nil, 3, nil, nil, 3],
                [3, 1, 1, 1, 1, 1, 1, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [7, nil, nil, 2, nil, nil, 2],
                [nil, 4, nil, 4, nil, nil, 4, nil],
                [nil, nil, 2, 4, nil, nil, nil],
                [nil, 4, nil, 2, nil, nil, 2, nil],
                [nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, 2, 2, nil, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil, nil],
                [nil, 5, 6, nil, nil, nil, nil],
                [nil, 6, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 446,
            rows: [
                [1, 1, 2, 2, 2, 2, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, 4, 4, 4, 4, 4],
                [4, nil, nil, nil, 4, 1, 7],
                [1, nil, nil, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, 3, 3, 3],
                [3, nil, nil, nil, nil, nil, 3, 3],
                [3, 3, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, 3, 3],
                [1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 2, nil, nil, nil],
                [2, 2, 5, 5, nil, nil, nil, nil],
                [6, 6, 6, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 447,
            rows: [
                [1, nil, 3, nil, 3, nil, 3, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [2, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 5, nil],
                [nil, 5, nil, 5, nil, 5, nil],
                [5, nil, 5, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [2, nil, 2, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 4, 4, 4, 4, 4, 1],
                [1, 7, 1, 1, 1, 1, 1],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 448,
            rows: [
                [1, 1, 2, nil, nil, 1, 1, 1],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, 2, 2, 4, nil, nil],
                [nil, 4, nil, 4, nil, 4, nil],
                [nil, nil, 6, 1, 1, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, 1, 1, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, 7, 3, nil, nil, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, 5, nil, nil, 6, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 449,
            rows: [
                [1, nil, 1, nil, nil, 1, nil, 1],
                [5, nil, 5, nil, 5, nil, 2],
                [2, nil, nil, 2, 2, nil, nil, 2],
                [2, nil, 2, 2, 2, nil, 2],
                [2, nil, nil, 3, 1, nil, nil, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, nil, 1, nil, 1, nil, 3],
                [3, nil, nil, 3, 3, nil, nil, 3],
                [3, nil, 3, nil, 3, nil, 4],
                [4, nil, 5, nil, nil, 5, nil, 6],
                [5, nil, nil, nil, nil, nil, 5],
                [5, nil, 5, nil, nil, 5, nil, 4],
                [4, nil, nil, nil, nil, nil, 6],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 450,
            rows: [
                [nil, nil, nil, 3, 3, 3, 3, nil],
                [3, 3, 3, nil, nil, nil, 3],
                [3, nil, nil, nil, nil, nil, nil, 3],
                [1, nil, nil, nil, nil, nil, 1],
                [4, nil, nil, nil, nil, nil, nil, 4],
                [4, nil, nil, nil, nil, nil, 2],
                [1, nil, nil, nil, 1, 1, 1, 1],
                [1, nil, nil, 2, 2, 4, 1],
                [1, nil, nil, nil, 1, 1, 1, 1],
                [1, nil, nil, 1, 5, 5, 5],
                [2, nil, nil, nil, 2, 2, 2, 2],
                [2, 2, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, 2, 2, 2, 1],
                [1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil, nil],
                [1, 7, 6, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 451,
            rows: [
                [6, nil, nil, nil, nil, nil, nil, 6],
                [6, 3, 3, 3, 3, 3, 3],
                [3, nil, nil, nil, nil, nil, nil, 3],
                [3, 1, 4, 4, 4, 4, 4],
                [4, nil, nil, nil, nil, nil, nil, 4],
                [1, 1, 2, 1, 1, 1, 1],
                [2, nil, nil, nil, nil, nil, nil, 5],
                [5, 5, 5, 2, 2, 2, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [2, 2, 2, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 452,
            rows: [
                [3, 3, 3, 3, 4, 4, 4, 4],
                [4, 4, 4, 4, 4, 4, 2],
                [2, 2, 2, 2, 2, 2, 2, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 7, 7, 1, 1],
                [1, 1, 1, 3, 5, 6, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 453,
            rows: [
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, 1, 1, 1, 1, 2],
                [nil, nil, nil, nil, nil, nil, 2, 2],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2, 2],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 2, 2, nil, nil, 2, nil, nil],
                [1, 1, 1, nil, 1, nil, nil],
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [1, 1, 1, nil, 1, nil, nil],
                [1, nil, 3, 3, 3, 3, nil, 5],
                [nil, 5, nil, 4, nil, 4, 4],
                [4, nil, 4, 4, 7, 1, nil, 5],
                [nil, 5, nil, 5, nil, 5, 6],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 454,
            rows: [
                [1, nil, 1, 1, 2, 4, nil, 4],
                [4, nil, nil, nil, nil, nil, 4],
                [4, 4, 1, 1, 1, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 1, 4, 4, 6, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 6, nil, 6, nil, 2, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [3, nil, 3, nil, 3, nil, 3],
                [nil, 3, nil, 3, nil, 5, nil, 5],
                [2, nil, 2, nil, 4, nil, 5],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 455,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, 5, nil, 5, 5, nil, nil],
                [5, 5, nil, 5, 5, nil, nil],
                [nil, 4, 4, nil, 4, 4, nil, nil],
                [4, 4, nil, 4, 1, nil, nil],
                [nil, 1, 3, nil, 3, 3, nil, nil],
                [3, 3, nil, 3, 3, nil, nil],
                [nil, 3, 3, nil, 3, 3, nil, nil],
                [1, 1, nil, 1, 1, nil, nil],
                [nil, 2, 2, nil, 2, 1, nil, nil],
                [1, 6, nil, 7, 2, nil, nil],
                [nil, 2, 2, nil, 1, 1, nil, nil],
                [1, 1, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 456,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 3, 3, nil, nil, nil, nil],
                [nil, nil, 3, 3, nil, nil, nil, nil],
                [nil, 3, 3, 3, nil, nil, nil],
                [nil, nil, 3, 3, nil, nil, nil, nil],
                [nil, 1, 1, 2, nil, nil, nil],
                [2, 2, 7, 7, 2, 2, 2, nil],
                [2, 2, 2, 2, 2, 2, nil],
                [2, 2, 1, 1, 1, 4, 4, nil],
                [4, 4, 4, 1, 1, 1, nil],
                [1, 6, 6, 1, 5, 5, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 457,
            rows: [
                [nil, 2, nil, nil, nil, nil, 3, nil],
                [3, nil, nil, 3, nil, nil, 1],
                [5, 5, 5, 5, 1, 1, 1, 1],
                [1, nil, nil, 2, nil, nil, 2],
                [2, 2, 2, 2, 4, 3, 3, 3],
                [3, nil, nil, 2, nil, nil, 2],
                [nil, 2, nil, 1, nil, nil, 1, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, 1, nil, 1, nil, nil, 1, nil],
                [nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil, nil],
                [nil, 4, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, 2, 7, nil, nil, nil, nil],
                [nil, 6, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 458,
            rows: [
                [4, 4, 4, 4, 4, 4, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, 2, 2, 2, 2, 1],
                [1, nil, nil, nil, 1, 1, 1],
                [3, nil, nil, 3, 3, 3, 3, 3],
                [3, nil, nil, nil, 6, 3, 3],
                [3, nil, nil, nil, nil, nil, 2, 2],
                [2, 1, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, 5, 5],
                [5, 5, nil, nil, nil, nil, nil],
                [1, 1, 1, 6, nil, nil, nil, nil],
                [1, 7, 1, 1, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 459,
            rows: [
                [nil, nil, 2, 2, nil, nil, nil, nil],
                [nil, 2, 2, 2, nil, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [2, 2, 1, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [4, 4, 3, 3, 6, 5, 2, 2],
                [4, 4, 4, 3, 3, 3, 3],
                [5, 3, 3, 3, 3, 3, 3, 3],
                [2, 2, 2, 5, 5, 5, 5],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 460,
            rows: [
                [4, nil, 4, nil, 4, nil, 4, nil],
                [nil, 4, nil, 5, nil, 5, nil],
                [5, nil, 1, nil, 1, nil, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [1, nil, 7, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 4, nil, 3, nil, 3, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [3, nil, 3, nil, 3, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 2, 2, 2, 2],
                [1, 1, 3, 6, 3, 3, 3],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
    ]
}
