// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch111 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2201,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 2, nil, 1, 2, nil, nil],
                [2, 1, nil, 1, 3, nil, nil],
                [nil, 3, 1, nil, 2, 1, nil, nil],
                [2, 2, nil, 1, 3, nil, nil],
                [nil, 1, 4, nil, 1, 4, nil, nil],
                [4, 1, nil, 3, 2, nil, nil],
                [nil, 1, 2, nil, 2, 2, nil, nil],
                [2, 1, nil, 5, 2, nil, nil],
                [nil, 1, 3, nil, 1, 1, nil, nil],
                [2, 1, nil, 2, 1, nil, nil],
                [nil, 1, 1, nil, 6, 1, nil, nil],
                [1, 1, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2202,
            rows: [
                [nil, nil, nil, 5, 1, 1, 2, nil],
                [4, 2, 1, nil, nil, nil, 3],
                [1, nil, nil, nil, nil, nil, nil, 3],
                [1, nil, nil, nil, nil, nil, 1],
                [3, nil, nil, nil, nil, nil, nil, 2],
                [1, nil, nil, nil, nil, nil, 2],
                [3, nil, nil, nil, 3, 3, 3, 3],
                [2, nil, nil, 5, 2, 3, 1],
                [2, nil, nil, nil, 6, 1, 2, 1],
                [3, nil, nil, 1, 2, 1, 1],
                [1, nil, nil, nil, 1, 1, 2, 1],
                [2, 2, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 6, 2, 2, 3],
                [4, 1, nil, nil, nil, nil, nil],
                [5, 3, 3, nil, nil, nil, nil, nil],
                [2, 1, 1, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2203,
            rows: [
                [nil, 5, 1, nil, 2, 1, 3, nil],
                [3, nil, nil, nil, nil, nil, 2],
                [nil, 3, 1, 3, nil, 4, 4, nil],
                [4, nil, nil, nil, nil, nil, 4],
                [nil, 2, 5, 1, nil, 2, 2, nil],
                [1, nil, nil, nil, nil, nil, 3],
                [nil, 3, 3, nil, 5, 2, 2, nil],
                [4, nil, nil, nil, nil, nil, 1],
                [nil, 2, 2, nil, 1, 5, 2, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 2, 1, 1, nil, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2204,
            rows: [
                [nil, nil, 2, 1, 3, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 1, nil, 4, 4, nil, 2],
                [2, 3, nil, 3, 5, nil, 1],
                [nil, 4, 3, 1, 1, 1, 1, nil],
                [2, 5, 5, 2, 2, 1, nil],
                [nil, nil, 2, 1, nil, 2, 2, nil],
                [nil, 2, 1, nil, 2, 2, nil],
                [nil, nil, nil, 3, 1, 3, nil, nil],
                [nil, nil, 1, 6, 3, nil, nil],
                [nil, nil, 3, 6, 1, 3, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2205,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [3, 3, 1, 3, 2, 1, 1],
                [6, 1, 1, 3, 2, 2, 3, 3],
                [3, 1, nil, 1, nil, 3, 3],
                [2, 1, 5, 5, 1, 2, 4, 3],
                [3, 2, nil, 2, nil, 1, 4],
                [3, 1, nil, 2, 3, nil, 1, 1],
                [3, nil, nil, 1, nil, nil, 1],
                [4, 1, nil, 4, 2, nil, 2, 3],
                [3, nil, nil, 3, nil, nil, 1],
                [1, 1, 2, nil, nil, 3, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 3, 2, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2206,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 5, nil, nil, nil, nil],
                [nil, 3, 3, 3, 2, nil, nil, 3],
                [3, 3, 1, 1, 1, nil, 1],
                [nil, 4, 4, 1, 1, nil, nil, 1],
                [1, 1, 2, 1, 1, nil, 2],
                [2, 3, 5, 1, 3, 2, 1, nil],
                [2, 2, 2, 1, 2, nil, 3],
                [4, 1, 3, 1, 1, 1, 4, nil],
                [2, 2, 1, 3, 3, nil, 3],
                [nil, 4, 1, 2, 1, nil, nil, 1],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 2, 2, 3, 3, nil, nil, 1],
                [nil, nil, 6, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2207,
            rows: [
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [2, 2, 4, 1, 1, 1, 2],
                [nil, nil, 1, 1, 2, 1, nil, nil],
                [nil, 1, 1, 1, 2, 2, nil],
                [nil, nil, 2, 6, 3, 3, nil, nil],
                [nil, 1, 3, 1, 1, 7, nil],
                [nil, nil, nil, 4, 5, nil, nil, nil],
                [nil, nil, 3, 6, 1, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 5, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2208,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [7, 1, 1, 1, nil, nil, nil],
                [1, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 3, 1, 1, 1],
                [1, nil, nil, 7, nil, nil, nil, nil],
                [nil, nil, nil, 2, 3, 2, 4],
                [1, nil, nil, nil, 3, nil, nil, 2],
                [2, 3, 1, 1, nil, nil, nil],
                [1, nil, nil, nil, 2, nil, nil, 3],
                [1, 1, 2, 2, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, 1],
                [nil, nil, nil, 3, 1, 3, 2],
                [nil, nil, nil, 1, nil, nil, nil, 2],
                [nil, nil, nil, 5, 2, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2209,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 2],
                [3, nil, 3, 3, 3, nil, 1],
                [nil, 1, 2, nil, nil, 2, 4, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 2, 3, nil, nil, 3, 2, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 3, 3, nil, nil, 1, 1, nil],
                [nil, 3, nil, nil, nil, 2, nil],
                [nil, 5, 5, nil, nil, 1, 1, nil],
                [nil, 2, nil, nil, nil, 5, nil],
                [nil, nil, 4, nil, nil, 2, nil, nil],
                [nil, nil, 4, 4, 2, nil, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2210,
            rows: [
                [nil, 4, 2, 2, 5, 2, 2, nil],
                [nil, 2, 2, 2, 4, 4, nil],
                [nil, nil, 2, 6, 3, 3, nil, nil],
                [nil, nil, 2, 1, 4, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, nil, 6, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, 5, nil, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2211,
            rows: [
                [nil, nil, nil, 1, 7, nil, nil, nil],
                [nil, nil, 3, 3, 2, nil, nil],
                [nil, nil, 3, 1, 2, 3, nil, nil],
                [nil, 4, 1, nil, 1, 4, nil],
                [nil, nil, 2, 1, 1, 1, nil, nil],
                [nil, 1, 1, nil, 3, 1, nil],
                [nil, 1, 4, nil, nil, 2, 2, nil],
                [2, 2, nil, nil, nil, 2, 2],
                [nil, 1, 1, nil, nil, 3, 3, nil],
                [6, 1, nil, nil, nil, 3, 3],
                [1, 1, nil, nil, nil, nil, 3, 3],
                [1, nil, nil, nil, nil, nil, 4],
                [4, 1, nil, nil, nil, nil, 6, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2212,
            rows: [
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, 2, 1, 3, nil, nil],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, 1, 1, nil, 2, 1, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, 1, 2, nil, 3, 2, nil],
                [nil, 2, 2, 2, 5, 5, 1, nil],
                [nil, 2, 2, nil, 4, 1, nil],
                [nil, 1, 1, 4, 4, 1, 4, nil],
                [nil, 1, 6, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2213,
            rows: [
                [1, nil, 2, nil, 4, nil, 3, nil],
                [nil, 2, nil, 2, nil, 5, nil],
                [5, nil, 5, nil, 1, nil, 2, nil],
                [nil, 1, nil, 1, nil, 2, nil],
                [2, nil, 2, nil, 2, nil, 4, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [2, nil, 3, nil, 1, nil, 2, nil],
                [nil, 4, nil, 4, nil, 1, nil],
                [1, nil, 4, nil, 1, nil, 4, nil],
                [nil, 4, nil, 1, nil, 3, nil],
                [3, nil, 1, nil, 2, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 2, 2, 1, 1, 1, 1],
                [5, 3, 3, 1, 4, 1, 3],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2214,
            rows: [
                [1, 2, 5, 3, 1, 2, 1, 1],
                [3, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, 1, 6, 1, 1, 2],
                [1, nil, nil, nil, 1, 1, 2],
                [2, nil, nil, 1, 5, 2, 2, 3],
                [4, nil, nil, nil, 4, 2, 2],
                [3, nil, nil, nil, nil, nil, 3, 3],
                [3, 1, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, 1, 3],
                [3, 3, nil, nil, nil, nil, nil],
                [2, 4, 4, 4, nil, nil, nil, nil],
                [1, 3, 1, 2, nil, nil, nil],
                [2, 2, 1, 5, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2215,
            rows: [
                [3, nil, nil, nil, 4, 4, nil, nil],
                [1, nil, nil, 1, 4, 4, nil],
                [2, nil, nil, 1, 2, 1, 3, nil],
                [1, nil, 2, 5, 2, 4, 2],
                [1, nil, nil, 1, 1, 1, 2, nil],
                [2, nil, 2, 2, 2, 3, 1],
                [3, nil, nil, 3, 1, 1, 4, nil],
                [2, nil, nil, 1, 1, 6, nil],
                [3, nil, nil, 1, 1, 3, 3, nil],
                [3, nil, nil, 3, 4, 1, nil],
                [1, nil, nil, nil, 3, 2, nil, nil],
                [nil, nil, nil, 2, 1, 1, nil],
                [1, nil, nil, nil, 3, 2, nil, nil],
                [nil, nil, nil, 5, 2, 2, nil],
                [nil, nil, nil, 2, 4, 1, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2216,
            rows: [
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [1, nil, nil, 5, nil, nil, 4],
                [4, 4, 3, 2, 1, 2, 2, 1],
                [3, nil, nil, 1, nil, nil, 1],
                [2, 1, 2, 2, 1, 1, 2, 1],
                [3, nil, nil, 1, nil, nil, 1],
                [nil, 2, nil, 3, nil, nil, 1, nil],
                [nil, nil, 3, 3, nil, nil, nil],
                [nil, 3, nil, 3, nil, nil, 1, nil],
                [nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 6, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, 2, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2217,
            rows: [
                [nil, 4, nil, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 4, 4, 4, 1, nil, nil],
                [nil, nil, 3, nil, 2, nil, nil],
                [nil, nil, 2, 2, 1, 1, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [3, 2, 3, nil, nil, 3, 1, 2],
                [nil, nil, 1, nil, 3, nil, nil],
                [1, 2, 2, nil, nil, 4, 3, 5],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 7, 5, 2, 1, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 5, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2218,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, 2, nil, nil],
                [nil, 2, nil, nil, 3, 1, 1, nil],
                [5, nil, nil, nil, nil, 5, nil],
                [nil, 1, nil, nil, 6, 2, 2, nil],
                [1, nil, nil, nil, nil, 2, nil],
                [2, 1, 2, 3, nil, 3, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [1, 1, 1, 3, nil, 1, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2219,
            rows: [
                [2, nil, nil, nil, nil, nil, nil, 2],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, 5, nil, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, 2, 3, 2, 2, nil, nil],
                [nil, 3, 1, 1, 5, 1, nil],
                [nil, 4, 1, 3, 1, 2, 2, nil],
                [nil, 6, 3, 3, 1, 1, nil],
                [nil, nil, 2, 1, 3, 3, nil, nil],
                [nil, nil, 4, 4, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2220,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, 1, 2, 1, 7, nil],
                [2, nil, nil, nil, nil, nil, 1],
                [3, nil, 1, 1, 2, 3, nil, 2],
                [3, nil, nil, nil, nil, nil, 1],
                [nil, 5, 1, 2, 1, 3, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 4, 2, 3, 2, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 1, 1, 3, 1, nil, nil],
                [nil, nil, 2, 1, 3, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
    ]
}
