// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch63 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1241,
            rows: [
                [2, 1, 2, nil, 1, nil, nil, 1],
                [4, nil, 2, 2, nil, 2, 4],
                [4, 1, 1, nil, 2, nil, nil, 3],
                [1, nil, 3, nil, nil, nil, 1],
                [5, 5, 3, 1, nil, 1, 2, 1],
                [1, 2, nil, 1, 3, nil, nil],
                [nil, 3, 1, 2, 1, nil, nil, nil],
                [nil, 5, 3, 1, nil, nil, 1],
                [1, nil, 1, 2, 4, 4, 1, 2],
                [1, 2, 1, 2, 2, 1, 6],
                [3, 1, 1, 2, 1, 1, 5, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 2, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1242,
            rows: [
                [nil, nil, 2, 2, 1, 6, 6, 1],
                [2, 1, 1, 1, 1, 1, 2],
                [2, 1, 1, 2, 4, 1, 2, 1],
                [2, 1, 3, 1, 2, 1, 3],
                [nil, 1, 2, 1, 3, 1, nil, nil],
                [nil, 2, 2, 3, 1, nil, nil],
                [nil, 2, 2, 1, nil, nil, nil, nil],
                [nil, 2, 2, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 3, 3, 1, 4, 1, 3, 1],
                [3, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1243,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 1, 3, 2, nil, nil],
                [nil, 1, 1, 1, 3, 1, 1, nil],
                [4, 3, 4, nil, 2, 1, nil],
                [nil, 2, nil, 1, 4, 4, 2, nil],
                [nil, nil, 1, nil, 2, nil, 2],
                [nil, nil, 4, nil, nil, 1, 2, 1],
                [1, 2, 2, nil, 2, 1, 3],
                [4, 4, 3, nil, nil, 3, 1, 3],
                [1, 1, 2, nil, 1, 1, 1],
                [2, 1, 3, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1244,
            rows: [
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 2, nil, 2, 5],
                [nil, 2, 2, 4, 1, 1, nil, nil],
                [4, nil, 1, nil, 1, 1, nil],
                [2, nil, 2, nil, 3, nil, nil, 2],
                [2, 2, 1, 1, nil, 3, nil],
                [1, nil, nil, nil, 2, 2, nil, nil],
                [nil, 2, nil, nil, nil, nil, 2],
                [2, 1, nil, 1, 1, 5, 3, 3],
                [nil, 1, nil, 1, nil, nil, nil],
                [1, 4, 4, 1, nil, nil, 2, 3],
                [nil, nil, nil, 2, 2, nil, 3],
                [1, nil, 4, 1, nil, 1, 3, 1],
                [1, 1, nil, nil, 1, 3, 3],
                [nil, 1, 4, 5, 1, 2, 1, nil],
                [nil, 3, 1, 1, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1245,
            rows: [
                [nil, 1, nil, 1, 2, 3, nil, nil],
                [nil, 6, nil, 1, nil, 1, nil],
                [nil, 4, 2, nil, 2, 2, 5, nil],
                [nil, nil, 2, nil, nil, 2, nil],
                [nil, 1, nil, 1, 3, nil, 2, nil],
                [nil, nil, nil, 1, nil, 1, nil],
                [nil, nil, 1, 1, 2, 1, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, 3, nil, 2, 2, 3, 3, nil],
                [nil, nil, nil, 2, 1, 3, nil],
                [nil, 3, 3, nil, 3, 1, nil, nil],
                [nil, 4, 1, 2, 1, 4, nil],
                [nil, 2, 2, 6, 6, 1, 2, nil],
                [nil, 1, 2, 2, 4, 1, nil],
                [nil, 2, 1, 4, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1246,
            rows: [
                [nil, 3, 3, nil, nil, nil, 1, 2],
                [nil, nil, 1, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, 4, nil],
                [nil, 1, 3, nil, nil, 2, 3],
                [nil, 2, 2, 2, nil, nil, 1, 1],
                [nil, 2, 2, 2, nil, 2, 4],
                [nil, 4, 4, 4, nil, 1, 2, 1],
                [nil, 3, 3, 2, nil, 2, 2],
                [nil, 1, 3, 6, nil, 6, 1, 3],
                [nil, 3, 1, 5, nil, 1, 1],
                [nil, 2, 1, 2, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1247,
            rows: [
                [3, nil, nil, nil, nil, 3, nil, nil],
                [2, nil, nil, nil, 3, 3, nil],
                [1, nil, nil, nil, nil, nil, 2, nil],
                [3, nil, 3, 2, nil, nil, 5],
                [nil, nil, 1, 1, nil, nil, nil, 1],
                [nil, nil, nil, 2, 2, 2, nil],
                [2, nil, nil, nil, nil, nil, 1, nil],
                [3, nil, nil, 3, 1, nil, nil],
                [1, 4, 2, 2, 1, 2, nil, nil],
                [2, 2, 2, nil, 2, nil, nil],
                [2, nil, 2, 1, 5, nil, 1, 1],
                [5, nil, 5, nil, nil, 1, 2],
                [1, 4, nil, 4, nil, 1, 3, 1],
                [nil, nil, 6, nil, nil, 1, 1],
                [3, 1, 1, 1, 3, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1248,
            rows: [
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, nil, 1, nil, 3, nil, nil],
                [nil, nil, 3, 1, 1, 2, nil, nil],
                [nil, nil, 6, nil, 2, nil, nil],
                [1, 6, 1, nil, nil, 2, 4, 5],
                [nil, nil, 6, nil, 2, nil, nil],
                [4, 1, 1, nil, nil, 2, 2, 1],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, 2, 1, 3, 1, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, nil, 1, 4, 4, 1, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 5, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1249,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, nil],
                [4, 2, 1, 2, nil, 1, 1],
                [1, 1, 3, 3, 1, 2, 2, 1],
                [nil, nil, 1, 2, nil, 1, 1],
                [3, 1, 3, 1, 1, 2, 1, 1],
                [nil, nil, 1, 1, nil, 4, 1],
                [nil, 1, 3, 2, 2, nil, 1, 3],
                [3, 1, 3, 3, nil, 3, 1],
                [nil, 6, 6, 1, 2, nil, 1, 1],
                [3, 1, 1, 2, nil, 2, 3],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1250,
            rows: [
                [2, nil, 3, 1, 5, 5, nil, 5],
                [1, nil, nil, nil, nil, nil, 4],
                [2, 3, 3, 3, 3, 4, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 2, 1, 3, nil, nil],
                [nil, nil, 1, 2, 3, nil, nil],
                [nil, nil, 1, 2, 1, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, nil, 3, nil, 3, nil, 3],
                [2, nil, 2, nil, 1, nil, 1],
                [nil, 1, nil, 2, nil, 2, nil, 2],
                [2, nil, 1, nil, 2, nil, 1],
                [nil, 2, nil, 1, nil, 1, nil, 2],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1251,
            rows: [
                [1, nil, 2, nil, 1, 2, nil, 2],
                [nil, nil, nil, 4, 1, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, 2, nil, nil, nil, nil, nil],
                [1, nil, 1, nil, 1, 2, 2, 2],
                [1, nil, 3, 2, 2, 2, 1],
                [nil, 2, 1, nil, 2, nil, 2, nil],
                [nil, nil, nil, 1, nil, nil, 2],
                [nil, 1, nil, 2, 2, nil, 1, nil],
                [nil, 3, nil, nil, 3, 1, 2],
                [2, 1, 5, 1, 1, 4, 1, 1],
                [2, 1, 4, 1, 2, 1, 1],
                [1, 2, 2, 1, 5, 1, 1, 2],
                [1, 4, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1252,
            rows: [
                [nil, nil, 2, nil, nil, 1, nil, nil],
                [nil, nil, 1, 4, 4, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 4, 3, 1, nil, nil],
                [nil, nil, nil, 6, 6, nil, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 3, 5, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1253,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 2],
                [6, 2, 1, 1, 4, 2, 3],
                [3, nil, nil, nil, nil, nil, nil, 3],
                [3, 3, 1, 4, 4, 4, 2],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [2, 1, 2, 1, 6, 2, 2],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1254,
            rows: [
                [nil, 1, 4, 4, 1, nil, nil, 1],
                [3, 5, nil, nil, nil, nil, 1],
                [nil, 3, 1, nil, nil, 4, nil, 1],
                [2, 1, 1, nil, 3, nil, nil],
                [3, nil, nil, nil, 1, 2, 1, nil],
                [1, nil, 2, nil, 1, 1, 3],
                [3, 3, 1, 3, 1, 1, 1, 2],
                [2, 2, 2, nil, 1, 5, 5],
                [1, 4, 1, 3, 1, 2, 4, 3],
                [1, 1, 2, nil, 1, 1, 5],
                [3, 1, 3, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1255,
            rows: [
                [nil, 1, 3, nil, nil, 3, nil, 1],
                [2, 2, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, 1, 5, 5, nil],
                [nil, 1, 1, nil, nil, 4, 4],
                [4, 1, 4, 1, nil, nil, 2, nil],
                [nil, nil, 1, 1, 1, nil, 3],
                [nil, nil, nil, 3, 3, 2, 2, 1],
                [nil, nil, 2, 2, nil, nil, nil],
                [1, 2, nil, 2, 1, 1, nil, 4],
                [4, 1, 2, 2, nil, nil, 2],
                [1, nil, 2, nil, 1, nil, 4, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1256,
            rows: [
                [nil, 1, 1, 6, nil, nil, nil, 6],
                [nil, nil, 1, 4, nil, nil, 4],
                [nil, 4, nil, 3, nil, nil, nil, 2],
                [nil, 3, nil, 1, nil, 5, 4],
                [nil, 2, 2, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, nil, 1, 2],
                [nil, 2, 1, 1, nil, 3, 1, 3],
                [nil, 1, 1, 1, nil, 3, 1],
                [nil, 1, 4, 4, nil, 1, 3, 1],
                [nil, 1, 2, 1, nil, 3, 3],
                [nil, 3, 1, 2, nil, 1, 1, 2],
                [nil, 1, 5, 1, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1257,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, 4],
                [4, nil, nil, nil, nil, nil, nil],
                [nil, 2, 1, 1, 2, 2, 1, nil],
                [1, 2, 3, nil, nil, nil, 3],
                [nil, nil, 3, nil, nil, 1, 4, nil],
                [nil, 4, 4, nil, nil, 1, 3],
                [1, nil, 2, nil, nil, nil, 1, 2],
                [nil, nil, 2, nil, nil, 2, 1],
                [2, 1, 2, nil, nil, 1, 3, 3],
                [1, 2, 1, nil, 2, 2, 1],
                [1, 1, 6, 2, 1, 1, 2, 1],
                [2, 5, 2, 2, 2, 5, 1],
                [6, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1258,
            rows: [
                [nil, nil, 2, 1, 3, nil, nil, 4],
                [4, nil, 1, 2, 2, 1, 3],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, 1, nil, 2, nil, nil, 1],
                [2, nil, 3, 3, nil, 1, nil, nil],
                [1, 3, nil, nil, 1, 4, 1],
                [nil, 2, 1, nil, 2, 1, nil, 2],
                [1, nil, nil, 1, 5, 2, 5],
                [nil, 5, 1, 2, nil, 1, 2, 1],
                [nil, nil, 2, nil, 1, 1, nil],
                [2, nil, nil, 2, nil, 1, 1, nil],
                [nil, 1, 2, 1, 3, 2, 2],
                [nil, 1, nil, nil, nil, 1, 1, 1],
                [2, 3, 2, 1, 2, nil, nil],
                [nil, 2, 2, 2, 4, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1259,
            rows: [
                [nil, 1, 2, 2, nil, 2, 4, nil],
                [nil, 4, 4, 1, nil, 4, nil],
                [nil, 4, 1, nil, nil, 1, nil, nil],
                [nil, 1, 3, nil, 3, nil, nil],
                [nil, 1, 3, 3, 2, 2, 2, nil],
                [nil, nil, 3, nil, nil, 1, nil],
                [nil, 1, nil, 3, nil, 1, 4, nil],
                [nil, nil, nil, 1, nil, 3, nil],
                [nil, nil, 3, 1, 3, 1, 1, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, 5, nil, 1, 5, nil, nil, nil],
                [nil, 5, nil, 1, 3, 1, nil],
                [nil, nil, 1, nil, 6, 1, 1, nil],
                [nil, 1, 3, 3, 1, 3, nil],
                [nil, 1, 3, 1, 3, 1, 4, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1260,
            rows: [
                [nil, nil, 2, nil, 3, 1, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [3, 3, nil, 5, 3, 4, 3],
                [nil, nil, 1, 3, 3, 1, nil, nil],
                [1, nil, 1, nil, 2, nil, nil],
                [nil, 2, 3, 2, nil, 1, nil, nil],
                [4, 4, 2, 4, nil, 1, 2],
                [1, 1, nil, 2, nil, 2, nil, nil],
                [2, 2, 1, nil, 3, 4, nil],
                [nil, 1, 4, nil, 4, 1, 3, 2],
                [nil, 1, 1, 4, 3, 3, 4],
                [nil, 1, 2, 2, 1, 1, 2, 2],
                [nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
    ]
}
