// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch137 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2721,
            rows: [
                [1, 2, 1, 4, 1, 1, 2, 3],
                [4, nil, nil, 2, nil, nil, 2],
                [1, nil, nil, 2, 4, nil, nil, 3],
                [nil, nil, nil, 1, nil, nil, nil],
                [3, nil, nil, 2, 4, nil, nil, 2],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 7, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2722,
            rows: [
                [nil, nil, 2, nil, nil, 3, nil, nil],
                [nil, 2, nil, nil, 7, nil, nil],
                [nil, 3, nil, nil, 2, 1, 2, nil],
                [1, nil, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, 3, 1, 2, nil],
                [3, nil, nil, nil, nil, 4, nil],
                [4, 5, 1, 2, nil, 7, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [2, 2, 1, 6, nil, 2, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2723,
            rows: [
                [1, nil, nil, nil, 3, nil, nil, nil],
                [3, nil, nil, nil, 3, nil, nil],
                [nil, 2, nil, nil, 1, 5, nil, nil],
                [nil, 1, nil, 2, nil, 2, nil],
                [nil, 1, nil, nil, 4, 2, nil, nil],
                [nil, 2, nil, 3, nil, 4, nil],
                [nil, 6, nil, nil, 1, 5, nil, nil],
                [2, nil, nil, 1, 5, 1, nil],
                [nil, 2, nil, nil, 1, 5, nil, nil],
                [1, nil, nil, 4, 1, 5, nil],
                [1, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2724,
            rows: [
                [nil, 1, nil, nil, nil, nil, 7, nil],
                [4, 3, nil, nil, nil, 6, 3],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [2, 1, nil, nil, nil, 4, 4],
                [nil, 2, nil, nil, nil, nil, 5, nil],
                [2, 2, nil, nil, nil, 3, 1],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [2, 1, nil, nil, nil, 3, 1],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [1, 1, nil, nil, nil, 3, 3],
                [nil, 1, nil, nil, nil, nil, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2725,
            rows: [
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [2, nil, nil, 1, nil, nil, 2],
                [1, nil, nil, 2, 1, nil, nil, 2],
                [1, nil, nil, 3, nil, nil, 5],
                [1, nil, nil, 4, 1, nil, nil, 1],
                [2, nil, nil, 1, nil, nil, 4],
                [nil, 1, 3, 3, 1, 2, 3, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 3, 1, 2, 2, 7, 1, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2726,
            rows: [
                [nil, 3, nil, nil, nil, nil, 1, nil],
                [6, 1, nil, nil, nil, 3, 3],
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [1, 4, nil, nil, nil, 1, 2],
                [nil, 1, nil, nil, nil, nil, 4, nil],
                [2, 1, nil, nil, nil, 5, 1],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [4, 2, nil, nil, nil, 1, 4],
                [nil, 1, nil, nil, nil, nil, 4, nil],
                [1, 4, nil, nil, nil, 1, 1],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2727,
            rows: [
                [nil, nil, 1, nil, nil, 4, nil, nil],
                [nil, 1, nil, nil, 6, nil, nil],
                [nil, 6, nil, nil, 3, 1, 3, nil],
                [1, nil, nil, nil, nil, 2, nil],
                [nil, 3, nil, nil, 1, 2, 5, nil],
                [2, nil, nil, nil, nil, 3, nil],
                [2, 1, 3, 1, nil, 3, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [3, 4, 1, 2, nil, 3, nil, nil],
                [nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 7, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil],
                [nil, 5, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2728,
            rows: [
                [nil, 1, nil, nil, nil, nil, 4, nil],
                [1, 5, nil, nil, nil, 1, 2],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [2, 3, nil, nil, nil, 3, 1],
                [nil, 4, nil, nil, nil, nil, 1, nil],
                [1, 6, nil, nil, nil, 6, 6],
                [nil, 6, nil, nil, nil, nil, 1, nil],
                [2, 3, nil, nil, nil, 5, 4],
                [nil, 3, nil, nil, nil, nil, 2, nil],
                [4, 2, nil, nil, nil, 1, 2],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2729,
            rows: [
                [4, nil, 5, nil, 1, nil, 4, nil],
                [nil, 1, nil, 6, nil, 3, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 5, nil, nil, 4, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [4, nil, nil, nil, nil, nil, nil, 4],
                [nil, nil, nil, 7, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil, 1],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2730,
            rows: [
                [nil, nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 2, nil, nil, 1, nil, 2, nil],
                [6, nil, nil, 4, nil, nil, 2],
                [nil, 1, nil, nil, 3, nil, 3, nil],
                [4, nil, nil, 1, nil, nil, 2],
                [nil, 4, nil, nil, 1, nil, 5, nil],
                [nil, 1, nil, 2, nil, 5, nil],
                [nil, 2, nil, nil, 1, nil, 4, nil],
                [nil, 1, nil, 3, nil, 1, nil],
                [nil, nil, 4, 2, 2, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 1, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2731,
            rows: [
                [nil, 4, nil, 2, nil, 6, nil, 5],
                [3, nil, 1, nil, 2, nil, 5],
                [nil, 2, nil, 1, nil, 3, nil, 3],
                [2, nil, 1, nil, 2, nil, 5],
                [nil, 2, nil, 2, nil, 4, nil, 1],
                [2, nil, 1, nil, 2, nil, 1],
                [nil, 2, nil, 3, nil, 1, nil, 2],
                [5, nil, 2, nil, 1, nil, 5],
                [nil, 3, nil, 5, nil, 4, nil, 1],
                [2, nil, 3, nil, 1, nil, 2],
                [nil, 5, nil, 3, nil, 1, nil, 2],
                [4, nil, 1, nil, 2, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2732,
            rows: [
                [3, 5, 1, 2, 4, 6, 1, 2],
                [1, nil, nil, 4, nil, nil, 6],
                [1, nil, nil, 2, 5, nil, nil, 4],
                [nil, nil, nil, 1, nil, nil, nil],
                [2, nil, nil, 3, 1, nil, nil, 2],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 7, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2733,
            rows: [
                [1, 2, 1, 3, 1, 2, 3, 1],
                [3, 1, 1, 6, 1, 3, 2],
                [3, 1, 3, 1, 6, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 3, 2, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2734,
            rows: [
                [nil, 3, 1, nil, 1, 2, nil, nil],
                [nil, 1, 2, nil, 4, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 1, 4, 4, nil, nil, nil],
                [nil, 1, 2, 1, nil, nil, nil],
                [nil, 2, 1, 2, nil, nil, nil, nil],
                [nil, 1, 1, 2, nil, nil, nil],
                [nil, 1, 2, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2735,
            rows: [
                [1, 2, 3, 1, 5, 3, 2, 1],
                [1, 2, 1, 5, 5, 1, 5],
                [2, 2, 1, 5, 1, 3, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 2, 1, 2, 1, 2, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2736,
            rows: [
                [nil, nil, 2, nil, nil, 3, nil, nil],
                [nil, nil, 2, 1, 3, nil, nil],
                [nil, nil, nil, 4, 5, nil, nil, nil],
                [nil, nil, 2, 4, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 5, 1, 5, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2737,
            rows: [
                [1, 3, nil, nil, nil, nil, 4, 4],
                [3, nil, nil, nil, nil, nil, 1],
                [nil, nil, 3, 2, 3, 3, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 2, 2, 1, 2, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 2, nil, nil, nil],
                [1, 2, nil, nil, nil, nil, 1, 1],
                [2, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2738,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, 1, 3, nil, nil],
                [nil, nil, 2, 1, 3, nil, nil],
                [nil, nil, 1, 4, 2, 1, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 3, 2, 1, 2, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 4, 1, 3, 2, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 1, 2, 1, 3, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2739,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [1, 4, 1, 2, 1, 4, 1, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 3, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2740,
            rows: [
                [3, 1, 2, 1, 2, 3, 2, 1],
                [5, 2, 1, 3, 1, 2, 1],
                [3, 1, 2, 2, 1, 3, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 2, 1, 2, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
    ]
}
