// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch65 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1281,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, 2, 3, 2, 1, nil, nil, 3],
                [1, 5, 2, 5, 5, nil, 4],
                [nil, 2, 4, 4, 3, nil, nil, 3],
                [1, 1, 2, 1, 4, nil, 1],
                [3, 1, 1, 1, 2, 3, 1, nil],
                [2, 1, 1, 1, 2, nil, 2],
                [2, 3, 3, 3, 3, 3, 1, nil],
                [1, 1, 2, 1, 2, nil, 2],
                [nil, 2, 6, 1, 2, nil, nil, 1],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 2, 1, 1, 2, nil, nil, 1],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1282,
            rows: [
                [nil, nil, 3, nil, nil, 1, nil, nil],
                [3, 2, 4, 1, 2, 2, 1],
                [1, 3, 1, 1, 1, 2, 2, 3],
                [1, 1, nil, 1, nil, 1, 3],
                [4, 1, 2, 1, 1, 2, 1, 4],
                [2, 1, nil, 3, nil, 3, 3],
                [5, 3, nil, 1, 2, nil, 2, 3],
                [2, nil, nil, 3, nil, nil, 3],
                [3, 3, nil, 3, 1, nil, 1, 3],
                [5, nil, nil, 3, nil, nil, 1],
                [1, 2, 3, nil, nil, 4, 4, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 3, nil, nil, 2, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1283,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, nil, 4, 1, 7, nil, nil],
                [nil, nil, 2, 2, 4, 1, nil, nil],
                [nil, nil, 1, 2, 4, nil, nil],
                [nil, nil, 4, 2, 2, 1, nil, nil],
                [nil, nil, 4, 1, 1, nil, nil],
                [nil, nil, 3, 1, 1, 4, nil, nil],
                [nil, nil, 1, 4, 5, nil, nil],
                [nil, nil, 1, 1, 4, 1, nil, nil],
                [nil, nil, 5, 1, 5, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1284,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, 3, 2, 4, 4, 2, nil],
                [nil, nil, 5, 1, 2, 2, nil, nil],
                [nil, 1, 2, 3, 2, 4, nil],
                [nil, 1, 2, 1, 1, 2, 1, nil],
                [1, 1, 2, 1, 1, 2, 1],
                [nil, 1, 1, 2, 3, 3, 1, nil],
                [2, 1, 3, 1, 2, 2, 3],
                [nil, 2, 1, 2, 1, 2, 1, nil],
                [nil, 2, 1, 2, 2, 1, nil],
                [nil, 2, 3, 2, 4, 2, 2, nil],
                [nil, 1, 2, 2, 4, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1285,
            rows: [
                [1, 2, 2, 2, 3, 4, 4, 1],
                [5, 5, 1, 1, 3, 6, 6],
                [3, 3, 2, 2, 1, 2, 1, 1],
                [2, 1, 1, 2, 2, 1, 3],
                [3, 3, 1, 2, 1, 1, 2, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1286,
            rows: [
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, 4, 2, 1, 5, nil, nil, 1],
                [2, 4, 3, 4, 1, nil, 1],
                [nil, 1, 3, 2, 2, nil, nil, 2],
                [3, 3, 3, 2, 2, nil, 2],
                [1, 1, 3, 3, 2, 5, 1, nil],
                [3, 2, 2, 1, 2, nil, 2],
                [2, 1, 5, 3, 2, 2, 1, nil],
                [3, 3, 3, 1, 3, nil, 3],
                [nil, 1, 4, 4, 1, nil, nil, 2],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 3, 1, 1, 1, nil, nil, 1],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1287,
            rows: [
                [nil, nil, 3, nil, nil, 1, nil, nil],
                [3, 1, 5, 5, 1, 1, 1],
                [2, 4, 2, 2, 1, 1, 2, 1],
                [1, 5, nil, 3, nil, 2, 2],
                [1, 1, 2, 2, 2, 2, 1, 2],
                [2, 1, nil, 3, nil, 3, 3],
                [1, 4, nil, 3, 6, nil, 3, 3],
                [1, nil, nil, 4, nil, nil, 4],
                [4, 3, nil, 1, 1, nil, 1, 2],
                [2, nil, nil, 3, nil, nil, 1],
                [3, 3, 1, nil, nil, 3, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1288,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil],
                [nil, nil, nil, nil, 2, 1, nil, nil],
                [nil, nil, nil, nil, 2, 1, nil],
                [nil, nil, nil, nil, nil, 6, 6, nil],
                [nil, nil, nil, nil, nil, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, 1, 2, nil],
                [1, 1, nil, nil, 1, 2, nil],
                [nil, 2, 1, nil, nil, 2, 3, nil],
                [1, 2, nil, nil, 2, 1, nil],
                [nil, 1, 1, nil, nil, 2, 2, nil],
                [1, 1, nil, nil, 1, 1, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, 1, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1289,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [2, 2, 1, 1, nil, nil, nil],
                [3, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, 5, 1, 1],
                [1, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 5, 5, 3, 1],
                [3, nil, nil, nil, 1, nil, nil, 4],
                [2, 3, 2, 3, nil, nil, nil],
                [3, nil, nil, nil, 5, nil, nil, 5],
                [3, 4, 6, 4, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, 4],
                [nil, nil, nil, 3, 4, 3, 4],
                [nil, nil, nil, 3, nil, nil, nil, 3],
                [nil, nil, nil, 1, 1, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1290,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 5, 3, 3, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 4, 2, 1, 1, nil, nil],
                [nil, nil, 5, 1, 2, nil, nil],
                [nil, nil, 1, 1, 5, 5, nil, nil],
                [nil, nil, 3, 1, 3, nil, nil],
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, nil, 2, 1, 4, nil, nil],
                [nil, nil, 2, 6, 2, 2, nil, nil],
                [nil, nil, 1, 1, 6, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1291,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 2, 1, 3, 1, nil, nil],
                [nil, 4, 1, 3, 1, 1, nil],
                [nil, nil, 3, 3, 1, 2, nil, nil],
                [nil, 2, 4, 1, 4, 2, nil],
                [nil, 6, 1, 2, 1, 2, 2, nil],
                [4, 2, 1, 2, 2, 1, 2],
                [nil, 1, 4, 1, 1, 1, 1, nil],
                [1, 3, 2, 1, 1, 1, 2],
                [nil, 2, 2, 1, 1, 6, 4, nil],
                [nil, 2, 2, 1, 2, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1292,
            rows: [
                [2, 1, 3, 2, 5, 5, 5, 1],
                [3, 1, 3, 3, 3, 3, 1],
                [2, 1, 6, 2, 3, 3, 4, 2],
                [2, 1, 2, 1, 2, 2, 1],
                [1, 6, 1, 1, 2, 1, 2, 1],
                [2, 1, 6, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1293,
            rows: [
                [1, 2, nil, 1, 2, nil, 2, 2],
                [1, 2, nil, 1, nil, 2, 1],
                [nil, 1, nil, 2, 2, nil, 3, nil],
                [3, 1, 6, 5, 1, 1, 1],
                [nil, 4, nil, 2, 5, nil, 1, nil],
                [1, 2, 2, 1, 2, 1, 2],
                [nil, 2, nil, 1, 4, nil, 4, nil],
                [1, 1, nil, nil, nil, 1, 2],
                [nil, 4, nil, 2, 2, nil, 1, nil],
                [2, 1, nil, nil, nil, 4, 2],
                [1, 1, 2, nil, nil, 1, 2, 1],
                [1, 2, nil, nil, nil, 2, 1],
                [1, 1, 2, nil, nil, 1, 6, 1],
                [1, 2, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1294,
            rows: [
                [nil, nil, 2, 4, 2, 1, nil, nil],
                [nil, nil, 3, 1, 2, nil, nil],
                [nil, nil, 2, 3, 1, 3, nil, nil],
                [nil, nil, 3, 1, 3, nil, nil],
                [nil, nil, 3, 1, 2, 6, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 5, 2, 2, 1, nil, nil],
                [nil, nil, 2, 1, 3, nil, nil],
                [nil, nil, 1, 1, 1, 4, nil, nil],
                [nil, nil, 2, 6, 1, nil, nil],
                [nil, nil, 1, 6, 2, 1, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 4, 1, 2, 1, nil, nil],
                [nil, nil, 3, 1, 2, nil, nil],
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, nil, 1, 1, 3, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1295,
            rows: [
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil, 3],
                [2, 2, 3, 2, 2, nil, 2],
                [nil, 1, 3, 1, 2, nil, nil, 4],
                [3, 1, 1, 1, 3, nil, 3],
                [1, 5, 3, 1, 2, 2, 1, nil],
                [2, 1, 2, 3, 3, nil, 3],
                [3, 2, 3, 2, 1, 2, 2, nil],
                [2, 1, 1, 2, 5, nil, 1],
                [nil, 2, 2, 2, 3, nil, nil, 3],
                [nil, nil, 5, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil, 1],
                [nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, nil, 6, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1296,
            rows: [
                [nil, nil, 1, nil, nil, 5, nil, nil],
                [1, 3, 3, 2, 2, 5, 1],
                [1, 1, 1, 1, 2, 3, 3, 1],
                [3, 3, nil, 3, nil, 2, 2],
                [3, 1, 1, 3, 3, 3, 6, 1],
                [2, 1, nil, 2, nil, 2, 2],
                [1, 1, nil, 1, 2, nil, 1, 2],
                [1, nil, nil, 3, nil, nil, 2],
                [2, 2, nil, 2, 3, nil, 3, 3],
                [1, nil, nil, 4, nil, nil, 1],
                [2, 1, 6, nil, nil, 1, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 2, 4, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1297,
            rows: [
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, 3, 4, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, 6, 1, nil],
                [nil, nil, nil, nil, nil, 4, 1, nil],
                [nil, nil, nil, nil, nil, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, nil, nil, 2, 1, nil],
                [1, 1, nil, nil, 3, 2, nil],
                [nil, 1, 1, nil, nil, 1, 4, nil],
                [3, 4, nil, nil, 2, 2, nil],
                [nil, 2, 1, nil, nil, 1, 1, nil],
                [3, 1, nil, nil, 1, 1, nil],
                [nil, 1, 4, nil, nil, 5, 4, nil],
                [4, 4, nil, nil, 2, 5, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1298,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [2, 2, 5, 6, nil, nil, nil],
                [2, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, 4, 1, 4],
                [1, nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, nil, 3, 3, 1, 1],
                [1, nil, nil, nil, 3, nil, nil, 4],
                [4, 2, 5, 1, nil, nil, nil],
                [2, nil, nil, nil, 2, nil, nil, 1],
                [3, 1, 3, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, 7],
                [nil, nil, nil, 1, 3, 1, 1],
                [nil, nil, nil, 1, nil, nil, nil, 1],
                [nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1299,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 3, 3, 1, nil, nil],
                [nil, nil, 2, 3, 3, nil, nil],
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 1, 1, 1, 3, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 1, 4, 1, 1, nil, nil],
                [nil, nil, 5, 1, 4, nil, nil],
                [nil, nil, 1, 2, 6, 6, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1300,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 2, 2, nil, nil],
                [nil, 2, 1, 2, 1, 3, nil],
                [nil, nil, 1, 5, 2, 2, nil, nil],
                [nil, 2, 1, 3, 3, 1, nil],
                [nil, 1, 2, 2, 2, 1, 2, nil],
                [1, 1, 1, 3, 3, 3, 2],
                [nil, 1, 3, 3, 5, 5, 2, nil],
                [1, 2, 2, 2, 4, 1, 1],
                [nil, 2, 1, 1, 2, 1, 2, nil],
                [nil, 4, 1, 2, 1, 1, nil],
                [nil, 1, 4, 2, 1, 2, 1, nil],
                [nil, 1, 4, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
    ]
}
