// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch136 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2701,
            rows: [
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, 1, 5, 1, nil, nil],
                [nil, nil, nil, 3, 7, nil, nil, nil],
                [nil, nil, 4, 1, 2, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, nil, 3, 5, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2702,
            rows: [
                [nil, 3, 3, nil, nil, 1, 4, nil],
                [1, nil, nil, nil, nil, nil, 4],
                [1, 3, nil, nil, nil, nil, 4, 3],
                [1, nil, nil, nil, nil, nil, 4],
                [2, 1, nil, nil, nil, nil, 4, 6],
                [1, nil, nil, nil, nil, nil, 4],
                [3, 2, nil, nil, nil, nil, 2, 1],
                [4, nil, nil, nil, nil, nil, 1],
                [4, 1, nil, nil, nil, nil, 3, 3],
                [1, nil, nil, nil, nil, nil, 6],
                [6, 1, nil, nil, nil, nil, 2, 1],
                [2, 4, nil, nil, nil, 2, 3],
                [3, 1, nil, nil, nil, nil, 4, 1],
                [4, 1, nil, nil, nil, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2703,
            rows: [
                [nil, nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 5, nil, nil, 3, nil, 1, nil],
                [3, nil, nil, 1, nil, nil, 3],
                [nil, 4, nil, nil, 1, nil, 6, nil],
                [2, nil, nil, 4, nil, nil, 2],
                [nil, 4, nil, nil, 2, nil, 4, nil],
                [nil, 1, nil, 4, nil, 3, nil],
                [nil, 1, nil, nil, 2, nil, 4, nil],
                [nil, 3, nil, 1, nil, 1, nil],
                [nil, nil, 2, 1, 5, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 4, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2704,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, 5, nil, nil],
                [nil, nil, nil, nil, 3, 1, nil, nil],
                [nil, nil, nil, nil, 6, 2, nil],
                [nil, nil, nil, nil, nil, 1, 5, nil],
                [nil, nil, nil, nil, nil, 1, 5],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 3, nil, nil, 2, 1, nil],
                [2, 5, nil, nil, 1, 3, nil],
                [nil, 2, 1, nil, nil, 1, 3, nil],
                [2, 5, nil, nil, 2, 4, nil],
                [nil, 1, 2, nil, nil, 3, 3, nil],
                [1, 6, nil, nil, 1, 3, nil],
                [nil, 1, 4, nil, nil, 1, 2, nil],
                [1, 1, nil, nil, 1, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2705,
            rows: [
                [1, 2, nil, nil, nil, nil, 1, 2],
                [1, 3, nil, nil, nil, 1, 2],
                [1, 3, nil, nil, nil, nil, 1, 6],
                [3, nil, nil, nil, nil, nil, 3],
                [2, 1, nil, nil, nil, nil, 3, 3],
                [1, nil, nil, nil, nil, nil, 1],
                [3, 1, nil, nil, nil, nil, 2, 4],
                [3, nil, nil, nil, nil, nil, 1],
                [5, 1, nil, nil, nil, nil, 2, 1],
                [2, nil, nil, nil, nil, nil, 1],
                [4, 1, nil, nil, nil, nil, 2, 2],
                [1, 2, nil, nil, nil, 1, 2],
                [1, 2, nil, nil, nil, nil, 1, 2],
                [1, 2, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2706,
            rows: [
                [1, nil, 5, nil, 1, nil, 2, nil],
                [nil, 7, nil, 1, nil, 3, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 3, nil, nil],
                [nil, 2, nil, nil, nil, 5, nil],
                [1, nil, nil, nil, nil, nil, nil, 4],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [nil, 2, nil, nil, nil, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2707,
            rows: [
                [1, 4, nil, nil, nil, nil, 1, 2],
                [3, 1, nil, nil, nil, 5, 1],
                [2, 4, nil, nil, nil, nil, 4, 6],
                [1, nil, nil, nil, nil, nil, 4],
                [3, 6, nil, nil, nil, nil, 1, 3],
                [4, nil, nil, nil, nil, nil, 3],
                [2, 1, nil, nil, nil, nil, 3, 2],
                [1, nil, nil, nil, nil, nil, 2],
                [1, 2, nil, nil, nil, nil, 2, 1],
                [2, nil, nil, nil, nil, nil, 2],
                [5, 1, nil, nil, nil, nil, 3, 1],
                [2, 1, nil, nil, nil, 1, 2],
                [1, 2, nil, nil, nil, nil, 3, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2708,
            rows: [
                [nil, 2, 1, nil, nil, 3, 1, nil],
                [7, nil, nil, nil, nil, nil, 1],
                [2, 4, nil, nil, nil, nil, 1, 2],
                [3, nil, nil, nil, nil, nil, 5],
                [3, 2, nil, nil, nil, nil, 1, 4],
                [1, nil, nil, nil, nil, nil, 4],
                [3, 2, nil, nil, nil, nil, 1, 1],
                [5, nil, nil, nil, nil, nil, 2],
                [1, 1, nil, nil, nil, nil, 2, 3],
                [2, nil, nil, nil, nil, nil, 1],
                [3, 2, nil, nil, nil, nil, 1, 1],
                [4, 2, nil, nil, nil, 6, 2],
                [3, 1, nil, nil, nil, nil, 2, 1],
                [2, 1, nil, nil, nil, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2709,
            rows: [
                [2, 1, nil, nil, nil, nil, 3, 1],
                [5, 1, nil, nil, nil, 2, 3],
                [2, 1, nil, nil, nil, nil, 3, 1],
                [4, nil, nil, nil, nil, nil, 2],
                [1, 3, nil, nil, nil, nil, 1, 7],
                [3, nil, nil, nil, nil, nil, 1],
                [2, 1, nil, nil, nil, nil, 2, 4],
                [2, nil, nil, nil, nil, nil, 1],
                [3, 3, nil, nil, nil, nil, 1, 2],
                [1, nil, nil, nil, nil, nil, 6],
                [1, 2, nil, nil, nil, nil, 2, 1],
                [2, 1, nil, nil, nil, 4, 1],
                [2, 1, nil, nil, nil, nil, 2, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2710,
            rows: [
                [nil, nil, 3, nil, nil, 2, nil, nil],
                [nil, 4, 2, nil, 2, 1, nil],
                [nil, 6, 4, 1, 2, 1, 2, nil],
                [nil, 1, 1, nil, 3, 3, nil],
                [nil, 1, 5, 5, 1, 2, 1, nil],
                [nil, 4, 2, nil, 1, 3, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 4, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2711,
            rows: [
                [1, 6, 1, 3, 1, 3, 1, 4],
                [3, nil, nil, 1, nil, nil, 2],
                [1, nil, nil, 4, 2, nil, nil, 3],
                [nil, nil, nil, 1, nil, nil, nil],
                [3, nil, nil, 1, 2, nil, nil, 3],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 5, 4, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 7, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2712,
            rows: [
                [3, nil, nil, 4, nil, 4, 1, 4],
                [5, nil, 3, nil, 2, nil, 3],
                [2, nil, nil, 1, nil, nil, nil, 2],
                [6, 2, 1, nil, nil, nil, 2],
                [1, nil, nil, 3, nil, nil, nil, 2],
                [1, 3, 2, nil, nil, nil, 6],
                [nil, nil, nil, 2, nil, 1, 3, nil],
                [nil, nil, 3, nil, 2, nil, nil],
                [nil, nil, nil, 5, nil, 5, 2, nil],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, nil, nil, 1, nil, 3, 4, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, 2, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2713,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 5, nil, 2, nil, 1, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, 2, nil, 1, nil, 3, nil],
                [2, 1, 5, 1, 3, 6, 1, 4],
                [3, nil, 2, nil, 1, nil, 2],
                [3, 1, 3, 7, 2, 1, 1, 3],
                [1, nil, 3, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2714,
            rows: [
                [1, nil, 4, nil, 2, nil, 3, nil],
                [nil, 1, nil, 3, nil, 3, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, 6, nil, nil],
                [nil, 4, nil, nil, nil, 1, nil],
                [3, nil, nil, nil, nil, nil, nil, 4],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [nil, 4, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2715,
            rows: [
                [nil, 2, 4, nil, nil, 2, 3, nil],
                [2, nil, nil, nil, nil, nil, 1],
                [4, 2, nil, nil, nil, nil, 1, 3],
                [2, nil, nil, nil, nil, nil, 3],
                [3, 2, nil, nil, nil, nil, 1, 5],
                [1, nil, nil, nil, nil, nil, 4],
                [2, 1, nil, nil, nil, nil, 4, 2],
                [1, nil, nil, nil, nil, nil, 2],
                [2, 1, nil, nil, nil, nil, 3, 2],
                [7, nil, nil, nil, nil, nil, 1],
                [4, 6, nil, nil, nil, nil, 2, 1],
                [2, 3, nil, nil, nil, 2, 4],
                [4, 2, nil, nil, nil, nil, 1, 2],
                [1, 2, nil, nil, nil, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2716,
            rows: [
                [2, 1, nil, nil, nil, nil, 4, 4],
                [1, 2, nil, nil, nil, 1, 5],
                [1, 2, nil, nil, nil, nil, 4, 4],
                [1, nil, nil, nil, nil, nil, 2],
                [1, 3, nil, nil, nil, nil, 1, 2],
                [5, nil, nil, nil, nil, nil, 2],
                [2, 3, nil, nil, nil, nil, 2, 6],
                [1, nil, nil, nil, nil, nil, 2],
                [1, 5, nil, nil, nil, nil, 3, 1],
                [2, nil, nil, nil, nil, nil, 5],
                [3, 1, nil, nil, nil, nil, 3, 1],
                [2, 3, nil, nil, nil, 1, 2],
                [1, 3, nil, nil, nil, nil, 1, 4],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2717,
            rows: [
                [nil, nil, nil, 2, 6, nil, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, 3, 1, 4, 5, nil, nil],
                [nil, 2, 3, 4, 1, 1, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, 1, 2, 3, 3, 7, nil],
                [nil, nil, 3, 5, 5, 1, nil, nil],
                [nil, nil, 3, 3, 2, nil, nil],
                [nil, nil, 1, 2, 1, 3, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2718,
            rows: [
                [nil, nil, 6, nil, nil, 1, nil, nil],
                [nil, 6, 1, nil, 3, 3, nil],
                [nil, 1, 5, 4, 2, 2, 1, nil],
                [nil, 4, 1, nil, 2, 1, nil],
                [nil, 2, 1, 2, 1, 4, 2, nil],
                [nil, 1, 2, nil, 1, 2, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2719,
            rows: [
                [nil, 1, nil, nil, nil, nil, 6, nil],
                [1, 4, nil, nil, nil, 3, 2],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [1, 2, nil, nil, nil, 4, 1],
                [nil, 3, nil, nil, nil, nil, 2, nil],
                [1, 4, nil, nil, nil, 5, 1],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [2, 4, nil, nil, nil, 4, 1],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [1, 4, nil, nil, nil, 1, 2],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2720,
            rows: [
                [nil, nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 5, nil, nil, 1, nil, 2, nil],
                [1, nil, nil, 3, nil, nil, 1],
                [nil, 1, nil, nil, 3, nil, 1, nil],
                [5, nil, nil, 5, nil, nil, 4],
                [nil, 1, nil, nil, 3, nil, 1, nil],
                [nil, 7, nil, 4, nil, 1, nil],
                [nil, 2, nil, nil, 1, nil, 2, nil],
                [nil, 1, nil, 3, nil, 2, nil],
                [nil, nil, 1, 2, 1, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 2, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
    ]
}
