// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch20 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 381,
            rows: [
                [nil, nil, 2, 2, 2, nil, nil, nil],
                [nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, 2, 3, 3, 3, nil, nil],
                [3, 3, 3, 3, 3, 3, nil],
                [nil, 1, 1, 1, 4, 4, nil, nil],
                [4, 4, 4, 4, 1, 1, nil],
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, 7, 5, 5, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, 6, 6, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 382,
            rows: [
                [nil, nil, nil, 2, 2, 2, 2, nil],
                [2, 2, 2, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [1, nil, nil, nil, 1, 1, 1, 1],
                [1, nil, nil, 5, 5, 5, 1],
                [1, nil, nil, nil, 1, 1, 3, 3],
                [3, nil, nil, 7, 7, 1, 1],
                [1, nil, nil, nil, 1, 1, 4, 4],
                [4, 4, nil, nil, nil, nil, nil],
                [6, nil, nil, nil, 1, 1, 5, 1],
                [1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil, nil],
                [1, 2, 2, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 383,
            rows: [
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 1, nil, 1, nil, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [2, 2, 2, 2, 5, 5, 1, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [1, 3, 3, 3, 3, 3, 7, 6],
                [6, nil, 3, nil, 3, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 384,
            rows: [
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [1, nil, 1, nil, 1, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [2, nil, nil, 2, 6, nil, nil, 6],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, 3, nil, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, 7, nil],
                [nil, nil, 7, nil, nil, 5, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, 2, nil, nil, 3, nil, nil],
                [nil, nil, 2, nil, 4, nil, nil],
                [nil, nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 385,
            rows: [
                [2, 2, 2, 2, 2, 2, 2, 2],
                [2, 2, 1, 1, 1, 4, 4],
                [4, 3, 3, 1, 1, 1, 1, 1],
                [1, 7, 5, 5, 5, 5, 5],
                [1, 1, 1, 1, 1, 1, 3, 7],
                [3, 3, 3, 3, 3, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 386,
            rows: [
                [1, 1, 1, nil, nil, 1, 1, 1],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 5, 5, 5, 2, nil, nil],
                [nil, 3, nil, 2, nil, 2, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 4, nil, 4, nil, 4, nil],
                [nil, nil, 4, 1, 3, 3, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 7, 7, 1, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 6, nil, nil, 6, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 387,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 6, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 5, 1, 1, 1, 2, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, 4, 1, 1, 2, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 7, 7, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 388,
            rows: [
                [nil, nil, 4, 4, 4, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 3, nil, 3, 3, nil, 3],
                [3, 3, nil, 2, 1, nil, 1],
                [nil, 1, 1, 1, 1, 6, 6, nil],
                [6, 2, 2, 2, 2, 2, nil],
                [nil, nil, 2, 2, nil, 5, 5, nil],
                [nil, 5, 5, nil, 1, 1, nil],
                [nil, nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 2, 2, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 389,
            rows: [
                [nil, 5, 5, nil, nil, 5, 5, nil],
                [5, nil, nil, nil, nil, nil, 5],
                [1, 4, nil, nil, nil, nil, 4, 4],
                [4, nil, nil, nil, nil, nil, 4],
                [4, 4, nil, nil, nil, nil, 3, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [3, 1, nil, nil, nil, nil, 1, 1],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 1, 2],
                [1, 7, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 390,
            rows: [
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 4, nil],
                [nil, nil, nil, nil, nil, nil, 4],
                [nil, 4, 4, 3, 3, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 7, nil, nil, nil, nil, nil, nil],
                [7, nil, nil, nil, nil, nil, nil],
                [nil, 6, 6, 3, 3, 5, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 391,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, 3, 3, nil, 3, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 2, 2, nil, 2, 4, nil],
                [nil, 4, 4, 4, 4, 4, 5, nil],
                [nil, 5, 1, nil, 1, 3, nil],
                [nil, 1, 1, 1, 1, 6, 6, nil],
                [nil, 7, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 392,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 6, 4, nil, nil, nil, nil],
                [nil, 2, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, nil, nil, nil, nil],
                [nil, 4, 4, 4, nil, nil, nil],
                [1, 1, 1, 3, 3, 3, 1, nil],
                [1, 1, 2, 2, 2, 2, nil],
                [2, 2, 2, 2, 3, 3, 3, nil],
                [1, 1, 1, 3, 3, 3, nil],
                [3, 3, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 7, 5, 7, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 393,
            rows: [
                [7, nil, 7, 2, 2, 2, nil, 2],
                [2, nil, nil, nil, nil, nil, 4],
                [4, 4, 4, 1, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 5, nil, 5, nil, 5, nil, 5],
                [5, nil, 5, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 3],
                [3, nil, 3, nil, 1, nil, 1],
                [nil, 2, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 3],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 394,
            rows: [
                [nil, nil, 2, 2, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, 3, 1, 1, nil, nil],
                [nil, nil, 1, 1, 7, 7, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 1, 1, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 4, 4, nil, nil],
                [nil, nil, 4, 4, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 5, 6, nil, nil],
                [nil, nil, 6, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 395,
            rows: [
                [nil, nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 4, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 3, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 3, 6, 3, 3, 3, nil],
                [nil, 3, 3, 3, 5, 5, 5, nil],
                [nil, 5, 2, 2, 2, 7, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 396,
            rows: [
                [nil, nil, 1, 1, 1, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 1, 1, 2, 2, 2, nil],
                [nil, 2, 2, 2, nil, nil, 2],
                [nil, nil, 2, 2, 2, 3, 3, nil],
                [nil, 3, 3, 3, nil, nil, 3],
                [nil, 1, nil, nil, 4, 4, 4, nil],
                [nil, 5, 5, 5, 5, 4, nil],
                [nil, 2, nil, nil, 2, 2, 2, nil],
                [nil, 6, 6, 1, 1, 1, nil],
                [nil, nil, 7, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 397,
            rows: [
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, nil, 3],
                [3, nil, 1, 1, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 1, 1, nil, 2],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [4, 4, 4, nil, 3, 3, 3],
                [5, 5, 5, 5, 5, 5, 2, 2],
                [2, 2, 2, nil, 2, 2, 1],
                [nil, 1, 1, nil, nil, 3, 3, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, 7, nil, nil, 3, 3, nil],
                [nil, nil, 2, 2, 6, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 398,
            rows: [
                [nil, 1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil],
                [nil, 6, 6, nil, nil, nil, nil, nil],
                [nil, nil, 6, 6, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 3, 2, nil, nil, nil],
                [nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil, nil],
                [nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, nil, 3, 3, nil, nil],
                [nil, nil, nil, 5, 5, 5, nil],
                [nil, nil, nil, nil, 5, 5, nil, nil],
                [nil, nil, nil, 3, 3, 3, nil],
                [nil, nil, nil, nil, 3, 7, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 399,
            rows: [
                [nil, nil, 1, nil, nil, 1, 1, nil],
                [nil, 1, 1, nil, nil, 5, 5],
                [5, nil, nil, 3, 3, 3, nil, nil],
                [3, 3, nil, 3, nil, nil, nil],
                [3, nil, nil, 2, 4, 4, nil, nil],
                [1, 2, nil, 2, nil, nil, nil],
                [2, nil, 2, 2, 2, 1, 7, nil],
                [nil, 4, nil, nil, 4, nil, 4],
                [4, nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, nil, 1, nil, 1],
                [nil, 1, 1, nil, nil, nil, 2, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, 2, 2, nil, nil, nil, 2, nil],
                [nil, nil, 6, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 400,
            rows: [
                [nil, nil, nil, nil, 4, 4, 3, nil],
                [nil, nil, 3, 1, 1, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, nil, 2, 2, 2, 2, 2, nil],
                [nil, 5, 5, 5, 5, 6, nil],
                [nil, 6, 6, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 3, 3, 3, 3, nil, nil],
                [3, 3, 3, 4, 4, nil, nil],
                [2, 2, 4, 4, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
    ]
}
