// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch80 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1581,
            rows: [
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [nil, 1, 1, 2, 2, 3, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [5, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 2, 5, 5, 1, 7, 1],
                [nil, 1, nil, nil, nil, nil, 1],
                [nil, 1, 2, 2, 2, 5, 2, 1],
                [nil, 2, nil, nil, nil, nil, 5],
                [nil, nil, nil, 2, 1, 2, 2, nil],
                [nil, 4, 4, nil, nil, nil, nil],
                [nil, nil, nil, 1, 2, 1, 2, nil],
                [nil, 5, 2, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1582,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, 1, 3, nil, nil, nil, nil],
                [2, 1, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, nil, 2, 3, nil],
                [1, 1, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, nil, 2, 1, nil],
                [nil, nil, nil, 1, 1, nil, 2, 3],
                [nil, 2, 4, nil, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, 3, 6],
                [nil, 2, 2, nil, nil, nil, nil],
                [2, 2, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [2, 1, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, nil, 3, 2, nil],
                [nil, nil, nil, nil, nil, nil, 4, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1583,
            rows: [
                [1, 2, nil, 2, 2, nil, 1, 1],
                [4, nil, nil, 4, nil, nil, 1],
                [5, nil, nil, 1, nil, nil, 6, nil],
                [1, nil, nil, 2, nil, nil, 4],
                [1, nil, nil, 1, nil, nil, 1, nil],
                [1, nil, nil, 3, nil, nil, 3],
                [3, nil, nil, 2, nil, nil, 1, nil],
                [2, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 2, nil],
                [4, nil, nil, 2, nil, nil, 2],
                [1, nil, nil, 4, nil, nil, 2, nil],
                [2, nil, nil, 5, nil, nil, 2],
                [2, nil, nil, 2, nil, nil, 1, nil],
                [2, nil, nil, 2, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1584,
            rows: [
                [nil, nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 2, nil, nil, 1, nil, 2, nil],
                [1, nil, nil, 2, nil, nil, 1],
                [nil, 2, nil, nil, 2, nil, 1, nil],
                [4, nil, nil, 5, nil, nil, 1],
                [nil, 1, nil, nil, 4, nil, 4, nil],
                [nil, 2, nil, 5, nil, 3, nil],
                [nil, 3, nil, nil, 2, nil, 1, nil],
                [nil, 3, nil, 1, nil, 4, nil],
                [nil, nil, 1, 1, 1, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 4, 4, 1, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1585,
            rows: [
                [nil, nil, 5, 3, 1, nil, nil, nil],
                [nil, 4, nil, nil, 5, nil, nil],
                [nil, nil, 2, 3, 3, 3, 4, nil],
                [nil, 2, 2, 1, nil, nil, 2],
                [nil, nil, 4, 4, 1, 1, 2, nil],
                [nil, 4, 1, 2, nil, nil, 1],
                [nil, 4, nil, nil, 2, 2, 1, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 3, nil, nil, 3, 6, 6, nil],
                [nil, 1, 3, 4, 1, 4, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1586,
            rows: [
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, 1, 1, 2, 2, 4, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, 4, 4, 1, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, 2, 3, 1, 3, 5, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, 1, 2, 1, 2, 1, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1587,
            rows: [
                [nil, nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, 4, 4, 4, 2, nil],
                [nil, nil, nil, 3, 1, 1, nil, nil],
                [nil, 2, 2, 6, 1, nil, nil],
                [nil, nil, nil, 2, 2, 5, nil, nil],
                [nil, 2, 3, 1, 1, nil, nil],
                [nil, 1, 1, 2, 3, 4, nil, nil],
                [1, 4, 3, 3, 1, 3, nil],
                [nil, 1, 3, 1, 3, 3, nil, nil],
                [2, 2, 2, 1, 4, 2, nil],
                [nil, 1, 1, 3, 1, 1, nil, nil],
                [nil, 2, 4, 2, 1, 1, nil],
                [nil, 4, 4, 1, 1, 1, nil, nil],
                [nil, 2, 1, 1, 4, 1, nil],
                [nil, nil, 1, 2, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1588,
            rows: [
                [nil, 2, nil, 2, nil, 2, nil, nil],
                [nil, 1, nil, 7, nil, 2, nil],
                [nil, 1, nil, 1, nil, 1, nil, nil],
                [nil, 6, nil, 1, nil, 1, nil],
                [nil, 6, nil, 2, nil, 2, nil, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [nil, 1, nil, 2, nil, 2, nil, nil],
                [nil, 1, nil, 2, nil, 3, nil],
                [nil, 2, nil, 2, nil, 1, nil, nil],
                [nil, 3, nil, 4, nil, 4, nil],
                [nil, 1, nil, 2, nil, 1, nil, nil],
                [nil, 5, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1589,
            rows: [
                [nil, 3, 3, 1, 4, 1, 2, nil],
                [2, nil, nil, nil, nil, nil, 5],
                [nil, 5, nil, nil, nil, nil, 5, nil],
                [1, 4, 4, 4, 4, 2, 3],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [5, 1, 1, 2, 2, 2, 2],
                [nil, 1, 6, 6, 1, 2, 1, nil],
                [nil, 2, 1, 3, 1, 1, nil],
                [nil, 2, 2, 1, 1, 4, 1, nil],
                [nil, 4, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1590,
            rows: [
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 2, 3, 3, nil, nil],
                [nil, nil, 1, 1, 3, 3, nil, nil],
                [nil, 1, 3, 2, 1, 1, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 3, 4, 2, 2, 2, nil],
                [nil, 1, 3, 3, 1, 1, 2, nil],
                [1, 1, 3, 3, 1, 3, 3],
                [nil, 3, 1, 3, 1, 5, 1, nil],
                [1, 1, 3, 1, 2, 2, 1],
                [nil, 1, 1, 1, 2, 2, 1, nil],
                [nil, 1, 2, 2, 2, 2, nil],
                [nil, 3, 1, 3, 3, 1, 1, nil],
                [nil, 1, 1, 3, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1591,
            rows: [
                [6, nil, nil, nil, nil, nil, nil, 1],
                [nil, 4, nil, nil, nil, 5, nil],
                [nil, nil, 3, nil, nil, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 2, 4, 7, nil, nil],
                [nil, nil, 2, 2, 1, 3, nil, nil],
                [nil, 3, 2, 1, 1, 3, nil],
                [nil, 4, 5, 1, 1, 4, 1, nil],
                [nil, 1, 2, 5, 1, 1, nil],
                [nil, nil, 2, 1, 3, 1, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1592,
            rows: [
                [nil, 1, 2, nil, nil, 3, 1, nil],
                [1, 3, 3, 1, 1, 1, 5],
                [3, 3, 4, 1, 2, 3, 2, 2],
                [1, 4, 1, 2, 2, 1, 1],
                [1, 1, 1, 2, 2, 2, 3, 3],
                [3, 1, 1, 6, 3, 3, 3],
                [nil, 1, 2, nil, nil, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 4, nil, nil, 5, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1593,
            rows: [
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [6, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 3, 3, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2],
                [nil, 2, 1, 2, 2, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, 3, 3, 4, 1, nil],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, 3, 2, 2, 2, 4, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [5, nil, nil, nil, nil, nil, nil],
                [nil, 4, 1, 6, 3, 4, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1594,
            rows: [
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, nil, 1, nil, 1, nil, 2],
                [nil, 3, 4, nil, nil, 3, 2, nil],
                [3, 4, nil, nil, nil, 4, 2],
                [nil, 2, 1, nil, nil, 3, 3, nil],
                [3, 4, nil, nil, nil, 1, 3],
                [3, nil, 3, 2, 1, 1, nil, 1],
                [4, 2, nil, nil, nil, 1, 2],
                [4, nil, 1, 2, 1, 2, nil, 3],
                [4, 1, nil, nil, nil, 2, 1],
                [nil, 2, 2, nil, nil, 1, 2, nil],
                [2, nil, 1, nil, 4, nil, 1],
                [nil, 4, 1, nil, nil, 6, 6, nil],
                [2, nil, 1, nil, 1, nil, 2],
                [1, nil, nil, 2, 2, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1595,
            rows: [
                [nil, nil, nil, nil, 2, 1, 1, 2],
                [2, 2, 1, 2, 1, 2, 1],
                [3, 2, 3, 2, 1, 2, 1, 1],
                [3, 3, 3, 5, 4, 2, 1],
                [1, 1, 2, 2, 2, 1, 1, 2],
                [1, 1, 3, 1, 1, 2, 3],
                [nil, nil, nil, nil, 2, 1, 3, 3],
                [nil, nil, nil, nil, 1, 3, 4],
                [nil, nil, nil, nil, 3, 3, 1, 2],
                [nil, nil, nil, nil, 2, 6, 1],
                [nil, nil, nil, nil, 2, 1, 3, 1],
                [nil, nil, nil, nil, 1, 2, 2],
                [nil, nil, nil, nil, 2, 1, 4, 1],
                [nil, nil, nil, nil, 3, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1596,
            rows: [
                [nil, 2, nil, nil, nil, nil, 5, nil],
                [5, 1, 2, 1, 5, 1, 3],
                [nil, nil, 3, 3, 1, 2, nil, nil],
                [nil, 1, 2, 1, 2, 5, nil],
                [nil, nil, 7, 1, 2, 2, nil, nil],
                [nil, 1, 2, 1, 4, 1, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1597,
            rows: [
                [7, nil, nil, nil, nil, nil, nil, 1],
                [7, nil, 1, 2, 1, nil, 2],
                [nil, 1, 1, nil, nil, 1, 3, nil],
                [nil, 4, nil, nil, nil, 4, nil],
                [nil, 3, 1, nil, nil, 1, 1, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 4, 4, nil, nil, 3, 2, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 1, 3, nil, nil, 1, 3, nil],
                [nil, 3, nil, nil, nil, 2, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 5, 3, 2, nil, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, 1, 4, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1598,
            rows: [
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 3, 1, 1, nil, nil],
                [nil, nil, 1, 3, 1, 1, nil, nil],
                [nil, 2, 2, nil, 2, 3, nil],
                [nil, nil, 7, 1, 2, 1, nil, nil],
                [nil, 1, 1, nil, 3, 3, nil],
                [nil, 1, 1, nil, nil, 2, 4, nil],
                [1, 5, nil, nil, nil, 2, 2],
                [nil, 1, 4, nil, nil, 4, 1, nil],
                [1, 1, nil, nil, nil, 5, 2],
                [2, 1, nil, nil, nil, nil, 3, 3],
                [1, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 3, 5],
                [2, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1599,
            rows: [
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, 3, 1, 1, 1, 2, nil],
                [nil, 4, 1, 6, 7, 5, 1, nil],
                [1, 2, 3, 1, 2, 2, 5],
                [nil, 4, 1, 3, 3, 1, 3, nil],
                [3, 3, 1, 1, 3, 1, 1],
                [nil, 2, 2, 1, 2, 1, 1, nil],
                [nil, 2, 1, 2, 2, 1, nil],
                [nil, 2, 1, 2, 1, 2, 1, nil],
                [nil, 1, 1, 1, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1600,
            rows: [
                [nil, nil, 2, nil, nil, 2, 2, nil],
                [nil, 2, 2, nil, nil, 1, 3],
                [2, nil, nil, 1, 1, 2, nil, nil],
                [5, 1, nil, 2, nil, nil, nil],
                [3, nil, nil, 2, 4, 4, nil, nil],
                [4, 3, nil, 4, nil, nil, nil],
                [1, nil, 2, 2, 2, 2, 2, nil],
                [nil, 5, nil, nil, 5, nil, 1],
                [1, nil, 2, 3, 3, 1, 4, nil],
                [nil, 1, nil, nil, 4, nil, 1],
                [nil, 1, 3, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
    ]
}
