// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch26 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 501,
            rows: [
                [3, nil, 3, 3, 3, 3, nil, 3],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 4, 4, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, 4, nil, 2, nil, 7],
                [2, nil, 2, nil, 2, nil, 2],
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [3, nil, 5, nil, 5, nil, 5],
                [nil, 5, nil, 1, nil, 1, nil, 1],
                [3, nil, 3, nil, 3, nil, 2],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 502,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, 1, 5, nil, nil],
                [5, 5, nil, 5, 2, nil, nil],
                [nil, 2, 2, nil, 2, 1, nil, nil],
                [1, 1, nil, 1, 2, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [1, 3, nil, 2, 2, nil, nil],
                [nil, 2, 2, nil, 2, 2, nil, nil],
                [2, 2, nil, 2, 6, nil, nil],
                [nil, 3, 3, nil, 3, 7, nil, nil],
                [4, 4, nil, 4, 4, nil, nil],
                [nil, 1, 1, nil, 1, 3, nil, nil],
                [3, 3, nil, 3, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 503,
            rows: [
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, 3, 3, nil, nil, nil, nil],
                [nil, nil, 3, 3, nil, nil, nil, nil],
                [nil, 3, 3, 3, nil, nil, nil],
                [nil, nil, 3, 3, nil, nil, nil, nil],
                [nil, 3, 2, 2, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, nil],
                [2, 4, 4, 4, 4, 4, nil],
                [4, 2, 1, 2, 2, 1, 1, nil],
                [1, 1, 1, 2, 2, 2, nil],
                [2, 2, 2, 2, 2, 5, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 2, 2, 7, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 504,
            rows: [
                [nil, 4, nil, nil, nil, nil, 4, nil],
                [4, nil, nil, 4, nil, nil, 7],
                [7, 1, 1, 1, 1, 1, 1, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [1, 5, 5, 1, 2, 2, 2, 2],
                [2, nil, nil, 2, nil, nil, 2],
                [nil, 2, nil, 2, nil, nil, 2, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, 1, nil, 3, nil, nil, 1, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 5, nil, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil, nil],
                [nil, 5, 6, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 505,
            rows: [
                [1, 3, 3, 3, 3, 3, 3, 3],
                [2, nil, nil, nil, nil, nil, 2],
                [5, nil, nil, 5, 4, 4, 4, 4],
                [4, nil, nil, nil, 1, 2, 2],
                [2, nil, nil, 2, 2, 1, 7, 5],
                [1, nil, nil, nil, 1, 1, 1],
                [2, nil, nil, nil, nil, nil, 2, 2],
                [2, 2, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, 1, 5],
                [5, 5, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 6, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 506,
            rows: [
                [nil, nil, 5, 5, nil, nil, nil, nil],
                [nil, 5, 1, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [7, 1, 1, 4, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, 2, 2, 2],
                [2, 2, 2, 2, 2, 3, 2, 2],
                [2, 2, 2, 3, 3, 3, 3],
                [4, 4, 3, 3, 3, 3, 1, 1],
                [1, 6, 4, 4, 3, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 507,
            rows: [
                [5, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 2, nil],
                [2, nil, 3, nil, 3, nil, 3, nil],
                [nil, 3, nil, 3, nil, 4, nil],
                [4, nil, 4, nil, 4, nil, 4, nil],
                [nil, 1, nil, 5, nil, 5, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 5, nil, 5, nil, 5, nil],
                [3, nil, 3, nil, 3, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 1, 1, 1, 1, 1, 2, 2],
                [6, 1, 1, 1, 1, 6, 1],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 508,
            rows: [
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [nil, 3, 3, 5, 5, 5, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, 3],
                [nil, 3, nil, nil, nil, nil, 3],
                [nil, 3, 3, 3, 5, 5, 5, 7],
                [nil, 7, nil, nil, nil, nil, 7],
                [nil, nil, nil, 4, 4, 4, 4, nil],
                [nil, 2, 2, nil, nil, nil, nil],
                [nil, nil, nil, 6, 2, 2, 2, nil],
                [nil, 2, 2, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 4
        ),
        LevelTemplate(
            levelNumber: 509,
            rows: [
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, nil, nil, 5, 5, nil, nil],
                [nil, nil, nil, nil, 5, 6, nil, nil],
                [nil, nil, nil, nil, 3, 3, nil],
                [nil, nil, nil, nil, nil, 3, 3, nil],
                [nil, nil, nil, nil, nil, 1, 7],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 7, 1, nil, nil, 1, 1, nil],
                [1, 2, nil, nil, 2, 2, nil],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [2, 3, nil, nil, 3, 3, nil],
                [nil, 3, 4, nil, nil, 4, 4, nil],
                [4, 4, nil, nil, 1, 3, nil],
                [nil, 3, 3, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, 1, 1, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 510,
            rows: [
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [3, 3, nil, nil, 3, 3, nil],
                [nil, 3, 3, nil, nil, 3, 2, nil],
                [2, 2, nil, nil, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 5, nil, 5, nil, 5, nil],
                [5, nil, 5, nil, 4, nil, 4, nil],
                [nil, 4, nil, 7, nil, 6, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 511,
            rows: [
                [4, 4, 4, nil, nil, 4, 4, 1],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, nil, 6, nil, 2, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, 6, 5, 5, nil, nil],
                [nil, nil, 5, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 2, nil, nil, 3, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 512,
            rows: [
                [nil, 2, 2, nil, nil, 2, 1, nil],
                [1, nil, 1, nil, 1, nil, 1],
                [2, nil, nil, 1, 1, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [7, nil, nil, nil, nil, nil, 7],
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, nil, 2, nil, nil, 6, nil, nil],
                [nil, nil, 3, nil, 4, nil, nil],
                [nil, nil, 4, nil, nil, 3, nil, nil],
                [nil, nil, 3, nil, 3, nil, nil],
                [nil, nil, nil, 3, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 513,
            rows: [
                [nil, nil, 1, 1, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [7, 2, 2, 2, 2, 2, nil],
                [nil, nil, 2, nil, 2, nil, nil, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, 2, nil, 3, nil, nil, nil],
                [nil, 3, nil, nil, 3, nil, nil],
                [nil, 3, 3, 3, nil, 5, 5, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, 5, 5, nil, 6, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 514,
            rows: [
                [1, nil, nil, 1, nil, 1, 1, 1],
                [2, nil, 2, nil, 3, nil, 3],
                [3, nil, nil, 3, nil, nil, nil, 3],
                [3, 3, 3, nil, nil, nil, 3],
                [1, nil, nil, 1, nil, nil, nil, 1],
                [5, 5, 5, nil, nil, nil, 2],
                [nil, nil, nil, 2, nil, 2, 2, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, nil, 7, nil, 7, 7, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 5, nil, 4, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 515,
            rows: [
                [2, nil, 2, nil, nil, 2, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
                [2, nil, nil, 2, 2, nil, nil, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, nil, 1, 1, 1, nil, 3],
                [3, nil, nil, 3, 3, nil, nil, 4],
                [4, nil, 1, nil, 3, nil, 3],
                [1, nil, nil, 6, 5, nil, nil, 3],
                [3, nil, 3, nil, 3, nil, 1],
                [5, nil, 5, nil, nil, 5, nil, 1],
                [1, nil, nil, nil, nil, nil, 5],
                [5, nil, 5, nil, nil, 5, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 516,
            rows: [
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [2, 1, 6, nil, nil, nil, 3],
                [3, nil, nil, nil, nil, nil, nil, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [3, nil, nil, nil, nil, nil, nil, 3],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, nil, 1, 1, 1, 1],
                [1, nil, nil, 1, 1, 1, 1],
                [2, nil, nil, nil, 2, 2, 2, 2],
                [2, nil, nil, 2, 2, 2, 4],
                [4, nil, nil, nil, 4, 4, 4, 3],
                [7, 7, nil, nil, nil, nil, nil],
                [5, nil, nil, nil, 5, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, nil],
                [1, 2, 4, nil, nil, nil, nil, nil],
                [4, 2, 2, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 517,
            rows: [
                [1, nil, nil, 1, 1, nil, nil, 1],
                [5, nil, 2, 3, 3, nil, 3],
                [nil, 3, nil, 3, 3, nil, 3, nil],
                [nil, 3, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 2, 5, nil, nil],
                [nil, nil, nil, 5, 4, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [2, 7, 2, 2, 2, 4, 4, 4],
                [4, nil, nil, nil, nil, nil, 4],
                [2, 2, 2, 2, 2, 2, 5, 6],
                [6, nil, nil, nil, nil, nil, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 518,
            rows: [
                [1, 1, nil, nil, nil, nil, 1, 5],
                [5, 5, 5, 5, 5, 1, 1],
                [1, 1, nil, nil, nil, nil, 3, 3],
                [3, 3, 3, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, 1, 2, 2, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, 1, 2, 1, 1, 1],
                [5, 5, nil, nil, nil, nil, 2, 2],
                [2, 2, 2, 2, 2, 2, 4],
                [1, 1, nil, nil, nil, nil, 1, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 2, nil, nil, nil, nil, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 519,
            rows: [
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [1, nil, 1, 1, nil, 1, nil],
                [1, nil, nil, nil, nil, nil, 1, nil],
                [1, 1, 1, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1, nil],
                [4, 4, 4, nil, nil, 4, 2],
                [nil, 2, 2, 2, 2, 2, 2, 2],
                [nil, 2, 3, nil, nil, 6, 6],
                [nil, 6, 6, 3, 3, 3, 3, 3],
                [nil, 3, 5, nil, nil, 5, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 520,
            rows: [
                [3, 3, 3, 3, 3, 3, 1, 1],
                [1, nil, nil, 1, nil, nil, 5],
                [5, 5, 5, 5, 1, 1, 1, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, 1, nil, nil, 4, nil, nil, 4],
                [2, 2, 1, 1, 1, 1, 1],
                [nil, 1, nil, nil, 1, nil, nil, 1],
                [1, 1, 1, 4, 4, 4, 2],
                [nil, 2, nil, nil, 7, nil, nil, 2],
                [2, nil, nil, 2, nil, nil, 2],
                [nil, 2, nil, nil, 2, nil, nil, 2],
                [2, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
    ]
}
