// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch93 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1841,
            rows: [
                [1, 2, nil, nil, nil, nil, 2, 2],
                [2, 1, nil, nil, nil, 3, 3],
                [3, 1, nil, nil, nil, nil, 1, 2],
                [3, nil, nil, nil, nil, nil, 3],
                [4, 4, nil, nil, nil, nil, 4, 1],
                [1, nil, nil, nil, nil, nil, 2],
                [5, 1, nil, nil, nil, nil, 2, 2],
                [2, 2, 1, 3, 3, 3, 3],
                [2, 1, nil, nil, nil, nil, 3, 1],
                [4, 4, 2, 1, 5, 5, 1],
                [nil, 1, 4, 1, 2, 2, 2, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [nil, 2, 2, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1842,
            rows: [
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, 1, 5, 1, 1, 3, 1, nil],
                [3, 1, 2, 2, 2, 3, 3],
                [nil, 4, 4, 4, 1, 2, 1, nil],
                [2, 2, 1, 3, 1, 1, 1],
                [nil, 1, 6, 4, 1, 3, 3, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 1, 4, 2, 1, 2, 1, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1843,
            rows: [
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, 4, nil, nil, nil],
                [nil, 4, nil, 4, nil, 3, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 2, nil, 1, nil, 3, nil],
                [2, 2, 1, 1, 2, 2, 2, 2],
                [1, nil, 1, nil, 6, nil, 1],
                [2, 2, 1, 5, 3, 5, 5, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1844,
            rows: [
                [1, 3, 2, 2, nil, 1, 3, nil],
                [2, nil, nil, 2, 2, 1, 3],
                [nil, nil, 2, 2, 5, 2, 3, 2],
                [nil, 3, 2, nil, 1, nil, nil],
                [1, nil, nil, nil, nil, nil, 2, 3],
                [nil, nil, 1, nil, 2, 1, 1],
                [nil, nil, nil, nil, 2, 1, nil, nil],
                [nil, 1, 6, 1, 1, nil, 3],
                [nil, nil, 1, nil, nil, nil, 3, 3],
                [2, 4, nil, 2, 1, 1, nil],
                [2, nil, 2, nil, 2, 3, 1, nil],
                [nil, 2, 1, nil, 5, 1, nil],
                [3, nil, 1, 5, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, 4],
                [1, nil, 3, nil, 3, 1, 2, nil],
                [1, nil, nil, 1, 1, 1, 1],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1845,
            rows: [
                [nil, nil, nil, 6, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, 2, 4, nil, nil],
                [nil, 4, 2, 1, 1, nil, nil],
                [nil, 2, 3, 2, 1, 3, 1, nil],
                [nil, 2, 1, 1, 4, 1, nil],
                [nil, 3, 3, 3, 1, 3, 3, nil],
                [nil, 3, 3, 1, 5, 1, nil],
                [nil, 2, 4, 1, 1, 1, 2, nil],
                [nil, 3, 1, 2, 1, 1, nil],
                [nil, 1, 2, 2, 1, 2, 4, nil],
                [nil, 2, 1, 1, 1, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1846,
            rows: [
                [2, nil, nil, 3, 1, nil, nil, 2],
                [5, nil, 2, 1, 1, nil, 2],
                [nil, 1, nil, 2, 2, nil, 2, nil],
                [nil, 2, 1, 2, 2, 2, nil],
                [nil, 2, nil, 2, 2, nil, 3, nil],
                [nil, 4, 4, 1, 1, 4, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, 1, 1, 5, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 3, 1, 1, nil, nil],
                [1, 7, 1, 5, 1, 1, 3, 3],
                [3, nil, nil, nil, nil, nil, 1],
                [4, 1, 1, 2, 1, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1847,
            rows: [
                [1, 1, nil, 2, 1, 3, 1, nil],
                [nil, 3, 3, 1, 1, 2, 2],
                [nil, 2, 1, 1, nil, nil, 2, nil],
                [nil, 1, nil, 1, nil, 2, 2],
                [1, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 1, nil, 5, nil, 2],
                [nil, nil, 1, 2, nil, 2, 3, 2],
                [nil, 3, 4, nil, nil, 4, nil],
                [3, 3, 1, nil, nil, nil, nil, nil],
                [4, nil, 1, nil, 1, nil, nil],
                [nil, 1, 4, nil, nil, 1, 1, nil],
                [3, 3, 3, 1, nil, nil, 4],
                [nil, nil, 2, nil, nil, nil, nil, 1],
                [nil, 3, 1, 2, 1, 1, 3],
                [1, 1, 1, 2, 1, 2, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1848,
            rows: [
                [1, 1, nil, nil, nil, nil, 2, 3],
                [nil, 3, nil, 3, nil, nil, nil],
                [3, 3, nil, 1, nil, nil, nil, nil],
                [nil, 2, nil, 1, 1, nil, 1],
                [nil, 2, 2, nil, nil, 1, 3, 2],
                [2, 1, 1, 1, 2, 4, 1],
                [4, 1, 4, 1, 4, 3, 1, 2],
                [1, 1, 4, 1, 4, 4, 1],
                [2, 1, 1, 1, 6, 5, 1, 4],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1849,
            rows: [
                [nil, 4, 2, nil, 2, 1, nil, nil],
                [1, nil, 2, 2, nil, 3, nil],
                [1, nil, nil, nil, nil, nil, 1, nil],
                [2, 2, 2, nil, nil, 5, 5],
                [5, nil, nil, nil, nil, nil, 3, nil],
                [2, 4, 4, nil, nil, 1, 2],
                [nil, 2, 2, 2, 1, 1, 3, 1],
                [nil, 3, 1, nil, nil, 4, 1],
                [nil, 3, 2, 3, 1, 5, 1, 1],
                [nil, 5, 1, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1850,
            rows: [
                [nil, 3, nil, 1, nil, 3, nil, 3],
                [5, nil, 2, nil, 1, nil, 1],
                [nil, 4, nil, 3, nil, 1, nil, 5],
                [1, nil, 1, nil, 1, nil, 3],
                [nil, 2, nil, 1, nil, 1, nil, 3],
                [1, nil, 1, nil, 4, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 2, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1851,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 2],
                [2, 1, nil, nil, nil, 5, 1],
                [nil, 2, 3, nil, nil, 3, 2, nil],
                [nil, 1, 2, nil, 1, 3, nil],
                [nil, 1, 1, 2, 1, 4, 1, nil],
                [nil, 2, 1, 3, 1, 2, nil],
                [nil, 1, 3, 3, 2, 2, 2, nil],
                [nil, 1, 1, 2, 3, 2, nil],
                [nil, 3, 1, 2, 1, 1, 2, nil],
                [nil, 1, 6, 2, 2, 1, nil],
                [nil, 5, 1, 2, 1, 2, 2, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1852,
            rows: [
                [nil, nil, 6, 1, 3, nil, 1, nil],
                [nil, 2, nil, nil, 4, 1, nil],
                [nil, nil, nil, 1, 1, nil, 2, nil],
                [nil, 4, 4, 2, nil, 1, nil],
                [nil, nil, 3, nil, 3, 1, nil, nil],
                [nil, 5, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, nil, 6, nil, nil],
                [nil, 1, 1, 1, 2, 1, nil],
                [nil, 1, 1, 4, 1, 1, 2, nil],
                [nil, 2, 3, 1, 1, 1, nil],
                [nil, 1, 4, 1, 2, 1, 1, nil],
                [nil, 1, 2, 1, 1, 1, nil],
                [nil, 1, 3, 3, 1, 2, 4, nil],
                [nil, 1, 2, 2, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1853,
            rows: [
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, 2, nil, 6],
                [1, 4, nil, 1, 3, nil, 1, 4],
                [1, 2, 2, 1, 1, 1, 1],
                [3, 1, nil, 3, 1, nil, 2, 2],
                [1, 2, 1, 1, 2, 3, 1],
                [2, 3, 1, 3, 1, 1, 2, 3],
                [1, nil, 1, 1, 4, nil, 1],
                [2, 2, 1, 4, 3, 1, 2, 2],
                [1, nil, 1, 2, 1, nil, 1],
                [nil, 4, 4, 3, 1, 3, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1854,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, 2, 2, 1, nil, 1],
                [nil, 2, nil, 2, 1, nil, 1, nil],
                [2, 1, 3, nil, 3, 3, 3],
                [nil, 3, 2, nil, 1, nil, nil, nil],
                [nil, 3, nil, nil, 2, 1, 1],
                [nil, 6, 5, nil, nil, 5, 1, nil],
                [1, 2, nil, nil, 2, 1, 2],
                [2, 2, 1, nil, nil, 1, nil, 4],
                [4, 4, 1, nil, 2, nil, 1],
                [2, 2, nil, nil, 1, 2, 2, 1],
                [1, 1, 1, 1, 1, 6, 1],
                [2, 1, 4, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1855,
            rows: [
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 4, 1, 1, nil, nil],
                [nil, nil, 4, 3, 3, 1, nil, nil],
                [nil, 6, 1, 3, 3, 2, nil],
                [nil, nil, 3, 3, 3, 1, nil, nil],
                [nil, 1, 1, 1, 1, 2, nil],
                [nil, nil, 4, 2, 2, 2, nil, nil],
                [nil, nil, 4, 1, 2, nil, nil],
                [nil, nil, 5, 4, 1, 4, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1856,
            rows: [
                [nil, 1, nil, 2, nil, 3, nil, 2],
                [2, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 3, nil],
                [nil, 3, nil, 3, nil, 7, nil],
                [3, nil, 2, nil, 1, nil, 2, nil],
                [nil, 4, nil, 2, nil, 3, nil],
                [nil, 2, nil, 3, nil, 2, nil, nil],
                [5, nil, 2, nil, 2, nil, nil],
                [nil, 2, nil, 2, nil, 3, nil, nil],
                [3, nil, 3, nil, 2, nil, nil],
                [nil, nil, 5, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1857,
            rows: [
                [2, 5, 5, 2, 1, 2, 1, 1],
                [3, nil, 3, nil, 3, 2, nil],
                [nil, nil, nil, nil, nil, 4, nil, 4],
                [2, nil, 1, nil, 3, 3, 2],
                [nil, 3, 5, 2, 2, 2, nil, 2],
                [2, 1, 1, 3, 3, 3, 1],
                [1, 2, nil, 2, nil, 1, nil, 1],
                [1, nil, nil, 1, 4, 1, nil],
                [nil, 4, 1, nil, 4, 1, 4, 1],
                [1, nil, 1, nil, 1, 1, 1],
                [nil, nil, 4, 1, 2, 4, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 4, nil, 1, 1, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1858,
            rows: [
                [nil, nil, 3, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, 6, nil, nil],
                [nil, nil, nil, 3, nil, nil, 3, nil],
                [nil, nil, 3, nil, nil, 5, nil],
                [nil, nil, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, 1, nil, nil, 5],
                [nil, nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, 4, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, 4],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 4, 4, nil, nil],
                [nil, 6, 4, 2, 4, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1859,
            rows: [
                [nil, 3, 1, nil, 5, nil, nil, nil],
                [1, 4, 2, 2, 1, 1, 3],
                [1, 1, 1, 1, nil, 3, nil, nil],
                [nil, 2, 1, 2, 3, nil, 3],
                [1, 1, 3, 2, nil, nil, nil, 2],
                [1, nil, nil, nil, nil, 2, 2],
                [1, 2, 2, nil, 2, nil, 3, 1],
                [2, 4, 4, nil, nil, nil, 2],
                [nil, 1, nil, nil, 3, 1, 2, 2],
                [nil, nil, 3, 3, 3, 1, 2],
                [1, 1, 2, nil, nil, nil, nil, nil],
                [nil, 1, 4, 4, 2, nil, 3],
                [nil, 2, 1, 3, nil, 1, 1, 1],
                [2, 1, 4, 2, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1860,
            rows: [
                [nil, 2, 2, nil, nil, 3, 3, nil],
                [4, 4, nil, nil, 1, 2, nil],
                [nil, 1, 1, nil, nil, 1, 2, nil],
                [2, 1, nil, nil, 2, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, nil, 2, nil, 3, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [2, nil, 2, nil, 3, nil, 1, nil],
                [nil, 1, nil, 2, nil, 2, nil],
                [2, nil, 2, nil, 2, nil, 3, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [5, nil, 2, nil, 5, nil, 1, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [1, nil, 2, nil, 1, nil, 1, nil],
                [nil, 2, nil, 5, nil, 3, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
    ]
}
