// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch51 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1001,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, 2],
                [2, nil, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, nil, 2, nil, nil],
                [2, 2, 2, nil, nil, 2, 2],
                [nil, 1, 1, 1, nil, nil, 3, nil],
                [3, nil, nil, nil, 3, nil, nil],
                [1, 4, 4, nil, nil, 4, 4, 4],
                [4, 4, nil, nil, 1, nil, 1],
                [1, nil, 2, nil, nil, nil, nil, 2],
                [1, nil, 1, nil, 1, 3, nil],
                [3, nil, 3, nil, nil, 1, nil, 1],
                [1, 1, 1, nil, 1, 1, 1],
                [6, 4, 4, 1, 1, 1, 6, 1],
                [5, 5, 5, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1002,
            rows: [
                [nil, 4, 4, 2, nil, nil, nil, 2],
                [nil, 2, nil, 1, 1, 1, nil],
                [nil, 1, 1, nil, nil, 4, 4, 4],
                [nil, nil, 4, 2, nil, nil, 2],
                [nil, 2, 2, nil, 1, 1, 3, 3],
                [3, 1, 5, nil, 5, 1, 1],
                [2, 2, 1, nil, 1, 6, nil, 1],
                [1, 1, 1, nil, 1, 1, nil],
                [1, 2, 6, nil, nil, 6, 6, 1],
                [2, nil, nil, nil, 2, nil, 2],
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [2, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [1, nil, 1, nil, nil, nil, 1],
                [nil, nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1003,
            rows: [
                [nil, 2, nil, nil, nil, 2, 2, nil],
                [nil, 3, 3, nil, nil, 1, nil],
                [nil, 1, 1, 2, 2, 2, nil, nil],
                [nil, 2, 2, nil, nil, 2, nil],
                [nil, nil, 2, 2, 2, 2, 2, nil],
                [nil, nil, 2, nil, 3, 3, nil],
                [nil, 3, nil, 3, 3, 3, 3, nil],
                [nil, 3, nil, 1, 5, 5, nil],
                [nil, 5, 5, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil, nil],
                [nil, 1, 1, nil, nil, 1, nil],
                [nil, 1, nil, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 4, 4, nil],
                [nil, 4, 4, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 6, 6, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1004,
            rows: [
                [1, 2, nil, nil, nil, nil, 2, 2],
                [nil, 2, 2, 2, 2, nil, nil],
                [3, 5, nil, 5, nil, 5, 5, 1],
                [nil, nil, nil, nil, nil, 1, nil],
                [1, 1, nil, nil, nil, 1, 3, 3],
                [nil, 3, 3, 3, nil, nil, nil],
                [3, nil, 3, 1, nil, 1, nil, 1],
                [1, nil, nil, 1, 1, nil, 1],
                [nil, nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, 1, nil, nil, nil, 1],
                [1, 1, nil, 1, 1, nil, nil, 1],
                [nil, nil, nil, 1, nil, 1, 1],
                [nil, 1, 1, 1, 1, 1, nil, 1],
                [nil, 1, 2, nil, nil, 2, 2],
                [nil, nil, nil, 2, 2, 2, 4, nil],
                [nil, 4, 6, 4, 6, 6, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1005,
            rows: [
                [2, nil, nil, 2, 2, 2, nil, 2],
                [2, 2, nil, 2, nil, nil, nil],
                [2, 2, nil, nil, 2, nil, 2, 2],
                [nil, 2, 2, nil, 3, 3, nil],
                [3, 3, nil, 3, nil, 3, nil, 3],
                [3, 3, nil, nil, 1, 1, 1],
                [1, 4, 4, 4, 4, nil, nil, 4],
                [4, 4, 4, 4, nil, 1, 1],
                [nil, nil, nil, 5, nil, nil, 1, 1],
                [nil, 1, 1, nil, 1, 1, 1],
                [6, nil, 6, nil, 6, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1006,
            rows: [
                [1, 1, 4, nil, 4, 4, 4, nil],
                [4, 4, 4, nil, nil, nil, nil],
                [nil, nil, nil, nil, 4, 1, 1, nil],
                [1, 1, 1, nil, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 3],
                [nil, nil, nil, nil, nil, nil, 3],
                [nil, 3, 3, 3, 3, nil, 3, 3],
                [3, nil, 2, nil, 2, nil, nil],
                [nil, 2, 2, 6, 6, 6, 1, 2],
                [1, 2, 2, nil, nil, 2, 2],
                [2, 2, 2, 1, 1, 1, 5, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1007,
            rows: [
                [nil, nil, nil, 2, nil, nil, 2, nil],
                [nil, 2, 2, 4, 2, 2, nil],
                [nil, 2, 2, nil, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, 3, 3, nil, 3, nil, 3, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, nil, nil, 3, nil],
                [nil, nil, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, 1, nil],
                [nil, 5, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 6, 1, 1, nil],
                [nil, 1, nil, nil, 1, 5, nil],
                [nil, 5, 5, 5, 4, 4, 4, nil],
                [nil, 4, 5, 1, 1, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1008,
            rows: [
                [nil, 1, nil, nil, nil, 1, 1, 1],
                [1, nil, 3, nil, nil, nil, nil],
                [3, nil, 3, 3, nil, 3, nil, 3],
                [3, nil, nil, nil, 3, 3, 3],
                [3, nil, 3, nil, 3, nil, nil, 1],
                [nil, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, nil, 1],
                [nil, nil, 1, nil, 1, 1, 4],
                [4, 4, 4, 4, 1, 1, 1, 1],
                [1, 1, 1, nil, 1, 1, 2],
                [2, 2, 2, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, 5, 5, 5, 6, 6, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1009,
            rows: [
                [1, 1, nil, nil, 3, 3, 3, 3],
                [3, nil, 3, 1, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 4, 4],
                [4, nil, 2, nil, 1, nil, nil],
                [nil, 1, nil, nil, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 5, 5, 5, 5, 4, 4, 4],
                [1, 1, 6, 3, 3, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, 1, nil, 1, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 4, 4, 1, 1, nil, nil],
                [nil, 4, 3, 3, 1, 1, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1010,
            rows: [
                [nil, 2, 2, nil, 2, 2, nil, nil],
                [nil, nil, 2, 2, 4, nil, 4],
                [4, 4, nil, nil, 1, nil, 1, 1],
                [1, 4, 4, nil, nil, nil, 2],
                [2, 2, 2, nil, nil, 2, nil, nil],
                [nil, 2, 2, 1, 5, nil, 5],
                [nil, 5, 3, nil, 3, 3, 3, 3],
                [3, 3, nil, nil, 3, 3, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, 1, nil, 6, 6, 6, 1],
                [1, nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1011,
            rows: [
                [nil, nil, 4, nil, 4, 1, 1, nil],
                [nil, 1, nil, 3, nil, nil, nil],
                [nil, 3, 3, 3, nil, 3, nil, nil],
                [nil, nil, 3, 3, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 2, 2, 1, nil, nil, nil],
                [nil, nil, 1, 2, nil, 2, 2, nil],
                [nil, nil, 2, 2, nil, nil, nil],
                [nil, 2, nil, 2, 5, nil, nil, nil],
                [nil, nil, 5, nil, nil, nil, nil],
                [nil, 5, 1, 1, 1, 1, 1, nil],
                [nil, 4, 4, 1, 1, 1, nil],
                [nil, 1, 4, 4, 4, 4, 4, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 6],
                [6, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1012,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 3, nil, 3, 3, nil, nil],
                [nil, 3, nil, nil, nil, 3, 3, nil],
                [3, 3, 6, nil, nil, nil, nil],
                [nil, 6, nil, nil, nil, 6, nil, nil],
                [nil, 1, nil, 1, 1, 1, 1],
                [nil, nil, 2, 2, nil, nil, nil, 2],
                [2, 2, nil, 2, 2, 2, 1],
                [nil, 1, nil, 5, nil, 5, 1, nil],
                [1, nil, nil, nil, 1, 1, 1],
                [nil, 1, 1, 1, 1, 4, 4, 3],
                [nil, 3, 2, 1, 1, 1, 4],
                [nil, 4, 1, 2, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1013,
            rows: [
                [nil, 1, 1, 1, nil, 1, 3, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 1, 2, 2, 5, 5, nil, nil],
                [nil, nil, 2, nil, nil, 2, nil],
                [nil, nil, nil, 2, 4, 4, 4, nil],
                [nil, nil, nil, 4, nil, 4, nil],
                [nil, nil, 4, nil, 4, 4, 4, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 2, 2, 5, nil, nil, 5, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, 1, 6, nil],
                [nil, 6, 1, 2, 2, 2, nil],
                [nil, 1, 1, 2, 2, 2, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 2, 2, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1014,
            rows: [
                [nil, nil, nil, nil, 3, 3, nil, nil],
                [nil, nil, 3, nil, 3, nil, nil],
                [nil, nil, nil, 1, nil, 1, 4, nil],
                [nil, 4, 4, 4, 1, nil, nil],
                [nil, nil, nil, 1, nil, nil, 1, nil],
                [1, 1, nil, 1, 2, 1, nil],
                [nil, nil, nil, nil, 1, 1, nil, nil],
                [2, nil, 2, 2, 2, nil, nil],
                [2, nil, nil, 2, nil, nil, 2, 2],
                [2, 2, 2, 2, 2, 2, 1],
                [nil, 1, 1, 6, 1, 1, 1, 1],
                [nil, 6, 6, 6, 2, 2, 2],
                [nil, 1, 1, 5, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1015,
            rows: [
                [nil, 2, nil, nil, 2, 2, nil, nil],
                [nil, 2, 2, 2, nil, 4, nil],
                [nil, 4, nil, 4, nil, 4, nil, nil],
                [nil, 4, 4, nil, nil, 4, nil],
                [nil, nil, 4, 6, 6, 6, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil],
                [nil, 1, nil, nil, 1, 1, nil, nil],
                [nil, nil, 2, nil, 2, 1, nil],
                [nil, 1, nil, 3, 3, nil, 3, nil],
                [nil, nil, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 2, 2, nil],
                [nil, 2, 2, 1, 1, 1, 1, nil],
                [nil, 5, 1, 1, 1, 3, nil],
                [nil, 3, nil, 3, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 2],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1016,
            rows: [
                [1, nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, nil, 1, 3, 3],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, nil, 1, nil, 1, nil, 1],
                [1, 1, 1, 1, 1, nil, 1, nil],
                [nil, 1, 1, 1, nil, nil, 1],
                [1, nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, 1, nil, nil, 3, 3],
                [3, 3, nil, nil, 3, 3, 3, 3],
                [6, 6, nil, nil, nil, 4, 4],
                [nil, 4, nil, 4, nil, 4, 2, nil],
                [2, 2, nil, nil, 2, nil, 2],
                [nil, nil, 4, nil, nil, nil, 4, nil],
                [nil, nil, nil, nil, 4, 4, nil],
                [2, 2, 2, 2, 5, 5, 5, 5],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1017,
            rows: [
                [nil, 1, nil, nil, 1, 1, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, 1, 1, 3, nil],
                [nil, nil, 3, nil, 1, 5, nil],
                [nil, 5, 5, nil, 1, nil, 1, nil],
                [nil, nil, 6, nil, 6, nil, nil],
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 4, nil, 4, 4, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 2, 2, 2, nil, 2, nil],
                [nil, 5, 5, nil, 5, 2, 3, nil],
                [nil, nil, 3, 3, 3, 3, nil],
                [nil, 3, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 3, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1018,
            rows: [
                [1, 1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, 1, nil, nil],
                [1, nil, nil, nil, 2, 2, nil, 2],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, 2, nil, nil, 2, 2, 2, 2],
                [2, 2, 2, 2, 2, 3, 1],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 5],
                [5, 5, 1, 1, 1, 1, 1],
                [1, 1, 4, 4, 4, 6, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 3, 4, 4, 3, 3, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1019,
            rows: [
                [nil, 3, 3, 3, 1, 1, nil, nil],
                [nil, nil, 1, nil, 1, 2, nil],
                [nil, 2, nil, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, 4, 4, nil, nil],
                [nil, nil, 4, nil, 4, 4, nil],
                [nil, 4, 4, 4, 2, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, nil, 2, 1, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, nil, 1, nil],
                [nil, nil, 5, 5, nil, 5, nil],
                [nil, 2, 2, 2, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 6, 6, 3, 3, 3, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1020,
            rows: [
                [5, 5, 3, nil, nil, nil, 3, nil],
                [4, 4, 4, nil, 4, nil, 4],
                [6, 6, 6, 1, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, 1, 3],
                [3, 2, 2, 2, 2, 2, nil, 2],
                [2, 1, 1, nil, 3, 3, nil],
                [3, 3, 3, 3, nil, nil, 1, 1],
                [nil, nil, 1, nil, nil, 1, nil],
                [2, 1, 4, nil, 4, 1, 1, nil],
                [1, 1, 1, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
    ]
}
