// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch138 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2741,
            rows: [
                [nil, 1, 3, nil, nil, 1, 2, nil],
                [nil, 3, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, nil, 4, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2742,
            rows: [
                [1, 2, nil, nil, nil, nil, 1, 2],
                [2, nil, nil, nil, nil, nil, 1],
                [nil, nil, 3, 1, 3, 1, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, nil, 4, 2, 1, 2, nil, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, 3, nil, nil, nil],
                [1, 3, nil, nil, nil, nil, 1, 3],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2743,
            rows: [
                [nil, 1, 4, nil, nil, 1, 1, nil],
                [4, nil, 1, nil, 2, nil, 3],
                [2, nil, nil, 1, 2, nil, nil, 1],
                [3, nil, nil, nil, nil, nil, 1],
                [3, nil, nil, 2, 3, nil, nil, 1],
                [2, nil, nil, nil, nil, nil, 3],
                [nil, 4, nil, nil, nil, nil, 3, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, 4, nil, 1, nil, nil],
                [nil, nil, 2, nil, nil, 1, nil, nil],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2744,
            rows: [
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [3, 1, nil, nil, nil, 2, 2],
                [nil, 4, nil, nil, nil, nil, 3, nil],
                [1, 2, nil, nil, nil, 2, 1],
                [nil, 3, nil, nil, nil, nil, 2, nil],
                [3, 1, nil, nil, nil, 3, 1],
                [nil, 2, nil, nil, nil, nil, 4, nil],
                [1, 3, nil, nil, nil, 2, 4],
                [nil, 4, nil, nil, nil, nil, 1, nil],
                [3, 3, nil, nil, nil, 1, 2],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2745,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 3, 1, nil, nil],
                [nil, nil, 3, 4, 2, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, nil, 3, 1, 2, nil, nil],
                [nil, nil, 1, 2, 1, 3, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, 2, 3, 1, 2, nil, nil],
                [nil, nil, 1, 4, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2746,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [1, 1, 6, 1, 2, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 1, 2, 1, 2, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2747,
            rows: [
                [nil, 1, nil, nil, 3, 4, 3, nil],
                [4, nil, nil, 2, 1, 2, nil],
                [4, nil, nil, 3, 2, 1, nil, nil],
                [2, nil, 1, 4, 2, nil, nil],
                [1, nil, nil, 2, 1, 2, nil, nil],
                [4, nil, 1, 2, 1, nil, nil],
                [3, nil, nil, 3, 1, 1, nil, nil],
                [3, nil, 1, 2, 1, 2, nil],
                [1, nil, nil, 2, 1, 3, nil, nil],
                [1, nil, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2748,
            rows: [
                [nil, 3, nil, 2, nil, 1, nil, 2],
                [2, nil, 3, nil, 3, nil, 3],
                [nil, 2, nil, 1, nil, 1, nil, 3],
                [3, nil, 2, nil, 1, nil, 2],
                [nil, 1, nil, 1, nil, 2, nil, 1],
                [1, nil, 2, nil, 1, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, 5, nil],
                [nil, nil, nil, nil, 2, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2749,
            rows: [
                [2, 1, 5, 2, 1, 4, 1, 3],
                [2, 1, 2, 3, 1, 2, 3],
                [1, 2, 1, 2, 3, 1, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 1, 4, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2750,
            rows: [
                [nil, 1, 2, 1, 2, 1, 5, nil],
                [nil, 1, 2, 1, 3, 1, nil],
                [nil, nil, 3, 3, 1, 5, nil, nil],
                [nil, nil, 5, 1, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 1, nil, nil, nil, nil, nil, nil],
                [2, 1, nil, nil, nil, nil, nil],
                [nil, 1, 2, nil, nil, nil, nil, nil],
                [nil, 3, 1, nil, nil, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2751,
            rows: [
                [3, nil, nil, nil, nil, nil, nil, 1],
                [2, 1, 1, 4, 4, 3, 3],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [2, 1, 2, 1, 2, 1, 2],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [1, 1, 2, 1, 2, 4, 2],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2752,
            rows: [
                [4, nil, nil, nil, 1, nil, nil, nil],
                [3, nil, nil, nil, 2, nil, nil],
                [nil, 4, nil, nil, 3, 1, nil, nil],
                [nil, 4, nil, 1, nil, 1, nil],
                [nil, 4, nil, nil, 1, 3, nil, nil],
                [nil, 2, nil, 2, nil, 4, nil],
                [nil, 2, nil, nil, 4, 3, nil, nil],
                [1, nil, nil, 3, 4, 4, nil],
                [nil, 1, nil, nil, 2, 1, nil, nil],
                [3, nil, nil, 1, 2, 1, nil],
                [1, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2753,
            rows: [
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 1, 4, 2, 1, 2, 4, nil],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, 2, 2, 2, 1, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 2, 1, 1, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, 1, 3, 3, 1, 2, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2754,
            rows: [
                [4, nil, nil, nil, nil, nil, nil, 2],
                [4, nil, 1, 3, 2, nil, 1],
                [nil, 3, 3, nil, nil, 1, 2, nil],
                [nil, 3, nil, nil, nil, 2, nil],
                [nil, 1, 2, nil, nil, 2, 1, nil],
                [nil, 2, nil, nil, nil, 3, nil],
                [nil, 1, 2, nil, nil, 1, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 1, 3, nil, nil, 1, 3, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, 3, nil, nil],
                [nil, nil, 1, 4, 1, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2755,
            rows: [
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, 2, nil, nil],
                [nil, nil, nil, 5, nil, nil, 1, nil],
                [nil, nil, 4, nil, nil, 1, nil],
                [nil, nil, nil, nil, 3, nil, nil, 3],
                [nil, nil, nil, 2, nil, nil, 1],
                [nil, nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 2, 1, 3, nil, nil],
                [nil, nil, 2, 1, 5, 1, nil, nil],
                [nil, 4, 1, 4, 1, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2756,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [2, 1, 1, 5, 1, 2, 1, 2],
                [nil, nil, nil, nil, 1, nil, nil],
                [3, 5, 1, 4, 1, 3, 1, 2],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 1, nil, 3, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2757,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, 2, nil, 1, nil, 2, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, 1, nil, 2, nil, 3, nil],
                [1, 2, 3, 5, 2, 1, 1, 3],
                [2, nil, 1, nil, 3, nil, 3],
                [1, 2, 1, 4, 1, 2, 1, 2],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2758,
            rows: [
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [2, 4, 1, 2, 1, 3, 2],
                [nil, nil, 2, 1, 4, 3, nil, nil],
                [nil, 1, 4, 2, 1, 2, nil],
                [nil, nil, 1, 3, 1, 2, nil, nil],
                [nil, 1, 4, 4, 3, 1, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, 2, 3, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2759,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 1, 3, 2, 3, 2, nil],
                [1, nil, nil, nil, nil, nil, 2],
                [5, nil, 2, 1, 3, 1, nil, 3],
                [4, nil, nil, nil, nil, nil, 1],
                [nil, 2, 1, 2, 1, 5, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 3, 1, nil, nil],
                [nil, nil, 3, 1, 4, nil, nil],
                [nil, nil, 1, 2, 1, 4, nil, nil],
                [nil, nil, 1, 1, 3, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2760,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 4, 1, 3, 1, nil, nil],
                [nil, 2, 1, 3, 1, nil, nil],
                [nil, 3, 2, 4, 5, 1, 4, nil],
                [nil, 3, 1, 4, 2, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
    ]
}
