// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch74 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1461,
            rows: [
                [3, 1, nil, nil, nil, nil, 3, 1],
                [3, 3, nil, nil, nil, 1, 4],
                [1, 1, nil, nil, nil, nil, 1, 4],
                [4, nil, nil, nil, nil, nil, 1],
                [2, 1, nil, nil, nil, nil, 2, 3],
                [3, nil, nil, nil, nil, nil, 1],
                [3, 1, nil, nil, nil, nil, 1, 3],
                [3, 2, 1, 2, 1, 1, 2],
                [2, 2, nil, nil, nil, nil, 5, 3],
                [5, 2, 1, 2, 1, 3, 3],
                [nil, 1, 1, 5, 1, 1, 2, nil],
                [nil, 1, nil, 2, nil, 3, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1462,
            rows: [
                [1, nil, nil, 1, 2, nil, nil, 1],
                [2, nil, 2, 2, 2, nil, 3],
                [nil, 1, nil, 2, 3, nil, 3, nil],
                [nil, 5, 5, 1, 5, 1, nil],
                [nil, 4, nil, 2, 1, nil, 2, nil],
                [nil, 5, 3, 3, 3, 4, nil],
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, 1, 4, 2, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 4, 1, nil, nil],
                [2, 1, 1, 1, 1, 5, 2, 2],
                [1, nil, nil, nil, nil, nil, 6],
                [1, 1, 1, 3, 1, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1463,
            rows: [
                [nil, 4, nil, 3, nil, 2, nil, 2],
                [1, nil, 5, nil, 1, nil, 3],
                [3, nil, 4, nil, 1, nil, 3, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [3, nil, 1, nil, 1, nil, 4, nil],
                [nil, 1, nil, 1, nil, 3, nil],
                [nil, 3, nil, 2, nil, 2, nil, nil],
                [2, nil, 1, nil, 2, nil, nil],
                [nil, 4, nil, 5, nil, 1, nil, nil],
                [2, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1464,
            rows: [
                [1, 1, nil, nil, nil, nil, 2, 6],
                [1, 4, 4, 4, 3, 3, 5],
                [3, 2, nil, nil, nil, nil, 3, 3],
                [2, 3, 3, 3, 3, 1, 2],
                [2, 3, nil, nil, nil, nil, 6, 2],
                [3, 1, 1, 1, 1, 2, 1],
                [1, 2, nil, nil, nil, nil, 1, 3],
                [2, 3, 1, 2, 2, 1, 1],
                [2, 3, nil, nil, nil, nil, 1, 2],
                [1, 2, 1, 2, 4, 1, 1],
                [4, 1, nil, nil, nil, nil, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 5, nil, nil, nil, nil, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1465,
            rows: [
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [3, 4, 4, 4, 1, 1, 1, 6],
                [nil, nil, nil, nil, nil, nil, 6],
                [2, 2, 1, 1, 4, 4, 7, 2],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, 1, 2, 1, 2, 3, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 3, 1, 1, 4, 4, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1466,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 4, 4, 1, nil, nil],
                [nil, nil, 3, 3, 1, 3, nil, nil],
                [nil, 1, 3, 3, 3, 3, nil],
                [nil, nil, 2, 4, 1, 3, nil, nil],
                [nil, 3, 1, 3, 3, 4, nil],
                [nil, 1, 3, 2, 1, 1, 1, nil],
                [1, 2, 2, 2, 1, 2, 1],
                [nil, 2, 1, 1, 2, 2, 2, nil],
                [3, 1, 1, 5, 2, 2, 1],
                [2, 4, 2, 5, 5, 2, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 4, 4, 1, 3, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1467,
            rows: [
                [5, 4, nil, nil, nil, nil, 3, 1],
                [2, nil, nil, nil, nil, nil, 1],
                [nil, nil, 5, 5, 3, 3, nil, nil],
                [nil, 3, nil, nil, nil, 2, nil],
                [nil, nil, 4, 4, 1, 2, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [2, 2, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, 6, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1468,
            rows: [
                [nil, nil, 1, 1, 1, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 3, nil, 2, 2, nil, 3],
                [6, 5, nil, 4, 1, nil, 2],
                [nil, 4, 1, 1, 2, 2, 1, nil],
                [3, 2, 1, 2, 2, 1, nil],
                [nil, nil, 2, 5, nil, 3, 3, nil],
                [nil, 3, 2, nil, 1, 3, nil],
                [nil, nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 1, 6, 6, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, 2, 1, 1, 2, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1469,
            rows: [
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 5, 2, 7, nil, nil],
                [nil, nil, 1, 1, 3, 3, nil, nil],
                [nil, 3, nil, 1, nil, 2, nil],
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, 3, nil, 4, nil, 2, nil],
                [3, nil, nil, 3, 1, nil, nil, 2],
                [1, 1, nil, 1, nil, 2, 4],
                [2, nil, nil, 3, 3, nil, nil, 4],
                [1, 2, nil, 1, nil, 1, 4],
                [nil, 4, 1, 1, 1, 1, 3, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 5, 1, 1, 1, 2, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1470,
            rows: [
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [2, nil, nil, 2, nil, nil, 2],
                [1, 2, 1, 1, 4, 4, 4, 3],
                [5, nil, nil, 1, nil, nil, 2],
                [5, 1, 3, 1, 3, 1, 2, 4],
                [2, nil, nil, 1, nil, nil, 3],
                [nil, 1, nil, 3, nil, nil, 1, nil],
                [nil, nil, 2, 5, nil, nil, nil],
                [nil, 1, nil, 1, nil, nil, 1, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1471,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [4, 4, 4, 2, 1, 5, 1, 2],
                [nil, nil, nil, nil, 2, nil, nil],
                [3, 1, 1, 3, 2, 2, 2, 1],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 3, nil, 3, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 1, nil, 4, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 5, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1472,
            rows: [
                [2, nil, nil, nil, nil, nil, nil, 2],
                [2, 1, 5, 5, 5, 3, 3],
                [3, nil, nil, nil, nil, nil, nil, 1],
                [5, 1, 1, 2, 1, 1, 7],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [4, 2, 1, 1, 5, 1, 2],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [1, 2, 1, 2, 1, 1, 1],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [2, 4, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1473,
            rows: [
                [2, 1, 6, 3, 2, 4, 4, 2],
                [2, 3, 4, 3, 1, 3, 2],
                [1, 2, 2, 3, 2, 2, 1, 2],
                [1, 3, 3, 3, 4, 1, 2],
                [1, 3, 1, 2, 4, 1, 2, 1],
                [7, 1, 4, 1, 4, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1474,
            rows: [
                [nil, 2, 1, 2, 3, 3, 3, nil],
                [nil, 2, 2, 6, 1, 2, nil],
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, nil, 4, 4, 1, nil, nil],
                [nil, nil, nil, 2, 7, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 1, 6, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, nil, nil],
                [3, 5, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil, nil],
                [nil, 5, 5, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 1, 2, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1475,
            rows: [
                [1, 2, 1, 1, 2, 1, 2, 2],
                [1, nil, 4, nil, 6, nil, 6],
                [nil, 3, 1, 5, 2, 5, 4, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [nil, 4, 4, 3, 1, 2, 2, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, 3, 3, 3, 1, 1, nil],
                [4, nil, 3, nil, 1, nil, 2],
                [nil, 1, 2, 2, 2, 2, 2, nil],
                [1, nil, 1, nil, 1, nil, 1],
                [3, 1, 1, 2, 2, 1, 1, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1476,
            rows: [
                [3, 3, nil, 3, 2, nil, 1, 1],
                [3, 2, nil, 2, nil, 2, 2],
                [nil, 3, nil, 1, 3, nil, 3, nil],
                [1, 1, 2, 2, 1, 1, 1],
                [nil, 2, nil, 1, 2, nil, 2, nil],
                [1, 3, 2, 1, 1, 4, 4],
                [nil, 1, nil, 1, 1, nil, 2, nil],
                [2, 3, nil, nil, nil, 2, 3],
                [nil, 1, nil, 3, 1, nil, 3, nil],
                [5, 3, nil, nil, nil, 3, 3],
                [2, 2, 1, nil, nil, 1, 1, 4],
                [3, 3, nil, nil, nil, 2, 2],
                [3, 1, 2, nil, nil, 1, 3, 2],
                [1, 1, nil, nil, nil, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1477,
            rows: [
                [nil, nil, 1, 4, 4, 3, nil, nil],
                [nil, nil, 1, 1, 7, nil, nil],
                [nil, nil, 1, 2, 4, 5, nil, nil],
                [nil, nil, 1, 3, 2, nil, nil],
                [nil, nil, 2, 3, 3, 1, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 2, 2, 1, 4, nil, nil],
                [nil, nil, 4, 4, 1, nil, nil],
                [nil, nil, 1, 3, 3, 1, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 2, 1, 1, 3, nil, nil],
                [nil, nil, 1, 5, 1, nil, nil],
                [nil, nil, 1, 2, 3, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1478,
            rows: [
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, 3, 3, 3, 2, nil, nil, 1],
                [2, 1, 3, 2, 1, nil, 4],
                [nil, 2, 1, 4, 3, nil, nil, 3],
                [3, 2, 1, 1, 1, nil, 4],
                [1, 5, 2, 1, 2, 1, 2, nil],
                [1, 2, 1, 4, 4, nil, 1],
                [3, 3, 3, 1, 5, 1, 1, nil],
                [1, 2, 6, 2, 1, nil, 2],
                [nil, 3, 3, 2, 2, nil, nil, 1],
                [nil, nil, 4, nil, nil, nil, nil],
                [nil, 1, 1, 2, 1, nil, nil, 2],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1479,
            rows: [
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [1, 1, 1, 5, 2, 2, 3],
                [1, 4, 4, 3, 2, 1, 1, 2],
                [3, 1, nil, 1, nil, 1, 1],
                [3, 1, 2, 3, 1, 2, 2, 3],
                [3, 2, nil, 1, nil, 1, 1],
                [1, 2, nil, 3, 3, nil, 2, 2],
                [3, nil, nil, 2, nil, nil, 1],
                [2, 6, nil, 2, 2, nil, 1, 6],
                [2, nil, nil, 2, nil, nil, 2],
                [2, 1, 3, nil, nil, 1, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, 3, 1, nil, nil, 3, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1480,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 2, 1, nil, 1, 3, nil],
                [nil, 3, 2, 1, 7, 1, 2, nil],
                [nil, 2, 2, nil, 3, 4, nil],
                [nil, 1, 2, 2, 5, 3, 3, nil],
                [nil, 2, 3, nil, 2, 2, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [4, nil, nil, 1, 2, nil, nil, 2],
                [1, nil, nil, 4, nil, nil, 4],
                [2, nil, nil, 3, 3, nil, nil, 5],
                [3, nil, nil, 1, nil, nil, 3],
                [nil, 2, 1, 2, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
    ]
}
