// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch88 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1741,
            rows: [
                [2, 3, 2, 1, 3, 3, 1, 3],
                [2, 3, 3, 2, 2, 1, 3],
                [1, 2, 1, 1, 4, 1, 1, 3],
                [2, 2, 6, 2, 2, 4, 3],
                [3, 4, 3, 1, 1, 3, 3, 1],
                [2, 1, 4, 4, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1742,
            rows: [
                [nil, 4, 4, 4, nil, nil, 4, 2],
                [nil, 2, 2, 1, nil, nil, 2],
                [nil, 1, 2, 1, nil, nil, 2, 2],
                [nil, 2, 4, 5, nil, 1, 2],
                [nil, 3, 2, 1, nil, nil, 1, 2],
                [nil, 1, 2, 3, nil, 2, 2],
                [nil, 1, 2, 1, nil, 4, 1, 2],
                [nil, 1, 2, 1, nil, 2, 1],
                [nil, 3, 1, 2, nil, 1, 1, 2],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1743,
            rows: [
                [nil, 1, 1, 1, 4, 4, 2, nil],
                [nil, 1, 3, 2, 3, 1, nil],
                [nil, nil, 2, 2, 2, 3, nil, nil],
                [nil, nil, 3, 1, 1, nil, nil],
                [nil, nil, nil, 6, 1, nil, nil, nil],
                [nil, nil, 3, 1, 1, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, 1, nil, nil, nil, nil, nil, nil],
                [3, 1, nil, nil, nil, nil, nil],
                [nil, 1, 2, nil, nil, nil, nil, nil],
                [nil, 1, 4, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 1, 2, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1744,
            rows: [
                [nil, 1, nil, 2, nil, nil, 1, 1],
                [nil, 1, 1, 2, nil, nil, 2],
                [nil, 2, nil, 1, nil, nil, nil, 1],
                [nil, 3, 2, 5, nil, 1, 1],
                [nil, 2, 2, 1, nil, nil, 2, 3],
                [nil, 3, 1, 5, nil, 1, 6],
                [nil, 1, 1, 1, nil, 1, 5, 1],
                [nil, 3, 1, 1, nil, 2, 2],
                [nil, 4, 1, 2, nil, 1, 1, 2],
                [nil, 1, 1, 2, nil, 1, 1],
                [nil, 1, 2, 1, nil, 3, 1, 4],
                [nil, 4, 1, 1, nil, 1, 2],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1745,
            rows: [
                [2, 6, 6, 2, 2, 1, 4, 4],
                [1, nil, 1, nil, 2, nil, 1],
                [nil, 2, 1, 2, 1, 1, 2, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, 2, nil],
                [nil, 1, nil, 3, nil, 1, nil],
                [nil, 4, 1, 6, 1, 3, 3, nil],
                [2, nil, 1, nil, 1, nil, 5],
                [nil, 5, 1, 3, 1, 1, 1, nil],
                [2, nil, 1, nil, 1, nil, 1],
                [2, 2, 1, 2, 4, 2, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 2, 1, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1746,
            rows: [
                [2, 1, nil, 1, 2, nil, 1, 2],
                [2, 3, nil, 1, nil, 1, 4],
                [nil, 2, nil, 2, 2, nil, 2, nil],
                [1, 2, 1, 5, 1, 2, 1],
                [nil, 1, nil, 1, 4, nil, 1, nil],
                [1, 2, 1, 4, 1, 2, 1],
                [nil, 1, nil, 4, 2, nil, 5, nil],
                [2, 2, nil, nil, nil, 2, 1],
                [nil, 1, nil, 3, 2, nil, 3, nil],
                [1, 4, nil, nil, nil, 2, 2],
                [3, 3, 1, nil, nil, 2, 2, 3],
                [1, 1, nil, nil, nil, 1, 3],
                [3, 2, 1, nil, nil, 2, 4, 1],
                [4, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1747,
            rows: [
                [nil, nil, 3, 1, 3, 2, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 2, 4, 4, 7, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil],
                [nil, nil, 1, 1, 2, 1, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 2, 3, 2, 2, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 2, 3, 3, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 1, 1, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, nil, 3, 1, 2, nil, nil],
                [nil, nil, 3, 3, 1, 3, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1748,
            rows: [
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [nil, 2, 1, 2, 3, nil, nil, 3],
                [1, 1, 4, 4, 1, nil, 2],
                [nil, 3, 2, 2, 1, nil, nil, 1],
                [1, 2, 1, 3, 2, nil, 2],
                [1, 2, 3, 1, 6, 2, 1, nil],
                [2, 2, 3, 1, 5, nil, 1],
                [1, 2, 3, 3, 3, 1, 3, nil],
                [3, 2, 1, 2, 4, nil, 3],
                [nil, 3, 2, 1, 2, nil, nil, 1],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, 1, 2, 5, 1, nil, nil, 2],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1749,
            rows: [
                [1, 2, nil, nil, nil, nil, nil, nil],
                [2, 1, nil, nil, nil, nil, nil],
                [3, 1, 1, nil, nil, nil, nil, nil],
                [3, 3, 3, nil, nil, nil, nil],
                [2, 2, 1, nil, nil, nil, nil, nil],
                [1, 3, 3, nil, nil, nil, nil],
                [5, 5, 1, 1, nil, nil, nil, nil],
                [1, 2, 4, 4, nil, nil, nil],
                [4, 4, 4, 4, nil, nil, nil, nil],
                [3, 1, 1, 2, nil, nil, nil],
                [5, 1, 1, 2, 1, nil, nil, nil],
                [3, 1, 6, 1, 1, nil, nil],
                [2, 1, 3, 1, 2, nil, nil, nil],
                [2, 1, 3, 1, 2, nil, nil],
                [1, 1, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1750,
            rows: [
                [nil, nil, 3, nil, nil, 4, nil, nil],
                [2, 1, 6, 2, 2, 2, 2],
                [2, 2, 2, 2, 1, 3, 2, 2],
                [1, 3, nil, 1, nil, 3, 1],
                [2, 3, 1, 4, 1, 2, 2, 1],
                [1, 1, nil, 3, nil, 3, 1],
                [2, 2, nil, 3, 5, nil, 5, 5],
                [1, nil, nil, 1, nil, nil, 2],
                [1, 2, nil, 2, 1, nil, 3, 3],
                [3, nil, nil, 1, nil, nil, 2],
                [2, 1, 1, nil, nil, 1, 1, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 2, 1, nil, nil, 2, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1751,
            rows: [
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, 2, 2, nil, 1, 1, nil],
                [nil, 2, 1, 6, 1, 1, 3, nil],
                [nil, 5, 5, nil, 3, 1, nil],
                [nil, 3, 4, 1, 4, 2, 1, nil],
                [nil, 2, 1, nil, 2, 1, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [1, nil, nil, 2, 1, nil, nil, 1],
                [2, nil, nil, 1, nil, nil, 2],
                [2, nil, nil, 1, 1, nil, nil, 6],
                [1, nil, nil, 1, nil, nil, 3],
                [nil, 6, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1752,
            rows: [
                [4, nil, nil, nil, 4, 1, nil, nil],
                [1, nil, nil, 1, 1, 1, nil],
                [1, nil, nil, 2, 2, 2, 1, nil],
                [1, nil, 3, 2, 1, 3, 5],
                [5, nil, nil, 2, 2, 6, 1, nil],
                [1, nil, 2, 1, 2, 4, 4],
                [3, nil, nil, 2, 3, 2, 3, nil],
                [3, nil, nil, 1, 3, 2, nil],
                [3, nil, nil, 2, 2, 3, 1, nil],
                [2, nil, nil, 3, 2, 2, nil],
                [3, nil, nil, nil, 3, 5, nil, nil],
                [nil, nil, nil, 2, 3, 2, nil],
                [2, nil, nil, nil, 1, 3, nil, nil],
                [nil, nil, nil, 3, 3, 1, nil],
                [nil, nil, nil, 3, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1753,
            rows: [
                [3, nil, 2, 2, 2, 3, nil, 3],
                [3, nil, nil, nil, nil, nil, 2],
                [3, 1, 2, 2, 3, 4, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 2, 3, nil, nil],
                [nil, nil, 3, 1, 2, nil, nil],
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 4, nil, 1, nil, 1],
                [2, nil, 1, nil, 3, nil, 3],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 2, nil, 1, nil, 2],
                [nil, 4, nil, 4, nil, 4, nil, 2],
                [1, nil, 2, nil, 2, nil, 1],
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1754,
            rows: [
                [nil, 4, 3, nil, nil, 1, 1, nil],
                [4, nil, 4, nil, 3, nil, 3],
                [5, nil, nil, 7, 4, nil, nil, 2],
                [3, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, 1, 2, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, 5],
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 2, nil, nil, nil, nil, 3, nil],
                [nil, 3, nil, nil, nil, 4, nil],
                [nil, nil, 4, nil, nil, 2, nil, nil],
                [nil, nil, 3, nil, 6, nil, nil],
                [nil, nil, 1, nil, nil, 5, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1755,
            rows: [
                [2, 1, 3, 2, 1, 3, 3, 2],
                [3, 2, 1, 1, 2, 4, 2],
                [1, 1, 2, 1, 2, 2, 3, 3],
                [2, 2, 4, 2, 4, 4, 1],
                [2, 1, 1, 2, 3, 3, 3, 2],
                [1, 1, 1, 1, 2, 2, 1],
                [1, 5, 5, 2, 4, 2, 2, 4],
                [2, 1, 2, 2, 2, 2, 1],
                [2, 1, 2, 2, 1, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1756,
            rows: [
                [nil, nil, 1, 1, nil, 2, nil, nil],
                [nil, nil, nil, 1, nil, 1, nil],
                [nil, nil, 1, 1, nil, nil, 6, nil],
                [nil, nil, nil, nil, 1, 2, 1],
                [nil, nil, nil, 4, nil, nil, nil, nil],
                [2, 2, 1, 4, 4, nil, 1],
                [1, nil, 3, 1, nil, 1, 2, 2],
                [1, 2, nil, 3, 1, 1, 2],
                [nil, nil, nil, 2, 2, 1, nil, 2],
                [2, 1, 3, 3, 3, 3, 1],
                [nil, 1, 1, nil, nil, 4, 1, 1],
                [nil, 4, nil, 1, 5, 4, 4],
                [nil, 1, 3, 1, 2, 1, 1, 1],
                [nil, 1, 1, 2, 1, 2, 1],
                [nil, nil, 4, 3, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1757,
            rows: [
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, 4, 4, nil],
                [4, 2, nil, nil, 2, 2, nil],
                [nil, 3, 1, nil, nil, 5, 2, nil],
                [1, 2, nil, nil, 3, 3, nil],
                [nil, 3, 3, nil, nil, 1, 1, nil],
                [3, 1, nil, nil, 3, 1, nil],
                [nil, 3, 1, nil, nil, 3, 1, nil],
                [1, 1, nil, nil, 1, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1758,
            rows: [
                [nil, nil, nil, nil, 3, nil, nil, nil],
                [1, 5, 2, 1, nil, nil, nil],
                [6, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 1, 2, 2, 1],
                [2, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 5, 1, 2, 2],
                [2, nil, nil, nil, 1, nil, nil, 3],
                [1, 1, 1, 3, nil, nil, nil],
                [1, nil, nil, nil, 2, nil, nil, 1],
                [1, 3, 3, 1, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil, 3],
                [nil, nil, nil, 2, 2, 1, 3],
                [nil, nil, nil, 1, nil, nil, nil, 1],
                [nil, nil, nil, 4, 1, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1759,
            rows: [
                [nil, 2, nil, 1, nil, 1, nil, 1],
                [2, 3, nil, 2, 1, nil, 2],
                [3, nil, 1, nil, 4, nil, 1, nil],
                [3, 1, nil, 2, 1, nil, 1],
                [6, nil, 6, nil, 4, nil, 1, nil],
                [2, 1, nil, 4, 1, nil, 2],
                [nil, 2, nil, 1, nil, 1, nil, 2],
                [3, 3, nil, 2, 1, nil, 1],
                [nil, 2, nil, 3, nil, 2, nil, 1],
                [1, 1, nil, 1, 1, nil, 1],
                [2, nil, 2, nil, 4, nil, 2, nil],
                [1, 2, nil, 5, 2, nil, 2],
                [2, nil, 4, nil, 2, nil, 1, nil],
                [2, 2, nil, 2, 2, nil, 2],
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1760,
            rows: [
                [nil, nil, 2, 1, 3, 3, nil, nil],
                [nil, 3, 3, nil, nil, 3, nil],
                [nil, 2, 1, nil, 2, 1, 1, nil],
                [1, 1, 4, 4, nil, nil, 4],
                [nil, 1, nil, 2, nil, nil, 1, nil],
                [2, 1, 2, nil, nil, 1, 1],
                [1, nil, 1, nil, nil, nil, 1, nil],
                [nil, 2, 4, nil, 4, 1, 2],
                [nil, 2, 2, 2, 2, 6, 2, 2],
                [nil, 1, 1, nil, nil, 2, 1],
                [nil, 3, nil, nil, nil, nil, 5, 1],
                [nil, 1, 2, 5, 5, 2, 2],
                [nil, 2, 2, 1, 2, 1, 2, 1],
                [nil, nil, nil, 2, nil, nil, 1],
                [nil, nil, 2, 1, 2, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
    ]
}
