// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch21 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 401,
            rows: [
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, 2, nil, nil, nil, 2, 2],
                [3, 3, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [2, 2, 3, 3, 4, 3, 3],
                [nil, 3, 5, 5, 5, 5, 4, nil],
                [nil, 4, nil, 6, nil, 6, nil],
                [nil, 6, 2, 2, 3, 3, 3, nil],
                [nil, 3, nil, 3, nil, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 402,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, 1, nil, nil, 1, 5, nil],
                [nil, 5, nil, nil, nil, 3, nil],
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [nil, 3, nil, nil, nil, 2, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 5, 5, nil, nil, 5, 2, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, 4, 7, 4, nil, nil],
                [nil, nil, 4, nil, nil, 2, nil, nil],
                [nil, nil, 2, 6, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 403,
            rows: [
                [5, 5, 5, 5, 2, 2, 1, 1],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [1, 4, 4, 4, 4, 2, 2, 2],
                [nil, nil, nil, nil, 2, nil, nil],
                [2, 2, 2, 2, 6, 1, 1, 1],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 6, 6, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [3, 3, 3, 3, 2, 2, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 404,
            rows: [
                [nil, 2, 1, 1, 1, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [1, 1, 3, 3, 3, 2, 2],
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [3, 3, 3, 3, 3, 7, 2],
                [nil, 2, 2, 2, 2, 7, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, 5, 3, 3, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 405,
            rows: [
                [nil, 1, nil, nil, 1, 2, 2, nil],
                [3, nil, nil, 3, 4, 5, nil],
                [5, nil, nil, 5, 5, 5, nil, nil],
                [1, nil, 1, 1, 1, nil, nil],
                [2, nil, nil, 2, 2, 2, nil, nil],
                [2, nil, 2, 2, 2, nil, nil],
                [7, nil, nil, 7, 3, 1, nil, nil],
                [1, nil, 1, 1, 1, 1, nil],
                [1, nil, nil, 1, 1, 4, nil, nil],
                [4, nil, 4, 3, 3, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 406,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [2, 2, nil, 2, nil, 2, 2],
                [2, 2, 2, 7, 7, 3, 3, 1],
                [1, 2, nil, 2, nil, 3, 3],
                [2, 3, nil, 2, 2, nil, 2, 2],
                [2, nil, nil, 2, nil, nil, 1],
                [1, 3, nil, 1, 4, nil, 4, 4],
                [1, nil, nil, 1, nil, nil, 1],
                [5, 4, 1, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 5, 1, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 407,
            rows: [
                [5, nil, 5, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [3, nil, 3, nil, 3, nil, 3, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [nil, nil, 3, 1, 4, 1, 1, nil],
                [nil, 1, 1, 1, 6, 6, nil],
                [nil, 1, 1, 1, 1, 2, 2, nil],
                [2, 2, 2, 2, 2, 2, 2],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 6, nil],
                [nil, nil, 6, 1, 2, 1, 1, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 408,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 5, nil, 5, 1, nil, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 2, nil],
                [nil, 2, 2, 2, 2, 1, 1, nil],
                [1, 1, 2, 2, 2, 2, 2],
                [nil, 2, 2, 2, 1, 1, 1, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 5, 5, 1, 1, 1, 1, nil],
                [nil, 1, 4, 3, 3, 3, nil],
                [nil, 2, 6, 6, 3, 4, 4, nil],
                [nil, 3, 3, 3, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 409,
            rows: [
                [nil, 5, 5, nil, nil, 5, 5, nil],
                [1, 1, nil, nil, 1, 1, nil],
                [nil, 1, 1, nil, nil, 1, 4, nil],
                [4, 4, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [1, nil, 2, nil, 2, nil, 6, nil],
                [nil, 6, nil, 6, nil, 6, nil],
                [2, nil, 2, nil, 2, nil, 4, nil],
                [nil, 4, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 3, nil, 3, nil],
                [nil, 1, nil, 1, nil, 3, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 410,
            rows: [
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 7, nil],
                [7, nil, 7, nil, 3, nil, 3, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [nil, 3, nil, 1, nil, 1, nil, nil],
                [1, nil, 1, nil, 5, nil, nil],
                [nil, 1, nil, 4, nil, 4, nil, nil],
                [4, nil, 2, nil, 2, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 411,
            rows: [
                [nil, 4, nil, 4, nil, 4, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, nil],
                [nil, 1, nil, 6, nil, 6, nil],
                [nil, 2, nil, 2, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, nil],
                [nil, 1, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil, nil],
                [nil, 2, nil, 2, nil, 7, nil],
                [nil, 7, nil, 5, nil, 5, nil, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 412,
            rows: [
                [nil, nil, nil, nil, nil, nil, 2, 1],
                [nil, nil, 1, 1, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, 2, 2],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, 3, nil, nil, 3, nil, nil],
                [3, 3, 3, nil, 2, nil, nil],
                [nil, 2, 2, nil, nil, 2, nil, nil],
                [2, 2, 1, nil, 1, nil, nil],
                [1, nil, 6, 6, 4, 4, nil, 5],
                [nil, 5, nil, 5, nil, 5, 1],
                [1, nil, 1, 1, 1, 1, nil, 3],
                [nil, 3, nil, 3, nil, 3, 3],
                [nil, 7, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 413,
            rows: [
                [nil, 2, 2, 2, 2, 1, 1, nil],
                [nil, 1, 1, 1, 1, 5, nil],
                [nil, nil, 5, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 1, 3, 3, 3, 3],
                [3, nil, nil, nil, nil, nil, 4],
                [4, nil, 1, 1, 1, 1, nil, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [1, nil, 1, 1, 1, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [6, 2, 4, 4, 4, 4, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 7, 1, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 414,
            rows: [
                [1, 1, nil, 4, nil, 4, 4, 4],
                [4, 4, 2, 5, 5, 5, nil],
                [nil, 5, nil, 5, nil, 1, nil, 2],
                [nil, 2, nil, 2, 2, 2, nil],
                [nil, 2, nil, nil, 2, 2, 2, nil],
                [2, nil, 2, 2, nil, nil, nil],
                [2, nil, nil, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, nil, 1, 3],
                [3, nil, 3, 3, 1, 3, 3, nil],
                [3, nil, nil, nil, 6, 3, nil],
                [3, nil, 3, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 4, 4, nil, nil, 4, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 415,
            rows: [
                [2, 2, nil, nil, nil, nil, 2, 2],
                [7, 1, 1, 1, 2, 2, 2],
                [2, 3, nil, nil, nil, nil, 3, 3],
                [3, 3, 4, 1, 1, 1, 1],
                [1, 2, nil, nil, nil, nil, 4, 4],
                [2, 2, 2, 2, 2, 2, 2],
                [2, 5, nil, nil, nil, nil, 1, 1],
                [3, 3, 3, 3, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, 1, 1, 5, 5, 5],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 3, nil, nil, nil, nil, 3, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 416,
            rows: [
                [nil, 1, 1, nil, nil, 1, 5, nil],
                [5, 5, 5, 5, 1, 1, 1],
                [1, 1, 1, 1, 4, 4, 4, 4],
                [4, 2, 2, 1, 1, 1, 1],
                [1, 1, 1, 3, 3, 2, 2, 2],
                [3, 3, 3, 3, 3, 6, 6],
                [nil, 6, 2, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 5, nil, nil, 5, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 417,
            rows: [
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [6, 6, 6, 6, 6, 3, 3],
                [nil, nil, 1, 1, 1, 4, nil, nil],
                [nil, 4, 4, 1, 2, 2, nil],
                [nil, nil, 5, 7, 7, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 3, 2, 2, nil, nil],
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 4
        ),
        LevelTemplate(
            levelNumber: 418,
            rows: [
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 2, 5, 1, 1, 1, 1, 5],
                [nil, 5, nil, nil, nil, nil, 5],
                [nil, 5, 2, 2, 2, 2, 2, 2],
                [nil, 2, nil, nil, nil, nil, 3],
                [nil, nil, nil, 3, 3, 3, 3, nil],
                [nil, 3, 3, nil, nil, nil, nil],
                [nil, nil, nil, 3, 7, 7, 4, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 419,
            rows: [
                [nil, 5, 5, nil, 5, 5, 5, nil],
                [5, nil, nil, nil, nil, nil, 1],
                [nil, 4, 2, 2, nil, 2, 2, nil],
                [2, nil, nil, nil, nil, nil, 1],
                [nil, 1, 1, 6, nil, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [4, nil, nil, nil, nil, nil, 3],
                [nil, 3, 3, 3, nil, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 7, 4, nil, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 420,
            rows: [
                [4, nil, 4, nil, 4, nil, 4, nil],
                [nil, 4, nil, 4, nil, 4, nil],
                [1, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 4, nil, 4, nil, 4, nil],
                [1, nil, 1, nil, 5, nil, 5, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [7, nil, 2, nil, 2, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 3, 2, 2, 1, 2, 2, 2],
                [2, 1, 1, 2, 2, 3, 6],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
    ]
}
