// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch36 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 701,
            rows: [
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [1, 1, 1, nil, nil, nil, 1],
                [1, nil, 1, 1, 1, 1, nil, 1],
                [nil, 1, nil, 1, 1, nil, 1],
                [nil, nil, 1, 4, nil, nil, 4, nil],
                [nil, 4, 4, nil, 4, 4, nil],
                [4, nil, nil, nil, nil, nil, 3, 3],
                [nil, 3, 3, nil, nil, nil, nil],
                [3, 3, nil, nil, nil, nil, 3, 3],
                [3, nil, 3, 3, nil, nil, 3],
                [nil, nil, 6, nil, 2, nil, 2, 2],
                [nil, nil, nil, 2, nil, 2, 2],
                [nil, 2, 2, nil, 2, 2, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, 6, 5, 5, 5, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 702,
            rows: [
                [nil, nil, nil, nil, 2, nil, 2, nil],
                [nil, 2, 2, nil, 2, 2, nil],
                [nil, 2, nil, 2, 2, 2, 5, nil],
                [nil, nil, 5, nil, 5, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 3, 3, nil],
                [nil, nil, 3, 3, nil, 3, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, 3, 3, nil, nil, nil, 4, nil],
                [nil, nil, nil, nil, 4, 6, nil],
                [nil, nil, 6, 6, 1, nil, 1, nil],
                [nil, 1, 1, nil, 4, 4, nil],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 4, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 703,
            rows: [
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [1, 1, 1, 1, 1, nil, 4],
                [nil, 4, 1, 1, nil, 1, nil, 1],
                [1, nil, nil, nil, nil, 3, 3],
                [nil, 3, nil, 3, nil, 2, 2, nil],
                [2, nil, 2, nil, nil, nil, 2],
                [2, nil, nil, nil, 2, 2, nil, 2],
                [nil, 2, 2, 2, 2, 2, nil],
                [2, nil, 3, nil, 3, 3, nil, nil],
                [3, 3, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, 3, nil, nil],
                [nil, 3, 4, 4, 4, 4, 5],
                [5, 5, 1, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 6, 6, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 704,
            rows: [
                [2, nil, 2, 2, nil, nil, 4, 4],
                [4, 4, 4, 4, 4, 4, 4],
                [4, 4, 5, 5, 5, nil, 5, 5],
                [6, 2, nil, 2, 2, 2, 2],
                [nil, 2, 2, nil, 2, nil, 2, 2],
                [2, 3, nil, 3, nil, nil, 1],
                [nil, nil, 3, 3, 3, nil, nil, 3],
                [nil, 1, 1, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, 1, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 705,
            rows: [
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, 1, 5, nil, nil, 5, 5, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 1, nil, 2, nil, 2, nil],
                [nil, nil, nil, 2, 2, 2, nil],
                [nil, 2, 1, 1, 4, 4, 4, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 4, nil],
                [nil, 4, 4, 4, 4, 4, nil],
                [nil, 1, 1, 1, 3, 3, 3, nil],
                [nil, 3, 3, 3, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 2, 2, 2, 6, 6, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 706,
            rows: [
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [nil, nil, 2, nil, nil, 3, nil],
                [nil, nil, 3, nil, 3, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 2, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil],
                [nil, 2, 2, 2, 3, 3, nil, nil],
                [nil, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, 3, 3, 3, nil, nil],
                [nil, 3, nil, 3, 3, 3, nil],
                [nil, 3, 1, 1, 1, 1, nil, nil],
                [nil, 1, 2, 2, nil, 1, nil],
                [nil, 1, 1, nil, 1, nil, 1, nil],
                [nil, nil, 5, 5, 1, 1, nil],
                [nil, 1, 1, 2, 2, 4, 4, nil],
                [nil, 6, 6, 2, 6, 6, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 707,
            rows: [
                [nil, 1, nil, nil, nil, 1, 1, nil],
                [1, 1, nil, 5, 5, nil, 5],
                [nil, nil, nil, 2, nil, 2, 1, 1],
                [nil, nil, 1, 1, nil, 1, 1],
                [1, nil, 1, 1, nil, 1, nil, nil],
                [3, 2, nil, nil, 2, 2, 2],
                [nil, 2, 2, nil, 2, 2, 2, nil],
                [2, nil, 2, 2, 2, 1, 4],
                [4, nil, nil, nil, nil, 4, 4, 4],
                [nil, nil, nil, 4, nil, nil, 4],
                [4, 1, 1, 1, nil, 1, nil, nil],
                [1, 1, nil, 3, nil, 3, 3],
                [nil, 3, 3, 1, nil, 1, 1, 6],
                [6, 1, nil, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 708,
            rows: [
                [1, 1, 1, 1, nil, 1, nil, nil],
                [nil, 3, 1, 1, 2, 2, nil],
                [2, 2, nil, 2, 2, nil, 2, nil],
                [nil, nil, nil, nil, 2, 2, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [3, 3, nil, 1, nil, nil, 1],
                [nil, 1, nil, 1, 1, 1, 1, 1],
                [2, nil, nil, nil, 2, 6, nil],
                [6, nil, 6, 1, 1, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 2, 1, 1, nil],
                [1, nil, 1, 1, nil, 1, nil],
                [1, 3, nil, 3, nil, 3, 3, 3],
                [3, nil, 4, nil, nil, nil, 4],
                [nil, 4, 1, nil, 6, 1, nil, nil],
                [nil, 1, nil, 1, 1, 1, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 709,
            rows: [
                [1, 1, 1, 2, nil, 2, nil, 2],
                [1, 1, 1, nil, 2, 1, 1],
                [nil, nil, nil, 1, nil, 1, nil, 1],
                [1, 1, 1, nil, nil, nil, nil],
                [1, 1, 3, 3, 3, 3, 2, 2],
                [2, 2, 5, nil, 5, 5, 5],
                [nil, 4, nil, nil, 4, 4, 4, 4],
                [4, nil, 3, nil, 3, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 4, nil, nil, 1, nil, nil, nil],
                [nil, nil, 1, nil, 1, 1, nil],
                [nil, nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, 6, 6, 6, 6, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 710,
            rows: [
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, 1, nil, 1, 1, nil, nil],
                [nil, 1, nil, nil, 1, 1, 2, nil],
                [nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil, nil],
                [nil, nil, 2, 4, 4, 4, nil],
                [nil, 4, 4, 1, nil, nil, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, 1, nil, 1, nil],
                [nil, 1, 2, 2, nil, 2, 2, nil],
                [nil, 2, nil, 2, 2, 1, nil],
                [nil, nil, 1, 1, 1, 1, 3, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, 3, 3, 5, 5, 5, 5, nil],
                [nil, 5, 1, 1, 6, 6, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 711,
            rows: [
                [nil, 1, nil, nil, 6, 6, 6, nil],
                [nil, 6, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 5, 5, nil, nil, 5, nil],
                [nil, 5, 2, 2, nil, 2, nil],
                [nil, nil, nil, 2, 2, nil, 2, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, nil, 3, nil, nil, nil],
                [nil, 2, 2, nil, 2, 2, nil],
                [nil, 2, 2, 2, 1, 1, 4, nil],
                [nil, 4, 4, 4, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 3, 3, 3, 1, 1, nil],
                [nil, 2, nil, 2, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 712,
            rows: [
                [nil, nil, 1, nil, nil, 1, 1, nil],
                [nil, nil, 1, 1, 2, 4, nil],
                [nil, nil, 3, nil, 3, nil, 2, nil],
                [nil, 2, nil, nil, 2, 1, nil],
                [nil, 1, 1, 1, 5, 5, 2, nil],
                [nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, nil, 2, nil, 2, 2, nil],
                [nil, nil, nil, 2, 1, 1, nil],
                [nil, nil, 6, nil, 6, nil, nil, nil],
                [nil, 3, nil, 3, 1, 1, nil],
                [nil, 1, 4, nil, 4, nil, 4, nil],
                [nil, nil, 3, nil, 3, 3, nil],
                [nil, nil, 4, 1, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, 4, 2, 2, 2, 2, nil],
                [nil, 2, 4, 4, 5, 2, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 713,
            rows: [
                [4, 4, nil, nil, 1, nil, nil, 1],
                [1, nil, 1, nil, 1, 1, nil],
                [1, 2, nil, 5, nil, 5, 5, 5],
                [5, 5, 2, 2, 2, 2, nil],
                [2, nil, nil, 2, 2, 2, nil, nil],
                [2, 2, 2, 4, nil, 4, 1],
                [1, 3, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, 3, 3, nil],
                [3, nil, 1, 1, 1, 1, nil, 6],
                [nil, nil, nil, 6, 6, nil, 1],
                [1, nil, 1, 1, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, 1, 1, nil, 1],
                [nil, nil, 1, 1, 1, nil, 1],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 714,
            rows: [
                [4, 4, 4, 4, nil, 4, 4, 4],
                [4, 4, nil, 6, 3, nil, nil],
                [3, nil, 3, nil, nil, nil, 3, nil],
                [3, nil, nil, 3, 1, 1, nil],
                [1, 1, 1, 1, nil, 1, 1, nil],
                [1, nil, 2, 2, 2, 2, 2],
                [nil, nil, 2, 2, 2, nil, 3, 3],
                [3, 3, 1, 1, 1, 1, 1],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [1, 1, nil, 1, 1, 1, 2],
                [nil, 2, nil, 2, 1, 1, 1, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, nil, 6, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 715,
            rows: [
                [nil, 2, nil, nil, 2, 2, nil, nil],
                [nil, 3, 3, 3, nil, 3, nil],
                [nil, 3, nil, 3, nil, 1, nil, nil],
                [nil, 1, 1, nil, nil, 1, nil],
                [nil, nil, 1, 4, 4, 1, nil, nil],
                [nil, nil, 1, 1, 1, 6, nil],
                [nil, 1, nil, nil, 2, 1, nil, nil],
                [nil, nil, 1, nil, 2, 2, nil],
                [nil, 2, nil, 2, 2, nil, 2, nil],
                [nil, nil, 2, 2, 2, 1, nil],
                [nil, 4, 4, 4, 4, 4, 4, nil],
                [nil, 1, 1, 6, 6, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 5],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 716,
            rows: [
                [4, nil, nil, 4, 4, 4, nil, nil],
                [4, nil, 4, nil, nil, nil, 2],
                [2, nil, 2, nil, 2, nil, nil, 2],
                [2, 2, 2, nil, 2, 2, nil],
                [nil, 1, 1, 1, nil, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [1, 1, 1, nil, 1, 1, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1],
                [1, nil, 3, 3, 3, 1, 1, nil],
                [1, 1, 1, nil, nil, 1, nil],
                [nil, 1, nil, 4, nil, 4, nil, 1],
                [nil, nil, nil, 1, 1, 6, 6],
                [5, nil, 3, 3, nil, nil, nil, nil],
                [3, nil, 3, 3, 3, nil, nil],
                [nil, nil, nil, 3, 4, nil, 1, nil],
                [nil, nil, 1, nil, 1, 5, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 717,
            rows: [
                [nil, nil, 6, 6, nil, 1, nil, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, 1, 4, nil, nil, nil, nil],
                [nil, 4, 4, nil, nil, 4, nil],
                [nil, nil, 4, 4, 1, nil, 1, nil],
                [nil, 1, nil, 2, 2, 3, nil],
                [nil, nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, nil, 1, 1, 5, nil],
                [nil, 5, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 3, 3, nil],
                [nil, 3, 3, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 5, 5, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 718,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, 3, 3, nil],
                [nil, nil, nil, 3, 2, 2, nil, nil],
                [nil, 2, nil, nil, nil, 2, 1],
                [nil, 1, nil, 1, nil, 1, nil, nil],
                [nil, 3, 2, 2, 2, nil, nil],
                [2, 2, nil, 4, nil, 4, 1, 1],
                [1, 1, nil, nil, 4, nil, 1],
                [1, nil, 1, 1, 1, 4, 4, 4],
                [nil, 4, nil, 4, 5, nil, 1],
                [nil, 1, 1, nil, nil, 1, 1, 6],
                [nil, 6, 6, 1, 1, nil, 2],
                [nil, 2, 1, 1, 1, 1, 1, 1],
                [nil, 4, 2, 1, 1, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 719,
            rows: [
                [nil, 1, nil, nil, nil, 2, nil, 2],
                [nil, nil, nil, 1, nil, 1, 1],
                [2, 2, 2, nil, 2, 2, nil, 2],
                [2, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, 1, nil, 1, nil, 1],
                [nil, nil, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, 1, 1],
                [nil, 1, 1, 1, nil, 3, 2, 2],
                [2, 2, nil, nil, nil, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, 5],
                [nil, nil, 3, nil, 3, 3, nil],
                [3, nil, 3, nil, nil, 6, 6, nil],
                [nil, 6, nil, nil, nil, 5, 5],
                [nil, nil, 5, nil, 6, 4, nil, nil],
                [nil, nil, nil, 4, 4, 5, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 720,
            rows: [
                [2, 2, nil, nil, nil, 2, nil, 2],
                [2, 2, nil, 2, 5, 5, nil],
                [nil, nil, 2, 2, nil, nil, nil, 2],
                [nil, nil, nil, 2, 2, 2, nil],
                [nil, 2, 2, 2, nil, nil, 2, 6],
                [6, nil, nil, 6, 3, 3, nil],
                [nil, 1, nil, nil, nil, nil, 1, 4],
                [nil, nil, 4, nil, 4, 4, 1],
                [nil, 1, nil, nil, 1, 1, nil, 3],
                [3, 3, 3, 1, nil, 1, nil],
                [1, 1, 1, 1, 1, nil, 1, nil],
                [1, nil, nil, 1, 1, nil, 1],
                [1, 1, 1, nil, nil, 3, 3, nil],
                [nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [1, 1, nil, 1, 1, 1, 1],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
    ]
}
