// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch03 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 41,
            rows: [
                [5, nil, 5, nil, nil, 5, nil, 5],
                [5, nil, 5, nil, 1, 1, 2],
                [nil, 2, nil, 2, 2, nil, 2, nil],
                [2, 2, nil, nil, nil, 2, nil],
                [nil, 2, nil, 2, 2, nil, 2, nil],
                [2, 1, nil, nil, nil, 1, nil],
                [1, nil, 1, 1, 1, 4, nil, 4],
                [4, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 1, 1, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 3, 3, 3, 3, 6, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 3, 3, 3, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 42,
            rows: [
                [2, 2, nil, nil, nil, nil, 2, 2],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [4, nil, 4, 2, 2, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [2, nil, 2, 3, 3, nil, 2],
                [2, 2, 2, 2, 2, 2, 3, 3],
                [3, 3, 3, nil, 3, 3, 3],
                [5, 5, 5, 5, 1, 1, 1, 1],
                [1, 1, 6, nil, 6, 6, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 43,
            rows: [
                [nil, nil, nil, nil, 5, 5, 5, nil],
                [nil, nil, 5, 5, 1, 1, 1],
                [nil, nil, 1, 4, 4, 4, 3, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, nil, 3, 3, 3, 3, 3, nil],
                [nil, 6, 6, 6, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [1, 1, 1, 1, 2, nil, nil],
                [nil, 2, 2, 1, 1, 1, nil, nil],
                [1, 1, 2, 2, 2, nil, nil],
                [2, 1, 3, 3, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 44,
            rows: [
                [1, 1, nil, nil, nil, nil, 1, 4],
                [4, 4, nil, nil, nil, 4, 4],
                [4, 2, nil, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 2, 3],
                [3, 3, 3, 3, 3, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, 6, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 4, nil],
                [nil, 4, 1, 1, 5, 5, 6, nil],
                [nil, 1, nil, 6, nil, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 45,
            rows: [
                [3, 3, nil, nil, nil, nil, nil, nil],
                [3, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil],
                [2, 2, 2, nil, nil, nil, nil, nil],
                [2, 2, 2, nil, nil, nil, nil],
                [2, 2, 2, 2, nil, nil, nil, nil],
                [2, 2, 1, 3, nil, nil, nil],
                [3, 3, 3, 3, nil, nil, nil, nil],
                [3, 3, 3, 3, nil, nil, nil],
                [1, 1, 1, 1, 1, nil, nil, nil],
                [1, 1, 1, 1, 1, nil, nil],
                [1, 1, 1, 4, 4, nil, nil, nil],
                [4, 4, 2, 2, 2, nil, nil],
                [6, 6, 5, 5, 5, 5, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 46,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 2, 4, nil, nil],
                [nil, 4, 4, 4, 4, 4, nil],
                [nil, nil, 4, 4, 7, 7, nil, nil],
                [nil, 1, 2, 2, 2, 2, nil],
                [nil, 2, nil, 2, 2, nil, 2, nil],
                [2, 2, 2, 1, 1, 2, 2],
                [nil, 2, nil, 2, 2, nil, 2, nil],
                [1, 1, 1, 1, 5, 1, 1],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 47,
            rows: [
                [nil, nil, 1, nil, nil, 5, nil, nil],
                [nil, 5, 5, 1, 1, 2, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [2, 2, 2, 2, 2, 2, 2],
                [nil, 2, 1, 1, 1, 1, 1, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 3, 3, 3, nil],
                [nil, 3, 2, 2, 5, 6, 6, nil],
                [nil, 6, 4, 4, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 48,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 4, 4, 4, 2],
                [2, 2, 2, 2, 2, 2, 2],
                [2, 2, 2, 2, 2, 2, 5, 5],
                [3, 3, 3, 1, 1, 6, 6],
                [1, 1, 1, 1, 1, 1, 1, 4],
                [4, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 7, 5, 3, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 49,
            rows: [
                [5, nil, nil, nil, 5, nil, nil, 5],
                [5, 5, nil, nil, 5, nil, 1],
                [nil, nil, 1, nil, 1, nil, 2, nil],
                [2, nil, 2, 2, nil, 2, nil],
                [nil, nil, 2, nil, 2, nil, 2, nil],
                [2, nil, 2, 2, nil, 2, nil],
                [2, 2, 2, 1, 1, 1, nil, 1],
                [nil, nil, 4, 4, 3, 3, 3],
                [3, 3, 3, 3, 1, 1, nil, 4],
                [nil, nil, 4, 4, 4, 1, 1],
                [nil, 1, 2, nil, nil, 1, nil, nil],
                [6, 1, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 50,
            rows: [
                [nil, nil, 5, nil, nil, 5, nil, nil],
                [nil, 5, 5, nil, 5, 5, nil],
                [nil, 1, 1, 1, 1, 4, 4, nil],
                [nil, 4, 4, nil, 4, 4, nil],
                [nil, 4, 4, 2, 2, 2, 2, nil],
                [nil, 2, 2, nil, 2, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [1, nil, nil, 3, 3, nil, nil, 3],
                [3, nil, nil, 3, nil, nil, 2],
                [1, nil, nil, 1, 2, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, 1, 6, 2, 2, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 51,
            rows: [
                [nil, nil, 5, 5, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, 1, 1, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, 2, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 6, 6, 6, 7, nil, nil],
                [nil, nil, 4, 1, 1, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 52,
            rows: [
                [2, nil, nil, 2, 2, nil, nil, 2],
                [2, 2, 5, 5, 5, 5, 5],
                [nil, 2, 2, nil, nil, 4, 6, nil],
                [6, nil, 1, 1, 1, nil, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, 3, nil, nil, 3, 3, nil],
                [nil, nil, 3, 3, 2, nil, nil],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, 3, 5, 4, 4, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 4, 3, 3, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 53,
            rows: [
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, 3, 3, nil, nil, nil, nil],
                [nil, nil, 3, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, 4, 4, 4, nil, nil, nil],
                [4, 3, 3, 3, 3, 3, 3, nil],
                [6, 6, 6, 6, 1, 1, nil],
                [2, 1, 1, 1, 1, 1, 1, nil],
                [1, 1, 2, 2, 2, 1, nil],
                [1, 2, 4, 4, 4, 4, 4, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 4, 6, 3, 3, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 54,
            rows: [
                [nil, nil, 1, 1, 4, 1, nil, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, 3, 3, 3, 1, 5, 5, nil],
                [nil, 5, 5, 5, 1, 1, nil],
                [nil, 1, 1, 1, 1, 6, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, nil, 2, 1, 1, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, 4, 4, 4, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, 1, 4, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 7, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 55,
            rows: [
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, 1, 1],
                [nil, 2, nil, 2, 2, nil, 2, nil],
                [2, 2, nil, nil, nil, 2, nil],
                [nil, 2, nil, 2, 7, nil, 7, nil],
                [3, 3, nil, nil, nil, 3, nil],
                [3, nil, 3, 1, 1, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 2],
                [2, nil, 4, 4, 5, 1, nil, 2],
                [1, nil, nil, nil, nil, nil, 6],
                [nil, 6, 1, 5, 5, 5, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 3, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 56,
            rows: [
                [3, 3, nil, nil, nil, nil, 3, 3],
                [4, nil, nil, nil, nil, nil, 4],
                [4, nil, nil, nil, nil, nil, nil, 4],
                [4, nil, 2, 2, 2, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [2, nil, 2, 2, 5, nil, 5],
                [5, 1, 1, 3, 3, 3, 1, 1],
                [4, 4, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 6, nil, nil, 6, 2, nil],
                [nil, nil, 2, 2, 3, nil, nil],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 57,
            rows: [
                [nil, nil, nil, nil, 1, 1, 1, nil],
                [nil, nil, 4, 4, 4, 4, 3],
                [nil, nil, 3, 1, 3, 3, 4, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, nil, 3, 3, 3, 3, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 1, 2, nil, nil],
                [2, 2, 2, 2, 1, nil, nil],
                [nil, 1, 1, 2, 2, 1, nil, nil],
                [1, 1, 1, 1, 1, nil, nil],
                [4, 4, 4, 4, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, 3, 6, 6, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 58,
            rows: [
                [4, nil, nil, 4, 4, nil, nil, 4],
                [4, nil, 6, 6, 1, nil, 1],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [nil, 1, 1, 1, 1, 4, nil],
                [nil, 4, nil, 4, 4, nil, 4, nil],
                [nil, 4, 1, 1, 1, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [1, 5, 5, 1, 1, 1, 3, 3],
                [1, nil, nil, nil, nil, nil, 3],
                [3, 3, 2, 1, 1, 1, 2, 2],
                [2, nil, nil, nil, nil, nil, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 59,
            rows: [
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 2, 2],
                [4, nil, nil, nil, nil, nil, 6],
                [6, 4, nil, nil, nil, nil, 2, 2],
                [2, 2, 2, 2, 2, 2, 3],
                [3, 3, nil, nil, nil, nil, 5, 5],
                [5, 3, 3, 3, 3, 2, 2],
                [nil, 2, 2, 2, 2, 4, 4, nil],
                [nil, 4, nil, 4, nil, 4, nil],
                [nil, 3, 1, 1, 3, 3, 3, nil],
                [nil, 1, nil, 1, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 60,
            rows: [
                [5, 6, nil, nil, nil, nil, nil, nil],
                [6, 2, nil, nil, nil, nil, nil],
                [2, 2, 2, nil, nil, nil, nil, nil],
                [2, 2, 2, nil, nil, nil, nil],
                [2, 1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil],
                [1, 4, 1, 3, nil, nil, nil, nil],
                [3, 3, 3, 4, nil, nil, nil],
                [1, 1, 5, 5, nil, nil, nil, nil],
                [5, 4, 4, 4, nil, nil, nil],
                [4, 1, 1, 1, 1, nil, nil, nil],
                [2, 2, 6, 1, 1, nil, nil],
                [2, 2, 2, 1, 1, nil, nil, nil],
                [1, 1, 1, 2, 2, nil, nil],
                [2, 2, 4, 3, 3, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
    ]
}
