// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch144 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2861,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 3, 2, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 2, 1, 5, 1, nil, nil],
                [nil, nil, 2, 4, 1, nil, nil],
                [nil, nil, 3, 1, 4, 1, nil, nil],
                [nil, nil, 4, 2, 2, nil, nil],
                [nil, nil, 1, 2, 2, 4, nil, nil],
                [nil, nil, 1, 5, 1, nil, nil],
                [nil, nil, 4, 3, 1, 3, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2862,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [2, 4, 3, 1, 3, 1, 4, 1],
                [nil, nil, nil, nil, 2, nil, nil],
                [1, 3, 1, 1, 3, 2, 4, 4],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 1, nil, 3, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, nil, nil, 1, 6, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2863,
            rows: [
                [nil, nil, 2, 3, 1, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 1, nil, 2, 3, nil, 1],
                [2, 1, nil, 2, 1, nil, 3],
                [nil, 2, 2, 1, 3, 4, 3, nil],
                [2, 1, 2, 1, 3, 5, nil],
                [nil, nil, 1, 2, nil, 3, 2, nil],
                [nil, 1, 2, nil, 1, 4, nil],
                [nil, nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 3, 1, 3, 1, nil, nil],
                [nil, 2, 2, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2864,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [2, 6, 1, 2, 1, 2, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [6, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2865,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, 3, nil, nil, 4, nil, 4, nil],
                [2, nil, nil, 1, nil, nil, 2],
                [nil, 3, nil, nil, 2, nil, 1, nil],
                [3, nil, nil, 1, nil, nil, 4],
                [nil, 1, nil, nil, 3, nil, 1, nil],
                [nil, 5, nil, 1, nil, 5, nil],
                [nil, 1, nil, nil, 2, nil, 1, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2866,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 3, 1, 5, nil, nil],
                [nil, nil, 1, 2, 3, 1, nil, nil],
                [nil, 4, 1, 2, 2, 1, nil],
                [nil, nil, 2, 2, 1, 2, nil, nil],
                [nil, 4, 1, 2, 1, 2, nil],
                [nil, nil, 1, 1, 4, 1, nil, nil],
                [nil, nil, 3, 1, 2, nil, nil],
                [nil, nil, 1, 4, 1, 4, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2867,
            rows: [
                [2, 3, 1, 3, 1, 1, 2, 1],
                [3, nil, nil, 3, nil, nil, 2],
                [1, nil, nil, 2, 1, nil, nil, 2],
                [nil, nil, nil, 1, nil, nil, nil],
                [3, nil, nil, 1, 4, nil, nil, 4],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 4, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2868,
            rows: [
                [4, nil, nil, nil, nil, nil, nil, 1],
                [2, 1, 1, 5, 1, 2, 1],
                [4, nil, nil, nil, nil, nil, nil, 1],
                [3, 3, 2, 1, 4, 3, 1],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [1, 2, 1, 2, 1, 3, 2],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [1, 2, 1, 2, 2, 1, 2],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2869,
            rows: [
                [4, 3, 1, 4, 1, 5, 1, 3],
                [1, 3, 1, 3, 1, 4, 4],
                [1, 2, 1, 3, 1, 2, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 3, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2870,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 1, nil, 1, 3, nil, nil],
                [2, 1, nil, 2, 1, nil, nil],
                [nil, 2, 5, nil, 2, 1, nil, nil],
                [2, 2, nil, 1, 2, nil, nil],
                [nil, 1, 2, nil, 1, 4, nil, nil],
                [1, 3, nil, 4, 1, nil, nil],
                [nil, 4, 1, nil, 3, 4, nil, nil],
                [1, 2, nil, 1, 2, nil, nil],
                [nil, 1, 3, nil, 1, 3, nil, nil],
                [1, 3, nil, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [1, 1, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2871,
            rows: [
                [nil, 3, nil, 2, nil, 2, nil, 1],
                [3, nil, 1, nil, 2, nil, 1],
                [3, nil, 2, nil, 4, nil, 1, nil],
                [nil, 2, nil, 1, nil, 3, nil],
                [1, nil, 5, nil, 1, nil, 2, nil],
                [nil, 3, nil, 4, nil, 5, nil],
                [nil, 3, nil, 1, nil, 3, nil, nil],
                [1, nil, 3, nil, 1, nil, nil],
                [nil, 4, nil, 1, nil, 1, nil, nil],
                [1, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2872,
            rows: [
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, 3, 1, 4, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, 1, 3, nil, 1, 2, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, 2, 3, nil, 6, 2, nil],
                [nil, 1, 1, 3, 2, 4, 3, nil],
                [nil, 1, 1, nil, 1, 2, nil],
                [nil, 1, 3, 3, 4, 1, 2, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2873,
            rows: [
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 2, 4, 4, 1, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, 3],
                [nil, 1, 2, 2, 3, 3, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 2, 1, 6, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, 5, nil],
                [nil, 1, 2, 1, 2, 1, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2874,
            rows: [
                [2, nil, nil, nil, nil, nil, nil, 1],
                [3, 2, 1, 1, 3, 5, 1],
                [3, nil, nil, nil, nil, nil, nil, 1],
                [2, 2, 2, 4, 3, 4, 1],
                [1, nil, nil, nil, nil, nil, nil, 3],
                [3, 1, 3, 1, 4, 1, 3],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2875,
            rows: [
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [3, 1, 1, 3, 3, 1, 1],
                [nil, nil, 6, 2, 1, 2, nil, nil],
                [nil, 2, 1, 3, 1, 2, nil],
                [nil, nil, 1, 3, 2, 1, nil, nil],
                [nil, 2, 3, 2, 3, 2, nil],
                [nil, nil, nil, 5, 3, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2876,
            rows: [
                [nil, 2, 1, nil, nil, nil, nil, nil],
                [4, 1, 3, nil, nil, nil, nil],
                [nil, 3, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, nil, nil, nil],
                [nil, 4, 3, nil, nil, nil, nil, nil],
                [nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil, nil],
                [nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil, nil],
                [nil, nil, nil, 1, 3, 4, nil],
                [nil, nil, nil, nil, 1, 2, nil, nil],
                [nil, nil, nil, 1, 3, 1, nil],
                [nil, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2877,
            rows: [
                [nil, 6, 1, nil, 3, 1, nil, nil],
                [nil, 2, 4, nil, 1, 2, nil],
                [nil, 3, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 4, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 3, 1, 3, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil, nil],
                [nil, 2, 1, 2, nil, nil, nil],
                [nil, 1, 2, 1, nil, nil, nil, nil],
                [nil, 2, 1, 1, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2878,
            rows: [
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2879,
            rows: [
                [3, nil, nil, nil, 1, nil, nil, nil],
                [3, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, 2, 1, nil, nil],
                [nil, 2, nil, 3, nil, 1, nil],
                [nil, 2, nil, nil, 1, 3, nil, nil],
                [nil, 1, nil, 3, nil, 1, nil],
                [nil, 4, nil, nil, 3, 1, nil, nil],
                [3, nil, nil, 1, 3, 4, nil],
                [nil, 1, nil, nil, 1, 4, nil, nil],
                [1, nil, nil, 1, 1, 1, nil],
                [1, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2880,
            rows: [
                [nil, 1, 2, nil, nil, 1, 1, nil],
                [nil, 2, nil, nil, nil, 6, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 6, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 3, nil, nil],
                [nil, 1, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
    ]
}
