// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch25 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 481,
            rows: [
                [3, 3, 3, nil, nil, 3, 3, 3],
                [nil, nil, 3, nil, 3, nil, nil],
                [nil, nil, 3, 2, 2, 2, nil, nil],
                [nil, 2, nil, 2, nil, 4, nil],
                [nil, nil, 4, 1, 1, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 4, 4, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 5, nil, nil],
                [nil, 5, 5, nil, nil, 5, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 6, 6, nil, nil, 7, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 4
        ),
        LevelTemplate(
            levelNumber: 482,
            rows: [
                [nil, nil, 5, 5, 4, nil, nil, nil],
                [nil, 4, 4, 4, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [2, 2, 2, 2, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [1, 1, 7, 1, 1, 1, nil],
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 1, nil, 3, nil, nil, nil],
                [nil, 3, nil, nil, 3, nil, nil],
                [nil, 3, 3, 6, nil, 6, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 3, 2, nil, 2, 2, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 483,
            rows: [
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, 1, nil, 6, nil, 6],
                [6, nil, nil, 3, 3, nil, nil, 4],
                [3, nil, 3, 3, 2, nil, 2],
                [3, nil, nil, 3, 2, nil, nil, 2],
                [5, nil, 5, 5, 5, nil, 2],
                [4, nil, nil, 4, 1, nil, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, nil, 1, nil, 1, nil, 2],
                [2, nil, 2, nil, nil, 2, nil, 2],
                [2, nil, nil, nil, nil, nil, 3],
                [3, nil, 4, nil, nil, 4, nil, 2],
                [2, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 484,
            rows: [
                [nil, nil, nil, 5, 5, 5, 2, nil],
                [2, 2, 2, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [6, nil, nil, nil, nil, nil, nil, 6],
                [3, nil, nil, nil, nil, nil, 3],
                [3, nil, nil, nil, 3, 3, 3, 3],
                [3, nil, nil, 3, 4, 1, 1],
                [1, nil, nil, nil, 4, 4, 4, 4],
                [4, nil, nil, 4, 4, 1, 1],
                [1, nil, nil, nil, 1, 2, 1, 1],
                [1, 1, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 1, 2, 2, 2],
                [2, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 485,
            rows: [
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, 1, nil, 3, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [2, 5, 5, 5, 5, 6, 1, 1],
                [1, nil, nil, nil, nil, nil, 2],
                [2, 2, 4, 4, 4, 7, 6, 6],
                [6, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 486,
            rows: [
                [nil, nil, 3, 3, 3, nil, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 1, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [2, nil, 2, nil, 1, nil, 1, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [2, nil, 2, nil, 2, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 4, nil, 4, nil],
                [nil, 4, nil, 4, nil, 6, nil],
                [6, nil, 4, nil, 4, nil, 5, nil],
                [nil, 5, nil, 7, nil, 5, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 487,
            rows: [
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, 7, 7, 5, 5, 2, 2, nil],
                [nil, 2, 2, 2, 4, 4, nil],
                [nil, 4, 4, 4, 1, 1, 1, nil],
                [nil, 1, 1, 1, 4, 4, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, nil, 6, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 488,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 3, 3, 3, 3],
                [2, nil, nil, nil, nil, nil, nil, 7],
                [1, 2, 2, 2, 2, 2, 4],
                [4, nil, nil, nil, nil, nil, nil, 4],
                [4, 4, 5, 5, 6, 6, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 2, 2, 2, 5, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 489,
            rows: [
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, nil, 2, 2, nil, 2],
                [4, 4, nil, 4, 5, nil, 5],
                [nil, 5, 1, 1, 1, 3, 3, nil],
                [3, 3, 3, 7, 2, 1, nil],
                [nil, nil, 3, 3, nil, 3, 3, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 1, 1, 6, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 490,
            rows: [
                [2, 2, nil, nil, nil, nil, 2, 1],
                [1, 1, nil, nil, nil, 3, 2],
                [2, 2, nil, nil, nil, nil, 2, 3],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 3, nil, nil, nil, nil, 3, 3],
                [3, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, 1, 2, 2, 3, 3],
                [3, 3, nil, nil, nil, nil, 3, 5],
                [5, 2, 2, 2, 2, 2, 2],
                [nil, 4, 4, 4, 4, 4, 4, nil],
                [nil, 4, nil, 3, nil, 3, nil],
                [nil, 7, 2, 2, 2, 2, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 491,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 6, 5, nil, nil],
                [nil, nil, 5, 5, 3, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, nil, 3, 3, nil],
                [nil, 1, 1, nil, nil, 1, 4, nil],
                [4, 4, nil, nil, nil, 4, 4],
                [nil, 4, 3, nil, nil, 3, 3, nil],
                [3, 3, nil, nil, nil, 3, 3],
                [3, 3, nil, nil, nil, nil, 3, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 7],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 492,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [nil, nil, 3, 1, 1, 1, nil, nil],
                [nil, 5, nil, 1, nil, 1, nil],
                [1, nil, nil, 1, 4, nil, nil, 4],
                [2, 2, nil, 2, nil, 1, 7],
                [6, nil, nil, 1, 5, nil, nil, 5],
                [5, 1, nil, 1, nil, 1, 1],
                [nil, 1, 2, 2, 2, 2, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 2, 2, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 493,
            rows: [
                [nil, nil, 4, 4, 4, nil, nil, nil],
                [nil, 4, nil, nil, 3, nil, nil],
                [nil, nil, 3, 3, 3, 3, 3, nil],
                [nil, 3, 3, 1, nil, nil, 1],
                [nil, nil, 1, 1, 1, 2, 2, nil],
                [nil, 2, 2, 2, nil, nil, 2],
                [nil, 2, nil, nil, 2, 2, 2, nil],
                [nil, 2, 1, 1, 1, 1, nil],
                [nil, 1, nil, nil, 1, 1, 1, nil],
                [nil, 1, 5, 5, 5, 4, nil],
                [nil, nil, 4, 7, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 7, 6, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 494,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 7, 7, 4, 4, 4, nil],
                [4, nil, nil, nil, nil, nil, 4],
                [4, nil, 2, 2, 2, 2, nil, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 2, 2, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 3, nil, nil],
                [nil, nil, 3, 4, 3, 5, nil, nil],
                [nil, nil, 3, 4, 3, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 495,
            rows: [
                [nil, 4, 4, nil, nil, 7, 4, nil],
                [4, nil, nil, nil, nil, nil, 4],
                [4, 2, nil, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [5, nil, nil, nil, nil, nil, 5],
                [5, 5, nil, nil, nil, nil, 3, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [3, 3, nil, nil, nil, nil, 3, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [1, 1, nil, nil, nil, nil, 1, 4],
                [1, 1, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 496,
            rows: [
                [nil, 5, 3, nil, 2, 2, 2, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 5, 5, 3, nil, 3, 3, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, 3, 7, 2, nil, 2, 2, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, 4],
                [nil, 4, 5, nil, 5, 2, 2, nil],
                [2, nil, nil, nil, nil, nil, 1],
                [nil, 2, 2, 6, nil, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, 6, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 497,
            rows: [
                [2, 2, 2, 4, 4, 4, 4, 4],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 5, 5, 5, 5, 5],
                [4, 4, 1, 1, 1, 6, 6],
                [2, 2, 7, 7, 2, 2, 2, 3],
                [3, 1, 3, 3, 3, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 498,
            rows: [
                [nil, nil, nil, nil, nil, nil, 2, 2],
                [nil, nil, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, 2, 2],
                [nil, 2, nil, nil, nil, 4, nil],
                [nil, nil, nil, nil, nil, nil, 4, 4],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [5, 5, 3, nil, 1, nil, nil],
                [nil, 1, 6, nil, nil, 4, nil, nil],
                [1, 1, 1, nil, 1, nil, nil],
                [3, nil, 3, 4, 4, 4, nil, 1],
                [nil, 3, nil, 3, nil, 3, 1],
                [1, nil, 5, 3, 3, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, 1],
                [nil, 7, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 499,
            rows: [
                [2, 2, 2, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [2, 6, 6, 3, 3, 3, 3, 3],
                [nil, nil, nil, nil, 3, nil, nil],
                [2, 2, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, 4, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 7, 6],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 500,
            rows: [
                [nil, 1, 1, nil, nil, 4, 4, nil],
                [2, 2, 2, 2, 2, 2, 3],
                [3, 3, 3, 3, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 3, 3, 3, 3, 3, 3, 2],
                [2, 5, 5, 2, 2, 1, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 7, 7, nil, nil, 6, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
    ]
}
