// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch100 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1981,
            rows: [
                [nil, 2, nil, 1, nil, 1, nil, 1],
                [5, 4, nil, 1, 3, nil, 3],
                [3, nil, 4, nil, 1, nil, 1, nil],
                [2, 2, nil, 2, 5, nil, 1],
                [1, nil, 2, nil, 4, nil, 3, nil],
                [3, 1, nil, 1, 2, nil, 1],
                [nil, 2, nil, 2, nil, 4, nil, 2],
                [2, 4, nil, 2, 2, nil, 2],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [4, 1, nil, 4, 4, nil, 1],
                [4, nil, 1, nil, 2, nil, 2, nil],
                [1, 2, nil, 2, 2, nil, 2],
                [6, nil, 1, nil, 1, nil, 1, nil],
                [1, 1, nil, 1, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1982,
            rows: [
                [3, 3, 3, 3, 2, 1, 1, 6],
                [1, 2, 1, 5, 2, 3, 1],
                [2, 1, 1, 1, 4, 4, 2, 1],
                [6, 2, 4, 6, 1, 2, 1],
                [1, 2, 2, 2, 1, 2, 2, 1],
                [2, 2, 2, 1, 1, 4, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1983,
            rows: [
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [3, 3, 3, 4, 4, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, 4],
                [4, 4, 1, 4, 1, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 3, 5, 2, 3, 1, nil],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, 2, 1, 2, 3, 7, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [1, 2, 4, 2, 2, 3, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1984,
            rows: [
                [6, 3, 3, 1, 1, 2, 1, 2],
                [nil, nil, nil, nil, 4, nil, nil],
                [nil, nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [1, 3, 3, 3, 3, 1, 5, 2],
                [nil, nil, nil, nil, 2, nil, nil],
                [2, 1, 2, 1, 1, 4, 1, 1],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1985,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 3, 3, nil, nil],
                [nil, nil, 2, 7, 1, nil, nil],
                [nil, nil, 6, 2, 2, 2, nil, nil],
                [nil, nil, 1, 3, 3, nil, nil],
                [nil, nil, 1, 3, 2, 4, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 1, 2, 2, 2, nil, nil],
                [nil, nil, 1, 2, 6, nil, nil],
                [nil, nil, 1, 1, 2, 1, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1986,
            rows: [
                [nil, nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, 4, 7, 1, nil, nil],
                [nil, nil, 2, 2, 1, 1, nil, nil],
                [nil, 1, 2, 2, 5, 5, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 1, 1, 1, 1, 3, nil],
                [nil, 5, 5, 2, 5, 3, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 3, 3, 3, 1, 1, 2, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1987,
            rows: [
                [nil, 3, nil, 3, nil, 3, nil, 3],
                [2, 4, nil, 4, 1, nil, 1],
                [1, nil, 2, nil, 5, nil, 1, nil],
                [2, 1, nil, 1, 6, nil, 2],
                [1, nil, 4, nil, 3, nil, 3, nil],
                [3, 2, nil, 1, 1, nil, 3],
                [nil, 1, nil, 1, nil, 4, nil, 4],
                [4, 4, nil, 2, 2, nil, 1],
                [nil, 2, nil, 2, nil, 1, nil, 2],
                [1, 2, nil, 2, 2, nil, 1],
                [2, nil, 4, nil, 2, nil, 1, nil],
                [2, 1, nil, 2, 2, nil, 1],
                [4, nil, 1, nil, 2, nil, 1, nil],
                [1, 1, nil, 1, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1988,
            rows: [
                [1, 1, 1, 2, 4, 1, 2, 1],
                [2, 6, 1, 1, 1, 2, 1],
                [2, 1, 2, 2, 1, 1, 3, 2],
                [5, 5, 2, 2, 1, 2, 3],
                [1, 3, 3, 1, 1, 5, 1, 6],
                [1, 3, 3, 3, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1989,
            rows: [
                [nil, nil, nil, 3, 4, nil, nil, nil],
                [nil, 4, 1, nil, nil, nil, nil],
                [4, 5, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, nil, 1, 2, nil],
                [5, 5, nil, 4, 3, nil, nil, nil],
                [nil, nil, nil, nil, 1, 3, nil],
                [nil, nil, nil, 2, 2, nil, 2, 1],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, 1, 2],
                [nil, 1, 1, nil, nil, nil, nil],
                [4, 4, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [5, 4, nil, 1, 4, nil, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, 6, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1990,
            rows: [
                [nil, nil, 1, 2, 3, nil, nil, nil],
                [nil, nil, 3, 1, 5, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 2, nil, 4, nil, 2, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [4, nil, 4, nil, 2, nil, 2, nil],
                [nil, 1, nil, 7, nil, 2, nil],
                [1, nil, 3, nil, 3, nil, 1, nil],
                [nil, 2, nil, 6, nil, 1, nil],
                [2, nil, 1, nil, 5, nil, 1, nil],
                [nil, 2, nil, 1, nil, 2, nil],
                [1, nil, 2, nil, 1, nil, 1, nil],
                [nil, 2, nil, 4, nil, 2, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1991,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 2],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 3, 3, 2, nil, nil],
                [nil, nil, 1, 1, 5, 5, nil, nil],
                [nil, 2, 6, 4, 4, 4, nil],
                [nil, 2, 1, 5, 5, 1, 2, nil],
                [nil, 2, 2, 1, 1, 2, nil],
                [nil, nil, 1, 3, 1, 1, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 3, 3, nil, nil],
                [nil, nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1992,
            rows: [
                [nil, 1, 1, 1, 4, 6, 2, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 2, nil, nil, nil, nil, 4, nil],
                [3, 3, 2, 1, 2, 5, 6],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [4, 4, 2, 1, 4, 1, 2],
                [nil, 2, 1, 1, 1, 2, 2, nil],
                [nil, 2, 3, 1, 2, 1, nil],
                [nil, 5, 4, 1, 2, 3, 3, nil],
                [nil, 2, 1, 2, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1993,
            rows: [
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [4, 4, 4, 2, 3, 3, 1, 1],
                [nil, nil, nil, nil, nil, nil, 2],
                [2, 2, 3, 3, 1, 1, 1, 5],
                [nil, nil, nil, nil, nil, nil, 4],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, 2, 3, 6, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 2, 5, 1, 5, 5, nil],
                [nil, 5, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [2, 1, 5, 2, 2, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1994,
            rows: [
                [1, 2, 2, 2, 4, 4, 1, 3],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [4, 4, 1, 1, 3, 1, 5, 1],
                [nil, nil, nil, nil, 5, nil, nil],
                [5, 5, 5, 6, 1, 3, 1, 3],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1995,
            rows: [
                [nil, 2, 3, 1, 2, 2, 2, nil],
                [nil, 1, 3, 1, 3, 3, nil],
                [nil, nil, 3, 1, 4, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 4, 2, 2, 2, 2, 1, 1],
                [3, nil, nil, nil, nil, nil, 4],
                [5, nil, 5, 1, 1, 2, nil, 2],
                [4, nil, 1, 2, 3, nil, 1],
                [2, nil, 1, 2, 3, 1, nil, 3],
                [2, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 4, 4, 1, 1, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 1, 3, 4, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1996,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 3, 3, nil, nil],
                [nil, nil, 1, 6, 1, nil, nil],
                [nil, nil, 2, 1, 1, 3, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 2, 1, 1, 5, nil, nil],
                [nil, nil, 1, 3, 6, nil, nil],
                [nil, nil, 3, 1, 4, 2, nil, nil],
                [nil, nil, 1, 2, 4, nil, nil],
                [nil, nil, 3, 1, 3, 1, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1997,
            rows: [
                [nil, 2, nil, 1, nil, 4, nil, 3],
                [3, nil, 1, nil, 3, nil, 3],
                [1, nil, 4, nil, 1, nil, 2, nil],
                [nil, 4, nil, 1, nil, 1, nil],
                [5, nil, 1, nil, 1, nil, 4, nil],
                [nil, 4, nil, 3, nil, 1, nil],
                [nil, 1, nil, 2, nil, 2, nil, nil],
                [1, nil, 2, nil, 2, nil, nil],
                [nil, 3, nil, 2, nil, 1, nil, nil],
                [6, nil, 1, nil, 2, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, 1, nil, 5, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1998,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 2, 2, 4, 3, nil, nil],
                [nil, 4, 4, 4, 1, 2, nil],
                [nil, nil, 1, 1, 5, 5, nil, nil],
                [nil, 5, 1, 2, 2, 2, nil],
                [nil, 2, 2, 1, 1, 2, 1, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 3, 6, 1, 2, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1999,
            rows: [
                [nil, nil, 4, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, 4, nil, nil],
                [nil, nil, nil, 3, nil, nil, 4, nil],
                [nil, nil, 4, nil, nil, 1, nil],
                [nil, nil, nil, nil, 6, nil, nil, 1],
                [nil, nil, nil, 2, nil, nil, 3],
                [nil, nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, 3, 3, 5, 5, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2000,
            rows: [
                [3, 2, nil, nil, nil, nil, 1, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, nil, 3, 2, 7, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 2, 2, nil, nil, nil],
                [2, 2, nil, nil, nil, nil, 3, 2],
                [5, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 6, nil, nil, 5, nil, nil, 2],
                [1, nil, nil, 6, nil, nil, 4],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
    ]
}
