// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch17 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 321,
            rows: [
                [nil, nil, nil, nil, nil, nil, 5, 5],
                [nil, nil, 5, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, 2, 2],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2, 2],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 3, 3, nil, nil, 3, nil, nil],
                [3, 3, 3, nil, 3, nil, nil],
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [1, 1, 1, nil, 1, nil, nil],
                [5, nil, 1, 1, 4, 4, nil, 4],
                [nil, 4, nil, 1, nil, 1, 1],
                [6, nil, 2, 1, 1, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, 1],
                [nil, 7, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 322,
            rows: [
                [3, nil, nil, 3, 3, nil, nil, 3],
                [1, 2, 2, 2, 2, 2, 6],
                [nil, 2, 3, nil, nil, 3, 3, nil],
                [3, nil, 3, 4, 4, nil, 4],
                [nil, 4, 4, nil, nil, 1, 1, nil],
                [2, nil, 2, 2, 2, nil, 2],
                [nil, 2, 5, nil, nil, 5, 5, nil],
                [nil, nil, 5, 1, 1, nil, nil],
                [nil, 1, 3, nil, nil, 3, 3, nil],
                [nil, nil, 3, 7, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 323,
            rows: [
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [3, nil, nil, 3, nil, nil, 3],
                [1, 1, 1, 1, 1, 1, 1, 4],
                [4, nil, nil, 4, nil, nil, 4],
                [2, 5, 5, 5, 6, 1, 1, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, 3, nil, 3, nil, nil, 3, nil],
                [nil, nil, 3, 3, nil, nil, nil],
                [nil, 3, nil, 3, nil, nil, 2, nil],
                [nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, 2, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, 7, 2, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 324,
            rows: [
                [nil, nil, 4, nil, nil, 4, nil, nil],
                [nil, 4, nil, nil, 4, nil, nil],
                [nil, nil, nil, 1, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil, 2],
                [nil, nil, nil, 2, nil, nil, 3],
                [nil, nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, 7],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 1, 1, nil, nil],
                [nil, 1, 7, 5, 5, 7, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 325,
            rows: [
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, 2, 2, 2, 1, 1, 1, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 1, 1, 5, 5, 5, 5, nil],
                [1, 1, 1, 2, 2, 2, 2],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 3, 3, 7, 3, 3, 3, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, 6, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, 7, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 326,
            rows: [
                [3, nil, nil, nil, 3, nil, nil, 3],
                [3, 3, nil, nil, 1, nil, 1],
                [nil, nil, 1, nil, 1, nil, 1, nil],
                [5, nil, 5, 2, nil, 2, nil],
                [nil, nil, 2, nil, 2, nil, 2, nil],
                [1, nil, 1, 1, nil, 1, nil],
                [1, 1, 1, 1, 1, 1, nil, 1],
                [nil, nil, 2, 2, 2, 4, 4],
                [4, 4, 4, 4, 3, 6, nil, 6],
                [nil, nil, 6, 6, 1, 1, 1],
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [1, 1, nil, nil, nil, 2, 2],
                [nil, 2, 2, nil, nil, 2, nil, nil],
                [2, 2, nil, nil, nil, 2, 1],
                [1, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 327,
            rows: [
                [nil, 4, 4, nil, 4, 4, nil, nil],
                [4, nil, 1, 1, nil, 1, nil],
                [1, nil, nil, nil, nil, nil, 2, nil],
                [2, 2, 6, nil, nil, 6, 1],
                [1, nil, nil, nil, nil, nil, 1, nil],
                [1, 7, 2, nil, nil, 2, 2],
                [nil, 5, 1, 1, 1, 1, 1, 1],
                [nil, 1, 5, nil, nil, 5, 5],
                [nil, 5, 2, 2, 2, 2, 3, 3],
                [nil, 1, 3, nil, nil, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 328,
            rows: [
                [2, 5, 5, 2, 2, 2, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, 2, 2, 2, 2, 2],
                [2, nil, nil, nil, 2, 2, 1],
                [1, nil, nil, 1, 1, 1, 1, 5],
                [5, nil, nil, nil, 4, 4, 1],
                [1, nil, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, 1, 5],
                [1, 1, nil, nil, nil, nil, nil],
                [1, 2, 5, 6, nil, nil, nil, nil],
                [3, 3, 1, 1, nil, nil, nil],
                [1, 3, 3, 3, nil, nil, nil, nil],
                [3, 3, 5, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 329,
            rows: [
                [nil, nil, 1, 2, nil, nil, nil, nil],
                [nil, 2, 2, 2, nil, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 1, 1, 1, 4, 4, nil, nil],
                [4, 4, 4, 4, 3, 2, 2],
                [2, 2, 2, 2, 2, 1, 1, 1],
                [1, 1, 1, 1, 3, 3, 3],
                [3, 3, 3, 3, 3, 3, 3, 3],
                [5, 5, 5, 6, 6, 6, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 330,
            rows: [
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 2, 2, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 4, nil],
                [nil, 4, 4, 1, 1, 1, nil],
                [nil, 3, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 6, nil],
                [nil, nil, 6, 3, 3, 7, nil, nil],
                [nil, nil, 7, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 3, nil, 3, nil, nil],
                [nil, nil, 3, 3, 3, 5, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 5, 5, 5, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 331,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [1, 1, nil, 1, 1, nil, nil],
                [nil, 1, 3, nil, 3, 3, nil, nil],
                [3, 3, nil, 3, 3, nil, nil],
                [nil, 3, 3, nil, 3, 3, nil, nil],
                [3, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, 6, nil, nil],
                [2, 2, nil, 2, 2, nil, nil],
                [nil, 2, 2, nil, 2, 2, nil, nil],
                [2, 2, nil, 2, 2, nil, nil],
                [nil, 2, 2, nil, 5, 4, nil, nil],
                [4, 4, nil, 7, 7, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 332,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 4, 4, 4, 4, nil, nil],
                [nil, 1, nil, 1, nil, 3, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [5, nil, nil, 1, 1, nil, nil, 1],
                [1, 1, nil, 1, nil, 1, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, 1, nil, 1, nil, 1, 1],
                [nil, 1, 5, 5, 2, 2, 7, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 2, 2, 6, 2, 2, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 333,
            rows: [
                [nil, 5, 5, 5, 5, 5, 2, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [1, 1, 3, 3, 3, 3, 3],
                [nil, 3, 3, 3, 2, 2, 1, nil],
                [nil, 1, 1, 1, 2, 2, nil],
                [nil, 2, 2, 2, 2, 6, 6, nil],
                [nil, 7, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 334,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, 1, 6, 6, 2, nil, nil],
                [nil, 2, 2, nil, 2, 2, nil],
                [nil, 2, 5, nil, nil, 5, 5, nil],
                [5, 5, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [4, 4, nil, nil, nil, 4, 2],
                [4, 1, nil, nil, nil, nil, 1, 2],
                [2, nil, nil, nil, nil, nil, 4],
                [4, 4, nil, nil, nil, nil, 4, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 335,
            rows: [
                [6, nil, nil, nil, nil, nil, nil, 6],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 4, 4, 4, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 3, 3, 3, 3, 3, nil],
                [nil, 3, 2, 2, 2, 2, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 7, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 336,
            rows: [
                [4, 4, nil, nil, nil, nil, nil, nil],
                [2, 3, nil, nil, nil, nil, nil],
                [3, 3, 3, nil, nil, nil, nil, nil],
                [3, 3, 3, nil, nil, nil, nil],
                [4, 4, 4, nil, nil, nil, nil, nil],
                [4, 4, 4, nil, nil, nil, nil],
                [4, 4, 5, 5, nil, nil, nil, nil],
                [5, 5, 2, 2, nil, nil, nil],
                [2, 2, 2, 2, nil, nil, nil, nil],
                [2, 2, 2, 3, nil, nil, nil],
                [3, 1, 1, 1, 1, nil, nil, nil],
                [2, 2, 2, 1, 1, nil, nil],
                [1, 1, 1, 1, 6, nil, nil, nil],
                [1, 1, 1, 1, 6, nil, nil],
                [1, 1, 1, 1, 1, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 337,
            rows: [
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [1, nil, nil, 2, 2, nil, nil, 2],
                [2, nil, 2, 2, 2, nil, 2],
                [2, nil, nil, 2, 2, nil, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
                [2, nil, nil, 2, 4, nil, nil, 4],
                [4, nil, 7, nil, 5, nil, 3],
                [5, nil, 5, nil, nil, 3, nil, 5],
                [5, nil, nil, nil, nil, nil, 5],
                [5, nil, 5, nil, nil, 3, nil, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 338,
            rows: [
                [nil, nil, 6, 1, 1, nil, nil, nil],
                [nil, 2, 1, 1, 1, nil, nil],
                [nil, 1, 4, 4, 4, 4, nil, nil],
                [4, 4, 3, 3, 3, 3, nil],
                [nil, 3, 3, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, 2, 5, nil, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, 7, nil, 5, 5, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 339,
            rows: [
                [nil, nil, nil, 4, 4, 1, 1, nil],
                [1, 2, 2, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, nil, 1, 1, 1, 1],
                [1, nil, nil, 2, 2, 2, 2],
                [2, nil, nil, nil, 1, 1, 1, 1],
                [1, nil, nil, 1, 1, 2, 2],
                [2, nil, nil, nil, 2, 2, 2, 2],
                [5, 5, nil, nil, nil, nil, nil],
                [5, nil, nil, nil, 3, 3, 3, 7],
                [3, 3, nil, nil, nil, nil, nil],
                [4, 3, 3, nil, nil, nil, nil, nil],
                [3, 6, 2, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 340,
            rows: [
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, 3, nil, 3, nil, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [1, 1, 1, 1, 1, 6, 7, 7],
                [4, nil, 4, nil, 1, nil, 1],
                [1, 1, 1, 1, 2, 2, 2, 2],
                [1, nil, 1, nil, 1, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
    ]
}
