// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch37 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 721,
            rows: [
                [nil, 2, 2, nil, 3, 3, 3, 4],
                [4, 4, 4, 1, 1, 1, 1],
                [nil, 1, nil, nil, 3, nil, 3, 3],
                [nil, 3, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, 2, 1, 2, nil],
                [2, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, 2, nil, 2, 2, nil],
                [nil, nil, nil, 2, nil, nil, 2],
                [nil, nil, nil, 2, nil, 6, 1, nil],
                [nil, 1, 1, 1, nil, 1, 4],
                [5, 5, 5, 5, 1, 1, 1, 1],
                [1, nil, 1, 1, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil, nil],
                [1, nil, nil, nil, nil, 6, nil],
                [nil, nil, nil, nil, nil, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 722,
            rows: [
                [3, 1, 1, 1, nil, 1, nil, 1],
                [nil, 1, nil, nil, 1, 1, nil],
                [2, 2, nil, 2, nil, 2, nil, 2],
                [nil, 2, 2, nil, nil, nil, nil],
                [nil, nil, 2, nil, 1, 1, nil, nil],
                [1, nil, 1, nil, 1, 1, 1],
                [nil, 1, nil, 1, nil, 1, 1, 1],
                [1, 1, 1, nil, 1, 1, 5],
                [5, 5, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, nil, 1, 1, 6],
                [6, 6, 4, 4, 4, 4, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 3, 3, 3, 1, 1, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 723,
            rows: [
                [nil, 1, 1, 1, nil, 2, 2, nil],
                [2, 2, 2, nil, nil, 2, nil],
                [2, 2, 2, 1, nil, 3, 3, 3],
                [3, 3, nil, nil, nil, 1, 1],
                [1, 1, 4, nil, 4, 4, nil, nil],
                [2, 2, nil, nil, 2, nil, 6],
                [nil, 5, 1, 1, 1, 1, nil, nil],
                [1, nil, 1, nil, 1, 1, 1],
                [1, 6, 6, 6, 1, nil, nil, nil],
                [nil, nil, 4, nil, 1, 1, 1],
                [1, 5, 1, 1, 1, 5, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 724,
            rows: [
                [2, nil, 2, 2, 2, nil, 4, 1],
                [1, 1, nil, nil, nil, 1, nil],
                [1, nil, 1, nil, 1, 1, nil, 3],
                [3, 3, 3, nil, 3, 3, 3],
                [nil, 3, 2, nil, 2, 2, 2, nil],
                [2, nil, nil, nil, 2, 2, nil],
                [nil, 2, nil, nil, 1, nil, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, nil, 4, 4, 4, 4, 5, 5],
                [5, 5, 5, nil, 5, 1, 1],
                [1, 1, 1, 1, 3, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 6, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 725,
            rows: [
                [nil, 4, nil, 3, nil, 3, nil, nil],
                [nil, nil, nil, 3, 3, 3, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [nil, 3, 3, 4, 4, 4, 4, nil],
                [nil, 4, 4, nil, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [nil, nil, 2, 2, nil, 2, nil],
                [nil, 2, 2, 1, 1, nil, 1, nil],
                [nil, nil, 1, nil, 1, 1, nil],
                [nil, nil, nil, 1, nil, 1, nil, nil],
                [nil, 1, 1, 5, nil, 5, nil],
                [nil, 5, nil, 5, nil, 1, 1, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, 1, 1, 1, 6, 1, 4, nil],
                [nil, 4, 4, 1, 1, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 726,
            rows: [
                [nil, 1, nil, 2, 2, nil, 1, nil],
                [nil, 1, 1, 1, nil, nil, 1],
                [nil, nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, 1, 1, 1],
                [1, 1, 1, 3, 3, 3, nil, nil],
                [nil, nil, nil, 3, nil, nil, 3],
                [nil, nil, nil, nil, 3, nil, nil, nil],
                [3, 3, 3, 3, 2, nil, nil],
                [nil, 1, nil, nil, 1, 1, 1, nil],
                [1, 1, nil, 2, nil, nil, 2],
                [2, nil, nil, 2, 2, 1, 1, 2],
                [nil, 2, 2, nil, 2, nil, 2],
                [2, 2, 5, 5, 4, nil, 4, nil],
                [nil, 4, nil, nil, 1, nil, 1],
                [1, 1, 1, nil, nil, nil, nil, nil],
                [nil, nil, 6, 4, 4, 6, 6],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 727,
            rows: [
                [3, 3, 3, nil, 3, 3, 3, nil],
                [nil, 3, 3, 3, 3, 5, 5],
                [nil, nil, 5, 1, nil, nil, nil, 1],
                [1, 1, nil, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, nil, 1, nil],
                [nil, 1, 1, 1, nil, nil, 1],
                [1, 1, 1, 1, nil, 2, 2, 2],
                [4, nil, 1, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 2, 2, nil, 2, 2, nil, nil],
                [nil, 2, 2, 4, 4, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [nil, 2, 6, 6, 5, 5, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 728,
            rows: [
                [nil, nil, nil, 3, 3, 3, 6, nil],
                [nil, nil, 4, nil, nil, nil, 4],
                [4, nil, 4, nil, nil, 4, 1, 1],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, 1],
                [3, nil, 2, 2, nil, nil, 2, 2],
                [nil, 2, nil, 2, 2, nil, nil],
                [nil, nil, nil, nil, 2, 5, nil, 5],
                [nil, 5, nil, 5, 5, 1, nil],
                [nil, 1, nil, nil, 1, 2, nil, nil],
                [nil, nil, nil, 2, nil, 1, nil],
                [nil, nil, nil, nil, 1, 1, nil, 1],
                [1, nil, 1, nil, 1, 4, 2],
                [2, 2, nil, nil, 2, nil, 2, 2],
                [2, 3, 3, 3, 3, 3, 3],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 729,
            rows: [
                [5, nil, nil, nil, 2, nil, 2, 2],
                [nil, nil, nil, nil, 2, nil, 2],
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [2, nil, nil, 1, 1, 3, nil],
                [3, 3, 3, nil, nil, 3, 3, nil],
                [nil, nil, nil, 4, nil, nil, 1],
                [1, 1, 1, 2, nil, nil, 2, 2],
                [2, nil, nil, nil, 2, nil, 2],
                [2, 2, nil, nil, nil, nil, 2, nil],
                [5, 5, nil, nil, nil, nil, nil],
                [5, nil, nil, 5, 1, 1, nil, 1],
                [1, nil, nil, 1, 1, 1, 1],
                [1, 1, 1, 1, nil, nil, nil, 1],
                [nil, nil, 1, 1, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, 1, 1],
                [1, 4, 4, 6, 4, 4, 6],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 730,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, 2, nil, 3, 3, nil, nil],
                [nil, 3, nil, nil, nil, 3, 3, nil],
                [3, 3, 3, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, 1, 1, 1, 1],
                [nil, nil, 1, 1, nil, nil, nil, 1],
                [4, 4, nil, 4, 4, 1, 1],
                [nil, 1, nil, 1, nil, 1, 1, nil],
                [3, nil, nil, nil, 1, 1, 1],
                [nil, 6, 6, 6, 2, 2, 2, 2],
                [nil, 2, 2, 2, 1, 1, 1],
                [nil, 1, 1, 5, 5, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 731,
            rows: [
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, 1, 1, 1, 1, nil, 1, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, 4, 4, 4, nil, 4, nil],
                [nil, 4, 4, nil, 6, 6, nil],
                [nil, nil, 6, 2, 6, nil, 1, nil],
                [nil, 1, 1, 2, 2, 2, nil],
                [nil, 2, 1, nil, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, nil, nil],
                [nil, 1, 2, nil, nil, 2, 2, nil],
                [nil, nil, 2, 2, nil, 2, nil],
                [nil, 2, 1, 3, 3, 3, 3, nil],
                [nil, 3, 3, 3, 1, 1, nil],
                [nil, 1, 1, 1, 5, 1, 1, nil],
                [nil, 1, 1, 1, 2, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 732,
            rows: [
                [4, 4, 4, 4, 4, nil, 4, 4],
                [nil, 4, nil, nil, 4, 4, nil],
                [1, nil, 1, 1, nil, 1, nil, 1],
                [1, 1, 1, nil, nil, 1, nil],
                [1, 1, nil, nil, 3, 3, 3, 3],
                [3, 3, nil, nil, nil, nil, 3],
                [1, 1, 1, 1, nil, 1, nil, 1],
                [nil, 1, nil, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, 1, 2, 2],
                [2, 2, nil, nil, 2, 2, 2],
                [2, 2, nil, 2, nil, nil, 6, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, 5, nil, 5, 5, 5, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 733,
            rows: [
                [nil, 2, nil, 2, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, 2, 1, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, 1, 1, 1, 4, 4, nil],
                [nil, nil, nil, nil, 4, 4, nil],
                [nil, 4, nil, 4, 4, 4, nil, nil],
                [nil, nil, nil, nil, 3, 3, nil],
                [nil, nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 1, nil],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, 5, 5, 3, 3, 3, nil],
                [nil, 3, 3, 3, 3, 3, 3, nil],
                [nil, 6, 6, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 734,
            rows: [
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, nil, nil, 1, nil],
                [nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, 4, 4, 4, 4, nil],
                [nil, nil, nil, 4, 4, 2, 2, nil],
                [nil, nil, 2, 2, 2, 2, nil],
                [nil, 6, 6, nil, nil, 5, 5, nil],
                [nil, 5, 5, 5, 3, nil, nil],
                [nil, nil, 3, 2, 2, 2, 3, nil],
                [nil, nil, nil, 3, 3, nil, nil],
                [nil, 3, 3, nil, nil, 2, 2, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, 2, 3, 3, 3, 3, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 735,
            rows: [
                [nil, 4, 2, nil, 2, 2, 2, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, 2, nil, 2, 2, 2, 5, nil],
                [nil, 5, nil, nil, 3, 3, nil],
                [nil, nil, 3, 3, 3, 1, 1, nil],
                [nil, 1, 4, 4, 4, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [nil, nil, nil, nil, 1, 1, 5, nil],
                [nil, 5, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, 1, 6, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 4, 3, 5, 5, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 736,
            rows: [
                [nil, 1, nil, nil, nil, 1, 1, 1],
                [1, nil, 1, nil, nil, nil, nil],
                [1, nil, 4, 4, nil, 4, nil, 4],
                [4, nil, nil, nil, 2, 2, 2],
                [2, nil, 2, nil, 2, nil, nil, 6],
                [nil, 6, 1, nil, nil, nil, nil],
                [3, 3, 3, 3, 3, 3, nil, 3],
                [nil, nil, 3, nil, 3, 3, 3],
                [3, 3, 1, 2, 2, 2, 1, 1],
                [1, 1, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 5, 5, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, 5, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 737,
            rows: [
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 4, 4, nil, nil],
                [nil, 4, 4, 4, 4, nil, nil, nil],
                [nil, 4, 1, nil, nil, nil, nil],
                [nil, nil, 1, nil, 1, 1, 1, nil],
                [nil, 1, nil, 6, 4, 3, nil],
                [nil, nil, 3, 3, nil, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, nil, 3, 2, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, 2, 2, nil, 2, 5, nil],
                [nil, nil, 5, nil, nil, 5, nil],
                [nil, nil, nil, 5, 5, nil, 3, nil],
                [nil, 3, nil, 1, nil, 1, nil],
                [nil, 1, 1, nil, 1, 3, 3, nil],
                [nil, 3, 3, 1, 3, 3, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 738,
            rows: [
                [nil, nil, 1, 1, 1, nil, 1, nil],
                [nil, 1, nil, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 2, nil],
                [nil, 2, 2, 2, nil, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [nil, 3, 3, 3, nil, 1, nil],
                [nil, 1, 2, 2, nil, nil, 2, nil],
                [nil, nil, nil, 2, 2, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, 4, 4, nil, 4, 4, nil, nil],
                [nil, nil, 4, 4, 1, 1, nil],
                [nil, 5, 3, nil, nil, 3, 3, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, 3, 1, nil, 1, 1, 1, nil],
                [nil, nil, 1, 6, 6, 6, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 739,
            rows: [
                [nil, nil, 4, nil, 4, 4, nil, nil],
                [nil, 1, nil, 1, nil, nil, 5],
                [5, nil, 5, nil, nil, 5, nil, 5],
                [3, 3, nil, nil, 3, nil, 3],
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [nil, 3, nil, nil, nil, nil, 3],
                [3, 1, 1, nil, nil, 1, 1, 1],
                [1, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [1, 1, 1, 1, nil, 1, nil],
                [1, nil, 1, 3, nil, nil, 3, 2],
                [2, nil, nil, 2, 2, 2, nil],
                [nil, 2, 2, 2, nil, 2, nil, 2],
                [6, 6, 6, 1, 1, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 740,
            rows: [
                [nil, 1, 3, 3, 3, 3, nil, nil],
                [nil, nil, 3, nil, 3, 2, nil],
                [nil, 2, nil, 2, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, 2, nil, 2, 2, nil, nil],
                [nil, nil, 1, nil, 1, 4, nil],
                [nil, 4, 4, 4, 4, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, nil, 1, nil, nil],
                [nil, nil, 1, 4, 4, nil, nil],
                [nil, 4, 1, nil, 1, nil, 1, nil],
                [nil, nil, 2, 2, nil, 6, nil],
                [nil, 1, 1, 1, 1, 1, 5, nil],
                [nil, 5, 5, 1, 1, 1, nil],
                [nil, 2, 1, 1, 1, 2, 1, nil],
                [nil, 6, 1, 1, 1, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
    ]
}
