// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch27 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 521,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 1],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, 1, 3, nil],
                [nil, 3, 3, 3, 4, 2, 1, nil],
                [nil, 1, 1, 1, 3, 3, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, 5, 5, 5, nil, nil],
                [nil, nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, 4, 4, 7, nil, nil],
                [nil, nil, nil, 7, 6, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 522,
            rows: [
                [nil, nil, 2, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [4, nil, 4, nil, 4, nil, 4, nil],
                [nil, 1, nil, 1, nil, 3, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 7, nil, 6, nil],
                [6, nil, 3, nil, 3, nil, 4, nil],
                [nil, 5, nil, 5, nil, 5, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 523,
            rows: [
                [nil, nil, 2, 2, 1, 3, nil, nil],
                [nil, 3, 3, 3, 7, 1, nil],
                [nil, 1, 3, 3, 3, 5, 5, nil],
                [nil, 5, 3, 3, 3, 3, nil],
                [nil, 3, 2, 4, 4, 4, 1, nil],
                [nil, 1, 2, 2, 2, 2, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 6, 5, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 524,
            rows: [
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, 2, nil, 2, 2, nil],
                [nil, 2, 1, 1, 1, 2, 2, nil],
                [nil, 2, 2, nil, 2, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [3, nil, nil, 3, 3, nil, nil, 3],
                [3, nil, nil, 4, nil, nil, 4],
                [4, nil, nil, 4, 4, nil, nil, 4],
                [4, nil, nil, 5, nil, nil, 2],
                [nil, 2, 2, 2, 7, 6, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 525,
            rows: [
                [nil, 2, nil, 5, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
                [nil, 2, nil, 2, nil, 5, nil, 5],
                [1, nil, 3, nil, 3, nil, 3],
                [nil, 3, nil, 6, nil, 6, nil, 6],
                [2, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 2, nil, 2],
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [4, nil, 4, nil, 4, nil, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 526,
            rows: [
                [3, nil, nil, nil, nil, nil, nil, 3],
                [1, 1, 2, 2, 2, 2, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [1, 1, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 5, 6, 6],
                [6, nil, nil, nil, nil, nil, nil, 2],
                [2, 2, 2, 2, 2, 2, 2],
                [7, nil, nil, nil, nil, nil, nil, 4],
                [5, 5, 4, 4, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 527,
            rows: [
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 2, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 1, 1, 6, nil, nil],
                [nil, nil, 6, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 5, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 7, 5, 4, nil, nil],
                [nil, nil, 5, 3, 5, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 528,
            rows: [
                [nil, nil, 3, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil, 2],
                [nil, nil, nil, 2, nil, nil, 2],
                [nil, nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, 6],
                [nil, nil, nil, nil, nil, nil, 6],
                [nil, nil, nil, 6, 3, nil, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 4, 4, 7, 7, nil, nil],
                [nil, 5, 3, 2, 3, 3, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 529,
            rows: [
                [nil, 1, nil, 1, nil, 2, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 7, nil],
                [7, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 2, nil, 1, nil, 1, nil, nil],
                [2, nil, 2, nil, 2, nil, nil],
                [nil, 2, nil, 4, nil, 5, nil, nil],
                [5, nil, 5, nil, 3, nil, nil],
                [nil, nil, 3, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, 4, nil, 4, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 530,
            rows: [
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 3, nil, 4, 4, nil, 4],
                [4, 3, nil, 3, 1, nil, 1],
                [nil, 4, 4, 2, 2, 2, 2, nil],
                [2, 5, 2, 1, 1, 1, nil],
                [nil, nil, 1, 1, nil, 1, 1, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 3, nil, nil],
                [nil, nil, 3, 2, 2, 2, nil, nil],
                [nil, 2, 2, 5, 5, nil, nil],
                [nil, nil, nil, 5, 6, nil, nil, nil],
                [nil, nil, 7, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 531,
            rows: [
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 6, 2, nil, nil, nil],
                [nil, nil, 5, 5, 7, nil, nil],
                [nil, nil, nil, 7, 3, nil, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, 4, 4, 7, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 532,
            rows: [
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, 1, 3, 2, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [2, 4, 2, nil, nil, 2, 4, 3],
                [nil, nil, 3, nil, 2, nil, nil],
                [2, 2, 2, nil, nil, 7, 3, 3],
                [nil, nil, 3, nil, 5, nil, nil],
                [nil, nil, 5, 5, 5, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, 6, 6, 6, nil, nil],
                [nil, 7, nil, nil, nil, 4, nil],
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 533,
            rows: [
                [nil, nil, 6, nil, nil, 6, 1, nil],
                [nil, 1, 1, nil, nil, 1, 1],
                [5, nil, nil, 5, 5, 2, nil, nil],
                [3, 3, nil, 3, nil, nil, nil],
                [3, nil, nil, 3, 2, 2, nil, nil],
                [1, 2, nil, 2, nil, nil, nil],
                [2, nil, 1, 1, 1, 1, 1, nil],
                [nil, 7, nil, nil, 7, nil, 4],
                [4, nil, 4, 4, 4, 2, 2, nil],
                [nil, 2, nil, nil, 2, nil, 2],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 3, nil, nil, nil, 3, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 534,
            rows: [
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, 2],
                [2, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [3, nil, nil, nil, nil, nil, 3],
                [3, 3, nil, nil, nil, nil, 1, 2],
                [2, 2, 4, 4, 4, 4, 4],
                [4, 4, nil, nil, nil, nil, 4, 2],
                [2, 2, 2, 2, 2, 2, 2],
                [nil, 2, 2, 2, 2, 2, 5, nil],
                [nil, 7, nil, 3, nil, 3, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 6, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 535,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 5, nil, 5, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [2, 2, nil, nil, nil, 2, 2],
                [nil, 2, 2, nil, nil, 4, 6, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [3, 3, nil, nil, nil, nil, 7, 3],
                [1, nil, nil, nil, nil, nil, 3],
                [3, 3, nil, nil, nil, nil, 6, 4],
                [4, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 536,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [nil, nil, 3, 2, 2, 2, nil, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [2, nil, nil, 2, 1, nil, nil, 1],
                [1, 1, nil, 1, nil, 1, 3],
                [3, nil, nil, 3, 3, nil, nil, 3],
                [3, 5, nil, 5, nil, 4, 4],
                [nil, 4, 1, 5, 7, 1, 7, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 6, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 537,
            rows: [
                [nil, nil, 3, 3, 3, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 6, 6, nil, nil, 4],
                [nil, nil, 4, 4, 4, 4, 4, nil],
                [nil, 2, 2, 1, nil, nil, 4],
                [nil, 4, nil, nil, 4, 4, 4, nil],
                [nil, 4, 2, 2, 2, 5, nil],
                [nil, 5, nil, nil, 1, 1, 1, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, nil, 2, 2, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 5, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 538,
            rows: [
                [3, 3, nil, 3, 3, nil, 3, 3],
                [3, nil, nil, 3, nil, nil, 3],
                [3, nil, nil, 3, nil, nil, 3, nil],
                [2, nil, nil, 2, nil, nil, 4],
                [4, nil, nil, 4, nil, nil, 4, nil],
                [7, nil, nil, 5, nil, nil, 6],
                [6, nil, nil, 1, nil, nil, 1, nil],
                [1, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1, nil],
                [1, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1, nil],
                [1, nil, nil, 1, nil, nil, 1],
                [4, nil, nil, 4, nil, nil, 2, nil],
                [2, nil, nil, 2, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 539,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 1, 1, nil, 1, 5, nil],
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, 2, 2, nil, 2, 2, nil],
                [nil, 3, 3, 3, 2, 2, 1, nil],
                [nil, 2, 7, nil, 7, 1, nil],
                [nil, 5, 2, 2, 2, 4, 4, nil],
                [nil, 4, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 540,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, 1, 4, 4, nil],
                [4, 4, 4, 4, 4, 4, 2],
                [nil, 2, 6, 6, 1, 1, 1, nil],
                [1, 1, 1, 1, 1, 2, 2],
                [nil, 2, 2, 2, 3, 3, 3, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 3, 3, 1, 1, 1, 1, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, 1, 1, 7, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
    ]
}
