// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch142 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2821,
            rows: [
                [nil, nil, 1, nil, nil, 3, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, 3, 1, 2, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, 5, 2, 4, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 3, 4, 2, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2822,
            rows: [
                [nil, nil, 4, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 3, 2, 1, nil, nil],
                [nil, 3, 1, 2, 2, nil, nil],
                [nil, 3, 1, 4, 5, 1, 3, nil],
                [nil, 1, 3, 1, 1, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2823,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 4, 5, 2, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, nil, 3, 1, 3, nil, nil],
                [nil, nil, 1, 5, 1, 4, nil, nil],
                [nil, nil, 1, 5, 2, nil, nil],
                [nil, nil, 2, 3, 1, 3, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, 3, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2824,
            rows: [
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2825,
            rows: [
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, 1, 5, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 4, 3, 2, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, 3, 5, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2826,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, 4, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 4, 1, 4, 1, nil, nil],
                [nil, 2, 5, 2, 4, nil, nil],
                [nil, 3, 2, 1, 3, 1, 5, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2827,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 1, 3, 2, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 2, 4, 1, 2, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 3, 5, 2, 1, nil, nil],
                [nil, nil, 5, 1, 6, nil, nil],
                [nil, nil, 1, 2, 1, 3, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 3, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2828,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [4, 1, 4, 3, 1, 3, 1, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 1, 2, 1, 3, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2829,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 2],
                [1, 6, 1, 1, 2, 3, 2],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [4, 2, 1, 1, 5, 5, 1],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [2, 2, 4, 2, 1, 2, 1],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2830,
            rows: [
                [nil, 1, 2, nil, nil, nil, nil, nil],
                [4, 1, 2, nil, nil, nil, nil],
                [nil, 1, 3, nil, nil, nil, nil, nil],
                [nil, nil, 5, 5, nil, nil, nil],
                [nil, 3, 1, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 1, 4, 2, nil, nil, nil],
                [nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 4, 3, nil, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, 4, 1, nil, nil],
                [nil, nil, nil, 4, 1, 3, nil],
                [nil, nil, nil, nil, 1, 2, nil, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2831,
            rows: [
                [nil, nil, nil, 1, 6, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2832,
            rows: [
                [nil, 3, 5, nil, nil, 1, 2, nil],
                [nil, 1, nil, nil, nil, 5, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 4, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 5, nil, nil, nil, 4, nil, nil],
                [nil, 3, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2833,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 3, 1, 5, 2, nil],
                [4, nil, nil, nil, nil, nil, 2],
                [3, nil, 3, 3, 2, 1, nil, 2],
                [3, nil, nil, nil, nil, nil, 2],
                [nil, 1, 1, 2, 1, 3, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 1, 2, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, 2, 1, 1, 1, nil, nil],
                [nil, nil, 5, 2, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2834,
            rows: [
                [nil, nil, 4, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, 3, nil, nil],
                [nil, nil, nil, 1, nil, nil, 3, nil],
                [nil, nil, 2, nil, nil, 1, nil],
                [nil, nil, nil, nil, 2, nil, nil, 1],
                [nil, nil, nil, 3, nil, nil, 1],
                [nil, nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, 3, 2, 1, 1, nil, nil],
                [nil, 1, 4, 1, 2, 3, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2835,
            rows: [
                [nil, 1, nil, 4, nil, 2, nil, 1],
                [4, nil, 1, nil, 3, nil, 2],
                [nil, 1, nil, 1, nil, 1, nil, 4],
                [1, nil, 3, nil, 1, nil, 1],
                [nil, 1, nil, 5, nil, 2, nil, 2],
                [1, nil, 5, nil, 1, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2836,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, 1, 4, 2, 1, 3, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 1, 1, 3, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, 4, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 3, 1, 3, 1, 6, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, 1, 1, 1, 2, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2837,
            rows: [
                [nil, nil, 1, nil, nil, 3, nil, nil],
                [nil, nil, 1, 1, 3, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 4, 5, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 4, 2, 1, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 4, 1, 3, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2838,
            rows: [
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 5, 3, 1, 2, nil, nil],
                [nil, 1, 3, 2, 1, nil, nil],
                [nil, 1, 2, 2, 4, 2, 4, nil],
                [nil, 2, 2, 2, 2, 2, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2839,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 3, 1, 1, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 4, 1, 2, 1, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 5, 2, 4, 1, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 1, 2, 4, 1, nil, nil],
                [nil, nil, 2, 3, 2, nil, nil],
                [nil, nil, 3, 3, 1, 2, nil, nil],
                [nil, nil, 1, 5, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2840,
            rows: [
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [3, 1, 4, 1, 2, 3, 1, 1],
                [nil, nil, nil, nil, 4, nil, nil],
                [1, 2, 1, 1, 2, 3, 1, 3],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, 5, nil, 2, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
    ]
}
