// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch16 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 301,
            rows: [
                [1, nil, nil, nil, 1, nil, nil, 1],
                [1, 1, nil, nil, 1, nil, 1],
                [nil, nil, 4, nil, 4, nil, 4, nil],
                [4, nil, 4, 4, nil, 5, nil],
                [nil, nil, 5, nil, 2, nil, 3, nil],
                [3, nil, 1, 2, nil, 2, nil],
                [2, 2, 2, 2, 2, 2, nil, 1],
                [nil, nil, 1, 1, 1, 6, 1],
                [3, 1, 1, 1, 1, 1, nil, 1],
                [nil, nil, 1, 3, 3, 3, 3],
                [nil, 3, 3, nil, nil, 3, nil, nil],
                [3, 3, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [6, nil, nil, nil, nil, nil, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 302,
            rows: [
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [1, nil, 2, 2, nil, 2, nil],
                [1, nil, nil, nil, nil, nil, 1, nil],
                [1, 1, 1, nil, nil, 1, 1],
                [4, nil, nil, nil, nil, nil, 4, nil],
                [4, 4, 4, nil, nil, 4, 4],
                [nil, 2, 2, 2, 7, 7, 4, 4],
                [nil, 4, 3, nil, nil, 3, 2],
                [nil, 3, 3, 3, 2, 2, 2, 1],
                [nil, 1, 1, nil, nil, 1, 6],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 303,
            rows: [
                [3, 3, 3, 1, 3, 3, 3, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [1, nil, nil, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, 1, 1, 1],
                [1, nil, nil, 1, 1, 1, 6, 6],
                [6, nil, nil, nil, 5, 5, 1],
                [1, nil, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, 2, 2],
                [1, 1, nil, nil, nil, nil, nil],
                [1, 1, 5, 2, nil, nil, nil, nil],
                [2, 2, 2, 2, nil, nil, nil],
                [2, 4, 4, 4, nil, nil, nil, nil],
                [4, 4, 5, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 304,
            rows: [
                [nil, nil, 4, 4, nil, nil, nil, nil],
                [nil, 4, 4, 4, nil, nil, nil],
                [nil, 4, 4, 1, 1, 1, nil, nil],
                [1, 7, 5, 5, 5, 1, 1],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [2, 2, 2, 2, 2, 1, 1],
                [1, 2, 2, 2, 2, 2, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 3],
                [3, 6, 5, 1, 5, 5, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 305,
            rows: [
                [nil, nil, 6, 3, 3, 3, nil, nil],
                [nil, 3, 3, 3, 3, 2, nil],
                [nil, 2, 2, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 5, 5, 5, nil],
                [nil, 5, 5, 2, 4, 4, nil],
                [nil, nil, 4, 2, 2, 2, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, nil, 5, 7, 1, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 306,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, 5, nil, 5, 6, nil, nil],
                [6, 2, nil, 2, 2, nil, nil],
                [nil, 2, 2, nil, 2, 2, nil, nil],
                [2, 2, nil, 2, 2, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [1, 1, nil, 3, 3, nil, nil],
                [nil, 3, 3, nil, 3, 3, nil, nil],
                [3, 3, nil, 3, 3, nil, nil],
                [nil, 3, 3, nil, 5, 4, nil, nil],
                [1, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, 3, nil, nil],
                [1, 1, nil, 7, 7, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 307,
            rows: [
                [nil, nil, nil, 7, 1, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 4, 4, nil, nil],
                [nil, 4, nil, 4, nil, 4, nil],
                [nil, nil, 4, 4, 1, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, 1, nil, 1, nil, 1, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, 1, nil, 3, nil, 3, 3],
                [nil, 3, 3, 3, 3, 3, 5, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 3, 2, 6, 5, 2, 1, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 6, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 308,
            rows: [
                [5, 5, nil, nil, nil, nil, nil, nil],
                [5, 5, nil, nil, nil, nil, nil],
                [5, 5, 4, nil, nil, nil, nil, nil],
                [4, 4, 6, nil, nil, nil, nil],
                [2, 2, 2, nil, nil, nil, nil, nil],
                [2, 3, 3, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 3, 3, 3, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [1, 1, 1, 1, 1, nil, nil, nil],
                [3, 3, 3, 1, 1, nil, nil],
                [1, 1, 1, 1, 1, nil, nil, nil],
                [4, 5, 2, 4, 4, nil, nil],
                [4, 4, 2, 2, 2, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 309,
            rows: [
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, 4, nil, 4, nil, 4],
                [2, nil, nil, 2, 2, nil, nil, 2],
                [2, nil, 2, 2, 2, nil, 2],
                [2, nil, nil, 2, 2, nil, nil, 2],
                [2, nil, 2, 2, 2, nil, 2],
                [3, nil, nil, 3, 3, nil, nil, 3],
                [3, nil, 3, nil, 1, nil, 1],
                [6, nil, nil, 6, 1, nil, nil, 7],
                [5, nil, 5, nil, 5, nil, 5],
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 310,
            rows: [
                [nil, nil, nil, 2, 2, 5, 5, nil],
                [5, 2, 2, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, 2, 4, 4, 4],
                [4, nil, nil, 4, 4, 4, 1],
                [1, nil, nil, nil, 1, 1, 1, 3],
                [3, nil, nil, 3, 3, 6, 6],
                [1, nil, nil, nil, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, 2, 2, 2, 2],
                [4, 4, nil, nil, nil, nil, nil],
                [1, 2, 2, nil, nil, nil, nil, nil],
                [1, 2, 7, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 311,
            rows: [
                [5, 5, 5, 1, 1, 1, 1, 1],
                [1, 1, 4, 4, 4, 2, 2],
                [2, 2, 2, 1, 2, 2, 2, 2],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 3, 3, 3, 3, 3, 3],
                [3, 3, 1, 4, 7, 7, 6],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 312,
            rows: [
                [2, 2, 3, nil, nil, 3, 3, 3],
                [nil, nil, 3, nil, 3, nil, nil],
                [nil, nil, 3, 3, 5, 5, nil, nil],
                [nil, 5, nil, 5, nil, 5, nil],
                [nil, nil, 5, 1, 1, 1, nil, nil],
                [nil, 1, nil, 4, nil, 4, nil],
                [nil, nil, 4, 4, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, 6, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 313,
            rows: [
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 3, nil, 3, 3, nil, 1],
                [6, 1, nil, 2, 4, nil, 4],
                [nil, 4, 4, 4, 2, 3, 3, nil],
                [3, 1, 1, 1, 1, 2, nil],
                [nil, nil, 2, 2, nil, 2, 2, nil],
                [nil, 2, 2, nil, 2, 1, nil],
                [nil, nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 7, 3, 3, nil, nil],
                [nil, 3, 3, 7, 7, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 314,
            rows: [
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 2, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2],
                [nil, 2, 5, 5, 5, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [6, nil, nil, nil, nil, nil, nil],
                [nil, 6, 4, 4, 7, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 315,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 5, 5, nil, nil, nil, nil],
                [nil, 5, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
                [2, 2, 1, 1, 1, 1, 1, nil],
                [1, 1, 1, 3, 3, 3, nil],
                [3, 2, 2, 2, 2, 2, 2, nil],
                [2, 2, 2, 6, 6, 3, nil],
                [1, 1, 4, 4, 1, 7, 7, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 4, 4, 4, 3, 3, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 316,
            rows: [
                [2, nil, 2, 2, 2, 2, nil, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 2, 2, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, 2, 7, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 4, 4, 4, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 6],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [2, nil, 2, nil, 1, nil, 5],
                [nil, 5, nil, 5, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 3, nil, 3],
                [3, nil, 3, nil, 7, nil, 6],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 317,
            rows: [
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 4, 4, 4, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 4, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 6, nil, nil],
                [nil, nil, 6, 6, 6, 1, nil, nil],
                [nil, nil, 5, 5, 5, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 318,
            rows: [
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 4, 1, 3, 3, nil, nil],
                [nil, 3, 3, 3, 3, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 4, nil],
                [nil, 4, 1, 3, 2, 6, 6, nil],
                [nil, 6, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 5, 5, nil],
                [nil, 5, 5, 5, 2, 2, nil],
                [nil, 2, 2, 2, 1, 1, 1, nil],
                [nil, 4, 4, 3, 3, 3, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 319,
            rows: [
                [nil, nil, nil, nil, 4, 4, 4, nil],
                [nil, nil, 4, 4, 4, 2, 5],
                [nil, nil, 5, 5, 5, 1, 1, nil],
                [nil, 1, 1, 1, 6, 1, nil],
                [nil, nil, 3, 1, 1, 1, 1, nil],
                [nil, 1, 2, 2, 2, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, 3, nil, nil],
                [nil, 3, 3, 3, 3, 3, nil, nil],
                [2, 7, 2, 3, 2, nil, nil],
                [2, 2, 2, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 320,
            rows: [
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 6, 1],
                [1, 3, nil, nil, nil, nil, 3, 3],
                [2, nil, nil, nil, nil, nil, 3],
                [3, 3, nil, nil, nil, nil, 3, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, 2, 2, 2, 5, 5, 5],
                [4, 4, nil, nil, nil, nil, 4, 4],
                [4, 4, 1, 1, 1, 1, 2],
                [nil, 2, 2, 2, 2, 1, 5, nil],
                [nil, 5, nil, 5, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
    ]
}
