// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch09 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 161,
            rows: [
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, 2, 4, nil],
                [nil, 4, 4, 4, 5, 5, 5, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 3, 3, 3, 3, nil],
                [nil, 7, 7, 1, 1, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 3, nil, 3, nil, nil],
                [nil, nil, 1, 1, 5, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 162,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 3, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, 2, 4, 3, 1, nil],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [6, 6, 5, 5, 5, 5, 4],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [1, 1, 1, 4, 4, 4, 4],
                [nil, 4, nil, 3, 3, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, nil, 1, 1, nil, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 163,
            rows: [
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 2, nil, 2, nil],
                [2, nil, 2, nil, 5, nil, 5, nil],
                [nil, 5, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 2, nil, 2, nil],
                [2, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [2, nil, 2, nil, 3, nil, 3, nil],
                [nil, 3, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 7, 7, 3, 3, 2, 2, 2],
                [2, 2, 2, 4, 4, 4, 4],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 164,
            rows: [
                [nil, nil, 4, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 3, nil, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 5, nil, nil],
                [nil, nil, 5, 1, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 5, 5, 5, nil, nil],
                [nil, nil, 5, 4, 4, nil, nil],
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, nil, 1, 7, 7, nil, nil],
                [nil, nil, 1, 6, 1, 1, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 1, 2, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 165,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, 3, 3, 3, 1, 1, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [1, 1, 1, 1, 1, 1, 5],
                [nil, 2, 2, 5, 3, 3, 3, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 4, 4, 4, 6, 2, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 7, 5, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 166,
            rows: [
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, 2, 2, 2, 2, 2, 2],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, 2, 4, 4, 4, 4, 3],
                [3, 3, nil, nil, nil, nil, 3, 3],
                [1, 1, 3, 3, 3, 3, 3],
                [1, 1, nil, nil, nil, nil, 5, 5],
                [5, 5, 1, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, 1, 1, 1, 6, 6],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 167,
            rows: [
                [nil, nil, nil, nil, 3, 3, 3, nil],
                [nil, nil, 1, 1, 1, 1, 1],
                [nil, nil, 1, 1, 2, 2, 2, nil],
                [nil, 6, 6, 2, 3, 3, nil],
                [nil, nil, 3, 3, 3, 3, 3, nil],
                [nil, 2, 2, 1, 1, 1, nil],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [2, 2, 2, 2, 1, nil, nil],
                [nil, 1, 1, 4, 4, 4, nil, nil],
                [4, 4, 4, 1, 1, nil, nil],
                [1, 1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 7, 5, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 168,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [2, 1, nil, 1, nil, 1, 1],
                [1, 1, 1, 1, 1, 2, 4, 4],
                [4, 3, nil, 3, nil, 3, 3],
                [3, 5, nil, 5, 2, nil, 2, 2],
                [2, nil, nil, 2, nil, nil, 2],
                [6, 6, nil, 2, 2, nil, 2, 2],
                [2, nil, nil, 2, nil, nil, 2],
                [2, 2, 1, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, 6, 5, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 169,
            rows: [
                [nil, nil, nil, nil, nil, 1, 1, 4],
                [nil, nil, nil, nil, 4, 4, 4],
                [nil, 6, 6, 6, 2, nil, 2, 2],
                [1, 2, 2, 2, nil, nil, nil],
                [nil, 2, 2, 2, 3, nil, 3, 1],
                [1, 1, 1, 1, nil, nil, nil],
                [1, nil, nil, nil, 2, 2, 2, 2],
                [2, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, 2, 2, 2, 1],
                [1, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 5, 5, nil, 1, nil],
                [3, 3, 3, 3, 3, 3, 3],
                [3, 1, 1, 1, 1, nil, 1, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 170,
            rows: [
                [1, nil, nil, nil, 1, nil, nil, 2],
                [2, 2, nil, nil, 2, nil, 1],
                [nil, nil, 3, nil, 1, nil, 1, nil],
                [1, nil, 1, 3, nil, 3, nil],
                [nil, nil, 2, nil, 2, nil, 2, nil],
                [2, nil, 2, 2, nil, 2, nil],
                [2, 2, 2, 2, 2, 1, nil, 1],
                [nil, nil, 1, 4, 4, 3, 3],
                [3, 1, 7, 1, 1, 1, nil, 1],
                [nil, nil, 1, 1, 3, 3, 5],
                [nil, 5, 5, nil, nil, 1, nil, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [1, 1, nil, nil, nil, 5, 4],
                [6, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 171,
            rows: [
                [nil, 1, nil, 1, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, nil],
                [nil, 1, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil, nil],
                [nil, 1, nil, 1, nil, 5, nil],
                [nil, 5, nil, 5, nil, 1, nil, nil],
                [nil, 4, nil, 4, nil, 1, nil],
                [nil, 3, nil, 3, nil, 3, nil, nil],
                [nil, 3, nil, 1, nil, 1, nil],
                [nil, 2, nil, 2, nil, 2, nil, nil],
                [nil, 3, nil, 6, nil, 6, nil],
                [nil, 6, nil, 7, nil, 7, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 172,
            rows: [
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, nil, 1, 2, 2, nil, 2],
                [nil, 2, nil, 2, 1, nil, 1, nil],
                [nil, 5, 5, 1, 1, 6, nil],
                [nil, 6, nil, 4, 4, nil, 1, nil],
                [nil, 1, 3, 3, 3, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [3, 3, 3, 1, 1, 2, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 7, 1, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 173,
            rows: [
                [nil, 1, 1, nil, 1, 1, 2, nil],
                [2, nil, nil, nil, nil, nil, 4],
                [nil, 4, 4, 4, nil, 4, 5, nil],
                [5, nil, nil, nil, nil, nil, 1],
                [nil, 1, 1, 1, nil, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 1, 2, nil, 7, 2, 2, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 1, 1, 3, nil, 3, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 6, 3, 2, nil, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 174,
            rows: [
                [2, 2, 2, 2, 2, 2, 2, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, 1, 1, 1],
                [4, nil, nil, 4, 4, 4, 1, 1],
                [1, nil, nil, nil, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, 1, 1],
                [3, 3, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, 4, 4],
                [4, 4, nil, nil, nil, nil, nil],
                [5, 5, 5, 5, nil, nil, nil, nil],
                [7, 2, 2, 3, nil, nil, nil],
                [3, 4, 3, 3, nil, nil, nil, nil],
                [3, 3, 3, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 175,
            rows: [
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 4, 4, 4, nil, nil],
                [nil, 4, 4, 4, 4, nil, nil],
                [nil, 4, 3, 3, 3, 3, 3, nil],
                [nil, 3, 1, 2, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 5, 6, nil],
                [nil, 5, 5, 5, 5, 5, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 176,
            rows: [
                [1, 6, nil, nil, nil, nil, 6, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [4, nil, nil, nil, nil, nil, nil, 4],
                [1, nil, 1, 1, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [1, 1, 4, 4, 3, 2, 2, 2],
                [1, 1, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 3, 3, 3, 3],
                [3, 3, 3, nil, 3, 3, 3],
                [nil, 5, 5, nil, nil, 2, 2, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, 5, 5, nil, nil, 4, 4, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 177,
            rows: [
                [nil, nil, 2, 2, nil, nil, nil, nil],
                [nil, 3, 3, 3, nil, nil, nil],
                [nil, 3, 3, 3, 3, 3, nil, nil],
                [3, 3, 5, 1, 1, 3, 3],
                [nil, 3, 1, 6, 6, 6, nil, nil],
                [4, 4, 4, 4, 4, 2, 2],
                [2, 5, 5, 2, 2, 2, 2, 2],
                [2, 2, 1, 1, 1, 1, 3],
                [3, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 178,
            rows: [
                [5, nil, nil, 5, 5, nil, nil, 1],
                [1, 1, 2, 2, 2, 4, 4],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [2, nil, 2, 2, 2, nil, 3],
                [nil, 3, 3, nil, nil, 3, 1, nil],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, 6, nil, nil, 6, 5, nil],
                [nil, nil, 5, 5, 4, nil, nil],
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, 4, 1, 1, 1, 1, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 4, 4, 4, 2, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 179,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, 1, 1, 1, 5, 5, 1, nil],
                [nil, 2, 2, nil, 5, 5, nil],
                [nil, 5, 5, 3, 3, 3, 4, nil],
                [nil, 2, 2, nil, 2, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [4, nil, nil, 4, 4, nil, nil, 6],
                [3, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 3],
                [3, nil, nil, 3, nil, nil, 3],
                [nil, 3, 3, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 180,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [3, 3, 3, 3, nil, nil, nil],
                [3, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 3, 3, 3, 3],
                [4, nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, nil, 4, 4, 4, 4],
                [4, nil, nil, nil, 1, nil, nil, 7],
                [2, 2, 2, 2, nil, nil, nil],
                [2, nil, nil, nil, 2, nil, nil, 2],
                [2, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, 1],
                [nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, 1, nil, nil, nil, 7],
                [nil, nil, nil, 5, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
    ]
}
