// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch95 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1881,
            rows: [
                [nil, 1, 1, nil, 1, nil, nil, nil],
                [nil, 2, 1, 2, 1, nil, 4],
                [nil, nil, 1, 1, nil, 2, nil, nil],
                [1, nil, 2, nil, 1, nil, nil],
                [4, nil, 1, 3, nil, nil, 3, 3],
                [3, 1, nil, 5, 4, 1, 1],
                [nil, 1, nil, nil, 2, 1, 5, 4],
                [nil, 2, 1, nil, 1, 2, 1],
                [2, 2, nil, nil, nil, 1, 2, 2],
                [nil, 2, nil, 1, nil, 1, 2],
                [1, 2, 2, 4, nil, 4, 1, 1],
                [1, 5, 1, 2, 1, 2, 1],
                [1, 2, 1, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1882,
            rows: [
                [nil, 2, nil, 1, nil, 4, nil, 4],
                [4, nil, nil, nil, 6, 5, 1],
                [2, 2, nil, 1, 2, nil, nil, nil],
                [1, nil, nil, 2, 3, 3, nil],
                [3, nil, 3, 1, nil, nil, 4, nil],
                [4, 1, 2, 1, nil, 2, 5],
                [1, nil, nil, 1, 2, 1, 2, 2],
                [1, 1, nil, nil, 1, nil, 3],
                [nil, 3, nil, 1, nil, nil, 1, nil],
                [nil, 5, nil, 1, 5, 1, 2],
                [1, 1, nil, nil, nil, 1, nil, 2],
                [nil, nil, nil, 1, nil, nil, nil],
                [2, 1, 5, 1, 2, 1, nil, nil],
                [1, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, 1, 1],
                [nil, nil, 1, nil, nil, 1, 1],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1883,
            rows: [
                [nil, nil, 1, 2, nil, 1, 6, nil],
                [nil, 1, nil, nil, 4, nil, nil],
                [nil, 1, 1, nil, 3, nil, 1, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, 1, 4, 1, 1, 1, nil],
                [nil, 2, 2, 1, 2, 1, nil],
                [nil, 6, 1, 2, 1, 1, 2, nil],
                [nil, 2, 2, 2, 1, 4, nil],
                [nil, 4, 1, 3, 1, 3, 1, nil],
                [nil, 2, 1, 5, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1884,
            rows: [
                [nil, 1, 2, nil, nil, nil, nil, nil],
                [5, 5, 2, nil, nil, nil, nil],
                [nil, 3, 3, nil, nil, nil, nil, nil],
                [nil, nil, 3, 3, nil, nil, nil],
                [nil, 1, 4, nil, nil, nil, nil, nil],
                [nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil, nil],
                [nil, nil, nil, 1, 2, 2, nil],
                [nil, nil, nil, nil, 6, 2, nil, nil],
                [nil, nil, nil, 2, 1, 3, nil],
                [nil, nil, nil, nil, 2, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1885,
            rows: [
                [nil, nil, 2, 6, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 5, nil, 1, 1, nil, 4],
                [1, 2, nil, 1, 4, nil, 1],
                [nil, 4, 4, 4, 4, 5, 3, nil],
                [3, 2, 2, 1, 1, 1, nil],
                [nil, nil, 4, 1, nil, 3, 1, nil],
                [nil, 1, 3, nil, 2, 6, nil],
                [nil, nil, nil, 1, 2, 3, nil, nil],
                [nil, nil, 1, 1, 4, nil, nil],
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, 2, 1, 5, 3, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1886,
            rows: [
                [nil, 2, 2, nil, nil, nil, 1, nil],
                [nil, 2, 1, 2, 1, 1, 4],
                [1, 1, 2, 3, nil, 3, 1, nil],
                [2, 2, 2, nil, 1, 1, nil],
                [nil, 4, 1, 1, nil, nil, nil, nil],
                [1, 3, 3, nil, 3, 1, nil],
                [6, nil, 4, nil, nil, 2, 1, 2],
                [2, nil, 1, 2, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, nil, nil],
                [2, 1, 2, 1, nil, 2, nil],
                [nil, 2, 2, 1, nil, 1, nil, nil],
                [nil, 5, 1, 5, 5, 1, 5],
                [1, 1, 4, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1887,
            rows: [
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, 1, 3, 2, 1, 1, nil],
                [nil, 2, 2, 2, 2, 1, 5, nil],
                [nil, 1, 4, 1, 1, 1, nil],
                [nil, 1, 3, 3, 3, 1, 2, nil],
                [nil, 1, 2, 2, 1, 4, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, 1, 6, 1, 1, nil, nil],
                [nil, nil, 1, nil, 3, nil, nil],
                [nil, nil, 1, 6, 1, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1888,
            rows: [
                [nil, 1, nil, 5, nil, nil, 5, 3],
                [nil, nil, 2, nil, 2, 2, 3],
                [nil, nil, nil, 3, 1, 1, nil, nil],
                [nil, nil, nil, 4, nil, 2, 2],
                [2, 1, 1, nil, 1, nil, 2, 1],
                [nil, 4, 3, 4, nil, nil, 2],
                [nil, 1, 2, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, 1, nil, nil],
                [nil, nil, 5, 5, nil, 3, nil, nil],
                [nil, 3, nil, nil, 3, nil, 1],
                [3, 1, 2, 1, 3, 3, nil, 1],
                [nil, 6, 2, 2, 4, nil, nil],
                [nil, 1, nil, nil, nil, 2, 1, 4],
                [1, 3, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1889,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 5, 1, 2, 1, nil, nil],
                [nil, 4, nil, 4, nil, 4, nil],
                [nil, nil, 5, 3, 1, 1, nil, nil],
                [nil, 1, nil, 3, nil, 3, nil],
                [1, nil, nil, 3, 3, nil, nil, 1],
                [1, 1, nil, 2, nil, 1, 5],
                [1, nil, nil, 2, 3, nil, nil, 1],
                [2, 1, nil, 4, nil, 1, 5],
                [nil, 1, 1, 2, 1, 1, 2, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1890,
            rows: [
                [nil, nil, 2, 1, nil, nil, nil, nil],
                [nil, 3, 2, 2, nil, nil, nil],
                [nil, 4, 4, 1, 2, 2, nil, nil],
                [2, 1, 1, 1, 2, 2, 3],
                [nil, 1, 3, 5, 6, 3, nil, nil],
                [1, 1, 5, 3, 4, 1, 4],
                [4, 2, 1, 2, 2, 1, 3, 3],
                [1, 2, 2, 1, 3, 1, 1],
                [1, 5, 1, 5, 1, 6, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1891,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 3, 1, 1, 1, nil, nil],
                [nil, nil, 4, nil, 4, 4, nil],
                [nil, nil, 1, 2, 1, 3, nil, nil],
                [nil, 1, 5, 2, 4, 1, nil],
                [nil, 1, 1, 2, 3, 3, 3, nil],
                [1, 4, 1, 2, 1, 1, 2],
                [nil, 2, 2, 1, 1, 1, 2, nil],
                [3, 2, 2, 2, 5, 3, 3],
                [1, 1, 2, 1, 2, 1, 4, 4],
                [1, 1, nil, nil, nil, nil, 1],
                [2, 1, 5, 1, 3, 1, 2, 1],
                [1, 1, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1892,
            rows: [
                [nil, nil, nil, nil, nil, 1, nil, nil],
                [nil, 1, 1, nil, nil, nil, 3],
                [1, 2, nil, 4, nil, nil, nil, nil],
                [1, 5, 1, 3, 1, nil, nil],
                [1, nil, 2, nil, nil, 3, 3, nil],
                [1, 1, 1, 6, 3, 3, 1],
                [1, 1, 1, 1, nil, 1, nil, nil],
                [2, 2, nil, 2, nil, nil, 1],
                [5, 3, nil, 3, nil, 3, nil, nil],
                [nil, 3, 1, nil, nil, nil, nil],
                [nil, nil, 1, 3, 3, 1, 2, 2],
                [nil, 2, nil, nil, 3, nil, 2],
                [2, nil, 1, 3, 1, 1, 1, nil],
                [nil, 6, 3, nil, 3, nil, nil],
                [nil, 1, 1, nil, 2, nil, nil, 2],
                [nil, 3, 3, 1, 1, 1, 1],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1893,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, 3, 4, 5, 5, nil, nil],
                [nil, 5, 1, 2, 6, 2, nil],
                [nil, nil, 1, 3, 3, 1, nil, nil],
                [nil, 3, 1, 2, 1, 4, nil],
                [nil, 1, 2, 4, 1, 1, 2, nil],
                [1, 3, 1, 3, 3, 3, 1],
                [nil, 5, 1, 1, 1, 2, 2, nil],
                [1, 1, 2, 1, 2, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1894,
            rows: [
                [nil, nil, 6, 6, nil, 4, nil, nil],
                [1, 3, 3, nil, nil, nil, 5],
                [1, 1, 1, 1, nil, 1, 3, nil],
                [3, 2, nil, nil, 4, 1, 4],
                [1, 3, 5, nil, nil, nil, 5, nil],
                [1, nil, 1, nil, 2, 3, 1],
                [1, 1, 2, 3, 3, 3, 4, nil],
                [nil, 1, 2, nil, 1, 1, nil],
                [nil, nil, 1, 2, 1, nil, 2, nil],
                [3, nil, 2, nil, 2, 3, 3],
                [2, 2, 1, 2, 2, 2, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 2, 1, 4, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1895,
            rows: [
                [nil, nil, 3, 3, 1, nil, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, 1, 4, 2, 1, nil, 1, nil],
                [nil, nil, 2, nil, nil, 2, nil],
                [nil, nil, nil, 1, nil, 2, nil, nil],
                [nil, 1, 4, 3, 1, 1, nil],
                [nil, 6, 4, 4, 1, 3, 3, nil],
                [nil, 1, 1, 2, 2, 1, nil],
                [nil, 1, 2, 1, 1, 2, 2, nil],
                [nil, 2, 1, 2, 1, 4, nil],
                [nil, 1, 1, 5, 1, 2, 1, nil],
                [nil, 1, 2, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1896,
            rows: [
                [nil, 5, nil, nil, nil, 5, nil, 5],
                [1, 3, 1, 2, nil, nil, 2],
                [nil, 2, 2, nil, 2, nil, 1, 1],
                [2, 1, nil, 4, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, 1, nil],
                [2, nil, 2, 2, nil, 1, 2],
                [3, 2, 1, 3, 2, 2, 1, 1],
                [3, 1, nil, nil, nil, 1, 1],
                [4, 1, 2, 1, nil, nil, 3, 1],
                [3, 3, nil, 3, 1, 3, nil],
                [2, 1, nil, nil, 2, 1, nil, 2],
                [2, 2, 1, 3, nil, 1, nil],
                [2, nil, 1, nil, 2, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, 1],
                [1, 1, 1, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1897,
            rows: [
                [nil, nil, 1, nil, 1, 2, nil, nil],
                [nil, 2, 3, 2, 2, nil, nil],
                [nil, 2, 2, nil, nil, 2, 3, nil],
                [nil, 1, 1, 3, 3, nil, nil],
                [nil, 2, 1, 3, nil, 1, 3, nil],
                [nil, 3, 1, 4, nil, 4, nil],
                [nil, 4, 2, 5, 3, nil, 2, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, 1, 3, nil, nil],
                [nil, nil, 3, 1, 2, 1, nil],
                [nil, 1, 2, 2, 1, 1, 2, nil],
                [nil, 2, 5, 3, 3, 2, nil],
                [nil, 1, 2, 1, 1, 1, 1, nil],
                [nil, 3, 1, 2, 1, 1, nil],
                [nil, 2, 2, 1, 3, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1898,
            rows: [
                [1, nil, 2, nil, nil, nil, 3, nil],
                [1, nil, 2, 1, nil, nil, 1],
                [nil, 3, 1, nil, nil, 4, 4, 1],
                [3, 3, 1, 1, 2, 3, nil],
                [1, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, 2, 3, 3, 1, nil],
                [3, nil, nil, nil, nil, 2, nil, nil],
                [2, 2, nil, 2, nil, 1, 5],
                [1, 6, nil, nil, nil, 2, nil, nil],
                [4, 2, 1, nil, nil, 4, 4],
                [nil, 1, 2, 1, 2, 1, 1, nil],
                [nil, 2, nil, 1, 1, 2, 4],
                [1, 3, 1, 1, nil, 1, 1, 1],
                [2, 1, nil, nil, 3, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1899,
            rows: [
                [3, 3, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, 3, nil, 4, nil],
                [nil, nil, 4, 3, nil, 3, nil, nil],
                [nil, 1, 2, nil, nil, 1, 1],
                [1, 2, nil, 2, 3, 1, 1, nil],
                [1, nil, nil, 5, 1, nil, 1],
                [2, nil, 1, nil, 2, 2, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [1, nil, 2, nil, 2, 3, nil, nil],
                [nil, 2, nil, nil, 1, 2, nil],
                [nil, nil, nil, 1, 3, 4, 1, 2],
                [2, 1, 2, 2, 1, 3, 1],
                [1, 3, 1, 4, 3, 1, 1, 3],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1900,
            rows: [
                [nil, 4, 4, 4, 2, 1, 1, nil],
                [nil, 2, nil, 2, 2, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil, nil],
                [nil, 3, 1, 2, 1, 2, nil],
                [nil, 2, 2, 1, nil, nil, 1, nil],
                [nil, 2, 2, 2, 1, nil, nil],
                [nil, nil, nil, 2, nil, 2, nil, nil],
                [nil, 2, nil, 1, 1, nil, nil],
                [nil, 4, 4, nil, 4, 4, 2, nil],
                [nil, nil, 1, 2, 3, 1, nil],
                [nil, 2, 1, 1, 1, 1, 1, nil],
                [nil, 1, 4, 1, 1, 1, nil],
                [nil, 3, 1, 1, 1, 3, 3, nil],
                [nil, 1, 2, 1, 2, 1, nil],
                [nil, 1, 3, 1, 1, 5, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
    ]
}
