// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch113 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2241,
            rows: [
                [nil, 4, 1, nil, nil, 2, 4, nil],
                [4, 4, 4, 4, 2, 2, 2],
                [2, 1, 2, 2, 2, 2, 2, 2],
                [1, 5, 2, 1, 3, 1, 1],
                [1, 3, 1, 3, 3, 1, 2, 3],
                [1, 3, 4, 1, 6, 1, 1],
                [nil, 2, 1, nil, nil, 3, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, 3, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2242,
            rows: [
                [1, 2, nil, 1, 2, nil, 2, 4],
                [5, nil, nil, 2, nil, nil, 3],
                [1, nil, nil, 3, nil, nil, 3, nil],
                [3, nil, nil, 2, nil, nil, 4],
                [3, nil, nil, 4, nil, nil, 1, nil],
                [1, nil, nil, 3, nil, nil, 2],
                [3, nil, nil, 3, nil, nil, 1, nil],
                [5, nil, nil, 3, nil, nil, 6],
                [2, nil, nil, 1, nil, nil, 2, nil],
                [1, nil, nil, 2, nil, nil, 1],
                [1, nil, nil, 2, nil, nil, 1, nil],
                [2, nil, nil, 1, nil, nil, 2],
                [2, nil, nil, 2, nil, nil, 1, nil],
                [2, nil, nil, 2, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2243,
            rows: [
                [4, nil, nil, nil, nil, nil, nil, 1],
                [2, 1, 4, 7, 4, 2, 7],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [2, 2, 4, 1, 1, 3, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [1, 5, 2, 1, 1, 4, 1],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2244,
            rows: [
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, 3, 3, 4, nil, nil],
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, 1, 1, 6, 6, 1, nil],
                [nil, nil, 1, 2, 1, 1, nil, nil],
                [nil, 2, 5, 5, 1, 2, nil],
                [nil, nil, 3, 4, 4, 3, nil, nil],
                [nil, nil, 2, 2, 4, nil, nil],
                [nil, nil, 3, 3, 2, 2, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, nil, 1, 6, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2245,
            rows: [
                [nil, 4, nil, 4, nil, 2, nil, 3],
                [1, 2, nil, 2, 1, nil, 2],
                [1, nil, 3, nil, 1, nil, 1, nil],
                [1, 2, nil, 2, 2, nil, 2],
                [2, nil, 2, nil, 2, nil, 2, nil],
                [5, 5, nil, 5, 1, nil, 1],
                [nil, 2, nil, 3, nil, 1, nil, 3],
                [6, 1, nil, 1, 1, nil, 1],
                [nil, 3, nil, 1, nil, 3, nil, 2],
                [1, 1, nil, 1, 3, nil, 1],
                [1, nil, 1, nil, 1, nil, 2, nil],
                [3, 1, nil, 3, 3, nil, 1],
                [1, nil, 3, nil, 3, nil, 3, nil],
                [1, 1, nil, 3, 1, nil, 4],
                [nil, 1, nil, 2, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2246,
            rows: [
                [nil, 1, 1, 1, nil, nil, 1, 1],
                [nil, 1, 3, 3, nil, nil, 3],
                [nil, 1, 1, 2, nil, nil, 3, 1],
                [nil, 4, 1, 4, nil, 1, 2],
                [nil, 2, 3, 3, nil, nil, 1, 2],
                [nil, 1, 4, 1, nil, 2, 2],
                [nil, 1, 1, 1, nil, 2, 1, 1],
                [nil, 6, 1, 3, nil, 1, 5],
                [nil, 1, 2, 2, nil, 2, 2, 1],
                [nil, 2, 1, 2, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2247,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, 2, 1, 2, 2, 2, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, 1, 6, 3, nil, nil],
                [nil, nil, nil, 5, 4, nil, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, 3, 1, 5, 4, 1, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, 1, 1, 3, 1, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2248,
            rows: [
                [nil, 1, nil, nil, nil, nil, 5, nil],
                [nil, 5, 2, 1, 1, 3, nil],
                [nil, 7, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 2, 3, 3, 4, 4, 2],
                [nil, 2, nil, nil, nil, nil, 1],
                [nil, 4, 1, 2, 2, 6, 3, 4],
                [nil, 2, nil, nil, nil, nil, 1],
                [nil, nil, nil, 2, 1, 2, 1, nil],
                [nil, 4, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, 1, 2, nil],
                [nil, 4, 2, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2249,
            rows: [
                [3, 3, 1, 3, 2, 2, 2, 4],
                [nil, nil, nil, nil, nil, nil, 2],
                [2, 2, 1, 2, 3, 4, 1, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [1, 2, 3, 1, 1, 1, 2, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [3, 3, 1, 2, 2, 2, 2, 3],
                [nil, nil, nil, nil, nil, nil, 1],
                [1, 2, 2, 1, 3, 1, 3, 3],
                [nil, nil, nil, nil, nil, nil, 5],
                [1, 1, 1, 3, 1, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [2, 1, 2, 2, 3, 1, 3, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 4, 3, 1, 1, 4, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2250,
            rows: [
                [4, 1, 3, 1, 1, 3, 4, 4],
                [2, nil, nil, 3, nil, nil, 3],
                [1, 3, 2, 2, 2, 4, 2, 4],
                [4, nil, nil, 4, nil, nil, 1],
                [1, 1, 1, 3, 1, 2, 3, 3],
                [2, nil, nil, 3, nil, nil, 3],
                [nil, 3, nil, nil, 2, nil, nil, 2],
                [3, 2, 2, 1, 3, 2, 2],
                [nil, 3, nil, nil, 2, nil, nil, 2],
                [3, 2, 3, 1, 1, 3, 3],
                [nil, 2, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 3, nil, nil, 2],
                [nil, 2, nil, nil, 3, nil, nil, 2],
                [1, nil, nil, 3, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2251,
            rows: [
                [1, 2, 1, 3, 4, 1, 1, 1],
                [4, 1, 2, 6, 1, 4, 4],
                [5, 1, 1, 1, 1, 5, 2, 1],
                [3, 3, 2, 5, 2, 2, 3],
                [1, 3, 1, 4, 1, 4, 1, 3],
                [1, 6, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2252,
            rows: [
                [4, nil, nil, 2, nil, 4, 4, 4],
                [1, nil, 1, nil, 5, nil, 5],
                [1, nil, nil, 3, nil, nil, nil, 3],
                [5, 2, 2, nil, nil, nil, 2],
                [1, nil, nil, 5, nil, nil, nil, 5],
                [5, 1, 3, nil, nil, nil, 3],
                [nil, nil, nil, 1, nil, 3, 2, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, nil, 2, nil, 1, 1, nil],
                [nil, nil, 1, nil, 3, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 5, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2253,
            rows: [
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, 2, nil, 3, nil, 3, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [2, 4, 1, 2, 4, 1, 1, 2],
                [7, nil, 2, nil, 3, nil, 2],
                [2, 2, 6, 1, 1, 2, 2, 4],
                [3, nil, 3, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2254,
            rows: [
                [2, nil, 2, nil, nil, 3, nil, 3],
                [2, nil, 6, nil, 4, nil, 3],
                [3, nil, nil, 3, 4, nil, nil, 4],
                [3, nil, 2, 2, 1, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 4],
                [4, nil, 2, 1, 2, nil, 5],
                [1, nil, nil, 2, 1, nil, nil, 1],
                [2, nil, 1, nil, 1, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [3, nil, 2, nil, 2, nil, 3],
                [2, nil, 4, nil, nil, 2, nil, 4],
                [2, nil, nil, nil, nil, nil, 2],
                [3, nil, 2, nil, nil, 2, nil, 4],
                [1, nil, nil, nil, nil, nil, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2255,
            rows: [
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [6, 1, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, nil, 1, 5, nil],
                [5, 5, nil, 5, 5, nil, nil, nil],
                [nil, nil, nil, nil, 1, 2, nil],
                [nil, nil, nil, 3, 3, nil, 3, 1],
                [nil, 2, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, 2, 2],
                [nil, 1, 2, nil, nil, nil, nil],
                [1, 1, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 2, nil],
                [1, 3, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2256,
            rows: [
                [nil, 2, nil, nil, nil, nil, 4, nil],
                [1, nil, nil, 2, nil, nil, 2],
                [5, nil, nil, 2, 3, nil, nil, 3],
                [1, nil, nil, 2, nil, nil, 2],
                [2, nil, nil, 1, 1, nil, nil, 2],
                [3, nil, nil, 5, nil, nil, 2],
                [nil, 4, 5, 1, 1, 3, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 1, 4, 1, 1, 1, 1, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 4, 5, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2257,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, 2, 3, nil, nil],
                [nil, nil, 1, 1, 2, 1, nil, nil],
                [nil, 3, 2, 3, 1, 1, nil],
                [nil, nil, 2, 3, 3, 2, nil, nil],
                [nil, 3, 3, 1, 2, 2, nil],
                [nil, 5, nil, 1, 1, nil, 3, nil],
                [3, 3, 4, 1, 2, 1, 2],
                [nil, 2, nil, 2, 1, nil, 2, nil],
                [2, 1, 4, 3, 1, 1, 1],
                [nil, 4, nil, 2, 2, nil, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 2, 2, nil, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2258,
            rows: [
                [nil, nil, 2, 2, 1, nil, nil, nil],
                [nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, 2, 1, 1, 3, 2, nil],
                [nil, 3, 2, 5, nil, nil, 5],
                [nil, nil, 5, 3, 3, 1, 1, nil],
                [nil, 2, 1, 2, nil, nil, 1],
                [nil, 3, nil, nil, 3, 3, 1, nil],
                [nil, 7, 1, 4, 4, 1, nil],
                [nil, 3, nil, nil, 4, 1, 1, nil],
                [nil, 6, 2, 1, 3, 1, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2259,
            rows: [
                [nil, nil, 1, nil, nil, 4, nil, nil],
                [nil, nil, 2, 1, 5, nil, nil],
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, 1, 4, 2, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 4, 4, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, nil, 6, 1, nil, nil, nil],
                [nil, nil, 3, 1, 5, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2260,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 3, 2, 2, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, 3, 1, 1, 6, nil, nil],
                [nil, 1, nil, 4, nil, 4, nil],
                [4, nil, nil, 2, 2, nil, nil, 7],
                [5, 1, nil, 3, nil, 3, 1],
                [2, nil, nil, 2, 1, nil, nil, 1],
                [1, 1, nil, 3, nil, 3, 1],
                [nil, 3, 3, 1, 5, 1, 1, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 4, 3, 1, 3, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
    ]
}
