// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch66 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1301,
            rows: [
                [2, 2, 1, 2, 1, 4, 4, 3],
                [2, 1, 1, 1, 1, 5, 1],
                [1, 2, 1, 4, 4, 4, 4, 1],
                [1, 3, 1, 2, 2, 1, 2],
                [5, 5, 2, 3, 1, 4, 1, 3],
                [3, 1, 2, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1302,
            rows: [
                [2, 1, nil, 4, 1, nil, 2, 4],
                [3, 1, nil, 3, nil, 1, 2],
                [nil, 1, nil, 4, 1, nil, 3, nil],
                [2, 1, 4, 2, 3, 2, 2],
                [nil, 1, nil, 2, 3, nil, 3, nil],
                [3, 1, 2, 1, 1, 2, 2],
                [nil, 1, nil, 1, 1, nil, 2, nil],
                [1, 2, nil, nil, nil, 1, 3],
                [nil, 3, nil, 6, 1, nil, 4, nil],
                [4, 1, nil, nil, nil, 1, 1],
                [2, 2, 3, nil, nil, 2, 1, 1],
                [2, 1, nil, nil, nil, 2, 1],
                [3, 1, 2, nil, nil, 2, 1, 1],
                [2, 2, nil, nil, nil, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1303,
            rows: [
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, nil, 1, 3, 3, nil, nil],
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, nil, 3, 2, 2, nil, nil],
                [nil, nil, 1, 3, 3, 2, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 2, 3, 1, 2, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, 6, 1, 2, 3, nil, nil],
                [nil, nil, 3, 1, 3, nil, nil],
                [nil, nil, 1, 2, 4, 1, nil, nil],
                [nil, nil, 5, 1, 1, nil, nil],
                [nil, nil, 3, 2, 1, 1, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1304,
            rows: [
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, 1, 1, 4, 4, nil, nil, 1],
                [1, 2, 3, 2, 3, nil, 1],
                [nil, 2, 1, 2, 2, nil, nil, 2],
                [1, 2, 3, 1, 3, nil, 1],
                [1, 4, 4, 1, 3, 1, 1, nil],
                [2, 2, 3, 2, 3, nil, 1],
                [1, 3, 1, 1, 3, 3, 3, nil],
                [2, 1, 3, 1, 2, nil, 5],
                [nil, 3, 3, 3, 6, nil, nil, 2],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 2, 2, 1, 1, nil, nil, 1],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1305,
            rows: [
                [nil, nil, 3, nil, nil, 3, nil, nil],
                [1, 1, 4, 3, 2, 2, 2],
                [1, 1, 4, 1, 3, 1, 3, 4],
                [1, 2, nil, 1, nil, 1, 1],
                [3, 1, 2, 1, 2, 1, 1, 1],
                [4, 3, nil, 1, nil, 2, 2],
                [3, 3, nil, 4, 1, nil, 2, 2],
                [2, nil, nil, 1, nil, nil, 1],
                [3, 1, nil, 2, 2, nil, 2, 3],
                [2, nil, nil, 2, nil, nil, 3],
                [1, 1, 1, nil, nil, 3, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 6, 3, nil, nil, 2, 4, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1306,
            rows: [
                [5, nil, nil, nil, 5, 2, nil, nil],
                [1, nil, nil, 4, 4, 2, nil],
                [1, nil, nil, 2, 3, 1, 4, nil],
                [1, nil, 1, 2, 1, 1, 3],
                [2, nil, nil, 1, 2, 3, 2, nil],
                [3, nil, 3, 2, 1, 1, 2],
                [1, nil, nil, 2, 1, 1, 2, nil],
                [2, nil, nil, 2, 1, 2, nil],
                [4, nil, nil, 1, 2, 1, 2, nil],
                [2, nil, nil, 3, 3, 1, nil],
                [1, nil, nil, nil, 1, 2, nil, nil],
                [nil, nil, nil, 2, 2, 2, nil],
                [1, nil, nil, nil, 4, 1, nil, nil],
                [nil, nil, nil, 3, 6, 5, nil],
                [nil, nil, nil, 1, 3, 1, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1307,
            rows: [
                [1, 4, 2, 2, 5, 3, 1, 4],
                [1, 2, 3, 1, 1, 3, 2],
                [1, 2, 3, 1, 1, 1, 4, 1],
                [2, 2, 4, 2, 1, 2, 1],
                [4, 1, 2, 1, 1, 3, 1, 3],
                [1, 3, 1, 3, 3, 6, 1],
                [1, 1, 4, 2, 4, 3, 1, 4],
                [1, 2, 2, 2, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1308,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil],
                [nil, nil, nil, nil, 2, 4, nil, nil],
                [nil, nil, nil, nil, 4, 4, nil],
                [nil, nil, nil, nil, nil, 3, 2, nil],
                [nil, nil, nil, nil, nil, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 3, nil, nil, 2, 3, nil],
                [1, 1, nil, nil, 1, 3, nil],
                [nil, 1, 2, nil, nil, 1, 2, nil],
                [1, 4, nil, nil, 4, 2, nil],
                [nil, 5, 2, nil, nil, 3, 1, nil],
                [1, 1, nil, nil, 1, 2, nil],
                [nil, 2, 3, nil, nil, 3, 2, nil],
                [2, 2, nil, nil, 2, 2, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1309,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [1, 1, 1, 3, nil, nil, nil],
                [3, nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, nil, 4, 4, 1, 3],
                [4, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 2, 2, 1],
                [1, nil, nil, nil, 4, nil, nil, 4],
                [4, 1, 3, 1, nil, nil, nil],
                [1, nil, nil, nil, 3, nil, nil, 3],
                [1, 1, 2, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, 1],
                [nil, nil, nil, 3, 2, 1, 3],
                [nil, nil, nil, 1, nil, nil, nil, 1],
                [nil, nil, nil, 5, 3, 3, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1310,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 4, 4, 3, 3, nil, nil],
                [nil, nil, 5, 2, 5, nil, nil],
                [nil, nil, 5, 5, 1, 3, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 3, 2, 2, 1, nil, nil],
                [nil, nil, 3, 2, 3, nil, nil],
                [nil, nil, 1, 2, 1, 7, nil, nil],
                [nil, nil, 1, 3, 2, nil, nil],
                [nil, nil, 2, 1, 1, 4, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1311,
            rows: [
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 2, 1, 4, nil, nil],
                [nil, nil, 1, 1, 3, 3, nil, nil],
                [nil, 3, 1, 1, 2, 2, nil],
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, 2, 1, 2, 2, 1, nil],
                [nil, 5, 5, 5, 3, 1, 4, nil],
                [1, 4, 1, 6, 1, 1, 2],
                [nil, 1, 2, 1, 3, 1, 1, nil],
                [1, 4, 4, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1312,
            rows: [
                [1, 1, 5, 1, 3, 2, 1, 1],
                [nil, nil, nil, nil, nil, nil, 4],
                [1, 1, 1, 4, 1, 3, 1, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [4, 1, 1, 1, 4, 3, 4, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [4, 2, 1, 3, 3, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, 1],
                [1, 3, 1, 2, 2, 3, 1, 1],
                [nil, nil, nil, nil, nil, nil, 3],
                [1, 3, 1, 1, 1, 3, 1, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [1, 1, 3, 5, 3, 2, 2, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, 3, 3, 3, 1, 1, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1313,
            rows: [
                [nil, nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, 2, 2, 4, nil, nil],
                [nil, nil, 4, 4, 4, 2, nil, nil],
                [nil, 1, 2, 1, 4, 4, nil],
                [nil, nil, 1, 2, 1, 3, nil, nil],
                [nil, 1, 1, 3, 2, 1, nil],
                [nil, 2, 1, 1, 3, 6, 1, nil],
                [2, 3, 3, 2, 2, 2, 5],
                [nil, 1, 1, 1, 1, 1, 2, nil],
                [1, 2, 3, 1, 3, 1, 3],
                [1, 1, 1, 3, 3, 2, 4, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 3, 2, 2, 1, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1314,
            rows: [
                [1, 1, 5, 5, 3, 5, 2, 2],
                [2, 2, 2, 2, 1, 5, 1],
                [3, 5, 4, 1, 3, 3, 2, 2],
                [1, 1, 3, 4, 1, 4, 1],
                [4, 1, 1, 3, 4, 3, 1, 1],
                [3, 1, 6, 3, 1, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1315,
            rows: [
                [nil, 5, 5, 1, 2, 3, 1, nil],
                [nil, 3, 1, 5, 1, 2, nil],
                [nil, nil, 4, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 6, 4, 2, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 2, nil, nil, nil, nil, nil, nil],
                [2, 2, nil, nil, nil, nil, nil],
                [nil, 2, 2, nil, nil, nil, nil, nil],
                [nil, 3, 3, nil, nil, nil, nil],
                [nil, nil, 3, 4, nil, nil, nil, nil],
                [nil, nil, 5, 5, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1316,
            rows: [
                [1, 2, nil, 1, 2, nil, 3, 3],
                [3, 1, nil, 2, nil, 1, 3],
                [nil, 1, nil, 2, 1, nil, 1, nil],
                [1, 4, 4, 2, 2, 1, 2],
                [nil, 1, nil, 1, 1, nil, 2, nil],
                [4, 4, 2, 2, 1, 2, 1],
                [nil, 2, nil, 2, 2, nil, 1, nil],
                [1, 3, nil, nil, nil, 2, 4],
                [nil, 1, nil, 2, 2, nil, 1, nil],
                [3, 1, nil, nil, nil, 2, 3],
                [1, 5, 1, nil, nil, 3, 1, 4],
                [1, 5, nil, nil, nil, 1, 3],
                [1, 1, 1, nil, nil, 1, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1317,
            rows: [
                [nil, nil, 2, 1, 1, 4, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 1, 4, 4, 4, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 1, 2, 1, 1, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 4, 1, 2, 1, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 1, 2, 3, 2, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 1, 5, 2, 2, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 1, 2, 1, 2, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 1, 1, 2, 2, nil, nil],
                [nil, nil, 5, 2, 2, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1318,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 5, nil, nil, nil, nil],
                [nil, 2, 1, 1, 4, nil, nil, 1],
                [1, 2, 2, 1, 3, nil, 3],
                [nil, 1, 1, 3, 1, nil, nil, 2],
                [3, 3, 3, 4, 1, nil, 1],
                [1, 2, 2, 1, 1, 2, 4, nil],
                [4, 1, 4, 4, 4, nil, 1],
                [1, 3, 3, 3, 1, 3, 1, nil],
                [1, 3, 1, 3, 2, nil, 7],
                [nil, 1, 3, 2, 1, nil, nil, 1],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 2, 1, 2, 1, nil, nil, 1],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1319,
            rows: [
                [nil, nil, 3, nil, nil, 2, nil, nil],
                [1, 4, 4, 1, 2, 1, 2],
                [1, 2, 3, 1, 5, 5, 5, 1],
                [3, 3, nil, 1, nil, 1, 4],
                [1, 4, 1, 4, 4, 1, 4, 4],
                [4, 2, nil, 2, nil, 3, 2],
                [1, 2, nil, 1, 1, nil, 1, 2],
                [1, nil, nil, 1, nil, nil, 1],
                [1, 2, nil, 2, 2, nil, 1, 2],
                [2, nil, nil, 2, nil, nil, 3],
                [2, 2, 4, nil, nil, 1, 1, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1320,
            rows: [
                [3, nil, nil, nil, 2, 2, nil, nil],
                [2, nil, nil, 1, 2, 1, nil],
                [4, nil, nil, 2, 1, 2, 4, nil],
                [3, nil, 4, 5, 2, 2, 1],
                [3, nil, nil, 6, 3, 3, 1, nil],
                [2, nil, 1, 4, 3, 3, 1],
                [3, nil, nil, 1, 1, 2, 1, nil],
                [4, nil, nil, 1, 2, 1, nil],
                [1, nil, nil, 1, 1, 5, 1, nil],
                [3, nil, nil, 2, 2, 2, nil],
                [1, nil, nil, nil, 3, 3, nil, nil],
                [nil, nil, nil, 4, 4, 4, nil],
                [1, nil, nil, nil, 2, 2, nil, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, nil, nil, 1, 5, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
    ]
}
