// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch132 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2621,
            rows: [
                [1, 4, 2, 1, 3, 1, 2, 3],
                [2, nil, nil, 1, nil, nil, 2],
                [1, nil, nil, 4, 1, nil, nil, 2],
                [nil, nil, nil, 5, nil, nil, nil],
                [3, nil, nil, 2, 1, nil, nil, 2],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 6, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2622,
            rows: [
                [1, 2, nil, nil, nil, nil, 4, 2],
                [3, 1, nil, nil, nil, 3, 1],
                [5, 1, nil, nil, nil, nil, 4, 1],
                [2, nil, nil, nil, nil, nil, 1],
                [3, 4, nil, nil, nil, nil, 5, 2],
                [1, nil, nil, nil, nil, nil, 5],
                [3, 4, nil, nil, nil, nil, 2, 1],
                [1, nil, nil, nil, nil, nil, 2],
                [2, 5, nil, nil, nil, nil, 1, 6],
                [1, nil, nil, nil, nil, nil, 5],
                [1, 2, nil, nil, nil, nil, 2, 3],
                [1, 3, nil, nil, nil, 1, 2],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2623,
            rows: [
                [3, 2, 5, 1, 3, 3, 4, 2],
                [1, nil, nil, 1, nil, nil, 7],
                [4, nil, nil, 3, 2, nil, nil, 6],
                [nil, nil, nil, 2, nil, nil, nil],
                [3, nil, nil, 2, 1, nil, nil, 3],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2624,
            rows: [
                [5, 3, nil, nil, nil, nil, 2, 3],
                [1, 4, nil, nil, nil, 3, 1],
                [1, 4, nil, nil, nil, nil, 1, 3],
                [1, nil, nil, nil, nil, nil, 3],
                [4, 2, nil, nil, nil, nil, 4, 1],
                [3, nil, nil, nil, nil, nil, 2],
                [1, 5, nil, nil, nil, nil, 1, 6],
                [1, nil, nil, nil, nil, nil, 2],
                [1, 2, nil, nil, nil, nil, 4, 4],
                [1, nil, nil, nil, nil, nil, 5],
                [2, 3, nil, nil, nil, nil, 2, 1],
                [2, 3, nil, nil, nil, 2, 2],
                [1, 2, nil, nil, nil, nil, 2, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2625,
            rows: [
                [4, 2, 3, 1, 3, 2, 3, 4],
                [4, nil, nil, 2, nil, nil, 4],
                [1, nil, nil, 2, 1, nil, nil, 4],
                [nil, nil, nil, 1, nil, nil, nil],
                [3, nil, nil, 1, 3, nil, nil, 5],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 5, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2626,
            rows: [
                [3, nil, 5, nil, 3, nil, 2, nil],
                [nil, 3, nil, 1, nil, 7, nil],
                [nil, nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [5, nil, nil, nil, nil, nil, nil, 4],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, 6],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2627,
            rows: [
                [2, 5, nil, nil, nil, nil, 1, 7],
                [5, 1, nil, nil, nil, 2, 1],
                [2, 1, nil, nil, nil, nil, 6, 1],
                [5, nil, nil, nil, nil, nil, 1],
                [2, 2, nil, nil, nil, nil, 1, 3],
                [1, nil, nil, nil, nil, nil, 2],
                [1, 5, nil, nil, nil, nil, 4, 3],
                [1, nil, nil, nil, nil, nil, 4],
                [1, 5, nil, nil, nil, nil, 1, 2],
                [1, nil, nil, nil, nil, nil, 2],
                [1, 1, nil, nil, nil, nil, 2, 2],
                [1, 3, nil, nil, nil, 1, 2],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2628,
            rows: [
                [nil, nil, 2, nil, nil, 6, nil, nil],
                [nil, 4, 3, nil, 2, 1, nil],
                [nil, 5, 3, 2, 3, 2, 2, nil],
                [nil, 3, 1, nil, 2, 5, nil],
                [nil, 3, 2, 1, 2, 3, 2, nil],
                [nil, 1, 4, nil, 1, 2, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2629,
            rows: [
                [nil, 5, nil, nil, nil, nil, 2, nil],
                [3, nil, nil, 1, nil, nil, 2],
                [3, nil, nil, 2, 4, nil, nil, 2],
                [1, nil, nil, 1, nil, nil, 2],
                [3, nil, nil, 2, 3, nil, nil, 1],
                [2, nil, nil, 1, nil, nil, 2],
                [nil, 3, 3, 4, 6, 3, 2, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 5, 1, 3, 1, 1, 1, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2630,
            rows: [
                [nil, nil, 4, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, 1, 5, 3, nil],
                [1, nil, nil, nil, nil, 3, nil],
                [nil, 6, nil, nil, 1, 3, 3, nil],
                [4, nil, nil, nil, nil, 1, nil],
                [7, 4, 1, 2, nil, 1, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [1, 6, 1, 4, nil, 1, nil, nil],
                [nil, nil, 6, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2631,
            rows: [
                [nil, 1, nil, 4, nil, 3, nil, 1],
                [4, nil, 6, nil, 1, nil, 2],
                [nil, 3, nil, 2, nil, 3, nil, 1],
                [5, nil, 1, nil, 2, nil, 3],
                [nil, 1, nil, 3, nil, 1, nil, 3],
                [1, nil, 2, nil, 6, nil, 3],
                [nil, 2, nil, 3, nil, 1, nil, 3],
                [1, nil, 3, nil, 2, nil, 1],
                [nil, 3, nil, 1, nil, 3, nil, 2],
                [3, nil, 1, nil, 3, nil, 4],
                [nil, 1, nil, 3, nil, 1, nil, 1],
                [2, nil, 3, nil, 6, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2632,
            rows: [
                [2, 1, 2, 5, 3, 1, 2, 7],
                [5, nil, nil, 2, nil, nil, 3],
                [1, nil, nil, 4, 2, nil, nil, 1],
                [nil, nil, nil, 2, nil, nil, nil],
                [1, nil, nil, 4, 3, nil, nil, 4],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2633,
            rows: [
                [nil, 2, 4, nil, nil, 1, 4, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, 3, nil, nil, nil, 4, nil, nil],
                [nil, 2, nil, nil, nil, 5, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 6, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 5, nil, nil, nil, 1, nil, nil],
                [nil, 4, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2634,
            rows: [
                [nil, 5, nil, nil, nil, nil, 2, nil],
                [3, 1, nil, nil, nil, 3, 3],
                [nil, 4, nil, nil, nil, nil, 4, nil],
                [2, 4, nil, nil, nil, 1, 4],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [4, 2, nil, nil, nil, 1, 2],
                [nil, 1, nil, nil, nil, nil, 5, nil],
                [1, 2, nil, nil, nil, 1, 2],
                [nil, 4, nil, nil, nil, nil, 1, nil],
                [5, 1, nil, nil, nil, 1, 1],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2635,
            rows: [
                [4, nil, nil, 1, nil, 5, 6, 1],
                [3, nil, 1, nil, 4, nil, 4],
                [2, nil, nil, 2, nil, nil, nil, 2],
                [1, 4, 3, nil, nil, nil, 2],
                [2, nil, nil, 1, nil, nil, nil, 1],
                [5, 3, 1, nil, nil, nil, 3],
                [nil, nil, nil, 5, nil, 3, 1, nil],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, nil, 4, nil, 5, 2, nil],
                [nil, nil, 5, nil, 1, nil, nil],
                [nil, nil, nil, 3, nil, 1, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 5, nil, 3, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2636,
            rows: [
                [1, nil, 6, nil, 4, nil, 2, nil],
                [nil, 4, nil, 5, nil, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 7, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 4, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, nil, 5, nil],
                [2, nil, nil, nil, nil, nil, nil, 6],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, 3],
                [nil, 1, nil, nil, nil, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2637,
            rows: [
                [2, 1, nil, nil, nil, nil, 3, 1],
                [5, 5, nil, nil, nil, 3, 1],
                [2, 5, nil, nil, nil, nil, 2, 1],
                [5, nil, nil, nil, nil, nil, 1],
                [3, 4, nil, nil, nil, nil, 2, 1],
                [1, nil, nil, nil, nil, nil, 3],
                [3, 1, nil, nil, nil, nil, 5, 1],
                [4, nil, nil, nil, nil, nil, 1],
                [1, 3, nil, nil, nil, nil, 3, 1],
                [2, nil, nil, nil, nil, nil, 1],
                [7, 2, nil, nil, nil, nil, 4, 2],
                [1, 2, nil, nil, nil, 2, 5],
                [2, 1, nil, nil, nil, nil, 2, 1],
                [2, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2638,
            rows: [
                [nil, nil, 1, nil, nil, 5, nil, nil],
                [nil, 2, 1, nil, 2, 3, nil],
                [nil, 5, 4, 2, 1, 1, 1, nil],
                [nil, 2, 3, nil, 6, 1, nil],
                [nil, 2, 3, 2, 4, 4, 4, nil],
                [nil, 1, 3, nil, 1, 2, nil],
                [nil, nil, 3, nil, nil, 6, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 5, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2639,
            rows: [
                [nil, 1, nil, nil, nil, nil, 7, nil],
                [2, nil, nil, 3, nil, nil, 4],
                [1, nil, nil, 2, 1, nil, nil, 2],
                [2, nil, nil, 2, nil, nil, 1],
                [2, nil, nil, 2, 1, nil, nil, 3],
                [1, nil, nil, 7, nil, nil, 2],
                [nil, 1, 2, 1, 2, 1, 5, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2640,
            rows: [
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, 4, nil, nil, 1, nil, nil],
                [nil, 5, nil, nil, 5, 4, 3, nil],
                [1, nil, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, 2, 1, 4, nil],
                [1, nil, nil, nil, nil, 3, nil],
                [1, 2, 4, 6, nil, 2, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [2, 6, 1, 3, nil, 1, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
    ]
}
