// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch120 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2381,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 3],
                [3, nil, 2, 1, 2, nil, nil],
                [nil, 1, nil, nil, 3, 1, 2, nil],
                [nil, nil, 1, nil, 2, 4, nil],
                [nil, 4, nil, nil, nil, 4, nil, nil],
                [nil, 5, 5, nil, nil, nil, 2],
                [3, 1, 1, nil, nil, 2, nil, 2],
                [1, nil, 2, nil, nil, 2, 2],
                [1, 3, 2, nil, nil, 2, 1, 1],
                [3, 3, 1, nil, 1, 3, 1],
                [2, 1, 1, 6, 6, 1, 1, 1],
                [4, 1, 3, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2382,
            rows: [
                [1, 4, nil, nil, nil, nil, nil, nil],
                [2, 1, nil, nil, nil, nil, nil],
                [2, 2, 2, nil, nil, nil, nil, nil],
                [1, 1, 4, nil, nil, nil, nil],
                [4, 4, 1, nil, nil, nil, nil, nil],
                [1, 2, 1, nil, nil, nil, nil],
                [4, 4, 3, 1, nil, nil, nil, nil],
                [5, 1, 2, 2, nil, nil, nil],
                [3, 5, 1, 1, nil, nil, nil, nil],
                [2, 3, 1, 3, nil, nil, nil],
                [3, 1, 1, 6, 6, nil, nil, nil],
                [1, 5, 2, 3, 2, nil, nil],
                [3, 1, 2, 1, 1, nil, nil, nil],
                [1, 1, 3, 4, 2, nil, nil],
                [1, 2, 1, 3, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2383,
            rows: [
                [nil, nil, 1, nil, nil, 4, 1, nil],
                [4, nil, 4, nil, nil, nil, 1],
                [1, 1, nil, 3, 1, nil, 1, 5],
                [1, 1, 1, 3, 3, 2, 1],
                [1, 2, nil, 1, 2, nil, 1, 2],
                [4, 1, 2, 2, 1, 4, 1],
                [2, 2, 1, 1, 1, 6, 1, 6],
                [1, nil, 1, 4, 1, nil, 4],
                [1, 2, 1, 1, 1, 1, 1, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2384,
            rows: [
                [nil, 3, 1, nil, nil, 2, 2, nil],
                [1, nil, 1, nil, 1, nil, 2],
                [1, 1, nil, 1, 2, nil, 1, 4],
                [4, 1, 2, 1, 1, 2, 2],
                [1, 1, nil, 2, 2, nil, 2, 3],
                [2, 1, 1, 1, 1, 1, 3],
                [3, 1, 2, 1, 2, 1, 3, 1],
                [1, nil, 2, 1, 5, nil, 2],
                [2, 2, 1, 6, 1, 3, 3, 1],
                [2, nil, 1, 1, 2, nil, 2],
                [nil, 1, 1, 2, 2, 3, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2385,
            rows: [
                [1, 3, nil, 5, nil, nil, 1, nil],
                [4, nil, 4, 1, 3, nil, nil],
                [2, nil, nil, 3, 1, 2, nil, 1],
                [nil, 3, 2, 1, 1, 5, nil],
                [nil, nil, 3, nil, 1, 6, 3, nil],
                [1, 1, 1, 2, 2, 1, 1],
                [3, nil, 3, 3, 3, 2, 1, nil],
                [1, 2, nil, 1, 2, nil, nil],
                [1, nil, nil, 5, 2, 1, nil, 3],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, 1, 1, nil, 1, 2, 3, 1],
                [nil, nil, nil, nil, nil, 1, nil],
                [1, nil, nil, 2, nil, 2, nil, 1],
                [nil, nil, nil, 3, 1, nil, 1],
                [nil, nil, 2, nil, nil, nil, 3, nil],
                [nil, nil, 3, 2, 2, 2, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2386,
            rows: [
                [2, 3, nil, nil, nil, nil, 4, 4],
                [1, nil, nil, nil, nil, nil, 1],
                [2, nil, nil, nil, nil, nil, nil, 5],
                [1, nil, 2, 3, 1, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [3, nil, 1, 3, 3, nil, 3],
                [1, 4, 1, 3, 3, 1, 3, 4],
                [4, 4, 2, nil, 2, 1, 1],
                [2, 2, 2, 2, 6, 1, 5, 1],
                [4, 4, 1, nil, 1, 1, 5],
                [nil, 4, 1, nil, nil, 2, 1, nil],
                [nil, nil, 1, 1, 4, nil, nil],
                [nil, 1, 4, nil, nil, 1, 1, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2387,
            rows: [
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, 4, 4, 4, 1, 3, nil],
                [nil, 2, nil, 2, nil, nil, 1, nil],
                [nil, 2, 1, 4, 1, nil, nil],
                [nil, 6, 1, nil, 1, 4, 1, nil],
                [nil, 2, 2, 2, nil, 2, nil],
                [nil, 1, 1, 1, 1, 4, nil, nil],
                [nil, 1, nil, 2, 2, 1, nil],
                [nil, nil, 3, 1, 2, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 3, 1, 2, 3, 5, 3, 1],
                [2, nil, nil, nil, nil, nil, 1],
                [5, nil, 1, 2, 1, 5, nil, 4],
                [1, nil, 1, nil, nil, 3, 1],
                [1, nil, 1, nil, 1, 1, nil, 1],
                [1, nil, 1, nil, nil, 1, 1],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2388,
            rows: [
                [nil, nil, nil, 1, 2, 3, 1, nil],
                [4, 1, 1, nil, nil, nil, 1],
                [4, nil, nil, nil, nil, nil, nil, 1],
                [3, nil, nil, nil, nil, nil, 3],
                [5, nil, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, 3],
                [2, nil, nil, nil, 1, 1, 3, 3],
                [3, nil, nil, 3, 4, 1, 2],
                [2, nil, nil, nil, 1, 2, 1, 3],
                [5, nil, nil, 3, 1, 2, 2],
                [2, nil, nil, nil, 2, 2, 1, 7],
                [1, 3, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 2, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2389,
            rows: [
                [nil, 1, 2, nil, 1, 4, 6, nil],
                [1, nil, nil, nil, nil, nil, 3],
                [nil, 2, 3, 1, nil, 2, 2, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 1, 1, 3, nil, 2, 1, nil],
                [3, nil, nil, nil, nil, nil, 1],
                [nil, 4, 5, nil, 3, 3, 3, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 1, 1, nil, 1, 4, 4, nil],
                [4, nil, nil, nil, nil, nil, 2],
                [nil, 2, 2, 1, nil, 3, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 6, 1, 3, nil, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2390,
            rows: [
                [nil, nil, 1, 5, 5, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 3, nil, 1, 5, nil, 2],
                [1, 2, nil, 3, 1, nil, 2],
                [nil, 2, 1, 4, 1, 1, 4, nil],
                [4, 3, 1, 5, 5, 3, nil],
                [nil, nil, 3, 3, nil, 4, 4, nil],
                [nil, 1, 2, nil, 2, 4, nil],
                [nil, nil, nil, 4, 1, 6, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, 1, 2, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2391,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 5, 3, nil, nil],
                [nil, nil, nil, nil, 4, 2, nil, nil],
                [nil, nil, nil, nil, 2, 3, nil],
                [nil, nil, nil, nil, nil, 5, 4, nil],
                [nil, nil, nil, nil, nil, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 3, nil, nil, 1, 6, nil],
                [1, 3, nil, nil, 1, 2, nil],
                [nil, 1, 2, nil, nil, 1, 3, nil],
                [3, 1, nil, nil, 3, 1, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, 4, nil, nil, 1, 4, nil],
                [nil, 2, 1, nil, nil, 1, 5, nil],
                [4, 3, nil, nil, 1, 4, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2392,
            rows: [
                [nil, 2, nil, nil, 1, nil, nil, nil],
                [nil, nil, 3, 1, nil, 2, nil],
                [nil, 3, 1, 2, 2, nil, 2, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 2, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil],
                [nil, 2, 4, 3, 3, 1, 4, nil],
                [nil, 1, 2, 1, 1, 1, nil],
                [nil, 2, 1, 6, 1, 1, 1, nil],
                [nil, 3, 1, 1, 4, 1, nil],
                [nil, 4, 1, 1, 3, 3, 3, nil],
                [nil, 1, 2, 1, 3, 1, nil],
                [nil, 4, 4, 1, 2, 4, 2, nil],
                [nil, 1, 3, 1, 1, 2, nil],
                [nil, 1, nil, 2, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2393,
            rows: [
                [nil, nil, 4, nil, nil, 1, nil, nil],
                [1, 2, 1, 1, 1, 2, 1],
                [4, 4, 4, 3, 1, 1, 2, 1],
                [5, 5, nil, 2, nil, 1, 2],
                [2, 1, 1, 1, 3, 2, 1, 3],
                [3, 2, nil, 3, nil, 2, 3],
                [4, 3, nil, 2, 2, nil, 3, 3],
                [1, nil, nil, 2, nil, nil, 1],
                [1, 1, nil, 5, 2, nil, 1, 1],
                [2, nil, nil, 1, nil, nil, 1],
                [1, 1, 6, nil, nil, 2, 3, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 3, 2, nil, nil, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2394,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 3, 1, 1, nil, nil, 2],
                [2, 1, 1, 3, 4, nil, 4],
                [nil, 1, 2, 1, 6, nil, nil, 5],
                [1, 1, 1, 2, 3, nil, 3],
                [3, 3, 3, 2, 2, 1, 3, nil],
                [1, 3, 3, 1, 2, nil, 3],
                [3, 1, 1, 1, 3, 2, 3, nil],
                [2, 3, 3, 2, 2, nil, 1],
                [nil, 4, 4, 4, 1, nil, nil, 1],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, 2, 2, 4, 2, nil, nil, 2],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2395,
            rows: [
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, 6, 3, 3, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [1, 1, 2, 2, 2, 1, 1],
                [nil, 1, 2, 1, 2, 2, nil, nil],
                [1, 2, 2, 6, 4, 4, 4],
                [2, 2, 2, 2, 1, 1, 5, 3],
                [1, 1, 1, 1, 2, 1, 2],
                [1, 2, 3, 2, 5, 1, 2, 1],
                [2, 2, 6, 2, 2, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2396,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, 1, 2, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 3, 2, 3, 1, nil, nil],
                [nil, 3, 3, 1, 2, 3, nil],
                [nil, 3, 1, 1, 1, 1, 1, nil],
                [1, 1, 2, 1, 6, 4, 2],
                [nil, 4, 2, 3, 3, 3, 1, nil],
                [2, 1, 4, 4, 5, 2, 5],
                [2, 2, 5, 2, 2, 2, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, 1, 1, 3, 3, 2, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2397,
            rows: [
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, 5, 5, 1, nil, nil],
                [nil, 2, 3, 1, 1, 2, 3, nil],
                [2, 1, 2, 2, 4, 4, 4],
                [nil, 4, 2, 3, 3, 3, 1, nil],
                [1, 3, 3, 1, 2, 1, 7],
                [nil, 2, 4, 1, 2, 2, 4, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 2, 2, 1, 2, 2, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, 1, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2398,
            rows: [
                [nil, nil, 2, nil, nil, nil, 2, nil],
                [4, nil, 2, 1, 3, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, 4],
                [2, 4, 1, 5, 4, 4, 4],
                [4, 4, 1, nil, nil, 4, nil, 1],
                [1, 2, 1, 1, 5, 1, 6],
                [nil, nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 3, 1, 1],
                [1, 1, nil, nil, nil, 1, 2, 2],
                [nil, 1, 1, 4, 4, 1, 3],
                [1, 3, nil, nil, nil, 1, nil, nil],
                [5, 1, nil, nil, 1, 3, 3],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2399,
            rows: [
                [2, nil, nil, 1, 2, nil, nil, 1],
                [2, 6, 1, 3, 3, 3, 3],
                [nil, 4, 3, nil, nil, 4, 1, nil],
                [2, nil, 1, 1, 3, nil, 1],
                [nil, 1, 4, nil, nil, 1, 5, nil],
                [2, nil, 1, 1, 1, nil, 4],
                [nil, 4, 4, nil, nil, 4, 4, nil],
                [nil, nil, 5, 3, 1, nil, nil],
                [nil, 2, 4, nil, nil, 4, 1, nil],
                [nil, nil, 3, 2, 2, nil, nil],
                [nil, 1, 1, 4, 1, 1, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2400,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, nil, 2, nil, 1],
                [nil, 2, 1, 3, 1, 4, nil, nil],
                [1, 3, 1, nil, 2, nil, nil],
                [nil, 1, 5, 1, nil, 2, nil, nil],
                [3, 3, 1, nil, 5, nil, 1],
                [2, nil, nil, nil, nil, 2, 1, 1],
                [nil, 2, nil, nil, 1, 6, nil],
                [nil, 1, 1, nil, nil, 4, 1, 2],
                [1, 2, 1, nil, 2, 1, 5],
                [2, 1, 1, 4, 1, 3, 1, 6],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
    ]
}
