// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch10 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 181,
            rows: [
                [nil, 5, 5, 5, 5, 5, 1, nil],
                [nil, 1, 1, 1, 1, 6, nil],
                [nil, nil, 6, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 4, 5, 2, 2, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 1, 2, 2, nil, 2],
                [1, nil, 1, 1, 1, nil, 3],
                [3, nil, 3, 3, 3, 2, nil, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 2, 2, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 3, 3, 2, nil, nil],
                [nil, nil, 2, 2, 3, nil, nil],
                [nil, nil, 3, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 182,
            rows: [
                [nil, 2, 2, nil, nil, 2, 5, nil],
                [5, 5, 6, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 3],
                [4, 4, 4, 3, 3, 4, 3, 3],
                [3, 3, 3, 2, 2, 6, 2],
                [nil, 2, 7, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 183,
            rows: [
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, nil, 2, 2, nil, 2],
                [2, 2, nil, 2, 2, nil, 2],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [2, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, nil, 3, 3, nil],
                [nil, 3, 3, nil, 3, 3, nil],
                [nil, nil, nil, 3, 3, 5, nil, nil],
                [nil, nil, 5, 4, 7, nil, nil],
                [nil, nil, 4, 4, 4, 4, nil, nil],
                [nil, 4, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 6, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 184,
            rows: [
                [6, 2, nil, nil, nil, nil, 2, 2],
                [2, 2, nil, nil, nil, 2, 1],
                [1, 5, nil, nil, nil, nil, 5, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 2],
                [4, nil, nil, nil, nil, nil, 4],
                [4, 4, nil, nil, nil, nil, 4, 4],
                [4, 4, 2, 2, 2, 2, 2],
                [2, 6, nil, nil, nil, nil, 6, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 3, 1, 1, 1, 3, 1, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 185,
            rows: [
                [6, nil, nil, 6, 6, nil, nil, 1],
                [1, nil, 2, nil, 2, nil, 2],
                [nil, 2, 2, nil, nil, 2, 3, nil],
                [3, 3, nil, nil, nil, 3, 3],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [2, nil, 1, 1, 1, 1, nil, 1],
                [1, 1, nil, nil, nil, 2, 2],
                [2, nil, 2, 2, 2, 2, nil, 2],
                [2, 2, nil, nil, nil, 2, 5],
                [nil, 5, 4, nil, nil, 4, 2, nil],
                [2, nil, 2, nil, 2, nil, 2],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [2, nil, 2, nil, 2, nil, 2],
                [2, nil, nil, 4, 2, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 186,
            rows: [
                [nil, nil, 2, 2, 2, nil, nil, nil],
                [nil, 2, 2, 2, 1, nil, nil],
                [nil, 4, 4, 1, 1, 3, nil, nil],
                [3, 3, 3, 3, 5, 5, nil],
                [nil, 2, 2, 2, 2, 1, nil, nil],
                [1, 3, 3, 3, 3, 3, nil],
                [nil, nil, 3, nil, 2, nil, nil, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, nil, 1, 1, 7],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 4, 4, nil, 5, 5, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 187,
            rows: [
                [1, nil, nil, nil, 1, 1, nil, nil],
                [1, nil, nil, 1, 1, 1, nil],
                [1, nil, nil, 1, 1, 1, 1, nil],
                [1, nil, 1, 1, 1, 1, 1],
                [1, nil, nil, 1, 1, 1, 2, nil],
                [2, nil, 2, 2, 1, 1, 1],
                [1, nil, nil, 1, 1, 1, 1, nil],
                [3, nil, nil, 2, 3, 3, nil],
                [2, nil, nil, 3, 3, 3, 3, nil],
                [3, nil, nil, 5, 4, 4, nil],
                [4, nil, nil, nil, 5, 5, nil, nil],
                [nil, nil, nil, 6, 2, 2, nil],
                [2, nil, nil, nil, 6, 6, nil, nil],
                [nil, nil, nil, 2, 2, 2, nil],
                [nil, nil, nil, 2, 3, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 188,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 3, 3, 3, nil, nil],
                [nil, 3, 1, nil, 1, 1, nil],
                [nil, nil, 1, 1, 3, 3, nil, nil],
                [nil, 3, 3, nil, 3, 3, nil],
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [3, 1, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [4, 4, nil, nil, nil, 4, 4],
                [5, 5, nil, nil, nil, nil, 5, 5],
                [1, nil, nil, nil, nil, nil, 7],
                [7, 7, nil, nil, nil, nil, 2, 2],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 189,
            rows: [
                [1, 1, 5, 5, 5, 5, 2, 2],
                [2, 2, 2, 4, 4, 4, 4],
                [2, 2, 7, 7, 1, 1, 1, 6],
                [2, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 2],
                [2, 2, 2, 2, 3, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 190,
            rows: [
                [2, 2, nil, nil, nil, nil, nil, nil],
                [2, 2, nil, nil, nil, nil, nil],
                [2, 2, 2, nil, nil, nil, nil, nil],
                [2, 1, 1, nil, nil, nil, nil],
                [1, 3, 3, nil, nil, nil, nil, nil],
                [1, 1, 2, nil, nil, nil, nil],
                [2, 2, 2, 2, nil, nil, nil, nil],
                [2, 6, 6, 3, nil, nil, nil],
                [3, 3, 3, 3, nil, nil, nil, nil],
                [3, 3, 3, 3, nil, nil, nil],
                [4, 4, 4, 4, 4, nil, nil, nil],
                [4, 1, 1, 1, 1, nil, nil],
                [1, 1, 5, 5, 5, nil, nil, nil],
                [7, 1, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 191,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [2, 2, 2, 2, 2, 3, 3],
                [nil, 3, 3, 3, 4, 4, 4, nil],
                [5, 5, 5, 5, 1, 1, 2],
                [nil, 2, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 2, nil],
                [nil, 2, 2, 2, 4, 4, 4, nil],
                [nil, 1, 1, 1, 6, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 192,
            rows: [
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 3, 3, 3, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, 7, 7, 7, 5, 2, 2, nil],
                [nil, 2, 2, 2, 2, 6, nil],
                [nil, nil, 5, 1, 1, 1, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, 5, 5, 2, 2, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, 2, 2, 2, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 4, 5, 5, 5, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 4
        ),
        LevelTemplate(
            levelNumber: 193,
            rows: [
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 5, 5, 5, nil, nil],
                [nil, 5, 5, 5, 5, 1, nil],
                [nil, 1, nil, 3, 3, nil, 3, nil],
                [3, 3, 1, 1, 1, 1, 4],
                [nil, 4, nil, 4, 4, nil, 4, nil],
                [1, 1, 1, 1, 1, 2, 2],
                [nil, 2, nil, 7, 6, nil, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, 2, 2, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 194,
            rows: [
                [5, 5, 5, 5, 1, 1, 3, 1],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, 3, 3, 3, 3],
                [nil, nil, nil, nil, 3, nil, nil],
                [3, 1, 1, 4, 4, 4, 4, 4],
                [nil, nil, nil, nil, 4, nil, nil],
                [nil, nil, nil, 4, 6, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [2, 5, 5, 5, 2, 5, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 195,
            rows: [
                [3, 3, 2, nil, 4, 4, nil, nil],
                [4, 4, nil, nil, nil, nil, nil],
                [4, 4, nil, 4, 4, 4, 1, 1],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, 1, 1, 1, nil, nil, nil, 1],
                [1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 5, 5],
                [nil, nil, 2, nil, nil, nil, nil],
                [2, 2, 2, 2, 2, nil, nil, nil],
                [nil, 2, 3, nil, 3, 3, 3],
                [nil, 3, nil, 3, 3, 3, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 3, 3, 3, 3, 3, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 196,
            rows: [
                [1, nil, 1, nil, 1, nil, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [2, nil, 2, nil, 1, nil, 1, nil],
                [nil, 1, nil, 2, nil, 3, nil],
                [3, nil, 3, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [2, nil, 2, nil, 1, nil, 5, nil],
                [nil, 5, nil, 5, nil, 5, nil],
                [5, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [1, nil, 4, nil, 4, nil, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 1, 4, 4, 6, 1, 1, 1],
                [1, 5, 5, 2, 3, 3, 1],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 197,
            rows: [
                [5, 5, 6, nil, nil, 1, 1, 1],
                [1, 1, 1, nil, 2, nil, nil],
                [1, 3, 3, nil, 3, nil, 3, 3],
                [nil, 3, nil, nil, 3, nil, nil],
                [3, 1, nil, 2, 2, 4, nil, nil],
                [4, nil, nil, nil, 4, 4, nil],
                [nil, nil, 6, 6, 6, nil, 2, nil],
                [1, nil, nil, nil, 2, 2, 2],
                [1, 1, nil, 1, 1, 1, 1, 2],
                [1, nil, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 198,
            rows: [
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 5, 5, 5, 5, nil, nil],
                [nil, nil, 5, 5, 3, nil, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 4, 4, 4, nil, nil],
                [nil, nil, 4, 7, 6, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 199,
            rows: [
                [nil, nil, nil, 3, 4, nil, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, 4, 1, 1, 1, 1, 1, nil],
                [2, 2, 2, 2, 3, 3, 3],
                [nil, 3, 3, 3, 1, 5, 5, nil],
                [5, 5, 5, 2, 7, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 2, 2, 2, 1, 1, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, 2, 1, 1, 6, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 200,
            rows: [
                [1, 1, nil, nil, nil, nil, 4, 1],
                [4, 4, 4, 4, 2, 2, 2],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, 2, 2, 2, 2, 3, 3],
                [3, 3, nil, nil, nil, nil, 3, 3],
                [1, 1, 1, 2, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, 6, 6, 6, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, 2, 2, 2, 2, 2],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, 5, nil, nil, nil, nil, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
    ]
}
