// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch140 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2781,
            rows: [
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 4, 1, 2, 1, nil, nil],
                [nil, 5, 1, 2, 1, 3, nil],
                [nil, nil, 1, 3, 2, 1, nil, nil],
                [nil, 2, 3, 1, 2, 1, nil],
                [nil, nil, 2, 4, 2, 1, nil, nil],
                [nil, nil, 2, 1, 3, nil, nil],
                [nil, nil, 1, 2, 1, 4, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2782,
            rows: [
                [1, 2, nil, nil, nil, nil, 1, 4],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, nil, 1, 3, 1, 2, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, nil, 1, 5, 1, 3, nil, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 1, 4, nil, nil, nil],
                [2, 1, nil, nil, nil, nil, 3, 1],
                [2, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2783,
            rows: [
                [nil, 1, 4, nil, nil, 2, 4, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 4, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 4, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2784,
            rows: [
                [nil, 1, 1, nil, nil, 2, 1, nil],
                [2, nil, 3, nil, 4, nil, 5],
                [2, nil, nil, 3, 4, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, 2],
                [1, nil, nil, 2, 1, nil, nil, 2],
                [3, nil, nil, nil, nil, nil, 2],
                [nil, 1, nil, nil, nil, nil, 4, nil],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, 2, nil, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, nil, 1, nil, nil, 5, nil, nil],
                [nil, nil, 1, nil, 3, nil, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, 3, nil, 2, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2785,
            rows: [
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, 1, nil, nil],
                [nil, nil, nil, 3, nil, nil, 1, nil],
                [nil, nil, 4, nil, nil, 1, nil],
                [nil, nil, nil, nil, 2, nil, nil, 1],
                [nil, nil, nil, 2, nil, nil, 1],
                [nil, nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, 6, 1, 2, 6, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2786,
            rows: [
                [nil, 2, nil, nil, nil, nil, 4, nil],
                [1, 1, 2, 1, 4, 4, 2],
                [nil, nil, 1, 2, 1, 3, nil, nil],
                [nil, 1, 5, 1, 3, 2, nil],
                [nil, nil, 5, 1, 2, 2, nil, nil],
                [nil, 1, 2, 3, 1, 2, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2787,
            rows: [
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [2, 2, 5, 2, nil, nil, nil],
                [2, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, 2, 1],
                [1, nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, nil, 3, 1, 3, 1],
                [5, nil, nil, nil, 2, nil, nil, 1],
                [4, 1, 2, 1, nil, nil, nil],
                [2, nil, nil, nil, 1, nil, nil, 3],
                [1, 4, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, 2],
                [nil, nil, nil, 3, 1, 2, 1],
                [nil, nil, nil, 1, nil, nil, nil, 2],
                [nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2788,
            rows: [
                [2, 3, 1, 3, 2, 3, 2, 3],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 2, 1, 2, 1, 2, 1, 2],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 2, 1, 4, 1, 3, 1, 4],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 2, 1, 2, 1],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, 1, 2, 1, 2, 5, 1],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, 2, 2, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 4, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2789,
            rows: [
                [1, 2, nil, 3, 4, nil, 2, 3],
                [2, nil, nil, 1, nil, nil, 1],
                [2, nil, nil, 3, nil, nil, 2, nil],
                [3, nil, nil, 2, nil, nil, 3],
                [4, nil, nil, 2, nil, nil, 1, nil],
                [3, nil, nil, 2, nil, nil, 3],
                [1, nil, nil, 2, nil, nil, 1, nil],
                [2, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 2, nil, nil, 1, nil],
                [1, nil, nil, 1, nil, nil, 1],
                [2, nil, nil, 3, nil, nil, 2, nil],
                [1, nil, nil, 3, nil, nil, 2],
                [3, nil, nil, 2, nil, nil, 2, nil],
                [3, nil, nil, 2, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2790,
            rows: [
                [nil, nil, 2, nil, nil, 1, 3, nil],
                [nil, 1, 4, nil, nil, 2, 1],
                [2, nil, nil, 1, 3, 4, nil, nil],
                [1, 2, nil, 2, nil, nil, nil],
                [3, nil, nil, 4, 3, 4, nil, nil],
                [1, 1, nil, 2, nil, nil, nil],
                [3, nil, 1, 4, 1, 3, 1, nil],
                [nil, 2, nil, nil, 2, nil, 1],
                [3, nil, 4, 1, 2, 1, 3, nil],
                [nil, 2, nil, nil, 1, nil, 3],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2791,
            rows: [
                [nil, 1, 4, 5, 1, 2, 1, nil],
                [nil, 3, 1, 3, 1, 3, nil],
                [nil, nil, 2, 1, 2, 3, nil, nil],
                [nil, nil, 4, 1, 2, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, nil, nil],
                [3, 1, nil, nil, nil, nil, nil],
                [nil, 2, 3, nil, nil, nil, nil, nil],
                [nil, 2, 1, nil, nil, nil, nil],
                [nil, nil, 1, 2, nil, nil, nil, nil],
                [nil, nil, 3, 2, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2792,
            rows: [
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, 1, 2, 3, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, 2, 1, nil, 3, 1, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, 3, 1, nil, 3, 1, nil],
                [nil, 3, 1, 6, 1, 2, 1, nil],
                [nil, 4, 2, nil, 1, 2, nil],
                [nil, 2, 1, 4, 1, 1, 1, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2793,
            rows: [
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, 2, 1, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, 2, 3, 1, 2, 1, 3, nil],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, 4, 1, 3, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 2, 1, 1, 1, 2, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [6, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 3, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2794,
            rows: [
                [nil, nil, 4, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, 4, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 5, 1, 2, nil, nil],
                [nil, 1, 2, 2, 2, nil, nil],
                [nil, 1, 3, 1, 5, 1, 1, nil],
                [nil, 5, 1, 1, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2795,
            rows: [
                [nil, nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [2, 1, 2, 1, 2, 3, 4, 1],
                [nil, nil, nil, nil, 2, nil, nil],
                [4, 2, 1, 3, 1, 2, 1, 2],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2796,
            rows: [
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2797,
            rows: [
                [nil, 4, nil, 1, nil, 1, nil, nil],
                [nil, 2, nil, 2, nil, 3, nil],
                [nil, 1, nil, 4, nil, 1, nil, nil],
                [nil, 4, nil, 2, nil, 1, nil],
                [nil, 2, nil, 1, nil, 4, nil, nil],
                [nil, 1, nil, 2, nil, 4, nil],
                [nil, 5, nil, 1, nil, 4, nil, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [nil, 2, nil, 1, nil, 2, nil, nil],
                [nil, 2, nil, 1, nil, 3, nil],
                [nil, 2, nil, 1, nil, 2, nil, nil],
                [nil, 1, nil, 3, nil, 2, nil],
                [nil, 1, nil, 3, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2798,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 1, 5, nil, nil],
                [nil, nil, 5, 2, 1, nil, nil],
                [nil, nil, 3, 4, 2, 4, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil],
                [nil, nil, 2, 3, 1, 2, nil, nil],
                [nil, nil, 1, 3, 4, nil, nil],
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, nil, 3, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2799,
            rows: [
                [nil, 1, nil, 3, nil, 2, nil, 3],
                [4, nil, 1, nil, 1, nil, 3],
                [nil, 2, nil, 3, nil, 2, nil, 3],
                [2, nil, 1, nil, 2, nil, 1],
                [nil, 3, nil, 4, nil, 1, nil, 3],
                [1, nil, 3, nil, 1, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2800,
            rows: [
                [nil, 1, 2, nil, nil, nil, nil, nil],
                [1, 2, 1, nil, nil, nil, nil],
                [nil, 2, 5, nil, nil, nil, nil, nil],
                [nil, nil, 2, 4, nil, nil, nil],
                [nil, 1, 3, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 3, 5, nil, nil, nil],
                [nil, nil, 2, 5, nil, nil, nil],
                [nil, nil, 1, 2, 4, nil, nil, nil],
                [nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, nil, nil, 2, 1, nil, nil],
                [nil, nil, nil, 4, 1, 2, nil],
                [nil, nil, nil, nil, 1, 2, nil, nil],
                [nil, nil, nil, 1, 2, 1, nil],
                [nil, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
    ]
}
