// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch07 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 121,
            rows: [
                [2, 2, nil, nil, nil, nil, nil, nil],
                [2, 2, nil, nil, nil, nil, nil],
                [2, 2, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil, nil],
                [1, 1, 5, nil, nil, nil, nil],
                [5, 5, 5, 5, nil, nil, nil, nil],
                [5, 2, 1, 1, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [1, 1, 4, 3, 3, nil, nil, nil],
                [3, 3, 3, 3, 3, nil, nil],
                [3, 3, 3, 3, 3, nil, nil, nil],
                [3, 3, 4, 4, 6, nil, nil],
                [4, 2, 4, 4, 4, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 122,
            rows: [
                [nil, nil, 5, nil, nil, 5, nil, nil],
                [nil, 5, 5, 5, 5, 2, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [2, 2, 2, 2, 2, 2, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [1, 1, 3, 3, 3, 1, 4],
                [nil, 4, 4, 4, 4, 4, 4, nil],
                [nil, 4, 4, 4, 6, 6, nil],
                [nil, 3, 3, 3, 3, 3, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 123,
            rows: [
                [nil, nil, 2, 2, 2, 3, nil, nil],
                [nil, nil, 5, 5, 5, nil, nil],
                [nil, nil, 5, 5, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, 3, nil, nil],
                [nil, nil, 6, 6, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 6, 6, 3, nil, nil],
                [nil, nil, 3, 3, 4, 3, nil, nil],
                [nil, nil, 3, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 4, 4, nil, nil],
                [nil, nil, 1, 1, 1, 4, nil, nil],
                [nil, nil, 4, 3, 1, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 124,
            rows: [
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, 4, 4, 1, 1, 1, 1, nil],
                [5, 2, 2, 2, 2, 5, 3],
                [nil, 3, 3, 3, 3, 5, 2, nil],
                [2, 2, 2, 5, 5, 5, 3],
                [nil, 3, 3, 2, 2, 2, 2, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 3, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, 3, 3, 7, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 125,
            rows: [
                [nil, nil, nil, nil, 5, 5, 5, nil],
                [nil, nil, 5, 5, 5, 5, 3],
                [nil, nil, 4, 3, 3, 3, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 1, 1, nil],
                [nil, 1, 1, 1, 1, 4, nil, nil],
                [4, 4, 4, 4, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [3, 3, 3, 3, 3, nil, nil],
                [3, 3, 3, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 1, 1, 6, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 126,
            rows: [
                [1, nil, nil, nil, 1, nil, nil, 1],
                [1, 1, nil, nil, 1, nil, 1],
                [nil, nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, 1, nil, 1, nil],
                [nil, nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, 4, nil, 4, nil],
                [4, 4, 4, 4, 4, 1, nil, 1],
                [nil, nil, 1, 1, 1, 1, 1],
                [2, 2, 7, 2, 2, 2, nil, 2],
                [nil, nil, 3, 3, 3, 3, 3],
                [nil, 3, 3, nil, nil, 3, nil, nil],
                [2, 2, nil, nil, nil, 2, 2],
                [nil, 2, 2, nil, nil, 2, nil, nil],
                [2, 2, nil, nil, nil, 6, 5],
                [5, nil, nil, nil, nil, nil, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 127,
            rows: [
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, nil, 1, 1, 2, nil, 2],
                [nil, 4, nil, 3, 4, nil, 4, nil],
                [nil, 4, 4, 5, 5, 6, nil],
                [nil, 6, nil, 2, 2, nil, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [1, 1, 3, 6, 6, 1, 1, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [3, 3, 3, 1, 1, 1, 1, 5],
                [5, nil, nil, nil, nil, nil, 5],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 128,
            rows: [
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, 2, 4, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 7, 4, 4, 3, nil],
                [nil, 3, 3, 1, 1, 1, nil],
                [nil, 3, 3, 3, 3, 3, 3, nil],
                [nil, 1, 1, 1, 7, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 5, 5, 5, 5, 7, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 129,
            rows: [
                [5, nil, nil, 3, 3, nil, nil, 3],
                [3, 3, 3, 3, 3, 3, 3],
                [nil, 4, 4, nil, nil, 1, 5, nil],
                [5, nil, 1, 2, 4, nil, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [5, nil, 5, 2, 2, nil, 2],
                [nil, 2, 2, nil, nil, 2, 1, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, 2, 2, nil, nil, 2, 3, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, 1, 1, 1, 3, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 3, 3, 3, 1, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 130,
            rows: [
                [3, 3, nil, nil, nil, nil, nil, nil],
                [3, 3, nil, nil, nil, nil, nil],
                [3, 3, 3, nil, nil, nil, nil, nil],
                [3, 3, 1, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil],
                [1, 2, 5, 5, nil, nil, nil, nil],
                [5, 7, 7, 1, nil, nil, nil],
                [2, 2, 2, 2, nil, nil, nil, nil],
                [2, 2, 6, 6, nil, nil, nil],
                [1, 2, 2, 2, 2, nil, nil, nil],
                [2, 1, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, 1, nil, nil, nil],
                [4, 4, 1, 1, 1, nil, nil],
                [3, 2, 2, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 131,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 5, 5, 5, 4, nil],
                [nil, 4, 4, 4, 4, 4, 3, nil],
                [3, 3, 3, 1, 2, 2, 1],
                [nil, 1, 1, 1, 3, 2, 2, nil],
                [2, 2, 2, 2, 2, 2, 2],
                [nil, 2, 2, 3, 3, 3, 3, nil],
                [nil, 3, 3, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 6, 7, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 132,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 3, 3, 3, nil],
                [nil, nil, 4, 4, 3, 3, nil, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, 3, nil, 3, 3, nil, 3, nil],
                [2, 2, 2, 2, 2, 2, 2],
                [nil, 2, nil, 5, 5, nil, 7, nil],
                [1, 1, 1, 2, 1, 1, 1],
                [nil, 1, nil, 1, 1, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, 2, 1, nil, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 133,
            rows: [
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 4, 4, 1, 1, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 1, 1, 2, 2, nil, nil],
                [nil, nil, 5, 5, 5, nil, nil],
                [nil, nil, 5, 5, 5, 5, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 5, 1, 1, 4, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 4, 4, 1, 1, nil, nil],
                [nil, nil, 1, 1, 6, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 134,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, 4, 4, 4, nil],
                [4, 4, 4, 4, 4, 4, 4],
                [nil, 4, 4, 1, 3, 3, 3, nil],
                [3, 3, 1, 5, 5, 5, 5],
                [nil, 1, 1, 1, 1, 3, 3, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 6, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, 1, 6, 6, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 135,
            rows: [
                [nil, nil, nil, nil, 3, 3, 3, nil],
                [nil, nil, 3, 5, 5, 5, 5],
                [nil, nil, 5, 5, 5, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 2, 4, nil, nil],
                [2, 2, 2, 2, 2, nil, nil],
                [nil, 4, 4, 4, 4, 4, nil, nil],
                [4, 4, 4, 2, 2, nil, nil],
                [2, 2, 2, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, 5, 2, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 136,
            rows: [
                [2, nil, nil, nil, 2, nil, nil, 2],
                [2, 2, nil, nil, 2, nil, 2],
                [nil, nil, 2, nil, 2, nil, 2, nil],
                [2, nil, 2, 1, nil, 1, nil],
                [nil, nil, 1, nil, 1, nil, 1, nil],
                [4, nil, 4, 4, nil, 4, nil],
                [1, 1, 1, 1, 1, 1, nil, 1],
                [nil, nil, 1, 1, 1, 1, 1],
                [4, 4, 4, 4, 3, 5, nil, 5],
                [nil, nil, 5, 5, 5, 1, 1],
                [nil, 1, 1, nil, nil, 3, nil, nil],
                [3, 1, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [1, 1, nil, nil, nil, 3, 3],
                [3, nil, nil, nil, nil, nil, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 137,
            rows: [
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [nil, 1, 3, 3, 3, 2, nil],
                [nil, 2, nil, 3, 3, nil, 3, nil],
                [nil, 3, 2, 2, 2, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 6, 6, 6, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [2, 2, 2, 2, 2, 4, 3, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [3, 5, 4, 4, 5, 5, 5, 4],
                [4, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 138,
            rows: [
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 6, 6, 1, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 3, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 1, 1, 4, nil],
                [nil, 4, 4, 4, 3, 3, nil],
                [nil, 3, 3, 3, 3, 3, 3, nil],
                [nil, 3, 1, 1, 1, 1, nil],
                [nil, 1, 5, 5, 5, 4, 6, nil],
                [nil, 1, 1, 1, 1, 6, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 139,
            rows: [
                [5, 5, nil, nil, nil, nil, 5, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [6, nil, 6, 3, 3, nil, 3],
                [3, nil, nil, nil, nil, nil, nil, 3],
                [2, nil, 2, 1, 1, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 3],
                [3, 3, 3, nil, 3, 3, 3],
                [3, 2, 2, 2, 2, 2, 2, 2],
                [2, 2, 2, nil, 2, 1, 1],
                [nil, 3, 3, nil, nil, 4, 4, nil],
                [nil, nil, 4, 1, 1, nil, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, 1, 3, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 140,
            rows: [
                [nil, nil, 2, 2, nil, nil, nil, nil],
                [nil, 2, 2, 2, nil, nil, nil],
                [nil, 2, 2, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, 2, 2, 2],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [2, 2, 4, 4, 1, 3, 3],
                [3, 3, 3, 1, 1, 6, 6, 6],
                [6, 1, 4, 4, 4, 1, 1],
                [1, 1, 1, 5, 5, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
    ]
}
