// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch148 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2941,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, 2, 2, 3, 2, 1, 2],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [1, 3, 3, 1, 1, 2, 1],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [2, 2, 1, 2, 1, 2, 1],
                [nil, nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2942,
            rows: [
                [nil, nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 2, nil, nil, 1, nil, 3, nil],
                [1, nil, nil, 6, nil, nil, 2],
                [nil, 1, nil, nil, 3, nil, 2, nil],
                [1, nil, nil, 2, nil, nil, 3],
                [nil, 2, nil, nil, 1, nil, 2, nil],
                [nil, 2, nil, 1, nil, 2, nil],
                [nil, 1, nil, nil, 2, nil, 1, nil],
                [nil, 2, nil, 1, nil, 2, nil],
                [nil, nil, 4, 1, 3, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2943,
            rows: [
                [nil, nil, 5, nil, nil, 5, nil, nil],
                [nil, nil, 3, 1, 5, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 2, 4, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2944,
            rows: [
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, 5, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 3, 2, nil, nil],
                [nil, 5, 1, 3, 1, nil, nil],
                [nil, 5, 1, 4, 2, 2, 1, nil],
                [nil, 2, 1, 1, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2945,
            rows: [
                [1, nil, 4, nil, 1, nil, 3, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, 5, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [4, nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil, 1],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2946,
            rows: [
                [nil, 3, 4, 2, 3, 1, 5, nil],
                [3, nil, nil, nil, nil, nil, 1],
                [nil, 3, nil, nil, nil, nil, 4, nil],
                [4, 1, 1, 2, 3, 2, 1],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [1, 5, 2, 1, 3, 2, 1],
                [nil, 2, 2, 1, 2, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 2, 1, 2, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2947,
            rows: [
                [nil, nil, 3, nil, nil, 2, nil, nil],
                [nil, 1, 2, nil, 5, 3, nil],
                [nil, 1, 3, 2, 5, 1, 4, nil],
                [nil, 1, 3, nil, 2, 1, nil],
                [nil, 2, 3, 1, 4, 1, 2, nil],
                [nil, 1, 3, nil, 1, 3, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2948,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, 3, 6, 4, nil],
                [4, nil, nil, nil, nil, 2, nil],
                [nil, 3, nil, nil, 2, 1, 1, nil],
                [1, nil, nil, nil, nil, 3, nil],
                [2, 2, 5, 1, nil, 2, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [1, 2, 1, 2, nil, 1, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2949,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, 3, 5, nil, nil, nil, nil],
                [1, 2, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, 4, nil],
                [3, 3, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, 2, nil],
                [nil, nil, nil, 1, 4, nil, 2, 4],
                [nil, 1, 2, nil, nil, nil, nil],
                [nil, nil, nil, 4, 2, nil, 1, 2],
                [nil, 1, 1, nil, nil, nil, nil],
                [2, 1, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, 3, 1, nil],
                [2, 1, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2950,
            rows: [
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [1, 2, 1, 4, 1, 2, 3],
                [nil, nil, 1, 3, 5, 1, nil, nil],
                [nil, 2, 1, 4, 1, 5, nil],
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, 2, 3, 1, 3, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2951,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [1, 3, 3, 1, 5, 1, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2952,
            rows: [
                [2, nil, nil, nil, 1, nil, nil, nil],
                [6, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, 1, 1, nil, nil],
                [nil, 4, nil, 2, nil, 3, nil],
                [nil, 2, nil, nil, 2, 1, nil, nil],
                [nil, 3, nil, 2, nil, 3, nil],
                [nil, 2, nil, nil, 2, 1, nil, nil],
                [2, nil, nil, 1, 3, 1, nil],
                [nil, 3, nil, nil, 5, 1, nil, nil],
                [2, nil, nil, 1, 2, 1, nil],
                [1, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2953,
            rows: [
                [nil, nil, 2, nil, nil, 1, 2, nil],
                [nil, 3, 5, nil, nil, 2, 1],
                [2, nil, nil, 1, 2, 3, nil, nil],
                [1, 2, nil, 1, nil, nil, nil],
                [4, nil, nil, 1, 2, 1, nil, nil],
                [4, 3, nil, 3, nil, nil, nil],
                [1, nil, 2, 4, 1, 4, 1, nil],
                [nil, 1, nil, nil, 3, nil, 1],
                [3, nil, 1, 4, 1, 2, 1, nil],
                [nil, 3, nil, nil, 1, nil, 2],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2954,
            rows: [
                [1, 4, 1, 1, 3, 2, 1, 3],
                [2, nil, nil, 5, nil, nil, 1],
                [3, nil, nil, 5, 2, nil, nil, 1],
                [nil, nil, nil, 2, nil, nil, nil],
                [1, nil, nil, 2, 2, nil, nil, 1],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2955,
            rows: [
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, nil, 3, 2, 1, 2, nil, nil],
                [nil, nil, 4, nil, 2, nil, nil],
                [nil, nil, 3, 2, 1, 2, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [1, 2, 1, nil, nil, 2, 1, 3],
                [nil, nil, 1, nil, 2, nil, nil],
                [2, 4, 1, nil, nil, 3, 2, 1],
                [nil, nil, 5, nil, 2, nil, nil],
                [nil, nil, 1, 3, 4, 3, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 2, 1, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2956,
            rows: [
                [nil, nil, 3, 4, 2, nil, nil, nil],
                [nil, nil, 3, 1, 2, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, nil, 1, nil, 3, nil, 2, nil],
                [nil, 2, nil, 3, nil, 2, nil],
                [3, nil, 3, nil, 2, nil, 5, nil],
                [nil, 3, nil, 2, nil, 1, nil],
                [2, nil, 1, nil, 1, nil, 4, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [2, nil, 1, nil, 2, nil, 1, nil],
                [nil, 3, nil, 1, nil, 2, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2957,
            rows: [
                [nil, 3, nil, nil, 3, 4, 4, nil],
                [4, nil, nil, 1, 3, 2, nil],
                [5, nil, nil, 1, 4, 2, nil, nil],
                [2, nil, 1, 2, 1, nil, nil],
                [2, nil, nil, 3, 3, 1, nil, nil],
                [2, nil, 1, 3, 1, nil, nil],
                [3, nil, nil, 1, 3, 1, nil, nil],
                [2, nil, 1, 3, 1, 2, nil],
                [1, nil, nil, 2, 1, 2, nil, nil],
                [1, nil, 2, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2958,
            rows: [
                [nil, 1, nil, 1, nil, 3, nil, 1],
                [3, nil, 1, nil, 2, nil, 3],
                [nil, 5, nil, 3, nil, 3, nil, 2],
                [1, nil, 4, nil, 2, nil, 1],
                [nil, 3, nil, 5, nil, 6, nil, 2],
                [1, nil, 2, nil, 2, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2959,
            rows: [
                [nil, nil, nil, 5, 4, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2960,
            rows: [
                [nil, 1, nil, 3, nil, 1, nil, 1],
                [5, nil, 1, nil, 2, nil, 5],
                [nil, 1, nil, 3, nil, 2, nil, 1],
                [3, nil, 1, nil, 3, nil, 1],
                [nil, 2, nil, 4, nil, 1, nil, 2],
                [1, nil, 4, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
    ]
}
