// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch69 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1361,
            rows: [
                [3, 3, nil, nil, nil, nil, 1, 1],
                [1, 3, 3, 1, 3, 3, 1],
                [1, 2, nil, nil, nil, nil, 2, 4],
                [1, 3, 3, 1, 2, 4, 1],
                [5, 4, nil, nil, nil, nil, 1, 1],
                [1, 1, 3, 3, 5, 3, 3],
                [3, 5, nil, nil, nil, nil, 3, 1],
                [2, 4, 2, 1, 4, 4, 2],
                [3, 1, nil, nil, nil, nil, 2, 1],
                [2, 1, 1, 2, 1, 4, 1],
                [2, 4, nil, nil, nil, nil, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 3, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1362,
            rows: [
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [1, 3, 3, 3, 2, 2, 3, 1],
                [nil, nil, nil, nil, nil, nil, 1],
                [2, 4, 1, 4, 2, 2, 1, 4],
                [nil, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, 1, 4, 1, 4, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 4, 4, 1, 1, 2, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [1, 1, 2, 2, 1, 5, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1363,
            rows: [
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, 5, 4, 3, nil, nil],
                [nil, nil, 3, 2, 1, 1, nil, nil],
                [nil, 4, 4, 1, 4, 1, nil],
                [nil, nil, 3, 2, 2, 2, nil, nil],
                [nil, 2, 1, 2, 1, 2, nil],
                [nil, 1, 4, 4, 1, 1, 4, nil],
                [4, 1, 2, 1, 1, 1, 4],
                [nil, 1, 1, 2, 1, 1, 4, nil],
                [4, 2, 3, 2, 2, 2, 2],
                [2, 1, 1, 3, 1, 2, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 1, 3, 3, 3, 4, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1364,
            rows: [
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, 2, 3, 1, nil, nil],
                [nil, nil, 4, 1, 1, 2, nil, nil],
                [nil, 1, nil, 2, nil, 3, nil],
                [nil, nil, 3, 2, 2, 2, nil, nil],
                [nil, 1, nil, 2, nil, 2, nil],
                [2, nil, nil, 1, 3, nil, nil, 2],
                [1, 1, nil, 1, nil, 1, 2],
                [2, nil, nil, 1, 3, nil, nil, 1],
                [1, 3, nil, 2, nil, 1, 1],
                [nil, 7, 1, 4, 3, 3, 3, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, 5, 5, 1, 2, 1, 1, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1365,
            rows: [
                [2, nil, nil, nil, nil, nil, nil, 2],
                [5, 2, 1, 1, 5, 3, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [3, 1, 2, 1, 1, 3, 4],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [2, 1, 3, 1, 1, 3, 3],
                [1, nil, nil, nil, nil, nil, nil, 3],
                [1, 5, 2, 1, 2, 5, 2],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [2, 1, 5, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1366,
            rows: [
                [1, 1, 1, 3, 1, 2, 2, 4],
                [4, 2, 1, 1, 2, 6, 2],
                [2, 2, 2, 2, 1, 3, 3, 1],
                [1, 5, 1, 1, 5, 1, 1],
                [3, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1367,
            rows: [
                [nil, 6, 2, 4, 1, 3, 3, nil],
                [nil, 2, 1, 2, 2, 1, nil],
                [nil, nil, 5, 2, 4, 3, nil, nil],
                [nil, nil, 1, 3, 3, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, 4, 1, 1, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 4, nil, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, nil],
                [nil, 3, 2, nil, nil, nil, nil, nil],
                [nil, 1, 3, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 4, 2, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1368,
            rows: [
                [1, 1, 1, 2, 1, 3, 3, 5],
                [1, nil, 1, nil, 2, nil, 2],
                [nil, 4, 4, 4, 6, 2, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, 2, 1, 1, 1, 1, nil],
                [nil, 3, nil, 2, nil, 3, nil],
                [nil, 3, 2, 3, 1, 3, 3, nil],
                [1, nil, 1, nil, 1, nil, 3],
                [nil, 2, 2, 3, 1, 4, 4, nil],
                [1, nil, 2, nil, 2, nil, 1],
                [2, 2, 1, 3, 2, 3, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 1, 1, 1, 3, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1369,
            rows: [
                [1, 2, nil, 2, 5, nil, 2, 1],
                [3, 2, nil, 3, nil, 3, 2],
                [nil, 1, nil, 3, 2, nil, 1, nil],
                [1, 3, 2, 3, 3, 1, 1],
                [nil, 1, nil, 2, 1, nil, 2, nil],
                [3, 2, 2, 2, 1, 1, 3],
                [nil, 2, nil, 1, 2, nil, 2, nil],
                [3, 2, nil, nil, nil, 3, 1],
                [nil, 4, nil, 1, 2, nil, 1, nil],
                [1, 3, nil, nil, nil, 1, 1],
                [4, 1, 3, nil, nil, 4, 1, 1],
                [1, 1, nil, nil, nil, 2, 2],
                [2, 1, 2, nil, nil, 5, 1, 3],
                [3, 3, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1370,
            rows: [
                [nil, nil, 2, 4, 4, 7, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, nil, 2, 1, 4, nil, nil],
                [nil, nil, 1, 3, 3, 1, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 1, 3, 3, 1, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 1, 4, 3, 1, nil, nil],
                [nil, nil, 1, 4, 1, nil, nil],
                [nil, nil, 2, 2, 1, 2, nil, nil],
                [nil, nil, 2, 3, 5, nil, nil],
                [nil, nil, 5, 5, 1, 1, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1371,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, 2, 1, 3, 1, nil, nil, 1],
                [3, 3, 6, 3, 1, nil, 1],
                [nil, 1, 2, 2, 1, nil, nil, 2],
                [2, 1, 1, 2, 1, nil, 3],
                [1, 2, 3, 3, 4, 4, 1, nil],
                [1, 1, 2, 2, 2, nil, 2],
                [1, 5, 2, 2, 1, 2, 2, nil],
                [1, 2, 1, 2, 2, nil, 5],
                [nil, 5, 2, 5, 1, nil, nil, 2],
                [nil, nil, 6, nil, nil, nil, nil],
                [nil, 1, 2, 1, 2, nil, nil, 1],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1372,
            rows: [
                [nil, nil, 4, nil, nil, 2, nil, nil],
                [2, 1, 1, 1, 3, 3, 2],
                [3, 3, 3, 3, 3, 3, 2, 1],
                [3, 1, nil, 3, nil, 2, 3],
                [5, 2, 1, 1, 1, 2, 1, 4],
                [4, 4, nil, 4, nil, 2, 3],
                [2, 1, nil, 3, 1, nil, 2, 1],
                [2, nil, nil, 1, nil, nil, 2],
                [2, 2, nil, 1, 1, nil, 5, 1],
                [2, nil, nil, 1, nil, nil, 3],
                [3, 1, 1, nil, nil, 3, 3, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 2, 3, nil, nil, 2, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1373,
            rows: [
                [2, nil, nil, nil, 2, 1, nil, nil],
                [5, nil, nil, 3, 1, 1, nil],
                [1, nil, nil, 1, 1, 2, 1, nil],
                [1, nil, 1, 1, 1, 3, 1],
                [2, nil, nil, 4, 3, 2, 2, nil],
                [1, nil, 2, 4, 1, 3, 3],
                [3, nil, nil, 1, 1, 6, 6, nil],
                [4, nil, nil, 1, 1, 3, nil],
                [3, nil, nil, 1, 2, 1, 4, nil],
                [1, nil, nil, 1, 1, 1, nil],
                [1, nil, nil, nil, 2, 1, nil, nil],
                [nil, nil, nil, 4, 1, 5, nil],
                [5, nil, nil, nil, 1, 2, nil, nil],
                [nil, nil, nil, 2, 1, 2, nil],
                [nil, nil, nil, 2, 1, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1374,
            rows: [
                [nil, 1, 1, nil, nil, 1, 3, nil],
                [4, nil, 1, nil, 4, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 2],
                [3, nil, nil, nil, nil, nil, 1],
                [5, nil, nil, 3, 2, nil, nil, 1],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, nil, 4, nil],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, nil, 4, nil, nil, 4, nil, nil],
                [nil, nil, 6, nil, 4, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1375,
            rows: [
                [1, 1, 1, 2, 4, 2, 3, 1],
                [2, 1, 1, 3, 3, 3, 2],
                [4, 4, 4, 2, 2, 1, 1, 2],
                [1, 2, 1, 1, 6, 2, 5],
                [1, 2, 2, 2, 1, 2, 3, 3],
                [3, 3, 2, 1, 1, 2, 1],
                [2, 1, 2, 2, 1, 1, 1, 1],
                [2, 2, 2, 2, 1, 4, 1],
                [2, 2, 1, 2, 1, 5, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1376,
            rows: [
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil],
                [nil, nil, nil, nil, 3, 2, nil, nil],
                [nil, nil, nil, nil, 2, 5, nil],
                [nil, nil, nil, nil, nil, 5, 5, nil],
                [nil, nil, nil, nil, nil, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, 1, 2, nil],
                [2, 1, nil, nil, 2, 1, nil],
                [nil, 2, 2, nil, nil, 4, 1, nil],
                [1, 1, nil, nil, 3, 7, nil],
                [nil, 1, 4, nil, nil, 6, 3, nil],
                [1, 1, nil, nil, 3, 1, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, 1, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1377,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [4, 4, 1, 2, nil, nil, nil],
                [1, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, 1, 2],
                [5, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, 3, 1],
                [2, nil, nil, nil, 2, nil, nil, 1],
                [1, 6, 2, 3, nil, nil, nil],
                [2, nil, nil, nil, 2, nil, nil, 2],
                [2, 2, 2, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, 4],
                [nil, nil, nil, 5, 5, 1, 4],
                [nil, nil, nil, 1, nil, nil, nil, 1],
                [nil, nil, nil, 1, 3, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1378,
            rows: [
                [nil, 3, nil, 1, nil, 3, nil, 4],
                [1, 3, nil, 1, 4, nil, 4],
                [2, nil, 2, nil, 2, nil, 2, nil],
                [2, 4, nil, 1, 3, nil, 2],
                [2, nil, 1, nil, 1, nil, 3, nil],
                [3, 1, nil, 2, 2, nil, 2],
                [nil, 2, nil, 2, nil, 1, nil, 3],
                [3, 2, nil, 2, 2, nil, 3],
                [nil, 3, nil, 1, nil, 3, nil, 1],
                [3, 1, nil, 2, 1, nil, 3],
                [1, nil, 4, nil, 4, nil, 1, nil],
                [3, 1, nil, 2, 1, nil, 4],
                [5, nil, 1, nil, 3, nil, 3, nil],
                [1, 1, nil, 1, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1379,
            rows: [
                [nil, 2, nil, nil, 4, 4, 2, nil],
                [2, nil, nil, 2, 3, 3, nil],
                [1, nil, nil, 3, 1, 5, nil, nil],
                [5, nil, 5, 2, 3, nil, nil],
                [1, nil, nil, 3, 3, 1, nil, nil],
                [1, nil, 3, 1, 4, nil, nil],
                [1, nil, nil, 1, 3, 1, nil, nil],
                [1, nil, 1, 1, 1, 1, nil],
                [3, nil, nil, 3, 3, 3, nil, nil],
                [1, nil, 4, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1380,
            rows: [
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, nil, 1, 6, 6, nil, nil],
                [nil, nil, 3, 5, 5, 4, nil, nil],
                [nil, 5, 5, 3, 3, 3, nil],
                [nil, nil, 1, 4, 4, 2, nil, nil],
                [nil, 3, 2, 2, 1, 1, nil],
                [nil, 1, 3, 2, 2, 2, 1, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 1, 1, 1, 3, 3, 1, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
    ]
}
