// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch149 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2961,
            rows: [
                [1, nil, 4, nil, 1, nil, 2, nil],
                [nil, 4, nil, 3, nil, 1, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 6, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [1, nil, nil, nil, nil, nil, nil, 5],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2962,
            rows: [
                [nil, nil, nil, 2, 6, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2963,
            rows: [
                [nil, 5, 1, nil, nil, 5, 1, nil],
                [nil, 5, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, nil, 2, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 3, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 4, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2964,
            rows: [
                [nil, 5, nil, 3, nil, 2, nil, 3],
                [1, nil, 2, nil, 1, nil, 2],
                [nil, 1, nil, 3, nil, 1, nil, 4],
                [2, nil, 3, nil, 2, nil, 1],
                [nil, 3, nil, 1, nil, 2, nil, 1],
                [5, nil, 1, nil, 3, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2965,
            rows: [
                [nil, nil, 3, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, 1, nil, nil],
                [nil, nil, nil, 5, nil, nil, 3, nil],
                [nil, nil, 2, nil, nil, 3, nil],
                [nil, nil, nil, nil, 2, nil, nil, 2],
                [nil, nil, nil, 1, nil, nil, 3],
                [nil, nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 1, 5, 2, 1, nil, nil],
                [nil, 2, 3, 2, 2, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2966,
            rows: [
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, 1, 4, nil, 2, 4, nil],
                [nil, 2, 2, 5, 3, 3, 1, nil],
                [nil, 3, 6, nil, 1, 3, nil],
                [nil, 2, 1, 4, 3, 1, 1, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2967,
            rows: [
                [3, nil, 1, nil, 2, nil, 2, nil],
                [nil, 1, nil, 5, nil, 1, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 3, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2968,
            rows: [
                [nil, nil, nil, 6, 5, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2969,
            rows: [
                [3, nil, nil, nil, nil, nil, nil, 1],
                [5, 1, 4, 1, 1, 3, 1],
                [3, nil, nil, nil, nil, nil, nil, 4],
                [1, 3, 1, 2, 3, 2, 1],
                [6, nil, nil, nil, nil, nil, nil, 1],
                [3, 1, 2, 3, 1, 2, 1],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2970,
            rows: [
                [nil, 3, 1, nil, nil, 2, 5, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 3, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, nil, 3, nil, nil],
                [nil, 5, nil, nil, nil, 1, nil],
                [nil, 3, nil, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 6, nil, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2971,
            rows: [
                [nil, 1, 3, nil, 3, 2, nil, nil],
                [1, nil, 4, 2, nil, 3, nil],
                [1, nil, nil, nil, nil, nil, 1, nil],
                [2, 1, 2, nil, nil, 1, 1],
                [3, nil, nil, nil, nil, nil, 1, nil],
                [1, 2, 1, nil, nil, 2, 3],
                [nil, 2, 1, 2, 6, 1, 1, 2],
                [nil, 1, 2, nil, nil, 1, 2],
                [nil, 1, 2, 1, 2, 1, 2, 1],
                [nil, 5, 2, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2972,
            rows: [
                [nil, 6, nil, 3, nil, 4, nil, 3],
                [2, nil, 2, nil, 3, nil, 1],
                [nil, 4, nil, 1, nil, 2, nil, 1],
                [2, nil, 2, nil, 1, nil, 2],
                [nil, 4, nil, 1, nil, 4, nil, 1],
                [4, nil, 4, nil, 1, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2973,
            rows: [
                [nil, nil, 1, nil, nil, 3, nil, nil],
                [nil, 3, nil, nil, 1, nil, nil],
                [nil, nil, nil, 2, nil, nil, 1, nil],
                [nil, nil, 6, nil, nil, 2, nil],
                [nil, nil, nil, nil, 5, nil, nil, 1],
                [nil, nil, nil, 4, nil, nil, 1],
                [nil, nil, nil, nil, nil, 4, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, 4, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 3, 3, 2, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, 2, 1, 3, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2974,
            rows: [
                [nil, nil, 1, nil, nil, 4, nil, nil],
                [nil, 5, 3, nil, 1, 2, nil],
                [nil, 1, 4, 1, 1, 1, 1, nil],
                [nil, 5, 1, nil, 2, 5, nil],
                [nil, 2, 4, 4, 2, 3, 4, nil],
                [nil, 2, 2, nil, 2, 2, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2975,
            rows: [
                [nil, 3, nil, nil, nil, nil, 2, nil],
                [3, nil, nil, 2, nil, nil, 1],
                [2, nil, nil, 1, 3, nil, nil, 4],
                [1, nil, nil, 4, nil, nil, 5],
                [4, nil, nil, 2, 2, nil, nil, 1],
                [4, nil, nil, 1, nil, nil, 1],
                [nil, 3, 1, 3, 1, 3, 1, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, 1, 2, 1, 3, 1, 2, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2976,
            rows: [
                [5, nil, 1, nil, 4, nil, 3, nil],
                [nil, 2, nil, 1, nil, 2, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, 1, nil, nil],
                [nil, 5, nil, nil, nil, 2, nil],
                [3, nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2977,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2978,
            rows: [
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, 1, nil, nil, 2, nil, 1, nil],
                [2, nil, nil, 4, nil, nil, 5],
                [nil, 1, nil, nil, 2, nil, 1, nil],
                [2, nil, nil, 3, nil, nil, 2],
                [nil, 1, nil, nil, 3, nil, 1, nil],
                [nil, 4, nil, 1, nil, 2, nil],
                [nil, 5, nil, nil, 5, nil, 2, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [nil, nil, 1, 3, 1, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2979,
            rows: [
                [1, 3, 1, 2, 1, 2, 4, 1],
                [3, nil, nil, 2, nil, nil, 3],
                [2, nil, nil, 5, 2, nil, nil, 3],
                [nil, nil, nil, 2, nil, nil, nil],
                [4, nil, nil, 1, 3, nil, nil, 2],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2980,
            rows: [
                [3, nil, nil, nil, nil, nil, nil, 5],
                [1, 2, 4, 2, 1, 5, 2],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [4, 3, 2, 3, 1, 3, 2],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [4, 4, 1, 3, 1, 3, 1],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 1
        ),
    ]
}
