// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch130 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2581,
            rows: [
                [2, 4, nil, nil, nil, nil, 4, 2],
                [2, 5, nil, nil, nil, 2, 3],
                [1, 2, nil, nil, nil, nil, 3, 1],
                [3, nil, nil, nil, nil, nil, 2],
                [1, 5, nil, nil, nil, nil, 4, 1],
                [5, nil, nil, nil, nil, nil, 1],
                [2, 1, nil, nil, nil, nil, 2, 1],
                [3, 1, 6, 1, 5, 1, 3],
                [3, 3, nil, nil, nil, nil, 1, 1],
                [4, 2, 1, 1, 2, 3, 2],
                [nil, 1, 5, 2, 1, 1, 2, nil],
                [nil, 5, nil, 2, nil, 1, nil],
                [nil, 2, 1, 2, 3, 1, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2582,
            rows: [
                [nil, 2, nil, nil, 1, 7, 1, nil],
                [5, nil, nil, 5, 2, 1, nil],
                [3, nil, nil, 1, 3, 1, nil, nil],
                [3, nil, 3, 4, 1, nil, nil],
                [3, nil, nil, 1, 3, 2, nil, nil],
                [3, nil, 2, 4, 1, nil, nil],
                [4, nil, nil, 1, 6, 1, nil, nil],
                [1, nil, 2, 1, 3, 2, nil],
                [1, nil, nil, 3, 1, 3, nil, nil],
                [1, nil, 3, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2583,
            rows: [
                [nil, nil, nil, 7, 1, nil, nil, nil],
                [nil, 3, 4, 1, 3, 2, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 3, 1, 2, nil, nil],
                [nil, nil, nil, 6, 1, nil, nil, nil],
                [nil, 3, 2, 1, 4, 2, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, 4, 2, 3, 1, 5, nil],
                [nil, nil, nil, 6, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2584,
            rows: [
                [1, nil, nil, 3, nil, 7, 3, 1],
                [4, nil, 2, nil, 1, nil, 3],
                [1, nil, nil, 3, nil, nil, nil, 2],
                [1, 2, 1, nil, nil, nil, 3],
                [4, nil, nil, 1, nil, nil, nil, 2],
                [1, 1, 2, nil, nil, nil, 3],
                [nil, nil, nil, 1, nil, 1, 3, nil],
                [nil, nil, 1, nil, 4, nil, nil],
                [nil, nil, nil, 6, nil, 1, 2, nil],
                [nil, nil, 1, nil, 3, nil, nil],
                [nil, nil, nil, 2, nil, 1, 3, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2585,
            rows: [
                [1, 5, 2, 2, 1, 4, 1, 4],
                [4, nil, nil, 1, nil, nil, 3],
                [2, 3, 1, 2, 1, 4, 3, 4],
                [1, nil, nil, 5, nil, nil, 1],
                [2, 3, 2, 1, 2, 1, 3, 1],
                [3, nil, nil, 6, nil, nil, 1],
                [nil, 2, nil, nil, 1, nil, nil, 3],
                [1, 3, 3, 1, 2, 1, 2],
                [nil, 1, nil, nil, 2, nil, nil, 1],
                [2, 1, 2, 1, 2, 1, 2],
                [nil, 1, nil, nil, 2, nil, nil, 1],
                [2, nil, nil, 1, nil, nil, 2],
                [nil, 1, nil, nil, 2, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2586,
            rows: [
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [1, 3, 3, 3, 1, 2, 1, 5],
                [nil, nil, nil, nil, 1, nil, nil],
                [3, 1, 2, 1, 2, 1, 7, 1],
                [nil, nil, nil, nil, 5, nil, nil],
                [nil, nil, nil, 1, 6, nil, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2587,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 5, 1, 4, nil, nil],
                [nil, nil, 2, 1, 2, 3, nil, nil],
                [nil, 2, 1, 7, 4, 4, nil],
                [nil, nil, 1, 5, 1, 3, nil, nil],
                [nil, 2, 2, 1, 2, 2, nil],
                [nil, 1, 5, 1, 1, 3, 1, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 1, 2, 5, 1, 2, 3, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2588,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 4, nil, 5, 2, nil, nil],
                [1, 2, nil, 1, 2, nil, nil],
                [nil, 1, 5, nil, 1, 6, nil, nil],
                [1, 2, nil, 2, 3, nil, nil],
                [nil, 1, 4, nil, 2, 1, nil, nil],
                [2, 1, nil, 2, 1, nil, nil],
                [nil, 1, 3, nil, 1, 2, nil, nil],
                [3, 1, nil, 4, 1, nil, nil],
                [nil, 3, 1, nil, 2, 1, nil, nil],
                [6, 1, nil, 2, 1, nil, nil],
                [nil, 2, 3, nil, 4, 1, nil, nil],
                [4, 1, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2589,
            rows: [
                [nil, 2, 1, nil, nil, 3, 2, nil],
                [1, 3, 3, 1, 5, 2, 1],
                [5, 3, 1, 5, 1, 2, 2, 1],
                [5, 1, 2, 1, 2, 1, 5],
                [2, 1, 6, 1, 2, 2, 1, 4],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2590,
            rows: [
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [5, nil, nil, 4, nil, nil, 2],
                [1, 7, 4, 1, 2, 3, 1, 4],
                [2, nil, nil, 1, nil, nil, 4],
                [4, 1, 2, 6, 1, 2, 4, 1],
                [3, nil, nil, 1, nil, nil, 3],
                [nil, 1, nil, 2, nil, nil, 1, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, 2, nil, 4, nil, nil, 1, nil],
                [nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 4, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2591,
            rows: [
                [nil, 2, 3, nil, 4, 3, nil, nil],
                [nil, 1, 4, nil, 4, 3, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 3, nil, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 6, 7, nil, nil, nil],
                [nil, nil, 3, 1, 3, nil, nil],
                [nil, nil, 1, 5, 2, nil, nil, nil],
                [nil, 1, 2, 1, nil, nil, nil],
                [nil, 2, 2, 3, nil, nil, nil, nil],
                [nil, 2, 1, 1, nil, nil, nil],
                [nil, 1, 3, 2, nil, nil, nil, nil],
                [nil, 1, 2, 1, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2592,
            rows: [
                [nil, 2, 1, nil, 6, 2, 3, nil],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 1, 5, 1, nil, 2, 1, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 1, 5, 1, nil, 2, 2, nil],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 1, 2, nil, 4, 1, 2, nil],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 7, 1, nil, 2, 1, 3, nil],
                [1, nil, nil, nil, nil, nil, 3],
                [nil, 2, 1, 1, nil, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2593,
            rows: [
                [nil, 1, nil, 3, nil, 4, nil, 1],
                [2, nil, 1, nil, 4, nil, 3],
                [nil, 2, nil, 1, nil, 4, nil, 3],
                [5, nil, 1, nil, 4, nil, 1],
                [nil, 3, nil, 3, nil, 4, nil, 1],
                [5, nil, 5, nil, 2, nil, 6],
                [nil, 2, nil, 1, nil, 4, nil, 2],
                [4, nil, 1, nil, 2, nil, 1],
                [nil, 4, nil, 5, nil, 5, nil, 1],
                [2, nil, 1, nil, 2, nil, 1],
                [nil, 2, nil, 4, nil, 1, nil, 2],
                [3, nil, 2, nil, 1, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2594,
            rows: [
                [4, nil, 3, 1, 1, 3, nil, 4],
                [1, nil, nil, nil, nil, nil, 3],
                [1, 5, 1, 2, 2, 3, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, 1, 2, nil, nil],
                [nil, nil, 3, 1, 3, nil, nil],
                [nil, nil, 1, 3, 5, 6, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 5, nil, 2, nil, 1],
                [3, nil, 2, nil, 1, nil, 2],
                [nil, 1, nil, 3, nil, 3, nil, 1],
                [4, nil, 1, nil, 3, nil, 1],
                [nil, 2, nil, 1, nil, 5, nil, 1],
                [3, nil, 1, nil, 2, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2595,
            rows: [
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 7, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2596,
            rows: [
                [nil, 1, 2, nil, nil, 1, 2, nil],
                [7, nil, 2, nil, 1, nil, 3],
                [1, nil, nil, 1, 2, nil, nil, 1],
                [2, nil, nil, nil, nil, nil, 4],
                [1, nil, nil, 5, 4, nil, nil, 2],
                [1, nil, nil, nil, nil, nil, 3],
                [nil, 1, nil, nil, nil, nil, 5, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [nil, 5, nil, nil, nil, 1, nil],
                [nil, nil, 6, nil, nil, 1, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2597,
            rows: [
                [nil, 2, 1, nil, nil, 2, 3, nil],
                [1, nil, nil, nil, nil, nil, 5],
                [3, 1, nil, nil, nil, nil, 2, 6],
                [1, nil, nil, nil, nil, nil, 2],
                [2, 1, nil, nil, nil, nil, 2, 1],
                [1, nil, nil, nil, nil, nil, 3],
                [1, 3, nil, nil, nil, nil, 1, 3],
                [3, nil, nil, nil, nil, nil, 1],
                [2, 1, nil, nil, nil, nil, 2, 3],
                [2, nil, nil, nil, nil, nil, 1],
                [1, 3, nil, nil, nil, nil, 5, 1],
                [4, 1, nil, nil, nil, 2, 5],
                [2, 5, nil, nil, nil, nil, 1, 2],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2598,
            rows: [
                [nil, nil, nil, 1, 2, 2, 3, nil],
                [2, 1, 4, nil, nil, nil, 1],
                [6, nil, nil, nil, nil, nil, nil, 1],
                [2, nil, nil, nil, nil, nil, 1],
                [3, nil, nil, nil, nil, nil, nil, 5],
                [2, nil, nil, nil, nil, nil, 5],
                [3, nil, nil, nil, 1, 2, 2, 2],
                [1, nil, nil, 4, 1, 3, 1],
                [4, nil, nil, nil, 1, 5, 1, 2],
                [1, nil, nil, 3, 1, 3, 2],
                [2, nil, nil, nil, 1, 5, 1, 3],
                [1, 4, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2599,
            rows: [
                [2, 3, 2, nil, nil, 2, 1, 2],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, 2, 1, 3, 5, nil, nil],
                [nil, 2, nil, 6, nil, 6, nil],
                [nil, nil, 2, 3, 2, 2, nil, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [nil, nil, 1, 5, 2, 2, nil, nil],
                [nil, nil, 1, 1, 3, nil, nil],
                [nil, nil, 2, 7, 2, 4, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, 3, 1, nil, nil, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, 4, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2600,
            rows: [
                [1, 2, 3, 1, 5, 1, 2, 1],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [1, 4, 2, 1, 4, 2, 4, 2],
                [nil, nil, nil, nil, 2, nil, nil],
                [2, 1, 1, 2, 1, 5, 2, 1],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [4, 1, 2, 6, 1, 2, 1, 5],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
    ]
}
