// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch68 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1341,
            rows: [
                [nil, 1, 2, nil, nil, 2, 5, nil],
                [2, nil, 5, nil, 1, nil, 2],
                [4, nil, nil, 2, 3, nil, nil, 3],
                [5, nil, nil, nil, nil, nil, 4],
                [2, nil, nil, 5, 2, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 1, nil, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, nil, 4, nil],
                [nil, 4, nil, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 6, nil, nil, 2, nil, nil],
                [nil, nil, 3, nil, 3, nil, nil],
                [nil, nil, 1, nil, nil, 5, nil, nil],
                [nil, nil, 1, nil, 6, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1342,
            rows: [
                [1, 1, 1, 2, 5, 2, 1, 1],
                [2, 2, 2, 2, 1, 1, 2],
                [4, 1, 1, 2, 1, 2, 1, 1],
                [2, 2, 4, 2, 1, 2, 2],
                [4, 2, 6, 2, 3, 1, 2, 1],
                [1, 3, 2, 3, 3, 1, 1],
                [1, 2, 1, 2, 1, 1, 2, 4],
                [2, 2, 2, 2, 2, 2, 6],
                [2, 2, 2, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1343,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil],
                [nil, nil, nil, nil, 4, 4, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, 5, 1, nil],
                [nil, nil, nil, nil, nil, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 6, nil, nil, 3, 1, nil],
                [1, 1, nil, nil, 2, 1, nil],
                [nil, 2, 4, nil, nil, 2, 3, nil],
                [2, 2, nil, nil, 3, 5, nil],
                [nil, 2, 1, nil, nil, 1, 5, nil],
                [1, 2, nil, nil, 1, 1, nil],
                [nil, 1, 1, nil, nil, 5, 3, nil],
                [3, 2, nil, nil, 1, 2, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1344,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [3, 3, 4, 4, nil, nil, nil],
                [4, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, 3, 1],
                [3, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 3, 4, 3, 1],
                [4, nil, nil, nil, 1, nil, nil, 1],
                [4, 1, 1, 1, nil, nil, nil],
                [2, nil, nil, nil, 2, nil, nil, 2],
                [3, 3, 1, 1, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil, 3],
                [nil, nil, nil, 3, 1, 2, 1],
                [nil, nil, nil, 5, nil, nil, nil, 1],
                [nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1345,
            rows: [
                [nil, 2, nil, 4, nil, 4, nil, 4],
                [4, 2, nil, 3, 2, nil, 2],
                [1, nil, 3, nil, 3, nil, 2, nil],
                [3, 2, nil, 1, 2, nil, 1],
                [1, nil, 4, nil, 1, nil, 4, nil],
                [2, 1, nil, 2, 1, nil, 2],
                [nil, 2, nil, 2, nil, 2, nil, 3],
                [3, 1, nil, 3, 2, nil, 1],
                [nil, 1, nil, 6, nil, 3, nil, 4],
                [1, 4, nil, 2, 1, nil, 3],
                [1, nil, 2, nil, 2, nil, 2, nil],
                [1, 1, nil, 4, 1, nil, 3],
                [1, nil, 3, nil, 1, nil, 1, nil],
                [1, 1, nil, 1, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1346,
            rows: [
                [4, 4, 4, 2, 2, 1, 1, 7],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 1, 3, 3, 3, 1, 1, 1],
                [nil, 2, nil, nil, nil, nil, nil],
                [nil, 1, 3, 1, 3, 3, 5, 1],
                [nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 2, 2, 1, 1],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, 1, 5, 5, 3, 2, 1],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 2, 5, 1, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1347,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 1, 1, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 5, 5, 5, 1, nil, nil],
                [nil, nil, 3, 3, 5, nil, nil],
                [nil, nil, 1, 6, 4, 1, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1348,
            rows: [
                [nil, nil, 3, 1, 1, nil, nil, nil],
                [nil, 3, 3, 3, 1, nil, nil],
                [nil, 4, 1, 1, 2, 3, nil, nil],
                [2, 2, 2, 4, 4, 1, nil],
                [nil, 1, 2, 5, 5, 1, nil, nil],
                [3, 1, 1, 4, 3, 1, nil],
                [nil, nil, 2, nil, 1, nil, nil, nil],
                [nil, 2, nil, nil, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, 2, nil, nil, 4, nil, nil],
                [nil, 4, 3, 3, nil, 3, 5, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 2, 1, nil, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1349,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, 2, 2, 1, 2, nil, nil],
                [nil, 2, 1, 4, 4, 3, nil],
                [nil, nil, 1, 1, 6, 6, nil, nil],
                [nil, 2, 1, 2, 2, 3, nil],
                [nil, 3, nil, 3, 1, nil, 3, nil],
                [1, 2, 2, 1, 3, 3, 3],
                [nil, 1, nil, 2, 4, nil, 1, nil],
                [3, 3, 1, 2, 1, 5, 1],
                [nil, 3, nil, 3, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, 1, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1350,
            rows: [
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [nil, 3, 3, 1, 2, 1, nil],
                [nil, 6, nil, nil, nil, nil, nil, nil],
                [6, nil, nil, nil, nil, nil, nil],
                [nil, 6, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 3, 5, 1, 1, 4, 1, 1],
                [nil, 2, nil, nil, nil, nil, 2],
                [nil, 3, 1, 1, 2, 1, 1, 1],
                [nil, 1, nil, nil, nil, nil, 1],
                [nil, nil, nil, 1, 1, 2, 2, nil],
                [nil, 2, 4, nil, nil, nil, nil],
                [nil, nil, nil, 4, 2, 1, 1, nil],
                [nil, 2, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1351,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, 2, 3, 2, 4, 4, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, 1, 1, 4, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, 1, 1, 1, 2, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 3, 4, 3, 1, 3, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, 6, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1352,
            rows: [
                [nil, 5, 5, 1, 5, 1, 1, nil],
                [2, nil, nil, nil, nil, nil, 1],
                [nil, 1, nil, nil, nil, nil, 4, nil],
                [2, 2, 3, 2, 4, 1, 4],
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [3, 1, 2, 2, 3, 3, 1],
                [nil, 3, 1, 1, 4, 1, 2, nil],
                [nil, 2, 4, 1, 3, 3, nil],
                [nil, 1, 3, 1, 4, 3, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1353,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 4, 1, 6, nil, nil],
                [nil, nil, 1, 1, 2, 2, nil, nil],
                [nil, 1, 2, 1, 1, 3, nil],
                [nil, nil, 1, 2, 2, 2, nil, nil],
                [nil, 2, 2, 1, 1, 1, nil],
                [nil, 3, 3, 3, 1, 1, 1, nil],
                [4, 5, 5, 2, 1, 1, 1],
                [nil, 1, 1, 2, 2, 2, 1, nil],
                [2, 3, 4, 1, 4, 1, 2],
                [nil, 2, 1, 3, 1, 1, 2, nil],
                [nil, 1, 1, 5, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1354,
            rows: [
                [6, nil, nil, nil, nil, nil, nil, 1],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 1, 1, 5, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 3, 2, 1, 1, 1, nil],
                [nil, 3, 1, 1, 1, 1, 3, nil],
                [nil, 3, 4, 2, 2, 3, nil],
                [nil, nil, 3, 1, 1, 4, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, 5, 2, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1355,
            rows: [
                [2, nil, nil, 1, 1, nil, nil, 2],
                [2, nil, 5, nil, 3, nil, 3],
                [nil, 3, 1, nil, nil, 3, 3, nil],
                [1, 3, nil, nil, nil, 6, 2],
                [nil, 3, 1, nil, nil, 1, 3, nil],
                [3, 1, nil, nil, nil, 3, 1],
                [2, nil, 1, 3, 2, 1, nil, 1],
                [4, 4, nil, nil, nil, 1, 5],
                [1, nil, 2, 2, 2, 5, nil, 1],
                [3, 1, nil, nil, nil, 1, 2],
                [nil, 2, 3, nil, nil, 1, 4, nil],
                [1, nil, 1, nil, 1, nil, 4],
                [nil, 1, 3, nil, nil, 1, 1, nil],
                [3, nil, 1, nil, 2, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1356,
            rows: [
                [nil, nil, nil, nil, 2, 2, 1, 1],
                [3, 1, 4, 4, 4, 1, 2],
                [1, 3, 4, 2, 1, 2, 5, 1],
                [3, 3, 1, 1, 2, 2, 2],
                [1, 1, 2, 2, 2, 3, 3, 3],
                [2, 3, 1, 2, 1, 3, 2],
                [nil, nil, nil, nil, 1, 1, 1, 4],
                [nil, nil, nil, nil, 4, 2, 2],
                [nil, nil, nil, nil, 1, 1, 2, 1],
                [nil, nil, nil, nil, 3, 1, 1],
                [nil, nil, nil, nil, 1, 1, 2, 3],
                [nil, nil, nil, nil, 1, 2, 1],
                [nil, nil, nil, nil, 3, 1, 1, 3],
                [nil, nil, nil, nil, 3, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1357,
            rows: [
                [nil, nil, 6, nil, nil, 4, 2, nil],
                [nil, 5, 4, nil, nil, 4, 2],
                [2, nil, nil, 1, 1, 3, nil, nil],
                [2, 1, nil, 1, nil, nil, nil],
                [3, nil, nil, 2, 2, 2, nil, nil],
                [3, 3, nil, 3, nil, nil, nil],
                [3, nil, 1, 6, 3, 1, 6, nil],
                [nil, 3, nil, nil, 2, nil, 1],
                [4, nil, 1, 1, 1, 3, 1, nil],
                [nil, 2, nil, nil, 1, nil, 3],
                [nil, 1, 1, nil, nil, nil, 5, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 3, 1, nil, nil, nil, 2, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1358,
            rows: [
                [nil, nil, nil, nil, nil, nil, 1, 3],
                [nil, nil, 3, 1, 3, 3, 1],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, 1, 3],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, 1, 1, nil, nil, 5, nil, nil],
                [2, 1, 6, nil, 1, nil, nil],
                [nil, 1, 2, nil, nil, 1, nil, nil],
                [3, 2, 1, nil, 1, nil, nil],
                [2, nil, 2, 1, 3, 2, nil, 1],
                [nil, 2, nil, 2, nil, 2, 1],
                [4, nil, 1, 5, 1, 1, nil, 2],
                [nil, 6, nil, 1, nil, 1, 1],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1359,
            rows: [
                [1, 3, 1, 1, 2, 3, 1, 3],
                [nil, nil, nil, nil, nil, nil, 3],
                [2, 4, 1, 2, 1, 4, 1, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [3, 4, 3, 1, 1, 4, 4, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [2, 2, 1, 2, 2, 6, 1, 2],
                [nil, nil, nil, nil, nil, nil, 1],
                [2, 1, 1, 3, 3, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, 2],
                [3, 3, 2, 2, 1, 1, 6, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 1, 3, 3, 3, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 3, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1360,
            rows: [
                [nil, 1, nil, 5, nil, 2, nil, 2],
                [5, nil, 5, nil, 3, nil, 1],
                [1, nil, 2, nil, 1, nil, 4, nil],
                [nil, 4, nil, 1, nil, 6, nil],
                [2, nil, 1, nil, 1, nil, 2, nil],
                [nil, 1, nil, 1, nil, 3, nil],
                [nil, 1, nil, 1, nil, 2, nil, nil],
                [3, nil, 2, nil, 1, nil, nil],
                [nil, 2, nil, 5, nil, 2, nil, nil],
                [1, nil, 2, nil, 2, nil, nil],
                [nil, nil, 3, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
    ]
}
