// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch102 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2021,
            rows: [
                [5, 5, nil, nil, nil, nil, 4, 2],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, 3, 2, 3, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, 3, 3, 1, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, nil, nil, nil],
                [6, 3, nil, nil, nil, nil, 1, 3],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, 1, nil, nil, 3],
                [1, nil, nil, 1, nil, nil, 5],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2022,
            rows: [
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, 4, nil, nil],
                [2, 2, 2, 3, 3, 3, 2, 2],
                [nil, nil, nil, nil, 1, nil, nil],
                [1, 4, 3, 3, 1, 2, 2, 2],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 5, nil, 4, nil, nil],
                [nil, nil, nil, 6, 1, nil, nil, nil],
                [nil, nil, 1, nil, 6, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 2, 5, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2023,
            rows: [
                [nil, 1, 2, nil, nil, 2, 1, nil],
                [4, 2, 1, 2, 2, 1, 3],
                [1, 3, 2, 2, 6, 2, 1, 1],
                [5, 5, 3, 3, 4, 3, 1],
                [2, 2, 7, 1, 2, 1, 1, 1],
                [3, 3, 1, 1, 3, 2, 2],
                [nil, 1, 3, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2024,
            rows: [
                [2, 1, nil, 3, 2, nil, 1, 1],
                [4, nil, nil, 4, nil, nil, 4],
                [3, nil, nil, 5, nil, nil, 1, nil],
                [1, nil, nil, 5, nil, nil, 2],
                [1, nil, nil, 2, nil, nil, 1, nil],
                [1, nil, nil, 2, nil, nil, 1],
                [3, nil, nil, 2, nil, nil, 2, nil],
                [2, nil, nil, 3, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1, nil],
                [1, nil, nil, 2, nil, nil, 2],
                [2, nil, nil, 2, nil, nil, 3, nil],
                [3, nil, nil, 7, nil, nil, 5],
                [1, nil, nil, 1, nil, nil, 1, nil],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2025,
            rows: [
                [nil, 2, nil, 1, nil, 2, nil, 4],
                [1, 2, nil, 3, 2, nil, 3],
                [3, nil, 1, nil, 1, nil, 1, nil],
                [3, 1, nil, 2, 1, nil, 3],
                [1, nil, 3, nil, 1, nil, 2, nil],
                [2, 3, nil, 3, 2, nil, 1],
                [nil, 1, nil, 2, nil, 1, nil, 1],
                [3, 2, nil, 1, 4, nil, 1],
                [nil, 1, nil, 1, nil, 4, nil, 4],
                [2, 3, nil, 2, 2, nil, 3],
                [1, nil, 2, nil, 2, nil, 2, nil],
                [2, 3, nil, 1, 5, nil, 1],
                [3, nil, 3, nil, 3, nil, 1, nil],
                [2, 1, nil, 3, 6, nil, 1],
                [nil, 3, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2026,
            rows: [
                [nil, 1, nil, nil, nil, nil, 7, nil],
                [nil, 1, 1, 2, 3, 1, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [nil, 4, 3, 5, 1, 2, 1, 2],
                [nil, 1, nil, nil, nil, nil, 2],
                [nil, 2, 2, 5, 2, 1, 3, 1],
                [nil, 2, nil, nil, nil, nil, 2],
                [nil, nil, nil, 1, 3, 3, 1, nil],
                [nil, 2, 5, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2027,
            rows: [
                [2, 1, 1, 3, 4, 3, 4, 2],
                [4, nil, nil, 4, nil, nil, 4],
                [2, 2, 1, 3, 2, 5, 5, 3],
                [2, nil, nil, 2, nil, nil, 2],
                [2, 4, 2, 2, 1, 5, 1, 1],
                [1, nil, nil, 1, nil, nil, 3],
                [nil, 3, nil, nil, 1, nil, nil, 2],
                [3, 1, 1, 2, 2, 3, 3],
                [nil, 1, nil, nil, 3, nil, nil, 3],
                [1, 2, 2, 1, 1, 4, 4],
                [nil, 1, nil, nil, 1, nil, nil, 3],
                [1, nil, nil, 2, nil, nil, 1],
                [nil, 1, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2028,
            rows: [
                [1, 3, 3, 2, 1, 1, 1, 3],
                [2, 1, 1, 2, 2, 2, 2],
                [2, 3, 2, 2, 2, 3, 3, 1],
                [1, 1, 1, 1, 3, 2, 3],
                [1, 1, 1, 5, 5, 3, 6, 4],
                [1, 3, 4, 3, 4, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2029,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, 1, 3, nil, nil, nil, nil],
                [6, 3, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, 4, 1, nil],
                [4, 1, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 3, nil],
                [nil, nil, nil, 2, 3, nil, 2, 3],
                [nil, 2, 1, nil, nil, nil, nil],
                [nil, nil, nil, 4, 4, nil, 2, 3],
                [nil, 2, 1, nil, nil, nil, nil],
                [1, 4, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, 3, 4, nil],
                [3, 3, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 3, 4, nil],
                [nil, nil, nil, nil, nil, nil, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2030,
            rows: [
                [nil, 1, 2, 5, 2, 1, 1, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 2, nil, nil, nil, nil, 3, nil],
                [1, 5, 5, 6, 4, 4, 1],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [2, 1, 2, 3, 4, 1, 3],
                [nil, 1, 2, 1, 1, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 4, 3, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2031,
            rows: [
                [1, 3, nil, nil, nil, nil, 1, 5],
                [5, 3, 2, 2, 1, 4, 3],
                [3, 1, nil, nil, nil, nil, 2, 1],
                [2, 4, 4, 3, 1, 2, 1],
                [1, 1, nil, nil, nil, nil, 2, 6],
                [3, 3, 3, 1, 1, 2, 1],
                [1, 2, nil, nil, nil, nil, 4, 4],
                [1, 1, 4, 1, 1, 1, 2],
                [2, 2, nil, nil, nil, nil, 1, 1],
                [1, 2, 2, 1, 5, 5, 1],
                [2, 4, nil, nil, nil, nil, 3, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 2, nil, nil, nil, nil, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2032,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 3],
                [2, 1, 1, 3, 1, 3, 3],
                [3, nil, nil, nil, nil, nil, nil, 1],
                [1, 1, 6, 2, 4, 1, 1],
                [5, nil, nil, nil, nil, nil, nil, 5],
                [5, 2, 2, 3, 3, 3, 1],
                [4, nil, nil, nil, nil, nil, nil, 4],
                [4, 1, 1, 2, 1, 1, 2],
                [2, nil, nil, nil, nil, nil, nil, 7],
                [4, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2033,
            rows: [
                [2, 2, nil, 2, 1, nil, 1, 2],
                [1, 2, nil, 1, nil, 1, 5],
                [nil, 3, nil, 1, 3, nil, 1, nil],
                [3, 3, 1, 1, 2, 3, 1],
                [nil, 2, nil, 1, 2, nil, 1, nil],
                [1, 1, 1, 2, 4, 1, 1],
                [nil, 1, nil, 1, 2, nil, 6, nil],
                [3, 2, nil, nil, nil, 3, 3],
                [nil, 3, nil, 2, 1, nil, 6, nil],
                [2, 1, nil, nil, nil, 2, 1],
                [2, 2, 2, nil, nil, 2, 4, 4],
                [2, 2, nil, nil, nil, 1, 2],
                [1, 2, 1, nil, nil, 2, 2, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2034,
            rows: [
                [nil, 1, 2, nil, 1, 2, nil, nil],
                [1, nil, 3, 1, nil, 4, nil],
                [3, nil, nil, nil, nil, nil, 7, nil],
                [1, 1, 3, nil, nil, 1, 3],
                [3, nil, nil, nil, nil, nil, 3, nil],
                [1, 3, 2, nil, nil, 1, 4],
                [nil, 2, 1, 1, 4, 2, 2, 2],
                [nil, 1, 2, nil, nil, 1, 1],
                [nil, 1, 2, 1, 1, 5, 1, 2],
                [nil, 1, 1, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2035,
            rows: [
                [nil, 1, 3, nil, nil, 1, 1, nil],
                [2, 3, nil, nil, 4, 4, nil],
                [nil, 4, 2, nil, nil, 1, 2, nil],
                [1, 2, nil, nil, 6, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [2, nil, 2, nil, 3, nil, 2, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [1, nil, 2, nil, 1, nil, 1, nil],
                [nil, 3, nil, 3, nil, 2, nil],
                [1, nil, 1, nil, 1, nil, 3, nil],
                [nil, 3, nil, 3, nil, 1, nil],
                [4, nil, 1, nil, 2, nil, 2, nil],
                [nil, 3, nil, 2, nil, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2036,
            rows: [
                [nil, nil, 1, 3, 5, nil, nil, nil],
                [nil, nil, 5, 5, 1, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 3, nil, 2, nil, 3, nil],
                [nil, 3, nil, 1, nil, 2, nil],
                [1, nil, 2, nil, 5, nil, 3, nil],
                [nil, 1, nil, 4, nil, 4, nil],
                [4, nil, 2, nil, 2, nil, 1, nil],
                [nil, 2, nil, 3, nil, 1, nil],
                [2, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 5, nil, 2, nil],
                [1, nil, 3, nil, 1, nil, 2, nil],
                [nil, 1, nil, 1, nil, 5, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2037,
            rows: [
                [nil, nil, nil, 6, 2, 1, 2, nil],
                [3, 3, 3, nil, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [2, nil, nil, nil, nil, nil, 3],
                [3, nil, nil, nil, nil, nil, nil, 1],
                [3, nil, nil, nil, nil, nil, 1],
                [3, nil, nil, nil, 4, 3, 1, 1],
                [4, nil, nil, 2, 1, 2, 6],
                [1, nil, nil, nil, 3, 1, 4, 4],
                [2, nil, nil, 1, 1, 3, 3],
                [3, nil, nil, nil, 2, 1, 6, 1],
                [2, 2, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 2, 1, 6, 1],
                [2, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2038,
            rows: [
                [6, 1, 3, 1, 2, 1, 2, 1],
                [4, nil, nil, nil, nil, nil, 1],
                [2, nil, nil, 5, 5, 1, 4, 4],
                [3, nil, nil, nil, 1, 3, 3],
                [3, nil, nil, 2, 2, 1, 3, 6],
                [3, nil, nil, nil, 3, 1, 5],
                [5, nil, nil, nil, nil, nil, 1, 4],
                [2, 2, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, 2, 1],
                [4, 1, nil, nil, nil, nil, nil],
                [2, 1, 1, 1, nil, nil, nil, nil],
                [4, 1, 1, 1, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2039,
            rows: [
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [1, nil, nil, 2, nil, nil, 2],
                [2, 3, 1, 3, 3, 2, 2, 4],
                [4, nil, nil, 6, nil, nil, 2],
                [2, 3, 3, 1, 5, 2, 1, 1],
                [2, nil, nil, 3, nil, nil, 2],
                [nil, 1, nil, 1, nil, nil, 2, nil],
                [nil, nil, 1, 2, nil, nil, nil],
                [nil, 2, nil, 1, nil, nil, 1, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, 2, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2040,
            rows: [
                [nil, 5, nil, nil, nil, nil, 4, nil],
                [nil, 4, nil, nil, nil, 4, nil],
                [nil, nil, 1, 2, 2, 3, nil, nil],
                [nil, nil, 3, nil, 4, nil, nil],
                [nil, nil, 4, 1, 2, 2, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [1, 1, 2, nil, nil, 5, 3, 5],
                [nil, nil, 2, nil, 2, nil, nil],
                [1, 1, 2, nil, nil, 2, 2, 1],
                [nil, nil, 1, nil, 3, nil, nil],
                [nil, nil, 2, 2, 1, 3, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, nil, 1, 1, 2, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
    ]
}
