// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch129 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2561,
            rows: [
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [nil, 3, nil, nil, nil, 4, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, 3, 1, 2, 1, nil, nil],
                [nil, nil, 3, nil, 1, nil, nil],
                [3, 1, 3, nil, nil, 1, 2, 3],
                [nil, nil, 2, nil, 1, nil, nil],
                [6, 1, 2, nil, nil, 1, 2, 3],
                [nil, nil, 2, nil, 5, nil, nil],
                [nil, nil, 1, 4, 1, 5, nil, nil],
                [nil, 1, nil, nil, nil, 4, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2562,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 3],
                [2, nil, 2, 2, 2, nil, 1],
                [nil, 4, 1, nil, nil, 1, 3, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 1, 3, nil, nil, 3, 2, nil],
                [nil, 5, nil, nil, nil, 3, nil],
                [nil, 2, 1, nil, nil, 3, 5, nil],
                [nil, 1, nil, nil, nil, 4, nil],
                [nil, 2, 1, nil, nil, 3, 1, nil],
                [nil, 2, nil, nil, nil, 3, nil],
                [nil, nil, 1, nil, nil, 3, nil, nil],
                [nil, nil, 1, 2, 6, nil, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2563,
            rows: [
                [nil, nil, 1, 3, 4, nil, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, nil, 4, nil, 1, nil, 2, nil],
                [nil, 1, nil, 2, nil, 4, nil],
                [2, nil, 1, nil, 2, nil, 4, nil],
                [nil, 1, nil, 3, nil, 2, nil],
                [1, nil, 4, nil, 3, nil, 1, nil],
                [nil, 4, nil, 5, nil, 4, nil],
                [1, nil, 4, nil, 4, nil, 2, nil],
                [nil, 2, nil, 4, nil, 2, nil],
                [4, nil, 3, nil, 1, nil, 3, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2564,
            rows: [
                [nil, 2, 5, 3, 2, 1, 4, nil],
                [2, nil, nil, nil, nil, nil, 5],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [2, 2, 3, 3, 3, 1, 2],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [1, 5, 1, 7, 1, 1, 4],
                [nil, 2, 1, 3, 1, 2, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 2, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2565,
            rows: [
                [nil, nil, 1, 2, 4, nil, nil, nil],
                [nil, 2, nil, nil, 6, nil, nil],
                [nil, nil, 2, 1, 2, 4, 1, nil],
                [nil, 3, 1, 2, nil, nil, 1],
                [nil, nil, 4, 4, 2, 5, 1, nil],
                [nil, 2, 1, 3, nil, nil, 3],
                [nil, 2, nil, nil, 4, 2, 2, nil],
                [nil, 2, 1, 4, 2, 1, nil],
                [nil, 7, nil, nil, 4, 1, 2, nil],
                [nil, 1, 4, 1, 4, 1, nil],
                [nil, nil, 5, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2566,
            rows: [
                [1, nil, nil, nil, 2, nil, nil, nil],
                [2, nil, nil, nil, 1, nil, nil],
                [nil, 7, nil, nil, 1, 3, nil, nil],
                [nil, 5, nil, 1, nil, 1, nil],
                [nil, 2, nil, nil, 1, 2, nil, nil],
                [nil, 1, nil, 3, nil, 1, nil],
                [nil, 7, nil, nil, 3, 5, nil, nil],
                [4, nil, nil, 2, 3, 2, nil],
                [nil, 1, nil, nil, 4, 2, nil, nil],
                [1, nil, nil, 4, 2, 1, nil],
                [2, nil, nil, nil, 4, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 3, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2567,
            rows: [
                [1, 6, nil, nil, nil, nil, 2, 3],
                [2, 3, nil, nil, nil, 1, 3],
                [1, 2, nil, nil, nil, nil, 1, 2],
                [5, nil, nil, nil, nil, nil, 5],
                [1, 2, nil, nil, nil, nil, 1, 2],
                [1, nil, nil, nil, nil, nil, 2],
                [1, 1, nil, nil, nil, nil, 2, 1],
                [3, nil, nil, nil, nil, nil, 3],
                [2, 1, nil, nil, nil, nil, 2, 1],
                [2, nil, nil, nil, nil, nil, 1],
                [2, 2, nil, nil, nil, nil, 1, 2],
                [1, 2, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2568,
            rows: [
                [1, 2, 7, 1, 2, 5, 2, 1],
                [4, 1, 2, 2, 6, 1, 2],
                [2, 3, 1, 3, 1, 4, 5, 1],
                [2, 3, 1, 4, 1, 2, 2],
                [5, 1, 3, 2, 1, 2, 3, 2],
                [1, 1, 2, 1, 2, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2569,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 5],
                [2, 1, 2, 1, 2, 1, 7],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [6, 3, 1, 2, 1, 2, 1],
                [2, nil, nil, nil, nil, nil, nil, 5],
                [2, 1, 5, 1, 3, 1, 2],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [4, 1, 2, 4, 2, 1, 3],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [1, 2, 1, 3, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2570,
            rows: [
                [nil, 1, 2, nil, nil, 1, 1, nil],
                [nil, 3, nil, nil, nil, 2, nil],
                [nil, 3, nil, nil, nil, 4, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 4, nil, nil, nil, 1, nil, nil],
                [nil, 4, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 7, nil],
                [nil, 3, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, nil, 5, nil, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2571,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 2, 3, 1, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, 1, 3, nil, 1, 4, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, 4, 1, nil, 4, 1, nil],
                [nil, 6, 2, 2, 7, 5, 1, nil],
                [nil, 3, 1, nil, 2, 3, nil],
                [nil, 1, 2, 1, 2, 3, 1, nil],
                [nil, 1, 3, nil, 4, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2572,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 3, 1, 1, 3, nil, nil],
                [nil, 2, 2, 6, 1, 3, nil],
                [nil, nil, 2, 2, 1, 7, nil, nil],
                [nil, 2, 3, 2, 1, 5, nil],
                [nil, nil, 5, 3, 2, 1, nil, nil],
                [nil, nil, 4, 2, 2, nil, nil],
                [nil, nil, 3, 3, 1, 2, nil, nil],
                [nil, nil, 3, 1, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2573,
            rows: [
                [1, 4, nil, 1, 2, nil, 1, 2],
                [1, nil, nil, 2, nil, nil, 1],
                [1, nil, nil, 2, nil, nil, 1, nil],
                [2, nil, nil, 3, nil, nil, 2],
                [1, nil, nil, 2, nil, nil, 5, nil],
                [1, nil, nil, 3, nil, nil, 2],
                [2, nil, nil, 3, nil, nil, 3, nil],
                [1, nil, nil, 1, nil, nil, 3],
                [3, nil, nil, 2, nil, nil, 1, nil],
                [1, nil, nil, 6, nil, nil, 4],
                [1, nil, nil, 4, nil, nil, 1, nil],
                [4, nil, nil, 2, nil, nil, 1],
                [4, nil, nil, 7, nil, nil, 4, nil],
                [2, nil, nil, 5, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2574,
            rows: [
                [nil, 1, 2, 5, 2, 3, 3, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, 3, nil, nil, nil, nil, 2, nil],
                [1, 4, 1, 2, 1, 2, 1],
                [nil, 4, nil, nil, nil, nil, 2, nil],
                [1, 4, 5, 1, 5, 2, 1],
                [nil, 2, 2, 1, 2, 1, 2, nil],
                [nil, 1, 6, 4, 2, 1, nil],
                [nil, 2, 1, 2, 1, 2, 3, nil],
                [nil, 2, 1, 2, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2575,
            rows: [
                [nil, 1, 2, nil, nil, 1, 5, nil],
                [5, 2, nil, nil, 1, 3, nil],
                [nil, 1, 2, nil, nil, 1, 4, nil],
                [1, 3, nil, nil, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 3, nil, 1, nil, 2, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [5, nil, 1, nil, 3, nil, 1, nil],
                [nil, 1, nil, 6, nil, 1, nil],
                [3, nil, 2, nil, 1, nil, 3, nil],
                [nil, 1, nil, 3, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2576,
            rows: [
                [nil, 1, 2, 3, 6, 1, 1, nil],
                [nil, 2, 3, 2, 1, 4, nil],
                [nil, nil, 3, 1, 4, 1, nil, nil],
                [nil, nil, 5, 1, 2, nil, nil],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 4, nil, nil, nil, nil, nil, nil],
                [1, 3, nil, nil, nil, nil, nil],
                [nil, 1, 4, nil, nil, nil, nil, nil],
                [nil, 3, 2, nil, nil, nil, nil],
                [nil, nil, 3, 2, nil, nil, nil, nil],
                [nil, nil, 3, 2, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2577,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [1, 7, 1, 2, 4, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 1, 3, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2578,
            rows: [
                [nil, 3, nil, 2, nil, 3, nil, 4],
                [2, 1, nil, 1, 2, nil, 3],
                [1, nil, 3, nil, 3, nil, 3, nil],
                [3, 2, nil, 2, 1, nil, 1],
                [2, nil, 1, nil, 3, nil, 1, nil],
                [2, 1, nil, 2, 3, nil, 6],
                [nil, 1, nil, 1, nil, 2, nil, 3],
                [2, 2, nil, 3, 4, nil, 4],
                [nil, 4, nil, 1, nil, 3, nil, 3],
                [3, 2, nil, 1, 2, nil, 1],
                [2, nil, 1, nil, 2, nil, 1, nil],
                [2, 1, nil, 2, 2, nil, 1],
                [2, nil, 1, nil, 2, nil, 1, nil],
                [5, 2, nil, 1, 2, nil, 1],
                [nil, 2, nil, 2, nil, 1, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2579,
            rows: [
                [nil, nil, 2, nil, nil, 3, nil, nil],
                [nil, 5, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, 3, 1, 5, nil],
                [6, nil, nil, nil, nil, 1, nil],
                [nil, 4, nil, nil, 3, 1, 2, nil],
                [1, nil, nil, nil, nil, 5, nil],
                [2, 5, 1, 3, nil, 2, nil, nil],
                [nil, nil, 5, nil, nil, nil, nil],
                [2, 5, 3, 4, nil, 4, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2580,
            rows: [
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, 4, 1, 2, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 3, 6, 1, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, 1, 3, 5, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 3, 1, 3, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 4, 3, 1, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 7, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
    ]
}
