// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch76 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1501,
            rows: [
                [nil, nil, 2, 2, 2, nil, nil, nil],
                [nil, 1, 1, 1, 2, nil, nil],
                [nil, 1, 3, 3, 1, 3, nil, nil],
                [2, 3, 7, 3, 1, 3, nil],
                [nil, 2, 1, 1, 3, 1, nil, nil],
                [5, 3, 5, 3, 3, 2, nil],
                [nil, nil, 2, nil, 1, nil, nil, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, 5, nil, 1, nil, nil, nil],
                [nil, 2, nil, nil, 1, nil, nil],
                [nil, 1, 2, 1, nil, 2, 5, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 2, nil, 1, 1, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1502,
            rows: [
                [nil, nil, 3, nil, nil, 3, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 1, 6, 6, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 4, 1, 2, nil, nil],
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, nil, 2, 4, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 5, 2, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1503,
            rows: [
                [2, nil, nil, 6, nil, 1, nil, 2],
                [3, 5, 3, nil, nil, 1, 1],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 2, 4, 3, 1, 2, 2],
                [nil, nil, 2, nil, nil, 1, nil, nil],
                [nil, 2, 5, 2, 2, 2, 1],
                [nil, nil, 5, 3, 3, 2, 1, 2],
                [nil, nil, 1, 1, 2, 3, 2],
                [nil, nil, 1, 2, 4, 1, 1, 2],
                [nil, nil, 1, 1, 3, 1, 1],
                [nil, nil, nil, 1, 5, nil, 1, 1],
                [nil, nil, nil, 4, nil, 1, 5],
                [nil, nil, nil, 4, 1, nil, 1, 2],
                [nil, nil, nil, 2, nil, 3, 5],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1504,
            rows: [
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 2, 1, 1, 3, nil, nil],
                [nil, 3, 5, 5, 2, 1, nil],
                [nil, nil, 4, 1, 5, 5, nil, nil],
                [nil, 6, 1, 1, 2, 2, nil],
                [nil, 2, nil, 2, 1, nil, 3, nil],
                [3, 3, 3, 4, 1, 1, 3],
                [nil, 3, nil, 1, 1, nil, 1, nil],
                [1, 3, 3, 6, 1, 2, 4],
                [nil, 1, nil, 1, 2, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, 1, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1505,
            rows: [
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [nil, 4, 4, 1, 3, 4, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, 2, 4, 1, 2, 2],
                [nil, 1, nil, nil, nil, nil, 5],
                [nil, 4, 1, 2, 2, 2, 3, 1],
                [nil, 1, nil, nil, nil, nil, 3],
                [nil, nil, nil, 4, 1, 4, 1, nil],
                [nil, 1, 2, nil, nil, nil, nil],
                [nil, nil, nil, 4, 4, 4, 2, nil],
                [nil, 1, 3, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1506,
            rows: [
                [4, 1, nil, 2, 2, nil, 3, 3],
                [1, nil, nil, 2, nil, nil, 1],
                [3, nil, nil, 3, nil, nil, 1, nil],
                [2, nil, nil, 2, nil, nil, 2],
                [1, nil, nil, 5, nil, nil, 2, nil],
                [2, nil, nil, 2, nil, nil, 2],
                [4, nil, nil, 5, nil, nil, 1, nil],
                [2, nil, nil, 3, nil, nil, 1],
                [5, nil, nil, 1, nil, nil, 4, nil],
                [6, nil, nil, 1, nil, nil, 3],
                [1, nil, nil, 3, nil, nil, 3, nil],
                [1, nil, nil, 4, nil, nil, 1],
                [1, nil, nil, 2, nil, nil, 2, nil],
                [1, nil, nil, 1, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1507,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 5, nil, nil, 5, nil, 3, nil],
                [1, nil, nil, 3, nil, nil, 1],
                [nil, 1, nil, nil, 1, nil, 2, nil],
                [1, nil, nil, 2, nil, nil, 2],
                [nil, 2, nil, nil, 2, nil, 1, nil],
                [nil, 3, nil, 2, nil, 3, nil],
                [nil, 2, nil, nil, 5, nil, 1, nil],
                [nil, 4, nil, 1, nil, 5, nil],
                [nil, nil, 1, 1, 1, 5, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1508,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, 2, 3, 3, 2, 2, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 3, 1, 1, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 5, 1, 2, nil, nil],
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, 1, 1, 3, 2, 1, nil],
                [nil, nil, nil, 6, 1, nil, nil, nil],
                [nil, 4, 2, 1, 2, 2, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1509,
            rows: [
                [nil, nil, nil, 6, 1, nil, nil, nil],
                [nil, nil, 3, 2, 2, 2, nil],
                [nil, nil, nil, 2, 1, 3, nil, nil],
                [nil, 3, 1, 1, 1, nil, nil],
                [nil, nil, nil, 3, 5, 5, nil, nil],
                [nil, 5, 1, 6, 2, nil, nil],
                [nil, 2, 4, 4, 3, 1, nil, nil],
                [2, 3, 1, 2, 1, 2, nil],
                [nil, 1, 2, 2, 1, 3, nil, nil],
                [1, 4, 1, 1, 3, 1, nil],
                [nil, 2, 1, 3, 1, 2, nil, nil],
                [nil, 1, 2, 1, 2, 2, nil],
                [nil, 1, 3, 1, 2, 1, nil, nil],
                [nil, 1, 1, 3, 2, 4, nil],
                [nil, nil, 2, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1510,
            rows: [
                [nil, 2, nil, 2, nil, 1, nil, nil],
                [nil, 2, nil, 1, nil, 4, nil],
                [nil, 4, nil, 2, nil, 1, nil, nil],
                [nil, 2, nil, 1, nil, 2, nil],
                [nil, 1, nil, 2, nil, 2, nil, nil],
                [nil, 4, nil, 4, nil, 4, nil],
                [nil, 3, nil, 3, nil, 1, nil, nil],
                [nil, 6, nil, 1, nil, 2, nil],
                [nil, 1, nil, 2, nil, 1, nil, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [nil, 2, nil, 4, nil, 2, nil, nil],
                [nil, 1, nil, 1, nil, 4, nil],
                [nil, 1, nil, 1, nil, 3, nil, nil],
                [nil, 2, nil, 3, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1511,
            rows: [
                [nil, 4, 4, 2, 5, 1, 2, nil],
                [1, nil, nil, nil, nil, nil, 3],
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [3, 1, 3, 1, 3, 3, 1],
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [3, 1, 4, 1, 1, 4, 1],
                [nil, 4, 2, 2, 2, 2, 3, nil],
                [nil, 4, 5, 1, 4, 4, nil],
                [nil, 1, 4, 1, 1, 6, 1, nil],
                [nil, 1, 2, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1512,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 6, 2, 1, 2, nil, nil],
                [nil, 1, 1, 2, 1, 2, nil],
                [nil, nil, 3, 2, 1, 2, nil, nil],
                [nil, 1, 5, 2, 4, 5, nil],
                [nil, 6, 1, 2, 1, 3, 1, nil],
                [2, 1, 1, 1, 3, 2, 3],
                [nil, 3, 2, 1, 3, 1, 1, nil],
                [2, 2, 1, 4, 4, 1, 2],
                [nil, 1, 2, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1513,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 6],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil],
                [nil, nil, 2, 1, 3, 1, nil, nil],
                [nil, 4, 4, 1, 3, 2, nil],
                [nil, 2, 3, 3, 2, 1, 1, nil],
                [nil, 4, 1, 1, 3, 1, nil],
                [nil, nil, 1, 2, 1, 2, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 2, 4, 2, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1514,
            rows: [
                [nil, 1, 4, nil, nil, 1, 1, nil],
                [2, 1, 2, 1, 5, 4, 4],
                [5, 5, 1, 5, 4, 1, 3, 4],
                [5, 2, 1, 1, 1, 3, 2],
                [1, 6, 1, 2, 1, 1, 1, 1],
                [2, 2, 5, 1, 1, 1, 4],
                [nil, 1, 1, nil, nil, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 2, nil, nil, 3, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1515,
            rows: [
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 3, 1, 3, 3, 1, nil],
                [nil, nil, nil, nil, nil, nil, 5],
                [nil, 4, 1, 2, 2, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, 4, 1, 1, 1, 3, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, 3, 1, 3, 3, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 6, 1, 3, 1, 4, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1516,
            rows: [
                [1, nil, nil, 4, 1, nil, nil, 3],
                [4, nil, 2, nil, 2, nil, 1],
                [nil, 6, 1, nil, nil, 4, 4, nil],
                [2, 2, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, nil, 4, 1, nil],
                [5, 5, nil, nil, nil, 1, 1],
                [1, nil, 4, 4, 2, 1, nil, 2],
                [1, 4, nil, nil, nil, 4, 2],
                [2, nil, 1, 3, 1, 1, nil, 2],
                [2, 4, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, nil, 1, 4, nil],
                [4, nil, 1, nil, 3, nil, 3],
                [nil, 1, 3, nil, nil, 1, 3, nil],
                [3, nil, 3, nil, 1, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1517,
            rows: [
                [nil, nil, nil, nil, 2, 1, 4, 4],
                [1, 4, 4, 4, 4, 5, 5],
                [1, 3, 3, 1, 3, 3, 1, 3],
                [1, 1, 2, 2, 1, 2, 2],
                [1, 6, 6, 1, 2, 1, 1, 2],
                [1, 2, 1, 1, 1, 3, 3],
                [nil, nil, nil, nil, 1, 2, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1518,
            rows: [
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [5, 1, 2, 2, 2, 1, 3],
                [nil, nil, 1, 4, 3, 4, nil, nil],
                [nil, 1, 1, 1, 5, 2, nil],
                [nil, nil, 1, 1, 2, 4, nil, nil],
                [nil, 1, 1, 2, 1, 3, nil],
                [nil, nil, nil, 3, 4, nil, nil, nil],
                [nil, nil, 6, 7, 2, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1519,
            rows: [
                [2, nil, nil, nil, nil, nil, nil, 2],
                [5, nil, 5, 2, 2, nil, 3],
                [nil, 2, 3, nil, nil, 2, 2, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, 4, 1, nil, nil, 1, 2, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, 2, nil, nil, 2, 3, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 2, 1, nil, nil, 7, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, nil, 4, nil, nil, 3, nil, nil],
                [nil, nil, 1, 3, 3, nil, nil],
                [nil, nil, 7, nil, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1520,
            rows: [
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, 3, 7, nil, 1, 1, nil],
                [nil, nil, 1, 4, 1, 1, nil, nil],
                [nil, 3, 4, nil, 2, 3, nil],
                [nil, 4, 4, nil, nil, 4, 1, nil],
                [1, 1, nil, nil, nil, 4, 4],
                [nil, 3, 3, nil, nil, 3, 2, nil],
                [1, 1, nil, nil, nil, 2, 1],
                [1, 2, nil, nil, nil, nil, 1, 1],
                [6, nil, nil, nil, nil, nil, 1],
                [2, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
    ]
}
