// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch67 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1321,
            rows: [
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [2, nil, 2, nil, 2, nil, 3],
                [4, nil, nil, 4, 4, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [2, nil, nil, 2, 1, nil, nil, 6],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 5, nil, nil, nil, nil, 5, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 6, nil, 3, nil, nil],
                [nil, nil, 3, nil, nil, 3, nil, nil],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1322,
            rows: [
                [4, 2, 1, 4, 4, 1, 3, 1],
                [3, 1, 1, 2, 2, 1, 5],
                [1, 1, 4, 2, 2, 1, 1, 2],
                [2, 3, 5, 2, 1, 2, 1],
                [5, 3, 1, 3, 3, 1, 3, 1],
                [2, 3, 1, 1, 2, 1, 1],
                [2, 1, 3, 3, 2, 2, 6, 2],
                [1, 2, 2, 1, 1, 1, 2],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1323,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil],
                [nil, nil, nil, nil, 1, 2, nil, nil],
                [nil, nil, nil, nil, 1, 4, nil],
                [nil, nil, nil, nil, nil, 1, 3, nil],
                [nil, nil, nil, nil, nil, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 6, nil, nil, 2, 3, nil],
                [1, 1, nil, nil, 2, 2, nil],
                [nil, 1, 3, nil, nil, 3, 1, nil],
                [1, 3, nil, nil, 3, 2, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, 4, 6, nil],
                [nil, 2, 1, nil, nil, 3, 3, nil],
                [4, 1, nil, nil, 4, 4, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1324,
            rows: [
                [nil, nil, nil, nil, 3, nil, nil, nil],
                [1, 2, 1, 5, nil, nil, nil],
                [3, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, 3, 2, 3],
                [1, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, 3, 1],
                [3, nil, nil, nil, 7, nil, nil, 4],
                [2, 1, 1, 5, nil, nil, nil],
                [3, nil, nil, nil, 1, nil, nil, 3],
                [2, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, 2],
                [nil, nil, nil, 3, 2, 2, 4],
                [nil, nil, nil, 4, nil, nil, nil, 2],
                [nil, nil, nil, 2, 2, 5, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1325,
            rows: [
                [3, 3, 1, 2, 1, 2, 1, 3],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 2, 3, 4, 4, 3, 3, 3],
                [nil, 3, nil, nil, nil, nil, nil],
                [nil, 3, 1, 1, 2, 2, 2, 2],
                [nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 1, 5, 4, 1],
                [nil, nil, 6, nil, nil, nil, nil],
                [nil, nil, 6, 1, 2, 1, 1, 1],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1326,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 5, 1, 6, 4, nil, nil],
                [nil, nil, 4, 4, 1, nil, nil],
                [nil, nil, 5, 2, 2, 1, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, 1, 1, 2, 3, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil],
                [nil, nil, 5, 2, 2, 1, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, 2, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1327,
            rows: [
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [nil, 1, 3, 3, 3, 2, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 2, 4, 1, 1, 5, 5, 2],
                [nil, 1, nil, nil, nil, nil, 1],
                [nil, 2, 1, 1, 2, 2, 4, 1],
                [nil, 1, nil, nil, nil, nil, 2],
                [nil, nil, nil, 2, 2, 4, 1, nil],
                [nil, 5, 4, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1328,
            rows: [
                [nil, 2, 2, 3, 3, 3, 4, nil],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 3, nil, nil, nil, nil, 1, nil],
                [1, 2, 1, 5, 2, 5, 5],
                [nil, 2, nil, nil, nil, nil, 3, nil],
                [2, 1, 6, 1, 1, 1, 3],
                [nil, 1, 1, 3, 3, 2, 3, nil],
                [nil, 4, 6, 1, 2, 1, nil],
                [nil, 2, 2, 1, 4, 1, 4, nil],
                [nil, 1, 1, 1, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1329,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, 3, 3, nil, nil],
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, 4, 1, 1, 2, 1, nil],
                [nil, nil, 1, 3, 3, 1, nil, nil],
                [nil, 3, 1, 2, 2, 1, nil],
                [nil, 3, 1, 1, 3, 3, 2, nil],
                [1, 2, 2, 1, 1, 1, 1],
                [nil, 2, 1, 2, 1, 2, 1, nil],
                [5, 2, 2, 1, 1, 1, 2],
                [nil, 1, 1, 2, 5, 2, 3, nil],
                [nil, 2, 5, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1330,
            rows: [
                [2, nil, nil, 1, 1, nil, nil, 4],
                [3, nil, 1, nil, 1, nil, 1],
                [nil, 4, 1, nil, nil, 1, 1, nil],
                [2, 2, nil, nil, nil, 2, 2],
                [nil, 1, 1, nil, nil, 3, 1, nil],
                [3, 1, nil, nil, nil, 2, 1],
                [3, nil, 1, 4, 1, 1, nil, 3],
                [1, 3, nil, nil, nil, 3, 3],
                [1, nil, 1, 1, 5, 2, nil, 1],
                [3, 4, nil, nil, nil, 2, 2],
                [nil, 3, 3, nil, nil, 4, 3, nil],
                [4, nil, 1, nil, 2, nil, 2],
                [nil, 3, 1, nil, nil, 1, 3, nil],
                [1, nil, 3, nil, 3, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 4],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1331,
            rows: [
                [1, 2, 1, 4, 1, 3, 1, 2],
                [nil, nil, nil, nil, nil, nil, 4],
                [1, 1, 3, 2, 1, 2, 2, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [2, 1, 6, 1, 4, 4, 1, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [2, 2, 1, 4, 1, 2, 4, 1],
                [nil, nil, nil, nil, nil, nil, 1],
                [4, 4, 1, 2, 3, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, 1],
                [3, 3, 3, 1, 4, 1, 3, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [2, 2, 1, 1, 1, 2, 1, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 5, 1, 5, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1332,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 1, 4, 1, nil, nil],
                [nil, nil, 3, 4, 1, 1, nil, nil],
                [nil, 1, 3, 2, 1, 2, nil],
                [nil, nil, 2, 2, 4, 3, nil, nil],
                [nil, 2, 2, 1, 1, 1, nil],
                [nil, 2, 5, 3, 1, 1, 3, nil],
                [2, 4, 2, 2, 3, 3, 2],
                [nil, 2, 4, 2, 1, 3, 2, nil],
                [2, 3, 3, 1, 1, 1, 4],
                [4, 2, 2, 2, 4, 1, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 1, 2, 1, 1, 1, 1, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1333,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 3, 2, nil, nil],
                [nil, nil, 1, 2, 1, 3, nil, nil],
                [nil, 1, nil, 2, nil, 3, nil],
                [nil, nil, 3, 3, 2, 1, nil, nil],
                [nil, 3, nil, 3, nil, 2, nil],
                [1, nil, nil, 1, 3, nil, nil, 2],
                [7, 1, nil, 2, nil, 2, 3],
                [4, nil, nil, 5, 1, nil, nil, 3],
                [5, 2, nil, 1, nil, 2, 2],
                [nil, 1, 1, 1, 1, 1, 4, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 2, 1, 1, 1, 2, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1334,
            rows: [
                [3, 1, 2, 1, 1, 1, 1, 1],
                [1, 3, 3, 1, 1, 3, 5],
                [5, 1, 4, 1, 1, 1, 1, 1],
                [3, 3, 2, 2, 1, 2, 4],
                [1, 2, 2, 4, 2, 1, 2, 1],
                [2, 1, 1, 4, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1335,
            rows: [
                [nil, 1, 2, 4, 2, 1, 1, nil],
                [nil, 2, 2, 2, 1, 2, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, nil, 5, 5, 5, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, nil, nil],
                [3, 1, nil, nil, nil, nil, nil],
                [nil, 1, 7, nil, nil, nil, nil, nil],
                [nil, 3, 3, nil, nil, nil, nil],
                [nil, nil, 7, 3, nil, nil, nil, nil],
                [nil, nil, 1, 3, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1336,
            rows: [
                [3, 3, nil, 1, 1, nil, 2, 2],
                [2, 1, nil, 1, nil, 1, 1],
                [nil, 3, nil, 3, 2, nil, 2, nil],
                [3, 3, 2, 4, 2, 3, 1],
                [nil, 1, nil, 1, 3, nil, 2, nil],
                [3, 1, 3, 1, 2, 2, 2],
                [nil, 2, nil, 1, 3, nil, 3, nil],
                [1, 1, nil, nil, nil, 3, 3],
                [nil, 1, nil, 2, 1, nil, 3, nil],
                [1, 1, nil, nil, nil, 1, 2],
                [4, 3, 3, nil, nil, 2, 1, 2],
                [1, 2, nil, nil, nil, 1, 1],
                [4, 1, 2, nil, nil, 1, 3, 3],
                [3, 5, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1337,
            rows: [
                [nil, nil, 1, 3, 1, 2, nil, nil],
                [nil, nil, 2, 3, 4, nil, nil],
                [nil, nil, 4, 2, 2, 2, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, 1, 1, 4, 4, nil, nil],
                [nil, nil, 1, 1, 6, nil, nil],
                [nil, nil, 3, 2, 1, 3, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, 1, 5, 2, 2, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 1, 1, 2, 1, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 2, 1, 3, 3, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 1, 1, 3, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1338,
            rows: [
                [nil, nil, nil, 6, 5, nil, nil, nil],
                [nil, nil, 5, nil, nil, nil, nil],
                [nil, 1, 2, 2, 1, nil, nil, 1],
                [1, 4, 2, 2, 1, nil, 3],
                [nil, 3, 2, 2, 5, nil, nil, 5],
                [2, 2, 1, 2, 3, nil, 1],
                [4, 3, 2, 2, 2, 2, 2, nil],
                [1, 3, 1, 2, 1, nil, 2],
                [3, 3, 3, 1, 4, 1, 2, nil],
                [2, 1, 4, 1, 1, nil, 1],
                [nil, 2, 2, 1, 5, nil, nil, 1],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil, 1],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1339,
            rows: [
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [3, 2, 2, 1, 1, 1, 1],
                [1, 5, 4, 4, 2, 1, 2, 1],
                [3, 1, nil, 3, nil, 1, 3],
                [2, 1, 2, 1, 2, 2, 4, 4],
                [3, 3, nil, 2, nil, 3, 2],
                [5, 2, nil, 1, 5, nil, 3, 3],
                [2, nil, nil, 5, nil, nil, 2],
                [2, 2, nil, 1, 2, nil, 1, 2],
                [2, nil, nil, 2, nil, nil, 2],
                [5, 1, 2, nil, nil, 1, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 2, 2, nil, nil, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1340,
            rows: [
                [1, nil, nil, nil, 2, 2, nil, nil],
                [5, nil, nil, 5, 1, 2, nil],
                [2, nil, nil, 3, 2, 3, 2, nil],
                [4, nil, 1, 1, 2, 2, 2],
                [1, nil, nil, 2, 4, 2, 1, nil],
                [5, nil, 4, 3, 1, 3, 5],
                [1, nil, nil, 1, 3, 3, 3, nil],
                [1, nil, nil, 1, 4, 3, nil],
                [1, nil, nil, 3, 1, 1, 1, nil],
                [3, nil, nil, 3, 2, 4, nil],
                [5, nil, nil, nil, 1, 2, nil, nil],
                [nil, nil, nil, 2, 5, 1, nil],
                [3, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
    ]
}
