// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch42 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 821,
            rows: [
                [5, nil, nil, 5, 4, 4, nil, nil],
                [4, nil, 4, nil, nil, nil, 4],
                [4, nil, 4, nil, 4, nil, nil, 4],
                [2, 2, 2, nil, 2, 2, nil],
                [nil, 1, 1, 1, nil, 1, nil, nil],
                [nil, 3, 3, nil, 3, 3, nil],
                [3, 3, 3, nil, 3, 3, nil, nil],
                [nil, nil, nil, 3, nil, 1, 2],
                [2, nil, 1, 1, 6, 6, 1, nil],
                [1, 1, 1, nil, nil, 1, nil],
                [nil, 2, nil, 2, nil, 1, nil, 1],
                [nil, nil, nil, 1, 1, 2, 1],
                [1, nil, 1, 1, nil, nil, nil, nil],
                [1, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, 1, nil],
                [nil, nil, 1, nil, 1, 1, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 822,
            rows: [
                [nil, 1, nil, 1, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1],
                [nil, 1, 1, 2, nil, 2, nil, 2],
                [1, nil, nil, nil, 1, nil, 1],
                [1, 1, nil, 1, 1, nil, 3, 3],
                [6, nil, 6, 6, 2, 1, 1],
                [1, 1, nil, 1, 1, 1, 1, 1],
                [nil, nil, 1, nil, 1, nil, 1],
                [6, 2, 2, 4, 4, 4, 4, nil],
                [4, 2, 2, 2, nil, 2, nil],
                [2, nil, 2, nil, nil, nil, nil, nil],
                [nil, 2, 2, 2, nil, nil, nil],
                [2, nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, 2, 2, nil, 3, 3],
                [2, nil, nil, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 823,
            rows: [
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [1, 5, 5, nil, nil, nil, 5],
                [4, nil, 4, 4, 1, 1, nil, 1],
                [nil, 1, nil, 1, 1, nil, 3],
                [nil, nil, 3, 3, nil, nil, 3, nil],
                [nil, 3, 3, nil, 4, 4, nil],
                [6, nil, nil, nil, nil, nil, 6, 1],
                [nil, 1, 1, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, 1, 1, nil, nil, 1],
                [nil, nil, 1, nil, 1, nil, 1, 1],
                [nil, nil, nil, 1, nil, 2, 2],
                [nil, 2, 2, nil, 2, 2, 2, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, nil, 2, 4, 4, 3, nil],
                [nil, 3, 3, 3, 3, 3, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 824,
            rows: [
                [nil, nil, nil, 1, 1, 1, 3, nil],
                [nil, nil, 3, nil, nil, nil, 3],
                [3, nil, 4, nil, nil, 4, 4, 4],
                [nil, nil, 4, 4, 3, nil, nil],
                [nil, nil, 3, 3, nil, 3, nil, 3],
                [nil, 3, nil, 2, nil, 2, 2],
                [2, nil, 2, 2, nil, nil, 2, 2],
                [nil, 2, nil, 2, 2, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil, 2],
                [nil, 2, nil, 2, 2, 1, nil],
                [nil, 5, nil, nil, 5, 1, nil, nil],
                [nil, nil, nil, 5, nil, 5, nil],
                [nil, nil, nil, nil, 5, 1, nil, 1],
                [1, nil, 1, nil, 1, 1, 1],
                [6, 1, nil, nil, 1, nil, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 825,
            rows: [
                [nil, 2, 2, nil, nil, nil, 2, nil],
                [2, 2, 2, 2, 2, nil, 2],
                [nil, 2, 2, 2, nil, 2, nil, 2],
                [1, nil, nil, nil, nil, 1, 1],
                [nil, 1, nil, 1, nil, 3, 3, nil],
                [1, nil, 1, nil, nil, nil, 1],
                [1, nil, nil, nil, 1, 1, nil, 1],
                [nil, 1, 1, 1, 1, 1, nil],
                [1, nil, 1, nil, 1, 1, nil, nil],
                [1, 5, nil, nil, nil, nil, nil],
                [nil, nil, 5, nil, nil, 3, nil, nil],
                [nil, 3, 3, 3, 2, 6, 6],
                [3, 3, 4, 4, nil, 3, 3, 3],
                [3, 3, 4, 4, 4, 5, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 826,
            rows: [
                [nil, 6, nil, nil, 6, 6, 6, nil],
                [nil, 2, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 2, nil, 2, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, 2, 2, nil, nil, 2, nil],
                [nil, 2, 2, 2, nil, 2, nil],
                [nil, nil, nil, 2, 2, nil, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, nil, 1, nil, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, 1, 1, 1, 4, 4, 4, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 5, 5, 5, nil],
                [nil, 5, nil, 3, nil, 4, nil, 3],
                [3, nil, 3, nil, 1, nil, 1],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 827,
            rows: [
                [nil, 1, 1, nil, 6, 6, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 1, nil, nil, 1, nil, 1, 2],
                [nil, 2, nil, nil, nil, nil, nil],
                [2, 2, nil, nil, 1, 5, 5, nil],
                [5, nil, 5, nil, 1, nil, 4],
                [4, nil, 4, 4, nil, 4, 1, nil],
                [nil, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, 1, nil, 2, 2, nil],
                [nil, 2, 2, 2, nil, 2, 2],
                [2, 2, 1, 2, 2, 2, 3, 3],
                [3, nil, 1, 1, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil, nil],
                [1, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, 3, 3, nil],
                [nil, 3, 1, 1, 1, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 828,
            rows: [
                [3, nil, 3, 3, 3, nil, 3, 3],
                [2, 2, nil, nil, nil, 2, nil],
                [2, nil, 2, nil, 4, 4, nil, 4],
                [4, 4, 5, nil, 5, 1, 1],
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [1, nil, nil, nil, 1, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
                [nil, nil, 2, 2, 1, 5, 5, 5],
                [6, 1, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 3, 1, 1, 1, 1, 1, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 829,
            rows: [
                [nil, 1, nil, nil, 1, 3, nil, nil],
                [nil, 1, nil, nil, 5, nil, nil],
                [nil, 5, nil, nil, 5, 5, 5, nil],
                [nil, nil, 5, nil, 1, 1, nil],
                [nil, 1, 1, nil, 3, nil, 3, nil],
                [nil, nil, 3, nil, 3, nil, nil],
                [nil, 3, 3, nil, 3, 1, 1, nil],
                [nil, 6, 6, 2, 2, nil, nil],
                [nil, 2, 1, 1, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, 2, 1, 4, 4, 4, nil, nil],
                [nil, 2, 2, 2, nil, 1, nil],
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [nil, nil, 1, 1, 2, 2, nil],
                [nil, 2, 2, 1, 1, 3, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 830,
            rows: [
                [3, 3, nil, nil, nil, nil, nil, 3],
                [3, 3, nil, nil, 3, nil, nil],
                [2, nil, nil, nil, 2, 2, nil, 2],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, 1, 1, 5, 5],
                [5, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [1, 1, 1, 1, 1, 4, 4],
                [4, 4, 2, 2, 2, 2, 2, 2],
                [2, 2, 1, 1, 1, 1, 1],
                [1, 1, 1, 4, 4, 6, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 2, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 831,
            rows: [
                [nil, 1, nil, nil, nil, 1, nil, 6],
                [nil, nil, nil, 6, nil, 6, 6],
                [2, 2, 1, nil, 1, 1, nil, 1],
                [1, 1, 1, nil, 1, 2, nil],
                [nil, nil, nil, 2, nil, 2, nil, 4],
                [nil, nil, 4, 1, 1, nil, nil],
                [1, 3, 3, 5, nil, nil, nil, nil],
                [5, 1, 1, 1, nil, 1, 2],
                [nil, 2, 2, 2, nil, 2, 2, 2],
                [2, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, 1, nil, 1, 1, nil],
                [1, nil, 1, nil, nil, 1, 5, nil],
                [nil, 5, nil, nil, nil, 5, 3],
                [nil, nil, 3, nil, 3, 4, nil, nil],
                [nil, nil, nil, 2, 2, 3, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 832,
            rows: [
                [nil, nil, nil, nil, 1, 1, 1, nil],
                [nil, 1, nil, nil, 2, nil, nil],
                [nil, 3, 3, 3, 3, nil, 3, nil],
                [nil, 1, nil, 1, 2, 1, nil],
                [nil, 1, nil, 1, nil, nil, nil, nil],
                [nil, 1, nil, 2, 2, 2, nil],
                [nil, 2, nil, nil, nil, 2, 1, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, nil, 1, 1, nil, nil],
                [nil, 1, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 4, 4, 4, nil],
                [nil, 4, 4, 6, 6, 6, nil],
                [nil, 5, nil, 5, nil, 5, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 833,
            rows: [
                [3, nil, nil, 3, 3, 3, nil, nil],
                [3, nil, 3, nil, nil, nil, 3],
                [3, nil, 3, nil, 3, nil, nil, 2],
                [2, 1, 4, nil, 4, 4, nil],
                [nil, 4, 1, 2, nil, 2, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [5, 1, 1, nil, 1, 1, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1],
                [1, nil, 1, 1, 1, 1, 1, nil],
                [1, 1, 1, nil, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, 1, 1, 1, 4],
                [2, nil, 5, 2, nil, nil, nil, nil],
                [2, nil, 4, 4, 4, nil, nil],
                [nil, nil, nil, 4, 2, nil, 2, nil],
                [nil, nil, 2, nil, 6, 6, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 834,
            rows: [
                [nil, 1, nil, 1, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1],
                [nil, 1, 1, 1, nil, 2, nil, 2],
                [2, nil, nil, nil, 2, nil, 2],
                [2, 2, nil, 2, 2, nil, 2, 2],
                [1, nil, 1, 1, 3, 3, 3],
                [3, 1, nil, 1, 1, 1, 4, 4],
                [nil, nil, 4, nil, 4, nil, 4],
                [2, 2, 1, 1, 1, 1, 1, nil],
                [6, 6, 6, 6, nil, 2, nil],
                [2, nil, 2, nil, nil, nil, nil, nil],
                [nil, 2, 1, 1, nil, nil, nil],
                [1, nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, 1, 1, nil, 2, 2],
                [2, nil, nil, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 835,
            rows: [
                [nil, 3, 3, nil, 3, 4, 4, nil],
                [4, 4, 4, nil, nil, nil, 4],
                [1, nil, 1, 1, 3, 3, nil, 2],
                [nil, 2, nil, 3, 3, nil, 3],
                [nil, nil, 3, 3, nil, nil, 3, nil],
                [nil, 3, 5, nil, 5, 5, nil],
                [6, nil, nil, nil, nil, nil, 6, 2],
                [nil, 2, 2, nil, nil, nil, nil],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, nil, 1, 1, nil, nil, 1],
                [nil, nil, 1, nil, 1, nil, 1, 1],
                [nil, nil, nil, 4, nil, 1, 1],
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 836,
            rows: [
                [nil, nil, nil, 2, 2, 2, 2, nil],
                [nil, nil, 2, nil, nil, nil, 2],
                [2, nil, 3, nil, nil, 3, 3, 3],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, nil, 3, nil, 1],
                [nil, 1, nil, 1, nil, 1, 1],
                [1, nil, 1, 1, nil, nil, 1, 1],
                [nil, 1, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, 1, 4, nil, 4],
                [nil, 4, nil, 4, 4, 4, nil],
                [nil, 1, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, 1, 1, nil, 2],
                [2, nil, 2, nil, 1, 1, 6],
                [2, 2, nil, nil, 5, nil, 5, 5],
                [5, 5, 2, 2, 2, 2, 2],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 837,
            rows: [
                [nil, nil, 5, nil, 5, nil, nil, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 1, nil, 3, 1, nil, nil, nil],
                [nil, 1, 1, nil, nil, 1, nil],
                [nil, 1, 3, 3, nil, 3, 2, nil],
                [nil, 1, 3, nil, nil, nil, nil],
                [nil, nil, 3, nil, 3, 6, nil, nil],
                [nil, 6, 6, nil, nil, 1, nil],
                [nil, nil, nil, 1, nil, 1, 2, nil],
                [nil, nil, 2, 4, 4, 4, nil],
                [nil, 4, 4, 4, 4, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 2, 2, 2, 2, 4, 1, nil],
                [nil, 1, 1, 2, 2, 2, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 838,
            rows: [
                [6, 6, 6, 6, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [1, 3, nil, 3, 3, nil, 3, nil],
                [nil, nil, nil, nil, 3, 3, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [1, 1, nil, 1, nil, nil, 1],
                [nil, 1, nil, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, 1, 1, nil],
                [1, nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 1, 1, 1, nil],
                [4, nil, 4, 4, nil, 2, nil],
                [2, 2, nil, 1, nil, 1, 2, 2],
                [3, nil, 3, nil, nil, nil, 3],
                [nil, 2, 2, nil, 2, 2, nil, nil],
                [nil, 2, nil, 2, 2, 2, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 839,
            rows: [
                [nil, 1, 3, nil, nil, nil, 3, nil],
                [3, 3, 3, 3, 3, nil, 3],
                [nil, 3, 3, 3, nil, 3, nil, 3],
                [2, nil, nil, nil, nil, 2, 2],
                [nil, 2, nil, 2, nil, 2, 4, nil],
                [4, nil, 1, nil, nil, nil, 6],
                [6, nil, nil, nil, 1, 1, nil, 4],
                [nil, 4, 4, 1, 1, 1, nil],
                [1, nil, 1, nil, 1, 2, nil, nil],
                [2, 2, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, 5, nil, nil],
                [nil, 1, 2, 2, 2, 2, 2],
                [5, 5, 1, 4, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 840,
            rows: [
                [nil, 1, nil, nil, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, nil, nil, 1, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, nil, 1, 1, nil, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, nil, 1, nil, nil, nil],
                [nil, 1, 1, nil, 2, 2, nil],
                [nil, 2, 6, 6, 6, 6, 2, nil],
                [nil, 2, 2, 5, 5, 1, nil],
                [nil, 4, 4, 4, 4, 3, 3, nil],
                [nil, 3, 3, 2, 2, 5, nil],
                [nil, 5, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
    ]
}
