// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch29 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 561,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, 2, 2, nil, nil, nil, nil],
                [2, 2, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 4, nil],
                [4, 4, nil, 4, 3, nil, nil, nil],
                [nil, nil, nil, nil, 5, 5, nil],
                [nil, nil, nil, 1, 1, nil, 1, 3],
                [nil, 3, 3, nil, nil, nil, nil],
                [nil, nil, nil, 6, 3, nil, 1, 1],
                [nil, 1, 1, nil, nil, nil, nil],
                [1, 1, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 3, 3, nil],
                [2, 1, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, 7, 7],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 562,
            rows: [
                [nil, 5, nil, 5, nil, 5, nil, 5],
                [3, nil, 3, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 2, nil, 4, nil, 3, nil, 3],
                [3, nil, 3, nil, 2, nil, 2],
                [nil, 2, nil, 2, nil, 2, nil, 6],
                [6, nil, 3, nil, 3, nil, 3],
                [nil, 3, nil, 3, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 7],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 563,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 7, 7, nil, nil, nil],
                [nil, 4, 4, nil, 1, 5, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, 1, 1, 1, 1, 3, 3, nil],
                [nil, 3, 3, nil, 1, 1, nil],
                [nil, 1, 1, 1, 2, 2, 2, nil],
                [nil, 2, 6, nil, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 564,
            rows: [
                [2, nil, nil, nil, nil, nil, nil, 2],
                [2, nil, 2, 2, 2, nil, 2],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [nil, 7, nil, nil, nil, 7, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 1, 1, 4, nil, nil],
                [nil, nil, 6, nil, nil, 4, nil, nil],
                [nil, nil, 2, 5, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 565,
            rows: [
                [2, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [2, nil, 2, nil, 1, nil, 4, nil],
                [nil, 4, nil, 4, nil, 4, nil],
                [4, nil, 4, nil, 4, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 3, nil, 5, nil],
                [5, nil, 5, nil, 5, nil, 1, nil],
                [nil, 1, nil, 3, nil, 3, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 3, 2, 2, 2, 1, 1, 1],
                [1, 1, 6, 6, 6, 2, 7],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 566,
            rows: [
                [nil, 3, 3, nil, nil, 3, 2, nil],
                [3, 3, nil, nil, 3, 1, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 2, nil, 2, nil, 4, nil],
                [4, nil, 4, nil, 4, nil, 5, nil],
                [nil, 5, nil, 3, nil, 3, nil],
                [3, nil, 3, nil, 3, nil, 1, nil],
                [nil, 1, nil, 5, nil, 5, nil],
                [2, nil, 2, nil, 2, nil, 7, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 2, nil, 2, nil],
                [nil, 2, nil, 6, nil, 2, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 567,
            rows: [
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [1, nil, nil, 1, 2, nil, nil, 2],
                [2, nil, 2, 2, 2, nil, 2],
                [2, nil, nil, 2, 2, nil, nil, 2],
                [2, nil, 3, nil, 4, nil, 4],
                [4, nil, nil, 4, 4, nil, nil, 4],
                [3, nil, 5, nil, 5, nil, 5],
                [3, nil, 3, nil, nil, 3, nil, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [7, nil, 5, nil, nil, 6, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 568,
            rows: [
                [5, 5, nil, nil, nil, nil, 5, 4],
                [4, 4, nil, nil, nil, 2, 2],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 3],
                [3, 3, nil, nil, nil, nil, 3, 3],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 3, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [3, 1, nil, nil, nil, nil, 1, 1],
                [7, 7, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 2, nil, nil, nil, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 569,
            rows: [
                [nil, nil, nil, 6, 6, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil],
                [nil, nil, nil, nil, 2, 5, nil, nil],
                [nil, nil, nil, nil, 3, 3, nil],
                [nil, nil, nil, nil, nil, 3, 7, nil],
                [nil, nil, nil, nil, nil, 7, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, 1, 4, nil],
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [2, 2, nil, nil, 2, 2, nil],
                [nil, 2, 4, nil, nil, 4, 4, nil],
                [4, 4, nil, nil, 1, 1, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, 1, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 570,
            rows: [
                [nil, nil, 1, nil, nil, 1, 1, nil],
                [nil, 6, 6, nil, nil, 6, 2],
                [1, nil, nil, 1, 1, 1, nil, nil],
                [1, 1, nil, 2, nil, nil, nil],
                [2, nil, nil, 2, 2, 3, nil, nil],
                [3, 3, nil, 3, nil, nil, nil],
                [3, nil, 3, 3, 1, 1, 1, nil],
                [nil, 1, nil, nil, 1, nil, 1],
                [1, nil, 1, 1, 1, 1, 1, nil],
                [nil, 4, nil, nil, 4, nil, 4],
                [nil, 3, 2, nil, nil, nil, 2, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, 2, 2, nil, nil, nil, 5, nil],
                [nil, nil, 7, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 571,
            rows: [
                [3, 3, 3, 1, 1, 1, 1, 1],
                [4, 4, 4, 4, 4, 4, 3],
                [3, 3, 1, 1, 5, 5, 5, 5],
                [2, 2, 2, 2, 2, 2, 3],
                [3, 3, 6, 1, 1, 1, 7, 7],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 572,
            rows: [
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, 1, 1, 3],
                [nil, 3, 2, 2, 2, 2, nil, nil],
                [2, 2, 2, 3, 1, 1, 1],
                [1, 1, 1, 1, 1, 3, 3, 2],
                [2, 2, 2, 2, 3, 3, 3],
                [3, 3, 3, 3, 3, 4, 4, 4],
                [4, 4, 4, 6, 5, 5, 7],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 573,
            rows: [
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [2, nil, nil, 2, nil, nil, 2],
                [2, nil, nil, 2, 2, nil, nil, 3],
                [3, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 5],
                [5, nil, nil, 5, nil, nil, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 6, 6, 6, 4, 4, 4, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 3, 5, nil, nil, nil],
                [nil, nil, nil, 7, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 574,
            rows: [
                [4, 4, 4, 6, 2, 1, 1, 1],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [3, 3, 3, 3, 2, 2, 2, 2],
                [nil, nil, nil, nil, 1, nil, nil],
                [1, 1, 1, 1, 2, 2, 7, 7],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [2, 1, 1, 1, 5, 1, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 575,
            rows: [
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, 4, 4, nil, nil, nil, nil],
                [4, 4, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil],
                [1, 1, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, 1, 1, nil, 1, 1],
                [nil, 1, 3, nil, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, 2, 2],
                [nil, 2, 2, nil, nil, nil, nil],
                [2, 2, nil, 2, 6, nil, nil, nil],
                [nil, nil, nil, nil, 6, 3, nil],
                [3, 3, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, nil, 3, 5, nil],
                [nil, nil, nil, nil, nil, nil, 5, 7],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 576,
            rows: [
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [2, nil, 2, nil, 2, nil, 2],
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [2, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 3],
                [3, nil, 3, nil, 3, nil, 3],
                [nil, 3, nil, 3, nil, 3, nil, 4],
                [4, nil, 4, nil, 4, nil, 4],
                [nil, 4, nil, 4, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, nil, 5, nil, 5, nil, 5],
                [5, nil, 3, nil, 3, nil, 6],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [6, nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 577,
            rows: [
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, nil, 4, nil, nil],
                [4, 4, 4, nil, nil, 4, 4, 3],
                [nil, nil, 3, nil, 3, nil, nil],
                [3, 3, 3, nil, nil, 1, 1, 1],
                [nil, nil, 7, nil, 7, nil, nil],
                [nil, nil, 5, 5, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, 1, 1, 3, nil, nil],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, 6, nil, nil, nil, nil, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 578,
            rows: [
                [1, 1, 1, nil, nil, 1, 2, 2],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, 3, 4, 4, 4, nil, nil],
                [nil, nil, 4, 4, 6, nil, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, 3, 5, nil, nil, 5, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, 2, nil, nil, 2, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 579,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [1, 1, 1, 6, 6, 1, 1, 1],
                [nil, nil, nil, nil, 1, nil, nil],
                [3, 3, 3, 7, 1, 1, 1, 1],
                [nil, nil, nil, nil, 5, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, 4, nil, 2, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 580,
            rows: [
                [nil, 1, 1, nil, nil, 4, 4, nil],
                [4, nil, nil, nil, nil, nil, 4],
                [4, 2, nil, nil, nil, nil, 1, 1],
                [3, nil, nil, nil, nil, nil, 3],
                [3, 3, nil, nil, nil, nil, 3, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [3, 3, nil, nil, nil, nil, 3, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [5, 5, nil, nil, nil, nil, 5, 5],
                [5, 1, nil, nil, nil, 1, 1],
                [1, 4, nil, nil, nil, nil, 4, 6],
                [2, 2, nil, nil, nil, 2, 7],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
    ]
}
