// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch106 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2101,
            rows: [
                [2, 2, nil, nil, nil, nil, 2, 1],
                [3, nil, nil, nil, nil, nil, 4],
                [nil, nil, 3, 3, 1, 1, nil, nil],
                [nil, 2, nil, nil, nil, 7, nil],
                [nil, nil, 7, 2, 2, 3, nil, nil],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 3, 1, nil, nil, nil],
                [2, 1, nil, nil, nil, nil, 2, 2],
                [1, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, 2, nil, nil, 5],
                [1, nil, nil, 1, nil, nil, 1],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2102,
            rows: [
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, 1, 4, nil, nil, nil, nil],
                [nil, nil, 4, 2, nil, nil, nil, nil],
                [nil, 2, 1, 3, nil, nil, nil],
                [nil, nil, 2, 3, nil, nil, nil, nil],
                [nil, 1, 1, 2, nil, nil, nil],
                [2, 1, 1, 3, 3, 3, 3, nil],
                [3, 1, 1, 2, 1, 2, nil],
                [1, 2, 1, 2, 1, 1, 2, nil],
                [2, 1, 1, 2, 2, 2, nil],
                [2, 1, 2, 6, 6, 2, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 3, 1, 1, 2, 3, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2103,
            rows: [
                [nil, nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [2, 1, 3, 3, 1, 4, 4, 3],
                [nil, nil, nil, nil, 2, nil, nil],
                [2, 1, 3, 1, 1, 2, 2, 1],
                [nil, nil, nil, nil, 5, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2104,
            rows: [
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, 2, 1, 6, 3, 3],
                [nil, nil, nil, nil, nil, nil, 3, 3],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, 1, 4],
                [nil, 4, nil, nil, nil, 1, nil],
                [nil, 2, 2, nil, nil, 1, nil, nil],
                [2, 1, 3, nil, 2, nil, nil],
                [nil, 2, 5, nil, nil, 2, nil, nil],
                [1, 2, 1, nil, 2, nil, nil],
                [2, nil, 2, 1, 5, 1, nil, 1],
                [nil, 1, nil, 1, nil, 3, 1],
                [5, nil, 1, 1, 1, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, 1],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2105,
            rows: [
                [nil, 4, 1, nil, nil, 5, 3, nil],
                [2, 1, 4, 4, 6, 2, 2],
                [2, 3, 3, 3, 2, 1, 3, 3],
                [4, 2, 1, 1, 2, 4, 3],
                [2, 1, 1, 2, 4, 1, 1, 2],
                [2, 1, 1, 2, 2, 1, 2],
                [nil, 1, 3, nil, nil, 3, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 1, nil, nil, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2106,
            rows: [
                [6, 2, nil, 2, 1, nil, 5, 2],
                [1, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1, nil],
                [1, nil, nil, 5, nil, nil, 5],
                [1, nil, nil, 2, nil, nil, 2, nil],
                [1, nil, nil, 4, nil, nil, 2],
                [1, nil, nil, 1, nil, nil, 4, nil],
                [1, nil, nil, 4, nil, nil, 4],
                [4, nil, nil, 1, nil, nil, 5, nil],
                [6, nil, nil, 3, nil, nil, 3],
                [2, nil, nil, 3, nil, nil, 4, nil],
                [2, nil, nil, 3, nil, nil, 2],
                [1, nil, nil, 2, nil, nil, 2, nil],
                [1, nil, nil, 2, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2107,
            rows: [
                [4, nil, nil, nil, nil, nil, nil, 1],
                [1, 2, 2, 3, 3, 1, 2],
                [4, nil, nil, nil, nil, nil, nil, 2],
                [1, 1, 5, 1, 2, 4, 4],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [3, 2, 4, 3, 3, 2, 7],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2108,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 2, 1, 3, nil, nil],
                [nil, nil, 4, 1, 1, 1, nil, nil],
                [nil, 2, 4, 1, 4, 1, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, 4, 1, 1, 3, 3, nil],
                [nil, nil, 4, 1, 1, 1, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 2, 2, 1, 1, nil, nil],
                [nil, nil, 5, 4, 3, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2109,
            rows: [
                [nil, 1, nil, 1, nil, 1, nil, 6],
                [2, 3, nil, 1, 1, nil, 4],
                [1, nil, 1, nil, 2, nil, 1, nil],
                [1, 3, nil, 1, 2, nil, 1],
                [2, nil, 1, nil, 1, nil, 2, nil],
                [3, 1, nil, 1, 1, nil, 2],
                [nil, 2, nil, 1, nil, 2, nil, 2],
                [2, 1, nil, 2, 2, nil, 5],
                [nil, 1, nil, 1, nil, 3, nil, 1],
                [3, 3, nil, 3, 3, nil, 3],
                [1, nil, 1, nil, 1, nil, 2, nil],
                [2, 4, nil, 4, 4, nil, 1],
                [4, nil, 1, nil, 2, nil, 4, nil],
                [1, 4, nil, 1, 3, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2110,
            rows: [
                [nil, 7, nil, nil, nil, nil, 1, nil],
                [nil, 6, 6, 3, 1, 3, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 3, 2, 2, 3, 4, 3, 3],
                [nil, 5, nil, nil, nil, nil, 2],
                [nil, 2, 1, 1, 3, 2, 3, 3],
                [nil, 4, nil, nil, nil, nil, 2],
                [nil, nil, nil, 3, 3, 2, 3, nil],
                [nil, 2, 3, nil, nil, nil, nil],
                [nil, nil, nil, 2, 2, 3, 1, nil],
                [nil, 3, 3, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2111,
            rows: [
                [3, 1, 2, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, 3],
                [3, 1, 2, 2, 1, 1, 3, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [3, 1, 6, 2, 2, 1, 3, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [3, 1, 4, 4, 5, 1, 3, 1],
                [nil, nil, nil, nil, nil, nil, 1],
                [3, 3, 1, 1, 4, 1, 2, 6],
                [nil, nil, nil, nil, nil, nil, 1],
                [2, 1, 3, 3, 1, 2, 4, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [1, 2, 1, 1, 1, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2112,
            rows: [
                [4, 2, 1, 1, 2, 1, 1, 1],
                [1, nil, nil, 4, nil, nil, 3],
                [3, 3, 3, 2, 5, 5, 1, 4],
                [2, nil, nil, 2, nil, nil, 3],
                [3, 2, 4, 4, 4, 4, 1, 2],
                [2, nil, nil, 2, nil, nil, 3],
                [nil, 2, nil, nil, 1, nil, nil, 1],
                [2, 2, 2, 1, 1, 7, 2],
                [nil, 2, nil, nil, 2, nil, nil, 2],
                [2, 1, 3, 1, 3, 1, 1],
                [nil, 1, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, 1, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2113,
            rows: [
                [3, 2, 1, 4, 2, 4, 4, 2],
                [2, 1, 2, 1, 2, 1, 3],
                [6, 3, 5, 1, 2, 2, 2, 3],
                [2, 1, 1, 1, 2, 1, 3],
                [1, 3, 1, 2, 5, 2, 1, 1],
                [2, 2, 4, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2114,
            rows: [
                [1, nil, nil, 1, nil, 4, 4, 1],
                [1, nil, 3, nil, 4, nil, 1],
                [4, nil, nil, 4, nil, nil, nil, 2],
                [3, 3, 1, nil, nil, nil, 2],
                [2, nil, nil, 2, nil, nil, nil, 2],
                [2, 1, 1, nil, nil, nil, 1],
                [nil, nil, nil, 3, nil, 3, 3, nil],
                [nil, nil, 5, nil, 5, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, nil, 1, nil, 4, nil, nil],
                [nil, nil, nil, 2, nil, 1, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 5, nil, 2, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2115,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 6, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, 4, nil, 3, nil, 1, nil],
                [1, 1, 1, 2, 3, 3, 3, 5],
                [1, nil, 1, nil, 1, nil, 1],
                [7, 3, 2, 3, 1, 3, 5, 4],
                [3, nil, 2, nil, 3, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2116,
            rows: [
                [5, nil, 1, nil, nil, 2, nil, 6],
                [2, nil, 1, nil, 3, nil, 3],
                [3, nil, nil, 3, 3, nil, nil, 5],
                [5, nil, 2, 4, 1, nil, 1],
                [1, nil, nil, 1, 3, nil, nil, 1],
                [3, nil, 2, 2, 2, nil, 3],
                [3, nil, nil, 3, 1, nil, nil, 1],
                [2, nil, 4, nil, 1, nil, 1],
                [1, nil, nil, 4, 4, nil, nil, 2],
                [2, nil, 1, nil, 5, nil, 1],
                [2, nil, 1, nil, nil, 1, nil, 5],
                [2, nil, nil, nil, nil, nil, 2],
                [3, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2117,
            rows: [
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, 4, 4, nil, nil, nil, nil],
                [4, 2, nil, 2, 4, nil, nil, nil],
                [nil, nil, nil, nil, 2, 3, nil],
                [1, 3, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 2, nil],
                [nil, nil, nil, 4, 2, nil, 1, 3],
                [nil, 4, 3, nil, nil, nil, nil],
                [nil, nil, nil, 3, 6, nil, 1, 1],
                [nil, 1, 3, nil, nil, nil, nil],
                [2, 1, nil, 4, 2, nil, nil, nil],
                [nil, nil, nil, nil, 2, 1, nil],
                [1, 4, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 4, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2118,
            rows: [
                [nil, 2, nil, nil, nil, nil, 3, nil],
                [3, nil, nil, 3, nil, nil, 1],
                [1, nil, nil, 3, 4, nil, nil, 4],
                [1, nil, nil, 3, nil, nil, 1],
                [2, nil, nil, 5, 1, nil, nil, 1],
                [3, nil, nil, 3, nil, nil, 1],
                [nil, 3, 2, 3, 3, 1, 2, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 2, 4, 1, 5, 1, 2, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2119,
            rows: [
                [nil, nil, 2, 1, 2, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 2, 2, 5, 2, 4, nil],
                [nil, 5, 5, 1, nil, nil, 1],
                [nil, nil, 2, 2, 4, 1, 1, nil],
                [nil, 3, 1, 1, nil, nil, 1],
                [nil, 2, nil, nil, 2, 2, 2, nil],
                [nil, 1, 2, 1, 1, 4, nil],
                [nil, 5, nil, nil, 4, 7, 3, nil],
                [nil, 1, 3, 3, 1, 1, nil],
                [nil, nil, 4, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 3, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2120,
            rows: [
                [nil, nil, 6, nil, nil, 4, nil, nil],
                [nil, nil, 1, 1, 7, nil, nil],
                [nil, nil, nil, 1, 6, nil, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, nil, 3, 5, nil, nil, nil],
                [nil, nil, 2, 4, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
    ]
}
