// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch79 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1561,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [1, 3, 2, 1, 3, 2, 2],
                [1, 2, 2, 2, 1, 3, 4, 2],
                [4, 2, 3, 3, 1, 5, 3],
                [2, 3, 1, 1, 6, 1, 3, 2],
                [4, 1, 1, 3, 1, 4, 4],
                [4, 2, 1, 1, 3, 1, 2, 1],
                [4, 4, 3, 3, 4, 1, 2],
                [2, 1, 1, 2, 3, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1562,
            rows: [
                [nil, nil, nil, 1, 6, nil, nil, nil],
                [nil, nil, 5, 1, 3, nil, nil],
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, 3, 2, 1, 1, 2, nil],
                [nil, nil, 4, 3, 1, 1, nil, nil],
                [nil, 2, 1, 2, 3, 4, nil],
                [nil, 4, 4, 1, 1, 2, 1, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 2, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1563,
            rows: [
                [nil, 3, 3, nil, 4, 4, nil, nil],
                [nil, 4, 3, nil, 3, 3, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 4, nil, nil, nil, 4, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 1, 6, nil, nil],
                [nil, nil, 2, 2, 5, nil, nil, nil],
                [nil, 1, 7, 1, nil, nil, nil],
                [nil, 1, 3, 1, nil, nil, nil, nil],
                [nil, 2, 1, 1, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1564,
            rows: [
                [3, 3, 3, 1, 3, 3, 1, 2],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 2, 3, 1, 1, 2, 2, 1],
                [nil, 5, nil, nil, nil, nil, nil],
                [nil, 5, 5, 2, 3, 1, 1, 1],
                [nil, 6, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, 1, 3, 2, 2],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, 3, 1, 2, 2, 4, 1],
                [nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, 1, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1565,
            rows: [
                [2, 2, 3, nil, nil, 4, 4, 1],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, 1, 2, 5, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, 2, 1, 3, 1, nil, nil],
                [nil, 2, nil, 3, nil, 3, nil],
                [nil, nil, 2, 1, 2, 2, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 2, 6, 2, 4, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, 3, 1, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1566,
            rows: [
                [2, nil, 5, nil, 3, nil, 2, nil],
                [nil, 2, nil, 3, nil, 1, nil],
                [3, nil, 2, nil, 2, nil, 1, nil],
                [nil, 2, nil, 2, nil, 3, nil],
                [nil, nil, 1, 3, 4, 4, 4, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, 2, 2, 2, 1, 6, 2, nil],
                [2, 2, 2, 3, 2, 2, 1],
                [nil, 1, 1, 3, 3, 1, 3, nil],
                [nil, 3, 1, 6, 1, 3, nil],
                [nil, nil, 2, 1, 3, 2, 1, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1567,
            rows: [
                [1, 2, 6, 4, 2, 1, 2, 1],
                [1, 3, 5, 2, 2, 2, 1],
                [3, 1, 5, 5, 1, 1, 3, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 4, 4, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1568,
            rows: [
                [nil, 2, 3, nil, nil, 1, 1, nil],
                [1, nil, 5, nil, 5, nil, 2],
                [3, nil, 3, 2, 1, 1, nil, 4],
                [4, 2, nil, 2, nil, 2, 1],
                [2, nil, 1, 2, 1, 1, nil, 6],
                [6, 2, nil, 1, nil, 1, 1],
                [nil, 2, nil, 1, 2, nil, 2, nil],
                [2, 4, 3, nil, 1, 1, 1],
                [nil, 1, nil, 2, 3, nil, 1, nil],
                [2, 1, 3, nil, 3, 1, 1],
                [2, nil, 1, nil, nil, 2, nil, 1],
                [2, 1, nil, nil, nil, 1, 1],
                [2, nil, 1, nil, nil, 2, nil, 2],
                [1, 3, nil, nil, nil, 2, 1],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1569,
            rows: [
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, 3, 2, nil, nil, nil, nil],
                [nil, nil, 4, 1, nil, nil, nil, nil],
                [nil, 1, 4, 2, nil, nil, nil],
                [nil, nil, 2, 2, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
                [2, 2, 4, 4, 2, 1, 3, nil],
                [4, 4, 3, 1, 4, 1, nil],
                [2, 2, 2, 2, 1, 2, 1, nil],
                [3, 3, 5, 5, 1, 2, nil],
                [1, 1, 2, 4, 4, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 6, 4, 2, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1570,
            rows: [
                [nil, nil, nil, nil, 1, 1, 2, nil],
                [nil, nil, 3, 4, 4, 3, 1],
                [nil, nil, 2, 2, 2, 5, 5, nil],
                [nil, 3, 1, 1, 4, 4, nil],
                [nil, nil, 1, 2, 3, 5, 5, nil],
                [nil, 3, 1, 1, 1, 5, nil],
                [nil, 1, 1, 4, 4, 4, nil, nil],
                [1, 2, 1, 2, 2, nil, nil],
                [nil, 1, 1, 2, 1, 1, nil, nil],
                [3, 1, 3, 3, 2, nil, nil],
                [1, 5, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 3, 2, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1571,
            rows: [
                [7, 1, nil, nil, nil, nil, 2, 1],
                [3, nil, nil, nil, nil, nil, 3],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [4, nil, 4, 4, 3, nil, 4],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [2, nil, 1, 3, 5, nil, 2],
                [2, 1, 2, 2, 1, 3, 3, 2],
                [4, 1, 1, nil, 1, 1, 2],
                [1, 5, 3, 1, 1, 2, 5, 3],
                [3, 1, 2, nil, 1, 1, 1],
                [nil, 1, 2, nil, nil, 1, 3, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, 2, 2, nil, nil, 2, 1, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1572,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 2, 3, nil, nil],
                [nil, nil, 3, 5, 1, nil, nil],
                [nil, nil, 2, 1, 3, 3, nil, nil],
                [nil, nil, 1, 4, 1, nil, nil],
                [nil, nil, 1, 1, 5, 2, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 4, 1, 7, 1, nil, nil],
                [nil, nil, 1, 3, 3, nil, nil],
                [nil, nil, 2, 1, 1, 1, nil, nil],
                [nil, nil, 6, 1, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1573,
            rows: [
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, nil, 2, 1, 5, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, 1, 2, nil, 1, 3, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, 1, 1, nil, 5, 1, nil],
                [nil, 4, 1, 5, 2, 1, 1, nil],
                [nil, 2, 1, nil, 3, 3, nil],
                [nil, 1, 1, 1, 2, 5, 2, nil],
                [nil, 1, 3, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1574,
            rows: [
                [nil, 2, 2, nil, 5, 2, 1, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, 2, 1, 5, nil, 2, 2, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 1, 3, 3, nil, 1, 4, nil],
                [4, nil, nil, nil, nil, nil, 2],
                [nil, 4, 2, nil, 1, 2, 2, nil],
                [1, nil, nil, nil, nil, nil, 3],
                [nil, 1, 1, nil, 1, 2, 1, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 5, 2, 1, nil, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 7, 2, nil, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1575,
            rows: [
                [nil, nil, 3, 3, 3, nil, nil, nil],
                [nil, 1, 2, 3, 3, nil, nil],
                [nil, 3, 3, 1, 1, 1, nil, nil],
                [3, 3, 2, 2, 2, 1, nil],
                [nil, 1, 3, 2, 7, 1, nil, nil],
                [1, 4, 4, 4, 4, 1, nil],
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, 1, nil, nil, 3, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil, nil],
                [nil, 1, nil, nil, 2, nil, nil],
                [nil, 1, 1, 2, nil, 2, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 2, nil, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1576,
            rows: [
                [nil, nil, 1, nil, nil, 5, nil, nil],
                [nil, nil, 5, 7, 2, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 3, 1, 4, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 2, 6, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1577,
            rows: [
                [1, nil, nil, 1, nil, 1, nil, 4],
                [3, 1, 1, nil, nil, 2, 1],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, 3, 3, 3, 3, 1, 2],
                [nil, nil, 2, nil, nil, 1, nil, nil],
                [nil, 1, 2, 2, 1, 2, 1],
                [nil, nil, 1, 2, 2, 3, 2, 5],
                [nil, nil, 1, 4, 1, 1, 1],
                [nil, nil, 2, 1, 1, 4, 1, 3],
                [nil, nil, 2, 4, 4, 4, 1],
                [nil, nil, nil, 2, 1, nil, 3, 1],
                [nil, nil, nil, 1, nil, 3, 6],
                [nil, nil, nil, 2, 2, nil, 2, 1],
                [nil, nil, nil, 1, nil, 3, 1],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1578,
            rows: [
                [nil, nil, nil, nil, nil, 1, 4, 2],
                [nil, nil, nil, nil, 1, 1, 2],
                [nil, 2, 1, 3, 4, nil, 1, 1],
                [1, 1, 2, 2, nil, nil, nil],
                [nil, 2, 1, 1, 6, nil, 4, 1],
                [3, 3, 3, 1, nil, nil, nil],
                [2, nil, nil, nil, 1, 4, 4, 2],
                [2, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, 3, 1, 6, 2],
                [5, nil, nil, nil, nil, nil, nil],
                [4, 4, 2, 1, 1, nil, 1, nil],
                [3, 1, 2, 1, 1, 2, 1],
                [2, 2, 3, 1, 3, nil, 1, nil],
                [4, 2, 1, 1, 3, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1579,
            rows: [
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, 6, 1, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [2, 2, 1, 5, 1, 2, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 4, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1580,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 2, 5, 1, nil, nil],
                [nil, nil, 1, 1, 4, 1, nil, nil],
                [nil, 1, 7, 3, 1, 2, nil],
                [nil, nil, 4, 4, 4, 3, nil, nil],
                [nil, 3, 1, 2, 2, 2, nil],
                [nil, 2, nil, 2, 2, nil, 2, nil],
                [2, 3, 1, 2, 2, 2, 2],
                [nil, 1, nil, 2, 1, nil, 1, nil],
                [1, 2, 3, 1, 1, 3, 1],
                [nil, 1, nil, 5, 3, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, 2, 2, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
    ]
}
