// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch91 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1801,
            rows: [
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 2, nil, 4, nil, 3, nil],
                [1, nil, 5, nil, 2, nil, 1, nil],
                [nil, 1, nil, 5, nil, 1, nil],
                [2, nil, 2, nil, 2, nil, 1, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [4, nil, 1, nil, 5, nil, 4, nil],
                [nil, 1, nil, 1, nil, 2, nil],
                [2, nil, 2, nil, 3, nil, 1, nil],
                [nil, 1, nil, 1, nil, 4, nil],
                [1, nil, 5, nil, 1, nil, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 2, 2, 2, 2, 2, 1, 1],
                [4, 1, 3, 1, 3, 1, 1],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1802,
            rows: [
                [nil, nil, 1, nil, 4, 4, nil, nil],
                [nil, 4, nil, nil, nil, 2, nil],
                [nil, 5, nil, 3, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, 2, nil, 1, 1, 4, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil],
                [nil, 3, nil, 1, 1, 2, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, 2, 2, 1, 2, 1, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 1, 1, 3, 3, 1, 5, nil],
                [nil, 1, 2, 2, 5, 5, nil],
                [nil, 1, 4, 1, 1, 1, 1, nil],
                [nil, 2, 3, 3, 1, 6, nil],
                [nil, 1, 2, 1, 1, 5, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1803,
            rows: [
                [nil, 3, nil, 1, nil, 2, nil, nil],
                [nil, 1, nil, 4, nil, 2, nil],
                [nil, 2, nil, 5, nil, 5, nil, nil],
                [nil, 5, nil, 1, nil, 2, nil],
                [nil, 2, nil, 1, nil, 3, nil, nil],
                [nil, 1, nil, 2, nil, 2, nil],
                [nil, 3, nil, 3, nil, 3, nil, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [nil, 6, nil, 1, nil, 1, nil, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, 5, nil, 1, nil, 4, nil, nil],
                [nil, 4, nil, 4, nil, 1, nil],
                [nil, 1, nil, 3, nil, 3, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1804,
            rows: [
                [nil, 1, nil, 3, 1, 2, nil, 5],
                [nil, 2, nil, nil, nil, nil, nil],
                [3, 3, nil, 1, 2, nil, nil, 3],
                [1, nil, 6, nil, 3, nil, nil],
                [2, 1, 1, nil, 5, nil, nil, 1],
                [nil, nil, nil, nil, 1, nil, nil],
                [2, nil, 4, 3, 3, 1, nil, nil],
                [nil, nil, nil, 2, 5, nil, nil],
                [nil, nil, nil, 2, 2, nil, 2, 2],
                [1, nil, 1, 5, 1, nil, 3],
                [nil, 2, 3, 3, nil, 3, 1, nil],
                [nil, 2, 1, 1, nil, nil, nil],
                [nil, 2, nil, 2, nil, 1, 1, 1],
                [1, 1, 2, nil, 1, 1, nil],
                [nil, 1, 2, 1, nil, 2, 5, nil],
                [nil, 2, 1, 5, 2, 2, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1805,
            rows: [
                [nil, 1, 2, 2, 3, 2, 1, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [1, 1, 1, 2, 2, 1, 4],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [5, 2, 1, 5, 2, 2, 2],
                [nil, 2, 1, 5, 1, 6, 1, nil],
                [nil, 1, 4, 1, 1, 1, nil],
                [nil, 1, 3, 3, 1, 3, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1806,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 4],
                [1, nil, 1, nil, nil, nil, nil],
                [nil, 1, nil, 1, nil, nil, nil, nil],
                [3, nil, 6, nil, 1, 1, 4],
                [nil, 1, 1, 3, 4, 2, 2, nil],
                [1, 2, 1, nil, 2, 2, 1],
                [1, 1, 4, nil, nil, 4, 1, 1],
                [2, 2, 1, nil, 3, 1, 3],
                [3, 1, 2, nil, nil, 1, 2, 1],
                [2, 1, 2, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1807,
            rows: [
                [nil, nil, 3, 3, 3, nil, nil, nil],
                [nil, nil, 1, 1, 4, nil, 4],
                [nil, 2, 2, nil, nil, 1, 1, 1],
                [2, 1, 3, 4, 1, 2, 2],
                [3, 3, 2, 1, 3, 1, 2, 1],
                [4, 1, 6, 1, 2, 1, 2],
                [1, 3, 2, 2, 1, 1, 2, 4],
                [1, 1, 1, 1, 2, 1, 5],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1808,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 2, 1, 4, 4, nil, nil],
                [nil, 3, 3, 2, 1, 2, nil],
                [nil, nil, 1, 1, 2, 2, nil, nil],
                [nil, 1, 5, 1, 2, 1, nil],
                [nil, 1, 2, 1, 1, 1, 1, nil],
                [2, 1, 5, 1, 5, 5, 1],
                [nil, 4, 1, 1, 2, 4, 1, nil],
                [1, 1, 1, 1, 2, 1, 1],
                [nil, 1, 1, 4, 1, 4, 2, nil],
                [nil, 1, 5, 1, 2, 1, nil],
                [nil, 2, 1, 1, 2, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1809,
            rows: [
                [5, nil, nil, nil, nil, nil, nil, 3],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, nil, 3, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 5, 1, 3, nil, nil],
                [nil, nil, 1, 1, 1, 3, nil, nil],
                [nil, 1, 2, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 3, nil],
                [nil, 1, 1, 2, 2, 5, nil],
                [nil, nil, 2, 2, 3, 6, nil, nil],
                [nil, nil, 2, 3, 4, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 3, 3, 2, nil, nil],
                [nil, nil, nil, 3, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1810,
            rows: [
                [nil, 2, 3, nil, nil, 3, 4, nil],
                [1, 1, 1, 4, 2, 3, 2],
                [2, 1, 1, 7, 4, 3, 1, 1],
                [3, 2, 2, 2, 1, 1, 3],
                [1, 4, 2, 5, 5, 1, 1, 4],
                [3, 3, 1, 4, 1, 1, 1],
                [nil, 3, 3, nil, nil, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1811,
            rows: [
                [2, 1, 3, 3, 1, 4, nil, nil],
                [4, 1, 2, nil, 2, 2, nil],
                [1, nil, 6, nil, 1, nil, 2, 1],
                [2, nil, 5, nil, nil, 1, nil],
                [1, 4, nil, 1, nil, 2, 2, nil],
                [1, nil, nil, nil, 1, 1, 6],
                [1, 4, 2, 1, 1, 2, 1, 2],
                [1, 1, 2, nil, 2, 1, 3],
                [1, 1, 2, 1, 4, 3, 1, 1],
                [1, 1, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1812,
            rows: [
                [nil, nil, nil, 1, nil, 2, 3, nil],
                [1, 2, nil, nil, 1, 1, 3],
                [nil, 1, 2, nil, 1, nil, nil, 1],
                [nil, nil, 1, 1, nil, 1, nil],
                [nil, 2, nil, 1, 2, 1, 2, 1],
                [2, 2, 2, 2, 3, 1, 2],
                [1, 3, 1, 2, 2, 1, 4, 1],
                [1, 2, 2, 1, 1, 1, 2],
                [1, 2, 2, 2, 2, 2, 2, 1],
                [1, 1, 3, 1, 4, 1, 1],
                [1, 2, 2, 1, 3, 5, 1, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 1, 3, 3, 1, 3, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1813,
            rows: [
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 3, 3, 3, 6, 2, 4, nil],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, 2, 2, 1, 2, 3, 4, nil],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, 4, nil],
                [nil, 2, 1, 2, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 4, 4, 4, 4, 4, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 2, 1, 2, 3, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1814,
            rows: [
                [1, nil, nil, 3, 3, nil, nil, 1],
                [3, nil, 1, nil, 2, nil, 1],
                [nil, 2, 5, nil, nil, 5, 5, nil],
                [2, 2, nil, nil, nil, 1, 4],
                [nil, 1, 1, nil, nil, 1, 4, nil],
                [2, 1, nil, nil, nil, 1, 3],
                [1, nil, 5, 1, 6, 1, nil, 1],
                [2, 2, nil, nil, nil, 1, 3],
                [6, nil, 1, 4, 1, 2, nil, 1],
                [2, 1, nil, nil, nil, 5, 1],
                [nil, 1, 1, nil, nil, 2, 1, nil],
                [1, nil, 2, nil, 1, nil, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, nil, 1, nil, 1, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1815,
            rows: [
                [3, 2, 2, 2, 1, 1, 1, 4],
                [5, nil, nil, nil, nil, nil, 4],
                [2, nil, nil, 3, 4, 4, 1, 1],
                [2, nil, nil, nil, 4, 4, 3],
                [3, nil, nil, 1, 3, 3, 2, 2],
                [1, nil, nil, nil, 3, 3, 1],
                [1, nil, nil, nil, nil, nil, 3, 1],
                [1, 1, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, 2, 2],
                [3, 1, nil, nil, nil, nil, nil],
                [1, 3, 1, 3, nil, nil, nil, nil],
                [3, 1, 2, 1, nil, nil, nil],
                [2, 1, 1, 3, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1816,
            rows: [
                [nil, nil, nil, nil, 1, 2, 3, 1],
                [2, 2, 1, 2, 1, 2, 6],
                [6, 1, 3, 1, 4, 1, 2, 3],
                [3, 2, 1, 2, 2, 3, 3],
                [1, 1, 1, 1, 2, 3, 2, 2],
                [1, 3, 3, 1, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 2, 2],
                [nil, nil, nil, nil, 2, 1, 2],
                [nil, nil, nil, nil, 2, 1, 1, 2],
                [nil, nil, nil, nil, 1, 1, 2],
                [nil, nil, nil, nil, 5, 2, 2, 2],
                [nil, nil, nil, nil, 2, 2, 2],
                [nil, nil, nil, nil, 2, 2, 2, 2],
                [nil, nil, nil, nil, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1817,
            rows: [
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [1, 5, 1, 3, 1, 2, 1],
                [nil, nil, 2, 1, 4, 1, nil, nil],
                [nil, 2, 2, 1, 2, 5, nil],
                [nil, nil, 4, 2, 1, 1, nil, nil],
                [nil, 2, 3, 5, 2, 1, nil],
                [nil, nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, 2, 1, 5, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, 1, 3, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1818,
            rows: [
                [1, nil, 2, nil, nil, 4, nil, 1],
                [2, nil, 2, nil, 3, nil, 4],
                [4, nil, nil, 1, 2, nil, nil, 3],
                [1, nil, 5, 5, 5, nil, 1],
                [2, nil, nil, 2, 2, nil, nil, 1],
                [3, nil, 6, 1, 3, nil, 3],
                [1, nil, nil, 4, 4, nil, nil, 1],
                [3, nil, 1, nil, 3, nil, 1],
                [3, nil, nil, 1, 1, nil, nil, 3],
                [3, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1819,
            rows: [
                [5, nil, nil, nil, nil, nil, nil, 5],
                [3, nil, 5, 4, 4, nil, 3],
                [nil, 1, 3, nil, nil, 1, 2, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 1, 3, nil, nil, 5, 1, nil],
                [nil, 4, nil, nil, nil, 1, nil],
                [nil, 1, 1, nil, nil, 6, 2, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 4, 1, nil, nil, 4, 4, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, nil, 6, nil, nil, 2, nil, nil],
                [nil, nil, 1, 3, 2, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1820,
            rows: [
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, 5, 3, 1, nil, nil],
                [nil, nil, 2, 6, 3, 3, nil, nil],
                [nil, 2, 5, nil, 5, 2, nil],
                [nil, nil, 1, 5, 3, 4, nil, nil],
                [nil, 2, 2, nil, 1, 1, nil],
                [nil, 2, 3, nil, nil, 2, 1, nil],
                [1, 1, nil, nil, nil, 3, 2],
                [nil, 1, 2, nil, nil, 4, 1, nil],
                [1, 1, nil, nil, nil, 2, 1],
                [1, 4, nil, nil, nil, nil, 4, 2],
                [4, nil, nil, nil, nil, nil, 4],
                [2, 3, nil, nil, nil, nil, 2, 3],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
    ]
}
