// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch50 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 981,
            rows: [
                [6, 6, 6, nil, 6, 6, 1, nil],
                [1, 1, nil, 2, 2, nil, nil],
                [nil, 2, nil, 2, 2, nil, nil, nil],
                [2, nil, 2, nil, 2, nil, nil],
                [2, nil, nil, 2, nil, 2, nil, nil],
                [2, nil, nil, 2, nil, 2, 2],
                [1, nil, 1, 1, nil, nil, 1, nil],
                [1, nil, 1, 3, 3, 3, 3],
                [3, nil, 3, nil, nil, nil, 3, nil],
                [3, nil, nil, 3, nil, 3, nil],
                [3, 3, 3, 1, 1, 1, nil, 1],
                [nil, 1, 1, 5, nil, nil, nil],
                [1, nil, nil, 4, 4, nil, 4, 4],
                [1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 982,
            rows: [
                [nil, 4, 4, nil, nil, nil, 4, nil],
                [4, 4, 4, 1, 1, nil, 1],
                [nil, 2, 1, 1, nil, 3, nil, 3],
                [3, nil, nil, nil, nil, 3, 3],
                [nil, 3, nil, 3, nil, 1, 1, nil],
                [1, nil, 1, nil, nil, nil, 1],
                [1, nil, nil, nil, 1, 1, nil, 1],
                [nil, 1, 1, 1, 2, 2, nil],
                [2, nil, 2, nil, 2, 2, nil, nil],
                [2, 2, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, 2, 2, 2, 3, 3],
                [3, 3, 5, 5, nil, 5, 3, 3],
                [1, 1, 1, 1, 1, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 983,
            rows: [
                [1, 4, nil, nil, 4, nil, nil, 4],
                [4, nil, 1, nil, 1, 1, nil],
                [1, 1, nil, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 6, 6, nil],
                [1, nil, nil, 1, 1, 1, nil, nil],
                [1, 1, 1, 1, nil, 1, 1],
                [1, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [1, nil, 1, 1, 2, 2, nil, 2],
                [nil, nil, nil, 2, 5, nil, 3],
                [3, nil, 3, 3, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, 2, 2],
                [nil, 2, 2, nil, 2, 2, nil, 2],
                [nil, nil, 1, 1, 5, nil, 5],
                [nil, nil, nil, nil, 5, 5, 5, 6],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 984,
            rows: [
                [nil, 1, 1, 1, 1, 1, 1, 1],
                [nil, 1, nil, 3, nil, 3, 6],
                [6, 2, nil, nil, nil, 2, nil, 2],
                [2, 2, 2, 2, 5, nil, nil],
                [1, 1, nil, 1, nil, nil, 1, 1],
                [1, 1, nil, nil, 2, 2, 2],
                [2, 2, 2, nil, nil, nil, 2, 2],
                [nil, 2, 2, 1, 1, 1, 1],
                [nil, 4, 4, 4, nil, 3, 3, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [3, nil, nil, 3, nil, 5, 5, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 5, 5, 3, 3, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 985,
            rows: [
                [nil, 5, nil, nil, 2, 2, nil, 1],
                [1, nil, 1, nil, nil, 1, nil],
                [1, nil, 1, nil, nil, 1, 1, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, 1, nil, 1, 3, 3, 3, 3],
                [3, 3, 3, nil, nil, nil, 5],
                [nil, 5, 5, nil, nil, 4, nil, nil],
                [4, 4, 4, 4, 2, nil, nil],
                [nil, 2, nil, 2, nil, 2, nil, 2],
                [2, 2, 2, 2, 2, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 4, 4, 4, 1, 6, 6, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 986,
            rows: [
                [5, 1, nil, 1, 1, nil, 1, 3],
                [nil, nil, 1, 3, nil, 3, nil],
                [nil, nil, nil, nil, nil, 3, 3, nil],
                [3, 3, nil, nil, 3, nil, 2],
                [nil, 2, 1, nil, 1, nil, 1, 1],
                [nil, nil, 1, nil, nil, nil, 1],
                [nil, 1, nil, nil, 1, nil, nil, nil],
                [6, 6, 2, 2, nil, 2, 2],
                [2, nil, 1, 1, nil, 4, 1, nil],
                [1, nil, 1, nil, nil, nil, 1],
                [nil, nil, 2, nil, nil, 2, nil, 2],
                [2, 2, nil, 2, 2, 2, nil],
                [2, nil, 2, 2, 2, nil, nil, 2],
                [2, nil, nil, nil, 2, nil, nil],
                [nil, 2, 4, 4, 1, 1, 1, nil],
                [nil, 1, 1, 4, 5, 6, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 987,
            rows: [
                [2, 1, nil, nil, nil, 1, nil, 1],
                [1, 1, nil, 1, 1, 4, nil],
                [nil, nil, 4, 4, nil, nil, nil, 4],
                [nil, nil, nil, 2, 2, 2, nil],
                [nil, 2, 2, 2, nil, nil, 2, 2],
                [2, nil, nil, 1, 1, 1, nil],
                [nil, 1, nil, nil, nil, nil, 1, 1],
                [nil, nil, 1, nil, 1, 1, 1],
                [nil, 6, nil, nil, 6, 6, nil, 1],
                [1, 1, 1, 2, nil, 2, nil],
                [2, 2, 2, 2, 2, nil, 3, nil],
                [3, nil, nil, 1, 1, nil, 1],
                [1, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, 5, nil, 5, 3, nil],
                [3, 3, nil, 3, 3, 3, 3],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 988,
            rows: [
                [nil, 5, nil, nil, 1, nil, 1, nil],
                [nil, 1, 1, nil, 1, nil, nil],
                [nil, 1, nil, 6, 6, 6, nil, nil],
                [nil, 2, 3, nil, 3, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, nil, 3, 3, 3, nil],
                [nil, 2, 2, 2, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, 1, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 1, 1, 1, 1, nil],
                [nil, 4, 6, 4, 4, 4, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 989,
            rows: [
                [nil, 1, nil, nil, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, 1, nil],
                [nil, 5, nil, nil, 5, nil, nil],
                [nil, 5, 3, 3, nil, nil, 3, nil],
                [nil, 3, 4, 4, nil, 4, nil],
                [nil, nil, nil, 4, 2, nil, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 2, 2, nil, 2, nil, nil, nil],
                [nil, 2, 2, nil, 2, 2, nil],
                [nil, 6, 1, 2, 2, 2, 2, nil],
                [nil, 2, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 6, 6, nil],
                [nil, 6, 1, 5, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 990,
            rows: [
                [nil, 2, 2, 2, 2, 2, nil, 2],
                [2, nil, 3, 3, 1, 1, 4],
                [4, 4, 4, nil, nil, 4, nil, 4],
                [4, 4, 4, 4, nil, nil, 4],
                [3, nil, nil, 3, 2, 2, nil, 6],
                [6, 1, nil, nil, 1, 1, 1],
                [3, nil, nil, 3, 3, 1, nil, 2],
                [2, 2, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, 4, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, 1, nil, 5, 1, nil, nil],
                [nil, 1, nil, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 2, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 991,
            rows: [
                [nil, 1, 1, nil, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 1, nil, nil, 1, nil, 2, 3],
                [nil, 3, nil, nil, nil, nil, nil],
                [3, 3, nil, nil, 3, 3, 3, nil],
                [1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, 1, 2, 4, nil, 4, 4],
                [4, 2, 2, 4, 2, 2, 2, 2],
                [5, nil, 5, 5, nil, nil, nil],
                [nil, 5, nil, nil, 2, nil, nil, nil],
                [6, nil, nil, nil, nil, 6, nil],
                [nil, nil, nil, nil, nil, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 992,
            rows: [
                [nil, nil, 1, 3, 3, 3, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, nil, 1, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 4, 4, 4, 4, nil, 6, nil],
                [nil, 6, 6, nil, 6, 1, nil],
                [nil, nil, 1, 1, 1, nil, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, nil, nil, 2, nil, nil],
                [nil, 2, nil, 2, nil, nil, nil],
                [nil, 2, 2, nil, nil, 1, 1, nil],
                [nil, nil, 1, 1, nil, 1, nil],
                [nil, 3, 3, 1, 1, 1, 3, nil],
                [nil, 3, 3, 1, 4, 4, nil],
                [nil, 1, 1, 5, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 993,
            rows: [
                [2, nil, nil, nil, nil, nil, nil, 5],
                [5, nil, nil, 5, 1, nil, 1],
                [nil, 1, 1, 2, 2, 3, 3, nil],
                [3, nil, 2, nil, 2, 2, 2],
                [nil, nil, nil, 2, nil, 2, 3, nil],
                [nil, 3, 3, nil, 3, 3, 4],
                [nil, nil, 4, nil, nil, 4, 4, nil],
                [nil, 4, 1, nil, nil, 1, nil],
                [1, 1, 1, nil, nil, 1, 1, 1],
                [nil, 1, nil, nil, 1, 1, nil],
                [1, nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, nil, 1],
                [1, 1, 1, 1, 1, 2, 2, 2],
                [2, 2, 2, 2, 6, 6, 5],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 994,
            rows: [
                [nil, 1, nil, nil, nil, 1, 1, nil],
                [1, 5, nil, 5, 5, nil, 6],
                [nil, nil, nil, 2, nil, 2, 2, 2],
                [nil, nil, 1, 1, nil, 1, 1],
                [1, nil, 1, 1, nil, 1, nil, nil],
                [1, 1, nil, nil, 1, 1, 1],
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [1, nil, 1, 2, 4, 4, 4],
                [4, nil, nil, nil, nil, 4, 4, 4],
                [nil, nil, nil, 4, nil, nil, 2],
                [2, 2, 2, 3, nil, 2, nil, nil],
                [2, 2, nil, 2, nil, 2, 2],
                [nil, 1, 1, 1, nil, 1, 1, 3],
                [3, 3, nil, 3, 3, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 995,
            rows: [
                [1, nil, 1, 1, 1, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, nil],
                [3, nil, 3, nil, 3, 3, nil, 1],
                [1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [1, nil, nil, nil, 1, 1, nil],
                [nil, 2, nil, nil, 2, nil, nil, 2],
                [2, nil, 2, nil, 5, nil, 5],
                [nil, nil, 5, 5, 5, 5, 3, 1],
                [1, 1, 1, nil, 1, 3, 3],
                [3, 3, 4, 6, 4, 4, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 1, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 996,
            rows: [
                [1, 1, nil, 1, nil, nil, nil, 1],
                [1, 5, nil, 5, 5, nil, 5],
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [2, 2, nil, 3, nil, 4, 4],
                [nil, 2, nil, 2, 2, 2, 2, 1],
                [nil, nil, 1, 1, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 3, 3, 3],
                [nil, nil, 3, 3, 3, nil, 3, 3],
                [3, 3, nil, 3, 3, nil, 2],
                [2, 2, nil, 1, nil, nil, 1, nil],
                [1, 1, 1, 6, 6, nil, nil],
                [1, 2, nil, 4, 1, nil, 1, nil],
                [1, nil, nil, 1, nil, nil, 1],
                [1, 1, 1, 1, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 997,
            rows: [
                [nil, nil, nil, nil, 6, 6, 2, 2],
                [nil, 2, nil, nil, nil, 2, 3],
                [3, nil, 3, 3, nil, nil, nil, nil],
                [3, 3, 1, nil, 1, nil, 1],
                [1, nil, nil, 1, nil, 1, 1, 1],
                [1, 1, 1, nil, nil, nil, 5],
                [nil, nil, 5, 5, 5, 5, nil, 5],
                [nil, 2, nil, nil, 2, nil, nil],
                [4, 1, nil, nil, 1, 1, 1, 1],
                [nil, 1, nil, nil, 1, nil, nil],
                [1, nil, 1, nil, nil, 1, 1, nil],
                [1, nil, nil, nil, nil, 2, 2],
                [2, 2, 2, 2, nil, nil, nil, nil],
                [2, 3, nil, 3, nil, 3, 2],
                [nil, 1, 1, nil, nil, 1, 1, 1],
                [nil, 2, nil, nil, 2, nil, 2],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 998,
            rows: [
                [nil, 4, nil, 4, nil, 1, nil, nil],
                [nil, nil, 3, 3, nil, 3, nil],
                [nil, nil, nil, nil, 1, 3, nil, nil],
                [nil, nil, 3, nil, 3, 3, nil],
                [nil, 3, 3, nil, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 2, 2, 2, 2, nil],
                [nil, nil, 2, 2, 2, 1, nil],
                [nil, 4, 4, 4, 1, 1, 1, nil],
                [nil, 5, nil, 5, nil, nil, nil],
                [nil, 5, 5, nil, nil, 6, nil, nil],
                [nil, nil, nil, 6, 6, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 999,
            rows: [
                [nil, nil, 2, 3, 3, 3, nil, nil],
                [nil, nil, 3, nil, nil, 3, nil],
                [nil, nil, nil, 3, 3, 3, 3, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 1, 1, nil, nil, 1, nil],
                [nil, nil, nil, 1, 1, nil, 6, nil],
                [nil, nil, nil, nil, 6, 6, nil],
                [nil, 6, nil, 6, nil, 1, 2, nil],
                [nil, nil, 2, 1, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 2, 2, 2, nil],
                [nil, 1, 1, 1, 1, 5, 4, nil],
                [nil, 4, 4, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 2, nil, 2],
                [2, nil, 4, nil, 4, nil, 5],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 1000,
            rows: [
                [1, nil, 1, 1, nil, 1, 1, 1],
                [nil, nil, 1, nil, nil, 3, nil],
                [nil, 3, nil, 3, 3, nil, 2, nil],
                [2, nil, nil, nil, nil, 2, nil],
                [nil, nil, 1, 1, 1, 1, nil, 4],
                [nil, nil, 4, nil, 4, nil, 4],
                [nil, 1, 1, 1, 1, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, nil, 1, 1, 1],
                [4, 4, 6, 6, 6, 5, 5, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, 5, 5, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
    ]
}
