// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch135 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2681,
            rows: [
                [3, 7, nil, nil, nil, nil, 3, 2],
                [4, nil, nil, nil, nil, nil, 3],
                [nil, nil, 3, 6, 3, 4, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, nil, 1, 5, 1, 2, nil, nil],
                [nil, 1, nil, nil, nil, 4, nil],
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 1, 5, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2682,
            rows: [
                [nil, 2, 3, nil, nil, 3, 1, nil],
                [nil, 2, nil, nil, nil, 7, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 5, nil, nil, nil, 1, nil],
                [nil, 4, nil, nil, nil, 4, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 3, nil, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 3, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 5, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2683,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, 2, 4, nil, nil, nil, nil],
                [4, 1, nil, 3, 6, nil, nil, nil],
                [nil, nil, nil, nil, 2, 1, nil],
                [2, 1, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, nil, 3, 1, nil],
                [nil, nil, nil, 1, 3, nil, 2, 1],
                [nil, 2, 1, nil, nil, nil, nil],
                [nil, nil, nil, 2, 4, nil, 1, 5],
                [nil, 7, 1, nil, nil, nil, nil],
                [3, 1, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, 2, 1, nil],
                [1, 1, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2684,
            rows: [
                [nil, 2, nil, nil, nil, nil, 3, nil],
                [2, 1, nil, nil, nil, 2, 1],
                [nil, 2, nil, nil, nil, nil, 3, nil],
                [4, 1, nil, nil, nil, 3, 1],
                [nil, 6, nil, nil, nil, nil, 1, nil],
                [2, 1, nil, nil, nil, 3, 1],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [2, 3, nil, nil, nil, 1, 5],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [2, 1, nil, nil, nil, 2, 5],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2685,
            rows: [
                [5, nil, nil, 3, nil, 6, 1, 4],
                [2, nil, 1, nil, 5, nil, 2],
                [3, nil, nil, 2, nil, nil, nil, 6],
                [2, 1, 4, nil, nil, nil, 2],
                [3, nil, nil, 3, nil, nil, nil, 2],
                [1, 4, 4, nil, nil, nil, 1],
                [nil, nil, nil, 5, nil, 3, 1, nil],
                [nil, nil, 3, nil, 2, nil, nil],
                [nil, nil, nil, 1, nil, 3, 2, nil],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, nil, nil, 1, nil, 3, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, 2, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2686,
            rows: [
                [1, 2, 4, 3, 1, 4, 3, 2],
                [1, nil, nil, 3, nil, nil, 2],
                [3, 1, 2, 1, 3, 2, 5, 2],
                [6, nil, nil, 3, nil, nil, 4],
                [2, 1, 3, 2, 3, 1, 2, 3],
                [1, nil, nil, 2, nil, nil, 2],
                [nil, 1, nil, nil, 3, nil, nil, 2],
                [5, 1, 2, 1, 2, 1, 3],
                [nil, 1, nil, nil, 2, nil, nil, 1],
                [2, 3, 1, 3, 1, 2, 1],
                [nil, 3, nil, nil, 3, nil, nil, 2],
                [1, nil, nil, 2, nil, nil, 1],
                [nil, 4, nil, nil, 1, nil, nil, 2],
                [3, nil, nil, 1, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2687,
            rows: [
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, 2, 1, 7, 1, nil, nil],
                [nil, 2, 3, 1, 3, 1, nil],
                [nil, nil, 5, 4, 1, 2, nil, nil],
                [nil, 1, 3, 1, 3, 1, nil],
                [nil, 3, 1, 3, 1, 4, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 2, 3, 1, 4, 1, 4, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2688,
            rows: [
                [nil, nil, 5, nil, nil, 7, 1, nil],
                [nil, 2, 1, nil, nil, 2, 3],
                [3, nil, nil, 3, 2, 3, nil, nil],
                [1, 2, nil, 5, nil, nil, nil],
                [1, nil, nil, 4, 1, 1, nil, nil],
                [4, 2, nil, 1, nil, nil, nil],
                [4, nil, 1, 4, 1, 4, 1, nil],
                [nil, 4, nil, nil, 2, nil, 1],
                [4, nil, 1, 6, 1, 3, 1, nil],
                [nil, 1, nil, nil, 1, nil, 1],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2689,
            rows: [
                [nil, nil, nil, 6, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, 1, 6, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [5, 2, 1, 2, 1, 3, 1, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 1, 4, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2690,
            rows: [
                [nil, 1, 2, nil, nil, 1, 2, nil],
                [6, 1, nil, nil, 4, 1, nil],
                [nil, 5, 1, nil, nil, 3, 1, nil],
                [2, 3, nil, nil, 2, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, nil, 3, nil, 1, nil, 3, nil],
                [nil, 2, nil, 3, nil, 3, nil],
                [3, nil, 2, nil, 1, nil, 2, nil],
                [nil, 5, nil, 2, nil, 1, nil],
                [2, nil, 1, nil, 3, nil, 2, nil],
                [nil, 1, nil, 2, nil, 5, nil],
                [2, nil, 1, nil, 2, nil, 3, nil],
                [nil, 2, nil, 1, nil, 5, nil],
                [1, nil, 3, nil, 1, nil, 1, nil],
                [nil, 2, nil, 2, nil, 2, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2691,
            rows: [
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 2, 1, 2, 1, 3, 1, nil],
                [nil, nil, nil, nil, nil, nil, 2],
                [nil, 1, 4, 1, 5, 5, 1, nil],
                [nil, nil, nil, nil, nil, nil, 6],
                [nil, nil, nil, nil, nil, nil, 4, nil],
                [nil, 3, 2, 1, 6, 1, nil],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, 3, 3, 3, 2, 7, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 3, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2692,
            rows: [
                [5, nil, nil, nil, nil, nil, nil, 6],
                [3, 1, 3, 1, 3, 1, 4],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [1, 6, 1, 4, 1, 2, 1],
                [1, nil, nil, nil, nil, nil, nil, 3],
                [1, 6, 1, 3, 1, 1, 1],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2693,
            rows: [
                [nil, 2, nil, 1, nil, 2, nil, 4],
                [7, nil, 5, nil, 1, nil, 1],
                [nil, 3, nil, 1, nil, 3, nil, 1],
                [3, nil, 2, nil, 1, nil, 2],
                [nil, 1, nil, 6, nil, 1, nil, 2],
                [1, nil, 3, nil, 2, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 5, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2694,
            rows: [
                [nil, 6, 1, nil, 2, 4, nil, nil],
                [1, nil, 7, 1, nil, 5, nil],
                [3, nil, nil, nil, nil, nil, 3, nil],
                [2, 4, 3, nil, nil, 1, 5],
                [1, nil, nil, nil, nil, nil, 1, nil],
                [2, 1, 5, nil, nil, 1, 2],
                [nil, 1, 1, 4, 1, 4, 2, 1],
                [nil, 3, 1, nil, nil, 3, 4],
                [nil, 1, 2, 3, 2, 3, 1, 3],
                [nil, 2, 3, nil, nil, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2695,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 2],
                [4, nil, 2, 3, 2, nil, 1],
                [nil, 2, 4, nil, nil, 5, 5, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, 4, 4, nil, nil, 1, 3, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 5, 7, nil, nil, 3, 1, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 1, 3, nil, nil, 2, 1, nil],
                [nil, 3, nil, nil, nil, 6, nil],
                [nil, nil, 2, nil, nil, 1, nil, nil],
                [nil, nil, 2, 3, 2, nil, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2696,
            rows: [
                [2, nil, 4, nil, 1, nil, 2, nil],
                [nil, 4, nil, 3, nil, 2, nil],
                [1, nil, 2, nil, 3, nil, 2, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [3, nil, 5, nil, 1, nil, 2, nil],
                [nil, 1, nil, 4, nil, 2, nil],
                [3, nil, 4, nil, 4, nil, 2, nil],
                [nil, 1, nil, 4, nil, 1, nil],
                [3, nil, 3, nil, 3, nil, 1, nil],
                [nil, 5, nil, 2, nil, 1, nil],
                [6, nil, 2, nil, 1, nil, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 2, 1, 2, 5, 1, 2, 1],
                [2, 1, 2, 1, 1, 1, 1],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2697,
            rows: [
                [nil, 1, nil, nil, nil, nil, 7, nil],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, nil, 1, 2, 1, 6, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, 4, 2, 3, 4, nil, nil],
                [nil, nil, 1, nil, 3, nil, nil],
                [1, 2, 4, nil, nil, 1, 4, 2],
                [nil, nil, 2, nil, 5, nil, nil],
                [1, 3, 5, nil, nil, 1, 3, 1],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, 2, 1, 4, 1, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, nil, 4, 1, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2698,
            rows: [
                [nil, nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [2, 5, 5, 3, 1, 3, 1, 2],
                [nil, nil, nil, nil, 1, nil, nil],
                [5, 2, 6, 1, 2, 4, 2, 6],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2699,
            rows: [
                [nil, 2, 3, 1, 2, 1, 2, nil],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 1, nil, nil, nil, nil, 5, nil],
                [3, 3, 1, 1, 3, 3, 2],
                [nil, 3, nil, nil, nil, nil, 4, nil],
                [2, 1, 4, 7, 3, 1, 4],
                [nil, 2, 4, 1, 4, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2700,
            rows: [
                [3, 4, nil, 1, 4, nil, 3, 2],
                [3, nil, nil, 3, nil, nil, 1],
                [6, nil, nil, 1, nil, nil, 5, nil],
                [2, nil, nil, 1, nil, nil, 1],
                [2, nil, nil, 1, nil, nil, 3, nil],
                [3, nil, nil, 2, nil, nil, 1],
                [2, nil, nil, 7, nil, nil, 4, nil],
                [1, nil, nil, 2, nil, nil, 1],
                [4, nil, nil, 2, nil, nil, 1, nil],
                [2, nil, nil, 1, nil, nil, 6],
                [1, nil, nil, 1, nil, nil, 4, nil],
                [1, nil, nil, 4, nil, nil, 1],
                [2, nil, nil, 1, nil, nil, 1, nil],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
    ]
}
