// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch119 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2361,
            rows: [
                [1, 1, nil, nil, 1, nil, 3, 3],
                [nil, nil, nil, 3, nil, 1, 1],
                [nil, 2, nil, 1, 1, nil, 2, nil],
                [1, 2, 2, 1, 5, 1, 2],
                [nil, 1, nil, 5, 5, nil, 5, nil],
                [2, 1, 2, 1, 2, 1, 3],
                [nil, 1, nil, 5, 1, nil, 3, nil],
                [1, 2, nil, nil, nil, 1, 4],
                [nil, 1, nil, 4, 4, nil, 1, nil],
                [1, 5, nil, nil, nil, 3, 1],
                [1, 4, 1, nil, nil, 4, 4, 1],
                [2, 1, nil, nil, nil, 1, 2],
                [2, 1, 3, nil, nil, 1, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2362,
            rows: [
                [1, 1, 1, nil, nil, 3, 2, nil],
                [1, nil, 6, nil, 1, 1, 2],
                [1, 3, 3, nil, nil, 3, nil, 1],
                [2, 2, 1, nil, nil, nil, nil],
                [nil, 2, 2, 2, 1, nil, 4, 4],
                [4, 4, 1, nil, 1, 5, 1],
                [1, 2, 1, 2, 1, 2, 3, 1],
                [1, 2, 1, nil, 1, 1, 1],
                [2, 1, 1, 2, 2, 1, 1, 3],
                [1, 3, 1, nil, 1, 1, 1],
                [1, 2, 1, 1, 2, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2363,
            rows: [
                [1, 2, 1, 1, 1, 3, 3, 3],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 2, 1, 4, 2, 2, 1, 1],
                [nil, 2, nil, nil, nil, nil, nil],
                [nil, 1, 2, 2, 2, 1, 3, 2],
                [nil, 3, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 2, 4, 6, 1],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, 2, 2, 1, 2, 2, 3],
                [nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, 3, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 3, 1, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2364,
            rows: [
                [nil, nil, 1, nil, nil, 3, nil, nil],
                [nil, 5, 2, nil, 4, 4, nil],
                [nil, 4, 2, 1, 1, 1, 2, nil],
                [nil, 1, 3, nil, 1, 2, nil],
                [nil, 3, 1, 2, 2, 2, 1, nil],
                [nil, 1, 5, nil, 1, 2, nil],
                [nil, nil, 1, nil, nil, 7, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2365,
            rows: [
                [1, 3, nil, nil, nil, nil, 3, 1],
                [3, 1, 2, 1, 1, 2, 2],
                [2, 2, nil, nil, nil, nil, 1, 2],
                [2, 2, 1, 3, 3, 1, 2],
                [1, 2, nil, nil, nil, nil, 2, 2],
                [4, 1, 1, 1, 2, 1, 2],
                [3, 1, nil, nil, nil, nil, 1, 1],
                [1, 3, 2, 1, 4, 2, 3],
                [3, 3, nil, nil, nil, nil, 3, 1],
                [5, 5, 4, 1, 1, 3, 6],
                [1, 4, nil, nil, nil, nil, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 2, nil, nil, nil, nil, 1, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2366,
            rows: [
                [5, nil, nil, nil, nil, nil, nil, 1],
                [2, 2, 5, 3, 4, 4, 4],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, 2, 3, 3, 2, 2, 1],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [1, 1, 5, 4, 2, 6, 1],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [1, 1, 2, 1, 2, 2, 1],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [1, 2, 3, 2, 1, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2367,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, nil, nil, 4, nil],
                [nil, nil, nil, nil, nil, nil, 6, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, 5, nil, nil, nil, nil],
                [nil, 5, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 3, 4, 4, nil, nil],
                [nil, 3, 2, 1, 3, nil, nil],
                [nil, 1, 3, 1, 3, 1, 2, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2368,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, 2, nil, nil, 2],
                [nil, nil, 4, 2, nil, 2, nil, nil],
                [1, 4, 5, nil, 1, 2, nil],
                [nil, 1, 2, 3, 1, nil, nil, nil],
                [3, 2, nil, nil, nil, nil, 1],
                [2, 1, 1, nil, nil, 1, 4, 4],
                [4, 4, 1, nil, 1, 3, 2],
                [1, 3, 3, nil, nil, 2, 1, 2],
                [2, 1, 6, nil, 1, 1, 2],
                [1, 1, 4, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2369,
            rows: [
                [nil, nil, 2, 2, 1, nil, nil, nil],
                [nil, 2, 1, 2, 2, nil, nil],
                [nil, 1, 3, 3, 3, 3, nil, nil],
                [2, 1, 2, 1, 3, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [3, 5, 5, 1, 2, 1, nil],
                [nil, nil, 4, nil, 4, nil, nil, nil],
                [nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, 1, nil, 4, nil, nil, nil],
                [nil, 3, nil, nil, 1, nil, nil],
                [nil, 6, 1, 2, nil, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2370,
            rows: [
                [1, 2, nil, 2, 3, nil, 3, 3],
                [2, 1, nil, 2, nil, 2, 2],
                [nil, 3, nil, 2, 1, nil, 2, nil],
                [1, 2, 2, 2, 4, 1, 2],
                [nil, 4, nil, 4, 6, nil, 1, nil],
                [2, 1, 2, 1, 2, 1, 1],
                [nil, 2, nil, 1, 1, nil, 1, nil],
                [2, 2, nil, nil, nil, 1, 2],
                [nil, 2, nil, 1, 2, nil, 1, nil],
                [1, 1, nil, nil, nil, 1, 2],
                [2, 2, 3, nil, nil, 3, 6, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [2, 1, 2, nil, nil, 3, 1, 2],
                [2, 1, nil, nil, nil, 1, 5],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2371,
            rows: [
                [nil, 1, 1, nil, nil, 2, 2, nil],
                [2, nil, nil, nil, nil, nil, 1],
                [1, 4, nil, nil, nil, nil, 4, 4],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 4, 1],
                [6, nil, nil, nil, nil, nil, 1],
                [6, 3, nil, nil, nil, nil, 1, 4],
                [3, nil, nil, nil, nil, nil, 2],
                [1, 3, nil, nil, nil, nil, 4, 3],
                [1, nil, nil, nil, nil, nil, 2],
                [2, 1, nil, nil, nil, nil, 5, 2],
                [5, 1, nil, nil, nil, 3, 1],
                [1, 4, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2372,
            rows: [
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 4, 4, 4, nil, nil],
                [nil, 1, 6, 2, 2, nil, nil],
                [nil, 2, 1, 2, 3, 5, 1, nil],
                [nil, 2, 5, 1, 1, 3, nil],
                [nil, 6, 1, 2, 1, 1, 3, nil],
                [nil, 3, 5, 1, 2, 4, nil],
                [nil, 4, 1, 3, 3, 1, 2, nil],
                [nil, 3, 1, 3, 2, 1, nil],
                [nil, 2, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2373,
            rows: [
                [nil, 1, nil, 2, nil, nil, 1, 2],
                [nil, nil, nil, 3, nil, nil, 3],
                [nil, 1, 1, 2, nil, nil, 2, nil],
                [nil, 2, nil, 1, nil, nil, 3],
                [nil, 1, nil, nil, nil, nil, 2, 1],
                [nil, 1, nil, 2, nil, 6, 1],
                [nil, 4, 1, 1, nil, 2, 2, 2],
                [nil, 2, 2, 1, nil, 4, 4],
                [nil, 1, 2, 1, nil, 3, 3, 3],
                [nil, 5, 5, 1, nil, 1, 2],
                [nil, 1, 6, 6, nil, 1, 2, 1],
                [nil, 4, 1, 2, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2374,
            rows: [
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 2, nil, nil, 1, nil, 3, nil],
                [3, nil, nil, 3, nil, nil, 4],
                [nil, 1, nil, nil, 1, nil, 1, nil],
                [1, nil, nil, 2, nil, nil, 1],
                [nil, 1, nil, nil, 1, nil, 2, nil],
                [nil, 2, nil, 2, nil, 3, nil],
                [nil, 1, nil, nil, 7, nil, 1, nil],
                [nil, 3, nil, 1, nil, 1, nil],
                [nil, nil, 3, 4, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2375,
            rows: [
                [nil, 2, 1, nil, 5, 2, nil, nil],
                [1, nil, 5, 5, nil, 2, nil],
                [3, nil, nil, nil, nil, nil, 2, nil],
                [3, 4, 1, nil, nil, 3, 4],
                [5, nil, nil, nil, nil, nil, 3, nil],
                [2, 2, 1, nil, nil, 3, 3],
                [nil, 1, 3, 2, 2, 2, 5, 1],
                [nil, 1, 4, nil, nil, 3, 3],
                [nil, 1, 7, 1, 1, 1, 1, 1],
                [nil, 1, 1, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2376,
            rows: [
                [nil, 3, 1, nil, nil, 3, 4, nil],
                [4, 5, nil, nil, 3, 3, nil],
                [nil, 2, 4, nil, nil, 3, 1, nil],
                [3, 1, nil, nil, 1, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 1, nil, 2, nil, 1, nil],
                [nil, 3, nil, 1, nil, 3, nil],
                [3, nil, 5, nil, 5, nil, 1, nil],
                [nil, 1, nil, 3, nil, 1, nil],
                [2, nil, 1, nil, 3, nil, 2, nil],
                [nil, 6, nil, 3, nil, 3, nil],
                [6, nil, 1, nil, 2, nil, 3, nil],
                [nil, 2, nil, 1, nil, 3, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2377,
            rows: [
                [nil, nil, 2, 1, 6, nil, nil, nil],
                [nil, nil, 6, 1, 1, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, nil, 1, nil, 5, nil, 5, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [1, nil, 3, nil, 3, nil, 1, nil],
                [nil, 1, nil, 3, nil, 3, nil],
                [1, nil, 4, nil, 4, nil, 1, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [2, nil, 1, nil, 5, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [2, nil, 1, nil, 4, nil, 1, nil],
                [nil, 2, nil, 1, nil, 2, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2378,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 5, nil, 1, 4, nil, nil],
                [2, 6, nil, 1, 1, nil, nil],
                [nil, 2, 3, nil, 2, 1, nil, nil],
                [1, 2, nil, 3, 1, nil, nil],
                [nil, 2, 3, nil, 3, 1, nil, nil],
                [3, 2, nil, 1, 1, nil, nil],
                [nil, 2, 1, nil, 2, 2, nil, nil],
                [3, 3, nil, 3, 1, nil, nil],
                [nil, 2, 2, nil, 2, 1, nil, nil],
                [2, 2, nil, 2, 1, nil, nil],
                [nil, 3, 1, nil, 2, 1, nil, nil],
                [2, 1, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2379,
            rows: [
                [1, nil, nil, 2, 1, nil, nil, 1],
                [4, nil, 3, nil, 3, nil, 2],
                [nil, 1, 1, nil, nil, 2, 1, nil],
                [3, 5, nil, nil, nil, 2, 1],
                [nil, 4, 6, nil, nil, 4, 3, nil],
                [3, 3, nil, nil, nil, 1, 5],
                [1, nil, 2, 2, 3, 3, nil, 3],
                [1, 2, nil, nil, nil, 2, 1],
                [5, nil, 4, 4, 1, 4, nil, 1],
                [1, 5, nil, nil, nil, 1, 4],
                [nil, 1, 1, nil, nil, 1, 4, nil],
                [1, nil, 1, nil, 2, nil, 1],
                [nil, 1, 2, nil, nil, 1, 2, nil],
                [1, nil, 1, nil, 1, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2380,
            rows: [
                [3, 1, nil, nil, nil, 1, 2, 4],
                [3, 2, nil, 3, nil, 2, 2],
                [1, 2, nil, 3, nil, 1, nil, nil],
                [nil, nil, 1, 2, 2, 5, 2],
                [nil, nil, nil, nil, 2, 1, nil, 1],
                [3, 1, nil, nil, nil, 1, 2],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [5, nil, nil, 2, nil, 4, nil],
                [3, 1, 5, 5, nil, nil, nil, nil],
                [3, 3, nil, 3, 2, 1, nil],
                [4, nil, 6, nil, nil, 2, nil, 1],
                [1, nil, nil, 2, 4, 2, nil],
                [4, nil, nil, nil, 4, 2, 1, 2],
                [4, nil, 2, 2, 2, nil, 2],
                [nil, 2, nil, nil, nil, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
    ]
}
