// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch55 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1081,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, 3, 3, 3, 1, 1, 2, nil],
                [2, 2, 3, 2, 1, 2, 3],
                [nil, 3, 3, 2, 7, 1, 1, nil],
                [2, 1, 2, 1, 1, 1, 1],
                [nil, 5, 4, 4, 1, 4, 2, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 2, 2, 1, 1, 1, 1, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, 3, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1082,
            rows: [
                [1, nil, nil, 3, 2, nil, nil, 1],
                [1, nil, 1, nil, 1, nil, 3],
                [nil, 1, 2, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, nil, 1, 3],
                [nil, 3, 3, nil, nil, 3, 1, nil],
                [5, 5, nil, nil, nil, 2, 1],
                [3, nil, 1, 3, 3, 2, nil, 3],
                [2, 3, nil, nil, nil, 1, 1],
                [1, nil, 2, 1, 3, 4, nil, 3],
                [1, 1, nil, nil, nil, 6, 6],
                [nil, 1, 1, nil, nil, 1, 2, nil],
                [4, nil, 2, nil, 3, nil, 3],
                [nil, 3, 2, nil, nil, 2, 3, nil],
                [3, nil, 1, nil, 2, nil, 3],
                [3, nil, nil, 2, 2, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1083,
            rows: [
                [nil, 5, nil, nil, nil, nil, 5, nil],
                [nil, 1, 2, 2, 2, 1, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [5, nil, nil, nil, nil, nil, nil],
                [nil, 2, 3, 2, 2, 5, 2, 3],
                [nil, 1, nil, nil, nil, nil, 1],
                [nil, 1, 2, 2, 5, 5, 3, 1],
                [nil, 5, nil, nil, nil, nil, 1],
                [nil, nil, nil, 3, 3, 5, 1, nil],
                [nil, 4, 1, nil, nil, nil, nil],
                [nil, nil, nil, 5, 3, 1, 2, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1084,
            rows: [
                [1, 2, 2, 2, 3, 3, 1, 2],
                [2, 2, 3, 1, 2, 2, 1],
                [2, 2, 2, 4, 4, 1, 1, 6],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 2, 2, 1, 1, 1, nil, nil],
                [nil, 2, 1, 2, 1, nil, nil],
                [nil, 1, 4, 2, nil, nil, nil, nil],
                [nil, 3, 3, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 1, 2, 1, 1, 2, 2, 1],
                [2, 1, 2, 1, 1, 2, 1],
                [2, 2, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1085,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 1, 6, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 4, 2, nil, nil],
                [nil, nil, 1, 2, 4, nil, nil],
                [nil, nil, 1, 1, 2, 1, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 4, 4, 4, 2, nil, nil],
                [nil, nil, 3, 6, 3, nil, nil],
                [nil, nil, 2, 3, 3, 1, nil, nil],
                [nil, nil, 2, 3, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1086,
            rows: [
                [nil, 1, 2, 2, 1, 3, 1, 1],
                [3, 3, 1, 3, 1, 2, 1],
                [1, 3, 3, 1, 1, 3, 3, 1],
                [2, 1, 1, 1, 2, 2, 1],
                [nil, 2, 1, 2, 1, 3, nil, nil],
                [nil, 3, 2, 1, 1, nil, nil],
                [nil, 4, 4, 4, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 2, 2, 1, 6, 1],
                [4, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1087,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, 2, 6, nil, 1, 2, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, 4, 2, 4, 1, 1, 4, nil],
                [nil, 6, 1, nil, 4, 1, nil],
                [nil, 3, 4, 1, 2, 1, 3, nil],
                [nil, 6, 2, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1088,
            rows: [
                [nil, nil, 1, nil, nil, 1, 2, nil],
                [6, nil, 2, nil, 1, nil, 1],
                [1, 1, nil, 3, 4, nil, 4, 1],
                [2, 1, 2, 3, 1, 2, 2],
                [2, 2, nil, 1, 4, nil, 4, 4],
                [1, 3, 1, 1, 2, 1, 1],
                [3, 3, 1, 6, 1, 1, 2, 1],
                [2, nil, 1, 1, 1, nil, 2],
                [2, 1, 3, 1, 1, 1, 1, 1],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1089,
            rows: [
                [1, 3, nil, nil, nil, nil, nil, nil],
                [2, 3, nil, nil, nil, nil, nil],
                [2, 1, 2, nil, nil, nil, nil, nil],
                [2, 4, 3, nil, nil, nil, nil],
                [3, 3, 1, nil, nil, nil, nil, nil],
                [2, 4, 4, nil, nil, nil, nil],
                [2, 2, 1, 3, nil, nil, nil, nil],
                [1, 1, 1, 3, nil, nil, nil],
                [3, 2, 1, 1, nil, nil, nil, nil],
                [2, 2, 1, 4, nil, nil, nil],
                [4, 1, 1, 2, 1, nil, nil, nil],
                [2, 4, 5, 1, 2, nil, nil],
                [1, 2, 1, 2, 1, nil, nil, nil],
                [1, 2, 6, 6, 2, nil, nil],
                [4, 2, 1, 2, 1, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1090,
            rows: [
                [1, nil, nil, 4, 1, nil, nil, 3],
                [1, 2, 2, 2, 1, 1, 2],
                [nil, 2, 2, nil, nil, 2, 3, nil],
                [3, nil, 3, 3, 7, nil, 2],
                [nil, 2, 3, nil, nil, 3, 3, nil],
                [3, nil, 4, 1, 5, nil, 2],
                [nil, 5, 1, nil, nil, 2, 4, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, 4, 4, nil, nil, 1, 4, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, 3, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1091,
            rows: [
                [2, nil, nil, nil, nil, nil, nil, 2],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 1, 4, 1, 1, nil, nil],
                [nil, 2, 1, 2, 1, 3, nil],
                [nil, 1, 5, 7, 2, 1, 1, nil],
                [nil, 1, 1, 1, 2, 3, nil],
                [nil, nil, 2, 2, 1, 3, nil, nil],
                [nil, nil, 2, 4, 3, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 2, 3, 1, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1092,
            rows: [
                [nil, nil, nil, nil, 2, 2, 1, 3],
                [1, 3, 3, 1, 1, 3, 1],
                [1, 1, 2, 1, 2, 1, 2, 2],
                [2, 1, 2, 2, 2, 2, 3],
                [3, 2, 6, 1, 3, 1, 6, 6],
                [2, 2, 2, 1, 1, 1, 4],
                [nil, nil, nil, nil, 1, 3, 1, 2],
                [nil, nil, nil, nil, 1, 2, 1],
                [nil, nil, nil, nil, 1, 2, 2, 1],
                [nil, nil, nil, nil, 3, 3, 3],
                [nil, nil, nil, nil, 2, 1, 2, 1],
                [nil, nil, nil, nil, 2, 1, 1],
                [nil, nil, nil, nil, 1, 2, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1093,
            rows: [
                [5, nil, 2, nil, nil, 2, nil, 1],
                [1, nil, 3, nil, 3, 1, 2],
                [nil, 2, nil, 1, 4, nil, 4, nil],
                [4, 2, nil, nil, nil, 2, nil],
                [nil, 2, nil, 1, 3, nil, 3, nil],
                [4, 1, nil, nil, nil, 3, nil],
                [4, nil, 1, 5, 5, 1, nil, 3],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 1, 3, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 1, 2, 1, 1, 7, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 3, 4, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1094,
            rows: [
                [nil, 1, 2, 2, 3, 1, 4, nil],
                [nil, 1, 2, 2, 1, 2, nil],
                [nil, 2, 1, 4, 1, 1, 2, nil],
                [nil, 2, 1, 2, 1, 1, nil],
                [nil, 1, 3, 3, 1, 1, 2, nil],
                [nil, 1, 3, 2, 2, 1, nil],
                [nil, 4, 1, 2, 1, 4, 4, nil],
                [nil, 1, 2, 1, 1, 6, nil],
                [nil, nil, 1, 2, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 1, 1, 1, nil, 1],
                [1, nil, 1, nil, nil, 1, 1],
                [1, nil, 1, nil, 1, 1, nil, 1],
                [1, nil, 1, nil, nil, 1, 1],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1095,
            rows: [
                [nil, 2, nil, nil, nil, nil, 4, nil],
                [1, 1, 2, 2, 3, 1, 5],
                [nil, nil, 3, 1, 1, 2, nil, nil],
                [nil, 2, 2, 1, 1, 3, nil],
                [nil, nil, 5, 4, 4, 1, nil, nil],
                [nil, 2, 1, 2, 3, 3, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, nil, 1, 6, nil, nil, nil],
                [nil, nil, 2, 5, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1096,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 4, 2, 4, nil, nil],
                [nil, nil, 1, 2, 1, 3, nil, nil],
                [nil, 3, 2, 1, 2, 1, nil],
                [nil, nil, 3, 3, 3, 1, nil, nil],
                [nil, 2, 3, 3, 1, 2, nil],
                [nil, 1, 2, 1, 3, 1, 2, nil],
                [1, 2, 1, 3, 3, 2, 1],
                [nil, 2, 2, 1, 4, 1, 4, nil],
                [1, 1, 2, 2, 1, 4, 1],
                [2, 1, 2, 1, 1, 2, 2, 2],
                [1, 3, nil, nil, nil, nil, 1],
                [6, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1097,
            rows: [
                [nil, nil, nil, 1, nil, 2, 1, nil],
                [nil, 1, 1, nil, 3, 4, nil],
                [nil, 4, 3, 2, 1, 2, nil, nil],
                [nil, 1, 1, 1, 2, 1, nil],
                [nil, 4, nil, nil, 1, nil, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, nil, 1, 1, 1, 1, 3, nil],
                [nil, 1, 1, 2, 1, 1, nil],
                [nil, 3, 3, 3, 3, 1, 3, nil],
                [nil, 2, 2, 3, 1, 1, nil],
                [nil, 1, 2, 1, 3, 1, 2, nil],
                [nil, 2, 3, 3, 3, 1, nil],
                [nil, 2, 2, 2, 1, 4, 1, nil],
                [nil, 4, 1, 2, 1, 1, nil],
                [nil, 4, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1098,
            rows: [
                [1, nil, 1, nil, 3, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 2, nil, 2, nil, 1, nil],
                [nil, 1, nil, 5, nil, 3, nil],
                [nil, nil, 3, 3, 5, 3, 1, nil],
                [nil, 2, 3, 2, 2, 1, nil],
                [nil, 5, 2, 1, 2, 3, 1, nil],
                [2, 5, 5, 5, 5, 2, 1],
                [nil, 3, 2, 3, 2, 3, 1, nil],
                [nil, 3, 1, 1, 4, 4, nil],
                [nil, nil, 2, 3, 1, 1, 3, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil, nil],
                [nil, nil, 3, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1099,
            rows: [
                [nil, nil, 3, 3, 3, 1, nil, nil],
                [nil, nil, 2, 3, 1, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, 4, 1, 3, 3, nil, nil],
                [nil, nil, 3, 1, 6, nil, nil],
                [nil, nil, 6, 6, 1, 1, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 1, 3, 1, 2, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 2, 1, 2, 2, nil, nil],
                [nil, nil, 2, 2, 3, nil, nil],
                [nil, nil, 1, 1, 1, 3, nil, nil],
                [nil, nil, 1, 3, 3, nil, nil],
                [nil, nil, 2, 3, 2, 4, nil, nil],
                [nil, nil, 1, 2, 4, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1100,
            rows: [
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, 2, 2, nil, 1, 1, nil],
                [nil, 1, 2, 2, 1, 1, 2, nil],
                [nil, 6, 4, nil, 5, 2, nil],
                [nil, 2, 2, 1, 1, 1, 5, nil],
                [nil, 5, 1, nil, 1, 2, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 5, 4, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [4, nil, nil, 1, 2, nil, nil, 1],
                [1, nil, nil, 2, nil, nil, 2],
                [1, nil, nil, 1, 2, nil, nil, 1],
                [3, nil, nil, 3, nil, nil, 1],
                [nil, 3, 1, 1, 3, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
    ]
}
