// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch124 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2461,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 2, 3, nil, nil],
                [nil, nil, 6, 1, 7, nil, nil],
                [nil, nil, 1, 5, 3, 1, nil, nil],
                [nil, nil, 5, 1, 2, nil, nil],
                [nil, nil, 3, 1, 4, 1, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, nil, 4, 2, 1, nil, nil],
                [nil, nil, 3, 1, 5, 2, nil, nil],
                [nil, nil, 1, 4, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2462,
            rows: [
                [nil, nil, 7, nil, nil, 1, nil, nil],
                [nil, 2, 1, nil, 3, 1, nil],
                [nil, 2, 1, 5, 3, 1, 3, nil],
                [nil, 2, 3, nil, 2, 1, nil],
                [nil, 4, 2, 1, 3, 2, 1, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2463,
            rows: [
                [nil, 1, nil, nil, nil, nil, 4, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, nil, 2, 1, 3, 4, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, nil, 2, 4, 1, 3, nil, nil],
                [nil, nil, 3, nil, 3, nil, nil],
                [5, 2, 1, nil, nil, 2, 1, 2],
                [nil, nil, 6, nil, 2, nil, nil],
                [1, 6, 1, nil, nil, 1, 6, 1],
                [nil, nil, 4, nil, 1, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, nil, 2, 1, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2464,
            rows: [
                [nil, nil, 1, 1, 3, nil, nil, nil],
                [nil, nil, 4, 3, 1, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, nil, 5, nil, 1, nil, 2, nil],
                [nil, 3, nil, 5, nil, 1, nil],
                [3, nil, 1, nil, 4, nil, 4, nil],
                [nil, 2, nil, 2, nil, 3, nil],
                [3, nil, 1, nil, 2, nil, 5, nil],
                [nil, 1, nil, 5, nil, 2, nil],
                [3, nil, 5, nil, 3, nil, 7, nil],
                [nil, 1, nil, 3, nil, 1, nil],
                [3, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2465,
            rows: [
                [nil, 3, 1, 3, 5, 1, 2, nil],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [1, 2, 3, 1, 2, 5, 4],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [4, 5, 2, 1, 3, 1, 5],
                [nil, 3, 1, 2, 6, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 5, 2, 5, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2466,
            rows: [
                [nil, nil, 1, 3, 1, nil, nil, nil],
                [nil, 2, nil, nil, 1, nil, nil],
                [nil, nil, 3, 2, 4, 2, 2, nil],
                [nil, 1, 3, 2, nil, nil, 3],
                [nil, nil, 5, 2, 1, 3, 2, nil],
                [nil, 1, 2, 1, nil, nil, 1],
                [nil, 3, nil, nil, 2, 4, 1, nil],
                [nil, 2, 1, 4, 2, 2, nil],
                [nil, 2, nil, nil, 5, 1, 3, nil],
                [nil, 2, 3, 1, 3, 1, nil],
                [nil, nil, 4, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2467,
            rows: [
                [1, nil, nil, nil, 3, nil, nil, nil],
                [2, nil, nil, nil, 3, nil, nil],
                [nil, 7, nil, nil, 1, 3, nil, nil],
                [nil, 1, nil, 1, nil, 4, nil],
                [nil, 4, nil, nil, 2, 1, nil, nil],
                [nil, 4, nil, 1, nil, 2, nil],
                [nil, 1, nil, nil, 1, 4, nil, nil],
                [2, nil, nil, 3, 2, 1, nil],
                [nil, 1, nil, nil, 3, 2, nil, nil],
                [2, nil, nil, 6, 2, 3, nil],
                [4, nil, nil, nil, 5, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 6, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2468,
            rows: [
                [1, 4, 1, 3, 2, 1, 6, 3],
                [1, 4, 1, 1, 2, 2, 2],
                [3, 3, 2, 1, 5, 1, 2, 3],
                [1, 3, 1, 1, 3, 1, 7],
                [1, 4, 1, 2, 1, 3, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2469,
            rows: [
                [nil, nil, nil, 3, 4, nil, nil, nil],
                [nil, nil, 5, 1, 5, nil, nil],
                [nil, nil, 1, 2, 2, 3, nil, nil],
                [nil, 2, 6, 2, 3, 3, nil],
                [nil, nil, 1, 4, 1, 5, nil, nil],
                [nil, 3, 1, 4, 2, 1, nil],
                [nil, nil, 3, 2, 1, 2, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 2, 3, 2, 1, nil, nil],
                [nil, nil, 7, 1, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2470,
            rows: [
                [nil, nil, 1, nil, nil, 6, nil, nil],
                [nil, 1, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, 4, 1, 3, nil],
                [3, nil, nil, nil, nil, 3, nil],
                [nil, 4, nil, nil, 1, 4, 1, nil],
                [2, nil, nil, nil, nil, 5, nil],
                [2, 5, 7, 4, nil, 2, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [1, 4, 5, 1, nil, 2, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2471,
            rows: [
                [4, nil, nil, 5, nil, 1, 4, 1],
                [7, nil, 6, nil, 3, nil, 3],
                [3, nil, nil, 1, nil, nil, nil, 2],
                [1, 2, 5, nil, nil, nil, 3],
                [1, nil, nil, 2, nil, nil, nil, 4],
                [1, 4, 4, nil, nil, nil, 1],
                [nil, nil, nil, 2, nil, 1, 2, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2472,
            rows: [
                [3, 2, 3, 2, 6, 2, 4, 1],
                [3, nil, nil, 1, nil, nil, 4],
                [2, 3, 1, 1, 2, 1, 3, 2],
                [2, nil, nil, 3, nil, nil, 2],
                [1, 2, 1, 1, 2, 1, 5, 1],
                [2, nil, nil, 2, nil, nil, 2],
                [nil, 1, nil, nil, 2, nil, nil, 1],
                [3, 1, 1, 3, 2, 1, 2],
                [nil, 1, nil, nil, 1, nil, nil, 3],
                [6, 1, 2, 3, 4, 1, 3],
                [nil, 2, nil, nil, 4, nil, nil, 3],
                [1, nil, nil, 4, nil, nil, 1],
                [nil, 3, nil, nil, 3, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2473,
            rows: [
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, 1, 3, 2, nil, nil],
                [nil, nil, 1, 3, 1, 4, nil, nil],
                [nil, 4, 2, 4, 1, 4, nil],
                [nil, nil, 1, 2, 1, 3, nil, nil],
                [nil, 3, 3, 1, 2, 2, nil],
                [nil, 1, 6, 3, 1, 2, 1, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 1, 2, 4, 1, 2, 1, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2474,
            rows: [
                [nil, 2, nil, 2, nil, 4, nil, 4],
                [1, nil, 4, nil, 1, nil, 4],
                [nil, 1, nil, 4, nil, 1, nil, 2],
                [2, nil, 5, nil, 1, nil, 4],
                [nil, 3, nil, 1, nil, 3, nil, 1],
                [2, nil, 1, nil, 3, nil, 1],
                [nil, 3, nil, 1, nil, 3, nil, 5],
                [4, nil, 1, nil, 5, nil, 5],
                [nil, 7, nil, 2, nil, 1, nil, 3],
                [1, nil, 3, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2475,
            rows: [
                [1, nil, 3, 2, 1, 3, nil, 2],
                [1, nil, nil, nil, nil, nil, 2],
                [1, 1, 3, 1, 2, 1, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 3, 2, 1, nil, nil],
                [nil, nil, 3, 1, 3, nil, nil],
                [nil, nil, 2, 1, 2, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 2, nil, 4, nil, 2],
                [3, nil, 2, nil, 4, nil, 1],
                [nil, 3, nil, 1, nil, 5, nil, 1],
                [5, nil, 1, nil, 4, nil, 1],
                [nil, 3, nil, 1, nil, 2, nil, 6],
                [1, nil, 3, nil, 2, nil, 1],
                [nil, 2, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2476,
            rows: [
                [nil, 4, 1, nil, nil, 4, 4, nil],
                [2, nil, nil, nil, nil, nil, 3],
                [2, 1, nil, nil, nil, nil, 3, 4],
                [4, nil, nil, nil, nil, nil, 1],
                [2, 1, nil, nil, nil, nil, 3, 1],
                [3, nil, nil, nil, nil, nil, 1],
                [2, 5, nil, nil, nil, nil, 3, 2],
                [4, nil, nil, nil, nil, nil, 1],
                [3, 2, nil, nil, nil, nil, 4, 2],
                [1, nil, nil, nil, nil, nil, 2],
                [1, 2, nil, nil, nil, nil, 1, 2],
                [1, 2, nil, nil, nil, 3, 1],
                [7, 3, nil, nil, nil, nil, 1, 4],
                [3, 1, nil, nil, nil, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2477,
            rows: [
                [nil, 1, nil, 2, nil, 3, nil, 1],
                [3, nil, 2, nil, 1, nil, 2],
                [nil, 2, nil, 2, nil, 1, nil, 2],
                [1, nil, 5, nil, 1, nil, 4],
                [nil, 7, nil, 3, nil, 1, nil, 4],
                [3, nil, 1, nil, 2, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2478,
            rows: [
                [2, nil, 1, nil, 2, nil, 1, nil],
                [nil, 4, nil, 1, nil, 2, nil],
                [1, nil, 3, nil, 1, nil, 3, nil],
                [nil, 3, nil, 2, nil, 3, nil],
                [1, nil, 5, nil, 4, nil, 2, nil],
                [nil, 1, nil, 4, nil, 1, nil],
                [1, nil, 2, nil, 4, nil, 2, nil],
                [nil, 1, nil, 6, nil, 1, nil],
                [1, nil, 2, nil, 1, nil, 2, nil],
                [nil, 1, nil, 2, nil, 3, nil],
                [1, nil, 3, nil, 1, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 2, 1, 1, 2, 1, 2, 1],
                [5, 1, 3, 1, 1, 1, 1],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2479,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 1, 1, 2, 1, 2, nil],
                [4, nil, nil, nil, nil, nil, 3],
                [1, nil, 6, 2, 1, 1, nil, 1],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 4, 3, 2, 1, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 2, 3, 3, nil, nil],
                [nil, nil, 2, 3, 1, nil, nil],
                [nil, nil, 5, 1, 3, 2, nil, nil],
                [nil, nil, 3, 1, 3, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2480,
            rows: [
                [2, nil, 1, nil, 6, nil, 1, nil],
                [nil, 3, nil, 1, nil, 3, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [1, nil, nil, nil, nil, nil, nil, 4],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 7, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
    ]
}
