// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch12 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 221,
            rows: [
                [nil, nil, 2, 1, nil, nil, nil, nil],
                [nil, 2, 2, 2, nil, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [2, 2, 2, 2, 2, 2, 2],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [2, 2, 2, 1, 1, 1, 1],
                [1, 1, 5, 5, 5, 5, 3, 3],
                [3, 3, 3, 3, 3, 3, 3],
                [3, 4, 4, 4, 1, 1, 1, 7],
                [1, 1, 1, 1, 1, 7, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 222,
            rows: [
                [nil, nil, nil, 6, 6, nil, nil, nil],
                [nil, 6, 6, nil, nil, nil, nil],
                [6, 6, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil],
                [2, 2, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil],
                [nil, nil, nil, 2, 4, nil, 4, 4],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, 1, 3],
                [nil, 3, 3, nil, nil, nil, nil],
                [1, 1, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 4, nil],
                [1, 1, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 223,
            rows: [
                [3, nil, nil, 3, 3, nil, nil, 3],
                [3, 3, 3, 3, 1, 1, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, nil, 1, 1, 4, nil, 4],
                [nil, 4, 4, nil, nil, 2, 2, nil],
                [2, nil, 2, 2, 2, nil, 2],
                [nil, 2, 2, nil, nil, 2, 1, nil],
                [nil, nil, 1, 3, 2, nil, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 5, 5, 5, 3, 5, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 224,
            rows: [
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, 2, nil, 2, 2, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 2, 2, nil, 2, 2, nil],
                [nil, 2, 2, 2, 2, 7, 3, nil],
                [nil, 3, 1, nil, 1, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [1, nil, nil, 1, 3, nil, nil, 3],
                [3, nil, nil, 4, nil, nil, 4],
                [4, nil, nil, 4, 3, nil, nil, 3],
                [3, nil, nil, 3, nil, nil, 5],
                [nil, 2, 2, 2, 2, 6, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 225,
            rows: [
                [nil, nil, nil, nil, 4, nil, nil, nil],
                [4, 1, 1, 1, nil, nil, nil],
                [1, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, 1, 3],
                [3, nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, nil, 5, 5, 5, 4],
                [4, nil, nil, nil, 4, nil, nil, 4],
                [4, 4, 4, 4, nil, nil, nil],
                [4, nil, nil, nil, 2, nil, nil, 2],
                [2, 2, 2, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, 3],
                [nil, nil, nil, 3, 3, 3, 3],
                [nil, nil, nil, 1, nil, nil, nil, 1],
                [nil, nil, nil, 1, 1, 5, 7],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 226,
            rows: [
                [nil, 1, 1, 1, 1, 1, 5, nil],
                [nil, 5, 5, 3, 1, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 4, 2, 2, 2, 2, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, 2, 2, 1, 1, nil, 1],
                [1, nil, 1, 1, 1, nil, 6],
                [6, nil, 6, 1, 1, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 4],
                [4, 4, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 227,
            rows: [
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, 2, 2, nil, nil],
                [nil, 2, 1, 1, 1, 3, nil],
                [nil, 3, 3, 3, 3, 3, 3, nil],
                [3, 1, 1, 1, 1, 5, 1],
                [nil, 1, 1, 1, 1, 1, 2, nil],
                [2, 2, 1, 2, 2, 4, 4],
                [2, 2, 2, 7, 2, 2, 4, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 2, 4, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 228,
            rows: [
                [nil, 1, 1, 5, 5, 5, 1, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [1, 1, 2, 2, 2, 2, 2],
                [nil, 2, 2, 5, 3, 3, 3, nil],
                [nil, 3, 3, 3, 3, 4, nil],
                [nil, 2, 2, 2, 2, 2, 7, nil],
                [nil, 3, 3, 3, 3, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 229,
            rows: [
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, nil, nil, 5, 5, nil, nil],
                [nil, nil, nil, nil, 1, 2, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, 2, 4],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 4, nil, nil, 4, 4, nil],
                [7, 7, nil, nil, 1, 3, nil],
                [nil, 3, 1, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, 3, 3, nil],
                [nil, 3, 3, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, 4, 4, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, 2, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 230,
            rows: [
                [nil, 2, 3, nil, nil, 2, 1, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 3],
                [3, 3, 3, 3, 3, 3, 3],
                [3, 2, 2, 2, 2, 2, 4, 4],
                [4, 4, 4, 7, 6, 6, 6],
                [nil, 5, 5, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 231,
            rows: [
                [nil, nil, 3, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil, 1],
                [1, 1, nil, 1, 1, nil, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [4, 4, 3, 3, 3, 3, nil],
                [nil, nil, 3, 3, nil, 3, 3, nil],
                [nil, 3, 3, nil, 3, 5, nil],
                [nil, nil, nil, 5, 6, 6, nil, nil],
                [nil, nil, 5, 5, 5, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, 7, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 232,
            rows: [
                [4, 4, nil, nil, nil, nil, 4, 4],
                [4, 3, nil, nil, nil, 3, 2],
                [2, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 3, 3],
                [3, 3, 3, 3, 3, 3, 3],
                [3, 1, nil, nil, nil, nil, 1, 6],
                [6, 6, 1, 1, 1, 1, 1],
                [nil, 1, 1, 1, 2, 2, 2, nil],
                [nil, 5, nil, 5, nil, 2, nil],
                [nil, 2, 2, 1, 1, 2, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 233,
            rows: [
                [nil, nil, 1, 1, 1, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 4, 4, 4, 4, 1, nil],
                [nil, 1, 1, 1, nil, nil, 1],
                [nil, nil, 1, 1, 1, 2, 2, nil],
                [nil, 2, 2, 2, nil, nil, 2],
                [nil, 2, nil, nil, 2, 3, 3, nil],
                [nil, 3, 3, 3, 1, 1, nil],
                [nil, 1, nil, nil, 6, 6, 1, nil],
                [nil, 1, 1, 1, 7, 7, nil],
                [nil, nil, 3, 3, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 234,
            rows: [
                [1, 3, 3, 3, 3, 3, 3, 3],
                [3, nil, 1, nil, 1, nil, 1],
                [nil, 1, 2, 2, 2, 2, 2, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, 1, 1, 2, 2, 2, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, 2, 2, 2, 2, 1, nil],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [1, nil, 1, nil, 1, nil, 1],
                [1, 4, 4, 4, 7, 2, 2, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 2, 2, 5, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 235,
            rows: [
                [nil, 2, 1, 1, 1, 1, nil, nil],
                [1, 1, nil, nil, 1, nil, 1],
                [nil, nil, 1, 4, 4, 4, nil, 4],
                [1, 1, nil, 2, nil, nil, 2],
                [nil, 2, 2, 2, nil, 2, 2, 3],
                [3, nil, nil, 3, nil, 3, 3],
                [nil, 3, nil, 1, 2, 2, nil, 2],
                [2, 2, 2, nil, nil, nil, nil],
                [nil, nil, 4, nil, nil, 4, nil, 4],
                [1, nil, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 5, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 4, 4, 6, 5, 5, 5, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 236,
            rows: [
                [nil, nil, nil, nil, 3, nil, 3, 3],
                [3, 1, 1, 1, 1, 1, 1],
                [2, 2, 2, 1, 1, 2, 2, 2],
                [2, 2, 2, 1, 2, 2, 2],
                [2, 2, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1, 6],
                [nil, nil, nil, nil, 6, 6, 6],
                [nil, nil, nil, nil, 5, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, 4, 4, 5],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 237,
            rows: [
                [4, nil, nil, 4, nil, 4, 2, 2],
                [2, nil, 2, nil, 2, nil, 1],
                [1, nil, nil, 1, nil, nil, nil, 1],
                [1, 1, 1, nil, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, nil, 1],
                [3, 5, 5, nil, nil, nil, 5],
                [nil, nil, nil, 2, nil, 2, 2, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, nil, 6, nil, 6, nil, nil],
                [nil, nil, nil, 3, nil, 3, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 7, nil, 3, 3, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 238,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, 6, 6, nil, nil, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [3, 3, 2, 2, 2, 2, 2, 2],
                [2, nil, 4, nil, 4, nil, 4],
                [4, 1, 1, 1, 5, 5, 5, 5],
                [5, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 239,
            rows: [
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [2, nil, 2, nil, 2, nil, 2],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, 6, 6, nil, nil, 7],
                [7, nil, nil, nil, nil, nil, 1],
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, 4, nil, nil, nil, nil, 4, nil],
                [nil, 4, nil, nil, nil, 4, nil],
                [nil, nil, 4, nil, nil, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, nil, nil, 3, nil, nil],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, nil, 1, 6, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 240,
            rows: [
                [2, nil, nil, 2, 1, nil, nil, 1],
                [1, nil, 1, nil, 3, nil, 3],
                [nil, 3, 3, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, 4, 2, nil, nil, 2, 2, nil],
                [2, 6, nil, nil, nil, 1, 1],
                [1, nil, 1, 2, 2, 2, nil, 2],
                [2, 2, nil, nil, nil, 2, 4],
                [4, nil, 4, 1, 1, 1, nil, 3],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, 1, 3, nil, nil, 5, 1, nil],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, 1, 3, nil, nil, 6, 6, nil],
                [3, nil, 3, nil, 3, nil, 3],
                [3, nil, nil, 3, 3, nil, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
    ]
}
