// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch08 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 141,
            rows: [
                [1, nil, nil, 1, 1, nil, nil, 3],
                [2, 2, 2, 3, 3, 2, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 1, 1, nil, nil, 1, 7, nil],
                [1, nil, 2, 2, 2, nil, 2],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [nil, nil, 5, 6, 6, nil, nil],
                [nil, 2, 2, nil, nil, 1, 4, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, 4, 3, 3, 3, 3, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 142,
            rows: [
                [3, 3, nil, nil, nil, nil, nil, nil],
                [3, 3, nil, nil, nil, nil, nil],
                [3, 1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil],
                [1, 4, 4, nil, nil, nil, nil, nil],
                [4, 4, 2, nil, nil, nil, nil],
                [2, 2, 2, 2, nil, nil, nil, nil],
                [3, 3, 3, 3, nil, nil, nil],
                [3, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 2, nil, nil, nil],
                [2, 2, 2, 2, 2, nil, nil, nil],
                [2, 5, 5, 5, 5, nil, nil],
                [5, 4, 2, 2, 2, nil, nil, nil],
                [2, 2, 2, 1, 1, nil, nil],
                [1, 6, 4, 4, 4, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 143,
            rows: [
                [nil, nil, 5, nil, nil, 5, nil, nil],
                [nil, 5, 5, 5, 4, 4, nil],
                [nil, 4, 4, 2, 2, 2, 2, nil],
                [1, 1, 2, 2, 2, 2, 2],
                [nil, 2, 2, 1, 1, 1, 1, nil],
                [1, 1, 1, 1, 1, 1, 3],
                [nil, 4, 4, 6, 3, 3, 3, nil],
                [nil, 3, 3, 1, 1, 1, nil],
                [nil, 1, 1, 1, 2, 2, 2, nil],
                [nil, 2, 3, 3, 3, 7, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 144,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 1, 1, 1, nil, nil],
                [nil, 1, 4, 4, 4, 2, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 3, nil, 3, 3, nil, 3, nil],
                [3, 3, 3, 3, 3, 5, 5],
                [nil, 5, nil, 5, 1, nil, 6, nil],
                [1, 1, 1, 4, 1, 7, 1],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 145,
            rows: [
                [nil, nil, 1, 1, 3, 3, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 7, 7, 4, nil, nil],
                [nil, nil, 5, 3, 3, 3, nil, nil],
                [nil, nil, 4, 5, 5, nil, nil],
                [nil, nil, 2, 2, 2, 4, nil, nil],
                [nil, nil, 4, 4, 6, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 146,
            rows: [
                [nil, nil, nil, 6, 6, nil, nil, nil],
                [nil, nil, 6, 6, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [2, 2, 2, 1, 1, 1, 1],
                [nil, 4, 4, 4, 4, 4, 4, nil],
                [3, 3, 5, 3, 3, 3, 3],
                [nil, 3, 2, 2, 2, 2, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 2, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, 1, 1, 3, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 147,
            rows: [
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, 2, 1, 1, 1, 1, 1],
                [5, 5, nil, nil, nil, nil, 5, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, 4, 4, 4, 3, 3],
                [3, 2, nil, nil, nil, nil, 2, 1],
                [1, 6, 6, 6, 3, 3, 3],
                [3, 3, nil, nil, nil, nil, 2, 2],
                [2, 2, 2, 2, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, nil, nil, nil, nil, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 148,
            rows: [
                [nil, nil, nil, nil, 1, 1, 1, nil],
                [nil, nil, 1, 1, 1, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, 4, 6, 2, 2, 2, nil],
                [nil, 2, 2, 3, 3, 3, nil, nil],
                [4, 4, 4, 2, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [2, 2, 4, 4, 4, nil, nil],
                [3, 3, 3, 6, 6, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 5, 3, 3, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 149,
            rows: [
                [3, nil, nil, nil, 3, nil, nil, 3],
                [3, 3, nil, nil, 3, nil, 3],
                [nil, nil, 3, nil, 3, nil, 3, nil],
                [4, nil, 4, 4, nil, 4, nil],
                [nil, nil, 4, nil, 4, nil, 4, nil],
                [4, nil, 6, 6, nil, 5, nil],
                [5, 5, 1, 1, 2, 2, nil, 2],
                [nil, nil, 1, 1, 1, 1, 1],
                [1, 1, 1, 2, 2, 2, nil, 2],
                [nil, nil, 2, 2, 2, 2, 2],
                [nil, 2, 2, nil, nil, 2, nil, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 150,
            rows: [
                [4, nil, nil, 4, 4, nil, nil, 4],
                [4, nil, 4, 4, 4, nil, 1],
                [nil, 1, nil, 1, 1, nil, 1, nil],
                [nil, 3, 2, 3, 5, 5, nil],
                [nil, 5, nil, 2, 2, nil, 2, nil],
                [nil, 2, 2, 2, 5, 5, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, 3, 3, 3, 3, 3, 3],
                [3, nil, nil, nil, nil, nil, 6],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 151,
            rows: [
                [nil, nil, nil, 5, nil, nil, nil, nil],
                [nil, nil, 5, nil, nil, nil, nil],
                [nil, 5, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, 1, 1, 1, 1, 3, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, 3, 1, 1, 2, 2, 2, nil],
                [nil, 2, 1, 7, 6, 6, nil],
                [nil, 4, 4, 4, 4, 4, 4, nil],
                [nil, 4, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 152,
            rows: [
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [2, nil, 2, 2, 2, nil, 1],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [1, nil, 1, 1, 1, nil, 1],
                [1, 1, 1, 1, 1, 2, 2, 2],
                [2, 2, 3, nil, 3, 3, 3],
                [3, 3, 1, 1, 1, 1, 1, 1],
                [1, 1, 4, nil, 4, 4, 4],
                [nil, 4, 4, nil, nil, 1, 1, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, 6, nil, nil, 6, 6, nil],
                [nil, nil, 6, 5, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 153,
            rows: [
                [nil, nil, 2, 2, nil, nil, nil, nil],
                [nil, 2, 2, 2, nil, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [3, 3, 4, 4, 4, 4, 4],
                [nil, 3, 3, 3, 3, 3, nil, nil],
                [3, 3, 3, 3, 1, 1, 1],
                [1, 1, 4, 4, 1, 1, 1, 1],
                [1, 4, 4, 4, 4, 4, 1],
                [4, 1, 1, 1, 5, 1, 1, 1],
                [1, 6, 5, 5, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 154,
            rows: [
                [5, nil, nil, 5, 5, nil, nil, 5],
                [5, 2, 4, 4, 4, 4, 4],
                [nil, 4, 4, nil, nil, 2, 2, nil],
                [2, nil, 2, 2, 2, nil, 2],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [2, nil, 2, 2, 3, nil, 3],
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 4, 4, 4, 7, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 155,
            rows: [
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, 2, nil, 1, 1, nil],
                [nil, 1, 3, 3, 3, 3, 3, nil],
                [nil, 3, 1, nil, 1, 1, nil],
                [nil, 2, 2, 2, 6, 3, 3, nil],
                [nil, 3, 3, nil, 3, 7, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [5, nil, nil, 5, 5, nil, nil, 4],
                [1, nil, nil, 4, nil, nil, 4],
                [1, nil, nil, 4, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 156,
            rows: [
                [nil, 4, 4, 4, 4, 4, 4, nil],
                [nil, 4, 4, 1, 3, 3, nil],
                [nil, nil, 3, 3, 3, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 2, 2, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, 2, 2, 2, 2, nil, 2],
                [1, nil, 1, 1, 1, nil, 1],
                [1, nil, 1, 1, 1, 1, nil, 6],
                [6, nil, nil, nil, nil, nil, 6],
                [1, 1, 1, 1, 1, 1, 5, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 157,
            rows: [
                [nil, 4, 4, nil, nil, 4, 4, nil],
                [4, 5, 1, 1, 1, 1, 1],
                [3, 3, 3, 1, 1, 1, 1, 1],
                [1, 7, 7, 7, 5, 2, 2],
                [1, 1, 1, 1, 3, 3, 3, 1],
                [1, 1, 1, 1, 1, 1, 2],
                [nil, 2, 2, nil, nil, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 158,
            rows: [
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 3, nil, nil, nil, nil, 3, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [3, 3, nil, nil, nil, nil, 3, 3],
                [4, 4, 1, 1, 1, 1, 1],
                [2, 2, nil, nil, nil, nil, 2, 4],
                [4, 4, 4, 3, 3, 3, 3],
                [nil, 3, 3, 3, 3, 3, 6, nil],
                [nil, 2, nil, 5, nil, 5, nil],
                [nil, 5, 2, 2, 2, 2, 2, nil],
                [nil, 2, nil, 2, nil, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 159,
            rows: [
                [1, 1, nil, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil],
                [1, 1, 5, nil, nil, nil, nil, nil],
                [5, 3, 3, nil, nil, nil, nil],
                [3, 3, 3, 3, nil, nil, nil, nil],
                [3, 5, 1, 1, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [1, 1, 2, 2, 4, nil, nil, nil],
                [4, 4, 4, 6, 2, nil, nil],
                [2, 2, 2, 5, 5, nil, nil, nil],
                [3, 3, 2, 2, 2, nil, nil],
                [2, 5, 5, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 160,
            rows: [
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [7, 7, 1, 1, 1, 1, 1],
                [nil, 1, 3, 3, 3, 3, 5, nil],
                [4, 4, 4, 4, 4, 1, 1],
                [nil, 4, 1, 1, 1, 1, 1, nil],
                [nil, 6, 1, 1, 1, 1, nil],
                [nil, 3, 3, 3, 3, 3, 1, nil],
                [nil, 1, 3, 1, 1, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
    ]
}
