// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch01 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1,
            rows: [
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, 3, 3, 3, 3, 3, nil, nil],
                [nil, 4, 4, 4, 4, 4, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 1
        ),
        LevelTemplate(
            levelNumber: 2,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 2, 2, 1, 1, 2, 2, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 3, 3, 3, 3, 3, 4, 4],
                [4, 4, 4, 5, 5, 5, 5],
                [5, 2, 2, 2, 2, 2, 2, 2],
                [2, 3, 3, 3, 3, 1, 1],
                [1, 6, 6, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 3,
            rows: [
                [1, nil, nil, 1, nil, 1, nil, 1],
                [1, 1, 1, nil, nil, 1, 1],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 3, 3, 3, 3, 3],
                [nil, nil, 3, nil, nil, 6, nil, nil],
                [nil, 6, 6, 6, 1, 1, 2],
                [nil, nil, 2, 2, 2, 2, 2, 2],
                [nil, nil, 2, 2, 2, 2, 2],
                [nil, nil, 2, 2, 2, 2, 2, 1],
                [nil, nil, 1, 5, 5, 1, 1],
                [nil, nil, nil, 1, 1, nil, 1, 1],
                [nil, nil, nil, 1, nil, 1, 1],
                [nil, nil, nil, 1, 1, nil, 1, 1],
                [nil, nil, nil, 4, nil, 4, 4],
                [nil, nil, nil, nil, nil, nil, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 4,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 5, 5, 5],
                [5, 2, 2, 2, 2, 2, 2],
                [2, 2, 2, 3, 3, 3, 3, 3],
                [4, 4, 4, 4, 4, 4, 4],
                [4, 6, 6, 4, 4, 2, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 5,
            rows: [
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, 3, 5, nil, 5, nil],
                [nil, nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, 4],
                [nil, nil, 4, nil, 4, nil, 4, nil],
                [2, 2, 2, 2, 2, nil, 2],
                [nil, 2, 2, nil, 2, 2, nil, nil],
                [2, 2, 2, nil, nil, 2, 2],
                [nil, nil, 2, 2, 2, 5, 5, 1],
                [1, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, 3, nil, nil, nil, 3],
                [nil, 3, 3, nil, nil, 3, 3],
                [nil, 3, nil, 3, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 6, nil, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 6,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 3, 3, 3],
                [3, 3, 3, 3, 3, 1, 1, 6],
                [6, 2, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 2, 2, 2, 2],
                [7, 2, 2, 1, 4, 4, 4, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 6, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 7,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, 3, nil],
                [nil, nil, nil, 3, 3, 3, nil, nil],
                [nil, 5, 5, 5, 5, nil, nil],
                [nil, nil, nil, 5, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, 2, nil, nil],
                [2, 2, 2, 1, 1, 1, nil],
                [nil, 4, 4, 4, 4, 4, nil, nil],
                [6, 6, 2, 2, 2, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [nil, 2, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 8,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 2, 2, 2],
                [2, 2, 2, 2, 2, 1, 1, 1],
                [1, 3, 3, 3, 3, 3, 5],
                [5, 5, 5, 1, 4, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 4],
                [4, 4, 4, 4, 1, 7, 7, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 9,
            rows: [
                [nil, 1, nil, nil, nil, 1, 1, nil],
                [nil, nil, 3, nil, nil, nil, 3],
                [1, nil, 2, 1, 1, 1, nil, 1],
                [2, 2, nil, 2, nil, 2, 2],
                [2, nil, 2, 2, 2, 2, nil, 2],
                [1, 1, nil, 1, nil, 1, 1],
                [nil, 5, nil, 5, 5, nil, 5, nil],
                [5, 1, 1, nil, 1, 1, 1],
                [nil, 4, nil, 4, 4, nil, 4, nil],
                [4, 4, 1, nil, 6, 1, 1],
                [1, nil, 1, nil, nil, 1, nil, 1],
                [6, 1, nil, nil, nil, 1, 1],
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 10,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 2, 5],
                [5, 5, 5, 5, 3, 1, 1],
                [1, 1, 1, 1, 2, 2, 2, 6],
                [6, 3, 3, 3, 3, 3, 3],
                [1, 1, 1, 1, 4, 2, 2, 1],
                [1, 1, 2, 2, 2, 2, 2],
                [2, 2, 2, 2, 2, 4, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 11,
            rows: [
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [1, 1, 6, 6, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [1, 1, 5, 5, 5, 1, 1],
                [nil, 1, 3, 3, 1, 6, 6, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 4, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 12,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 2, 2, 2],
                [2, 2, 5, 5, 5, 5, 1, 5],
                [5, 5, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 2, 2, 2],
                [2, 2, 2, 2, 4, 4, 4],
                [3, 1, 1, 6, 3, 3, 3, 1],
                [1, 6, 3, 3, 3, 3, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 13,
            rows: [
                [1, nil, nil, nil, 1, nil, nil, 1],
                [2, 2, nil, nil, 2, nil, 2],
                [nil, nil, 2, nil, 2, nil, 2, nil],
                [4, nil, 4, 4, nil, 4, nil],
                [nil, nil, 5, nil, 5, nil, 1, nil],
                [1, nil, 3, 3, nil, 3, nil],
                [3, 3, 3, 3, 5, 5, nil, 2],
                [nil, nil, 2, 2, 1, 1, 3],
                [3, 5, 1, 1, 1, 1, nil, 1],
                [nil, nil, 1, 3, 3, 1, 1],
                [nil, 5, 6, nil, nil, 6, nil, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 14,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 3, 3, 3, 3, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 2, 2, 2, 2, 2],
                [2, 3, 3, 4, 4, 4, 4],
                [4, 4, 4, 4, 1, 1, 1, 1],
                [1, 1, 1, 5, 5, 5, 3],
                [5, 5, 5, 5, 2, 6, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 15,
            rows: [
                [1, 1, nil, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, nil, nil],
                [1, 1, 3, nil, nil, nil, nil],
                [3, 3, 5, nil, nil, nil, nil, nil],
                [5, 5, 5, nil, nil, nil, nil],
                [5, 4, 4, 4, nil, nil, nil, nil],
                [4, 4, 4, 6, nil, nil, nil],
                [6, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [1, 1, 1, 1, 1, nil, nil, nil],
                [2, 2, 2, 2, 2, nil, nil],
                [2, 2, 2, 2, 2, nil, nil, nil],
                [2, 3, 3, 3, 3, nil, nil],
                [3, 2, 2, 2, 2, 5, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 16,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 2, 2, 1],
                [3, 3, 3, 3, 3, 3, 3, 2],
                [1, 1, 1, 3, 3, 3, 4],
                [4, 4, 4, 4, 1, 1, 1, 1],
                [1, 1, 1, 2, 2, 2, 2],
                [5, 5, 5, 1, 2, 2, 2, 2],
                [2, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 2, 7, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 17,
            rows: [
                [nil, nil, 2, nil, nil, 4, nil, nil],
                [nil, 4, 4, 1, 1, 3, nil],
                [nil, 3, 3, 3, 3, 3, 2, nil],
                [2, 2, 2, 1, 1, 1, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [1, 1, 2, 2, 2, 2, 2],
                [nil, 5, 5, 5, 5, 5, 5, nil],
                [nil, 5, 5, 3, 3, 1, nil],
                [nil, 1, 1, 1, 1, 1, 5, nil],
                [nil, 6, 6, 4, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 18,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [5, 5, 5, 5, 1, 1, 4],
                [2, 2, 2, 3, 3, 1, 1, 1],
                [1, 1, 4, 4, 4, 4, 4],
                [4, 4, 3, 3, 3, 3, 3, 1],
                [2, 2, 2, 2, 2, 2, 2],
                [2, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 7, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 19,
            rows: [
                [3, nil, nil, nil, 3, nil, nil, 3],
                [3, 1, nil, nil, 1, nil, 1],
                [nil, nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 4, 4, nil, 2, nil],
                [nil, nil, 2, nil, 2, nil, 2, nil],
                [2, nil, 2, 2, nil, 3, nil],
                [1, 1, 1, 1, 1, 1, nil, 1],
                [nil, nil, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 2, nil, 4],
                [nil, nil, 4, 5, 3, 3, 3],
                [nil, 3, 3, nil, nil, 4, nil, nil],
                [4, 4, nil, nil, nil, 5, 5],
                [nil, 5, 2, nil, nil, 2, nil, nil],
                [2, 2, nil, nil, nil, 6, 6],
                [1, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 20,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1],
                [2, 2, 2, 2, 2, 2, 2, 2],
                [2, 2, 6, 6, 6, 6, 1],
                [1, 1, 3, 3, 3, 3, 3, 3],
                [3, 3, 3, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 2, 2, 4, 4, 2],
                [2, 1, 1, 1, 2, 2, 2, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
    ]
}
