// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch40 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 781,
            rows: [
                [1, nil, nil, nil, nil, 1, 1, 1],
                [1, 3, 3, nil, nil, 3, nil],
                [3, nil, 3, 3, nil, 3, 3, 3],
                [nil, 3, nil, nil, 3, 3, nil],
                [3, nil, 1, 1, 1, 1, 1, 2],
                [2, 1, 1, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, 2, nil, 2],
                [2, nil, nil, nil, 2, nil, 2],
                [1, 1, 1, 2, 2, 2, 2, 2],
                [1, 1, 1, nil, 1, 1, 1],
                [1, 1, 5, 5, 4, 4, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 6, 6, 6, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 782,
            rows: [
                [2, nil, nil, nil, nil, nil, nil, 3],
                [3, nil, 3, nil, 3, nil, nil],
                [nil, 3, 1, 2, 2, 2, 2, nil],
                [nil, 1, nil, nil, 1, 1, 1],
                [nil, 1, 1, nil, 2, 2, 2, nil],
                [2, 2, 2, nil, nil, nil, nil],
                [1, 1, 1, nil, nil, nil, 1, 6],
                [5, nil, 5, nil, nil, nil, 5],
                [6, 6, 1, nil, nil, 1, 2, nil],
                [2, nil, nil, nil, 2, 1, nil],
                [1, nil, 1, nil, nil, 2, 2, 4],
                [4, 1, 1, 1, 1, 1, 1],
                [1, 2, 2, 2, 1, 3, 1, 2],
                [2, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 783,
            rows: [
                [nil, 1, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, nil, 1, 2, nil],
                [nil, 2, 2, 2, 1, nil, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, 2, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, 1, 1, nil],
                [nil, nil, 1, nil, 4, 4, nil, nil],
                [nil, 4, 4, 4, 4, 5, nil],
                [nil, 5, 5, 5, nil, nil, 5, nil],
                [nil, 2, 2, nil, 1, nil, nil],
                [nil, 1, nil, nil, 1, nil, 6, nil],
                [nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, nil, 1, 1, nil, 1, nil],
                [nil, 3, nil, 3, 3, 3, nil],
                [nil, 3, 3, nil, 3, 3, 4, nil],
                [nil, 2, 2, 2, 2, 4, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 784,
            rows: [
                [1, 1, 5, 5, nil, 5, 5, nil],
                [nil, 5, 1, nil, 1, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil, nil],
                [3, 3, 3, 3, nil, 3, 1],
                [1, nil, nil, 1, 1, nil, 1, nil],
                [2, 2, 2, 2, nil, 1, 1],
                [nil, 1, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, 4, nil, 3, nil, 3],
                [nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, 1, nil, nil, 1, 1, nil],
                [1, 6, nil, 6, 6, 1, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [nil, nil, 1, nil, nil, 1, 1],
                [nil, 1, 1, 1, nil, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 785,
            rows: [
                [nil, nil, nil, nil, 2, 2, nil, nil],
                [2, 2, nil, nil, 1, nil, 1],
                [nil, 1, 1, 1, nil, nil, nil, nil],
                [1, nil, 1, nil, nil, nil, 1],
                [nil, 1, nil, 1, nil, nil, 1, 1],
                [nil, nil, nil, 1, 1, nil, 1],
                [nil, nil, nil, nil, nil, 1, 1, 1],
                [1, nil, 4, 3, 3, 3, 3],
                [6, nil, 6, nil, nil, 2, 2, 2],
                [2, nil, 2, nil, 2, 2, nil],
                [1, nil, 1, nil, nil, 1, 1, 1],
                [1, 1, 1, 1, 3, 3, 3],
                [2, 5, 5, 5, nil, 4, 4, 4],
                [4, 4, 4, 2, 2, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 786,
            rows: [
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, 3, nil, nil, 3, nil],
                [nil, nil, nil, 3, 3, 3, 2, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, 1, 1, nil, nil, 1, nil],
                [nil, nil, nil, 6, 6, nil, 6, nil],
                [nil, nil, nil, nil, 6, 6, nil],
                [nil, 1, nil, 4, nil, 1, 1, nil],
                [nil, nil, 1, 1, nil, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 5, 5, nil],
                [nil, 4, nil, 4, nil, 2, nil, 2],
                [4, nil, 4, nil, 2, nil, 2],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 787,
            rows: [
                [nil, nil, nil, 2, 2, 2, 3, nil],
                [nil, nil, 3, nil, nil, nil, 4],
                [4, nil, 4, nil, nil, 4, 4, 4],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, nil, 1, nil, 1],
                [nil, 5, nil, 2, nil, 2, 2],
                [3, nil, 3, 3, nil, nil, 3, 3],
                [nil, 3, nil, 3, 3, nil, nil],
                [nil, nil, nil, nil, 2, 2, nil, 2],
                [nil, 2, nil, 2, 2, 2, nil],
                [nil, 2, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, 1, 1, nil, 1],
                [1, nil, 1, nil, 1, 5, 2],
                [2, 2, nil, nil, 5, nil, 5, 5],
                [1, 1, 1, 1, 1, 1, 6],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 788,
            rows: [
                [nil, nil, nil, nil, 3, 3, 3, nil],
                [nil, 3, nil, nil, 2, nil, nil],
                [nil, 2, 2, 2, 2, nil, 1, nil],
                [nil, 1, nil, 2, 2, 2, nil],
                [nil, 2, nil, 2, nil, nil, nil, nil],
                [nil, 2, nil, 2, 2, 2, nil],
                [nil, 2, nil, nil, nil, 3, 1, nil],
                [nil, 1, 5, 5, 5, nil, nil],
                [nil, nil, 1, nil, 4, 4, nil, nil],
                [nil, 4, 4, 4, 1, 1, nil],
                [nil, 1, 6, 6, 6, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 789,
            rows: [
                [nil, nil, nil, 5, 1, 4, 1, nil],
                [nil, nil, 1, nil, nil, nil, 1],
                [1, nil, 1, nil, nil, 1, 1, 1],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, nil, 1, nil, 2],
                [nil, 2, nil, 2, nil, 2, 2],
                [3, nil, 3, 3, nil, nil, 3, 3],
                [nil, 3, nil, 3, 3, nil, nil],
                [nil, nil, nil, nil, 3, 3, nil, 1],
                [nil, 1, nil, 4, 4, 1, nil],
                [nil, 1, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, 2, nil, 5, nil],
                [nil, nil, nil, nil, 5, 5, nil, 4],
                [4, nil, 4, nil, 2, 2, 2],
                [2, 1, nil, nil, 1, nil, 2, 2],
                [2, 2, 2, 2, 2, 5, 6],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 790,
            rows: [
                [nil, 1, 1, nil, 1, 1, 4, 4],
                [4, 4, 4, 2, 2, 2, 2],
                [nil, 2, nil, nil, 2, nil, 2, 1],
                [nil, 1, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, 1, 1, 2, nil],
                [2, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, 1, nil, 6, 6, nil],
                [nil, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, 1, 1, 1, nil, 1, 1],
                [1, 2, 2, 2, 2, 3, 3, 3],
                [3, nil, 3, 3, nil, nil, nil],
                [nil, 3, nil, nil, 1, nil, nil, nil],
                [2, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, 2, 5, nil],
                [nil, 5, 5, 5, 1, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 791,
            rows: [
                [nil, nil, nil, 1, 2, 2, 2, nil],
                [nil, nil, 1, nil, nil, nil, 1],
                [1, nil, 1, nil, nil, 1, 1, 5],
                [nil, nil, 5, 1, 1, nil, nil],
                [nil, nil, 1, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, 1],
                [1, nil, 1, 1, nil, nil, 1, 1],
                [nil, 1, nil, 4, 4, nil, nil],
                [nil, nil, nil, nil, 4, 4, nil, 4],
                [nil, 4, nil, 2, 2, 2, nil],
                [nil, 3, nil, nil, 3, 3, nil, nil],
                [nil, nil, nil, 3, nil, 3, nil],
                [nil, nil, nil, nil, 3, 2, nil, 2],
                [5, nil, 5, nil, 5, 2, 3],
                [3, 3, nil, nil, 3, nil, 2, 2],
                [2, 6, 2, 2, 2, 2, 2],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 792,
            rows: [
                [nil, nil, nil, nil, 1, 1, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, 2, 2, 2, 2, nil, 2, nil],
                [nil, 2, nil, 2, 2, 2, nil],
                [nil, 2, nil, 1, nil, nil, nil, nil],
                [nil, 1, nil, 1, 1, 1, nil],
                [nil, 1, nil, nil, nil, 1, 1, nil],
                [nil, 1, 3, 3, 3, nil, nil],
                [nil, nil, 3, nil, 3, 4, nil, nil],
                [nil, 4, 4, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 5, 5, 5, 6, 2, nil],
                [nil, 4, nil, 4, nil, 6, nil, 6],
                [2, nil, 2, nil, 2, nil, 2],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 793,
            rows: [
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, nil, 1, nil, nil, nil, 1],
                [1, nil, 5, nil, nil, 5, 5, 5],
                [nil, nil, 5, 3, 3, nil, nil],
                [nil, nil, 1, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, 1],
                [1, nil, 1, 1, nil, nil, 2, 2],
                [nil, 2, nil, 2, 2, nil, nil],
                [nil, nil, nil, nil, 2, 4, nil, 4],
                [nil, 4, nil, 3, 3, 3, nil],
                [nil, 3, nil, nil, 3, 3, nil, nil],
                [nil, nil, nil, 3, nil, 2, nil],
                [nil, nil, nil, nil, 2, 2, nil, 2],
                [2, nil, 2, nil, 2, 1, 1],
                [1, 1, nil, nil, 2, nil, 2, 2],
                [2, 4, 4, 4, 1, 3, 6],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 794,
            rows: [
                [nil, 1, 1, nil, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 2, 2],
                [nil, 2, nil, nil, 2, nil, 3, 1],
                [nil, 1, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, 1, 1, 1, nil],
                [2, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, 2, nil, 2, 2, nil],
                [nil, nil, nil, 2, nil, nil, 2],
                [nil, nil, nil, 2, nil, 1, 1, nil],
                [nil, 1, 1, 1, nil, 1, 1],
                [1, 1, 1, 1, 1, 6, 6, 3],
                [3, nil, 3, 4, nil, nil, nil],
                [nil, 4, nil, nil, 4, nil, nil, nil],
                [4, nil, nil, nil, nil, 4, nil],
                [nil, nil, nil, nil, nil, 3, 3, nil],
                [nil, 5, 5, 5, 5, 3, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 795,
            rows: [
                [nil, nil, nil, 2, 2, 2, 2, nil],
                [nil, nil, 2, nil, nil, nil, 3],
                [3, nil, 1, nil, nil, 5, 3, 4],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 4, 2, nil, 2, nil, 2],
                [nil, 1, nil, 1, nil, 1, 1],
                [1, nil, 1, 1, nil, nil, 1, 1],
                [nil, 1, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil, 5],
                [nil, 5, nil, 5, 5, 4, nil],
                [nil, 2, nil, nil, 2, 2, nil, nil],
                [nil, nil, nil, 2, nil, 2, nil],
                [nil, nil, nil, nil, 2, 3, nil, 3],
                [3, nil, 1, nil, 1, 2, 2],
                [2, 3, nil, nil, 3, nil, 3, 3],
                [1, 1, 1, 1, 6, 1, 1],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 796,
            rows: [
                [2, 2, nil, nil, nil, nil, nil, 5],
                [5, 5, nil, nil, 1, nil, nil],
                [2, nil, nil, nil, 2, 3, nil, 3],
                [nil, nil, nil, nil, nil, 3, nil],
                [nil, 3, nil, nil, 3, 3, 2, 6],
                [6, 6, 1, 1, 2, 2, 2],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [4, 4, 4, 4, 1, 1, 2],
                [2, 2, 2, 1, 1, 1, 1, 2],
                [2, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 797,
            rows: [
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, nil, 2, nil, nil, nil, 2],
                [2, nil, 2, nil, nil, 2, 2, 2],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, 1],
                [1, nil, 1, 4, nil, nil, 4, 4],
                [nil, 4, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, 1, 2, nil, 2],
                [nil, 2, nil, 2, 2, 2, nil],
                [nil, 2, nil, nil, 2, 2, nil, nil],
                [nil, nil, nil, 5, nil, 5, nil],
                [nil, nil, nil, nil, 5, 5, nil, 5],
                [3, nil, 3, nil, 3, 3, 3],
                [3, 3, nil, nil, 3, nil, 4, 4],
                [1, 1, 1, 3, 2, 6, 3],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 798,
            rows: [
                [nil, nil, nil, nil, 3, 3, 3, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, 2, 2, 4, nil, 4, nil],
                [nil, 4, nil, 4, 4, 1, nil],
                [nil, 1, nil, 1, nil, nil, nil, nil],
                [nil, 1, nil, 1, 1, 1, nil],
                [nil, 1, nil, nil, nil, 1, 1, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, nil, 1, 1, nil, nil],
                [nil, 2, 2, 2, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 6, nil, 5, nil, 5, nil, 5],
                [6, nil, 3, nil, 3, nil, 6],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 799,
            rows: [
                [nil, nil, nil, 2, 2, 2, 2, nil],
                [nil, nil, 2, nil, nil, nil, 1],
                [3, nil, 3, nil, nil, 3, 3, 3],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, 1, 1, nil, 1, nil, 1],
                [nil, 1, nil, 2, nil, 2, 2],
                [2, nil, 2, 2, nil, nil, 2, 2],
                [nil, 2, nil, 2, 3, nil, nil],
                [nil, nil, nil, nil, 3, 3, nil, 1],
                [nil, 1, nil, 1, 1, 1, nil],
                [nil, 1, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, 1, nil, 5, nil],
                [nil, nil, nil, nil, 5, 5, nil, 5],
                [5, nil, 3, nil, 3, 4, 4],
                [4, 1, nil, nil, 1, nil, 1, 1],
                [1, 1, 1, 4, 4, 4, 6],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 800,
            rows: [
                [nil, 4, 4, nil, nil, nil, 3, nil],
                [3, 3, 3, 4, 4, nil, 4],
                [nil, 4, 6, 6, nil, 2, nil, 2],
                [2, nil, nil, nil, nil, 2, 2],
                [nil, 2, nil, 2, nil, 2, 2, nil],
                [2, nil, 1, nil, nil, nil, 1],
                [1, nil, nil, nil, 2, 2, nil, 2],
                [nil, 2, 2, 1, 1, 3, nil],
                [3, nil, 3, nil, 3, 1, nil, nil],
                [5, 5, nil, nil, nil, nil, nil],
                [nil, nil, 5, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, 3, 3],
                [3, 3, 1, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
    ]
}
