// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch71 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 1401,
            rows: [
                [nil, nil, 2, nil, nil, 1, 2, nil],
                [nil, 3, 3, nil, nil, 1, 1],
                [2, nil, nil, 4, 4, 1, nil, nil],
                [2, 1, nil, 1, nil, nil, nil],
                [2, nil, nil, 2, 1, 2, nil, nil],
                [1, 4, nil, 5, nil, nil, nil],
                [2, nil, 3, 3, 2, 1, 5, nil],
                [nil, 7, nil, nil, 2, nil, 1],
                [2, nil, 2, 1, 2, 1, 1, nil],
                [nil, 2, nil, nil, 4, nil, 2],
                [nil, 1, 1, nil, nil, nil, 2, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 2, 2, nil, nil, nil, 2, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1402,
            rows: [
                [nil, nil, nil, nil, nil, nil, 1, 3],
                [nil, nil, 5, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, 5, 4],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2, 1],
                [nil, 2, nil, nil, nil, 4, nil],
                [nil, 4, 4, nil, nil, 2, nil, nil],
                [1, 3, 3, nil, 1, nil, nil],
                [nil, 1, 1, nil, nil, 3, nil, nil],
                [3, 1, 2, nil, 3, nil, nil],
                [2, nil, 1, 2, 1, 2, nil, 1],
                [nil, 1, nil, 1, nil, 2, 1],
                [3, nil, 1, 2, 1, 4, nil, 1],
                [nil, 2, nil, 1, nil, 3, 2],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1403,
            rows: [
                [1, 1, 3, 3, 3, 3, 2, 3],
                [nil, nil, nil, nil, nil, nil, 3],
                [2, 2, 4, 1, 2, 1, 1, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [3, 3, 2, 1, 1, 1, 1, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [4, 1, 1, 1, 2, 1, 2, 5],
                [nil, nil, nil, nil, nil, nil, 2],
                [5, 5, 1, 4, 2, 2, 4, 2],
                [nil, nil, nil, nil, nil, nil, 3],
                [2, 2, 1, 2, 1, 3, 2, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [3, 2, 2, 1, 2, 3, 3, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 3, 1, 4, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1404,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 3, 3, 2, 5, 5, nil],
                [1, nil, nil, nil, nil, nil, 2],
                [1, nil, 1, 1, 1, 1, nil, 2],
                [2, nil, nil, nil, nil, nil, 1],
                [nil, 2, 2, 6, 3, 3, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 2, 1, 2, nil, nil],
                [nil, nil, 1, 7, 1, nil, nil],
                [nil, nil, 2, 6, 2, 1, nil, nil],
                [nil, nil, 1, 5, 1, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1405,
            rows: [
                [1, nil, nil, 1, 1, nil, nil, 1],
                [2, nil, 2, 2, 5, nil, 1],
                [nil, 3, nil, 1, 3, nil, 5, nil],
                [nil, 2, 5, 1, 1, 2, nil],
                [nil, 5, nil, 1, 3, nil, 1, nil],
                [nil, 1, 1, 1, 1, 2, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [1, 6, 5, 1, 2, 1, 4, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [4, 4, 1, 5, 1, 1, 5, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1406,
            rows: [
                [nil, 3, nil, 3, nil, 1, nil, 2],
                [1, nil, 4, nil, 1, nil, 1],
                [2, nil, 3, nil, 3, nil, 3, nil],
                [nil, 3, nil, 2, nil, 6, nil],
                [4, nil, 4, nil, 2, nil, 1, nil],
                [nil, 2, nil, 1, nil, 1, nil],
                [nil, 1, nil, 2, nil, 2, nil, nil],
                [2, nil, 4, nil, 2, nil, nil],
                [nil, 2, nil, 2, nil, 2, nil, nil],
                [1, nil, 3, nil, 1, nil, nil],
                [nil, nil, 2, nil, 4, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, nil, nil, 7, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1407,
            rows: [
                [3, 2, nil, nil, nil, nil, 6, 2],
                [3, 3, 4, 2, 3, 2, 3],
                [1, 3, nil, nil, nil, nil, 3, 3],
                [3, 3, 1, 2, 2, 1, 1],
                [2, 3, nil, nil, nil, nil, 2, 2],
                [5, 3, 3, 3, 1, 2, 1],
                [2, 2, nil, nil, nil, nil, 1, 3],
                [3, 3, 3, 3, 3, 1, 2],
                [1, 5, nil, nil, nil, nil, 5, 6],
                [1, 1, 2, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1408,
            rows: [
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [1, 4, 1, 3, 2, 5, 6, 1],
                [nil, nil, nil, nil, nil, nil, 6],
                [1, 3, 1, 1, 3, 3, 3, 2],
                [nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, 4, nil],
                [nil, 1, 3, 2, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, 5, 1, 4, 1, nil],
                [nil, 6, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1409,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 3, 2, 3, 1, nil, nil],
                [nil, 3, 1, 1, 1, 1, nil],
                [nil, nil, 2, 3, 2, 1, nil, nil],
                [nil, 1, 3, 2, 2, 2, nil],
                [nil, 3, 2, 1, 4, 4, 4, nil],
                [1, 3, 3, 3, 1, 1, 1],
                [nil, 3, 1, 3, 4, 3, 3, nil],
                [1, 2, 2, 2, 3, 1, 6],
                [1, 1, 1, 6, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 3, 3, 4, 1, 4, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1410,
            rows: [
                [2, 1, nil, nil, nil, nil, 1, 2],
                [3, nil, nil, nil, nil, nil, 1],
                [nil, nil, 1, 2, 2, 5, nil, nil],
                [nil, 5, nil, nil, nil, 1, nil],
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, 4, nil, nil, nil, 1, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, 7, nil, nil, nil],
                [nil, nil, 1, 2, nil, nil, nil],
                [3, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, 7, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1411,
            rows: [
                [nil, nil, 3, 5, 5, 5, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 3, nil, 3, 3, nil, 2],
                [4, 4, nil, 4, 2, nil, 2],
                [nil, 1, 3, 1, 3, 1, 3, nil],
                [2, 3, 1, 2, 1, 2, nil],
                [nil, nil, 2, 3, nil, 4, 2, nil],
                [nil, 1, 2, nil, 2, 2, nil],
                [nil, nil, nil, 2, 1, 3, nil, nil],
                [nil, nil, 3, 1, 4, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1412,
            rows: [
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, 3, 1, 4, 1, nil, nil],
                [nil, 2, nil, 1, nil, 4, nil],
                [nil, nil, 1, 2, 5, 1, nil, nil],
                [nil, 6, nil, 1, nil, 4, nil],
                [1, nil, nil, 2, 2, nil, nil, 2],
                [3, 3, nil, 3, nil, 4, 1],
                [1, nil, nil, 3, 1, nil, nil, 1],
                [3, 1, nil, 1, nil, 4, 1],
                [nil, 4, 1, 1, 4, 4, 1, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, 1, 4, 1, 1, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1413,
            rows: [
                [4, nil, nil, nil, nil, nil, nil, 2],
                [1, 1, 1, 2, 3, 1, 1],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [1, 1, 2, 2, 2, 3, 3],
                [2, nil, nil, nil, nil, nil, nil, 5],
                [6, 3, 3, 1, 4, 4, 1],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [1, 2, 3, 3, 2, 3, 2],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [1, 2, 5, 1, 1, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1414,
            rows: [
                [3, 1, 1, 2, 4, 1, 1, 4],
                [2, 1, 4, 4, 1, 2, 1],
                [1, 3, 2, 1, 3, 1, 1, 1],
                [3, 1, 4, 4, 3, 3, 1],
                [2, 2, 1, 3, 2, 7, 1, 3],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1415,
            rows: [
                [nil, 4, 4, 4, 1, 4, 4, nil],
                [nil, 2, 2, 1, 1, 3, nil],
                [nil, nil, 1, 3, 3, 1, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 6, 2, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, nil, nil],
                [3, 2, nil, nil, nil, nil, nil],
                [nil, 2, 3, nil, nil, nil, nil, nil],
                [nil, 3, 1, nil, nil, nil, nil],
                [nil, nil, 1, 4, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1416,
            rows: [
                [1, 3, 3, 3, 1, 1, 2, 4],
                [1, nil, 2, nil, 1, nil, 4],
                [nil, 2, 1, 2, 1, 1, 1, nil],
                [nil, 3, nil, 1, nil, 3, nil],
                [nil, 1, 1, 1, 3, 3, 2, nil],
                [nil, 1, nil, 1, nil, 3, nil],
                [nil, 1, 3, 1, 2, 2, 2, nil],
                [2, nil, 3, nil, 1, nil, 1],
                [nil, 3, 4, 2, 5, 3, 3, nil],
                [3, nil, 3, nil, 3, nil, 4],
                [4, 2, 1, 1, 2, 1, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 6, 2, 1, 2, 3, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1417,
            rows: [
                [1, 1, nil, 1, 1, nil, 1, 4],
                [4, 4, nil, 3, nil, 2, 2],
                [nil, 1, nil, 3, 5, nil, 1, nil],
                [1, 3, 1, 2, 2, 1, 2],
                [nil, 3, nil, 3, 1, nil, 2, nil],
                [2, 2, 2, 2, 2, 1, 2],
                [nil, 1, nil, 3, 3, nil, 3, nil],
                [2, 1, nil, nil, nil, 2, 1],
                [nil, 1, nil, 1, 1, nil, 2, nil],
                [1, 2, nil, nil, nil, 1, 3],
                [2, 1, 5, nil, nil, 1, 3, 3],
                [2, 1, nil, nil, nil, 1, 2],
                [1, 3, 3, nil, nil, 3, 2, 3],
                [2, 2, nil, nil, nil, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1418,
            rows: [
                [nil, nil, 2, 2, 3, 3, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 4, 1, 3, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 4, 2, 4, 1, nil, nil],
                [nil, nil, 3, 2, 3, nil, nil],
                [nil, nil, 3, 2, 2, 2, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 3, 1, 5, 6, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 2, 2, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 3, 5, 6, 1, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, 2, 1, 2, 3, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1419,
            rows: [
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 3, 2, 1, nil, nil, 2],
                [3, 3, 1, 1, 1, nil, 1],
                [nil, 3, 3, 3, 1, nil, nil, 3],
                [1, 2, 1, 1, 2, nil, 6],
                [2, 2, 1, 1, 2, 4, 1, nil],
                [3, 3, 1, 3, 3, nil, 1],
                [1, 3, 4, 2, 2, 1, 1, nil],
                [1, 1, 4, 2, 2, nil, 3],
                [nil, 1, 2, 5, 5, nil, nil, 1],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, 3, 4, 1, 2, nil, nil, 1],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 1420,
            rows: [
                [nil, nil, 1, nil, nil, 4, nil, nil],
                [1, 2, 4, 3, 2, 3, 3],
                [2, 2, 1, 1, 1, 2, 1, 5],
                [1, 2, nil, 2, nil, 3, 1],
                [1, 1, 2, 2, 2, 2, 4, 4],
                [4, 3, nil, 3, nil, 3, 1],
                [3, 1, nil, 1, 1, nil, 2, 2],
                [3, nil, nil, 3, nil, nil, 1],
                [3, 3, nil, 3, 3, nil, 1, 1],
                [1, nil, nil, 4, nil, nil, 1],
                [3, 2, 2, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 4, nil, nil, 4, 5, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
    ]
}
