// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch122 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2421,
            rows: [
                [nil, nil, 4, nil, nil, 2, nil, nil],
                [nil, 1, 3, nil, 5, 5, nil],
                [nil, 3, 2, 6, 2, 2, 1, nil],
                [nil, 2, 3, nil, 1, 3, nil],
                [nil, 1, 1, 4, 2, 2, 3, nil],
                [nil, 1, 3, nil, 3, 2, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [5, nil, nil, 3, 4, nil, nil, 1],
                [4, nil, nil, 3, nil, nil, 1],
                [5, nil, nil, 1, 3, nil, nil, 1],
                [3, nil, nil, 1, nil, nil, 3],
                [nil, 1, 3, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2422,
            rows: [
                [2, nil, nil, 1, 3, 3, 4, nil],
                [nil, 2, 1, nil, nil, 2, nil],
                [2, nil, 1, 4, 4, 1, nil, nil],
                [nil, nil, nil, 2, nil, nil, 1],
                [nil, nil, nil, 3, nil, 3, nil, nil],
                [2, nil, nil, nil, 1, 1, nil],
                [nil, 2, nil, 4, nil, nil, nil, 2],
                [nil, nil, 2, 4, nil, 1, 2],
                [3, nil, 1, nil, 3, nil, 2, 1],
                [3, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, nil, 2, 1, 2],
                [1, 1, nil, nil, 5, nil, 6],
                [2, 1, 2, nil, 1, 3, 4, 1],
                [1, 1, 3, 1, 2, 1, 2],
                [nil, 1, 4, 2, 1, 3, 2, nil],
                [nil, 1, 3, 1, 1, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2423,
            rows: [
                [nil, 2, nil, 2, 1, nil, 5, nil],
                [2, nil, 1, 1, nil, nil, 2],
                [nil, 2, 3, 1, nil, 3, 1, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [1, 4, 4, 1, 5, nil, nil, 2],
                [1, nil, 3, 1, 2, 1, nil],
                [3, nil, nil, 3, 2, nil, nil, 1],
                [3, nil, nil, nil, nil, 1, nil],
                [2, nil, nil, nil, 2, nil, 3, 4],
                [1, 2, nil, 1, 6, nil, nil],
                [nil, 1, 3, 1, 2, 1, nil, nil],
                [2, nil, 1, nil, nil, nil, nil],
                [nil, 3, 2, 2, 3, 1, 1, 3],
                [1, 3, 1, 2, 1, 4, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2424,
            rows: [
                [2, nil, nil, nil, 1, 2, nil, nil],
                [1, 1, 2, 3, 5, nil, 5],
                [nil, 2, 1, 4, 2, nil, 1, 6],
                [nil, 4, 1, nil, 3, 2, nil],
                [3, nil, nil, 2, nil, 1, 5, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [1, nil, 3, 1, 3, nil, nil, nil],
                [2, 1, nil, 3, nil, 1, 4],
                [nil, 3, nil, 1, 2, nil, nil, nil],
                [nil, 1, 2, 1, 1, 2, 1],
                [3, 1, nil, nil, 3, nil, nil, 1],
                [nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, 2, 1, 2, 1, 2],
                [2, 1, 4, 1, 1, 1, 3],
                [1, 1, 3, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2425,
            rows: [
                [nil, nil, nil, 3, 5, 2, nil, nil],
                [nil, nil, 4, 4, 1, 3, nil],
                [nil, 1, 1, nil, nil, 3, 1, nil],
                [2, 3, nil, 6, 1, 2, 1],
                [nil, nil, 3, 1, 1, 1, 2, nil],
                [nil, 1, nil, 6, 3, nil, nil],
                [nil, nil, nil, 3, 1, nil, 2, nil],
                [1, 2, 1, nil, nil, 2, nil],
                [nil, 1, 2, 3, nil, nil, 1, 2],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, 2, nil, nil, 1, 4, nil, 2],
                [nil, 3, 4, 4, nil, 1, 3],
                [nil, 1, 3, 1, 2, 1, 1, 2],
                [nil, 1, 2, 1, 5, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2426,
            rows: [
                [3, nil, 2, nil, 1, nil, 2, nil],
                [nil, 4, nil, 2, nil, 3, nil],
                [1, nil, 3, nil, 6, nil, 1, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [2, nil, 1, nil, 2, nil, 1, nil],
                [nil, 6, nil, 1, nil, 3, nil],
                [4, nil, 3, nil, 1, nil, 2, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [3, nil, 2, nil, 4, nil, 3, nil],
                [nil, 1, nil, 3, nil, 1, nil],
                [4, nil, 1, nil, 2, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2427,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, nil],
                [3, 1, nil, nil, nil, 5, 1],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, 1, 4, nil],
                [nil, 2, 2, 1, 2, nil, 1, nil],
                [nil, 1, 3, 1, 4, 2, nil],
                [nil, 1, 2, 2, 2, 3, 2, nil],
                [nil, 1, 3, 1, 3, 5, nil],
                [nil, 5, 1, 4, 1, 4, 4, nil],
                [nil, 1, 3, 1, 6, 1, nil],
                [nil, 4, 1, 1, 5, 1, 2, nil],
                [nil, nil, 1, 5, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2428,
            rows: [
                [nil, 4, nil, nil, nil, nil, 1, nil],
                [3, 4, nil, nil, nil, 1, 2],
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [1, 3, nil, nil, nil, 2, 3],
                [nil, 4, nil, nil, nil, nil, 5, nil],
                [1, 2, nil, nil, nil, 1, 5],
                [nil, 2, nil, nil, nil, nil, 4, nil],
                [3, 1, nil, nil, nil, 2, 3],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [2, 2, nil, nil, nil, 4, 2],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2429,
            rows: [
                [1, nil, nil, nil, 4, nil, nil, nil],
                [1, 3, nil, 4, nil, 3, 1],
                [nil, 2, 1, 3, nil, 1, 4, 1],
                [nil, nil, nil, 2, nil, 1, nil],
                [3, 2, 1, 5, 1, 1, 5, 1],
                [nil, nil, 2, 1, nil, 6, 1],
                [nil, 4, 1, 3, 1, nil, 2, 1],
                [3, 1, 3, 2, nil, 3, 1],
                [nil, 2, 1, 4, 5, nil, 1, 2],
                [1, 3, 1, 2, nil, 1, 1],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2430,
            rows: [
                [nil, nil, 1, nil, 3, 1, 2, nil],
                [nil, 1, 2, 1, nil, nil, 4],
                [3, 2, nil, nil, 1, nil, nil, 3],
                [nil, 3, nil, nil, nil, 4, 1],
                [2, 1, 2, nil, 1, nil, nil, 2],
                [1, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, 2, 1],
                [2, 6, nil, 1, nil, nil, 5],
                [2, 3, 3, nil, 4, 1, nil, nil],
                [3, nil, nil, 2, nil, 1, nil],
                [3, nil, 4, 1, nil, nil, nil, 2],
                [nil, 1, nil, 3, nil, nil, nil],
                [4, 2, nil, nil, nil, nil, 1, 2],
                [1, 4, 2, 1, 2, 1, 2],
                [1, 3, 1, 3, 1, 2, 1, 2],
                [1, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2431,
            rows: [
                [1, 2, 1, nil, 1, 2, nil, nil],
                [3, 1, nil, nil, nil, nil, nil],
                [2, 4, 2, 4, nil, 1, 3, nil],
                [nil, nil, nil, nil, 2, 2, nil],
                [nil, nil, nil, 5, nil, 6, nil, 2],
                [nil, nil, 1, 5, nil, nil, 4],
                [1, nil, nil, 3, 1, 2, 4, nil],
                [2, 1, 2, 1, nil, nil, 4],
                [1, 1, nil, nil, nil, 4, nil, nil],
                [1, 2, nil, 4, 3, 2, 1],
                [3, nil, 3, 2, 1, nil, 2, 2],
                [nil, nil, 1, nil, 4, 1, 4],
                [nil, nil, 1, nil, 2, 1, 2, 1],
                [2, 1, nil, nil, nil, 1, 1],
                [nil, 1, 1, nil, 1, nil, nil, nil],
                [nil, 1, 1, 1, 1, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2432,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, 1],
                [2, 1, 4, 1, nil, 2, 1],
                [2, 2, 1, 3, 1, 2, 1, 2],
                [nil, nil, 3, 4, nil, 1, 2],
                [2, 1, 3, 1, 2, 3, 1, 3],
                [nil, nil, 1, 3, nil, 3, 1],
                [nil, 1, 5, 4, 1, nil, 1, 3],
                [1, 6, 1, 2, nil, 1, 2],
                [nil, 1, 3, 1, 4, nil, 1, 3],
                [1, 1, 1, 1, nil, 1, 1],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2433,
            rows: [
                [1, 3, 1, 4, 1, 4, 1, 3],
                [2, nil, nil, 3, nil, nil, 1],
                [4, 1, 3, 1, 1, 3, 4, 5],
                [1, nil, nil, 3, nil, nil, 1],
                [3, 2, 1, 2, 1, 3, 4, 3],
                [4, nil, nil, 1, nil, nil, 2],
                [nil, 1, nil, nil, 2, nil, nil, 1],
                [3, 4, 1, 5, 4, 1, 2],
                [nil, 4, nil, nil, 1, nil, nil, 3],
                [1, 3, 1, 3, 1, 4, 1],
                [nil, 3, nil, nil, 1, nil, nil, 3],
                [1, nil, nil, 1, nil, nil, 2],
                [nil, 1, nil, nil, 2, nil, nil, 1],
                [2, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2434,
            rows: [
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [nil, 4, nil, nil, nil, 2, nil],
                [nil, nil, 1, 3, 1, 5, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, nil, 1, 3, 2, 1, nil, nil],
                [nil, nil, 3, nil, 4, nil, nil],
                [3, 1, 4, nil, nil, 2, 1, 2],
                [nil, nil, 2, nil, 3, nil, nil],
                [1, 2, 1, nil, nil, 3, 1, 1],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, 1, 1, 3, 2, nil, nil],
                [nil, 4, nil, nil, nil, 1, nil],
                [nil, nil, 2, 4, 1, 2, nil, nil],
                [nil, 4, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2435,
            rows: [
                [1, 2, 1, 2, 4, 3, 2, 1],
                [2, nil, nil, 1, nil, nil, 5],
                [3, 1, 3, 1, 4, 1, 2, 1],
                [2, nil, nil, 1, nil, nil, 3],
                [3, 4, 1, 3, 1, 5, 3, 4],
                [3, nil, nil, 1, nil, nil, 3],
                [nil, 1, nil, nil, 2, nil, nil, 4],
                [6, 1, 3, 1, 3, 2, 1],
                [nil, 3, nil, nil, 1, nil, nil, 3],
                [1, 2, 1, 4, 2, 1, 2],
                [nil, 3, nil, nil, 1, nil, nil, 2],
                [1, nil, nil, 4, nil, nil, 1],
                [nil, 2, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2436,
            rows: [
                [3, nil, nil, nil, 2, nil, nil, nil],
                [1, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, 4, 1, nil, nil],
                [nil, 2, nil, 3, nil, 1, nil],
                [nil, 3, nil, nil, 3, 1, nil, nil],
                [nil, 3, nil, 1, nil, 2, nil],
                [nil, 1, nil, nil, 1, 2, nil, nil],
                [1, nil, nil, 2, 1, 7, nil],
                [nil, 1, nil, nil, 3, 1, nil, nil],
                [4, nil, nil, 1, 5, 1, nil],
                [2, nil, nil, nil, 1, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, 1, 5, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2437,
            rows: [
                [4, 3, 6, 6, 1, 3, 1, 3],
                [2, nil, nil, 2, nil, nil, 3],
                [1, 2, 3, 1, 1, 1, 5, 4],
                [1, nil, nil, 3, nil, nil, 2],
                [4, 1, 2, 1, 2, 1, 1, 1],
                [3, nil, nil, 1, nil, nil, 2],
                [nil, 1, nil, nil, 2, nil, nil, 1],
                [2, 3, 6, 2, 1, 2, 1],
                [nil, 3, nil, nil, 2, nil, nil, 1],
                [2, 1, 4, 1, 2, 1, 2],
                [nil, 1, nil, nil, 2, nil, nil, 1],
                [3, nil, nil, 1, nil, nil, 2],
                [nil, 1, nil, nil, 2, nil, nil, 1],
                [2, nil, nil, 1, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2438,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 4, 1, 2, nil, nil],
                [nil, nil, 1, 3, 2, nil, nil],
                [nil, nil, 4, 2, 2, 2, nil, nil],
                [nil, nil, 1, 2, 5, nil, nil],
                [nil, nil, 3, 3, 1, 3, nil, nil],
                [nil, nil, 2, 5, 1, nil, nil],
                [nil, nil, 4, 1, 4, 1, nil, nil],
                [nil, nil, 4, 1, 2, nil, nil],
                [nil, nil, 4, 1, 6, 1, nil, nil],
                [nil, nil, 4, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2439,
            rows: [
                [nil, 2, nil, nil, nil, nil, 3, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, nil, 2, 1, 2, 4, nil, nil],
                [nil, nil, 3, nil, 4, nil, nil],
                [nil, nil, 3, 4, 1, 2, nil, nil],
                [nil, nil, 2, nil, 5, nil, nil],
                [3, 1, 3, nil, nil, 3, 1, 1],
                [nil, nil, 1, nil, 4, nil, nil],
                [2, 6, 4, nil, nil, 1, 4, 2],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, 4, nil, nil, nil, 3, nil],
                [nil, nil, 4, 3, 1, 5, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2440,
            rows: [
                [nil, nil, 5, 3, 1, nil, nil, nil],
                [nil, 3, nil, nil, 5, nil, nil],
                [nil, nil, 6, 1, 3, 4, 2, nil],
                [nil, 3, 1, 2, nil, nil, 3],
                [nil, nil, 1, 3, 1, 3, 1, nil],
                [nil, 2, 3, 2, nil, nil, 1],
                [nil, 2, nil, nil, 1, 5, 3, nil],
                [nil, 1, 2, 3, 5, 2, nil],
                [nil, 3, nil, nil, 2, 1, 2, nil],
                [nil, 1, 2, 5, 1, 1, nil],
                [nil, nil, 2, 2, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
    ]
}
