// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch32 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 621,
            rows: [
                [1, nil, 1, 1, 1, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, nil],
                [1, nil, 1, nil, 1, 1, nil, 5],
                [3, 3, 3, nil, 2, 2, 2],
                [nil, 4, 3, nil, 3, 3, 3, nil],
                [3, nil, nil, nil, 3, 2, nil],
                [nil, 2, nil, nil, 2, nil, nil, 2],
                [2, nil, 2, nil, 2, nil, 2],
                [nil, nil, 6, 5, 5, 5, 5, 5],
                [1, 1, 1, nil, 4, 4, 4],
                [4, 1, 1, 1, 1, 2, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 622,
            rows: [
                [nil, nil, nil, 5, 5, 2, 2, nil],
                [nil, nil, 2, nil, nil, nil, 2],
                [2, nil, 2, nil, nil, 2, 2, 2],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 1, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, 1],
                [1, nil, 1, 3, nil, nil, 2, 2],
                [nil, 2, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil, 1],
                [nil, 1, nil, 1, 1, 3, nil],
                [nil, 3, nil, nil, 3, 3, nil, nil],
                [nil, nil, nil, 3, nil, 1, nil],
                [nil, nil, nil, nil, 1, 4, nil, 5],
                [5, nil, 5, nil, 1, 6, 4],
                [4, 1, nil, nil, 1, nil, 1, 3],
                [3, 3, 4, 4, 4, 2, 3],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 623,
            rows: [
                [nil, 2, 2, 2, nil, 1, nil, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, 1, 1, 4, nil, nil],
                [nil, nil, 4, 4, 4, nil, 4, nil],
                [nil, 4, nil, 4, 4, 4, nil],
                [nil, nil, 3, nil, 3, nil, 3, nil],
                [nil, 3, nil, nil, 3, nil, nil],
                [nil, 3, nil, 5, nil, 5, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, nil, nil, 1, nil],
                [nil, 2, 2, 2, nil, 2, nil],
                [nil, nil, nil, 2, nil, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, nil, 2, 1, 1, 1, nil],
                [nil, 3, 3, 3, 6, 6, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 624,
            rows: [
                [nil, 1, 1, nil, 1, 2, 2, nil],
                [2, 2, 2, nil, nil, nil, 2],
                [2, nil, 3, 3, 3, 3, nil, 4],
                [nil, 4, nil, 4, 1, nil, 3],
                [nil, nil, 3, 3, nil, nil, 3, nil],
                [nil, 3, 1, nil, 4, 4, nil],
                [4, nil, nil, nil, nil, nil, 4, 3],
                [nil, 3, 3, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, 1, 1, nil, nil, 2],
                [nil, nil, 2, nil, 2, nil, 1, 6],
                [nil, nil, nil, 6, nil, 5, 5],
                [nil, 1, 5, nil, 1, 1, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 625,
            rows: [
                [3, 1, 1, 2, nil, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [2, 2, nil, 2, 2, nil, 1, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [1, 1, nil, 1, nil, nil, 1],
                [nil, 1, nil, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, 1, 1, nil],
                [4, nil, 4, 4, 3, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 3, 3, 1, 1, 1, 1, nil],
                [1, nil, 2, 2, nil, 2, nil],
                [2, 6, nil, 6, nil, 3, 3, 3],
                [3, nil, 1, nil, nil, nil, 1],
                [nil, 1, 1, nil, 1, 3, nil, nil],
                [nil, 2, nil, 2, 6, 6, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 626,
            rows: [
                [nil, 1, nil, nil, 1, 1, 1, nil],
                [nil, 1, 5, 5, 1, nil, nil],
                [nil, nil, nil, 5, 5, nil, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, nil, nil, 1, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, nil, 2, 6, nil, 6, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 2, 2, nil, 2, nil, nil, nil],
                [nil, 2, 2, nil, 2, 1, nil],
                [nil, 1, 1, 1, 1, 1, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 1, 1, 4, 4, nil],
                [nil, 4, 4, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 3, nil, 3],
                [3, nil, 3, nil, 6, nil, 6],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 627,
            rows: [
                [nil, 1, 1, nil, 1, 1, 1, 2],
                [2, 2, 3, 3, 3, 3, 3],
                [nil, 3, nil, nil, 3, nil, 2, 2],
                [nil, 2, nil, nil, nil, nil, nil],
                [2, 2, nil, nil, 2, 2, 4, nil],
                [4, nil, 4, nil, 4, nil, 4],
                [6, nil, 1, 1, nil, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, 1, 1, 1, nil, 1, 5],
                [5, 5, 1, 1, 2, 2, 2, 2],
                [2, nil, 2, 1, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil, nil],
                [5, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, 1, 1, nil],
                [nil, 1, 1, 1, 6, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 628,
            rows: [
                [2, nil, 2, 1, 1, nil, 1, 1],
                [2, 2, nil, nil, nil, 2, nil],
                [2, nil, 2, nil, 2, 1, nil, 1],
                [1, 5, 5, nil, 5, 5, 5],
                [nil, 5, 1, nil, 1, 1, 1, nil],
                [1, nil, nil, nil, 1, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, nil, 3, 3, 3, 3, 3, 3],
                [3, 3, 3, nil, 2, 2, 1],
                [1, 1, 1, 1, 1, 4, 4, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [4, 4, 1, 2, 2, 1, 1, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 629,
            rows: [
                [nil, nil, nil, 4, 4, 4, 4, nil],
                [nil, nil, 4, nil, nil, nil, 4],
                [1, nil, 3, nil, nil, 3, 3, 3],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 3, nil, 3, nil, 1],
                [nil, 1, nil, 1, nil, 1, 1],
                [1, nil, 2, 2, nil, nil, 2, 2],
                [nil, 2, nil, 2, 2, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil, 1],
                [nil, 1, nil, 1, 5, 5, nil],
                [nil, 5, nil, nil, 5, 5, nil, nil],
                [nil, nil, nil, 2, nil, 2, nil],
                [nil, nil, nil, nil, 2, 2, nil, 2],
                [2, nil, 2, nil, 2, 2, 2],
                [1, 1, nil, nil, 1, nil, 1, 1],
                [6, 1, 1, 1, 1, 1, 1],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 630,
            rows: [
                [nil, 1, 1, 1, nil, 1, nil, nil],
                [nil, 1, 1, 6, nil, 6, nil],
                [nil, nil, 1, nil, 1, nil, 1, nil],
                [nil, 4, 4, 4, 4, nil, nil],
                [nil, nil, 4, 4, 4, nil, 2, nil],
                [nil, 2, nil, 2, 2, 1, nil],
                [nil, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil, nil],
                [nil, 1, 2, 2, 3, 3, nil],
                [nil, 3, 3, 3, nil, nil, 3, nil],
                [nil, 5, 5, 1, nil, 1, nil],
                [nil, nil, nil, 1, nil, 1, 2, nil],
                [nil, 3, 2, 2, 2, 2, nil],
                [nil, 2, nil, 2, 2, 2, 3, nil],
                [nil, 3, 2, 2, 4, 4, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 631,
            rows: [
                [nil, 3, 3, nil, 3, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, 1],
                [1, 1, nil, nil, 1, nil, 4, 4],
                [4, 4, 1, nil, nil, nil, 1],
                [1, 1, 1, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, 2, nil, 2],
                [nil, 2, 2, nil, 2, 2, 2, 2],
                [2, 2, nil, nil, 2, 2, 2],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, 1, nil, 1, 1, 4, 4],
                [1, nil, 1, 1, 5, 5, 5, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 3, 3, 3, 3, 6, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 632,
            rows: [
                [nil, 1, 4, nil, 4, 4, 4, nil],
                [4, 4, 4, nil, nil, nil, 1],
                [1, nil, 3, 1, 1, 1, nil, 1],
                [nil, 1, nil, 3, 3, nil, 3],
                [nil, nil, 3, 2, nil, nil, 2, nil],
                [nil, 2, 2, nil, 2, 2, nil],
                [2, nil, nil, nil, nil, nil, 2, 2],
                [nil, 2, 1, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, 1, 1, nil, nil, 1],
                [nil, nil, 1, nil, 1, nil, 1, 1],
                [nil, nil, nil, 5, nil, 5, 5],
                [nil, 6, 6, nil, 1, 1, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, 3, 1, 1, 3, nil],
                [nil, 3, 3, 3, 3, 3, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 633,
            rows: [
                [nil, 3, 3, nil, nil, nil, 3, nil],
                [3, 3, 3, 2, 2, nil, 2],
                [nil, 2, 2, 1, nil, 1, nil, 3],
                [3, nil, nil, nil, nil, 3, 3],
                [nil, 3, nil, 3, nil, 3, 2, nil],
                [2, nil, 2, nil, nil, nil, 4],
                [1, nil, nil, nil, 1, 1, nil, 1],
                [nil, 1, 1, 1, 1, 1, nil],
                [1, nil, 1, nil, 1, 1, nil, nil],
                [1, 2, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, 6, nil, nil],
                [nil, 6, 1, 1, 2, 2, 5],
                [1, 1, 1, 1, nil, 5, 4, 4],
                [4, 4, 4, 2, 2, 2, 5],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 634,
            rows: [
                [1, 1, 1, 1, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [1, 1, nil, 1, 1, nil, 1, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [3, 3, nil, 1, nil, nil, 1],
                [nil, 1, nil, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, 1, 1, nil],
                [6, nil, 6, 6, 3, nil, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 3, 3, 3, 2, 2, nil],
                [2, nil, 2, 2, nil, 2, nil],
                [3, 3, nil, 3, nil, 3, 3, 2],
                [2, nil, 2, nil, nil, nil, 2],
                [nil, 4, 4, nil, 2, 6, nil, nil],
                [nil, 2, nil, 2, 2, 2, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 635,
            rows: [
                [nil, 2, nil, nil, 1, 1, 1, nil],
                [nil, 1, 2, 2, 2, nil, nil],
                [nil, nil, nil, 2, 2, nil, 2, nil],
                [nil, 2, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, nil, nil, 1, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, nil, 1, 1, nil, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 1, 1, nil, 1, nil, nil, nil],
                [nil, 1, 5, nil, 5, 5, nil],
                [nil, 5, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 1, 1, 1, nil],
                [nil, 1, 1, 1, 3, 3, 6, nil],
                [nil, 1, 1, 1, 1, 6, nil],
                [nil, 4, nil, 4, nil, 4, nil, 4],
                [6, nil, 6, nil, 3, nil, 3],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 636,
            rows: [
                [1, nil, nil, 4, 4, 4, nil, nil],
                [4, nil, 4, nil, nil, nil, 4],
                [4, nil, 4, nil, 1, nil, nil, 1],
                [1, 1, 1, nil, 1, 1, nil],
                [nil, 1, 1, 1, nil, 5, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil],
                [1, 1, 3, nil, 3, 3, nil, nil],
                [nil, nil, nil, 3, nil, 3, 3],
                [1, nil, 6, 6, 1, 1, 1, nil],
                [1, 1, 1, nil, nil, 4, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, 2, 5, 2, 2],
                [2, nil, 2, 2, nil, nil, nil, nil],
                [2, nil, 2, 2, 3, nil, nil],
                [nil, nil, nil, 1, 1, nil, 3, nil],
                [nil, nil, 3, nil, 3, 2, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 637,
            rows: [
                [nil, 1, nil, nil, nil, 1, nil, 1],
                [nil, nil, nil, 2, nil, 2, 2],
                [2, 2, 2, nil, 2, 1, nil, 1],
                [1, 1, 1, nil, 1, 3, nil],
                [nil, nil, nil, 3, nil, 3, nil, 3],
                [nil, nil, 3, 1, 1, nil, nil],
                [1, 2, 2, 2, nil, nil, nil, nil],
                [2, 1, 1, 1, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, 5],
                [nil, nil, 5, nil, 5, 2, nil],
                [2, nil, 2, nil, nil, 2, 5, nil],
                [nil, 5, nil, nil, nil, 4, 4],
                [nil, nil, 4, nil, 3, 6, nil, nil],
                [nil, nil, nil, 6, 6, 6, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 638,
            rows: [
                [nil, 1, 1, nil, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 1, nil, nil, 1, nil, 1, 5],
                [nil, 5, nil, nil, nil, nil, nil],
                [3, 3, nil, nil, 3, 3, 2, nil],
                [2, nil, 2, nil, 2, nil, 2],
                [2, nil, 2, 4, nil, 1, 1, nil],
                [nil, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, 1, 1, 2, nil, 2, 2],
                [6, 6, 3, 4, 4, 3, 3, 1],
                [1, nil, 1, 1, nil, nil, nil],
                [nil, 1, nil, nil, 2, nil, nil, nil],
                [2, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, 2, 2, nil],
                [nil, 2, 5, 5, 4, 4, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 639,
            rows: [
                [nil, 1, 1, 2, nil, 2, 2, nil],
                [2, 2, 2, nil, nil, 2, nil],
                [2, 2, 2, 2, nil, 2, 1, 1],
                [1, 3, nil, nil, nil, 3, 3],
                [1, 1, 1, nil, 1, 1, nil, nil],
                [1, 6, nil, nil, 6, nil, 6],
                [nil, 6, 1, 1, 1, 1, nil, nil],
                [1, nil, 1, nil, 1, 4, 4],
                [1, 1, 1, 5, 1, nil, nil, nil],
                [nil, nil, 5, nil, 5, 1, 1],
                [1, 4, 4, 1, 1, 1, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 640,
            rows: [
                [2, nil, 2, 2, 2, nil, 2, 2],
                [2, 2, nil, nil, nil, 2, nil],
                [2, nil, 4, nil, 4, 4, nil, 1],
                [1, 1, 3, nil, 3, 3, 3],
                [nil, 3, 3, nil, 3, 3, 3, nil],
                [2, nil, nil, nil, 2, 1, nil],
                [nil, 5, nil, nil, 5, nil, nil, 5],
                [6, nil, 1, nil, 1, nil, 1],
                [nil, nil, 1, 5, 1, 1, 4, 4],
                [1, 5, 5, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
    ]
}
