// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch128 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2541,
            rows: [
                [nil, 1, nil, 1, nil, 3, nil, 5],
                [2, nil, 3, nil, 4, nil, 1],
                [nil, 2, nil, 1, nil, 2, nil, 3],
                [1, nil, 3, nil, 1, nil, 2],
                [nil, 1, nil, 4, nil, 1, nil, 3],
                [1, nil, 1, nil, 2, nil, 3],
                [nil, 5, nil, 2, nil, 3, nil, 4],
                [1, nil, 2, nil, 3, nil, 2],
                [nil, 1, nil, 2, nil, 3, nil, 5],
                [4, nil, 2, nil, 1, nil, 4],
                [nil, 3, nil, 1, nil, 1, nil, 4],
                [1, nil, 2, nil, 1, nil, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2542,
            rows: [
                [1, nil, 2, 3, 3, 1, nil, 2],
                [3, nil, nil, nil, nil, nil, 3],
                [1, 3, 1, 5, 3, 1, 6, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 3, 1, 3, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, 4, 1, 2, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, 1, nil, 2, nil, 1],
                [4, nil, 4, nil, 2, nil, 2],
                [nil, 1, nil, 2, nil, 5, nil, 3],
                [1, nil, 1, nil, 3, nil, 2],
                [nil, 1, nil, 3, nil, 2, nil, 1],
                [3, nil, 2, nil, 1, nil, 4],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 1, nil, 1, nil, 1],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2543,
            rows: [
                [nil, 2, 3, nil, nil, 2, 4, nil],
                [2, nil, 4, nil, 3, nil, 3],
                [3, nil, nil, 2, 5, nil, nil, 3],
                [1, nil, nil, nil, nil, nil, 3],
                [2, nil, nil, 2, 1, nil, nil, 2],
                [5, nil, nil, nil, nil, nil, 6],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, 2, nil, nil, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2544,
            rows: [
                [nil, 2, 1, nil, nil, 2, 1, nil],
                [1, nil, nil, nil, nil, nil, 3],
                [5, 1, nil, nil, nil, nil, 5, 3],
                [3, nil, nil, nil, nil, nil, 2],
                [5, 5, nil, nil, nil, nil, 4, 4],
                [2, nil, nil, nil, nil, nil, 1],
                [3, 1, nil, nil, nil, nil, 2, 6],
                [2, nil, nil, nil, nil, nil, 1],
                [2, 1, nil, nil, nil, nil, 6, 2],
                [4, nil, nil, nil, nil, nil, 1],
                [1, 2, nil, nil, nil, nil, 1, 6],
                [1, 4, nil, nil, nil, 2, 2],
                [3, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2545,
            rows: [
                [7, 4, 5, nil, nil, 1, 2, 1],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, 4, 5, 2, 3, nil, nil],
                [nil, 3, nil, 1, nil, 2, nil],
                [nil, nil, 1, 2, 1, 3, nil, nil],
                [nil, 1, nil, 1, nil, 2, nil],
                [nil, nil, 2, 4, 1, 3, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, nil, 2, 5, 1, nil, nil],
                [nil, 3, 6, nil, nil, 4, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2546,
            rows: [
                [3, 5, 1, 3, 1, 2, 2, 1],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [2, 4, 3, 1, 3, 2, 1, 2],
                [nil, nil, nil, nil, 3, nil, nil],
                [5, 2, 1, 3, 3, 1, 4, 2],
                [nil, nil, nil, nil, 4, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [1, 1, 4, 2, 4, 2, 6, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2547,
            rows: [
                [nil, 3, 4, nil, 1, 4, nil, nil],
                [1, nil, 2, 1, nil, 3, nil],
                [1, nil, nil, nil, nil, nil, 2, nil],
                [1, 2, 1, nil, nil, 2, 1],
                [5, nil, nil, nil, nil, nil, 3, nil],
                [4, 2, 1, nil, nil, 2, 4],
                [nil, 2, 3, 1, 5, 1, 4, 2],
                [nil, 6, 2, nil, nil, 1, 7],
                [nil, 1, 3, 2, 1, 2, 4, 1],
                [nil, 2, 1, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2548,
            rows: [
                [nil, 1, nil, 2, nil, 1, nil, 3],
                [1, nil, 3, nil, 4, nil, 5],
                [nil, 1, nil, 1, nil, 1, nil, 3],
                [1, nil, 2, nil, 7, nil, 5],
                [nil, 1, nil, 2, nil, 1, nil, 3],
                [2, nil, 2, nil, 4, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil],
                [nil, nil, 5, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 6, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2549,
            rows: [
                [1, 4, 5, 3, 2, 1, 5, 1],
                [5, nil, nil, 6, nil, nil, 3],
                [4, nil, nil, 3, 1, nil, nil, 3],
                [nil, nil, nil, 1, nil, nil, nil],
                [2, nil, nil, 1, 2, nil, nil, 2],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2550,
            rows: [
                [2, nil, 3, nil, nil, 2, nil, 3],
                [1, nil, 3, nil, 1, nil, 2],
                [1, nil, nil, 2, 7, nil, nil, 1],
                [2, nil, 3, 3, 1, nil, 2],
                [4, nil, nil, 5, 1, nil, nil, 5],
                [1, nil, 1, 2, 1, nil, 2],
                [1, nil, nil, 4, 1, nil, nil, 2],
                [1, nil, 4, nil, 1, nil, 2],
                [1, nil, nil, 2, 1, nil, nil, 2],
                [1, nil, 6, nil, 1, nil, 5],
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2551,
            rows: [
                [2, nil, 1, nil, 2, nil, 5, nil],
                [nil, 4, nil, 2, nil, 1, nil],
                [2, nil, 6, nil, 2, nil, 4, nil],
                [nil, 1, nil, 4, nil, 1, nil],
                [3, nil, 1, nil, 2, nil, 1, nil],
                [nil, 2, nil, 1, nil, 2, nil],
                [4, nil, 5, nil, 1, nil, 2, nil],
                [nil, 1, nil, 1, nil, 5, nil],
                [2, nil, 2, nil, 1, nil, 2, nil],
                [nil, 5, nil, 1, nil, 1, nil],
                [2, nil, 1, nil, 1, nil, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 3, 1, 2, 1, 5, 1, 2],
                [1, 3, 1, 1, 1, 1, 1],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2552,
            rows: [
                [nil, 1, nil, nil, nil, nil, 4, nil],
                [1, 5, nil, nil, nil, 1, 2],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [1, 2, nil, nil, nil, 1, 1],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [2, 1, nil, nil, nil, 3, 3],
                [nil, 1, nil, nil, nil, nil, 6, nil],
                [1, 2, nil, nil, nil, 1, 3],
                [nil, 1, nil, nil, nil, nil, 5, nil],
                [2, 1, nil, nil, nil, 2, 5],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2553,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 6, 3, 1, 4, 1, 4, nil],
                [4, nil, nil, nil, nil, nil, 2],
                [2, nil, 1, 2, 1, 2, nil, 1],
                [4, nil, nil, nil, nil, nil, 1],
                [nil, 3, 2, 4, 5, 1, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 3, 1, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 4, 1, 2, 1, nil, nil],
                [nil, nil, 1, 4, 1, nil, nil],
                [nil, nil, nil, 7, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2554,
            rows: [
                [4, nil, 1, nil, 2, nil, 5, nil],
                [nil, 7, nil, 1, nil, 2, nil],
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, 2, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [2, nil, nil, nil, nil, nil, nil, 3],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, 2],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2555,
            rows: [
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, 1, 5, nil, nil, nil, nil],
                [5, 1, nil, 4, 3, nil, nil, nil],
                [nil, nil, nil, nil, 2, 1, nil],
                [2, 1, nil, 2, 4, nil, nil, nil],
                [nil, nil, nil, nil, 1, 2, nil],
                [nil, nil, nil, 1, 1, nil, 5, 1],
                [nil, 2, 6, nil, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, 6, 1],
                [nil, 3, 2, nil, nil, nil, nil],
                [1, 4, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, 3, nil],
                [4, 2, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2556,
            rows: [
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [1, nil, nil, 5, nil, nil, 6],
                [2, nil, nil, 1, 1, nil, nil, 5],
                [2, nil, nil, 4, nil, nil, 1],
                [5, nil, nil, 1, 3, nil, nil, 2],
                [2, nil, nil, 1, nil, nil, 3],
                [nil, 5, 1, 4, 5, 1, 4, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 3, 1, 2, 3, 1, 2, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2557,
            rows: [
                [1, 3, nil, nil, nil, nil, 2, 3],
                [2, 1, 4, 1, 3, 1, 1],
                [4, 1, nil, nil, nil, nil, 2, 1],
                [3, 2, 1, 3, 5, 1, 3],
                [4, 1, nil, nil, nil, nil, 6, 4],
                [2, 1, 2, 4, 1, 2, 3],
                [1, 5, nil, nil, nil, nil, 3, 1],
                [1, 3, 1, 3, 1, 2, 1],
                [3, 4, nil, nil, nil, nil, 1, 4],
                [3, 3, 3, 2, 1, 2, 1],
                [2, 4, nil, nil, nil, nil, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 3, nil, nil, nil, nil, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2558,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 2, 7, 2, nil, nil],
                [nil, nil, 2, 1, 5, nil, nil],
                [nil, nil, 2, 3, 1, 4, nil, nil],
                [nil, nil, 2, 5, 1, nil, nil],
                [nil, nil, 6, 1, 4, 5, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 1, 2, 3, 1, nil, nil],
                [nil, nil, 3, 4, 1, nil, nil],
                [nil, nil, 3, 1, 1, 1, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2559,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 3, nil, 2, 1, nil],
                [nil, 5, 2, 6, 1, 1, 6, nil],
                [nil, 2, 1, nil, 2, 4, nil],
                [nil, 3, 1, 3, 1, 2, 5, nil],
                [nil, 1, 3, nil, 1, 2, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2560,
            rows: [
                [nil, 4, nil, 1, nil, 3, nil, 1],
                [2, nil, 1, nil, 3, nil, 2],
                [3, nil, 1, nil, 2, nil, 4, nil],
                [nil, 1, nil, 6, nil, 3, nil],
                [1, nil, 5, nil, 1, nil, 4, nil],
                [nil, 4, nil, 4, nil, 1, nil],
                [nil, 1, nil, 2, nil, 1, nil, nil],
                [6, nil, 3, nil, 1, nil, nil],
                [nil, 3, nil, 1, nil, 3, nil, nil],
                [4, nil, 2, nil, 1, nil, nil],
                [nil, nil, 6, nil, 2, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
    ]
}
