// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch114 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2261,
            rows: [
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 2, 2, 2, 3, nil, nil],
                [nil, 3, 3, 3, 3, 1, nil],
                [nil, nil, 1, 3, 3, 3, nil, nil],
                [nil, 2, 2, 1, 1, 2, nil],
                [nil, 1, 3, 1, 2, 1, 2, nil],
                [2, 1, 2, 1, 1, 1, 3],
                [nil, 3, 2, 1, 3, 3, 5, nil],
                [2, 1, 1, 2, 4, 1, 6],
                [nil, 2, 1, 2, 2, 2, 1, nil],
                [nil, 1, 1, 4, 1, 2, nil],
                [nil, 2, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2262,
            rows: [
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 5, nil, nil],
                [nil, 4, nil, nil, nil, 1, nil],
                [nil, 6, nil, nil, nil, 6, nil, nil],
                [nil, 4, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 5, nil, nil, nil, 5, nil],
                [nil, 5, nil, nil, nil, 1, nil, nil],
                [nil, 7, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 3, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2263,
            rows: [
                [1, nil, 5, nil, nil, 2, nil, 1],
                [1, nil, 2, nil, 1, 2, 1],
                [nil, 2, nil, 2, 1, nil, 2, nil],
                [1, 3, nil, nil, nil, 2, nil],
                [nil, 3, nil, 4, 1, nil, 2, nil],
                [3, 1, nil, nil, nil, 2, nil],
                [1, nil, 1, 2, 1, 1, nil, 3],
                [3, nil, nil, nil, nil, nil, 1],
                [1, nil, 3, 2, 3, 1, nil, 3],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 1, 1, 2, 2, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 3, 5, 7, 6, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2264,
            rows: [
                [nil, 2, 3, nil, nil, nil, nil, nil],
                [3, 1, 1, nil, nil, nil, nil],
                [nil, 1, 2, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, 3, 3, nil, nil, nil, nil, nil],
                [nil, nil, 2, 4, nil, nil, nil],
                [nil, nil, 3, 3, 2, nil, nil, nil],
                [nil, nil, 1, 7, nil, nil, nil],
                [nil, nil, 2, 2, 5, nil, nil, nil],
                [nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, 2, 2, 3, nil],
                [nil, nil, nil, nil, 4, 4, nil, nil],
                [nil, nil, nil, 4, 2, 2, nil],
                [nil, nil, nil, nil, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2265,
            rows: [
                [2, 1, 4, 3, 3, 2, 4, 3],
                [2, nil, nil, 4, nil, nil, 1],
                [3, nil, nil, 4, 1, nil, nil, 2],
                [nil, nil, nil, 4, nil, nil, nil],
                [1, nil, nil, 2, 1, nil, nil, 1],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 3, 4, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2266,
            rows: [
                [nil, 1, 1, 4, 3, 1, 1, nil],
                [3, nil, nil, nil, nil, nil, 2],
                [nil, 5, nil, nil, nil, nil, 2, nil],
                [2, 1, 1, 1, 4, 1, 1],
                [nil, 6, nil, nil, nil, nil, 1, nil],
                [1, 1, 2, 3, 3, 3, 2],
                [nil, 4, 4, 1, 4, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 3, 3, 2, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2267,
            rows: [
                [4, 4, 4, 5, 3, 1, 2, 3],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 2, 1, 2, 2, 1],
                [nil, 3, nil, nil, nil, nil, nil],
                [nil, 3, 3, 1, 1, 2, 2, 3],
                [nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 5, 1, 3, 3],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, 3, 2, 2, 5, 2, 1],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, 1, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 6, 1, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2268,
            rows: [
                [nil, nil, 3, nil, nil, 3, nil, nil],
                [nil, 3, 3, nil, 3, 1, nil],
                [nil, 2, 2, 2, 1, 1, 1, nil],
                [nil, 1, 1, nil, 3, 1, nil],
                [nil, 5, 5, 2, 2, 1, 1, nil],
                [nil, 4, 3, nil, 2, 6, nil],
                [nil, nil, 1, nil, nil, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2269,
            rows: [
                [2, 5, nil, nil, nil, nil, 5, 5],
                [1, 1, 4, 4, 1, 2, 2],
                [1, 2, nil, nil, nil, nil, 1, 2],
                [4, 3, 3, 1, 2, 1, 1],
                [3, 3, nil, nil, nil, nil, 1, 2],
                [1, 6, 2, 2, 1, 1, 2],
                [1, 4, nil, nil, nil, nil, 4, 3],
                [3, 1, 5, 4, 1, 2, 1],
                [4, 1, nil, nil, nil, nil, 4, 4],
                [1, 2, 1, 2, 2, 1, 2],
                [1, 1, nil, nil, nil, nil, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2270,
            rows: [
                [3, nil, nil, nil, nil, nil, nil, 2],
                [2, 1, 6, 4, 1, 3, 2],
                [5, nil, nil, nil, nil, nil, nil, 5],
                [1, 4, 1, 3, 2, 1, 2],
                [3, nil, nil, nil, nil, nil, nil, 2],
                [1, 1, 4, 4, 3, 1, 1],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, 2, 2, 1, 2, 2, 3],
                [1, nil, nil, nil, nil, nil, nil, 1],
                [2, 3, 2, 3, 3, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2271,
            rows: [
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 5, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 1, 2, nil, nil],
                [nil, 5, 3, 3, 3, nil, nil],
                [nil, 6, 2, 4, 3, 2, 1, nil],
                [nil, 2, 1, 4, 1, 1, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2272,
            rows: [
                [nil, nil, 1, 4, 1, nil, nil, nil],
                [nil, 1, 5, 1, 1, nil, nil],
                [nil, 2, 2, 2, 2, 1, nil, nil],
                [2, 5, 5, 2, 2, 2, nil],
                [nil, 1, 1, 1, 3, 1, nil, nil],
                [3, 3, 1, 1, 2, 1, nil],
                [nil, nil, 2, nil, 1, nil, nil, nil],
                [nil, 6, nil, nil, 3, nil, nil],
                [nil, nil, 4, nil, 1, nil, nil, nil],
                [nil, 3, nil, nil, 2, nil, nil],
                [nil, 3, 1, 1, nil, 3, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 2, 1, nil, 1, 6, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2273,
            rows: [
                [2, 2, nil, 1, 2, nil, 1, 1],
                [2, 6, nil, 6, nil, 2, 2],
                [nil, 4, nil, 2, 1, nil, 3, nil],
                [1, 2, 1, 2, 1, 3, 1],
                [nil, 1, nil, 1, 3, nil, 2, nil],
                [1, 3, 2, 2, 1, 1, 1],
                [nil, 1, nil, 2, 1, nil, 2, nil],
                [5, 3, nil, nil, nil, 3, 3],
                [nil, 1, nil, 1, 1, nil, 2, nil],
                [2, 2, nil, nil, nil, 1, 4],
                [1, 3, 1, nil, nil, 4, 1, 3],
                [1, 3, nil, nil, nil, 1, 1],
                [1, 1, 1, nil, nil, 3, 1, 3],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2274,
            rows: [
                [nil, 4, 1, nil, nil, 2, 1, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 3],
                [3, 3, nil, nil, nil, nil, 5, 4],
                [4, nil, nil, nil, nil, nil, 3],
                [3, 2, nil, nil, nil, nil, 2, 2],
                [1, nil, nil, nil, nil, nil, 2],
                [2, 1, nil, nil, nil, nil, 4, 4],
                [4, nil, nil, nil, nil, nil, 4],
                [1, 2, nil, nil, nil, nil, 2, 1],
                [1, 1, nil, nil, nil, 1, 4],
                [4, 1, nil, nil, nil, nil, 5, 1],
                [5, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2275,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 3, nil, nil, 5, nil, 2, nil],
                [6, nil, nil, 2, nil, nil, 3],
                [nil, 2, nil, nil, 1, nil, 2, nil],
                [1, nil, nil, 2, nil, nil, 1],
                [nil, 3, nil, nil, 2, nil, 3, nil],
                [nil, 3, nil, 1, nil, 4, nil],
                [nil, 1, nil, nil, 1, nil, 2, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [nil, nil, 2, 4, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 4, 3, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2276,
            rows: [
                [nil, 1, 1, nil, 3, 3, nil, nil],
                [1, nil, 2, 3, nil, 2, nil],
                [2, nil, nil, nil, nil, nil, 3, nil],
                [1, 1, 1, nil, nil, 4, 1],
                [1, nil, nil, nil, nil, nil, 1, nil],
                [3, 3, 7, nil, nil, 1, 2],
                [nil, 3, 3, 2, 5, 1, 2, 2],
                [nil, 1, 4, nil, nil, 2, 1],
                [nil, 2, 1, 2, 1, 2, 2, 1],
                [nil, 1, 1, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2277,
            rows: [
                [nil, 2, 4, nil, nil, 2, 3, nil],
                [1, 2, nil, nil, 3, 5, nil],
                [nil, 5, 2, nil, nil, 2, 2, nil],
                [1, 5, nil, nil, 3, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 1, nil, 3, nil, 1, nil],
                [nil, 1, nil, 4, nil, 1, nil],
                [5, nil, 5, nil, 1, nil, 2, nil],
                [nil, 2, nil, 3, nil, 3, nil],
                [3, nil, 1, nil, 2, nil, 2, nil],
                [nil, 2, nil, 1, nil, 4, nil],
                [1, nil, 1, nil, 5, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2278,
            rows: [
                [nil, nil, 5, 1, 3, nil, nil, nil],
                [nil, nil, 3, 4, 1, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, nil, 2, nil, 2, nil, 2, nil],
                [nil, 1, nil, 1, nil, 1, nil],
                [1, nil, 1, nil, 2, nil, 4, nil],
                [nil, 4, nil, 4, nil, 1, nil],
                [2, nil, 1, nil, 3, nil, 2, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [1, nil, 1, nil, 3, nil, 1, nil],
                [nil, 6, nil, 1, nil, 2, nil],
                [1, nil, 3, nil, 2, nil, 5, nil],
                [nil, 2, nil, 1, nil, 1, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2279,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 3, nil, 3, 2, nil, nil],
                [1, 2, nil, 2, 1, nil, nil],
                [nil, 3, 3, nil, 3, 3, nil, nil],
                [3, 1, nil, 2, 2, nil, nil],
                [nil, 5, 2, nil, 2, 2, nil, nil],
                [1, 4, nil, 4, 1, nil, nil],
                [nil, 2, 1, nil, 3, 1, nil, nil],
                [2, 1, nil, 1, 3, nil, nil],
                [nil, 2, 2, nil, 2, 1, nil, nil],
                [7, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, nil, 1, 1, nil, nil],
                [1, 1, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2280,
            rows: [
                [4, nil, nil, 4, 2, nil, nil, 1],
                [2, nil, 1, nil, 3, nil, 3],
                [nil, 2, 1, nil, nil, 1, 3, nil],
                [2, 2, nil, nil, nil, 4, 4],
                [nil, 2, 2, nil, nil, 5, 5, nil],
                [1, 3, nil, nil, nil, 2, 1],
                [2, nil, 4, 2, 2, 1, nil, 2],
                [1, 5, nil, nil, nil, 5, 1],
                [1, nil, 2, 2, 2, 1, nil, 4],
                [1, 1, nil, nil, nil, 6, 1],
                [nil, 2, 1, nil, nil, 4, 4, nil],
                [2, nil, 1, nil, 1, nil, 2],
                [nil, 1, 2, nil, nil, 1, 2, nil],
                [2, nil, 1, nil, 1, nil, 1],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
    ]
}
