// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch116 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2301,
            rows: [
                [2, 1, 2, 3, 3, 2, 3, 1],
                [1, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, 3, 1, 1, 4, 4],
                [7, nil, nil, nil, 1, 3, 1],
                [2, nil, nil, 2, 3, 3, 3, 3],
                [1, nil, nil, nil, 1, 2, 2],
                [3, nil, nil, nil, nil, nil, 3, 2],
                [1, 5, nil, nil, nil, nil, nil],
                [5, nil, nil, nil, nil, nil, 1, 1],
                [1, 2, nil, nil, nil, nil, nil],
                [1, 2, 1, 1, nil, nil, nil, nil],
                [1, 2, 1, 2, nil, nil, nil],
                [5, 1, 1, 1, nil, nil, nil, nil],
                [1, 1, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2302,
            rows: [
                [nil, nil, nil, 1, 1, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 2, 2, nil, 1, nil, nil],
                [nil, nil, nil, nil, 4, 2, nil],
                [nil, 1, 1, nil, 2, 4, 2, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, 2, nil, 2, nil, nil, 1, nil],
                [nil, nil, 1, 1, 4, 4, nil],
                [nil, 4, 1, 6, 6, 1, 3, nil],
                [nil, 3, 1, 3, 3, 3, nil],
                [nil, 1, 5, 1, 1, 2, 4, nil],
                [nil, 4, 1, 1, 2, 1, nil],
                [nil, 1, 1, 2, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2303,
            rows: [
                [2, 5, 5, 4, 4, 1, 3, 2],
                [1, 3, 3, 2, 1, 2, 4],
                [1, 1, 1, 3, 2, 2, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 6, 2, 3, 3, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2304,
            rows: [
                [4, nil, nil, nil, 4, 2, nil, nil],
                [1, nil, nil, 1, 2, 2, nil],
                [1, nil, nil, 2, 1, 6, 1, nil],
                [2, nil, 2, 2, 1, 2, 2],
                [5, nil, nil, 1, 7, 2, 1, nil],
                [2, nil, 1, 2, 4, 3, 3],
                [2, nil, nil, 1, 4, 1, 3, nil],
                [1, nil, nil, 1, 1, 1, nil],
                [1, nil, nil, 2, 2, 1, 4, nil],
                [1, nil, nil, 3, 1, 3, nil],
                [3, nil, nil, nil, 3, 2, nil, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [3, nil, nil, nil, 1, 4, nil, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2305,
            rows: [
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [4, nil, nil, 1, nil, nil, 1],
                [1, 1, 2, 1, 1, 2, 4, 2],
                [3, nil, nil, 3, nil, nil, 3],
                [3, 3, 3, 1, 4, 1, 2, 4],
                [1, nil, nil, 2, nil, nil, 1],
                [nil, 2, nil, 2, nil, nil, 5, nil],
                [nil, nil, 7, 1, nil, nil, nil],
                [nil, 4, nil, 1, nil, nil, 4, nil],
                [nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2306,
            rows: [
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, nil, 1, 1, 3, 3, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, nil, 2, 4, 4, 1, nil, nil],
                [nil, nil, 6, nil, 1, nil, nil],
                [1, 1, 3, nil, nil, 2, 1, 2],
                [nil, nil, 1, nil, 1, nil, nil],
                [2, 3, 3, nil, nil, 2, 2, 5],
                [nil, nil, 3, nil, 1, nil, nil],
                [nil, nil, 1, 3, 1, 3, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 2, 1, 1, 1, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2307,
            rows: [
                [nil, nil, 4, nil, nil, 1, nil, nil],
                [nil, 7, nil, nil, 3, nil, nil],
                [nil, 4, nil, nil, 1, 2, 1, nil],
                [3, nil, nil, nil, nil, 3, nil],
                [nil, 3, nil, nil, 2, 1, 3, nil],
                [1, nil, nil, nil, nil, 3, nil],
                [2, 1, 1, 3, nil, 4, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [1, 5, 2, 4, nil, 1, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, 7, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2308,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 3],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, 3, 1, 4, nil, nil],
                [nil, nil, 1, 1, 3, 2, nil, nil],
                [nil, 1, 1, 1, 2, 1, nil],
                [nil, 3, 2, 2, 1, 1, 1, nil],
                [nil, 1, 1, 2, 2, 4, nil],
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, 1, 4, 2, nil, nil],
                [nil, nil, nil, 6, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2309,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 3, 1, 2, 2, 2, nil],
                [1, nil, nil, nil, nil, nil, 4],
                [4, nil, 4, 1, 1, 3, nil, 1],
                [1, nil, nil, nil, nil, nil, 3],
                [nil, 1, 1, 5, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, 6, 1, 3, nil, nil],
                [nil, nil, 5, 2, 3, nil, nil],
                [nil, nil, 3, 1, 1, 3, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2310,
            rows: [
                [nil, 1, 1, 3, 1, 3, 2, nil],
                [2, nil, nil, nil, nil, nil, 1],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [3, 1, 1, 1, 2, 3, 2],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [3, 3, 1, 1, 1, 2, 1],
                [nil, 4, 2, 1, 1, 2, 6, nil],
                [nil, 2, 2, 4, 4, 2, nil],
                [nil, 5, 2, 1, 2, 1, 5, nil],
                [nil, 3, 2, 1, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2311,
            rows: [
                [1, nil, nil, 1, 3, nil, nil, 1],
                [2, nil, 1, 4, 1, nil, 5],
                [nil, 1, nil, 3, 1, nil, 2, nil],
                [nil, 2, 2, 2, 2, 1, nil],
                [nil, 3, nil, 4, 4, nil, 4, nil],
                [nil, 1, 6, 6, 3, 3, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 3, 5, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [1, 2, 3, 1, 1, 1, 1, 1],
                [5, nil, nil, nil, nil, nil, 1],
                [3, 1, 1, 2, 2, 4, 2, 1],
                [3, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2312,
            rows: [
                [1, nil, 3, 2, 3, 1, nil, 4],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 1, 3, 4, 2, 1, 5, 5],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 3, 2, 6, nil, nil],
                [nil, nil, 4, 1, 2, nil, nil],
                [nil, nil, 3, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, 1, nil, 2, nil, 1],
                [2, nil, 3, nil, 1, nil, 3],
                [nil, 2, nil, 2, nil, 2, nil, 5],
                [1, nil, 2, nil, 2, nil, 1],
                [nil, 3, nil, 3, nil, 1, nil, 1],
                [3, nil, 6, nil, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [3, nil, 3, nil, 3, nil, 3],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2313,
            rows: [
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [2, 3, 3, 1, 1, 2, 5, 5],
                [nil, nil, nil, nil, nil, nil, 5],
                [5, 4, 1, 2, 1, 3, 3, 3],
                [nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, 3, nil],
                [nil, 3, 1, 2, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, 2, 1, 1, 2, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [5, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [1, 2, 3, 3, 1, 5, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2314,
            rows: [
                [2, 1, 1, 2, 1, 1, 2, 1],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [2, 1, 2, 1, 1, 2, 2, 3],
                [nil, nil, nil, nil, 3, nil, nil],
                [5, 1, 2, 3, 1, 2, 2, 1],
                [nil, nil, nil, nil, 6, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [2, 2, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2315,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 5, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [2, 5, 5, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 4, 2, 2, 5, 2, 2, 4],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2316,
            rows: [
                [nil, 3, 3, 1, 2, 2, 3, nil],
                [nil, 3, 1, 1, 2, 5, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [7, 2, 1, 1, 1, 2, 3, 3],
                [1, nil, nil, nil, nil, nil, 3],
                [4, nil, 4, 1, 3, 2, nil, 5],
                [4, nil, 4, 4, 3, nil, 1],
                [1, nil, 1, 1, 2, 3, nil, 3],
                [2, nil, nil, nil, nil, nil, 3],
                [2, 1, 1, 1, 2, 1, 3, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 1, 2, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 1, 1, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2317,
            rows: [
                [nil, 2, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 2, 6, 6, 3, 4, 2, nil],
                [nil, nil, nil, nil, nil, nil, 4],
                [nil, 1, 4, 3, 2, 2, 3, nil],
                [nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, 2, 2, 2, 2, 3, nil],
                [nil, nil, nil, nil, nil, nil, 4, nil],
                [nil, 1, 3, 4, 1, 1, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [nil, 1, 5, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2318,
            rows: [
                [nil, nil, 2, nil, nil, 2, 1, nil],
                [nil, 1, 3, nil, nil, 3, 3],
                [3, nil, nil, 1, 5, 1, nil, nil],
                [2, 4, nil, 2, nil, nil, nil],
                [1, nil, nil, 3, 3, 3, nil, nil],
                [3, 5, nil, 5, nil, nil, nil],
                [2, nil, 1, 2, 1, 2, 6, nil],
                [nil, 1, nil, nil, 1, nil, 1],
                [1, nil, 1, 2, 1, 1, 2, nil],
                [nil, 2, nil, nil, 2, nil, 1],
                [nil, 2, 1, nil, nil, nil, 2, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 2, 1, nil, nil, nil, 4, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2319,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 4, 1, nil, nil],
                [nil, nil, 2, 4, 2, nil, nil],
                [nil, nil, 3, 3, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 2, 3, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 1, 4, 2, 1, nil, nil],
                [nil, nil, 5, 2, 2, nil, nil],
                [nil, nil, 1, 4, 5, 1, nil, nil],
                [nil, nil, 7, 3, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2320,
            rows: [
                [nil, 3, nil, 2, nil, 4, nil, 1],
                [2, nil, 1, nil, 1, nil, 3],
                [1, nil, 2, nil, 1, nil, 5, nil],
                [nil, 1, nil, 3, nil, 1, nil],
                [7, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 2, nil, 2, nil],
                [nil, 2, nil, 1, nil, 1, nil, nil],
                [2, nil, 1, nil, 1, nil, nil],
                [nil, 1, nil, 1, nil, 2, nil, nil],
                [2, nil, 4, nil, 2, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, 5, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
    ]
}
