// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch109 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2161,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 3, 3, nil, nil, nil, nil],
                [nil, nil, 3, 4, nil, nil, nil, nil],
                [nil, 1, 2, 1, nil, nil, nil],
                [nil, nil, 4, 1, nil, nil, nil, nil],
                [nil, 3, 2, 1, nil, nil, nil],
                [1, 2, 2, 2, 2, 1, 3, nil],
                [1, 1, 3, 1, 1, 1, nil],
                [3, 1, 3, 4, 1, 3, 2, nil],
                [1, 2, 1, 5, 2, 2, nil],
                [1, 3, 1, 1, 3, 3, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 1, 1, 5, 3, 1, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2162,
            rows: [
                [nil, 4, 6, nil, nil, 2, 2, nil],
                [2, nil, 3, nil, 1, nil, 3],
                [2, nil, nil, 1, 1, nil, nil, 1],
                [3, nil, nil, nil, nil, nil, 1],
                [4, nil, nil, 3, 1, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, 4, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, nil, 2, nil, nil, 1, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, nil, 2, nil, nil, 2, nil, nil],
                [nil, nil, 2, nil, 4, nil, nil],
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2163,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [2, 2, 1, 2, 1, 1, 4, 6],
                [nil, nil, nil, nil, 5, nil, nil],
                [2, 1, 4, 1, 2, 4, 2, 4],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 1, nil, 3, nil, nil],
                [nil, nil, nil, 1, 6, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2164,
            rows: [
                [nil, nil, nil, nil, nil, nil, 3, 1],
                [nil, nil, 1, 1, 1, 1, 5],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, 1, 3],
                [nil, 5, nil, nil, nil, 4, nil],
                [nil, 1, 1, nil, nil, 2, nil, nil],
                [3, 1, 6, nil, 1, nil, nil],
                [nil, 3, 1, nil, nil, 1, nil, nil],
                [3, 1, 4, nil, 1, nil, nil],
                [2, nil, 5, 2, 2, 1, nil, 4],
                [nil, 1, nil, 2, nil, 1, 3],
                [1, nil, 2, 1, 2, 1, nil, 1],
                [nil, 4, nil, 1, nil, 1, 1],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2165,
            rows: [
                [nil, 1, nil, nil, 3, 2, 3, nil],
                [1, nil, nil, 3, 1, 2, nil],
                [2, nil, nil, 2, 2, 1, nil, nil],
                [3, nil, 1, 1, 3, nil, nil],
                [3, nil, nil, 5, 4, 2, nil, nil],
                [3, nil, 1, 2, 2, nil, nil],
                [3, nil, nil, 3, 1, 6, nil, nil],
                [6, nil, 1, 1, 2, 2, nil],
                [2, nil, nil, 1, 2, 1, nil, nil],
                [1, nil, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2166,
            rows: [
                [nil, 2, 1, nil, nil, 1, 1, nil],
                [5, 2, 5, 4, 1, 2, 2],
                [1, 6, 3, 2, 1, 5, 5, 5],
                [2, 4, 1, 1, 1, 1, 1],
                [2, 3, 3, 3, 1, 1, 3, 1],
                [1, 2, 1, 1, 2, 2, 1],
                [nil, 3, 1, nil, nil, 4, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, 4, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2167,
            rows: [
                [1, 5, nil, 1, 1, nil, 7, 3],
                [3, nil, nil, 5, nil, nil, 5],
                [4, nil, nil, 4, nil, nil, 2, nil],
                [1, nil, nil, 1, nil, nil, 3],
                [2, nil, nil, 1, nil, nil, 2, nil],
                [2, nil, nil, 2, nil, nil, 1],
                [4, nil, nil, 1, nil, nil, 3, nil],
                [3, nil, nil, 3, nil, nil, 2],
                [1, nil, nil, 3, nil, nil, 3, nil],
                [1, nil, nil, 5, nil, nil, 1],
                [3, nil, nil, 1, nil, nil, 2, nil],
                [1, nil, nil, 2, nil, nil, 1],
                [1, nil, nil, 5, nil, nil, 2, nil],
                [2, nil, nil, 2, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2168,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 1],
                [5, 5, 5, 6, 3, 1, 3],
                [5, nil, nil, nil, nil, nil, nil, 2],
                [3, 3, 2, 4, 2, 4, 3],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [3, 2, 2, 1, 4, 3, 1],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2169,
            rows: [
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, 2, 4, 4, 3, nil, nil],
                [nil, 4, 1, 3, 2, 2, nil],
                [nil, nil, 3, 1, 5, 1, nil, nil],
                [nil, 4, 5, 5, 1, 6, nil],
                [nil, nil, 1, 4, 2, 2, nil, nil],
                [nil, nil, 4, 4, 1, nil, nil],
                [nil, nil, 3, 3, 1, 1, nil, nil],
                [nil, nil, 3, 2, 6, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2170,
            rows: [
                [nil, 2, nil, 1, nil, 3, nil, 2],
                [3, 3, nil, 1, 3, nil, 4],
                [4, nil, 1, nil, 1, nil, 2, nil],
                [1, 2, nil, 4, 1, nil, 3],
                [2, nil, 1, nil, 2, nil, 2, nil],
                [1, 1, nil, 2, 1, nil, 2],
                [nil, 1, nil, 3, nil, 4, nil, 3],
                [1, 1, nil, 2, 4, nil, 3],
                [nil, 1, nil, 1, nil, 1, nil, 2],
                [1, 1, nil, 1, 3, nil, 1],
                [2, nil, 6, nil, 1, nil, 2, nil],
                [1, 4, nil, 2, 1, nil, 2],
                [2, nil, 1, nil, 2, nil, 3, nil],
                [1, 1, nil, 4, 1, nil, 1],
                [nil, 1, nil, 4, nil, 3, nil, 4],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2171,
            rows: [
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, 2, 1, 2, 1, 2, nil],
                [nil, nil, nil, 2, 6, nil, nil, nil],
                [nil, nil, 6, 2, 3, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 4, 1, nil, nil],
                [nil, nil, nil, 7, 1, nil, nil, nil],
                [nil, 5, 5, 3, 3, 1, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, 2, 3, 1, 3, 1, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2172,
            rows: [
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [nil, 1, 1, 3, 3, 1, nil],
                [nil, 5, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, 3, 3, 3, 1, 1, 4, 3],
                [nil, 2, nil, nil, nil, nil, 1],
                [nil, 1, 3, 2, 3, 1, 1, 1],
                [nil, 6, nil, nil, nil, nil, 1],
                [nil, nil, nil, 1, 4, 1, 3, nil],
                [nil, 3, 5, nil, nil, nil, nil],
                [nil, nil, nil, 5, 2, 4, 1, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2173,
            rows: [
                [2, 2, 1, 1, 3, 4, 1, 3],
                [nil, nil, nil, nil, nil, nil, 3],
                [1, 2, 2, 2, 2, 1, 4, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [1, 1, 3, 1, 1, 1, 1, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [1, 1, 2, 2, 6, 3, 3, 2],
                [nil, nil, nil, nil, nil, nil, 3],
                [1, 3, 1, 3, 1, 1, 1, 2],
                [nil, nil, nil, nil, nil, nil, 1],
                [1, 3, 1, 1, 2, 2, 2, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [2, 2, 1, 1, 3, 5, 1, nil],
                [4, nil, nil, nil, nil, nil, nil],
                [nil, 1, 3, 4, 3, 3, 3, 3],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2174,
            rows: [
                [2, 4, 1, 1, 3, 1, 3, 2],
                [2, nil, nil, 1, nil, nil, 2],
                [1, 1, 1, 3, 1, 2, 3, 1],
                [2, nil, nil, 2, nil, nil, 2],
                [2, 6, 1, 1, 1, 2, 3, 3],
                [3, nil, nil, 2, nil, nil, 2],
                [nil, 2, nil, nil, 1, nil, nil, 3],
                [1, 1, 3, 1, 3, 3, 1],
                [nil, 1, nil, nil, 4, nil, nil, 4],
                [2, 1, 1, 2, 1, 1, 1],
                [nil, 1, nil, nil, 3, nil, nil, 1],
                [3, nil, nil, 1, nil, nil, 3],
                [nil, 1, nil, nil, 3, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2175,
            rows: [
                [4, 1, 3, 2, 1, 2, 1, 3],
                [2, 2, 3, 1, 2, 2, 1],
                [3, 1, 3, 1, 2, 3, 1, 2],
                [2, 1, 6, 1, 1, 2, 4],
                [1, 1, 3, 1, 4, 1, 5, 4],
                [1, 3, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2176,
            rows: [
                [1, nil, nil, 1, nil, 1, 1, 2],
                [2, nil, 2, nil, 2, nil, 5],
                [3, nil, nil, 3, nil, nil, nil, 3],
                [5, 1, 1, nil, nil, nil, 1],
                [2, nil, nil, 2, nil, nil, nil, 4],
                [2, 4, 1, nil, nil, nil, 4],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, nil, nil, 2, nil, 2, 2, nil],
                [nil, nil, 5, nil, 1, nil, nil],
                [nil, nil, nil, 1, nil, 4, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, 1, 6, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2177,
            rows: [
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, 1, nil, 2, nil, 2, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, 1, nil, 3, nil, 6, nil],
                [1, 1, 1, 2, 1, 5, 2, 2],
                [1, nil, 3, nil, 3, nil, 1],
                [7, 1, 1, 2, 1, 1, 1, 1],
                [1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2178,
            rows: [
                [6, nil, 1, nil, nil, 3, nil, 3],
                [4, nil, 2, nil, 1, nil, 6],
                [3, nil, nil, 2, 1, nil, nil, 1],
                [3, nil, 1, 3, 3, nil, 4],
                [4, nil, nil, 1, 2, nil, nil, 1],
                [1, nil, 1, 2, 3, nil, 3],
                [3, nil, nil, 2, 1, nil, nil, 2],
                [1, nil, 2, nil, 1, nil, 2],
                [1, nil, nil, 2, 1, nil, nil, 2],
                [2, nil, 1, nil, 2, nil, 1],
                [1, nil, 2, nil, nil, 1, nil, 2],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, 2, nil, nil, 2, nil, 1],
                [2, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2179,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, 3, 3, nil, nil, nil, nil],
                [3, 5, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, nil, 4, 4, nil],
                [4, 4, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, 2, 2, nil, 1, 2],
                [nil, 3, 3, nil, nil, nil, nil],
                [nil, nil, nil, 6, 5, nil, 1, 2],
                [nil, 1, 5, nil, nil, nil, nil],
                [1, 2, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, 2, 1, nil],
                [2, 1, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2180,
            rows: [
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [2, nil, nil, 4, nil, nil, 4],
                [1, nil, nil, 3, 5, nil, nil, 4],
                [2, nil, nil, 6, nil, nil, 1],
                [3, nil, nil, 5, 2, nil, nil, 1],
                [2, nil, nil, 1, nil, nil, 4],
                [nil, 1, 3, 2, 1, 3, 1, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, 3, 5, 5, 1, 1, 1, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
    ]
}
