// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch105 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2081,
            rows: [
                [nil, 1, 3, 4, 4, 1, 1, nil],
                [nil, 2, 1, 3, 2, 3, nil],
                [nil, nil, 1, 3, 1, 2, nil, nil],
                [nil, nil, 2, 3, 1, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 1, 5, 5, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 2, nil, nil, nil, nil, nil, nil],
                [2, 1, nil, nil, nil, nil, nil],
                [nil, 2, 7, nil, nil, nil, nil, nil],
                [nil, 5, 1, nil, nil, nil, nil],
                [nil, nil, 5, 3, nil, nil, nil, nil],
                [nil, nil, 1, 5, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2082,
            rows: [
                [6, 1, 1, 1, 1, 2, 3, 1],
                [2, nil, nil, nil, nil, nil, 1],
                [1, nil, nil, 2, 4, 2, 3, 3],
                [2, nil, nil, nil, 4, 4, 1],
                [2, nil, nil, 2, 1, 2, 1, 1],
                [4, nil, nil, nil, 2, 4, 1],
                [2, nil, nil, nil, nil, nil, 2, 1],
                [1, 2, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, 4, 1],
                [3, 2, nil, nil, nil, nil, nil],
                [2, 2, 1, 3, nil, nil, nil, nil],
                [1, 1, 5, 1, nil, nil, nil],
                [1, 2, 3, 1, nil, nil, nil, nil],
                [1, 1, 3, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2083,
            rows: [
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [2, nil, nil, 4, nil, nil, 1],
                [2, 5, 5, 1, 6, 6, 3, 2],
                [1, nil, nil, 1, nil, nil, 4],
                [2, 2, 1, 1, 1, 4, 1, 3],
                [3, nil, nil, 1, nil, nil, 5],
                [nil, 2, nil, 2, nil, nil, 3, nil],
                [nil, nil, 3, 4, nil, nil, nil],
                [nil, 2, nil, 2, nil, nil, 2, nil],
                [nil, nil, 5, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, 1, 4, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 4, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2084,
            rows: [
                [nil, 5, nil, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, 3, 5, 1, nil, nil],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, 2, 2, 1, 3, nil, nil],
                [nil, nil, 1, nil, 5, nil, nil],
                [1, 1, 3, nil, nil, 1, 2, 1],
                [nil, nil, 3, nil, 3, nil, nil],
                [3, 1, 5, nil, nil, 6, 1, 3],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 4, 1, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2085,
            rows: [
                [nil, nil, 2, nil, nil, 4, nil, nil],
                [nil, 1, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, 1, 1, 6, nil],
                [4, nil, nil, nil, nil, 5, nil],
                [nil, 3, nil, nil, 3, 2, 1, nil],
                [2, nil, nil, nil, nil, 2, nil],
                [1, 1, 1, 1, nil, 4, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [1, 2, 4, 1, nil, 4, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2086,
            rows: [
                [4, nil, nil, nil, nil, nil, nil, 4],
                [nil, 4, nil, nil, nil, 5, nil],
                [nil, nil, 2, nil, nil, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 6, 1, nil, nil],
                [nil, nil, 3, 5, 1, 1, nil, nil],
                [nil, 3, 1, 1, 2, 3, nil],
                [nil, 3, 1, 2, 2, 5, 3, nil],
                [nil, 3, 1, 5, 1, 1, nil],
                [nil, nil, 1, 5, 5, 2, nil, nil],
                [nil, nil, 1, 5, 3, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2087,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 2, 5, 1, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 2, 2, 2, nil, 4],
                [4, nil, nil, nil, nil, nil, 3],
                [nil, 3, 5, 2, 5, 4, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 1, 1, 6, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, nil, 1, 1, 7, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2088,
            rows: [
                [nil, 1, 4, 2, 1, 2, 1, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, 3, nil, nil, nil, nil, 2, nil],
                [1, 2, 2, 2, 1, 3, 1],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [4, 4, 1, 1, 2, 2, 1],
                [nil, 2, 1, 7, 2, 1, 1, nil],
                [nil, 2, 1, 1, 1, 4, nil],
                [nil, 2, 1, 5, 3, 6, 2, nil],
                [nil, 1, 2, 2, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2089,
            rows: [
                [4, nil, nil, 2, 2, nil, nil, 5],
                [3, nil, 3, 3, 1, nil, 1],
                [nil, 5, nil, 5, 4, nil, 1, nil],
                [nil, 2, 2, 2, 2, 1, nil],
                [nil, 1, nil, 3, 3, nil, 1, nil],
                [nil, 1, 1, 1, 2, 1, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 5, 1, 2, nil, nil],
                [nil, nil, nil, 1, 7, nil, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [2, 4, 5, 1, 3, 1, 1, 2],
                [2, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2090,
            rows: [
                [1, nil, 2, 2, 4, 1, nil, 2],
                [1, nil, nil, nil, nil, nil, 1],
                [2, 2, 1, 3, 2, 2, 4, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 5, 5, 4, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 1, nil, 2, nil, 1],
                [1, nil, 2, nil, 1, nil, 2],
                [nil, 2, nil, 2, nil, 2, nil, 3],
                [3, nil, 4, nil, 4, nil, 4],
                [nil, 1, nil, 1, nil, 1, nil, 2],
                [3, nil, 1, nil, 3, nil, 3],
                [nil, 2, nil, 1, nil, 1, nil, 2],
                [2, nil, 7, nil, 2, nil, 2],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2091,
            rows: [
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 1, 4, 6, 3, 3],
                [nil, nil, nil, nil, nil, nil, 4],
                [3, 3, 3, 3, 3, 3, 1, 1],
                [nil, nil, nil, nil, nil, nil, 4],
                [nil, nil, nil, nil, nil, nil, 2, nil],
                [nil, 4, 1, 2, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, 4, nil],
                [nil, 4, 2, 2, 6, 2, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 5, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [2, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2092,
            rows: [
                [1, 2, 1, 3, 2, 3, 3, 1],
                [nil, nil, nil, nil, 6, nil, nil],
                [nil, nil, nil, 6, 2, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [2, 1, 3, 3, 4, 1, 1, 1],
                [nil, nil, nil, nil, 1, nil, nil],
                [1, 2, 1, 1, 2, 2, 2, 3],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [2, 3, 3, 1, 5, 3, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2093,
            rows: [
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 7, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [4, 4, 2, 2, 3, 1, 2, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 2, 3, 2, 1, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2094,
            rows: [
                [nil, 2, 1, 1, 2, 2, 1, nil],
                [nil, 2, 1, 3, 1, 2, nil],
                [nil, nil, 2, 2, 5, 5, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 3, 3, 3, 1, 7, 1, 1],
                [1, nil, nil, nil, nil, nil, 3],
                [3, nil, 3, 3, 1, 1, nil, 4],
                [1, nil, 1, 1, 1, nil, 1],
                [2, nil, 2, 1, 2, 1, nil, 3],
                [1, nil, nil, nil, nil, nil, 2],
                [1, 3, 1, 4, 1, 3, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 4, 1, 4, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2095,
            rows: [
                [nil, nil, 3, nil, nil, 2, 2, nil],
                [nil, 2, 1, nil, nil, 4, 6],
                [1, nil, nil, 1, 2, 5, nil, nil],
                [3, 4, nil, 1, nil, nil, nil],
                [1, nil, nil, 1, 1, 4, nil, nil],
                [3, 2, nil, 2, nil, nil, nil],
                [3, nil, 1, 1, 3, 1, 1, nil],
                [nil, 1, nil, nil, 4, nil, 1],
                [1, nil, 1, 2, 1, 1, 1, nil],
                [nil, 1, nil, nil, 5, nil, 2],
                [nil, 1, 1, nil, nil, nil, 3, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 2, 7, nil, nil, nil, 3, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2096,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 7, 2, 1, 3, nil, nil],
                [nil, nil, 3, 3, 7, nil, nil],
                [nil, nil, 3, 3, 3, 1, nil, nil],
                [nil, nil, 2, 4, 6, nil, nil],
                [nil, nil, 2, 1, 5, 1, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 1, 2, 1, 4, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2097,
            rows: [
                [nil, 5, nil, 3, nil, 2, nil, 2],
                [1, nil, 1, nil, 2, nil, 2],
                [1, nil, 1, nil, 1, nil, 3, nil],
                [nil, 2, nil, 2, nil, 1, nil],
                [3, nil, 1, nil, 4, nil, 1, nil],
                [nil, 3, nil, 3, nil, 4, nil],
                [nil, 5, nil, 1, nil, 2, nil, nil],
                [3, nil, 2, nil, 1, nil, nil],
                [nil, 1, nil, 3, nil, 4, nil, nil],
                [2, nil, 6, nil, 1, nil, nil],
                [nil, nil, 1, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2098,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 2, 1, 4, nil, nil],
                [nil, nil, 1, 5, 3, 5, nil, nil],
                [nil, 3, 5, 1, 2, 3, nil],
                [nil, nil, 3, 2, 1, 1, nil, nil],
                [nil, 1, 2, 2, 3, 2, nil],
                [nil, 2, 1, 1, 5, 1, 2, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, 2, 6, 1, 1, 1, 1, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2099,
            rows: [
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, nil, 3, nil, nil, 2, nil],
                [nil, nil, 1, nil, nil, 5, nil],
                [nil, nil, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, 4, nil, nil],
                [nil, nil, nil, nil, nil, nil, 5, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, 7],
                [nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, 5, 5, nil, nil, nil],
                [nil, nil, 2, 3, 2, nil, nil],
                [nil, nil, 2, 5, 3, 3, nil, nil],
                [nil, 3, 2, 4, 4, 5, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2100,
            rows: [
                [nil, nil, 1, 2, 1, 6, nil, nil],
                [nil, nil, 2, 2, 3, nil, nil],
                [nil, nil, 3, 2, 2, 4, nil, nil],
                [nil, nil, 1, 2, 4, nil, nil],
                [nil, nil, 1, 6, 1, 2, nil, nil],
                [nil, nil, 1, 1, 3, nil, nil],
                [nil, nil, 3, 1, 5, 5, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 2, 1, 3, 1, nil, nil],
                [nil, nil, 2, 2, 1, nil, nil],
                [nil, nil, 1, 1, 3, 4, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 2, 1, 1, 3, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 1, 1, 3, 2, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
    ]
}
