// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch125 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2481,
            rows: [
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, 6, 2, nil, nil, nil, nil],
                [5, 1, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, 3, 5, nil],
                [4, 1, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, 4, 4, nil],
                [nil, nil, nil, 1, 4, nil, 1, 2],
                [nil, 1, 3, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, 4, 1],
                [nil, 3, 1, nil, nil, nil, nil],
                [2, 5, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, nil, 3, 1, nil],
                [5, 3, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2482,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 6, 5, 3, nil, nil],
                [nil, nil, 4, 5, 1, nil, nil],
                [nil, nil, 1, 2, 1, 2, nil, nil],
                [nil, nil, 1, 3, 2, nil, nil],
                [nil, nil, 1, 2, 1, 1, nil, nil],
                [nil, nil, 5, 1, 2, nil, nil],
                [nil, nil, 1, 5, 3, 2, nil, nil],
                [nil, nil, 3, 2, 1, nil, nil],
                [nil, nil, 3, 2, 6, 3, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2483,
            rows: [
                [nil, nil, 4, nil, nil, 5, nil, nil],
                [nil, 5, 5, nil, 5, 5, nil],
                [nil, 1, 3, 1, 3, 2, 2, nil],
                [nil, 1, 2, nil, 3, 2, nil],
                [nil, 1, 1, 1, 2, 1, 1, nil],
                [nil, 2, 4, nil, 3, 1, nil],
                [nil, nil, 2, nil, nil, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2484,
            rows: [
                [nil, 1, nil, 4, nil, 5, nil, 1],
                [5, nil, 1, nil, 3, nil, 2],
                [5, nil, 2, nil, 6, nil, 2, nil],
                [nil, 1, nil, 2, nil, 3, nil],
                [2, nil, 1, nil, 2, nil, 1, nil],
                [nil, 4, nil, 1, nil, 7, nil],
                [nil, 1, nil, 1, nil, 2, nil, nil],
                [1, nil, 2, nil, 1, nil, nil],
                [nil, 2, nil, 1, nil, 3, nil, nil],
                [2, nil, 1, nil, 2, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, 1, nil, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2485,
            rows: [
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 4, nil],
                [nil, nil, 1, 2, 1, 3, nil, nil],
                [nil, nil, 1, nil, 3, nil, nil],
                [nil, nil, 1, 2, 1, 2, nil, nil],
                [nil, nil, 3, nil, 5, nil, nil],
                [3, 1, 6, nil, nil, 3, 2, 1],
                [nil, nil, 1, nil, 1, nil, nil],
                [3, 2, 1, nil, nil, 3, 2, 1],
                [nil, nil, 1, nil, 4, nil, nil],
                [nil, nil, 2, 3, 2, 3, nil, nil],
                [nil, 4, nil, nil, nil, 4, nil],
                [nil, nil, 4, 2, 1, 4, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2486,
            rows: [
                [5, nil, nil, nil, nil, nil, nil, 3],
                [2, nil, 1, 2, 4, nil, 1],
                [nil, 2, 3, nil, nil, 2, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 2, 2, nil, nil, 4, 1, nil],
                [nil, 3, nil, nil, nil, 4, nil],
                [nil, 2, 3, nil, nil, 2, 2, nil],
                [nil, 6, nil, nil, nil, 2, nil],
                [nil, 1, 1, nil, nil, 2, 1, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, nil, 5, nil, nil, 1, nil, nil],
                [nil, nil, 2, 1, 4, nil, nil],
                [nil, nil, 3, nil, nil, 1, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2487,
            rows: [
                [nil, nil, 1, 2, 1, nil, nil, nil],
                [nil, nil, 1, 1, 3, nil, nil],
                [nil, nil, nil, 2, 6, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 5, nil, 1, nil, 2, nil],
                [nil, 1, nil, 5, nil, 4, nil],
                [2, nil, 1, nil, 3, nil, 1, nil],
                [nil, 2, nil, 1, nil, 3, nil],
                [1, nil, 2, nil, 1, nil, 2, nil],
                [nil, 4, nil, 1, nil, 3, nil],
                [2, nil, 3, nil, 1, nil, 5, nil],
                [nil, 1, nil, 3, nil, 4, nil],
                [1, nil, 4, nil, 1, nil, 2, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2488,
            rows: [
                [nil, 1, 2, 3, 5, 1, 2, nil],
                [4, nil, nil, nil, nil, nil, 2],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [5, 1, 5, 3, 1, 3, 3],
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [2, 1, 5, 2, 3, 1, 2],
                [nil, 1, 2, 1, 1, 3, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 3, 6, 5, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2489,
            rows: [
                [nil, nil, 4, 1, 2, nil, nil, nil],
                [nil, 1, nil, nil, 3, nil, nil],
                [nil, nil, 1, 3, 1, 2, 1, nil],
                [nil, 3, 1, 5, nil, nil, 2],
                [nil, nil, 2, 1, 2, 1, 6, nil],
                [nil, 1, 2, 3, nil, nil, 1],
                [nil, 2, nil, nil, 5, 2, 1, nil],
                [nil, 1, 3, 1, 3, 1, nil],
                [nil, 7, nil, nil, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2490,
            rows: [
                [1, nil, nil, nil, 3, nil, nil, nil],
                [2, nil, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, 2, 1, nil, nil],
                [nil, 2, nil, 1, nil, 3, nil],
                [nil, 2, nil, nil, 3, 1, nil, nil],
                [nil, 3, nil, 1, nil, 2, nil],
                [nil, 2, nil, nil, 3, 1, nil, nil],
                [3, nil, nil, 6, 2, 6, nil],
                [nil, 3, nil, nil, 1, 4, nil, nil],
                [4, nil, nil, 1, 5, 1, nil],
                [2, nil, nil, nil, 5, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, 3, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2491,
            rows: [
                [3, 1, nil, nil, nil, nil, 2, 1],
                [3, 2, nil, nil, nil, 5, 3],
                [2, 3, nil, nil, nil, nil, 3, 3],
                [2, nil, nil, nil, nil, nil, 5],
                [1, 5, nil, nil, nil, nil, 2, 1],
                [3, nil, nil, nil, nil, nil, 2],
                [3, 2, nil, nil, nil, nil, 5, 2],
                [1, nil, nil, nil, nil, nil, 3],
                [1, 3, nil, nil, nil, nil, 6, 2],
                [3, nil, nil, nil, nil, nil, 1],
                [2, 2, nil, nil, nil, nil, 1, 2],
                [2, 1, nil, nil, nil, 3, 1],
                [2, 6, nil, nil, nil, nil, 1, 2],
                [1, 2, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2492,
            rows: [
                [1, 3, 1, 2, 3, 2, 1, 3],
                [1, 1, 2, 1, 2, 1, 2],
                [1, 5, 2, 1, 4, 6, 2, 1],
                [2, 3, 2, 1, 3, 4, 4],
                [3, 1, 3, 6, 2, 2, 5, 1],
                [5, 2, 2, 1, 3, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2493,
            rows: [
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, 2, 1, 4, nil, nil],
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, 6, 1, nil, 3, 3, nil],
                [nil, nil, nil, 5, 4, nil, nil, nil],
                [nil, 5, 3, nil, 2, 1, nil],
                [nil, 3, 1, 2, 7, 2, 1, nil],
                [nil, 2, 1, nil, 2, 1, nil],
                [nil, 2, 5, 1, 1, 5, 2, nil],
                [nil, 1, 2, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2494,
            rows: [
                [nil, nil, nil, 5, 3, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, 3, 2, 1, 2, nil, nil],
                [nil, 4, 1, 3, 2, 4, nil],
                [nil, nil, 2, 1, 1, 6, nil, nil],
                [nil, 3, 1, 3, 1, 2, nil],
                [nil, nil, 1, 6, 2, 2, nil, nil],
                [nil, nil, 1, 4, 1, nil, nil],
                [nil, nil, 6, 2, 5, 3, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, 2, 5, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2495,
            rows: [
                [nil, nil, 3, nil, nil, 5, nil, nil],
                [nil, 6, nil, nil, 1, nil, nil],
                [nil, 5, nil, nil, 1, 2, 1, nil],
                [4, nil, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, 2, 5, 1, nil],
                [2, nil, nil, nil, nil, 2, nil],
                [1, 2, 1, 3, nil, 1, nil, nil],
                [nil, nil, 6, nil, nil, nil, nil],
                [1, 2, 1, 5, nil, 1, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2496,
            rows: [
                [nil, 3, nil, nil, 1, 5, 2, nil],
                [2, nil, nil, 1, 1, 3, nil],
                [1, nil, nil, 2, 2, 1, nil, nil],
                [3, nil, 1, 2, 1, nil, nil],
                [2, nil, nil, 1, 2, 1, nil, nil],
                [2, nil, 1, 1, 2, nil, nil],
                [1, nil, nil, 2, 3, 1, nil, nil],
                [2, nil, 1, 1, 6, 1, nil],
                [3, nil, nil, 2, 3, 1, nil, nil],
                [3, nil, 2, 3, 1, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2497,
            rows: [
                [1, nil, nil, 2, nil, 1, 4, 5],
                [6, nil, 2, nil, 1, nil, 4],
                [3, nil, nil, 3, nil, nil, nil, 1],
                [2, 1, 4, nil, nil, nil, 1],
                [2, nil, nil, 4, nil, nil, nil, 1],
                [3, 1, 2, nil, nil, nil, 3],
                [nil, nil, nil, 1, nil, 2, 3, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, nil, 2, nil, 3, 1, nil],
                [nil, nil, 2, nil, 4, nil, nil],
                [nil, nil, nil, 1, nil, 2, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2498,
            rows: [
                [2, 3, 1, 1, 3, 1, 2, 2],
                [1, nil, nil, 2, nil, nil, 1],
                [3, 1, 1, 4, 2, 1, 3, 2],
                [4, nil, nil, 3, nil, nil, 6],
                [6, 1, 3, 1, 2, 1, 2, 1],
                [3, nil, nil, 1, nil, nil, 5],
                [nil, 2, nil, nil, 4, nil, nil, 1],
                [2, 3, 2, 2, 3, 2, 1],
                [nil, 3, nil, nil, 2, nil, nil, 1],
                [2, 1, 2, 1, 4, 1, 3],
                [nil, 1, nil, nil, 3, nil, nil, 1],
                [3, nil, nil, 1, nil, nil, 3],
                [nil, 2, nil, nil, 1, nil, nil, 3],
                [1, nil, nil, 3, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2499,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 3, 2, 4, nil, nil],
                [nil, nil, 4, 2, 1, 3, nil, nil],
                [nil, 2, 3, 2, 3, 1, nil],
                [nil, nil, 4, 3, 3, 1, nil, nil],
                [nil, 3, 2, 3, 1, 3, nil],
                [nil, 5, 1, 3, 2, 6, 1, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 2, 3, 3, 1, 3, 1, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2500,
            rows: [
                [nil, 1, nil, nil, nil, nil, 5, nil],
                [2, nil, nil, 5, nil, nil, 2],
                [3, 1, 2, 4, 1, 3, 6, 3],
                [5, nil, nil, 1, nil, nil, 3],
                [5, 1, 4, 5, 1, 4, 1, 3],
                [1, nil, nil, 3, nil, nil, 2],
                [nil, 3, nil, 2, nil, nil, 1, nil],
                [nil, nil, 5, 2, nil, nil, nil],
                [nil, 1, nil, 2, nil, nil, 3, nil],
                [nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, 3, 2, nil, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, 4, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
    ]
}
