// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch117 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2321,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 2, 1, nil, nil],
                [nil, 6, 2, 1, 3, 3, nil],
                [nil, nil, 1, 1, 4, 1, nil, nil],
                [nil, 2, 1, 5, 1, 2, nil],
                [nil, 2, 5, 2, 2, 2, 2, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, 5, 3, 3, 2, 3, 4, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2322,
            rows: [
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, 5, nil, nil],
                [nil, nil, nil, 3, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, 1, nil],
                [nil, nil, nil, nil, 1, nil, nil, 2],
                [nil, nil, nil, 3, nil, nil, 1],
                [nil, nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, 7],
                [nil, nil, nil, nil, nil, nil, 5],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 2, 1, 2, nil, nil],
                [nil, nil, 1, 2, 1, 2, nil, nil],
                [nil, 2, 3, 1, 1, 4, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2323,
            rows: [
                [nil, nil, 1, 1, 2, 1, nil, nil],
                [nil, nil, 4, 2, 1, nil, nil],
                [nil, nil, 2, 3, 3, 1, nil, nil],
                [nil, nil, 3, 6, 2, nil, nil],
                [nil, nil, 4, 4, 2, 1, nil, nil],
                [nil, nil, 1, 2, 2, nil, nil],
                [nil, nil, 2, 1, 2, 1, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 2, 2, 2, 1, nil, nil],
                [nil, nil, 4, 4, 4, nil, nil],
                [nil, nil, 3, 4, 4, 4, nil, nil],
                [nil, nil, 4, 1, 3, nil, nil],
                [nil, nil, 1, 3, 2, 2, nil, nil],
                [nil, nil, 1, 3, 1, nil, nil],
                [nil, nil, 5, 3, 1, 3, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2324,
            rows: [
                [1, 5, nil, nil, nil, nil, 2, 1],
                [1, nil, nil, nil, nil, nil, 4],
                [nil, nil, 5, 1, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 6, 5, 1, 3, nil, nil],
                [nil, 2, nil, nil, nil, 3, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 1, 2, nil, nil, nil],
                [2, 2, nil, nil, nil, nil, 1, 5],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, nil, 3, nil, nil, 1],
                [3, nil, nil, 1, nil, nil, 3],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2325,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, 2, 2, nil, nil, nil, nil],
                [nil, nil, 7, 1, nil, nil, nil, nil],
                [nil, 1, 2, 1, nil, nil, nil],
                [nil, nil, 4, 4, nil, nil, nil, nil],
                [nil, 2, 3, 5, nil, nil, nil],
                [1, 4, 1, 2, 1, 1, 2, nil],
                [5, 2, 1, 3, 2, 1, nil],
                [1, 2, 5, 1, 2, 2, 3, nil],
                [2, 1, 6, 2, 2, 1, nil],
                [2, 1, 2, 2, 1, 3, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2326,
            rows: [
                [nil, 1, 3, nil, nil, 2, 1, nil],
                [2, nil, 1, nil, 3, nil, 4],
                [4, nil, nil, 1, 5, nil, nil, 1],
                [3, nil, nil, nil, nil, nil, 1],
                [7, nil, nil, 1, 3, nil, nil, 3],
                [1, nil, nil, nil, nil, nil, 2],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, 6, nil, nil, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2327,
            rows: [
                [nil, nil, nil, nil, 7, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil],
                [2, 5, 4, 2, 1, 1, 1, 2],
                [nil, nil, nil, nil, 2, nil, nil],
                [1, 6, 1, 5, 5, 2, 2, 3],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 3, nil, 3, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 2, nil, 1, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, 6, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2328,
            rows: [
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, 4, 1, 1, 2, 2],
                [nil, nil, nil, nil, nil, nil, 1, 4],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 3, 3],
                [nil, 2, nil, nil, nil, 4, nil],
                [nil, 1, 1, nil, nil, 1, nil, nil],
                [3, 5, 1, nil, 1, nil, nil],
                [nil, 1, 2, nil, nil, 1, nil, nil],
                [2, 2, 2, nil, 1, nil, nil],
                [1, nil, 2, 2, 1, 3, nil, 4],
                [nil, 4, nil, 4, nil, 1, 3],
                [1, nil, 3, 1, 2, 1, nil, 1],
                [nil, 1, nil, 1, nil, 1, 1],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2329,
            rows: [
                [nil, 2, nil, nil, 2, 4, 1, nil],
                [1, nil, nil, 3, 1, 1, nil],
                [3, nil, nil, 3, 3, 1, nil, nil],
                [2, nil, 2, 1, 2, nil, nil],
                [1, nil, nil, 2, 1, 2, nil, nil],
                [1, nil, 6, 7, 2, nil, nil],
                [2, nil, nil, 1, 4, 4, nil, nil],
                [2, nil, 2, 1, 2, 1, nil],
                [1, nil, nil, 1, 3, 3, nil, nil],
                [2, nil, 1, 2, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2330,
            rows: [
                [nil, 1, 2, nil, nil, 3, 4, nil],
                [4, 4, 1, 2, 6, 3, 1],
                [4, 1, 1, 1, 2, 2, 7, 2],
                [4, 3, 3, 3, 1, 2, 1],
                [2, 4, 2, 2, 1, 1, 1, 4],
                [3, 2, 4, 2, 3, 3, 1],
                [nil, 5, 2, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 2, nil, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2331,
            rows: [
                [3, 3, nil, 3, 2, nil, 1, 6],
                [6, nil, nil, 1, nil, nil, 4],
                [4, nil, nil, 4, nil, nil, 4, nil],
                [1, nil, nil, 2, nil, nil, 2],
                [3, nil, nil, 3, nil, nil, 2, nil],
                [5, nil, nil, 1, nil, nil, 1],
                [5, nil, nil, 2, nil, nil, 2, nil],
                [1, nil, nil, 1, nil, nil, 4],
                [1, nil, nil, 5, nil, nil, 2, nil],
                [5, nil, nil, 5, nil, nil, 1],
                [2, nil, nil, 1, nil, nil, 2, nil],
                [1, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1, nil],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2332,
            rows: [
                [4, nil, nil, nil, nil, nil, nil, 4],
                [6, 3, 1, 3, 4, 1, 2],
                [2, nil, nil, nil, nil, nil, nil, 5],
                [5, 1, 4, 1, 1, 2, 1],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [4, 1, 3, 3, 1, 2, 4],
                [nil, nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2333,
            rows: [
                [nil, 1, nil, 1, nil, 5, nil, 5],
                [2, nil, 2, nil, 5, nil, 5],
                [nil, 5, nil, 2, nil, 2, nil, 2],
                [3, nil, 3, nil, 4, nil, 4],
                [nil, 1, nil, 4, nil, 1, nil, 1],
                [1, nil, 1, nil, 6, nil, 6],
                [nil, 1, nil, 1, nil, 3, nil, 1],
                [3, nil, 4, nil, 2, nil, 1],
                [nil, 2, nil, 1, nil, 3, nil, 1],
                [3, nil, 3, nil, 3, nil, 2],
                [nil, 1, nil, 4, nil, 1, nil, 2],
                [1, nil, 2, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2334,
            rows: [
                [nil, 3, 2, nil, 2, 1, nil, nil],
                [nil, 2, 1, nil, 2, 2, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 3, nil, nil, nil, 1, nil],
                [nil, 2, nil, nil, nil, 4, nil, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 6, nil, nil, nil],
                [nil, nil, 5, 3, 3, nil, nil],
                [nil, nil, 3, 1, 4, nil, nil, nil],
                [nil, 1, 3, 1, nil, nil, nil],
                [nil, 5, 1, 4, nil, nil, nil, nil],
                [nil, 1, 7, 1, nil, nil, nil],
                [nil, 4, 1, 1, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2335,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, 1],
                [3, nil, 3, 1, 2, nil, 1],
                [nil, nil, 2, 2, nil, 1, 2, nil],
                [nil, nil, nil, nil, nil, 2, 2],
                [nil, 1, 2, nil, nil, 4, 4, nil],
                [nil, 1, 6, nil, 1, 4, 1],
                [4, 4, 1, nil, nil, 1, 1, 5],
                [1, 2, 1, nil, 1, 2, 2],
                [1, 1, 1, nil, nil, 2, 2, 1],
                [3, 1, 4, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2336,
            rows: [
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 4, 3, 3, nil, nil],
                [nil, nil, 4, 5, 4, 4, nil, nil],
                [nil, 6, 1, 4, 1, 1, nil],
                [nil, nil, 2, 4, 1, 1, nil, nil],
                [nil, 1, 2, 2, 2, 4, nil],
                [nil, nil, 4, 4, 4, 1, nil, nil],
                [nil, nil, 1, 1, 2, nil, nil],
                [nil, nil, 1, 2, 2, 1, nil, nil],
                [nil, nil, 3, 1, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2337,
            rows: [
                [nil, 3, nil, 5, nil, 2, nil, 1],
                [2, 3, nil, 3, 1, nil, 1],
                [1, nil, 1, nil, 2, nil, 1, nil],
                [3, 1, nil, 2, 1, nil, 6],
                [2, nil, 1, nil, 3, nil, 3, nil],
                [1, 1, nil, 2, 3, nil, 2],
                [nil, 1, nil, 3, nil, 3, nil, 2],
                [1, 1, nil, 3, 4, nil, 1],
                [nil, 1, nil, 1, nil, 4, nil, 1],
                [1, 2, nil, 3, 2, nil, 1],
                [4, nil, 4, nil, 4, nil, 2, nil],
                [3, 2, nil, 3, 1, nil, 3],
                [3, nil, 2, nil, 2, nil, 2, nil],
                [1, 1, nil, 2, 1, nil, 1],
                [nil, 3, nil, 2, nil, 1, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2338,
            rows: [
                [nil, 1, 1, 1, nil, nil, 1, 2],
                [nil, 1, 2, 1, nil, nil, 1],
                [nil, 1, 2, 2, nil, nil, 1, 1],
                [nil, 6, 3, 1, nil, 2, 1],
                [nil, 3, 1, 2, nil, nil, 2, 1],
                [nil, 1, 1, 4, nil, 1, 2],
                [nil, 2, 2, 2, nil, 1, 4, 1],
                [nil, 2, 1, 4, nil, 1, 3],
                [nil, 3, 1, 2, nil, 1, 2, 1],
                [nil, 1, 1, 1, nil, 2, 2],
                [nil, 1, 6, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1],
                [nil, nil, nil, nil, nil, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2339,
            rows: [
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, 2, 2, 2, 3, 4, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 3, 4, 4, nil, nil],
                [nil, nil, nil, 1, 7, nil, nil, nil],
                [nil, nil, 7, 5, 2, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, 1, 1, 2, 1, 3, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, 2, 2, 1, 3, 2, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2340,
            rows: [
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [nil, 6, 4, 6, 2, 1, nil],
                [nil, 6, nil, nil, nil, nil, nil, nil],
                [2, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, 4, 5, 1, 2, 2, 3, 1],
                [nil, 2, nil, nil, nil, nil, 1],
                [nil, 3, 2, 1, 1, 2, 1, 4],
                [nil, 1, nil, nil, nil, nil, 2],
                [nil, nil, nil, 2, 1, 5, 2, nil],
                [nil, 1, 2, nil, nil, nil, nil],
                [nil, nil, nil, 2, 1, 4, 1, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
    ]
}
