// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch110 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2181,
            rows: [
                [nil, nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, 2, 1, 1, nil, nil],
                [nil, nil, 3, 1, 6, 1, nil, nil],
                [nil, 3, 1, 6, 2, 4, nil],
                [nil, nil, 4, 4, 1, 1, nil, nil],
                [nil, 1, 1, 3, 3, 3, nil],
                [nil, 1, nil, 2, 5, nil, 2, nil],
                [2, 1, 1, 2, 2, 1, 3],
                [nil, 2, nil, 2, 2, nil, 1, nil],
                [3, 1, 1, 2, 2, 5, 2],
                [nil, 2, nil, 1, 1, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 5, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2182,
            rows: [
                [nil, nil, 2, 1, 4, nil, nil, nil],
                [nil, 3, nil, nil, 3, nil, nil],
                [nil, nil, 3, 1, 2, 1, 3, nil],
                [nil, 1, 1, 1, nil, nil, 1],
                [nil, nil, 2, 1, 3, 3, 3, nil],
                [nil, 1, 1, 5, nil, nil, 2],
                [nil, 4, nil, nil, 4, 1, 2, nil],
                [nil, 2, 1, 2, 1, 3, nil],
                [nil, 5, nil, nil, 3, 3, 1, nil],
                [nil, 3, 1, 1, 3, 1, nil],
                [nil, nil, 3, 5, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 3, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2183,
            rows: [
                [nil, nil, 3, nil, nil, 4, nil, nil],
                [nil, nil, 5, 1, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 5, 6, 1, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 1, 2, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 2, 1, 7, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2184,
            rows: [
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 3, 1, nil, nil],
                [nil, 7, nil, 2, nil, 1, nil],
                [nil, nil, 1, 1, 1, 2, nil, nil],
                [nil, 2, nil, 3, nil, 3, nil],
                [1, nil, nil, 1, 1, nil, nil, 1],
                [2, 5, nil, 5, nil, 5, 1],
                [1, nil, nil, 5, 2, nil, nil, 1],
                [2, 3, nil, 2, nil, 2, 2],
                [nil, 1, 4, 4, 1, 1, 3, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, 1, 1, 1, 3, 3, 1, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2185,
            rows: [
                [nil, 1, 3, nil, nil, 3, 1, nil],
                [nil, 6, nil, nil, nil, 1, nil],
                [nil, 5, nil, nil, nil, 5, nil, nil],
                [nil, 4, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 7, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 7, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2186,
            rows: [
                [5, nil, 5, nil, nil, 3, nil, 3],
                [3, nil, 2, nil, 2, 2, 2],
                [nil, 1, nil, 2, 3, nil, 3, nil],
                [1, 1, nil, nil, nil, 4, nil],
                [nil, 2, nil, 1, 2, nil, 4, nil],
                [1, 2, nil, nil, nil, 1, nil],
                [3, nil, 1, 1, 2, 1, nil, 2],
                [1, nil, nil, nil, nil, nil, 2],
                [1, nil, 6, 4, 1, 2, nil, 3],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 3, 4, 4, 2, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 1, 2, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2187,
            rows: [
                [nil, 2, 2, nil, nil, nil, nil, nil],
                [3, 1, 1, nil, nil, nil, nil],
                [nil, 3, 4, nil, nil, nil, nil, nil],
                [nil, nil, 1, 4, nil, nil, nil],
                [nil, 1, 2, nil, nil, nil, nil, nil],
                [nil, nil, 4, 2, nil, nil, nil],
                [nil, nil, 4, 1, 4, nil, nil, nil],
                [nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, 2, 2, 6, nil, nil, nil],
                [nil, nil, 4, 4, nil, nil, nil],
                [nil, nil, nil, nil, 3, 1, nil, nil],
                [nil, nil, nil, 1, 3, 7, nil],
                [nil, nil, nil, nil, 1, 3, nil, nil],
                [nil, nil, nil, 1, 3, 1, nil],
                [nil, nil, nil, nil, 1, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2188,
            rows: [
                [1, 5, 2, 2, 1, 3, 3, 1],
                [3, nil, nil, 2, nil, nil, 2],
                [1, nil, nil, 4, 1, nil, nil, 6],
                [nil, nil, nil, 1, nil, nil, nil],
                [1, nil, nil, 1, 1, nil, nil, 2],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 4, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 5, nil, nil, nil],
                [nil, nil, nil, 5, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 6, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2189,
            rows: [
                [nil, 4, 1, 4, 5, 1, 6, nil],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [3, 5, 2, 1, 4, 1, 1],
                [nil, 4, nil, nil, nil, nil, 4, nil],
                [5, 2, 5, 2, 2, 1, 1],
                [nil, 3, 3, 2, 2, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 6, 3, 6, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2190,
            rows: [
                [nil, nil, 2, nil, nil, 1, nil, nil],
                [nil, 4, 4, nil, 2, 1, nil],
                [nil, 2, 1, 2, 2, 1, 2, nil],
                [nil, 2, 2, nil, 3, 1, nil],
                [nil, 1, 5, 3, 5, 1, 5, nil],
                [nil, 3, 3, nil, 1, 2, nil],
                [nil, nil, 3, nil, nil, 5, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2191,
            rows: [
                [3, 3, nil, nil, nil, nil, 1, 3],
                [3, 4, 4, 3, 2, 1, 1],
                [3, 2, nil, nil, nil, nil, 2, 3],
                [5, 4, 1, 5, 2, 1, 2],
                [2, 3, nil, nil, nil, nil, 6, 1],
                [1, 3, 1, 1, 2, 3, 4],
                [4, 3, nil, nil, nil, nil, 3, 1],
                [2, 1, 1, 1, 1, 1, 2],
                [1, 2, nil, nil, nil, nil, 3, 2],
                [2, 2, 3, 1, 1, 3, 3],
                [3, 1, nil, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, 4, nil, nil, nil, nil, 1, 3],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2192,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 5],
                [2, 3, 1, 3, 1, 2, 1],
                [2, nil, nil, nil, nil, nil, nil, 3],
                [1, 2, 4, 2, 2, 2, 1],
                [3, nil, nil, nil, nil, nil, nil, 3],
                [6, 2, 3, 3, 1, 3, 3],
                [1, nil, nil, nil, nil, nil, nil, 3],
                [2, 4, 2, 2, 1, 2, 2],
                [1, nil, nil, nil, nil, nil, nil, 3],
                [3, 4, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2193,
            rows: [
                [nil, nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, 6, nil],
                [nil, nil, nil, nil, 4, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [nil, 4, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 2, 2, 1, 5, nil, nil],
                [nil, 3, 3, 1, 1, nil, nil],
                [nil, 2, 2, 5, 3, 3, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2194,
            rows: [
                [nil, nil, 1, 1, 3, nil, nil, nil],
                [nil, 1, 2, 3, 3, nil, nil],
                [nil, 5, 1, 2, 2, 2, nil, nil],
                [2, 1, 6, 1, 1, 1, nil],
                [nil, 1, 2, 1, 1, 3, nil, nil],
                [3, 3, 1, 5, 2, 1, nil],
                [nil, nil, 4, nil, 5, nil, nil, nil],
                [nil, 5, nil, nil, 1, nil, nil],
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, 1, 1, 1, nil, 2, 2, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 4, 1, nil, 3, 1, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2195,
            rows: [
                [1, 4, nil, 1, 1, nil, 6, 1],
                [2, 3, nil, 3, nil, 3, 3],
                [nil, 3, nil, 3, 1, nil, 4, nil],
                [4, 4, 4, 4, 1, 1, 2],
                [nil, 1, nil, 2, 3, nil, 3, nil],
                [3, 2, 5, 1, 1, 1, 1],
                [nil, 2, nil, 2, 1, nil, 2, nil],
                [2, 2, nil, nil, nil, 1, 2],
                [nil, 1, nil, 6, 1, nil, 2, nil],
                [1, 1, nil, nil, nil, 1, 1],
                [1, 1, 1, nil, nil, 1, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [1, 1, 1, nil, nil, 1, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2196,
            rows: [
                [nil, 2, 3, nil, nil, 2, 1, nil],
                [2, nil, nil, nil, nil, nil, 2],
                [1, 2, nil, nil, nil, nil, 4, 4],
                [4, nil, nil, nil, nil, nil, 3],
                [6, 6, nil, nil, nil, nil, 2, 3],
                [1, nil, nil, nil, nil, nil, 2],
                [2, 5, nil, nil, nil, nil, 1, 3],
                [2, nil, nil, nil, nil, nil, 3],
                [1, 3, nil, nil, nil, nil, 1, 1],
                [2, nil, nil, nil, nil, nil, 5],
                [1, 1, nil, nil, nil, nil, 1, 3],
                [2, 3, nil, nil, nil, 3, 1],
                [2, 1, nil, nil, nil, nil, 1, 3],
                [1, 1, nil, nil, nil, 2, 3],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2197,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, 1, nil, nil, 1, nil, 4, nil],
                [3, nil, nil, 1, nil, nil, 1],
                [nil, 1, nil, nil, 6, nil, 5, nil],
                [1, nil, nil, 4, nil, nil, 3],
                [nil, 1, nil, nil, 7, nil, 1, nil],
                [nil, 1, nil, 3, nil, 2, nil],
                [nil, 4, nil, nil, 2, nil, 2, nil],
                [nil, 1, nil, 1, nil, 4, nil],
                [nil, nil, 2, 2, 1, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 3, 3, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2198,
            rows: [
                [nil, 2, 2, nil, 3, 1, nil, nil],
                [1, nil, 2, 2, nil, 2, nil],
                [2, nil, nil, nil, nil, nil, 3, nil],
                [2, 2, 1, nil, nil, 2, 1],
                [2, nil, nil, nil, nil, nil, 3, nil],
                [3, 3, 2, nil, nil, 5, 5],
                [nil, 1, 4, 1, 4, 1, 2, 1],
                [nil, 4, 1, nil, nil, 7, 4],
                [nil, 1, 2, 1, 3, 1, 1, 1],
                [nil, 1, 1, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2199,
            rows: [
                [nil, 1, 1, nil, nil, 1, 3, nil],
                [2, 1, nil, nil, 4, 4, nil],
                [nil, 1, 2, nil, nil, 1, 3, nil],
                [1, 4, nil, nil, 2, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, nil, 1, nil, 3, nil, 3, nil],
                [nil, 1, nil, 2, nil, 1, nil],
                [4, nil, 4, nil, 1, nil, 4, nil],
                [nil, 1, nil, 2, nil, 2, nil],
                [1, nil, 1, nil, 2, nil, 1, nil],
                [nil, 7, nil, 3, nil, 1, nil],
                [5, nil, 1, nil, 2, nil, 1, nil],
                [nil, 4, nil, 4, nil, 1, nil],
                [3, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2200,
            rows: [
                [nil, nil, 1, 2, 3, nil, nil, nil],
                [nil, nil, 1, 1, 3, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [3, nil, 3, nil, 3, nil, 1, nil],
                [nil, 3, nil, 1, nil, 2, nil],
                [2, nil, 2, nil, 2, nil, 3, nil],
                [nil, 3, nil, 3, nil, 5, nil],
                [1, nil, 3, nil, 4, nil, 1, nil],
                [nil, 6, nil, 1, nil, 1, nil],
                [4, nil, 6, nil, 1, nil, 4, nil],
                [nil, 1, nil, 5, nil, 5, nil],
                [3, nil, 2, nil, 1, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
    ]
}
