// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch133 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 2641,
            rows: [
                [nil, 1, nil, 2, nil, 1, nil, 6],
                [2, nil, 1, nil, 2, nil, 1],
                [nil, 2, nil, 1, nil, 3, nil, 1],
                [2, nil, 1, nil, 1, nil, 7],
                [nil, 5, nil, 1, nil, 2, nil, 1],
                [1, nil, 1, nil, 5, nil, 2],
                [nil, 1, nil, 2, nil, 1, nil, 3],
                [1, nil, 5, nil, 1, nil, 4],
                [nil, 3, nil, 2, nil, 3, nil, 2],
                [1, nil, 1, nil, 2, nil, 4],
                [nil, 1, nil, 3, nil, 5, nil, 1],
                [2, nil, 1, nil, 4, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2642,
            rows: [
                [5, 6, 2, 5, 1, 3, 2, 3],
                [4, nil, nil, 2, nil, nil, 1],
                [4, nil, nil, 2, 5, nil, nil, 1],
                [nil, nil, nil, 3, nil, nil, nil],
                [1, nil, nil, 2, 1, nil, nil, 3],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 5, 1, nil, nil, nil],
                [nil, nil, nil, 4, nil, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2643,
            rows: [
                [nil, 3, 1, nil, nil, 4, 1, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, 5, nil, nil, nil, 3, nil, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 2, nil, nil, nil, 7, nil],
                [nil, 1, nil, nil, nil, 3, nil, nil],
                [nil, 1, nil, nil, nil, 5, nil],
                [nil, 2, nil, nil, nil, 1, nil, nil],
                [nil, 2, nil, nil, nil, 3, nil],
                [nil, 3, nil, nil, nil, 5, nil, nil],
                [nil, 2, nil, nil, nil, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2644,
            rows: [
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [2, 2, nil, nil, nil, 1, 5],
                [nil, 2, nil, nil, nil, nil, 1, nil],
                [3, 6, nil, nil, nil, 3, 2],
                [nil, 2, nil, nil, nil, nil, 3, nil],
                [4, 1, nil, nil, nil, 5, 2],
                [nil, 1, nil, nil, nil, nil, 3, nil],
                [4, 1, nil, nil, nil, 2, 1],
                [nil, 4, nil, nil, nil, nil, 3, nil],
                [1, 4, nil, nil, nil, 5, 1],
                [nil, 5, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, nil, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2645,
            rows: [
                [5, nil, nil, 3, nil, 1, 1, 5],
                [1, nil, 2, nil, 1, nil, 1],
                [4, nil, nil, 1, nil, nil, nil, 2],
                [4, 1, 2, nil, nil, nil, 1],
                [4, nil, nil, 2, nil, nil, nil, 3],
                [4, 4, 3, nil, nil, nil, 7],
                [nil, nil, nil, 1, nil, 2, 1, nil],
                [nil, nil, 4, nil, 1, nil, nil],
                [nil, nil, nil, 3, nil, 3, 5, nil],
                [nil, nil, 1, nil, 1, nil, nil],
                [nil, nil, nil, 1, nil, 2, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 2, nil, 5, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2646,
            rows: [
                [1, 2, 1, 1, 3, 1, 2, 2],
                [6, nil, nil, 1, nil, nil, 3],
                [1, 3, 1, 4, 1, 3, 3, 1],
                [2, nil, nil, 3, nil, nil, 1],
                [4, 1, 3, 2, 1, 2, 3, 1],
                [2, nil, nil, 2, nil, nil, 7],
                [nil, 1, nil, nil, 5, nil, nil, 2],
                [1, 3, 1, 1, 3, 2, 1],
                [nil, 2, nil, nil, 1, nil, nil, 3],
                [1, 2, 1, 2, 1, 1, 2],
                [nil, 1, nil, nil, 2, nil, nil, 1],
                [3, nil, nil, 1, nil, nil, 1],
                [nil, 1, nil, nil, 1, nil, nil, 1],
                [1, nil, nil, 1, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2647,
            rows: [
                [nil, nil, nil, nil, 1, nil, nil, nil],
                [5, 2, 1, 2, nil, nil, nil],
                [4, nil, nil, 6, nil, nil, nil, nil],
                [nil, nil, nil, 5, 5, 5, 1],
                [2, nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, nil, 1, 2, 1, 5],
                [1, nil, nil, nil, 2, nil, nil, 1],
                [2, 2, 1, 3, nil, nil, nil],
                [2, nil, nil, nil, 1, nil, nil, 6],
                [2, 1, 3, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil, 3],
                [nil, nil, nil, 2, 1, 2, 1],
                [nil, nil, nil, 2, nil, nil, nil, 3],
                [nil, nil, nil, 1, 2, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2648,
            rows: [
                [1, nil, 5, nil, 3, nil, 2, nil],
                [nil, 3, nil, 5, nil, 3, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, 2, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [7, nil, nil, nil, nil, nil, nil, 2],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil, 1],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2649,
            rows: [
                [1, 3, nil, nil, nil, nil, 2, 6],
                [2, 1, nil, nil, nil, 1, 4],
                [1, 3, nil, nil, nil, nil, 5, 2],
                [1, nil, nil, nil, nil, nil, 2],
                [1, 2, nil, nil, nil, nil, 1, 2],
                [3, nil, nil, nil, nil, nil, 2],
                [1, 1, nil, nil, nil, nil, 3, 3],
                [2, nil, nil, nil, nil, nil, 2],
                [3, 2, nil, nil, nil, nil, 1, 3],
                [3, nil, nil, nil, nil, nil, 1],
                [3, 1, nil, nil, nil, nil, 4, 2],
                [6, 1, nil, nil, nil, 4, 4],
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 1, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2650,
            rows: [
                [nil, nil, 2, nil, nil, 1, nil, nil],
                [nil, 1, 3, nil, 1, 2, nil],
                [nil, 3, 2, 6, 2, 2, 7, nil],
                [nil, 3, 2, nil, 3, 5, nil],
                [nil, 3, 5, 2, 4, 1, 2, nil],
                [nil, 6, 2, nil, 1, 2, nil],
                [nil, nil, 3, nil, nil, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2651,
            rows: [
                [nil, 1, nil, nil, nil, nil, 2, nil],
                [1, nil, nil, 3, nil, nil, 2],
                [3, nil, nil, 1, 2, nil, nil, 1],
                [4, nil, nil, 1, nil, nil, 4],
                [1, nil, nil, 1, 3, nil, nil, 5],
                [3, nil, nil, 1, nil, nil, 5],
                [nil, 1, 3, 1, 2, 7, 2, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, 2, 1, 5, 1, 2, 1, nil],
                [nil, nil, nil, 3, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2652,
            rows: [
                [nil, nil, 4, nil, nil, 3, nil, nil],
                [nil, 1, nil, nil, 2, nil, nil],
                [nil, 4, nil, nil, 4, 3, 1, nil],
                [1, nil, nil, nil, nil, 3, nil],
                [nil, 3, nil, nil, 4, 2, 1, nil],
                [2, nil, nil, nil, nil, 3, nil],
                [1, 4, 4, 1, nil, 2, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [5, 1, 2, 2, nil, 4, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, 6, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2653,
            rows: [
                [1, nil, 2, nil, nil, 3, nil, 1],
                [1, nil, 2, nil, 1, nil, 5],
                [2, nil, nil, 1, 3, nil, nil, 3],
                [1, nil, 3, 1, 2, nil, 1],
                [2, nil, nil, 1, 4, nil, nil, 1],
                [2, nil, 1, 6, 1, nil, 2],
                [1, nil, nil, 2, 1, nil, nil, 2],
                [1, nil, 2, nil, 1, nil, 5],
                [1, nil, nil, 1, 2, nil, nil, 1],
                [3, nil, 1, nil, 2, nil, 3],
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2654,
            rows: [
                [1, nil, nil, nil, 2, nil, nil, nil],
                [1, nil, nil, nil, 3, nil, nil],
                [nil, 2, nil, nil, 1, 7, nil, nil],
                [nil, 4, nil, 1, nil, 2, nil],
                [nil, 1, nil, nil, 2, 1, nil, nil],
                [nil, 2, nil, 4, nil, 4, nil],
                [nil, 2, nil, nil, 1, 3, nil, nil],
                [1, nil, nil, 3, 1, 4, nil],
                [nil, 2, nil, nil, 4, 1, nil, nil],
                [1, nil, nil, 4, 1, 2, nil],
                [3, nil, nil, nil, 4, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, nil, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2655,
            rows: [
                [nil, 1, nil, 3, nil, 5, nil, 3],
                [1, nil, 3, nil, 5, nil, 1],
                [nil, 3, nil, 1, nil, 1, nil, 1],
                [2, nil, 5, nil, 5, nil, 2],
                [nil, 3, nil, 3, nil, 4, nil, 4],
                [2, nil, 3, nil, 3, nil, 1],
                [nil, 4, nil, 2, nil, 1, nil, 2],
                [4, nil, 1, nil, 5, nil, 1],
                [nil, 6, nil, 1, nil, 3, nil, 1],
                [2, nil, 1, nil, 1, nil, 2],
                [nil, 1, nil, 2, nil, 1, nil, 1],
                [2, nil, 1, nil, 2, nil, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2656,
            rows: [
                [nil, nil, 2, 3, 2, nil, nil, nil],
                [nil, nil, 2, 1, 4, nil, nil],
                [nil, nil, nil, 5, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 2, nil, 5, nil, 1, nil],
                [nil, 1, nil, 3, nil, 3, nil],
                [1, nil, 1, nil, 3, nil, 5, nil],
                [nil, 1, nil, 2, nil, 3, nil],
                [4, nil, 2, nil, 1, nil, 3, nil],
                [nil, 3, nil, 1, nil, 3, nil],
                [1, nil, 2, nil, 1, nil, 2, nil],
                [nil, 4, nil, 6, nil, 1, nil],
                [2, nil, 1, nil, 4, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2657,
            rows: [
                [3, 4, 3, 2, 3, 2, 5, 2],
                [5, nil, nil, 1, nil, nil, 1],
                [2, nil, nil, 1, 3, nil, nil, 1],
                [nil, nil, nil, 2, nil, nil, nil],
                [1, nil, nil, 3, 2, nil, nil, 1],
                [nil, nil, nil, 6, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 2, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, 1, nil, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2658,
            rows: [
                [6, 3, 4, 2, 4, 1, 4, 1],
                [nil, nil, nil, nil, 4, nil, nil],
                [nil, nil, nil, 1, 4, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [1, 6, 2, 1, 5, 2, 1, 3],
                [nil, nil, nil, nil, 1, nil, nil],
                [3, 1, 2, 1, 1, 2, 6, 1],
                [nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [nil, nil, nil, 1, 3, nil, nil, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [1, 2, 1, 3, 3, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2659,
            rows: [
                [nil, 1, 3, nil, nil, 1, 6, nil],
                [nil, 5, nil, nil, nil, 1, nil],
                [nil, 4, nil, nil, nil, 3, nil, nil],
                [nil, 1, nil, nil, nil, 4, nil],
                [nil, 1, nil, nil, nil, 3, nil, nil],
                [nil, 1, nil, nil, nil, 3, nil],
                [nil, 1, nil, nil, nil, 3, nil, nil],
                [nil, 2, nil, nil, nil, 1, nil],
                [nil, 7, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, 1, nil, nil, nil, 2, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 2
        ),
        LevelTemplate(
            levelNumber: 2660,
            rows: [
                [nil, nil, nil, 4, 1, nil, nil, nil],
                [nil, 2, 3, nil, nil, nil, nil],
                [4, 2, nil, 1, 3, nil, nil, nil],
                [nil, nil, nil, nil, 1, 2, nil],
                [3, 3, nil, 2, 3, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, 2, 4, nil, 3, 2],
                [nil, 5, 2, nil, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, 2, 4],
                [nil, 5, 7, nil, nil, nil, nil],
                [1, 2, nil, 3, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, 3, nil],
                [2, 1, nil, 2, 2, nil, nil, nil],
                [nil, nil, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, 3, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 2
        ),
    ]
}
