// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch18 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 341,
            rows: [
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [5, 5, 5, 5, 5, 4, 4],
                [4, 4, 4, 4, 4, 3, 3, 2],
                [2, 7, 6, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 342,
            rows: [
                [3, 3, 3, nil, nil, 3, 3, 3],
                [nil, nil, 2, nil, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, nil, 4, nil, 4, nil],
                [nil, nil, 4, 1, 1, 1, nil, nil],
                [nil, 1, nil, 1, nil, 6, nil],
                [nil, nil, 5, 5, 5, 5, nil, nil],
                [nil, nil, 5, 2, 2, nil, nil],
                [nil, nil, 2, 2, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, 1, nil, nil, 1, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, nil, nil, 7, 6, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 343,
            rows: [
                [nil, nil, 3, 3, 3, 3, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 3, 3, nil, 3, 1, nil, 1],
                [6, 6, nil, 1, 1, nil, 1],
                [nil, 1, 1, 2, 2, 2, 7, nil],
                [7, 7, 2, 2, 2, 1, nil],
                [nil, nil, 1, 1, nil, 1, 1, nil],
                [nil, 1, 1, nil, 2, 2, nil],
                [nil, nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 4, 4, 4, 2, nil, nil],
                [nil, 2, 5, 5, 1, nil, nil],
                [nil, nil, nil, 2, 2, nil, nil, nil],
                [nil, nil, 2, 1, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 4
        ),
        LevelTemplate(
            levelNumber: 344,
            rows: [
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [4, nil, nil, nil, nil, nil, 4],
                [4, 4, nil, nil, nil, nil, 2, 3],
                [3, nil, nil, nil, nil, nil, 3],
                [3, 3, nil, nil, nil, nil, 3, 1],
                [2, nil, nil, nil, nil, nil, 2],
                [2, 1, nil, nil, nil, nil, 1, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, nil, nil, nil, nil, 7, 7],
                [1, nil, nil, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 2, 3],
                [5, 5, nil, nil, nil, 5, 5],
                [5, 1, nil, nil, nil, nil, 1, 1],
                [6, 3, nil, nil, nil, 3, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 345,
            rows: [
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [3, nil, nil, nil, nil, nil, nil],
                [nil, 3, 3, 2, 2, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2],
                [nil, 2, 2, 2, 2, 2, 5, nil],
                [nil, nil, nil, nil, nil, nil, 5],
                [nil, nil, nil, nil, nil, nil, 5, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, 1, nil],
                [nil, 1, 1, 1, 6, 6, nil],
                [nil, 6, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [7, nil, nil, nil, nil, nil, nil],
                [nil, 4, 4, 6, 3, 4, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 346,
            rows: [
                [nil, nil, 5, nil, nil, nil, nil, nil],
                [nil, 5, 5, nil, nil, nil, nil],
                [nil, nil, 5, 5, nil, nil, nil, nil],
                [nil, 1, 1, 1, nil, nil, nil],
                [nil, nil, 3, 3, nil, nil, nil, nil],
                [nil, 3, 3, 3, nil, nil, nil],
                [3, 3, 3, 3, 3, 1, 1, nil],
                [2, 2, 2, 2, 2, 2, nil],
                [2, 4, 4, 4, 4, 4, 1, nil],
                [1, 1, 1, 1, 1, 1, nil],
                [1, 1, 2, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 2, 2, 2, 2, 2, 6, 6],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 347,
            rows: [
                [1, nil, 1, 1, 1, 1, nil, 1],
                [1, nil, nil, nil, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, nil, 2, nil, 2, nil, 6],
                [6, nil, 6, nil, 6, nil, 4],
                [nil, 2, nil, 1, nil, 1, nil, 1],
                [4, nil, 4, nil, 3, nil, 3],
                [nil, 3, nil, 3, nil, 3, nil, 3],
                [3, nil, 3, nil, 3, nil, 3],
                [nil, 3, nil, 1, nil, 1, nil, 1],
                [5, nil, 5, nil, 5, nil, 5],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 348,
            rows: [
                [nil, nil, 1, 4, 4, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 3, 3, nil, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 3, 2, 2, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, 5, nil, nil],
                [nil, nil, 5, 2, 2, nil, nil],
                [nil, nil, 2, 2, 2, 2, nil, nil],
                [nil, nil, 2, 2, 6, nil, nil],
                [nil, nil, 4, 4, 4, 4, nil, nil],
                [nil, nil, 2, 2, 7, nil, nil],
                [nil, nil, 2, 2, 3, 2, nil, nil],
                [nil, nil, 2, 5, 1, nil, nil],
            ], backgroundColor: .yellow, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 349,
            rows: [
                [nil, nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, 1, nil, nil, nil, nil, nil, nil],
                [1, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 1, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, 2, nil],
                [nil, 1, 1, 1, 1, 3, nil],
                [nil, 3, 3, 3, 3, 3, 3, nil],
                [nil, 3, 1, 1, 1, 1, nil],
                [nil, 1, 1, 4, 4, 4, 5, nil],
                [nil, 1, 1, 4, 4, 4, nil],
                [nil, 4, 5, 5, 5, 5, 5, nil],
                [nil, 1, 6, 1, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 350,
            rows: [
                [nil, nil, 3, 3, 3, nil, nil, nil],
                [nil, 3, nil, nil, 3, nil, nil],
                [nil, nil, 3, 6, 1, 1, 1, nil],
                [nil, 2, 2, 2, nil, nil, 2],
                [nil, nil, 2, 2, 1, 1, 1, nil],
                [nil, 1, 2, 2, nil, nil, 2],
                [nil, 2, nil, nil, 2, 2, 2, nil],
                [nil, 1, 1, 1, 6, 1, nil],
                [nil, 1, nil, nil, 1, 1, 1, nil],
                [nil, 1, 4, 4, 4, 3, nil],
                [nil, nil, 3, 6, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 6, 7, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 351,
            rows: [
                [2, 2, nil, nil, nil, nil, 2, 2],
                [2, nil, nil, nil, nil, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 2],
                [2, nil, 2, 2, 2, nil, 2],
                [2, nil, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 3, 4, nil, 4],
                [4, 3, 5, 5, 1, 1, 1, 1],
                [1, 1, 1, nil, 1, 3, 1],
                [1, 1, 3, 1, 1, 1, 1, 1],
                [1, 1, 1, nil, 1, 1, 1],
                [nil, 1, 7, nil, nil, 3, 3, nil],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, 3, 3, nil, nil, 3, 3, nil],
                [nil, nil, 4, 4, 6, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 352,
            rows: [
                [nil, nil, 1, nil, nil, 1, 1, nil],
                [nil, 4, 5, nil, nil, 1, 2],
                [2, nil, nil, 2, 1, 1, nil, nil],
                [3, 3, nil, 3, nil, nil, nil],
                [1, nil, nil, 1, 1, 1, nil, nil],
                [1, 6, nil, 6, nil, nil, nil],
                [3, nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, nil, nil, 1, nil, 1],
                [1, nil, 5, 5, 3, 3, 1, nil],
                [nil, 1, nil, nil, 7, nil, 4],
                [nil, 4, 4, nil, nil, nil, 4, nil],
                [nil, nil, 4, nil, nil, nil, nil],
                [nil, 1, 1, nil, nil, nil, 1, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 353,
            rows: [
                [nil, nil, nil, nil, 5, 2, 2, nil],
                [nil, nil, 2, 1, 1, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, nil, 1, 1, 1, 1, 1, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, 3, 3, 3, 6, 6, nil, nil],
                [6, 1, 1, 1, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil, nil],
                [2, 2, 2, 4, 4, nil, nil],
                [4, 4, 4, 5, 5, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [5, 5, 3, 3, 2, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 354,
            rows: [
                [1, 1, nil, nil, nil, nil, 1, 1],
                [1, 2, nil, nil, nil, 2, 2],
                [2, 2, nil, nil, nil, nil, 2, 2],
                [5, nil, nil, nil, nil, nil, 5],
                [5, 5, nil, nil, nil, nil, 5, 5],
                [5, nil, nil, nil, nil, nil, 5],
                [2, 2, nil, nil, nil, nil, 2, 4],
                [4, 4, 4, 1, 1, 1, 1],
                [1, 1, nil, nil, nil, nil, 1, 2],
                [2, 2, 2, 2, 1, 6, 1],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, 2, 3, 3, 3, 3, nil],
                [nil, 3, nil, 3, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 355,
            rows: [
                [1, nil, nil, nil, nil, nil, nil, 1],
                [1, nil, 1, 2, 2, nil, 2],
                [nil, 2, 2, nil, nil, 2, 2, nil],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 2, 2, nil, nil, 1, 5, nil],
                [nil, 5, nil, nil, nil, 5, nil],
                [nil, 5, 5, nil, nil, 6, 6, nil],
                [nil, 1, nil, nil, nil, 1, nil],
                [nil, 1, 4, nil, nil, 3, 3, nil],
                [nil, 3, nil, nil, nil, 3, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, nil, 1, nil, nil, 1, nil, nil],
                [nil, nil, 1, 7, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 356,
            rows: [
                [3, 3, 7, 7, 4, 4, 3, 3],
                [nil, nil, nil, nil, 3, nil, nil],
                [nil, nil, nil, 3, 3, nil, nil, nil],
                [nil, nil, 3, nil, nil, nil, nil],
                [nil, nil, nil, 3, 1, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [5, 5, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, 1, nil, nil],
                [1, 1, 1, 1, 2, 2, 2, 2],
                [nil, nil, nil, nil, 1, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 2, nil, nil, nil, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [nil, nil, 1, nil, nil, nil, nil],
                [1, 1, 6, 2, 2, 2, 2, 2],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 357,
            rows: [
                [nil, 3, 3, 1, 7, 7, 3, nil],
                [3, nil, nil, nil, nil, nil, 3],
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [2, 4, 4, 4, 2, 2, 2],
                [nil, 2, nil, nil, nil, nil, 2, nil],
                [2, 2, 1, 5, 1, 1, 5],
                [nil, 5, 1, 1, 1, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 358,
            rows: [
                [nil, 3, 3, nil, nil, 3, 1, nil],
                [1, 2, nil, nil, 2, 2, nil],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [1, 1, nil, nil, 1, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [nil, 1, nil, 4, nil, 4, nil],
                [3, nil, 2, nil, 2, nil, 5, nil],
                [nil, 4, nil, 4, nil, 4, nil],
                [4, nil, 5, nil, 5, nil, 2, nil],
                [nil, 2, nil, 2, nil, 3, nil],
                [2, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, 2, nil, 3, nil],
                [3, nil, 3, nil, 7, nil, 7, nil],
                [nil, 1, nil, 3, nil, 3, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 359,
            rows: [
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, nil, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, 1, 1],
                [nil, 1, nil, nil, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, 2, 2],
                [nil, 2, nil, nil, nil, 2, nil],
                [nil, 2, 2, nil, nil, 2, nil, nil],
                [2, 3, 3, nil, 3, nil, nil],
                [nil, 3, 3, nil, nil, 1, nil, nil],
                [1, 1, 1, nil, 1, nil, nil],
                [1, nil, 5, 5, 5, 6, nil, 1],
                [nil, 1, nil, 1, nil, 1, 4],
                [4, nil, 5, 5, 5, 4, nil, 4],
                [nil, 4, nil, 4, nil, 6, 7],
                [nil, 7, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 4
        ),
        LevelTemplate(
            levelNumber: 360,
            rows: [
                [1, nil, nil, 1, 1, nil, nil, 1],
                [1, 1, 1, 1, 1, 1, 1],
                [nil, 5, 5, nil, nil, 2, 2, nil],
                [3, nil, 3, 3, 3, nil, 2],
                [nil, 2, 2, nil, nil, 4, 4, nil],
                [1, nil, 1, 1, 1, nil, 1],
                [nil, 5, 2, nil, nil, 2, 2, nil],
                [nil, nil, 2, 2, 3, nil, nil],
                [nil, 3, 6, nil, nil, 2, 2, nil],
                [nil, nil, 2, 2, 3, nil, nil],
                [nil, 3, 3, 3, 4, 4, 4, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 4, 7, 1, 1, 1, 5, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
    ]
}
