// SPDX-License-Identifier: CC-BY-NC-4.0

import Foundation

enum LevelTemplatesBatch49 {
    static let levels: [LevelTemplate] = [
        LevelTemplate(
            levelNumber: 961,
            rows: [
                [nil, 1, nil, nil, nil, 3, nil, 3],
                [nil, nil, nil, 3, nil, 1, 1],
                [1, 1, 1, nil, 1, 1, nil, 6],
                [2, 2, 2, nil, 2, 2, nil],
                [nil, nil, nil, 2, nil, 2, nil, 2],
                [nil, nil, 2, 2, 2, nil, nil],
                [2, 5, 5, 5, nil, nil, nil, nil],
                [5, 5, 1, 1, nil, 1, 1],
                [nil, 1, 1, 1, nil, 1, 1, 4],
                [4, 4, nil, nil, nil, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil, 1],
                [nil, nil, 1, nil, 1, 1, nil],
                [1, nil, 1, nil, nil, 1, 2, nil],
                [nil, 2, nil, nil, nil, 2, 3],
                [nil, nil, 3, nil, 6, 6, nil, nil],
                [nil, nil, nil, 6, 3, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 962,
            rows: [
                [nil, nil, nil, nil, 1, 1, 1, nil],
                [nil, 1, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, nil, 1, nil],
                [nil, 3, nil, 3, 3, 1, nil],
                [nil, 2, nil, 2, nil, nil, nil, nil],
                [nil, 2, nil, 6, 1, 1, nil],
                [nil, 1, nil, nil, nil, 1, 1, nil],
                [nil, 1, 1, 1, 1, nil, nil],
                [nil, nil, 1, nil, 1, 1, nil, nil],
                [nil, 6, 6, 2, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 5, 5, 2, 2, 2, nil],
                [nil, 2, 5, 1, 3, 3, 4, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, nil, 4, nil, 4, nil, 4],
                [4, nil, 1, nil, 1, nil, 2],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 963,
            rows: [
                [4, nil, nil, 4, 4, 4, nil, nil],
                [6, nil, 6, nil, nil, nil, 1],
                [1, nil, 1, nil, 1, nil, nil, 1],
                [1, 1, 1, nil, 1, 1, nil],
                [nil, 4, 4, 4, nil, 4, nil, nil],
                [nil, 4, 2, nil, 2, 2, nil],
                [2, 2, 2, nil, 3, 3, nil, nil],
                [nil, nil, nil, 3, nil, 3, 3],
                [3, nil, 1, 1, 1, 1, 1, nil],
                [1, 1, 1, nil, nil, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [nil, nil, nil, 1, 1, 1, 1],
                [1, nil, 1, 1, nil, nil, nil, nil],
                [3, nil, 3, 3, 3, nil, nil],
                [nil, nil, nil, 5, 5, nil, 2, nil],
                [nil, nil, 2, nil, 2, 2, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 964,
            rows: [
                [3, 3, 3, 3, nil, 3, 3, nil],
                [nil, 3, 1, nil, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil, nil],
                [1, 1, 1, 1, nil, 1, 1],
                [1, nil, nil, 1, 1, nil, 1, nil],
                [1, 1, 1, 1, nil, 1, 1],
                [nil, 1, nil, nil, 1, 1, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, nil, 1, nil, 1, nil, 2],
                [nil, nil, nil, 2, 2, 2, 2],
                [nil, nil, 2, nil, nil, 2, 2, nil],
                [2, 2, nil, 2, 5, 5, 5],
                [5, nil, nil, 6, 6, nil, nil, 6],
                [nil, nil, 4, nil, nil, 4, 1],
                [nil, 1, 1, 1, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, 5, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 965,
            rows: [
                [nil, nil, nil, 2, 2, 2, 2, nil],
                [nil, 2, 1, nil, 1, nil, nil],
                [nil, 1, nil, 1, 1, 1, 1, nil],
                [nil, nil, nil, 2, 2, 2, nil],
                [nil, 2, 1, nil, 1, 1, nil, nil],
                [nil, 4, 4, 4, 4, 4, nil],
                [nil, nil, 4, 4, nil, nil, nil, nil],
                [nil, 4, 4, 4, 3, 3, nil],
                [nil, 5, 5, nil, nil, nil, 3, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, 2, 2, 2, nil, nil, nil, nil],
                [nil, nil, 3, 3, 1, nil, nil],
                [nil, 1, nil, 1, 1, 1, 3, nil],
                [nil, 3, 3, 3, 3, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 6, 6, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 966,
            rows: [
                [nil, nil, nil, 1, 1, nil, 1, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, 1, 1, nil, nil, 1, 3, nil],
                [nil, nil, nil, 3, 3, nil, nil],
                [nil, nil, 3, 3, nil, 3, 3, nil],
                [nil, 1, nil, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, 1, nil, 2, nil, nil],
                [nil, 2, nil, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 4, 4, 1, 5, nil],
                [nil, 5, 5, 1, 1, 1, nil],
                [nil, 1, 1, 4, 4, 4, 4, nil],
                [nil, 4, 1, 1, 1, 1, nil],
                [nil, 1, nil, 1, nil, 1, nil, 1],
                [1, nil, 6, nil, 3, nil, 6],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 967,
            rows: [
                [nil, 1, nil, nil, nil, nil, 1, nil],
                [nil, 1, 1, nil, 5, 5, nil],
                [nil, nil, nil, nil, 5, 3, 3, nil],
                [nil, nil, 3, nil, 4, 4, nil],
                [nil, 4, nil, 6, 6, 6, 1, nil],
                [nil, nil, 2, nil, 2, 2, nil],
                [nil, nil, 2, nil, 2, 2, 2, nil],
                [nil, 2, 2, nil, 2, 2, nil],
                [nil, nil, nil, nil, nil, 2, nil, nil],
                [nil, 2, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 2, nil],
                [nil, 2, 1, 1, 1, 1, 4, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 968,
            rows: [
                [nil, nil, 1, nil, 1, 1, nil, nil],
                [nil, 1, nil, 1, nil, nil, 1],
                [1, nil, 1, nil, nil, 1, nil, 1],
                [1, 1, nil, nil, 1, nil, 1],
                [nil, 1, 1, nil, nil, 1, 1, nil],
                [nil, 1, nil, nil, nil, nil, 1],
                [3, 3, 3, nil, nil, 3, 3, 3],
                [3, nil, 3, nil, 3, nil, nil],
                [nil, nil, nil, nil, 3, 6, 6, 6],
                [5, 5, 5, 5, nil, 5, nil],
                [2, nil, 2, 1, nil, nil, 2, 2],
                [1, nil, nil, 4, 4, 2, nil],
                [nil, 2, 3, 3, nil, 2, nil, 2],
                [2, 3, 2, 2, 2, 4, 1],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 969,
            rows: [
                [nil, 2, nil, 2, nil, nil, nil, 2],
                [2, 2, nil, nil, nil, nil, 2],
                [nil, 2, 2, 2, nil, 2, nil, 2],
                [2, nil, nil, nil, 2, nil, 1],
                [1, 1, nil, 1, 1, nil, 1, 1],
                [1, nil, 1, 1, 1, 1, 2],
                [3, 3, nil, 3, 3, 2, 2, 1],
                [nil, nil, 1, nil, 1, nil, 1],
                [1, 1, 1, 1, 1, 1, 1, nil],
                [1, 1, 1, 1, nil, 4, nil],
                [4, nil, 4, nil, nil, nil, nil, nil],
                [nil, 4, 2, 2, nil, nil, nil],
                [2, nil, nil, nil, nil, 2, nil, nil],
                [nil, nil, 2, 2, nil, 6, 6],
                [6, nil, nil, 6, 2, 2, 2, 4],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 970,
            rows: [
                [nil, 2, 2, nil, nil, nil, 2, nil],
                [nil, nil, 2, 2, nil, 2, nil],
                [nil, 2, 2, 2, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, 2, nil],
                [nil, 2, 2, 2, nil, nil, 4, nil],
                [nil, 4, 4, nil, nil, 4, nil],
                [nil, 4, 4, 4, 4, nil, 1, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, nil, 5, 1, nil, nil, nil, nil],
                [nil, 1, 1, 6, nil, nil, nil],
                [nil, nil, nil, 6, 3, 3, nil, nil],
                [nil, nil, 1, 1, nil, 5, nil],
                [nil, 5, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 6, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 971,
            rows: [
                [6, nil, nil, nil, nil, 6, 3, nil],
                [3, nil, 3, 2, nil, nil, nil],
                [2, 2, nil, nil, 2, nil, 2, nil],
                [nil, nil, nil, nil, nil, 2, 2],
                [nil, 2, 2, nil, nil, nil, 2, nil],
                [nil, 2, nil, nil, 2, 2, nil],
                [3, 3, nil, 3, 3, 3, 3, 3],
                [1, 1, nil, 4, 4, 4, nil],
                [nil, 1, 1, 1, nil, nil, nil, 1],
                [nil, nil, 1, 1, 1, 1, 1],
                [nil, 1, 4, 4, nil, nil, 1, 1],
                [5, 5, 5, 5, 1, 1, nil],
                [1, nil, 1, nil, 1, nil, 1, nil],
                [1, 1, nil, 1, nil, 1, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 972,
            rows: [
                [nil, 1, 1, nil, 1, 1, 1, nil],
                [1, 1, 1, nil, nil, nil, 1],
                [1, nil, 2, 2, 2, 2, nil, 2],
                [nil, 2, nil, 2, 2, nil, 2],
                [nil, nil, 1, 5, nil, nil, 5, nil],
                [nil, 5, 3, nil, 1, 1, nil],
                [1, nil, nil, nil, nil, nil, 1, 1],
                [nil, 1, 3, nil, nil, nil, nil],
                [3, 3, nil, nil, nil, nil, 3, 3],
                [3, nil, 3, 3, nil, nil, 1],
                [nil, nil, 2, nil, 1, nil, 4, 4],
                [nil, nil, nil, 4, nil, 4, 3],
                [nil, 3, 3, nil, 4, 4, 4, nil],
                [nil, 1, nil, nil, 6, nil, nil],
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, 1, 1, 6, 1, 1, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 973,
            rows: [
                [nil, nil, nil, 1, 1, 1, 1, nil],
                [nil, nil, 3, nil, nil, nil, 3],
                [3, nil, 3, nil, nil, 3, 3, 3],
                [nil, nil, 3, 3, 3, nil, nil],
                [nil, nil, 2, 2, nil, 2, nil, 2],
                [nil, 2, nil, 2, nil, 2, 2],
                [2, nil, 2, 2, nil, nil, 2, 2],
                [nil, 2, nil, 2, 2, nil, nil],
                [nil, nil, nil, nil, 2, 1, nil, 1],
                [nil, 1, nil, 1, 1, 1, nil],
                [nil, 4, nil, nil, 4, 4, nil, nil],
                [nil, nil, nil, 4, nil, 4, nil],
                [nil, nil, nil, nil, 1, 1, nil, 1],
                [5, nil, 6, nil, 1, 1, 5],
                [5, 5, nil, nil, 5, nil, 1, 1],
                [1, 1, 1, 1, 1, 1, 4],
            ], backgroundColor: .purple, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 974,
            rows: [
                [nil, 4, 4, 4, nil, 4, 1, nil],
                [1, 1, 1, nil, nil, 6, nil],
                [6, 6, 6, 1, nil, 1, 1, 2],
                [2, 2, nil, nil, nil, 2, 2],
                [2, 2, 2, nil, 2, 2, nil, nil],
                [2, 2, nil, nil, 1, nil, 3],
                [nil, 1, 3, 3, 1, 1, nil, nil],
                [1, nil, 1, nil, 1, 1, 1],
                [1, 1, 1, 1, 1, nil, nil, nil],
                [nil, nil, 1, nil, 1, 1, 1],
                [1, 1, 3, 3, 5, 5, 5, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [1, 1, 1, 1, 1, 1, 1, 1],
                [nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .blue, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 975,
            rows: [
                [nil, nil, 1, nil, 1, nil, nil, nil],
                [nil, 6, nil, nil, nil, 6, nil],
                [nil, 6, nil, 1, 1, nil, nil, nil],
                [nil, 3, 3, nil, nil, 1, nil],
                [nil, 2, 2, 2, nil, 2, 2, nil],
                [nil, 1, 1, nil, nil, nil, nil],
                [nil, nil, 1, nil, 1, 1, nil, nil],
                [nil, 1, 1, nil, nil, 1, nil],
                [nil, nil, nil, 2, nil, 1, 1, nil],
                [nil, nil, 1, 1, 1, 5, nil],
                [nil, 5, 1, 1, 1, 2, 2, nil],
                [nil, 2, 2, 2, 2, 1, nil],
                [nil, 4, 4, 4, 4, 4, 4, nil],
                [nil, 4, 4, 1, 1, 3, nil],
                [nil, 3, 3, 3, 3, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 976,
            rows: [
                [1, 1, 1, 1, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [1, 1, nil, 1, 1, nil, 2, nil],
                [nil, nil, nil, nil, 2, 1, nil],
                [nil, nil, nil, 1, 1, nil, nil, nil],
                [1, 1, nil, 1, nil, nil, 1],
                [nil, 1, nil, 2, 2, 2, 2, 2],
                [2, nil, nil, nil, 2, 3, nil],
                [3, nil, 2, 2, 2, nil, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
                [2, 2, 2, 2, 1, 1, 1, nil],
                [1, nil, 1, 1, nil, 3, nil],
                [3, 3, nil, 3, nil, 3, 3, 3],
                [3, nil, 3, nil, nil, nil, 6],
                [nil, 4, 1, nil, 1, 4, nil, nil],
                [nil, 4, nil, 6, 6, 6, nil],
            ], backgroundColor: .orange, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 977,
            rows: [
                [nil, nil, nil, nil, nil, nil, nil, nil],
                [nil, nil, 3, nil, 1, 1, nil],
                [nil, nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, nil, nil, nil, 1, 1],
                [nil, 1, nil, 1, nil, 1, nil, nil],
                [nil, 1, 1, 1, 6, nil, nil],
                [6, 6, nil, 3, nil, 3, 3, 4],
                [1, 1, nil, nil, 1, nil, 1],
                [1, nil, 1, 1, 1, 1, 2, 2],
                [nil, 2, nil, 2, 4, nil, 4],
                [nil, 1, 1, nil, nil, 1, 1, 1],
                [nil, 1, 1, 1, 1, nil, 1],
                [nil, 1, 1, 2, 2, 2, 2, 2],
                [nil, 4, 4, 4, 2, 4, 4],
                [nil, nil, 4, 5, 3, 2, 2, nil],
                [nil, nil, nil, nil, nil, nil, nil],
            ], backgroundColor: .pink, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 978,
            rows: [
                [nil, nil, 1, nil, 1, 4, 4, nil],
                [nil, nil, nil, nil, nil, 4, nil],
                [nil, nil, 4, 4, 4, 4, 4, nil],
                [nil, 2, 2, nil, nil, 2, nil],
                [nil, nil, 2, 2, 2, nil, 2, nil],
                [nil, 2, 2, 1, 1, nil, nil],
                [nil, nil, 1, nil, 1, 1, 1, nil],
                [nil, 6, 3, nil, 3, nil, nil],
                [nil, 3, nil, 3, nil, 3, 3, nil],
                [nil, 3, 3, 1, 1, nil, nil],
                [nil, nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, nil, 1, 1, 1, nil],
                [nil, 1, 1, nil, 1, 2, 2, nil],
                [nil, nil, nil, 2, 6, 6, nil],
                [nil, 1, 1, 1, 1, nil, 1, nil],
                [nil, 1, 2, 2, 5, 5, nil],
            ], backgroundColor: .red, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 979,
            rows: [
                [nil, 3, 3, 3, nil, 3, nil, nil],
                [nil, 3, 3, 1, nil, 4, nil],
                [nil, nil, 4, nil, 4, nil, 4, nil],
                [nil, 4, 4, 1, 1, nil, nil],
                [nil, nil, 1, 1, 2, nil, 2, nil],
                [nil, 1, nil, 3, 3, 3, nil],
                [nil, nil, 2, nil, 2, nil, 2, nil],
                [nil, 2, nil, nil, 2, nil, nil],
                [nil, 2, nil, 2, nil, 2, nil, nil],
                [nil, 2, 2, 2, 2, 2, nil],
                [nil, 2, 2, 1, nil, nil, 1, nil],
                [nil, 1, 1, 1, nil, 1, nil],
                [nil, nil, nil, 1, nil, 1, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 5, nil, 5, 4, 4, 4, nil],
                [nil, 1, 1, 6, 6, 1, nil],
            ], backgroundColor: .brown, potentialPotatoCount: 3
        ),
        LevelTemplate(
            levelNumber: 980,
            rows: [
                [nil, 1, 1, 1, nil, nil, nil, nil],
                [nil, nil, 1, 1, 1, nil, nil],
                [nil, 1, nil, 1, nil, nil, 1, nil],
                [nil, nil, nil, 1, nil, 2, nil],
                [nil, 2, nil, 2, 2, 2, 2, nil],
                [nil, 2, 2, 2, nil, nil, nil],
                [nil, 3, nil, nil, nil, 3, nil, nil],
                [nil, 1, nil, 1, 1, 1, nil],
                [nil, 1, nil, nil, nil, 1, nil, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 2, nil, 2, 2, 6, 1, nil],
                [nil, 1, 1, 1, 1, 1, nil],
                [nil, 1, 1, 1, 1, 3, 3, nil],
                [nil, 3, 3, 3, 3, 3, nil],
                [nil, 3, 3, 6, 6, 4, 4, nil],
                [nil, 4, 4, 4, 5, 5, nil],
            ], backgroundColor: .green, potentialPotatoCount: 3
        ),
    ]
}
